# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('satellite', ['internet', 'network', 'propagation', 'antenna', 'csma'])
    module.source = [
        'model/geo-coordinate.cc',
        'model/cbr-application.cc',
        'model/satellite-antenna-gain-pattern.cc',
        'model/satellite-antenna-gain-pattern-container.cc',
        'model/satellite-arp-cache.cc',
        'model/satellite-mac.cc',
        'model/satellite-channel.cc',
        'model/satellite-channel-fading-trace.cc',
        'model/satellite-channel-fading-trace-container.cc',
        'model/satellite-net-device.cc',
        'model/ideal-net-device.cc',
        'model/satellite-geo-net-device.cc',
        'model/satellite-phy.cc',
        'model/satellite-phy-tx.cc',               
        'model/satellite-phy-rx.cc',
        'model/satellite-phy-rx-carrier.cc',
        'model/satellite-phy-rx-carrier-conf.cc',
        'model/satellite-link-results.cc',
        'model/satellite-look-up-table.cc',
        'model/satellite-signal-parameters.cc',
        'model/virtual-channel.cc',
        'model/satellite-beam-scheduler.cc',
        'model/satellite-control-message.cc',
        'model/satellite-mac-tag.cc',       
        'model/satellite-ncc.cc',
        'model/satellite-ut-mac.cc',
        'model/satellite-mobility-model.cc',
        'model/satellite-constant-position-mobility-model.cc',
        'model/satellite-position-allocator.cc',
        'model/satellite-propagation-delay-model.cc',
        'model/satellite-interference.cc',
        'model/satellite-per-packet-interference.cc',
        'model/satellite-constant-interference.cc',
        'model/satellite-traced-interference.cc',
        'model/satellite-free-space-loss.cc',
        'model/satellite-fading.cc',
        'model/satellite-fader.cc',
        'model/satellite-fader-conf.cc',
        'model/satellite-markov-conf.cc',
        'model/satellite-rayleigh-conf.cc',
        'model/satellite-loo-conf.cc',
        'model/satellite-fading-container.cc',
        'model/satellite-markov-model.cc',
        'model/satellite-loo-model.cc',
        'model/satellite-rayleigh-model.cc',
        'model/satellite-fading-oscillator.cc',
        'model/satellite-mobility-observer.cc',
        'helper/satellite-helper.cc',
        'helper/satellite-beam-helper.cc',
        'helper/satellite-user-helper.cc',
        'helper/satellite-ut-helper.cc',
        'helper/satellite-gw-helper.cc',
        'helper/satellite-geo-helper.cc',
        'helper/satellite-conf.cc',
        'helper/satellite-frame-conf.cc',
        'helper/satellite-wave-form-conf.cc',
        'helper/satellite-beam-user-info.cc',
        'helper/satellite-superframe-sequence.cc',
        'helper/cbr-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('satellite')
    module_test.source = [
        'test/geo-coordinate-test.cc',
        'test/satellite-fading-trace-test.cc',
        'test/performance-memory-test.cc',
        'test/cbr-test.cc',
        'test/link-results-test.cc',
        'test/satellite-simple-p2p.cc',
        'test/satellite-scenario-creation.cc',
        'test/satellite-mobility-test.cc',
        'test/satellite-interference-test.cc',
        'test/satellite-fsl-test.cc',
        'test/satellite-antenna-pattern-test.cc',
        'test/satellite-mobility-observer-test.cc',
        ]

    headers = bld.new_task_gen(features=['ns3header'])
    headers.module = 'satellite'
    headers.source = [
    	'model/satellite-utils.h',
        'model/geo-coordinate.h',
        'model/cbr-application.h',
        'model/satellite-antenna-gain-pattern.h',
        'model/satellite-antenna-gain-pattern-container.h',        
        'model/satellite-arp-cache.h',
        'model/satellite-mac.h',
        'model/satellite-channel.h',
        'model/satellite-channel-fading-trace.h',
        'model/satellite-channel-fading-trace-container.h',
        'model/satellite-net-device.h',
        'model/ideal-net-device.h',
        'model/satellite-geo-net-device.h',
        'model/satellite-phy.h',
        'model/satellite-phy-tx.h',               
        'model/satellite-phy-rx.h',
        'model/satellite-phy-rx-carrier.h',
		'model/satellite-phy-rx-carrier-conf.h',
        'model/satellite-link-results.h',
        'model/satellite-look-up-table.h',
        'model/satellite-signal-parameters.h',
        'model/virtual-channel.h',
        'model/satellite-beam-scheduler.h',
        'model/satellite-control-message.h',
        'model/satellite-mac-tag.h',        
        'model/satellite-ncc.h',
        'model/satellite-ut-mac.h',
        'model/satellite-mobility-model.h',
        'model/satellite-constant-position-mobility-model.h',
        'model/satellite-position-allocator.h',
        'model/satellite-propagation-delay-model.h',
        'model/satellite-interference.h',
        'model/satellite-per-packet-interference.h',
        'model/satellite-constant-interference.h',
        'model/satellite-traced-interference.h',
        'model/satellite-free-space-loss.h',       
        'model/satellite-fading.h',
        'model/satellite-fader.h',
        'model/satellite-fader-conf.h',
        'model/satellite-markov-conf.h',
        'model/satellite-rayleigh-conf.h',
        'model/satellite-loo-conf.h',
        'model/satellite-fading-container.h',
        'model/satellite-markov-model.h',
        'model/satellite-loo-model.h',
        'model/satellite-rayleigh-model.h',
        'model/satellite-fading-oscillator.h',
        'model/satellite-mobility-observer.h',
        'helper/satellite-helper.h',
        'helper/satellite-beam-helper.h',
		'helper/satellite-user-helper.h',
		'helper/satellite-ut-helper.h',
        'helper/satellite-gw-helper.h',
        'helper/satellite-geo-helper.h',
        'helper/satellite-conf.h',
        'helper/satellite-frame-conf.h',
        'helper/satellite-wave-form-conf.h',
        'helper/satellite-beam-user-info.h',
        'helper/satellite-superframe-sequence.h',
        'helper/cbr-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.add_subdirs('examples')

    # bld.ns3_python_bindings()

