# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('satellite-example', ['satellite'])
    obj.source = 'satellite-example.cc'
    
    obj = bld.create_ns3_program('cbr-example', ['satellite','point-to-point', 'applications'])
    obj.source = 'cbr-example.cc'
    

