# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('sat-cbr-example', ['satellite'])
    obj.source = 'sat-cbr-example.cc'
    
    obj = bld.create_ns3_program('sat-cbr-larger-example', ['satellite', 'traffic', 'flow-monitor'])
    obj.source = 'sat-cbr-larger-example.cc'
    
    obj = bld.create_ns3_program('simple-scenario-p2p', ['satellite', 'netanim', 'flow-monitor'])
    obj.source = 'simple-scenario-p2p.cc'
    
    obj = bld.create_ns3_program('larger-scenario-p2p', ['satellite', 'netanim', 'flow-monitor'])
    obj.source = 'larger-scenario-p2p.cc'

    obj = bld.create_ns3_program('link-results-plot', ['satellite', 'tools'])
    obj.source = 'link-results-plot.cc'
    
    obj = bld.create_ns3_program('markov-logic-example', ['satellite'])
    obj.source = 'markov-logic-example.cc'

    obj = bld.create_ns3_program('rayleigh-example', ['satellite'])
    obj.source = 'rayleigh-example.cc'

    obj = bld.create_ns3_program('loo-example', ['satellite'])
    obj.source = 'loo-example.cc'

    obj = bld.create_ns3_program('markov-fading-trace-example', ['satellite'])
    obj.source = 'markov-fading-trace-example.cc'
    
    obj = bld.create_ns3_program('sat-link-budget-example', ['satellite'])
    obj.source = 'sat-link-budget-example.cc'
    
    obj = bld.create_ns3_program('sat-http-example', ['satellite', 'traffic'])
    obj.source = 'sat-http-example.cc'

    obj = bld.create_ns3_program('sat-nrtv-example', ['satellite', 'traffic'])
    obj.source = 'sat-nrtv-example.cc'

    obj = bld.create_ns3_program('environmental-variables-example', ['satellite'])
    obj.source = 'environmental-variables-example.cc'

    obj = bld.create_ns3_program('trace-output-example', ['satellite'])
    obj.source = 'trace-output-example.cc'

    obj = bld.create_ns3_program('trace-input-interference-example', ['satellite'])
    obj.source = 'trace-input-interference-example.cc'    
    
    obj = bld.create_ns3_program('trace-input-fading-example', ['satellite'])
    obj.source = 'trace-input-fading-example.cc'
    
    obj = bld.create_ns3_program('trace-input-external-fading-example', ['satellite'])
    obj.source = 'trace-input-external-fading-example.cc'

    obj = bld.create_ns3_program('trace-input-rx-power-example', ['satellite'])
    obj.source = 'trace-input-rx-power-example.cc'
    
    obj = bld.create_ns3_program('sat-onoff-example', ['satellite'])
    obj.source = 'sat-onoff-example.cc'    