SNS3
SatPerPacketFwdLinkUserTestCase Class Reference
Public Member Functions
SatPerPacketFwdLinkUserTestCase ()
SatPerPacketFwdLinkUserTestCase (std::string name, SatEnums::FadingModel_t fading, bool dummyFrames)
SatPerPacketFwdLinkUserTestCase (std::string name, SatEnums::FadingModel_t fading, bool dummyFrames, StringValue ival1, UintegerValue pSize1, StringValue ival2, UintegerValue pSize2)
virtual ~SatPerPacketFwdLinkUserTestCase ()
Public Member Functions inherited from SatPerPacketBaseTestCase
SatPerPacketBaseTestCase ()
SatPerPacketBaseTestCase (std::string name, std::string extName, SatEnums::FadingModel_t fading, bool dummyFrames, StringValue ival1, UintegerValue pSize1, StringValue ival2, UintegerValue pSize2)
virtual ~SatPerPacketBaseTestCase ()
Private Member Functions
virtual void DoRun (void)
Additional Inherited Members
Protected Member Functions inherited from SatPerPacketBaseTestCase
void InitOutput (bool figureOutput)
void PrintTraceInfo ()
Protected Attributes inherited from SatPerPacketBaseTestCase
bool m_dummyFrames
std::string m_extName
SatEnums::FadingModel_t m_fading
StringValue m_Interval1
StringValue m_Interval2
UintegerValue m_PackageSize1
UintegerValue m_PackageSize2
Detailed Description
Definition at line 211 of file satellite-per-packet-if-test.cc.
Constructor & Destructor Documentation
SatPerPacketFwdLinkUserTestCase() [1/3]
SatPerPacketFwdLinkUserTestCase::SatPerPacketFwdLinkUserTestCase ()
Definition at line 232 of file satellite-per-packet-if-test.cc.
SatPerPacketFwdLinkUserTestCase() [2/3]
SatPerPacketFwdLinkUserTestCase::SatPerPacketFwdLinkUserTestCase (std::string name, SatEnums::FadingModel_t fading, bool dummyFrames)
Definition at line 244 of file satellite-per-packet-if-test.cc.
SatPerPacketFwdLinkUserTestCase() [3/3]
SatPerPacketFwdLinkUserTestCase::SatPerPacketFwdLinkUserTestCase (std::string name, SatEnums::FadingModel_t fading, bool dummyFrames, StringValue ival1, UintegerValue pSize1, StringValue ival2, UintegerValue pSize2)
Definition at line 258 of file satellite-per-packet-if-test.cc.
~SatPerPacketFwdLinkUserTestCase()
SatPerPacketFwdLinkUserTestCase::~SatPerPacketFwdLinkUserTestCase () virtual
Definition at line 276 of file satellite-per-packet-if-test.cc.
Member Function Documentation
DoRun()
void SatPerPacketFwdLinkUserTestCase::DoRun (void) private virtual
Implements SatPerPacketBaseTestCase.
Definition at line 281 of file satellite-per-packet-if-test.cc.
References SatPerPacketBaseTestCase::InitOutput(), LinkBudgetTraceCb(), SatPerPacketBaseTestCase::m_dummyFrames, SatPerPacketBaseTestCase::m_extName, SatPerPacketBaseTestCase::m_fading, SatPerPacketBaseTestCase::m_Interval1, SatPerPacketBaseTestCase::m_Interval2, SatPerPacketBaseTestCase::m_PackageSize1, SatPerPacketBaseTestCase::m_PackageSize2, and SatPerPacketBaseTestCase::PrintTraceInfo().
The documentation for this class was generated from the following file:
/builds/sns3/satellite/satellite/test/satellite-per-packet-if-test.cc