SNS3
SatRegenerationTest5 Class Reference
'Regeneration, test 5' test case implementation.
Public Member Functions
SatRegenerationTest5 ()
virtual ~SatRegenerationTest5 ()
Private Member Functions
virtual void DoRun (void)
void GeoPhyFeederModcodTraceCb (uint32_t modcod, const Address &address)
void GeoPhyGwModcodTraceCb (uint32_t modcod, const Address &address)
void GeoPhyUserModcodTraceCb (uint32_t modcod, const Address &address)
void GeoPhyUtModcodTraceCb (uint32_t modcod, const Address &address)
double GetAverage (std::vector< uint32_t > list, uint32_t beg, uint32_t end)
double GetMostFrequent (std::vector< uint32_t > list, uint32_t beg, uint32_t end)
Private Attributes
std::vector< uint32_t > m_feederModcods
std::vector< uint32_t > m_gwModcods
Ptr< SatHelper > m_helper
std::vector< uint32_t > m_userModcods
std::vector< uint32_t > m_utModcods
Detailed Description
'Regeneration, test 5' test case implementation.
This case tests ACM on all links. It is based on a SIMPLE scenario, with PHY regeneration on FWD and LINK regeneration on RTN.
Expected result: Most robust MODCOD used a start of simulation Efficient MODCOD used on all links after a few seconds Same MODCOD on FWD feeder and FWD user Not same MODCOD on RTN feeder and RTN user
Definition at line 1065 of file satellite-regeneration-test.cc.
Constructor & Destructor Documentation
SatRegenerationTest5()
SatRegenerationTest5::SatRegenerationTest5 ()
Definition at line 1148 of file satellite-regeneration-test.cc.
~SatRegenerationTest5()
SatRegenerationTest5::~SatRegenerationTest5 () virtual
Definition at line 1155 of file satellite-regeneration-test.cc.
Member Function Documentation
DoRun()
void SatRegenerationTest5::DoRun (void) private virtual
Set regeneration mode
Enable ACM
Set simulation output details
Definition at line 1163 of file satellite-regeneration-test.cc.
References GeoPhyFeederModcodTraceCb(), GeoPhyGwModcodTraceCb(), GeoPhyUserModcodTraceCb(), GeoPhyUtModcodTraceCb(), GetAverage(), GetMostFrequent(), m_feederModcods, m_gwModcods, m_helper, m_userModcods, and m_utModcods.
GeoPhyFeederModcodTraceCb()
void SatRegenerationTest5::GeoPhyFeederModcodTraceCb (uint32_t modcod, const Address & address) private
Definition at line 1102 of file satellite-regeneration-test.cc.
References m_feederModcods.
Referenced by DoRun().
GeoPhyGwModcodTraceCb()
void SatRegenerationTest5::GeoPhyGwModcodTraceCb (uint32_t modcod, const Address & address) private
Definition at line 1090 of file satellite-regeneration-test.cc.
References m_gwModcods.
Referenced by DoRun().
GeoPhyUserModcodTraceCb()
void SatRegenerationTest5::GeoPhyUserModcodTraceCb (uint32_t modcod, const Address & address) private
Definition at line 1108 of file satellite-regeneration-test.cc.
References m_userModcods.
Referenced by DoRun().
GeoPhyUtModcodTraceCb()
void SatRegenerationTest5::GeoPhyUtModcodTraceCb (uint32_t modcod, const Address & address) private
Definition at line 1096 of file satellite-regeneration-test.cc.
References m_utModcods.
Referenced by DoRun().
GetAverage()
double SatRegenerationTest5::GetAverage (std::vector< uint32_t > list, uint32_t beg, uint32_t end) private
Definition at line 1114 of file satellite-regeneration-test.cc.
Referenced by DoRun().
GetMostFrequent()
double SatRegenerationTest5::GetMostFrequent (std::vector< uint32_t > list, uint32_t beg, uint32_t end) private
Definition at line 1125 of file satellite-regeneration-test.cc.
Referenced by DoRun().
Member Data Documentation
m_feederModcods
std::vector<uint32_t> SatRegenerationTest5::m_feederModcods private
Definition at line 1085 of file satellite-regeneration-test.cc.
Referenced by DoRun(), and GeoPhyFeederModcodTraceCb().
m_gwModcods
std::vector<uint32_t> SatRegenerationTest5::m_gwModcods private
Definition at line 1083 of file satellite-regeneration-test.cc.
Referenced by DoRun(), and GeoPhyGwModcodTraceCb().
m_helper
Ptr<SatHelper> SatRegenerationTest5::m_helper private
Definition at line 1081 of file satellite-regeneration-test.cc.
Referenced by DoRun().
m_userModcods
std::vector<uint32_t> SatRegenerationTest5::m_userModcods private
Definition at line 1086 of file satellite-regeneration-test.cc.
Referenced by DoRun(), and GeoPhyUserModcodTraceCb().
m_utModcods
std::vector<uint32_t> SatRegenerationTest5::m_utModcods private
Definition at line 1084 of file satellite-regeneration-test.cc.
Referenced by DoRun(), and GeoPhyUtModcodTraceCb().
The documentation for this class was generated from the following file:
/builds/sns3/satellite/satellite/test/satellite-regeneration-test.cc