SNS3
ns3::LoraForwarder Class Reference
This application forwards packets between NetDevices: SatLorawanNetDevice -> PointToPointNetDevice and vice versa.
#include "lora-forwarder.h"
Public Member Functions
LoraForwarder ()
~LoraForwarder ()
bool ReceiveFromLora (Ptr< SatLorawanNetDevice > loraNetDevice, Ptr< const Packet > packet, uint16_t protocol, const Address &sender)
Receive a packet from the LoraNetDevice.
bool ReceiveFromPointToPoint (Ptr< NetDevice > pointToPointNetDevice, Ptr< const Packet > packet, uint16_t protocol, const Address &sender)
Receive a packet from the PointToPointNetDevice.
void SetLoraNetDevice (uint8_t beamId, Ptr< SatLorawanNetDevice > loraNetDevice)
Sets the device to use to communicate with the EDs.
void SetPointToPointNetDevice (Ptr< PointToPointNetDevice > pointToPointNetDevice)
Sets the P2P device to use to communicate with the NS.
void StartApplication (void)
Start the application.
void StopApplication (void)
Stop the application.
Static Public Member Functions
static TypeId GetTypeId (void)
Private Attributes
Ptr< PointToPointNetDevice > m_pointToPointNetDevice
Pointer to the P2PNetDevice we use to.
std::map< uint8_t, Ptr< SatLorawanNetDevice > > m_satLorawanNetDevices
Map between beam ID and pointer to the node's SatLorawanNetDevice.
Detailed Description
This application forwards packets between NetDevices: SatLorawanNetDevice -> PointToPointNetDevice and vice versa.
Definition at line 42 of file lora-forwarder.h.
Constructor & Destructor Documentation
LoraForwarder()
ns3::LoraForwarder::LoraForwarder ()
Definition at line 44 of file lora-forwarder.cc.
~LoraForwarder()
ns3::LoraForwarder::~LoraForwarder ()
Definition at line 49 of file lora-forwarder.cc.
Member Function Documentation
GetTypeId()
TypeId ns3::LoraForwarder::GetTypeId (void) static
Definition at line 37 of file lora-forwarder.cc.
ReceiveFromLora()
bool ns3::LoraForwarder::ReceiveFromLora (Ptr< SatLorawanNetDevice > loraNetDevice, Ptr< const Packet > packet, uint16_t protocol, const Address & sender)
Receive a packet from the LoraNetDevice.
Parameters
loraNetDevice The LoraNetDevice we received the packet from.
packet The packet we received.
protocol The protocol number associated to this packet.
sender The address of the sender.
Returns
True if we can handle the packet, false otherwise.
Definition at line 71 of file lora-forwarder.cc.
References m_pointToPointNetDevice.
Referenced by ns3::LoraForwarderHelper::InstallPriv().
ReceiveFromPointToPoint()
bool ns3::LoraForwarder::ReceiveFromPointToPoint (Ptr< NetDevice > pointToPointNetDevice, Ptr< const Packet > packet, uint16_t protocol, const Address & sender)
Receive a packet from the PointToPointNetDevice.
Definition at line 89 of file lora-forwarder.cc.
References ns3::LoraBeamTag::GetBeamId(), and m_satLorawanNetDevices.
Referenced by ns3::LoraForwarderHelper::InstallPriv().
SetLoraNetDevice()
void ns3::LoraForwarder::SetLoraNetDevice (uint8_t beamId, Ptr< SatLorawanNetDevice > loraNetDevice)
Sets the device to use to communicate with the EDs.
Parameters
beamId The beam ID of the device.
loraNetDevice The LoraNetDevice on this node.
Definition at line 63 of file lora-forwarder.cc.
References m_satLorawanNetDevices.
SetPointToPointNetDevice()
void ns3::LoraForwarder::SetPointToPointNetDevice (Ptr< PointToPointNetDevice > pointToPointNetDevice)
Sets the P2P device to use to communicate with the NS.
Parameters
pointToPointNetDevice The P2PNetDevice on this node.
Definition at line 55 of file lora-forwarder.cc.
References m_pointToPointNetDevice.
StartApplication()
void ns3::LoraForwarder::StartApplication (void)
Start the application.
Definition at line 109 of file lora-forwarder.cc.
StopApplication()
void ns3::LoraForwarder::StopApplication (void)
Stop the application.
Definition at line 117 of file lora-forwarder.cc.
Member Data Documentation
m_pointToPointNetDevice
Ptr<PointToPointNetDevice> ns3::LoraForwarder::m_pointToPointNetDevice private
Pointer to the P2PNetDevice we use to.
Definition at line 102 of file lora-forwarder.h.
Referenced by ReceiveFromLora(), and SetPointToPointNetDevice().
m_satLorawanNetDevices
std::map<uint8_t, Ptr<SatLorawanNetDevice> > ns3::LoraForwarder::m_satLorawanNetDevices private
Map between beam ID and pointer to the node's SatLorawanNetDevice.
Definition at line 99 of file lora-forwarder.h.
Referenced by ReceiveFromPointToPoint(), and SetLoraNetDevice().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/lora-forwarder.h
/builds/sns3/satellite/satellite/model/lora-forwarder.cc