SNS3
ns3::SatBtuConf Class Reference
This class implements configuration for Bandwidth Time Unit (BTU).
#include "satellite-frame-conf.h"
Public Member Functions
SatBtuConf ()
Default constructor for SatBtuConf.
SatBtuConf (double bandwidthInHz, double rollOff, double spacing, uint32_t spreadingFactor)
Constructor for SatBtuConf.
~SatBtuConf ()
Destructor for SatBtuConf.
double GetAllocatedBandwidthInHz () const
Get bandwidth of BTU.
double GetEffectiveBandwidthInHz () const
Get occupied bandwidth of BTU.
double GetOccupiedBandwidthInHz () const
Get occupied bandwidth of BTU.
double GetSpreadingFactor () const
Get spreading factor of BTU.
double GetSymbolRateInBauds () const
Get symbol rate of BTU.
Private Attributes
double m_allocatedBandwidthInHz
Time m_duration
double m_effectiveBandwidthInHz
double m_occupiedBandwidthInHz
double m_spreadingFactor
Detailed Description
This class implements configuration for Bandwidth Time Unit (BTU).
Definition at line 45 of file satellite-frame-conf.h.
Constructor & Destructor Documentation
SatBtuConf() [1/2]
ns3::SatBtuConf::SatBtuConf ()
Default constructor for SatBtuConf.
Definition at line 42 of file satellite-frame-conf.cc.
SatBtuConf() [2/2]
ns3::SatBtuConf::SatBtuConf (double bandwidthInHz, double rollOff, double spacing, uint32_t spreadingFactor)
Constructor for SatBtuConf.
Parameters
bandwidthInHz Allocated bandwidth of BTU in Hertz
rollOff Roll-off factor
spacing Spacing factor
spreadingFactor Spreading factor
Definition at line 54 of file satellite-frame-conf.cc.
References m_allocatedBandwidthInHz, m_duration, m_effectiveBandwidthInHz, and m_occupiedBandwidthInHz.
~SatBtuConf()
ns3::SatBtuConf::~SatBtuConf ()
Destructor for SatBtuConf.
Definition at line 82 of file satellite-frame-conf.cc.
Member Function Documentation
GetAllocatedBandwidthInHz()
double ns3::SatBtuConf::GetAllocatedBandwidthInHz () const inline
Get bandwidth of BTU.
Returns
The bandwidth of BTU in hertz.
Definition at line 73 of file satellite-frame-conf.h.
References m_allocatedBandwidthInHz.
GetEffectiveBandwidthInHz()
double ns3::SatBtuConf::GetEffectiveBandwidthInHz () const inline
Get occupied bandwidth of BTU.
Returns
The occupied bandwidth of BTU in hertz.
Definition at line 93 of file satellite-frame-conf.h.
References m_effectiveBandwidthInHz.
Referenced by GetSymbolRateInBauds().
GetOccupiedBandwidthInHz()
double ns3::SatBtuConf::GetOccupiedBandwidthInHz () const inline
Get occupied bandwidth of BTU.
Returns
The occupied bandwidth of BTU in hertz.
Definition at line 83 of file satellite-frame-conf.h.
References m_occupiedBandwidthInHz.
GetSpreadingFactor()
double ns3::SatBtuConf::GetSpreadingFactor () const inline
Get spreading factor of BTU.
Returns
The spreading factor of BTU.
Definition at line 103 of file satellite-frame-conf.h.
References m_spreadingFactor.
Referenced by GetSymbolRateInBauds().
GetSymbolRateInBauds()
double ns3::SatBtuConf::GetSymbolRateInBauds () const inline
Get symbol rate of BTU.
Returns
The symbol rate of BTU in bauds.
Definition at line 113 of file satellite-frame-conf.h.
References GetEffectiveBandwidthInHz(), and GetSpreadingFactor().
Member Data Documentation
m_allocatedBandwidthInHz
double ns3::SatBtuConf::m_allocatedBandwidthInHz private
Definition at line 119 of file satellite-frame-conf.h.
Referenced by SatBtuConf(), and GetAllocatedBandwidthInHz().
m_duration
Time ns3::SatBtuConf::m_duration private
Definition at line 123 of file satellite-frame-conf.h.
Referenced by SatBtuConf().
m_effectiveBandwidthInHz
double ns3::SatBtuConf::m_effectiveBandwidthInHz private
Definition at line 121 of file satellite-frame-conf.h.
Referenced by SatBtuConf(), and GetEffectiveBandwidthInHz().
m_occupiedBandwidthInHz
double ns3::SatBtuConf::m_occupiedBandwidthInHz private
Definition at line 120 of file satellite-frame-conf.h.
Referenced by SatBtuConf(), and GetOccupiedBandwidthInHz().
m_spreadingFactor
double ns3::SatBtuConf::m_spreadingFactor private
Definition at line 122 of file satellite-frame-conf.h.
Referenced by GetSpreadingFactor().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-frame-conf.h
/builds/sns3/satellite/satellite/model/satellite-frame-conf.cc