SNS3
ns3::SatRxPowerInputTraceContainer Class Reference
Class for Rx power input trace container.
#include "satellite-rx-power-input-trace-container.h"
Public Types
typedef std::map< key_t, Ptr< SatInputFileStreamTimeDoubleContainer > > container_t
typedef for map of containers
typedef std::pair< Address, SatEnums::ChannelType_t > key_t
typedef for map key
Public Member Functions
SatRxPowerInputTraceContainer ()
Constructor.
~SatRxPowerInputTraceContainer ()
Destructor.
void DoDispose ()
Do needed dispose actions.
TypeId GetInstanceTypeId (void) const
NS-3 instance type id function.
double GetRxPowerDensity (key_t key)
Function for getting the Rx power density.
void Reset ()
Function for resetting the variables.
Public Member Functions inherited from ns3::SatBaseTraceContainer
SatBaseTraceContainer ()
Constructor.
virtual ~SatBaseTraceContainer ()
Destructor.
TypeId GetInstanceTypeId (void) const
NS-3 instance type id function.
Static Public Member Functions
static TypeId GetTypeId (void)
NS-3 type id function.
Static Public Member Functions inherited from ns3::SatBaseTraceContainer
static TypeId GetTypeId (void)
NS-3 type id function.
Private Member Functions
Ptr< SatInputFileStreamTimeDoubleContainer > AddNode (std::pair< Address, SatEnums::ChannelType_t > key)
Function for adding the node to the map.
Ptr< SatInputFileStreamTimeDoubleContainer > FindNode (key_t key)
Function for finding the container matching the key.
Private Attributes
container_t m_container
Map for containers.
Additional Inherited Members
Static Public Attributes inherited from ns3::SatBaseTraceContainer
static const uint32_t CSINR_TRACE_DEFAULT_FADING_VALUE_INDEX = 1
Default sinr value index for composite sinr traces.
static const uint32_t CSINR_TRACE_DEFAULT_NUMBER_OF_COLUMNS = 2
Default number of columns for composite sinr traces.
static const uint32_t FADING_TRACE_DEFAULT_FADING_VALUE_INDEX = 1
Default fading value index for fading traces.
static const uint32_t FADING_TRACE_DEFAULT_NUMBER_OF_COLUMNS = 2
Default number of columns for fading traces.
static const uint32_t INTF_TRACE_DEFAULT_INTF_DENSITY_INDEX = 1
Default interference density index for interference traces.
static const uint32_t INTF_TRACE_DEFAULT_NUMBER_OF_COLUMNS = 2
Default number of columns for interference traces.
static const uint32_t POSITION_TRACE_DEFAULT_ALTITUDE_INDEX = 3
Default altitude value index for positions traces.
static const uint32_t POSITION_TRACE_DEFAULT_LATITUDE_INDEX = 1
Default latitude value index for positions traces.
static const uint32_t POSITION_TRACE_DEFAULT_LONGITUDE_INDEX = 2
Default longitude value index for positions traces.
static const uint32_t POSITION_TRACE_DEFAULT_NUMBER_OF_COLUMNS = 4
Default number of columns for position traces.
static const uint32_t RX_CNO_TRACE_DEFAULT_NUMBER_OF_COLUMNS = 2
Default Rx power density index for Rx power traces.
static const uint32_t RX_CNO_TRACE_DEFAULT_RX_POWER_DENSITY_INDEX = 1
Default Rx power density index for Rx power traces.
static const uint32_t RX_POWER_TRACE_DEFAULT_NUMBER_OF_COLUMNS = 2
Default Rx C/N0 index for C/N0 traces.
static const uint32_t RX_POWER_TRACE_DEFAULT_RX_POWER_DENSITY_INDEX = 1
Default Rx C/N0 index for C/N0 traces.
Detailed Description
Class for Rx power input trace container.
The class contains multiple Rx power input sample traces and provides an interface to them.
Definition at line 38 of file satellite-rx-power-input-trace-container.h.
Member Typedef Documentation
container_t
typedef std::map<key_t, Ptr<SatInputFileStreamTimeDoubleContainer> > ns3::SatRxPowerInputTraceContainer::container_t
typedef for map of containers
Definition at line 49 of file satellite-rx-power-input-trace-container.h.
key_t
typedef std::pair<Address, SatEnums::ChannelType_t> ns3::SatRxPowerInputTraceContainer::key_t
typedef for map key
Definition at line 44 of file satellite-rx-power-input-trace-container.h.
Constructor & Destructor Documentation
SatRxPowerInputTraceContainer()
ns3::SatRxPowerInputTraceContainer::SatRxPowerInputTraceContainer ()
Constructor.
Definition at line 53 of file satellite-rx-power-input-trace-container.cc.
~SatRxPowerInputTraceContainer()
ns3::SatRxPowerInputTraceContainer::~SatRxPowerInputTraceContainer ()
Destructor.
Definition at line 58 of file satellite-rx-power-input-trace-container.cc.
References Reset().
Member Function Documentation
AddNode()
Ptr< SatInputFileStreamTimeDoubleContainer > ns3::SatRxPowerInputTraceContainer::AddNode (std::pair< Address, SatEnums::ChannelType_t > key) private
Function for adding the node to the map.
Parameters
key key
Returns
pointer to the added container
Definition at line 87 of file satellite-rx-power-input-trace-container.cc.
References ns3::SatEnums::GetChannelTypeName(), m_container, and ns3::SatBaseTraceContainer::RX_POWER_TRACE_DEFAULT_NUMBER_OF_COLUMNS.
Referenced by FindNode().
DoDispose()
void ns3::SatRxPowerInputTraceContainer::DoDispose (void)
Do needed dispose actions.
Definition at line 66 of file satellite-rx-power-input-trace-container.cc.
References Reset().
FindNode()
Ptr< SatInputFileStreamTimeDoubleContainer > ns3::SatRxPowerInputTraceContainer::FindNode (key_t key) private
Function for finding the container matching the key.
Parameters
key key
Returns
matching container
Definition at line 138 of file satellite-rx-power-input-trace-container.cc.
References AddNode(), and m_container.
Referenced by GetRxPowerDensity().
GetInstanceTypeId()
TypeId ns3::SatRxPowerInputTraceContainer::GetInstanceTypeId (void) const
NS-3 instance type id function.
Returns
Instance type is
Definition at line 46 of file satellite-rx-power-input-trace-container.cc.
References GetTypeId().
GetRxPowerDensity()
double ns3::SatRxPowerInputTraceContainer::GetRxPowerDensity (key_t key)
Function for getting the Rx power density.
Parameters
key key
Returns
Rx power density
Definition at line 153 of file satellite-rx-power-input-trace-container.cc.
References FindNode(), and ns3::SatBaseTraceContainer::RX_POWER_TRACE_DEFAULT_RX_POWER_DENSITY_INDEX.
GetTypeId()
TypeId ns3::SatRxPowerInputTraceContainer::GetTypeId (void) static
NS-3 type id function.
Returns
type id
Definition at line 37 of file satellite-rx-power-input-trace-container.cc.
Referenced by GetInstanceTypeId().
Reset()
void ns3::SatRxPowerInputTraceContainer::Reset (void) virtual
Function for resetting the variables.
Implements ns3::SatBaseTraceContainer.
Definition at line 76 of file satellite-rx-power-input-trace-container.cc.
References m_container.
Referenced by ~SatRxPowerInputTraceContainer(), and DoDispose().
Member Data Documentation
m_container
container_t ns3::SatRxPowerInputTraceContainer::m_container private
Map for containers.
Definition at line 109 of file satellite-rx-power-input-trace-container.h.
Referenced by AddNode(), FindNode(), and Reset().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-rx-power-input-trace-container.h
/builds/sns3/satellite/satellite/model/satellite-rx-power-input-trace-container.cc