SNS3
ns3::SatPositionInputTraceContainer Class Reference
Class for Rx power input trace container.
#include "satellite-position-input-trace-container.h"
Public Types
typedef std::map< std::string, Ptr< SatInputFileStreamTimeDoubleContainer > > container_t
typedef for map of containers
Public Member Functions
SatPositionInputTraceContainer ()
Constructor.
~SatPositionInputTraceContainer ()
Destructor.
void DoDispose ()
Do needed dispose actions.
TypeId GetInstanceTypeId (void) const
NS-3 instance type id function.
GeoCoordinate GetPosition (const std::string &key, GeoCoordinate::ReferenceEllipsoid_t refEllipsoid)
Function for getting the Rx power density.
void Reset ()
Function for resetting the variables.
Public Member Functions inherited from ns3::SatBaseTraceContainer
SatBaseTraceContainer ()
Constructor.
virtual ~SatBaseTraceContainer ()
Destructor.
TypeId GetInstanceTypeId (void) const
NS-3 instance type id function.
Static Public Member Functions
static TypeId GetTypeId (void)
NS-3 type id function.
Static Public Member Functions inherited from ns3::SatBaseTraceContainer
static TypeId GetTypeId (void)
NS-3 type id function.
Private Member Functions
Ptr< SatInputFileStreamTimeDoubleContainer > AddNode (const std::string &key)
Function for adding the node to the map.
Ptr< SatInputFileStreamTimeDoubleContainer > FindNode (const std::string &key)
Function for finding the container matching the key.
Private Attributes
container_t m_container
Map for containers.
Additional Inherited Members
Static Public Attributes inherited from ns3::SatBaseTraceContainer
static const uint32_t CSINR_TRACE_DEFAULT_FADING_VALUE_INDEX = 1
Default sinr value index for composite sinr traces.
static const uint32_t CSINR_TRACE_DEFAULT_NUMBER_OF_COLUMNS = 2
Default number of columns for composite sinr traces.
static const uint32_t FADING_TRACE_DEFAULT_FADING_VALUE_INDEX = 1
Default fading value index for fading traces.
static const uint32_t FADING_TRACE_DEFAULT_NUMBER_OF_COLUMNS = 2
Default number of columns for fading traces.
static const uint32_t INTF_TRACE_DEFAULT_INTF_DENSITY_INDEX = 1
Default interference density index for interference traces.
static const uint32_t INTF_TRACE_DEFAULT_NUMBER_OF_COLUMNS = 2
Default number of columns for interference traces.
static const uint32_t POSITION_TRACE_DEFAULT_ALTITUDE_INDEX = 3
Default altitude value index for positions traces.
static const uint32_t POSITION_TRACE_DEFAULT_LATITUDE_INDEX = 1
Default latitude value index for positions traces.
static const uint32_t POSITION_TRACE_DEFAULT_LONGITUDE_INDEX = 2
Default longitude value index for positions traces.
static const uint32_t POSITION_TRACE_DEFAULT_NUMBER_OF_COLUMNS = 4
Default number of columns for position traces.
static const uint32_t RX_CNO_TRACE_DEFAULT_NUMBER_OF_COLUMNS = 2
Default Rx power density index for Rx power traces.
static const uint32_t RX_CNO_TRACE_DEFAULT_RX_POWER_DENSITY_INDEX = 1
Default Rx power density index for Rx power traces.
static const uint32_t RX_POWER_TRACE_DEFAULT_NUMBER_OF_COLUMNS = 2
Default Rx C/N0 index for C/N0 traces.
static const uint32_t RX_POWER_TRACE_DEFAULT_RX_POWER_DENSITY_INDEX = 1
Default Rx C/N0 index for C/N0 traces.
Detailed Description
Class for Rx power input trace container.
The class contains multiple Rx power input sample traces and provides an interface to them.
Definition at line 39 of file satellite-position-input-trace-container.h.
Member Typedef Documentation
container_t
typedef std::map<std::string, Ptr<SatInputFileStreamTimeDoubleContainer> > ns3::SatPositionInputTraceContainer::container_t
typedef for map of containers
Definition at line 45 of file satellite-position-input-trace-container.h.
Constructor & Destructor Documentation
SatPositionInputTraceContainer()
ns3::SatPositionInputTraceContainer::SatPositionInputTraceContainer ()
Constructor.
Definition at line 51 of file satellite-position-input-trace-container.cc.
~SatPositionInputTraceContainer()
ns3::SatPositionInputTraceContainer::~SatPositionInputTraceContainer ()
Destructor.
Definition at line 56 of file satellite-position-input-trace-container.cc.
References Reset().
Member Function Documentation
AddNode()
Ptr< SatInputFileStreamTimeDoubleContainer > ns3::SatPositionInputTraceContainer::AddNode (const std::string & key) private
Function for adding the node to the map.
Parameters
key filename to read positions from
Returns
pointer to the added container
Definition at line 85 of file satellite-position-input-trace-container.cc.
References m_container, and ns3::SatBaseTraceContainer::POSITION_TRACE_DEFAULT_NUMBER_OF_COLUMNS.
Referenced by FindNode().
DoDispose()
void ns3::SatPositionInputTraceContainer::DoDispose (void)
Do needed dispose actions.
Definition at line 64 of file satellite-position-input-trace-container.cc.
References Reset().
FindNode()
Ptr< SatInputFileStreamTimeDoubleContainer > ns3::SatPositionInputTraceContainer::FindNode (const std::string & key) private
Function for finding the container matching the key.
Parameters
key key
Returns
matching container
Definition at line 105 of file satellite-position-input-trace-container.cc.
References AddNode(), and m_container.
Referenced by GetPosition().
GetInstanceTypeId()
TypeId ns3::SatPositionInputTraceContainer::GetInstanceTypeId (void) const
NS-3 instance type id function.
Returns
Instance type is
Definition at line 44 of file satellite-position-input-trace-container.cc.
References GetTypeId().
GetPosition()
GeoCoordinate ns3::SatPositionInputTraceContainer::GetPosition (const std::string & key, GeoCoordinate::ReferenceEllipsoid_t refEllipsoid)
Function for getting the Rx power density.
Parameters
key key
Returns
Rx power density
Definition at line 120 of file satellite-position-input-trace-container.cc.
References FindNode(), ns3::SatBaseTraceContainer::POSITION_TRACE_DEFAULT_ALTITUDE_INDEX, ns3::SatBaseTraceContainer::POSITION_TRACE_DEFAULT_LATITUDE_INDEX, and ns3::SatBaseTraceContainer::POSITION_TRACE_DEFAULT_LONGITUDE_INDEX.
GetTypeId()
TypeId ns3::SatPositionInputTraceContainer::GetTypeId (void) static
NS-3 type id function.
Returns
type id
Definition at line 35 of file satellite-position-input-trace-container.cc.
Referenced by GetInstanceTypeId().
Reset()
void ns3::SatPositionInputTraceContainer::Reset (void) virtual
Function for resetting the variables.
Implements ns3::SatBaseTraceContainer.
Definition at line 74 of file satellite-position-input-trace-container.cc.
References m_container.
Referenced by ~SatPositionInputTraceContainer(), and DoDispose().
Member Data Documentation
m_container
container_t ns3::SatPositionInputTraceContainer::m_container private
Map for containers.
Definition at line 105 of file satellite-position-input-trace-container.h.
Referenced by AddNode(), FindNode(), and Reset().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-position-input-trace-container.h
/builds/sns3/satellite/satellite/model/satellite-position-input-trace-container.cc