SNS3
ns3::SatStatsFwdUserQueuePacketsHelper Class Reference
Satellite Statistics
Produce queue size statistics in packets for return feeder link.
#include "satellite-stats-satellite-queue-helper.h"
Public Member Functions
SatStatsFwdUserQueuePacketsHelper (Ptr< const SatHelper > satHelper)
virtual ~SatStatsFwdUserQueuePacketsHelper ()
/ Destructor.
Public Member Functions inherited from ns3::SatStatsSatelliteQueueHelper
SatStatsSatelliteQueueHelper (Ptr< const SatHelper > satHelper)
virtual ~SatStatsSatelliteQueueHelper ()
/ Destructor.
void InstallProbes ()
Set up several probes or other means of listeners and connect them to the collectors.
void QueueSizeCallback (uint32_t size, const Address &addr)
Receive inputs from trace sources and forward them to the collector.
void SetAveragingMode (bool averagingMode)
void SetUnitType (UnitType_t unitType)
Public Member Functions inherited from ns3::SatStatsHelper
SatStatsHelper (Ptr< const SatHelper > satHelper)
Creates a new helper instance.
virtual ~SatStatsHelper ()
/ Destructor.
IdentifierType_t GetIdentifierType () const
std::string GetName () const
OutputType_t GetOutputType () const
Ptr< const SatHelper > GetSatHelper () const
void Install ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
bool IsInstalled () const
void SetIdentifierType (IdentifierType_t identifierType)
void SetName (std::string name)
void SetOutputType (OutputType_t outputType)
Static Public Member Functions
static TypeId GetTypeId ()
inherited from ObjectBase base class
Static Public Member Functions inherited from ns3::SatStatsSatelliteQueueHelper
static TypeId GetTypeId ()
inherited from ObjectBase base class
static std::string GetUnitTypeName (UnitType_t unitType)
Static Public Member Functions inherited from ns3::SatStatsHelper
static std::string GetIdentifierTypeName (IdentifierType_t identifierType)
static std::string GetOutputTypeName (OutputType_t outputType)
static TypeId GetTypeId ()
inherited from ObjectBase base class
Protected Member Functions
void DoInstallProbes ()
Protected Member Functions inherited from ns3::SatStatsSatelliteQueueHelper
bool ConnectProbeToCollector (Ptr< Probe > probe, uint32_t identifier)
Connect the probe to the right collector.
void DoInstall ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
void PassSampleToCollector (uint32_t size, uint32_t identifier)
Find a collector with the right identifier and pass a sample data to it.
void SaveAddressAndIdentifier (Ptr< Node > utNode)
Save the address and the proper identifier from the given UT node.
Protected Member Functions inherited from ns3::SatStatsHelper
Ptr< DataCollectionObject > CreateAggregator (std::string aggregatorTypeId, std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue())
Create the aggregator according to the output type.
uint32_t CreateCollectorPerIdentifier (CollectorMap &collectorMap) const
Create one collector instance for each identifier in the simulation.
virtual std::string GetDistributionHeading (std::string dataLabel) const
uint32_t GetGwId (Ptr< Node > gwNode) const
uint32_t GetIdentifierForBeam (uint32_t satId, uint32_t beamId) const
uint32_t GetIdentifierForGroup (uint32_t groupId) const
uint32_t GetIdentifierForGw (Ptr< Node > gwNode) const
uint32_t GetIdentifierForIsl (Ptr< Node > satNodeSrc, Ptr< Node > satNodeDst) const
uint32_t GetIdentifierForSat (Ptr< Node > satNode) const
uint32_t GetIdentifierForUt (Ptr< Node > utNode) const
uint32_t GetIdentifierForUtUser (Ptr< Node > utUserNode) const
virtual std::string GetIdentifierHeading (std::string dataLabel) const
virtual std::string GetOutputFileName () const
Compute the path and file name where statistics output should be written to.
virtual std::string GetOutputPath () const
uint32_t GetSatId (Ptr< Node > satNode) const
virtual std::string GetTimeHeading (std::string dataLabel) const
uint32_t GetUtId (Ptr< Node > utNode) const
uint32_t GetUtUserId (Ptr< Node > utUserNode) const
Additional Inherited Members
Public Types inherited from ns3::SatStatsSatelliteQueueHelper
enum UnitType_t { UNIT_BYTES = 0 , UNIT_NUMBER_OF_PACKETS }
Public Types inherited from ns3::SatStatsHelper
enum IdentifierType_t {
IDENTIFIER_GLOBAL = 0 , IDENTIFIER_GW , IDENTIFIER_BEAM , IDENTIFIER_UT ,
IDENTIFIER_UT_USER , IDENTIFIER_SLICE , IDENTIFIER_GROUP , IDENTIFIER_SAT ,
IDENTIFIER_ISL
}
Possible categorization of statistics output.
enum OutputType_t {
OUTPUT_NONE = 0 , OUTPUT_SCALAR_FILE , OUTPUT_SCATTER_FILE , OUTPUT_HISTOGRAM_FILE ,
OUTPUT_PDF_FILE , OUTPUT_CDF_FILE , OUTPUT_SCALAR_PLOT , OUTPUT_SCATTER_PLOT ,
OUTPUT_HISTOGRAM_PLOT , OUTPUT_PDF_PLOT , OUTPUT_CDF_PLOT
}
Possible types and formats of statistics output.
Static Protected Member Functions inherited from ns3::SatStatsHelper
static NetDeviceContainer GetGwSatNetDevice (Ptr< Node > gwNode)
static Ptr< NetDevice > GetSatSatGeoNetDevice (Ptr< Node > satNode)
static Ptr< NetDevice > GetUtSatNetDevice (Ptr< Node > utNode)
Protected Attributes inherited from ns3::SatStatsSatelliteQueueHelper
Ptr< DataCollectionObject > m_aggregator
The aggregator created by this helper.
Ptr< DistributionCollector > m_averagingCollector
The final collector utilized in averaged output (histogram, PDF, and CDF).
Ptr< DataCollectionObject > m_collector
The collector created by this helper.
std::map< const Address, uint32_t > m_identifierMap
Map of address and the identifier associated with it (for return link).
CollectorMap m_terminalCollectors
Maintains a list of collectors created by this helper.
Detailed Description
Produce queue size statistics in packets for return feeder link.
For a more convenient usage in simulation script, it is recommended to use the corresponding methods in SatStatsHelperContainer class.
Otherwise, the following example can be used:
Ptr<SatStatsFwdUserQueuePacketsHelper> s = Create<SatStatsFwdUserQueuePacketsHelper> (satHelper);
s->SetName ("name");
s->SetOutputType (SatStatsHelper::OUTPUT_SCATTER_FILE);
s->Install ();
Definition at line 252 of file satellite-stats-satellite-queue-helper.h.
Constructor & Destructor Documentation
SatStatsFwdUserQueuePacketsHelper()
ns3::SatStatsFwdUserQueuePacketsHelper::SatStatsFwdUserQueuePacketsHelper (Ptr< const SatHelper > satHelper)
Definition at line 835 of file satellite-stats-satellite-queue-helper.cc.
References ns3::SatStatsSatelliteQueueHelper::SetUnitType(), and ns3::SatStatsSatelliteQueueHelper::UNIT_NUMBER_OF_PACKETS.
~SatStatsFwdUserQueuePacketsHelper()
ns3::SatStatsFwdUserQueuePacketsHelper::~SatStatsFwdUserQueuePacketsHelper () virtual
/ Destructor.
Definition at line 842 of file satellite-stats-satellite-queue-helper.cc.
Member Function Documentation
DoInstallProbes()
void ns3::SatStatsFwdUserQueuePacketsHelper::DoInstallProbes () protected virtual
Implements ns3::SatStatsSatelliteQueueHelper.
Definition at line 856 of file satellite-stats-satellite-queue-helper.cc.
References ns3::SatStatsHelper::GetSatHelper(), ns3::SatStatsHelper::GetSatSatGeoNetDevice(), ns3::SatStatsSatelliteQueueHelper::QueueSizeCallback(), and ns3::SatStatsSatelliteQueueHelper::SaveAddressAndIdentifier().
GetTypeId()
TypeId ns3::SatStatsFwdUserQueuePacketsHelper::GetTypeId (void) static
inherited from ObjectBase base class
Definition at line 848 of file satellite-stats-satellite-queue-helper.cc.
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/stats/satellite-stats-satellite-queue-helper.h
/builds/sns3/satellite/satellite/stats/satellite-stats-satellite-queue-helper.cc