SNS3
SatConstellationTest3 Class Reference
'Constellation, test 3 test case implementation.
Public Member Functions
SatConstellationTest3 ()
virtual ~SatConstellationTest3 ()
Private Member Functions
virtual void DoRun (void)
std::vector< std::string > Split (std::string s, char del)
void TestFileValue (std::string path, uint32_t time, uint32_t expectedValue)
Private Attributes
Ptr< SatHelper > m_helper
Detailed Description
'Constellation, test 3 test case implementation.
This case tests that a application throughputs PerEntity are correct, with one ISL link. It generates a conf with 2 satellites, 2 GWs, 3 UTs and 3 UT users per UT. Each UT user receives 409.6 kb/s.
Expected throughputs (after 3s):
6144 kb/s globally
2048 kb/s and 4096 kb/s per satellite
2048 kb/s per UT
2048 kb/s and 4096 kb/s per GW
409.6 kb/s per UT user
2048 kb/s and 4096 kb/s per satellite
Definition at line 510 of file satellite-constellation-test.cc.
Constructor & Destructor Documentation
SatConstellationTest3()
SatConstellationTest3::SatConstellationTest3 ()
Definition at line 526 of file satellite-constellation-test.cc.
~SatConstellationTest3()
SatConstellationTest3::~SatConstellationTest3 () virtual
Definition at line 533 of file satellite-constellation-test.cc.
Member Function Documentation
DoRun()
void SatConstellationTest3::DoRun (void) private virtual
Set regeneration mode
Use constellation
Definition at line 595 of file satellite-constellation-test.cc.
References m_helper, and TestFileValue().
Split()
std::vector< std::string > SatConstellationTest3::Split (std::string s, char del) private
Definition at line 538 of file satellite-constellation-test.cc.
Referenced by TestFileValue().
TestFileValue()
void SatConstellationTest3::TestFileValue (std::string path, uint32_t time, uint32_t expectedValue) private
Definition at line 552 of file satellite-constellation-test.cc.
References Split().
Referenced by DoRun().
Member Data Documentation
m_helper
Ptr<SatHelper> SatConstellationTest3::m_helper private
Definition at line 522 of file satellite-constellation-test.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
/builds/sns3/satellite/satellite/test/satellite-constellation-test.cc