SNS3
SatRegenerationTest6 Class Reference
'Regeneration, test 6' test case implementation.
Public Member Functions
SatRegenerationTest6 ()
virtual ~SatRegenerationTest6 ()
Private Member Functions
virtual void DoRun (void)
void GeoDevGwRxTraceCb (Ptr< const Packet > packet, const Address &)
void GeoDevGwTxTraceCb (Ptr< const Packet > packet)
void GeoDevUtRxTraceCb (Ptr< const Packet > packet, const Address &)
void GeoDevUtTxTraceCb (Ptr< const Packet > packet)
bool HasSinkInstalled (Ptr< Node > node, uint16_t port)
Private Attributes
Ptr< SatHelper > m_helper
uint32_t m_totalReceivedGw
uint32_t m_totalReceivedUt
uint32_t m_totalSentGw
uint32_t m_totalSentUt
Detailed Description
'Regeneration, test 6' test case implementation.
This case tests network regeneration on satellite. It is based on a LARGER scenario.
Expected result: Same number of bytes sent and received on FWD Same number of bytes sent and received on RTN
Definition at line 1302 of file satellite-regeneration-test.cc.
Constructor & Destructor Documentation
SatRegenerationTest6()
SatRegenerationTest6::SatRegenerationTest6 ()
Definition at line 1368 of file satellite-regeneration-test.cc.
References m_totalReceivedGw, m_totalReceivedUt, m_totalSentGw, and m_totalSentUt.
~SatRegenerationTest6()
SatRegenerationTest6::~SatRegenerationTest6 () virtual
Definition at line 1380 of file satellite-regeneration-test.cc.
Member Function Documentation
DoRun()
void SatRegenerationTest6::DoRun (void) private virtual
Set regeneration mode
Set simulation output details
Definition at line 1388 of file satellite-regeneration-test.cc.
References GeoDevGwRxTraceCb(), GeoDevGwTxTraceCb(), GeoDevUtRxTraceCb(), GeoDevUtTxTraceCb(), m_helper, m_totalReceivedGw, m_totalReceivedUt, m_totalSentGw, and m_totalSentUt.
GeoDevGwRxTraceCb()
void SatRegenerationTest6::GeoDevGwRxTraceCb (Ptr< const Packet > packet, const Address &) private
Definition at line 1337 of file satellite-regeneration-test.cc.
References m_totalReceivedGw.
Referenced by DoRun().
GeoDevGwTxTraceCb()
void SatRegenerationTest6::GeoDevGwTxTraceCb (Ptr< const Packet > packet) private
Definition at line 1325 of file satellite-regeneration-test.cc.
References m_totalSentGw.
Referenced by DoRun().
GeoDevUtRxTraceCb()
void SatRegenerationTest6::GeoDevUtRxTraceCb (Ptr< const Packet > packet, const Address & address) private
Definition at line 1343 of file satellite-regeneration-test.cc.
References m_totalReceivedUt.
Referenced by DoRun().
GeoDevUtTxTraceCb()
void SatRegenerationTest6::GeoDevUtTxTraceCb (Ptr< const Packet > packet) private
Definition at line 1331 of file satellite-regeneration-test.cc.
References m_totalSentUt.
Referenced by DoRun().
HasSinkInstalled()
bool SatRegenerationTest6::HasSinkInstalled (Ptr< Node > node, uint16_t port) private
Definition at line 1349 of file satellite-regeneration-test.cc.
Member Data Documentation
m_helper
Ptr<SatHelper> SatRegenerationTest6::m_helper private
Definition at line 1316 of file satellite-regeneration-test.cc.
Referenced by DoRun().
m_totalReceivedGw
uint32_t SatRegenerationTest6::m_totalReceivedGw private
Definition at line 1320 of file satellite-regeneration-test.cc.
Referenced by SatRegenerationTest6(), DoRun(), and GeoDevGwRxTraceCb().
m_totalReceivedUt
uint32_t SatRegenerationTest6::m_totalReceivedUt private
Definition at line 1321 of file satellite-regeneration-test.cc.
Referenced by SatRegenerationTest6(), DoRun(), and GeoDevUtRxTraceCb().
m_totalSentGw
uint32_t SatRegenerationTest6::m_totalSentGw private
Definition at line 1318 of file satellite-regeneration-test.cc.
Referenced by SatRegenerationTest6(), DoRun(), and GeoDevGwTxTraceCb().
m_totalSentUt
uint32_t SatRegenerationTest6::m_totalSentUt private
Definition at line 1319 of file satellite-regeneration-test.cc.
Referenced by SatRegenerationTest6(), DoRun(), and GeoDevUtTxTraceCb().
The documentation for this class was generated from the following file:
/builds/sns3/satellite/satellite/test/satellite-regeneration-test.cc