SNS3
ns3::SatPositionAllocator Class Reference abstract
Allocate a set of satellite positions.
#include "satellite-position-allocator.h"
Public Member Functions
SatPositionAllocator ()
Default constructor.
virtual ~SatPositionAllocator ()
Destructor for SatPositionAllocator.
virtual int64_t AssignStreams (int64_t stream)
virtual Vector GetNext (void) const
virtual GeoCoordinate GetNextGeoPosition (uint32_t satId=0) const =0
Get next position.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
bool m_GetAsGeoCoordinates
Detailed Description
Allocate a set of satellite positions.
The allocation strategy is implemented in inherited classes.
This is a pure abstract base class.
Definition at line 42 of file satellite-position-allocator.h.
Constructor & Destructor Documentation
SatPositionAllocator()
ns3::SatPositionAllocator::SatPositionAllocator ()
Default constructor.
Definition at line 62 of file satellite-position-allocator.cc.
~SatPositionAllocator()
ns3::SatPositionAllocator::~SatPositionAllocator () virtual
Destructor for SatPositionAllocator.
Definition at line 67 of file satellite-position-allocator.cc.
Member Function Documentation
AssignStreams()
int64_t ns3::SatPositionAllocator::AssignStreams (int64_t stream) virtual
Reimplemented in ns3::SatSpotBeamPositionAllocator, ns3::SatRandomCirclePositionAllocator, and ns3::SatRandomBoxPositionAllocator.
Definition at line 89 of file satellite-position-allocator.cc.
GetNext()
Vector ns3::SatPositionAllocator::GetNext (void) const virtual
Definition at line 72 of file satellite-position-allocator.cc.
References ns3::GeoCoordinate::GetAltitude(), ns3::GeoCoordinate::GetLatitude(), ns3::GeoCoordinate::GetLongitude(), GetNextGeoPosition(), m_GetAsGeoCoordinates, and ns3::GeoCoordinate::ToVector().
GetNextGeoPosition()
virtual GeoCoordinate ns3::SatPositionAllocator::GetNextGeoPosition (uint32_t satId = 0) const pure virtual
Get next position.
Returns
The next chosen position.
Implemented in ns3::SatRandomCirclePositionAllocator, ns3::SatRandomBoxPositionAllocator, ns3::SatListPositionAllocator, and ns3::SatSpotBeamPositionAllocator.
Referenced by GetNext().
GetTypeId()
TypeId ns3::SatPositionAllocator::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 48 of file satellite-position-allocator.cc.
References m_GetAsGeoCoordinates.
Member Data Documentation
m_GetAsGeoCoordinates
bool ns3::SatPositionAllocator::m_GetAsGeoCoordinates private
Definition at line 78 of file satellite-position-allocator.h.
Referenced by GetNext(), and GetTypeId().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-position-allocator.h
/builds/sns3/satellite/satellite/model/satellite-position-allocator.cc