SNS3
ns3::SatAntennaGainPatternContainer Class Reference
Antenna gain pattern container holds all antenna patterns related to a satellite system.
#include "satellite-antenna-gain-pattern-container.h"
Public Types
typedef std::map< std::pair< uint32_t, uint32_t >, SatBeamUserInfo > BeamUserInfoMap_t
definition for beam map key is pair sat ID / beam ID and value is UT/user info.
Public Member Functions
SatAntennaGainPatternContainer (uint32_t nbSats=1)
Default constructor.
~SatAntennaGainPatternContainer ()
void ConfigureBeamsMobility (uint32_t satelliteId, Ptr< SatMobilityModel > mobility)
Ptr< SatAntennaGainPattern > GetAntennaGainPattern (uint32_t beamId) const
Get the antenna pattern of a specified beam id.
Ptr< SatMobilityModel > GetAntennaMobility (uint32_t satelliteId) const
Get the mobility model of a specified beam id.
uint32_t GetBestBeamId (uint32_t satelliteId, GeoCoordinate coord, bool ignoreNan)
Get the best beam id based on the antenna patterns in a specified geo coordinate.
GeoCoordinate GetDefaultGeoPosition ()
Load the default satellite position associated to these traces.
TypeId GetInstanceTypeId () const
uint32_t GetNAntennaGainPatterns () const
Get the number of stored antenna pattern.
void SetEnabledBeams (BeamUserInfoMap_t &info)
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
std::map< uint32_t, Ptr< SatAntennaGainPattern > > m_antennaPatternMap
Container of antenna patterns.
std::map< uint32_t, Ptr< SatMobilityModel > > m_mobilityModelMap
Container of mobility models.
std::string m_patternsFolder
Detailed Description
Antenna gain pattern container holds all antenna patterns related to a satellite system.
Current reference system consists of 72 spot-beams. It is assumed that all links use the same set of antenna patterns (forward feeder and user, return feeder and user). Each antenna gain pattern is stored in a separate class SatAntennaGainPattern. The best beam may be chosen based on the antenna patterns by using GetBestBeamId for a given position.
Definition at line 45 of file satellite-antenna-gain-pattern-container.h.
Member Typedef Documentation
BeamUserInfoMap_t
typedef std::map<std::pair<uint32_t, uint32_t>, SatBeamUserInfo> ns3::SatAntennaGainPatternContainer::BeamUserInfoMap_t
definition for beam map key is pair sat ID / beam ID and value is UT/user info.
Definition at line 65 of file satellite-antenna-gain-pattern-container.h.
Constructor & Destructor Documentation
SatAntennaGainPatternContainer()
ns3::SatAntennaGainPatternContainer::SatAntennaGainPatternContainer (uint32_t nbSats = 1)
Default constructor.
Parameters
nbSats Number of satellites to consider
Definition at line 68 of file satellite-antenna-gain-pattern-container.cc.
References GetDefaultGeoPosition(), m_antennaPatternMap, m_patternsFolder, and numbers.
~SatAntennaGainPatternContainer()
ns3::SatAntennaGainPatternContainer::~SatAntennaGainPatternContainer ()
Definition at line 165 of file satellite-antenna-gain-pattern-container.cc.
Member Function Documentation
ConfigureBeamsMobility()
void ns3::SatAntennaGainPatternContainer::ConfigureBeamsMobility (uint32_t satelliteId, Ptr< SatMobilityModel > mobility)
Definition at line 292 of file satellite-antenna-gain-pattern-container.cc.
References m_mobilityModelMap.
Referenced by SatAntennaPatternTestCase::DoRun().
GetAntennaGainPattern()
Ptr< SatAntennaGainPattern > ns3::SatAntennaGainPatternContainer::GetAntennaGainPattern (uint32_t beamId) const
Get the antenna pattern of a specified beam id.
Parameters
beamId Beam identifier
Returns
The antenna gain pattern instance of the specified beam id
Definition at line 199 of file satellite-antenna-gain-pattern-container.cc.
References m_antennaPatternMap.
Referenced by SatAntennaPatternTestCase::DoRun().
GetAntennaMobility()
Ptr< SatMobilityModel > ns3::SatAntennaGainPatternContainer::GetAntennaMobility (uint32_t satelliteId) const
Get the mobility model of a specified beam id.
Parameters
satelliteId Satellite identifier
Returns
The mobility model
Definition at line 215 of file satellite-antenna-gain-pattern-container.cc.
References m_mobilityModelMap.
GetBestBeamId()
uint32_t ns3::SatAntennaGainPatternContainer::GetBestBeamId (uint32_t satelliteId, GeoCoordinate coord, bool ignoreNan)
Get the best beam id based on the antenna patterns in a specified geo coordinate.
Parameters
satelliteId ID of satellite to search
coord Geo coordinate
ignoreNan Do not crash if a NaN value is returned
Returns
best beam id in the specified geo coordinate
Definition at line 232 of file satellite-antenna-gain-pattern-container.cc.
References ns3::GeoCoordinate::GetLatitude(), ns3::GeoCoordinate::GetLongitude(), m_antennaPatternMap, and m_mobilityModelMap.
Referenced by SatAntennaPatternTestCase::DoRun().
GetDefaultGeoPosition()
GeoCoordinate ns3::SatAntennaGainPatternContainer::GetDefaultGeoPosition ()
Load the default satellite position associated to these traces.
Must be in GeoPos.in
Returns
The satellite position
Definition at line 171 of file satellite-antenna-gain-pattern-container.cc.
References m_patternsFolder.
Referenced by SatAntennaGainPatternContainer().
GetInstanceTypeId()
TypeId ns3::SatAntennaGainPatternContainer::GetInstanceTypeId (void) const
Definition at line 62 of file satellite-antenna-gain-pattern-container.cc.
References GetTypeId().
GetNAntennaGainPatterns()
uint32_t ns3::SatAntennaGainPatternContainer::GetNAntennaGainPatterns () const
Get the number of stored antenna pattern.
Returns
The total number of antenna gain pattern instance
Definition at line 282 of file satellite-antenna-gain-pattern-container.cc.
References m_antennaPatternMap.
GetTypeId()
TypeId ns3::SatAntennaGainPatternContainer::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 46 of file satellite-antenna-gain-pattern-container.cc.
References m_patternsFolder.
Referenced by GetInstanceTypeId().
SetEnabledBeams()
void ns3::SatAntennaGainPatternContainer::SetEnabledBeams (BeamUserInfoMap_t & info)
Definition at line 301 of file satellite-antenna-gain-pattern-container.cc.
References m_antennaPatternMap.
Member Data Documentation
m_antennaPatternMap
std::map<uint32_t, Ptr<SatAntennaGainPattern> > ns3::SatAntennaGainPatternContainer::m_antennaPatternMap private
Container of antenna patterns.
Definition at line 113 of file satellite-antenna-gain-pattern-container.h.
Referenced by SatAntennaGainPatternContainer(), GetAntennaGainPattern(), GetBestBeamId(), GetNAntennaGainPatterns(), and SetEnabledBeams().
m_mobilityModelMap
std::map<uint32_t, Ptr<SatMobilityModel> > ns3::SatAntennaGainPatternContainer::m_mobilityModelMap private
Container of mobility models.
Definition at line 118 of file satellite-antenna-gain-pattern-container.h.
Referenced by ConfigureBeamsMobility(), GetAntennaMobility(), and GetBestBeamId().
m_patternsFolder
std::string ns3::SatAntennaGainPatternContainer::m_patternsFolder private
Definition at line 108 of file satellite-antenna-gain-pattern-container.h.
Referenced by SatAntennaGainPatternContainer(), GetDefaultGeoPosition(), and GetTypeId().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-antenna-gain-pattern-container.h
/builds/sns3/satellite/satellite/model/satellite-antenna-gain-pattern-container.cc