SNS3
ns3::SatFwdLinkSchedulerDefault Class Reference
SatFwdLinkSchedulerDefault schedules BB frames for forward link.
#include "satellite-fwd-link-scheduler-default.h"
Public Member Functions
SatFwdLinkSchedulerDefault ()
Construct a SatFwdLinkScheduler.
SatFwdLinkSchedulerDefault (Ptr< SatBbFrameConf > conf, Mac48Address address, double carrierBandwidthInHz)
Actual constructor of a SatFwdLinkScheduler.
~SatFwdLinkSchedulerDefault ()
Destroy a SatFwdLinkScheduler.
virtual TypeId GetInstanceTypeId (void) const
Get the type ID of instance.
virtual std::pair< Ptr< SatBbFrame >, const Time > GetNextFrame ()
Get next frame to be transmitted.
Public Member Functions inherited from ns3::SatFwdLinkScheduler
SatFwdLinkScheduler ()
Construct a SatFwdLinkScheduler.
SatFwdLinkScheduler (Ptr< SatBbFrameConf > conf, Mac48Address address, double carrierBandwidthInHz)
Actual constructor of a SatFwdLinkScheduler.
~SatFwdLinkScheduler ()
Destroy a SatFwdLinkScheduler.
void CnoInfoUpdated (Mac48Address utAddress, double cnoEstimate)
Called when UT's C/N0 estimation is updated.
Time GetDefaultFrameDuration () const
Return the BB frame duration of the default frame format, i.e.
bool SendControlMsg (Ptr< SatControlMessage > message, const Address &dest) const
Method te send a control message to a destination.
void SetDummyFrameSendingEnabled (bool dummyFrameSendingEnabled)
Set the value of m_dummyFrameSendingEnabled.
void SetSchedContextCallback (SatFwdLinkScheduler::SchedContextCallback cb)
Method to set Tx opportunity callback.
void SetSendControlMsgCallback (SatFwdLinkScheduler::SendControlMsgCallback cb)
Method to set the control message sender callback.
void SetTxOpportunityCallback (SatFwdLinkScheduler::TxOpportunityCallback cb)
Method to set Tx opportunity callback.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::SatFwdLinkScheduler
static bool CompareSoFlowId (Ptr< SatSchedulingObject > obj1, Ptr< SatSchedulingObject > obj2)
Compares to scheduling objects priorities.
static bool CompareSoPriorityHol (Ptr< SatSchedulingObject > obj1, Ptr< SatSchedulingObject > obj2)
Compares to scheduling objects priorities and HOL.
static bool CompareSoPriorityLoad (Ptr< SatSchedulingObject > obj1, Ptr< SatSchedulingObject > obj2)
Compares to scheduling objects priorities and load.
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void DoDispose (void)
Do dispose actions.
void GetSchedulingObjects (std::vector< Ptr< SatSchedulingObject >> &output)
Gets scheduling object in sorted order according to configured sorting criteria.
void PeriodicTimerExpired ()
Handles periodic timer timeouts.
void ScheduleBbFrames ()
Schedule BB Frames.
void SendAndClearSymbolsSentStat ()
Send stats and reset all the symbols sent count for each slice to zero.
Private Attributes
Ptr< SatBbFrameContainer > m_bbFrameContainer
The container for BB Frames.
Time m_schedulingStartThresholdTime
Threshold time of total transmissions in BB Frame container to trigger a scheduling round.
Time m_schedulingStopThresholdTime
Threshold time of total transmissions in BB Frame container to stop a scheduling round.
uint32_t m_symbolsSent
The number of symbols sent for each slice during an allocation cycle.
Additional Inherited Members
Public Types inherited from ns3::SatFwdLinkScheduler
typedef Callback< void, std::vector< Ptr< SatSchedulingObject > > & > SchedContextCallback
Callback to get scheduling contexts from upper layer.
enum ScheduleSortingCriteria_t {
NO_SORT , BUFFERING_DELAY_SORT , BUFFERING_LOAD_SORT , RANDOM_SORT ,
PRIORITY_SORT
}
Types for sorting algorithm used by forward link scheduler.
typedef Callback< bool, Ptr< SatControlMessage >, const Address & > SendControlMsgCallback
Callback to notify upper layer about Tx opportunity.
typedef Callback< Ptr< Packet >, uint32_t, Mac48Address, uint8_t, uint32_t &, uint32_t & > TxOpportunityCallback
Callback to notify upper layer about Tx opportunity.
Protected Types inherited from ns3::SatFwdLinkScheduler
typedef std::map< Mac48Address, Ptr< SatCnoEstimator > > CnoEstimatorMap_t
Protected Member Functions inherited from ns3::SatFwdLinkScheduler
SatFwdLinkScheduler (const SatFwdLinkScheduler &)
bool CnoMatchWithFrame (double cno, Ptr< SatBbFrame > frame) const
Check if given estimated C/N0 match with given frame.
Ptr< SatCnoEstimator > CreateCnoEstimator ()
Create estimator for the UT according to set attributes.
void DoDispose (void)
Do dispose actions.
double GetSchedulingObjectCno (Ptr< SatSchedulingObject > ob)
void GetSchedulingObjects (std::vector< Ptr< SatSchedulingObject >> &output)
Gets scheduling object in sorted order according to configured sorting criteria.
SatFwdLinkScheduler & operator= (const SatFwdLinkScheduler &)
void PeriodicTimerExpired ()
Handles periodic timer timeouts.
void ScheduleBbFrames ()
Schedule BB Frames.
void SortSchedulingObjects (std::vector< Ptr< SatSchedulingObject >> &so)
Sorts given scheduling objects according to configured sorting criteria.
Protected Attributes inherited from ns3::SatFwdLinkScheduler
ScheduleSortingCriteria_t m_additionalSortCriteria
Additional sorting criteria for scheduling objects received from LLC.
Ptr< SatBbFrameConf > m_bbFrameConf
Configured BB Frame conf.
double m_carrierBandwidthInHz
Carrier bandwidth in hertz where scheduler is associated to.
Time m_cnoEstimationWindow
Time window for C/N0 estimation.
CnoEstimatorMap_t m_cnoEstimatorContainer
C/N0 estimator per UT.
SatCnoEstimator::EstimationMode_t m_cnoEstimatorMode
Mode used for C/N0 estimator.
bool m_dummyFrameSendingEnabled
Flag indicating if Dummy Frames are sent or not.
Mac48Address m_macAddress
MAC address of the this instance (node)
Time m_periodicInterval
The interval for periodic scheduling timer.
Ptr< UniformRandomVariable > m_random
Random variable used in FWD link scheduling.
SatFwdLinkScheduler::SchedContextCallback m_schedContextCallback
The scheduling context getter callback.
TracedCallback< uint8_t, double > m_schedulingSymbolRateTrace
Traced callback for symbol rate, with flowId, requested Modcod info.
SatFwdLinkScheduler::SendControlMsgCallback m_sendControlMsgCallback
The control message sender callback.
SatFwdLinkScheduler::TxOpportunityCallback m_txOpportunityCallback
Callback to notify the txOpportunity to upper layer Returns a packet Attributes: payload in bytes.
Detailed Description
SatFwdLinkSchedulerDefault schedules BB frames for forward link.
This is the reference case of the scheduler, without separation between slices. It uses only one instance of BbFrameContainer.
   SatFwdLinkSchedulerDefault communicated through callback functions to request scheduling
objects and notifying TX opportunities.
   GW MAC requests frames from scheduler through method GetNextFrame.
Definition at line 44 of file satellite-fwd-link-scheduler-default.h.
Constructor & Destructor Documentation
SatFwdLinkSchedulerDefault() [1/2]
ns3::SatFwdLinkSchedulerDefault::SatFwdLinkSchedulerDefault ()
Construct a SatFwdLinkScheduler.
This the default constructor for the SatFwdLinkScheduler is not supported.
Definition at line 69 of file satellite-fwd-link-scheduler-default.cc.
SatFwdLinkSchedulerDefault() [2/2]
ns3::SatFwdLinkSchedulerDefault::SatFwdLinkSchedulerDefault (Ptr< SatBbFrameConf > conf, Mac48Address address, double carrierBandwidthInHz)
Actual constructor of a SatFwdLinkScheduler.
Parameters
conf BB Frame configuration
address MAC address
carrierBandwidthInHz Carrier bandwidth where scheduler is associated to [Hz].
Definition at line 76 of file satellite-fwd-link-scheduler-default.cc.
References ns3::SatFwdLinkScheduler::m_bbFrameConf, m_bbFrameContainer, ns3::SatFwdLinkScheduler::m_periodicInterval, and PeriodicTimerExpired().
~SatFwdLinkSchedulerDefault()
ns3::SatFwdLinkSchedulerDefault::~SatFwdLinkSchedulerDefault ()
Destroy a SatFwdLinkScheduler.
This is the destructor for the SatFwdLinkScheduler.
Definition at line 95 of file satellite-fwd-link-scheduler-default.cc.
Member Function Documentation
DoDispose()
void ns3::SatFwdLinkSchedulerDefault::DoDispose (void) private
Do dispose actions.
Definition at line 101 of file satellite-fwd-link-scheduler-default.cc.
References ns3::SatFwdLinkScheduler::DoDispose(), and m_bbFrameContainer.
GetInstanceTypeId()
TypeId ns3::SatFwdLinkSchedulerDefault::GetInstanceTypeId (void) const virtual
Get the type ID of instance.
Returns
the object TypeId
Reimplemented from ns3::SatFwdLinkScheduler.
Definition at line 62 of file satellite-fwd-link-scheduler-default.cc.
References GetTypeId().
GetNextFrame()
std::pair< Ptr< SatBbFrame >, const Time > ns3::SatFwdLinkSchedulerDefault::GetNextFrame () virtual
Get next frame to be transmitted.
Returns
Pointer to frame
Reimplemented from ns3::SatFwdLinkScheduler.
Definition at line 109 of file satellite-fwd-link-scheduler-default.cc.
References ns3::SatEnums::DUMMY_FRAME, ns3::SatFwdLinkScheduler::m_bbFrameConf, m_bbFrameContainer, ns3::SatFwdLinkScheduler::m_carrierBandwidthInHz, ns3::SatFwdLinkScheduler::m_dummyFrameSendingEnabled, ns3::SatFwdLinkScheduler::m_macAddress, m_schedulingStartThresholdTime, m_symbolsSent, ScheduleBbFrames(), ns3::SatMacTag::SetDestAddress(), ns3::SatAddressE2ETag::SetE2EDestAddress(), ns3::SatAddressE2ETag::SetE2ESourceAddress(), and ns3::SatMacTag::SetSourceAddress().
GetSchedulingObjects()
void ns3::SatFwdLinkSchedulerDefault::GetSchedulingObjects (std::vector< Ptr< SatSchedulingObject >> & output) private
Gets scheduling object in sorted order according to configured sorting criteria.
Parameters
output reference to a vector which will be filled with pointers to the scheduling objects available for scheduling.
Definition at line 257 of file satellite-fwd-link-scheduler-default.cc.
References m_bbFrameContainer, ns3::SatFwdLinkScheduler::m_schedContextCallback, m_schedulingStopThresholdTime, and ns3::SatFwdLinkScheduler::SortSchedulingObjects().
Referenced by ScheduleBbFrames().
GetTypeId()
TypeId ns3::SatFwdLinkSchedulerDefault::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 33 of file satellite-fwd-link-scheduler-default.cc.
References m_bbFrameContainer, m_schedulingStartThresholdTime, and m_schedulingStopThresholdTime.
Referenced by GetInstanceTypeId().
PeriodicTimerExpired()
void ns3::SatFwdLinkSchedulerDefault::PeriodicTimerExpired () private
Handles periodic timer timeouts.
Definition at line 169 of file satellite-fwd-link-scheduler-default.cc.
References ns3::SatFwdLinkScheduler::m_periodicInterval, ScheduleBbFrames(), and SendAndClearSymbolsSentStat().
Referenced by SatFwdLinkSchedulerDefault().
ScheduleBbFrames()
void ns3::SatFwdLinkSchedulerDefault::ScheduleBbFrames () private
Schedule BB Frames.
Definition at line 192 of file satellite-fwd-link-scheduler-default.cc.
References ns3::SatFwdLinkScheduler::GetSchedulingObjectCno(), GetSchedulingObjects(), ns3::SatFwdLinkScheduler::m_bbFrameConf, m_bbFrameContainer, ns3::SatFwdLinkScheduler::m_carrierBandwidthInHz, m_schedulingStopThresholdTime, and ns3::SatFwdLinkScheduler::m_txOpportunityCallback.
Referenced by GetNextFrame(), and PeriodicTimerExpired().
SendAndClearSymbolsSentStat()
void ns3::SatFwdLinkSchedulerDefault::SendAndClearSymbolsSentStat () private virtual
Send stats and reset all the symbols sent count for each slice to zero.
Reimplemented from ns3::SatFwdLinkScheduler.
Definition at line 182 of file satellite-fwd-link-scheduler-default.cc.
References ns3::SatFwdLinkScheduler::m_schedulingSymbolRateTrace, and m_symbolsSent.
Referenced by PeriodicTimerExpired().
Member Data Documentation
m_bbFrameContainer
Ptr<SatBbFrameContainer> ns3::SatFwdLinkSchedulerDefault::m_bbFrameContainer private
The container for BB Frames.
Definition at line 124 of file satellite-fwd-link-scheduler-default.h.
Referenced by SatFwdLinkSchedulerDefault(), DoDispose(), GetNextFrame(), GetSchedulingObjects(), GetTypeId(), and ScheduleBbFrames().
m_schedulingStartThresholdTime
Time ns3::SatFwdLinkSchedulerDefault::m_schedulingStartThresholdTime private
Threshold time of total transmissions in BB Frame container to trigger a scheduling round.
Definition at line 129 of file satellite-fwd-link-scheduler-default.h.
Referenced by GetNextFrame(), and GetTypeId().
m_schedulingStopThresholdTime
Time ns3::SatFwdLinkSchedulerDefault::m_schedulingStopThresholdTime private
Threshold time of total transmissions in BB Frame container to stop a scheduling round.
Definition at line 134 of file satellite-fwd-link-scheduler-default.h.
Referenced by GetSchedulingObjects(), GetTypeId(), and ScheduleBbFrames().
m_symbolsSent
uint32_t ns3::SatFwdLinkSchedulerDefault::m_symbolsSent private
The number of symbols sent for each slice during an allocation cycle.
Definition at line 139 of file satellite-fwd-link-scheduler-default.h.
Referenced by GetNextFrame(), and SendAndClearSymbolsSentStat().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-fwd-link-scheduler-default.h
/builds/sns3/satellite/satellite/model/satellite-fwd-link-scheduler-default.cc