SNS3
ns3::SatStatsCarrierIdHelper Class Reference
Satellite Statistics
#include "satellite-stats-carrier-id-helper.h"
Public Member Functions
SatStatsCarrierIdHelper (Ptr< const SatHelper > satHelper)
virtual ~SatStatsCarrierIdHelper ()
/ Destructor.
void CarrierIdRxCallback (uint32_t carrierId, const Address &from)
Receive inputs from trace sources and determine the right collector to forward the inputs to.
std::string GetTraceSourceName () const
SatPhyRxCarrier::CarrierType GetValidCarrierType () const
Get the valid carrier type.
Public Member Functions inherited from ns3::SatStatsHelper
SatStatsHelper (Ptr< const SatHelper > satHelper)
Creates a new helper instance.
virtual ~SatStatsHelper ()
/ Destructor.
IdentifierType_t GetIdentifierType () const
std::string GetName () const
OutputType_t GetOutputType () const
Ptr< const SatHelper > GetSatHelper () const
void Install ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
bool IsInstalled () const
void SetIdentifierType (IdentifierType_t identifierType)
void SetName (std::string name)
void SetOutputType (OutputType_t outputType)
Static Public Member Functions
static TypeId GetTypeId ()
inherited from ObjectBase base class
Static Public Member Functions inherited from ns3::SatStatsHelper
static std::string GetIdentifierTypeName (IdentifierType_t identifierType)
static std::string GetOutputTypeName (OutputType_t outputType)
static TypeId GetTypeId ()
inherited from ObjectBase base class
Protected Member Functions
void DoInstall ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
void SetTraceSourceName (std::string traceSourceName)
void SetValidCarrierType (SatPhyRxCarrier::CarrierType carrierType)
Set valid carrier type for this statistics helper type.
Protected Member Functions inherited from ns3::SatStatsHelper
Ptr< DataCollectionObject > CreateAggregator (std::string aggregatorTypeId, std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue())
Create the aggregator according to the output type.
uint32_t CreateCollectorPerIdentifier (CollectorMap &collectorMap) const
Create one collector instance for each identifier in the simulation.
virtual std::string GetDistributionHeading (std::string dataLabel) const
uint32_t GetGwId (Ptr< Node > gwNode) const
uint32_t GetIdentifierForBeam (uint32_t satId, uint32_t beamId) const
uint32_t GetIdentifierForGroup (uint32_t groupId) const
uint32_t GetIdentifierForGw (Ptr< Node > gwNode) const
uint32_t GetIdentifierForIsl (Ptr< Node > satNodeSrc, Ptr< Node > satNodeDst) const
uint32_t GetIdentifierForSat (Ptr< Node > satNode) const
uint32_t GetIdentifierForUt (Ptr< Node > utNode) const
uint32_t GetIdentifierForUtUser (Ptr< Node > utUserNode) const
virtual std::string GetIdentifierHeading (std::string dataLabel) const
virtual std::string GetOutputFileName () const
Compute the path and file name where statistics output should be written to.
virtual std::string GetOutputPath () const
uint32_t GetSatId (Ptr< Node > satNode) const
virtual std::string GetTimeHeading (std::string dataLabel) const
uint32_t GetUtId (Ptr< Node > utNode) const
uint32_t GetUtUserId (Ptr< Node > utUserNode) const
Private Member Functions
void SaveAddressAndIdentifier (Ptr< Node > utNode)
Save the address and the proper identifier from the given UT node.
Private Attributes
Ptr< DataCollectionObject > m_aggregator
The aggregator created by this helper.
SatPhyRxCarrier::CarrierType m_carrierType
std::map< const Address, uint32_t > m_identifierMap
Map of address and the identifier associated with it (for forward link).
CollectorMap m_terminalCollectors
Maintains a list of collectors created by this helper.
std::string m_traceSourceName
Additional Inherited Members
Public Types inherited from ns3::SatStatsHelper
enum IdentifierType_t {
IDENTIFIER_GLOBAL = 0 , IDENTIFIER_GW , IDENTIFIER_BEAM , IDENTIFIER_UT ,
IDENTIFIER_UT_USER , IDENTIFIER_SLICE , IDENTIFIER_GROUP , IDENTIFIER_SAT ,
IDENTIFIER_ISL
}
Possible categorization of statistics output.
enum OutputType_t {
OUTPUT_NONE = 0 , OUTPUT_SCALAR_FILE , OUTPUT_SCATTER_FILE , OUTPUT_HISTOGRAM_FILE ,
OUTPUT_PDF_FILE , OUTPUT_CDF_FILE , OUTPUT_SCALAR_PLOT , OUTPUT_SCATTER_PLOT ,
OUTPUT_HISTOGRAM_PLOT , OUTPUT_PDF_PLOT , OUTPUT_CDF_PLOT
}
Possible types and formats of statistics output.
Static Protected Member Functions inherited from ns3::SatStatsHelper
static NetDeviceContainer GetGwSatNetDevice (Ptr< Node > gwNode)
static Ptr< NetDevice > GetSatSatGeoNetDevice (Ptr< Node > satNode)
static Ptr< NetDevice > GetUtSatNetDevice (Ptr< Node > utNode)
Detailed Description
Definition at line 45 of file satellite-stats-carrier-id-helper.h.
Constructor & Destructor Documentation
SatStatsCarrierIdHelper()
ns3::SatStatsCarrierIdHelper::SatStatsCarrierIdHelper (Ptr< const SatHelper > satHelper)
Definition at line 56 of file satellite-stats-carrier-id-helper.cc.
References ns3::SatPhyRxCarrier::DEDICATED_ACCESS, SetTraceSourceName(), and SetValidCarrierType().
~SatStatsCarrierIdHelper()
ns3::SatStatsCarrierIdHelper::~SatStatsCarrierIdHelper () virtual
/ Destructor.
Definition at line 64 of file satellite-stats-carrier-id-helper.cc.
Member Function Documentation
CarrierIdRxCallback()
void ns3::SatStatsCarrierIdHelper::CarrierIdRxCallback (uint32_t carrierId, const Address & from)
Receive inputs from trace sources and determine the right collector to forward the inputs to.
Parameters
carrierId carrier used by the received packet burst.
from the source address of the packet.
Definition at line 290 of file satellite-stats-carrier-id-helper.cc.
References ns3::SatStatsHelper::GetOutputType(), ns3::SatStatsHelper::GetOutputTypeName(), m_identifierMap, m_terminalCollectors, ns3::SatStatsHelper::OUTPUT_SCALAR_FILE, ns3::SatStatsHelper::OUTPUT_SCALAR_PLOT, ns3::SatStatsHelper::OUTPUT_SCATTER_FILE, and ns3::SatStatsHelper::OUTPUT_SCATTER_PLOT.
Referenced by DoInstall().
DoInstall()
void ns3::SatStatsCarrierIdHelper::DoInstall () protected virtual
Install the probes, collectors, and aggregators necessary to produce the statistics output.
An abstract method of SatStatsHelper which must be implemented by child classes. It will be invoked by Install().
Todo:
Add support for boxes in Gnuplot.
Implements ns3::SatStatsHelper.
Definition at line 90 of file satellite-stats-carrier-id-helper.cc.
References CarrierIdRxCallback(), ns3::SatStatsHelper::CreateAggregator(), ns3::SatStatsHelper::CreateCollectorPerIdentifier(), ns3::SatStatsHelper::GetGwSatNetDevice(), ns3::SatStatsHelper::GetIdentifierHeading(), ns3::SatStatsHelper::GetName(), ns3::SatStatsHelper::GetOutputFileName(), ns3::SatStatsHelper::GetOutputPath(), ns3::SatStatsHelper::GetOutputType(), ns3::SatStatsHelper::GetOutputTypeName(), ns3::SatStatsHelper::GetSatHelper(), ns3::SatStatsHelper::GetTimeHeading(), GetTraceSourceName(), GetValidCarrierType(), m_aggregator, m_terminalCollectors, ns3::SatStatsHelper::OUTPUT_CDF_FILE, ns3::SatStatsHelper::OUTPUT_CDF_PLOT, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_FILE, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_PLOT, ns3::SatStatsHelper::OUTPUT_NONE, ns3::SatStatsHelper::OUTPUT_PDF_FILE, ns3::SatStatsHelper::OUTPUT_PDF_PLOT, ns3::SatStatsHelper::OUTPUT_SCALAR_FILE, ns3::SatStatsHelper::OUTPUT_SCALAR_PLOT, ns3::SatStatsHelper::OUTPUT_SCATTER_FILE, ns3::SatStatsHelper::OUTPUT_SCATTER_PLOT, and SaveAddressAndIdentifier().
GetTraceSourceName()
std::string ns3::SatStatsCarrierIdHelper::GetTraceSourceName () const
Returns
Definition at line 84 of file satellite-stats-carrier-id-helper.cc.
References m_traceSourceName.
Referenced by DoInstall().
GetTypeId()
TypeId ns3::SatStatsCarrierIdHelper::GetTypeId (void) static
inherited from ObjectBase base class
Definition at line 70 of file satellite-stats-carrier-id-helper.cc.
GetValidCarrierType()
SatPhyRxCarrier::CarrierType ns3::SatStatsCarrierIdHelper::GetValidCarrierType () const inline
Get the valid carrier type.
Returns
the valid carrier type
Definition at line 78 of file satellite-stats-carrier-id-helper.h.
References m_carrierType.
Referenced by DoInstall().
SaveAddressAndIdentifier()
void ns3::SatStatsCarrierIdHelper::SaveAddressAndIdentifier (Ptr< Node > utNode) private
Save the address and the proper identifier from the given UT node.
Parameters
utNode a UT node.
The address of the given node will be saved in the m_identifierMap member variable.
Definition at line 343 of file satellite-stats-carrier-id-helper.cc.
References ns3::SatStatsHelper::GetIdentifierForUt(), ns3::SatIdMapper::GetUtMacWithNode(), and m_identifierMap.
Referenced by DoInstall().
SetTraceSourceName()
void ns3::SatStatsCarrierIdHelper::SetTraceSourceName (std::string traceSourceName) protected
Parameters
traceSourceName
Definition at line 77 of file satellite-stats-carrier-id-helper.cc.
References m_traceSourceName.
Referenced by SatStatsCarrierIdHelper().
SetValidCarrierType()
void ns3::SatStatsCarrierIdHelper::SetValidCarrierType (SatPhyRxCarrier::CarrierType carrierType) inline protected
Set valid carrier type for this statistics helper type.
Parameters
carrierType
Definition at line 96 of file satellite-stats-carrier-id-helper.h.
References m_carrierType.
Referenced by SatStatsCarrierIdHelper().
Member Data Documentation
m_aggregator
Ptr<DataCollectionObject> ns3::SatStatsCarrierIdHelper::m_aggregator private
The aggregator created by this helper.
Definition at line 115 of file satellite-stats-carrier-id-helper.h.
Referenced by DoInstall().
m_carrierType
SatPhyRxCarrier::CarrierType ns3::SatStatsCarrierIdHelper::m_carrierType private
Definition at line 122 of file satellite-stats-carrier-id-helper.h.
Referenced by GetValidCarrierType(), and SetValidCarrierType().
m_identifierMap
std::map<const Address, uint32_t> ns3::SatStatsCarrierIdHelper::m_identifierMap private
Map of address and the identifier associated with it (for forward link).
Definition at line 118 of file satellite-stats-carrier-id-helper.h.
Referenced by CarrierIdRxCallback(), and SaveAddressAndIdentifier().
m_terminalCollectors
CollectorMap ns3::SatStatsCarrierIdHelper::m_terminalCollectors private
Maintains a list of collectors created by this helper.
Definition at line 112 of file satellite-stats-carrier-id-helper.h.
Referenced by CarrierIdRxCallback(), and DoInstall().
m_traceSourceName
std::string ns3::SatStatsCarrierIdHelper::m_traceSourceName private
Definition at line 120 of file satellite-stats-carrier-id-helper.h.
Referenced by GetTraceSourceName(), and SetTraceSourceName().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/stats/satellite-stats-carrier-id-helper.h
/builds/sns3/satellite/satellite/stats/satellite-stats-carrier-id-helper.cc