SNS3
ns3::SatTimeTag Class Reference
Time tag used to identify the time when packet is enqueued at LLC level.
#include "satellite-time-tag.h"
Public Member Functions
SatTimeTag ()
Default constructor.
SatTimeTag (Time senderTimestamp)
Constructor with initialization parameters.
virtual void Deserialize (TagBuffer i)
Deserializes information from buffer to this instance of SatTimeTag.
virtual TypeId GetInstanceTypeId (void) const
Get the type ID of instance.
Time GetSenderTimestamp (void) const
Get sender time stamp of this tag.
virtual uint32_t GetSerializedSize () const
Get serialized size of SatTimeTag.
virtual void Print (std::ostream &os) const
Print time stamp of this instance of SatTimeTag.
virtual void Serialize (TagBuffer i) const
Serializes information to buffer from this instance of SatTimeTag.
void SetSenderTimestamp (Time senderTimestamp)
Set sender time stamp of this tag.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Time m_senderTimestamp
Detailed Description
Time tag used to identify the time when packet is enqueued at LLC level.
Definition at line 41 of file satellite-time-tag.h.
Constructor & Destructor Documentation
SatTimeTag() [1/2]
ns3::SatTimeTag::SatTimeTag ()
Default constructor.
Definition at line 36 of file satellite-time-tag.cc.
SatTimeTag() [2/2]
ns3::SatTimeTag::SatTimeTag (Time senderTimestamp)
Constructor with initialization parameters.
Parameters
senderTimestamp
Definition at line 42 of file satellite-time-tag.cc.
Member Function Documentation
Deserialize()
void ns3::SatTimeTag::Deserialize (TagBuffer i) virtual
Deserializes information from buffer to this instance of SatTimeTag.
Parameters
i Buffer from which the information is deserialized
Definition at line 75 of file satellite-time-tag.cc.
References m_senderTimestamp.
GetInstanceTypeId()
TypeId ns3::SatTimeTag::GetInstanceTypeId (void) const virtual
Get the type ID of instance.
Returns
the object TypeId
Definition at line 56 of file satellite-time-tag.cc.
References GetTypeId().
GetSenderTimestamp()
Time ns3::SatTimeTag::GetSenderTimestamp (void) const
Get sender time stamp of this tag.
Returns
Sender timestamp
Definition at line 89 of file satellite-time-tag.cc.
References m_senderTimestamp.
Referenced by ns3::SatBaseEncapsulator::GetHolDelay().
GetSerializedSize()
uint32_t ns3::SatTimeTag::GetSerializedSize (void) const virtual
Get serialized size of SatTimeTag.
Returns
Serialized size in bytes
Definition at line 62 of file satellite-time-tag.cc.
GetTypeId()
TypeId ns3::SatTimeTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 49 of file satellite-time-tag.cc.
Referenced by GetInstanceTypeId().
Print()
void ns3::SatTimeTag::Print (std::ostream & os) const virtual
Print time stamp of this instance of SatTimeTag.
Parameters
&os Output stream to which tag timestamp is printed.
Definition at line 83 of file satellite-time-tag.cc.
References m_senderTimestamp.
Serialize()
void ns3::SatTimeTag::Serialize (TagBuffer i) const virtual
Serializes information to buffer from this instance of SatTimeTag.
Parameters
i Buffer in which the information is serialized
Definition at line 68 of file satellite-time-tag.cc.
References m_senderTimestamp.
SetSenderTimestamp()
void ns3::SatTimeTag::SetSenderTimestamp (Time senderTimestamp)
Set sender time stamp of this tag.
Parameters
senderTimestamp Sender time stamp
Definition at line 95 of file satellite-time-tag.cc.
References m_senderTimestamp.
Member Data Documentation
m_senderTimestamp
Time ns3::SatTimeTag::m_senderTimestamp private
Definition at line 104 of file satellite-time-tag.h.
Referenced by Deserialize(), GetSenderTimestamp(), Print(), Serialize(), and SetSenderTimestamp().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-time-tag.h
/builds/sns3/satellite/satellite/model/satellite-time-tag.cc