SNS3
ns3::SatStatsLinkJitterHelper Class Reference abstract
Satellite Statistics
Base class for jitter statistics helpers.
#include "satellite-stats-link-jitter-helper.h"
Public Member Functions
SatStatsLinkJitterHelper (Ptr< const SatHelper > satHelper)
virtual ~SatStatsLinkJitterHelper ()
/ Destructor.
bool GetAveragingMode () const
void InstallProbes ()
Set up several probes or other means of listeners and connect them to the collectors.
void RxLinkJitterCallback (const Time &jitter, const Address &from)
Receive inputs from trace sources and determine the right collector to forward the inputs to.
void SetAveragingMode (bool averagingMode)
Public Member Functions inherited from ns3::SatStatsHelper
SatStatsHelper (Ptr< const SatHelper > satHelper)
Creates a new helper instance.
virtual ~SatStatsHelper ()
/ Destructor.
IdentifierType_t GetIdentifierType () const
std::string GetName () const
OutputType_t GetOutputType () const
Ptr< const SatHelper > GetSatHelper () const
void Install ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
bool IsInstalled () const
void SetIdentifierType (IdentifierType_t identifierType)
void SetName (std::string name)
void SetOutputType (OutputType_t outputType)
Static Public Member Functions
static TypeId GetTypeId ()
inherited from ObjectBase base class
Static Public Member Functions inherited from ns3::SatStatsHelper
static std::string GetIdentifierTypeName (IdentifierType_t identifierType)
static std::string GetOutputTypeName (OutputType_t outputType)
static TypeId GetTypeId ()
inherited from ObjectBase base class
Protected Member Functions
bool ConnectProbeToCollector (Ptr< Probe > probe, uint32_t identifier)
Connect the probe to the right collector.
void DoInstall ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
virtual void DoInstallProbes ()=0
void PassSampleToCollector (const Time &jitter, uint32_t identifier)
Find a collector with the right identifier and pass a sample data to it.
void SaveAddressAndIdentifier (Ptr< Node > utNode)
Save the address and the proper identifier from the given UT node.
void SetChannelLink (SatEnums::ChannelType_t channelLink)
Set the channel used by this probe.
Protected Member Functions inherited from ns3::SatStatsHelper
Ptr< DataCollectionObject > CreateAggregator (std::string aggregatorTypeId, std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue())
Create the aggregator according to the output type.
uint32_t CreateCollectorPerIdentifier (CollectorMap &collectorMap) const
Create one collector instance for each identifier in the simulation.
virtual std::string GetDistributionHeading (std::string dataLabel) const
uint32_t GetGwId (Ptr< Node > gwNode) const
uint32_t GetIdentifierForBeam (uint32_t satId, uint32_t beamId) const
uint32_t GetIdentifierForGroup (uint32_t groupId) const
uint32_t GetIdentifierForGw (Ptr< Node > gwNode) const
uint32_t GetIdentifierForIsl (Ptr< Node > satNodeSrc, Ptr< Node > satNodeDst) const
uint32_t GetIdentifierForSat (Ptr< Node > satNode) const
uint32_t GetIdentifierForUt (Ptr< Node > utNode) const
uint32_t GetIdentifierForUtUser (Ptr< Node > utUserNode) const
virtual std::string GetIdentifierHeading (std::string dataLabel) const
virtual std::string GetOutputFileName () const
Compute the path and file name where statistics output should be written to.
virtual std::string GetOutputPath () const
uint32_t GetSatId (Ptr< Node > satNode) const
virtual std::string GetTimeHeading (std::string dataLabel) const
uint32_t GetUtId (Ptr< Node > utNode) const
uint32_t GetUtUserId (Ptr< Node > utUserNode) const
Protected Attributes
Ptr< DataCollectionObject > m_aggregator
The aggregator created by this helper.
Ptr< DistributionCollector > m_averagingCollector
The final collector utilized in averaged output (histogram, PDF, and CDF).
std::map< const Address, uint32_t > m_identifierMap
Map of address and the identifier associated with it (for return link).
CollectorMap m_terminalCollectors
Maintains a list of collectors created by this helper.
Private Attributes
bool m_averagingMode
AveragingMode attribute.
SatEnums::ChannelType_t m_channelLink
Additional Inherited Members
Public Types inherited from ns3::SatStatsHelper
enum IdentifierType_t {
IDENTIFIER_GLOBAL = 0 , IDENTIFIER_GW , IDENTIFIER_BEAM , IDENTIFIER_UT ,
IDENTIFIER_UT_USER , IDENTIFIER_SLICE , IDENTIFIER_GROUP , IDENTIFIER_SAT ,
IDENTIFIER_ISL
}
Possible categorization of statistics output.
enum OutputType_t {
OUTPUT_NONE = 0 , OUTPUT_SCALAR_FILE , OUTPUT_SCATTER_FILE , OUTPUT_HISTOGRAM_FILE ,
OUTPUT_PDF_FILE , OUTPUT_CDF_FILE , OUTPUT_SCALAR_PLOT , OUTPUT_SCATTER_PLOT ,
OUTPUT_HISTOGRAM_PLOT , OUTPUT_PDF_PLOT , OUTPUT_CDF_PLOT
}
Possible types and formats of statistics output.
Static Protected Member Functions inherited from ns3::SatStatsHelper
static NetDeviceContainer GetGwSatNetDevice (Ptr< Node > gwNode)
static Ptr< NetDevice > GetSatSatGeoNetDevice (Ptr< Node > satNode)
static Ptr< NetDevice > GetUtSatNetDevice (Ptr< Node > utNode)
Detailed Description
Base class for jitter statistics helpers.
Definition at line 49 of file satellite-stats-link-jitter-helper.h.
Constructor & Destructor Documentation
SatStatsLinkJitterHelper()
ns3::SatStatsLinkJitterHelper::SatStatsLinkJitterHelper (Ptr< const SatHelper > satHelper)
Definition at line 63 of file satellite-stats-link-jitter-helper.cc.
~SatStatsLinkJitterHelper()
ns3::SatStatsLinkJitterHelper::~SatStatsLinkJitterHelper () virtual
/ Destructor.
Definition at line 70 of file satellite-stats-link-jitter-helper.cc.
Member Function Documentation
ConnectProbeToCollector()
bool ns3::SatStatsLinkJitterHelper::ConnectProbeToCollector (Ptr< Probe > probe, uint32_t identifier) protected
Connect the probe to the right collector.
Parameters
probe
identifier
Definition at line 474 of file satellite-stats-link-jitter-helper.cc.
References ns3::SatStatsHelper::GetOutputType(), ns3::SatStatsHelper::GetOutputTypeName(), m_averagingMode, m_terminalCollectors, ns3::SatStatsHelper::OUTPUT_CDF_FILE, ns3::SatStatsHelper::OUTPUT_CDF_PLOT, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_FILE, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_PLOT, ns3::SatStatsHelper::OUTPUT_PDF_FILE, ns3::SatStatsHelper::OUTPUT_PDF_PLOT, ns3::SatStatsHelper::OUTPUT_SCALAR_FILE, ns3::SatStatsHelper::OUTPUT_SCALAR_PLOT, ns3::SatStatsHelper::OUTPUT_SCATTER_FILE, and ns3::SatStatsHelper::OUTPUT_SCATTER_PLOT.
Referenced by ns3::SatStatsFwdUserDevLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdUserMacLinkJitterHelper::DoInstallProbes(), and ns3::SatStatsFwdUserPhyLinkJitterHelper::DoInstallProbes().
DoInstall()
void ns3::SatStatsLinkJitterHelper::DoInstall () protected virtual
Install the probes, collectors, and aggregators necessary to produce the statistics output.
An abstract method of SatStatsHelper which must be implemented by child classes. It will be invoked by Install().
Todo:
Add support for boxes in Gnuplot.
Todo:
Find a better dataset name.
Todo:
Find a better dataset name.
Implements ns3::SatStatsHelper.
Definition at line 105 of file satellite-stats-link-jitter-helper.cc.
References ns3::SatStatsHelper::CreateAggregator(), ns3::SatStatsHelper::CreateCollectorPerIdentifier(), ns3::SatStatsHelper::GetDistributionHeading(), ns3::SatStatsHelper::GetIdentifierHeading(), ns3::SatStatsHelper::GetName(), ns3::SatStatsHelper::GetOutputFileName(), ns3::SatStatsHelper::GetOutputPath(), ns3::SatStatsHelper::GetOutputType(), ns3::SatStatsHelper::GetOutputTypeName(), ns3::SatStatsHelper::GetTimeHeading(), InstallProbes(), m_aggregator, m_averagingCollector, m_averagingMode, m_terminalCollectors, ns3::SatStatsHelper::OUTPUT_CDF_FILE, ns3::SatStatsHelper::OUTPUT_CDF_PLOT, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_FILE, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_PLOT, ns3::SatStatsHelper::OUTPUT_NONE, ns3::SatStatsHelper::OUTPUT_PDF_FILE, ns3::SatStatsHelper::OUTPUT_PDF_PLOT, ns3::SatStatsHelper::OUTPUT_SCALAR_FILE, ns3::SatStatsHelper::OUTPUT_SCALAR_PLOT, ns3::SatStatsHelper::OUTPUT_SCATTER_FILE, and ns3::SatStatsHelper::OUTPUT_SCATTER_PLOT.
DoInstallProbes()
virtual void ns3::SatStatsLinkJitterHelper::DoInstallProbes () protected pure virtual
Implemented in ns3::SatStatsRtnUserPhyLinkJitterHelper, ns3::SatStatsRtnFeederPhyLinkJitterHelper, ns3::SatStatsRtnUserMacLinkJitterHelper, ns3::SatStatsRtnFeederMacLinkJitterHelper, ns3::SatStatsRtnUserDevLinkJitterHelper, ns3::SatStatsRtnFeederDevLinkJitterHelper, ns3::SatStatsFwdUserPhyLinkJitterHelper, ns3::SatStatsFwdFeederPhyLinkJitterHelper, ns3::SatStatsFwdUserMacLinkJitterHelper, ns3::SatStatsFwdFeederMacLinkJitterHelper, ns3::SatStatsFwdUserDevLinkJitterHelper, and ns3::SatStatsFwdFeederDevLinkJitterHelper.
Referenced by InstallProbes().
GetAveragingMode()
bool ns3::SatStatsLinkJitterHelper::GetAveragingMode () const
Returns
the currently active averaging mode.
Definition at line 99 of file satellite-stats-link-jitter-helper.cc.
References m_averagingMode.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::SatStatsLinkJitterHelper::GetTypeId (void) static
inherited from ObjectBase base class
Definition at line 76 of file satellite-stats-link-jitter-helper.cc.
References GetAveragingMode(), and SetAveragingMode().
InstallProbes()
void ns3::SatStatsLinkJitterHelper::InstallProbes ()
Set up several probes or other means of listeners and connect them to the collectors.
Definition at line 411 of file satellite-stats-link-jitter-helper.cc.
References DoInstallProbes().
Referenced by DoInstall().
PassSampleToCollector()
void ns3::SatStatsLinkJitterHelper::PassSampleToCollector (const Time & jitter, uint32_t identifier) protected
Find a collector with the right identifier and pass a sample data to it.
Parameters
jitter
identifier
Definition at line 540 of file satellite-stats-link-jitter-helper.cc.
References ns3::SatStatsHelper::GetOutputType(), ns3::SatStatsHelper::GetOutputTypeName(), m_averagingMode, m_terminalCollectors, ns3::SatStatsHelper::OUTPUT_CDF_FILE, ns3::SatStatsHelper::OUTPUT_CDF_PLOT, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_FILE, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_PLOT, ns3::SatStatsHelper::OUTPUT_PDF_FILE, ns3::SatStatsHelper::OUTPUT_PDF_PLOT, ns3::SatStatsHelper::OUTPUT_SCALAR_FILE, ns3::SatStatsHelper::OUTPUT_SCALAR_PLOT, ns3::SatStatsHelper::OUTPUT_SCATTER_FILE, and ns3::SatStatsHelper::OUTPUT_SCATTER_PLOT.
Referenced by RxLinkJitterCallback().
RxLinkJitterCallback()
void ns3::SatStatsLinkJitterHelper::RxLinkJitterCallback (const Time & jitter, const Address & from)
Receive inputs from trace sources and determine the right collector to forward the inputs to.
Parameters
jitter packet jitter.
from the address of the sender of the packet.
Used in return link statistics. DoInstallProbes() is expected to connect the right trace sources to this method.
Definition at line 418 of file satellite-stats-link-jitter-helper.cc.
References m_identifierMap, and PassSampleToCollector().
Referenced by ns3::SatStatsFwdFeederDevLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdFeederMacLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdFeederPhyLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnFeederDevLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnUserDevLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnFeederMacLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnUserMacLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnFeederPhyLinkJitterHelper::DoInstallProbes(), and ns3::SatStatsRtnUserPhyLinkJitterHelper::DoInstallProbes().
SaveAddressAndIdentifier()
void ns3::SatStatsLinkJitterHelper::SaveAddressAndIdentifier (Ptr< Node > utNode) protected
Save the address and the proper identifier from the given UT node.
Parameters
utNode a UT node.
The address of the given node will be saved in the m_identifierMap member variable.
Used in return link statistics. DoInstallProbes() is expected to pass the the UT node of interest into this method.
Definition at line 454 of file satellite-stats-link-jitter-helper.cc.
References ns3::SatStatsHelper::GetIdentifierForUt(), ns3::SatIdMapper::GetUtMacWithNode(), and m_identifierMap.
Referenced by ns3::SatStatsFwdFeederDevLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdFeederMacLinkJitterHelper::DoInstallProbes(), ns3::SatStatsFwdFeederPhyLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnFeederDevLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnUserDevLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnFeederMacLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnUserMacLinkJitterHelper::DoInstallProbes(), ns3::SatStatsRtnFeederPhyLinkJitterHelper::DoInstallProbes(), and ns3::SatStatsRtnUserPhyLinkJitterHelper::DoInstallProbes().
SetAveragingMode()
void ns3::SatStatsLinkJitterHelper::SetAveragingMode (bool averagingMode)
Parameters
averagingMode average all samples before passing them to aggregator.
Definition at line 92 of file satellite-stats-link-jitter-helper.cc.
References m_averagingMode.
Referenced by GetTypeId().
SetChannelLink()
void ns3::SatStatsLinkJitterHelper::SetChannelLink (SatEnums::ChannelType_t channelLink) protected
Set the channel used by this probe.
Parameters
channelLink The channel used.
Definition at line 595 of file satellite-stats-link-jitter-helper.cc.
References m_channelLink.
Referenced by ns3::SatStatsFwdFeederPhyLinkJitterHelper::SatStatsFwdFeederPhyLinkJitterHelper(), ns3::SatStatsFwdUserPhyLinkJitterHelper::SatStatsFwdUserPhyLinkJitterHelper(), ns3::SatStatsRtnFeederPhyLinkJitterHelper::SatStatsRtnFeederPhyLinkJitterHelper(), and ns3::SatStatsRtnUserPhyLinkJitterHelper::SatStatsRtnUserPhyLinkJitterHelper().
Member Data Documentation
m_aggregator
Ptr<DataCollectionObject> ns3::SatStatsLinkJitterHelper::m_aggregator protected
The aggregator created by this helper.
Definition at line 141 of file satellite-stats-link-jitter-helper.h.
Referenced by DoInstall().
m_averagingCollector
Ptr<DistributionCollector> ns3::SatStatsLinkJitterHelper::m_averagingCollector protected
The final collector utilized in averaged output (histogram, PDF, and CDF).
Definition at line 138 of file satellite-stats-link-jitter-helper.h.
Referenced by DoInstall().
m_averagingMode
bool ns3::SatStatsLinkJitterHelper::m_averagingMode private
AveragingMode attribute.
Definition at line 147 of file satellite-stats-link-jitter-helper.h.
Referenced by ConnectProbeToCollector(), DoInstall(), GetAveragingMode(), PassSampleToCollector(), and SetAveragingMode().
m_channelLink
SatEnums::ChannelType_t ns3::SatStatsLinkJitterHelper::m_channelLink private
Definition at line 149 of file satellite-stats-link-jitter-helper.h.
Referenced by SetChannelLink().
m_identifierMap
std::map<const Address, uint32_t> ns3::SatStatsLinkJitterHelper::m_identifierMap protected
Map of address and the identifier associated with it (for return link).
Definition at line 144 of file satellite-stats-link-jitter-helper.h.
Referenced by RxLinkJitterCallback(), and SaveAddressAndIdentifier().
m_terminalCollectors
CollectorMap ns3::SatStatsLinkJitterHelper::m_terminalCollectors protected
Maintains a list of collectors created by this helper.
Definition at line 135 of file satellite-stats-link-jitter-helper.h.
Referenced by ConnectProbeToCollector(), DoInstall(), and PassSampleToCollector().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/stats/satellite-stats-link-jitter-helper.h
/builds/sns3/satellite/satellite/stats/satellite-stats-link-jitter-helper.cc