SNS3
ns3::PointToPointIslChannel Class Reference
Point to Point ISL Channel.
#include "satellite-point-to-point-isl-channel.h"
Classes
class Link
Wire model for the PointToPointIslChannel.
Public Member Functions
PointToPointIslChannel ()
Create a PointToPointIslChannel.
void Attach (Ptr< PointToPointIslNetDevice > device)
Attach a given netdevice to this channel.
virtual Ptr< NetDevice > GetDevice (std::size_t i) const
Get NetDevice corresponding to index i on this channel.
virtual std::size_t GetNDevices (void) const
Get number of devices on this channel.
Ptr< PointToPointIslNetDevice > GetPointToPointIslDevice (std::size_t i) const
Get PointToPointIslNetDevice corresponding to index i on this channel.
virtual bool TransmitStart (Ptr< const Packet > p, Ptr< PointToPointIslNetDevice > src, Ptr< Node > dst, Time txTime)
Transmit a packet over this channel.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the TypeId.
Protected Member Functions
Time GetDelay (Ptr< MobilityModel > senderMobility, Ptr< MobilityModel > receiverMobility) const
Get the delay between two nodes on this channel.
Ptr< PointToPointIslNetDevice > GetDestination (uint32_t i) const
Get the destination net-device.
Ptr< PointToPointIslNetDevice > GetSource (uint32_t i) const
Get the source net-device.
bool IsInitialized (void) const
Check to make sure the link is initialized.
Private Types
enum WireState { INITIALIZING , IDLE , TRANSMITTING , PROPAGATING }
Wire states.
Private Attributes
Link m_link [N_DEVICES]
Link model.
std::size_t m_nDevices
Devices of this channel.
double m_propagationSpeed
propagation speed on the channel
Static Private Attributes
static const std::size_t N_DEVICES = 2
Each point to point link has exactly two net devices.
Detailed Description
Point to Point ISL Channel.
Channel connecting two satellites
This class represents a very simple point to point channel. Think full duplex RS-232 or RS-422 with null modem and no handshaking. There is no multi-drop capability on this channel – there can be a maximum of two point-to-point net devices connected.
There are two "wires" in the channel. The first device connected gets the [0] wire to transmit on. The second device gets the [1] wire. There is a state (IDLE, TRANSMITTING) associated with each wire.
(PointToPointChannel with mobile nodes)
Definition at line 56 of file satellite-point-to-point-isl-channel.h.
Member Enumeration Documentation
WireState
enum ns3::PointToPointIslChannel::WireState private
Wire states.
Enumerator
INITIALIZING
Initializing state.
IDLE
Idle state (no transmission from NetDevice)
TRANSMITTING
Transmitting state (data being transmitted from NetDevice.
PROPAGATING
Propagating state (data is being propagated in the channel.
Definition at line 165 of file satellite-point-to-point-isl-channel.h.
Constructor & Destructor Documentation
PointToPointIslChannel()
ns3::PointToPointIslChannel::PointToPointIslChannel ()
Create a PointToPointIslChannel.
Definition at line 51 of file satellite-point-to-point-isl-channel.cc.
Member Function Documentation
Attach()
void ns3::PointToPointIslChannel::Attach (Ptr< PointToPointIslNetDevice > device)
Attach a given netdevice to this channel.
Parameters
device pointer to the netdevice to attach to the channel
Definition at line 59 of file satellite-point-to-point-isl-channel.cc.
References IDLE, ns3::PointToPointIslChannel::Link::m_dst, m_link, m_nDevices, ns3::PointToPointIslChannel::Link::m_src, ns3::PointToPointIslChannel::Link::m_state, and N_DEVICES.
Referenced by ns3::PointToPointIslHelper::Install().
GetDelay()
Time ns3::PointToPointIslChannel::GetDelay (Ptr< MobilityModel > senderMobility, Ptr< MobilityModel > receiverMobility) const protected
Get the delay between two nodes on this channel.
Parameters
senderMobility location of the sender
receiverMobility location of the receiver
Returns
Time delay
Definition at line 133 of file satellite-point-to-point-isl-channel.cc.
References m_propagationSpeed.
Referenced by TransmitStart().
GetDestination()
Ptr< PointToPointIslNetDevice > ns3::PointToPointIslChannel::GetDestination (uint32_t i) const protected
Get the destination net-device.
Parameters
i the link requested
Returns
Ptr to destination PointToPointIslNetDevice for the specified link
Definition at line 151 of file satellite-point-to-point-isl-channel.cc.
References ns3::PointToPointIslChannel::Link::m_dst, and m_link.
GetDevice()
Ptr< NetDevice > ns3::PointToPointIslChannel::GetDevice (std::size_t i) const virtual
Get NetDevice corresponding to index i on this channel.
Parameters
i Index number of the device requested
Returns
Ptr to NetDevice requested
Definition at line 125 of file satellite-point-to-point-isl-channel.cc.
References GetPointToPointIslDevice().
GetNDevices()
std::size_t ns3::PointToPointIslChannel::GetNDevices (void) const virtual
Get number of devices on this channel.
Returns
number of devices on this channel
Definition at line 108 of file satellite-point-to-point-isl-channel.cc.
References m_nDevices.
GetPointToPointIslDevice()
Ptr< PointToPointIslNetDevice > ns3::PointToPointIslChannel::GetPointToPointIslDevice (std::size_t i) const
Get PointToPointIslNetDevice corresponding to index i on this channel.
Parameters
i Index number of the device requested
Returns
Ptr to PointToPointIslNetDevice requested
Definition at line 116 of file satellite-point-to-point-isl-channel.cc.
References m_link, and ns3::PointToPointIslChannel::Link::m_src.
Referenced by GetDevice().
GetSource()
Ptr< PointToPointIslNetDevice > ns3::PointToPointIslChannel::GetSource (uint32_t i) const protected
Get the source net-device.
Parameters
i the link (direction) requested
Returns
Ptr to source PointToPointIslNetDevice for the specified link
Definition at line 143 of file satellite-point-to-point-isl-channel.cc.
References m_link, and ns3::PointToPointIslChannel::Link::m_src.
GetTypeId()
TypeId ns3::PointToPointIslChannel::GetTypeId (void) static
Get the TypeId.
Returns
The TypeId for this class
Definition at line 37 of file satellite-point-to-point-isl-channel.cc.
References m_propagationSpeed, and ns3::SatConstVariables::SPEED_OF_LIGHT.
IsInitialized()
bool ns3::PointToPointIslChannel::IsInitialized (void) const protected
Check to make sure the link is initialized.
Returns
true if initialized, asserts otherwise
Definition at line 159 of file satellite-point-to-point-isl-channel.cc.
References INITIALIZING, and m_link.
TransmitStart()
bool ns3::PointToPointIslChannel::TransmitStart (Ptr< const Packet > p, Ptr< PointToPointIslNetDevice > src, Ptr< Node > dst, Time txTime) virtual
Transmit a packet over this channel.
Parameters
p Packet to transmit
src source PointToPointIslNetDevice
dst node at the other end of the channel
txTime transmission time
Returns
true if successful (always true)
Definition at line 81 of file satellite-point-to-point-isl-channel.cc.
References GetDelay(), INITIALIZING, ns3::PointToPointIslChannel::Link::m_dst, m_link, ns3::PointToPointIslChannel::Link::m_src, and ns3::PointToPointIslNetDevice::Receive().
Member Data Documentation
m_link
Link ns3::PointToPointIslChannel::m_link[N_DEVICES] private
Link model.
Definition at line 198 of file satellite-point-to-point-isl-channel.h.
Referenced by Attach(), GetDestination(), GetPointToPointIslDevice(), GetSource(), IsInitialized(), and TransmitStart().
m_nDevices
std::size_t ns3::PointToPointIslChannel::m_nDevices private
Devices of this channel.
Definition at line 160 of file satellite-point-to-point-isl-channel.h.
Referenced by Attach(), and GetNDevices().
m_propagationSpeed
double ns3::PointToPointIslChannel::m_propagationSpeed private
propagation speed on the channel
Definition at line 159 of file satellite-point-to-point-isl-channel.h.
Referenced by GetDelay(), and GetTypeId().
N_DEVICES
const std::size_t ns3::PointToPointIslChannel::N_DEVICES = 2 static private
Each point to point link has exactly two net devices.
Definition at line 157 of file satellite-point-to-point-isl-channel.h.
Referenced by Attach().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-point-to-point-isl-channel.h
/builds/sns3/satellite/satellite/model/satellite-point-to-point-isl-channel.cc