SNS3
ns3::LoraForwarderHelper Class Reference
This class can be used to install LoraForwarder applications on a set of gateways.
#include "lora-forwarder-helper.h"
Public Member Functions
LoraForwarderHelper ()
~LoraForwarderHelper ()
ApplicationContainer Install (NodeContainer c) const
ApplicationContainer Install (Ptr< Node > node) const
void SetAttribute (std::string name, const AttributeValue &value)
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
Ptr< Application > InstallPriv (Ptr< Node > node) const
Private Attributes
ObjectFactory m_factory
Detailed Description
This class can be used to install LoraForwarder applications on a set of gateways.
Definition at line 44 of file lora-forwarder-helper.h.
Constructor & Destructor Documentation
LoraForwarderHelper()
ns3::LoraForwarderHelper::LoraForwarderHelper ()
Definition at line 49 of file lora-forwarder-helper.cc.
References m_factory.
~LoraForwarderHelper()
ns3::LoraForwarderHelper::~LoraForwarderHelper ()
Definition at line 54 of file lora-forwarder-helper.cc.
Member Function Documentation
GetTypeId()
TypeId ns3::LoraForwarderHelper::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 41 of file lora-forwarder-helper.cc.
Install() [1/2]
ApplicationContainer ns3::LoraForwarderHelper::Install (NodeContainer c) const
Definition at line 71 of file lora-forwarder-helper.cc.
References InstallPriv().
Install() [2/2]
ApplicationContainer ns3::LoraForwarderHelper::Install (Ptr< Node > node) const
Definition at line 65 of file lora-forwarder-helper.cc.
References InstallPriv().
InstallPriv()
Ptr< Application > ns3::LoraForwarderHelper::InstallPriv (Ptr< Node > node) const private
Definition at line 83 of file lora-forwarder-helper.cc.
References ns3::SatLorawanNetDevice::GetLorawanMac(), m_factory, ns3::LoraForwarder::ReceiveFromLora(), and ns3::LoraForwarder::ReceiveFromPointToPoint().
Referenced by Install().
SetAttribute()
void ns3::LoraForwarderHelper::SetAttribute (std::string name, const AttributeValue & value)
Definition at line 59 of file lora-forwarder-helper.cc.
References m_factory.
Member Data Documentation
m_factory
ObjectFactory ns3::LoraForwarderHelper::m_factory private
Definition at line 66 of file lora-forwarder-helper.h.
Referenced by LoraForwarderHelper(), InstallPriv(), and SetAttribute().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/helper/lora-forwarder-helper.h
/builds/sns3/satellite/satellite/helper/lora-forwarder-helper.cc