SNS3
ns3::SatStatsWaveformUsageHelper Class Reference
Satellite Statistics
#include "satellite-stats-waveform-usage-helper.h"
Public Member Functions
SatStatsWaveformUsageHelper (Ptr< const SatHelper > satHelper)
virtual ~SatStatsWaveformUsageHelper ()
/ Destructor.
Public Member Functions inherited from ns3::SatStatsHelper
SatStatsHelper (Ptr< const SatHelper > satHelper)
Creates a new helper instance.
virtual ~SatStatsHelper ()
/ Destructor.
IdentifierType_t GetIdentifierType () const
std::string GetName () const
OutputType_t GetOutputType () const
Ptr< const SatHelper > GetSatHelper () const
void Install ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
bool IsInstalled () const
void SetIdentifierType (IdentifierType_t identifierType)
void SetName (std::string name)
void SetOutputType (OutputType_t outputType)
Static Public Member Functions
static TypeId GetTypeId ()
inherited from ObjectBase base class
Static Public Member Functions inherited from ns3::SatStatsHelper
static std::string GetIdentifierTypeName (IdentifierType_t identifierType)
static std::string GetOutputTypeName (OutputType_t outputType)
static TypeId GetTypeId ()
inherited from ObjectBase base class
Protected Member Functions
void DoInstall ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
std::string GetIdentifierHeading (std::string dataLabel) const
Protected Member Functions inherited from ns3::SatStatsHelper
Ptr< DataCollectionObject > CreateAggregator (std::string aggregatorTypeId, std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue())
Create the aggregator according to the output type.
uint32_t CreateCollectorPerIdentifier (CollectorMap &collectorMap) const
Create one collector instance for each identifier in the simulation.
virtual std::string GetDistributionHeading (std::string dataLabel) const
uint32_t GetGwId (Ptr< Node > gwNode) const
uint32_t GetIdentifierForBeam (uint32_t satId, uint32_t beamId) const
uint32_t GetIdentifierForGroup (uint32_t groupId) const
uint32_t GetIdentifierForGw (Ptr< Node > gwNode) const
uint32_t GetIdentifierForIsl (Ptr< Node > satNodeSrc, Ptr< Node > satNodeDst) const
uint32_t GetIdentifierForSat (Ptr< Node > satNode) const
uint32_t GetIdentifierForUt (Ptr< Node > utNode) const
uint32_t GetIdentifierForUtUser (Ptr< Node > utUserNode) const
virtual std::string GetOutputFileName () const
Compute the path and file name where statistics output should be written to.
virtual std::string GetOutputPath () const
uint32_t GetSatId (Ptr< Node > satNode) const
virtual std::string GetTimeHeading (std::string dataLabel) const
uint32_t GetUtId (Ptr< Node > utNode) const
uint32_t GetUtUserId (Ptr< Node > utUserNode) const
Private Member Functions
void WaveformUsageCallback (std::string context, uint32_t waveformId)
Private Attributes
Ptr< DataCollectionObject > m_aggregator
The aggregator created by this helper.
std::map< uint32_t, CollectorMap > m_collectors
Two-dimensional map of collectors, indexed by the waveform ID and then by the identifier.
Additional Inherited Members
Public Types inherited from ns3::SatStatsHelper
enum IdentifierType_t {
IDENTIFIER_GLOBAL = 0 , IDENTIFIER_GW , IDENTIFIER_BEAM , IDENTIFIER_UT ,
IDENTIFIER_UT_USER , IDENTIFIER_SLICE , IDENTIFIER_GROUP , IDENTIFIER_SAT ,
IDENTIFIER_ISL
}
Possible categorization of statistics output.
enum OutputType_t {
OUTPUT_NONE = 0 , OUTPUT_SCALAR_FILE , OUTPUT_SCATTER_FILE , OUTPUT_HISTOGRAM_FILE ,
OUTPUT_PDF_FILE , OUTPUT_CDF_FILE , OUTPUT_SCALAR_PLOT , OUTPUT_SCATTER_PLOT ,
OUTPUT_HISTOGRAM_PLOT , OUTPUT_PDF_PLOT , OUTPUT_CDF_PLOT
}
Possible types and formats of statistics output.
Static Protected Member Functions inherited from ns3::SatStatsHelper
static NetDeviceContainer GetGwSatNetDevice (Ptr< Node > gwNode)
static Ptr< NetDevice > GetSatSatGeoNetDevice (Ptr< Node > satNode)
static Ptr< NetDevice > GetUtSatNetDevice (Ptr< Node > utNode)
Detailed Description
Definition at line 41 of file satellite-stats-waveform-usage-helper.h.
Constructor & Destructor Documentation
SatStatsWaveformUsageHelper()
ns3::SatStatsWaveformUsageHelper::SatStatsWaveformUsageHelper (Ptr< const SatHelper > satHelper)
Definition at line 50 of file satellite-stats-waveform-usage-helper.cc.
~SatStatsWaveformUsageHelper()
ns3::SatStatsWaveformUsageHelper::~SatStatsWaveformUsageHelper () virtual
/ Destructor.
Definition at line 56 of file satellite-stats-waveform-usage-helper.cc.
Member Function Documentation
DoInstall()
void ns3::SatStatsWaveformUsageHelper::DoInstall () protected virtual
Install the probes, collectors, and aggregators necessary to produce the statistics output.
An abstract method of SatStatsHelper which must be implemented by child classes. It will be invoked by Install().
Implements ns3::SatStatsHelper.
Definition at line 69 of file satellite-stats-waveform-usage-helper.cc.
References ns3::SatStatsHelper::CreateAggregator(), ns3::SatStatsHelper::GetIdentifierForBeam(), GetIdentifierHeading(), ns3::SatStatsHelper::GetIdentifierType(), ns3::SatStatsHelper::GetIdentifierTypeName(), ns3::SatStatsHelper::GetOutputFileName(), ns3::SatStatsHelper::GetOutputType(), ns3::SatStatsHelper::GetOutputTypeName(), ns3::SatStatsHelper::GetSatHelper(), ns3::SatStatsHelper::IDENTIFIER_UT, ns3::SatStatsHelper::IDENTIFIER_UT_USER, m_aggregator, ns3::SatStatsHelper::OUTPUT_SCALAR_FILE, and WaveformUsageCallback().
GetIdentifierHeading()
std::string ns3::SatStatsWaveformUsageHelper::GetIdentifierHeading (std::string dataLabel) const protected virtual
Parameters
dataLabel the short name of the main data of this statistics
Returns
a string to be printed as the first line of output, consisting of the identifier title and the given data label
Reimplemented from ns3::SatStatsHelper.
Definition at line 125 of file satellite-stats-waveform-usage-helper.cc.
References ns3::SatStatsHelper::GetIdentifierType(), ns3::SatStatsHelper::IDENTIFIER_BEAM, ns3::SatStatsHelper::IDENTIFIER_GLOBAL, and ns3::SatStatsHelper::IDENTIFIER_GW.
Referenced by DoInstall().
GetTypeId()
TypeId ns3::SatStatsWaveformUsageHelper::GetTypeId (void) static
inherited from ObjectBase base class
Definition at line 62 of file satellite-stats-waveform-usage-helper.cc.
WaveformUsageCallback()
void ns3::SatStatsWaveformUsageHelper::WaveformUsageCallback (std::string context, uint32_t waveformId) private
Parameters
context
waveformId
Definition at line 146 of file satellite-stats-waveform-usage-helper.cc.
References ns3::SatStatsHelper::GetGwId(), ns3::SatStatsHelper::GetIdentifierType(), ns3::SatStatsHelper::GetIdentifierTypeName(), ns3::SatStatsHelper::GetSatHelper(), ns3::SatStatsHelper::IDENTIFIER_BEAM, ns3::SatStatsHelper::IDENTIFIER_GLOBAL, ns3::SatStatsHelper::IDENTIFIER_GW, m_aggregator, m_collectors, and ns3::SatConstVariables::MAX_BEAMS_PER_SATELLITE.
Referenced by DoInstall().
Member Data Documentation
m_aggregator
Ptr<DataCollectionObject> ns3::SatStatsWaveformUsageHelper::m_aggregator private
The aggregator created by this helper.
Definition at line 76 of file satellite-stats-waveform-usage-helper.h.
Referenced by DoInstall(), and WaveformUsageCallback().
m_collectors
std::map<uint32_t, CollectorMap> ns3::SatStatsWaveformUsageHelper::m_collectors private
Two-dimensional map of collectors, indexed by the waveform ID and then by the identifier.
Definition at line 73 of file satellite-stats-waveform-usage-helper.h.
Referenced by WaveformUsageCallback().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/stats/satellite-stats-waveform-usage-helper.h
/builds/sns3/satellite/satellite/stats/satellite-stats-waveform-usage-helper.cc