SNS3
ns3::SatPhyTimeTag Class Reference
Time tag used to identify the time when packet is enqueued at PHY on first link between GW and UT level.
#include "satellite-time-tag.h"
Public Member Functions
SatPhyTimeTag ()
Default constructor.
SatPhyTimeTag (Time senderTimestamp)
Constructor with initialization parameters.
virtual void Deserialize (TagBuffer i)
Deserializes information from buffer to this instance of SatPhyTimeTag.
virtual TypeId GetInstanceTypeId (void) const
Get the type ID of instance.
Time GetSenderTimestamp (void) const
Get sender time stamp of this tag.
virtual uint32_t GetSerializedSize () const
Get serialized size of SatPhyTimeTag.
virtual void Print (std::ostream &os) const
Print time stamp of this instance of SatPhyTimeTag.
virtual void Serialize (TagBuffer i) const
Serializes information to buffer from this instance of SatPhyTimeTag.
void SetSenderTimestamp (Time senderTimestamp)
Set sender time stamp of this tag.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Time m_senderTimestamp
Detailed Description
Time tag used to identify the time when packet is enqueued at PHY on first link between GW and UT level.
Definition at line 112 of file satellite-time-tag.h.
Constructor & Destructor Documentation
SatPhyTimeTag() [1/2]
ns3::SatPhyTimeTag::SatPhyTimeTag ()
Default constructor.
Definition at line 104 of file satellite-time-tag.cc.
SatPhyTimeTag() [2/2]
ns3::SatPhyTimeTag::SatPhyTimeTag (Time senderTimestamp)
Constructor with initialization parameters.
Parameters
senderTimestamp
Definition at line 110 of file satellite-time-tag.cc.
Member Function Documentation
Deserialize()
void ns3::SatPhyTimeTag::Deserialize (TagBuffer i) virtual
Deserializes information from buffer to this instance of SatPhyTimeTag.
Parameters
i Buffer from which the information is deserialized
Definition at line 144 of file satellite-time-tag.cc.
References m_senderTimestamp.
GetInstanceTypeId()
TypeId ns3::SatPhyTimeTag::GetInstanceTypeId (void) const virtual
Get the type ID of instance.
Returns
the object TypeId
Definition at line 125 of file satellite-time-tag.cc.
References GetTypeId().
GetSenderTimestamp()
Time ns3::SatPhyTimeTag::GetSenderTimestamp (void) const
Get sender time stamp of this tag.
Returns
Sender timestamp
Definition at line 158 of file satellite-time-tag.cc.
References m_senderTimestamp.
Referenced by ns3::SatPhy::RxTraces().
GetSerializedSize()
uint32_t ns3::SatPhyTimeTag::GetSerializedSize (void) const virtual
Get serialized size of SatPhyTimeTag.
Returns
Serialized size in bytes
Definition at line 131 of file satellite-time-tag.cc.
GetTypeId()
TypeId ns3::SatPhyTimeTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 117 of file satellite-time-tag.cc.
Referenced by GetInstanceTypeId().
Print()
void ns3::SatPhyTimeTag::Print (std::ostream & os) const virtual
Print time stamp of this instance of SatPhyTimeTag.
Parameters
&os Output stream to which tag timestamp is printed.
Definition at line 152 of file satellite-time-tag.cc.
References m_senderTimestamp.
Serialize()
void ns3::SatPhyTimeTag::Serialize (TagBuffer i) const virtual
Serializes information to buffer from this instance of SatPhyTimeTag.
Parameters
i Buffer in which the information is serialized
Definition at line 137 of file satellite-time-tag.cc.
References m_senderTimestamp.
SetSenderTimestamp()
void ns3::SatPhyTimeTag::SetSenderTimestamp (Time senderTimestamp)
Set sender time stamp of this tag.
Parameters
senderTimestamp Sender time stamp
Definition at line 164 of file satellite-time-tag.cc.
References m_senderTimestamp.
Member Data Documentation
m_senderTimestamp
Time ns3::SatPhyTimeTag::m_senderTimestamp private
Definition at line 175 of file satellite-time-tag.h.
Referenced by Deserialize(), GetSenderTimestamp(), Print(), Serialize(), and SetSenderTimestamp().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-time-tag.h
/builds/sns3/satellite/satellite/model/satellite-time-tag.cc