SNS3
ns3::SatPhyTx Class Reference
The SatellitePhyTx models the physical layer transmitter of satellite system.
#include "satellite-phy-tx.h"
Public Types
enum SatPhyTxMode_t { NORMAL , TRANSPARENT }
enum State { IDLE , TX , RECONFIGURING }
PHY states.
Public Member Functions
SatPhyTx ()
Default constructor.
virtual ~SatPhyTx ()
Destructor for SatPhyTx.
bool CanTransmit (void) const
Tell whether or not this channel can transmit data.
void ClearChannel ()
virtual void DoDispose ()
Dispose of this class instance.
double GetAntennaGain (Ptr< MobilityModel > mobility)
Get antenna gain based on position or in case that antenna pattern is not configured, maximum configured gain is return.
Ptr< SatChannel > GetChannel ()
double GetFadingValue (Address macAddress, SatEnums::ChannelType_t channelType)
Get fading value.
Ptr< MobilityModel > GetMobility ()
bool IsTransmitting (void) const
Tell whether or not this channel is transmitting data.
void SetAntennaGainPattern (Ptr< SatAntennaGainPattern > agp, Ptr< SatMobilityModel > mobility)
void SetBeamId (uint32_t beamId)
Set the beam id for all the transmissions from this SatPhyTx.
void SetChannel (Ptr< SatChannel > c)
void SetDefaultFadingValue (double fadingValue)
Function for setting the default fading value.
void SetFadingContainer (Ptr< SatBaseFading > fadingContainer)
Set fading container.
void SetMaxAntennaGain_Db (double gain_db)
Set the maximum Antenna gain in Db.
void SetMobility (Ptr< MobilityModel > m)
void SetSatId (uint32_t satId)
Set the satellite id for all the transmissions from this SatPhyTx.
virtual void StartTx (Ptr< SatSignalParameters > txParams)
Start packet transmission to the channel.
Static Public Member Functions
static TypeId GetTypeId (void)
inherited from Object
Protected Member Functions
virtual void EndTx ()
Private Member Functions
void ChangeState (State newState)
Private Attributes
Ptr< SatAntennaGainPattern > m_antennaGainPattern
uint32_t m_beamId
Ptr< SatChannel > m_channel
double m_defaultFadingValue
Default fading value.
Ptr< SatBaseFading > m_fadingContainer
Fading container for fading model.
double m_maxAntennaGain
Configured maximum antenna gain in linear.
Ptr< MobilityModel > m_mobility
uint32_t m_satId
Ptr< SatMobilityModel > m_satMobility
State m_state
SatPhyTxMode_t m_txMode
Detailed Description
The SatellitePhyTx models the physical layer transmitter of satellite system.
Definition at line 50 of file satellite-phy-tx.h.
Member Enumeration Documentation
SatPhyTxMode_t
enum ns3::SatPhyTx::SatPhyTxMode_t
Enumerator
NORMAL
TRANSPARENT
Definition at line 53 of file satellite-phy-tx.h.
State
enum ns3::SatPhyTx::State
PHY states.
Enumerator
IDLE
TX
RECONFIGURING
Definition at line 72 of file satellite-phy-tx.h.
Constructor & Destructor Documentation
SatPhyTx()
ns3::SatPhyTx::SatPhyTx ()
Default constructor.
Definition at line 47 of file satellite-phy-tx.cc.
~SatPhyTx()
ns3::SatPhyTx::~SatPhyTx () virtual
Destructor for SatPhyTx.
Definition at line 57 of file satellite-phy-tx.cc.
Member Function Documentation
CanTransmit()
bool ns3::SatPhyTx::CanTransmit (void) const
Tell whether or not this channel can transmit data.
Definition at line 320 of file satellite-phy-tx.cc.
References m_state, and RECONFIGURING.
ChangeState()
void ns3::SatPhyTx::ChangeState (State newState) private
Definition at line 230 of file satellite-phy-tx.cc.
References m_state.
Referenced by ClearChannel(), EndTx(), SetChannel(), and StartTx().
ClearChannel()
void ns3::SatPhyTx::ClearChannel ()
Definition at line 211 of file satellite-phy-tx.cc.
References ChangeState(), m_channel, and RECONFIGURING.
DoDispose()
void ns3::SatPhyTx::DoDispose (void) virtual
Dispose of this class instance.
Definition at line 63 of file satellite-phy-tx.cc.
References m_channel, m_fadingContainer, and m_mobility.
EndTx()
void ns3::SatPhyTx::EndTx () protected virtual
Reimplemented in ns3::SatLoraPhyTx.
Definition at line 284 of file satellite-phy-tx.cc.
References ChangeState(), IDLE, m_state, and TX.
Referenced by ns3::SatLoraPhyTx::EndTx(), and StartTx().
GetAntennaGain()
double ns3::SatPhyTx::GetAntennaGain (Ptr< MobilityModel > mobility)
Get antenna gain based on position or in case that antenna pattern is not configured, maximum configured gain is return.
Parameters
mobility Mobility used to get gain from antenna pattern
Returns
antenna gain
If antenna gain pattern is not set, we use the set maximum antenna gain.
Definition at line 118 of file satellite-phy-tx.cc.
References m_antennaGainPattern, m_maxAntennaGain, and m_satMobility.
GetChannel()
Ptr< SatChannel > ns3::SatPhyTx::GetChannel (void)
Definition at line 221 of file satellite-phy-tx.cc.
References m_channel.
GetFadingValue()
double ns3::SatPhyTx::GetFadingValue (Address macAddress, SatEnums::ChannelType_t channelType)
Get fading value.
Parameters
macAddress MAC address
channelType channel type
Returns
Definition at line 149 of file satellite-phy-tx.cc.
References m_defaultFadingValue, and m_fadingContainer.
GetMobility()
Ptr< MobilityModel > ns3::SatPhyTx::GetMobility ()
Definition at line 173 of file satellite-phy-tx.cc.
References m_mobility.
GetTypeId()
TypeId ns3::SatPhyTx::GetTypeId (void) static
inherited from Object
Definition at line 94 of file satellite-phy-tx.cc.
References m_txMode, NORMAL, and TRANSPARENT.
IsTransmitting()
bool ns3::SatPhyTx::IsTransmitting (void) const
Tell whether or not this channel is transmitting data.
Definition at line 312 of file satellite-phy-tx.cc.
References m_state, and TX.
Referenced by ns3::SatLoraPhyTx::IsTransmitting().
SetAntennaGainPattern()
void ns3::SatPhyTx::SetAntennaGainPattern (Ptr< SatAntennaGainPattern > agp, Ptr< SatMobilityModel > mobility)
Definition at line 191 of file satellite-phy-tx.cc.
References m_antennaGainPattern, and m_satMobility.
SetBeamId()
void ns3::SatPhyTx::SetBeamId (uint32_t beamId)
Set the beam id for all the transmissions from this SatPhyTx.
Parameters
beamId the Beam Identifier
Definition at line 305 of file satellite-phy-tx.cc.
References m_beamId.
SetChannel()
void ns3::SatPhyTx::SetChannel (Ptr< SatChannel > c)
Definition at line 201 of file satellite-phy-tx.cc.
References ChangeState(), IDLE, and m_channel.
SetDefaultFadingValue()
void ns3::SatPhyTx::SetDefaultFadingValue (double fadingValue)
Function for setting the default fading value.
Parameters
fadingValue default fading value
Definition at line 141 of file satellite-phy-tx.cc.
References m_defaultFadingValue.
SetFadingContainer()
void ns3::SatPhyTx::SetFadingContainer (Ptr< SatBaseFading > fadingContainer)
Set fading container.
Parameters
fadingContainer fading container
Definition at line 164 of file satellite-phy-tx.cc.
References m_fadingContainer.
SetMaxAntennaGain_Db()
void ns3::SatPhyTx::SetMaxAntennaGain_Db (double gain_db)
Set the maximum Antenna gain in Db.
Parameters
gain_db maximum antenna gain in Dbs
Definition at line 110 of file satellite-phy-tx.cc.
References ns3::SatUtils::DbToLinear(), and m_maxAntennaGain.
SetMobility()
void ns3::SatPhyTx::SetMobility (Ptr< MobilityModel > m)
Definition at line 182 of file satellite-phy-tx.cc.
References m_mobility.
SetSatId()
void ns3::SatPhyTx::SetSatId (uint32_t satId)
Set the satellite id for all the transmissions from this SatPhyTx.
Parameters
satId the satellite Identifier
Definition at line 298 of file satellite-phy-tx.cc.
References m_satId.
StartTx()
void ns3::SatPhyTx::StartTx (Ptr< SatSignalParameters > txParams) virtual
Start packet transmission to the channel.
Parameters
txParams Transmission parameters for a packet
The SatPhyTx is mapped to a spot-beam, which means that there may be several carriers handled by the same SatPhyTx. This is why the SatPhyTx state machine needs to be overtaken, thus the SatPhyTx is allowed to send several overlapping packets; in different carriers though. TODO: The SatPhyTx state machine may need some (code quality) improvements. E.g. different inherited implementations may be done for satellite and terrestrial domain nodes.
Reimplemented in ns3::SatLoraPhyTx.
Definition at line 238 of file satellite-phy-tx.cc.
References ChangeState(), EndTx(), IDLE, m_channel, m_state, m_txMode, RECONFIGURING, TRANSPARENT, and TX.
Referenced by ns3::SatLoraPhyTx::StartTx().
Member Data Documentation
m_antennaGainPattern
Ptr<SatAntennaGainPattern> ns3::SatPhyTx::m_antennaGainPattern private
Definition at line 178 of file satellite-phy-tx.h.
Referenced by GetAntennaGain(), and SetAntennaGainPattern().
m_beamId
uint32_t ns3::SatPhyTx::m_beamId private
Definition at line 192 of file satellite-phy-tx.h.
Referenced by SetBeamId().
m_channel
Ptr<SatChannel> ns3::SatPhyTx::m_channel private
Definition at line 173 of file satellite-phy-tx.h.
Referenced by ClearChannel(), DoDispose(), GetChannel(), SetChannel(), and StartTx().
m_defaultFadingValue
double ns3::SatPhyTx::m_defaultFadingValue private
Default fading value.
Definition at line 203 of file satellite-phy-tx.h.
Referenced by GetFadingValue(), and SetDefaultFadingValue().
m_fadingContainer
Ptr<SatBaseFading> ns3::SatPhyTx::m_fadingContainer private
Fading container for fading model.
Definition at line 198 of file satellite-phy-tx.h.
Referenced by DoDispose(), GetFadingValue(), and SetFadingContainer().
m_maxAntennaGain
double ns3::SatPhyTx::m_maxAntennaGain private
Configured maximum antenna gain in linear.
Definition at line 188 of file satellite-phy-tx.h.
Referenced by GetAntennaGain(), and SetMaxAntennaGain_Db().
m_mobility
Ptr<MobilityModel> ns3::SatPhyTx::m_mobility private
Definition at line 172 of file satellite-phy-tx.h.
Referenced by DoDispose(), GetMobility(), and SetMobility().
m_satId
uint32_t ns3::SatPhyTx::m_satId private
Definition at line 191 of file satellite-phy-tx.h.
Referenced by SetSatId().
m_satMobility
Ptr<SatMobilityModel> ns3::SatPhyTx::m_satMobility private
Definition at line 183 of file satellite-phy-tx.h.
Referenced by GetAntennaGain(), and SetAntennaGainPattern().
m_state
State ns3::SatPhyTx::m_state private
Definition at line 190 of file satellite-phy-tx.h.
Referenced by CanTransmit(), ChangeState(), EndTx(), IsTransmitting(), and StartTx().
m_txMode
SatPhyTxMode_t ns3::SatPhyTx::m_txMode private
Definition at line 193 of file satellite-phy-tx.h.
Referenced by GetTypeId(), and StartTx().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-phy-tx.h
/builds/sns3/satellite/satellite/model/satellite-phy-tx.cc