SNS3
SatBaseTestCase Class Reference
Test case to unit test the UT request manager.
Public Member Functions
SatBaseTestCase ()
virtual ~SatBaseTestCase ()
bool ControlMsgTxPossible () const
Check whether a control message transmission is possible.
SatQueue::QueueStats_t GetQueueStatistics (bool reset)
Get queue statistics for request manager.
bool SendControlMsg (Ptr< SatControlMessage > msg, const Address &dest)
Send control message called with a callback from request manager.
Private Member Functions
virtual void DoRun (void)
Private Attributes
std::vector< Ptr< SatCrMessage > > m_rcvdCapacityRequests
Received CRs.
Detailed Description
Test case to unit test the UT request manager.
Definition at line 48 of file satellite-request-manager-test.cc.
Constructor & Destructor Documentation
SatBaseTestCase()
SatBaseTestCase::SatBaseTestCase ()
Definition at line 86 of file satellite-request-manager-test.cc.
~SatBaseTestCase()
SatBaseTestCase::~SatBaseTestCase () virtual
Definition at line 91 of file satellite-request-manager-test.cc.
Member Function Documentation
ControlMsgTxPossible()
bool SatBaseTestCase::ControlMsgTxPossible () const
Check whether a control message transmission is possible.
Returns
Boolean indicating the possibility
Definition at line 196 of file satellite-request-manager-test.cc.
Referenced by DoRun().
DoRun()
void SatBaseTestCase::DoRun (void) private virtual
Definition at line 96 of file satellite-request-manager-test.cc.
References ControlMsgTxPossible(), GetQueueStatistics(), m_rcvdCapacityRequests, and SendControlMsg().
GetQueueStatistics()
SatQueue::QueueStats_t SatBaseTestCase::GetQueueStatistics (bool reset)
Get queue statistics for request manager.
This comes really from the SatQueue, but here we send some known information as KPIs for RM.
Parameters
reset Flag to reset queue statistics (not used here)
Returns
Queue statistics struct
Definition at line 182 of file satellite-request-manager-test.cc.
References ns3::SatQueue::QueueStats_t::m_incomingRateKbps, ns3::SatQueue::QueueStats_t::m_outgoingRateKbps, ns3::SatQueue::QueueStats_t::m_queueSizeBytes, ns3::SatQueue::QueueStats_t::m_volumeInBytes, and ns3::SatQueue::QueueStats_t::m_volumeOutBytes.
Referenced by DoRun().
SendControlMsg()
bool SatBaseTestCase::SendControlMsg (Ptr< SatControlMessage > msg, const Address & dest)
Send control message called with a callback from request manager.
In this test the method is used to analyze the sent requests from RM.
Parameters
msg Control msg (CR, or CNo report)
dest Destination MAC address
Returns
Boolean whether the send was successfull.
Definition at line 163 of file satellite-request-manager-test.cc.
References m_rcvdCapacityRequests.
Referenced by DoRun().
Member Data Documentation
m_rcvdCapacityRequests
std::vector<Ptr<SatCrMessage> > SatBaseTestCase::m_rcvdCapacityRequests private
Received CRs.
Definition at line 83 of file satellite-request-manager-test.cc.
Referenced by DoRun(), and SendControlMsg().
The documentation for this class was generated from the following file:
/builds/sns3/satellite/satellite/test/satellite-request-manager-test.cc