SNS3
ns3::LoraDeviceAddressGenerator Class Reference
This class generates sequential LoraDeviceAddress instances.
#include "lora-device-address-generator.h"
Public Member Functions
LoraDeviceAddressGenerator (const uint8_t nwkId=0, const uint32_t nwkAddr=0)
Initialise the base NwkID and the first NwkAddr to be used by the generator.
LoraDeviceAddress GetNextAddress (void)
Get the LoraDeviceAddress that will be allocated upon a call to NextAddress.
LoraDeviceAddress NextAddress (void)
Allocate the next LoraDeviceAddress.
LoraDeviceAddress NextNetwork (void)
Get the first address from the next network.
Static Public Member Functions
static TypeId GetTypeId (void)
Private Attributes
NwkAddr m_currentNwkAddr
The current Network Address value.
NwkID m_currentNwkId
The current Network Id value.
Detailed Description
This class generates sequential LoraDeviceAddress instances.
Definition at line 35 of file lora-device-address-generator.h.
Constructor & Destructor Documentation
LoraDeviceAddressGenerator()
ns3::LoraDeviceAddressGenerator::LoraDeviceAddressGenerator (const uint8_t nwkId = 0, const uint32_t nwkAddr = 0)
Initialise the base NwkID and the first NwkAddr to be used by the generator.
The first call to NextAddress() or GetAddress() will return these values.
Parameters
nwkId The first network id.
nwkAddr The first address.
Definition at line 41 of file lora-device-address-generator.cc.
References m_currentNwkAddr, m_currentNwkId, ns3::NwkAddr::Set(), and ns3::NwkID::Set().
Member Function Documentation
GetNextAddress()
LoraDeviceAddress ns3::LoraDeviceAddressGenerator::GetNextAddress (void)
Get the LoraDeviceAddress that will be allocated upon a call to NextAddress.
Does not change the internal state; is just used to peek at the next address that will be allocated upon a call to NextAddress
Returns
the LoraDeviceAddress
Definition at line 72 of file lora-device-address-generator.cc.
References ns3::NwkID::Get(), ns3::NwkAddr::Get(), m_currentNwkAddr, and m_currentNwkId.
GetTypeId()
TypeId ns3::LoraDeviceAddressGenerator::GetTypeId (void) static
Definition at line 33 of file lora-device-address-generator.cc.
NextAddress()
LoraDeviceAddress ns3::LoraDeviceAddressGenerator::NextAddress (void)
Allocate the next LoraDeviceAddress.
This operation is a post-increment, meaning that the first address allocated will be the one that was initially configured.
This keeps the nwkId constant, only incrementing nwkAddr.
Returns
the LoraDeviceAddress address
Definition at line 61 of file lora-device-address-generator.cc.
References ns3::NwkAddr::Get(), m_currentNwkAddr, m_currentNwkId, and ns3::NwkAddr::Set().
NextNetwork()
LoraDeviceAddress ns3::LoraDeviceAddressGenerator::NextNetwork (void)
Get the first address from the next network.
This resets the address to the base address that was used for initialization.
Returns
the LoraDeviceAddress address of the next network
Definition at line 50 of file lora-device-address-generator.cc.
References ns3::NwkID::Get(), m_currentNwkAddr, m_currentNwkId, ns3::NwkAddr::Set(), and ns3::NwkID::Set().
Member Data Documentation
m_currentNwkAddr
NwkAddr ns3::LoraDeviceAddressGenerator::m_currentNwkAddr private
The current Network Address value.
Definition at line 86 of file lora-device-address-generator.h.
Referenced by LoraDeviceAddressGenerator(), GetNextAddress(), NextAddress(), and NextNetwork().
m_currentNwkId
NwkID ns3::LoraDeviceAddressGenerator::m_currentNwkId private
The current Network Id value.
Definition at line 85 of file lora-device-address-generator.h.
Referenced by LoraDeviceAddressGenerator(), GetNextAddress(), NextAddress(), and NextNetwork().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/lora-device-address-generator.h
/builds/sns3/satellite/satellite/model/lora-device-address-generator.cc