SNS3
ns3::JulianDate Class Reference
Class to handle Julian days and provide respective Earth Orientation Parameters (EOP).
#include "julian-date.h"
Public Member Functions
JulianDate (const std::string &date, TimeSystem ts=DateTime::UTC)
JulianDate constructor receiving time as a Gregorian date.
JulianDate (double jd)
JulianDate constructor receiving the Julian days as parameter.
JulianDate (uint32_t days, uint32_t ms_day)
JulianDate constructor receiving time since Unix/POSIX epoch.
JulianDate (void)
Default constructor.
DateTime GetDateTime (TimeSystem ts) const
Get the Gregorian calendar date in the specified time system.
DateTime GetDateTime (void) const
Get the Gregorian calendar date in current time system.
double GetDouble (TimeSystem ts=DateTime::UTC) const
GetDouble Get the Julian days.
double GetGmst (void) const
Retrieve the Greenwich Mean Sidereal Time.
double GetOmegaEarth (void) const
Retrieve Earth's angular velocity.
std::pair< double, double > GetPolarMotion (void) const
Retrieve the polar motion cofficients measured/predicted.
bool operator!= (const JulianDate &jd) const
operator != (compare Julian dates).
JulianDate operator+ (const Time &t) const
operator + (positive time adjustment).
void operator+= (const Time &t)
operator += (positive time adjustment).
Time operator- (const JulianDate &jd) const
operator - (time between Julian dates).
JulianDate operator- (const Time &t) const
operator - (negative time adjustment).
void operator-= (const Time &t)
operator -= (negative time adjustment).
bool operator< (const JulianDate &jd) const
operator < (compare Julian dates).
bool operator<= (const JulianDate &jd) const
operator <= (compare Julian dates).
bool operator== (const JulianDate &jd) const
operator == (compare Julian dates).
bool operator> (const JulianDate &jd) const
operator > (compare Julian dates).
bool operator>= (const JulianDate &jd) const
operator >= (compare Julian dates).
void SetDate (const std::string &date, TimeSystem ts=DateTime::UTC)
Set Julian days using time in Gregorian calendar date.
void SetDate (double jd)
Set the Julian days.
void SetDate (uint32_t days, uint32_t ms_day)
Set Julian days using the time since Unix/POSIX epoch.
std::string ToString (TimeSystem ts) const
Get the string representation of the Gregorian calendar date in time system ts.
std::string ToString (void) const
Get the string representation of the Gregorian calendar date.
Static Public Attributes
static const uint32_t DayToMs = HourToMs * 24
milliseconds in a day
static const uint32_t HourToMs = 3600000
milliseconds in an hour
static const uint32_t J2000Epoch = 2451545
1 Jan 2000, 12h
static const uint32_t MaxYear = 2099
Maximum year supported.
static const uint32_t MinYear = 1992
Minimum year supported.
static const uint32_t Posix1992 = 8035
1 Jan 1992 (POSIX days)
static const double PosixEpoch = 2440587.5
1 Jan 1970, 0h
static const uint32_t PosixYear = 1970
POSIX/Unix epoch year.
static const Time TaiToGps = MilliSeconds(19000)
offset from TAI to GPST
static const Time TtToTai = MilliSeconds(32184)
offset from TT to TAI
Private Types
typedef DateTime::TimeSystem TimeSystem
equivalent to C++11 using TimeSystem = DateTime::TimeSystem.
Private Member Functions
DateTime GregorianDate (void) const
Convert into Gregorian calendar.
Time OffsetFromUtc (void) const
Returns the offset from UTC.
Time OffsetToUtc (void) const
Returns the offset to UTC.
Static Private Member Functions
static Time Dut1 (uint32_t daysInPosix)
Retrieve the DUT1 (UT1 - UTC) value for a given day.
static DateTime GregorianDate (uint32_t days, uint32_t ms_day)
Convert Julian days into Gregorian calendar.
static bool IsLeapYear (uint32_t year)
Check if it is a leap year.
static Time OffsetFromUtc (uint32_t daysInPosix, TimeSystem ts)
Returns the offset from UTC for a given time.
static Time OffsetToUtc (uint32_t daysInPosix, uint32_t ms_day, TimeSystem ts)
Returns the offset to UTC for a given time.
static Time TaiMinusUtc (uint32_t daysInPosix)
The difference between TAI and UTC time systems.
Private Attributes
uint32_t m_days
full days since epoch.
uint32_t m_ms_day
milliseconds of the day.
TimeSystem m_time_scale
external time system.
Friends
std::ostream & operator<< (std::ostream &os, const JulianDate &jd)
operator << (print as GregorianDate).
Detailed Description
Class to handle Julian days and provide respective Earth Orientation Parameters (EOP).
This class provides an easy interface to convert between Julian days and Gregorian dates in UTC, UT1, TAI, TT, GPST, and Unix/POSIX time, and, using IersData class, provides the respective Earth Orientation Parameters (EOP). The EOP parameters available are: DUT1, Earth's angular velocity, and Greenwich Mean Sidereal Time (GMST).
IMPORTANT: Complete EOP values are only available since 1 January 1992, therefore, this class only supports dates from 1 January 1992 up to 31 December 2099.
Definition at line 77 of file julian-date.h.
Member Typedef Documentation
TimeSystem
typedef DateTime::TimeSystem ns3::JulianDate::TimeSystem private
equivalent to C++11 using TimeSystem = DateTime::TimeSystem.
Definition at line 80 of file julian-date.h.
Constructor & Destructor Documentation
JulianDate() [1/4]
ns3::JulianDate::JulianDate (void)
Default constructor.
Definition at line 85 of file julian-date.cc.
References m_days, m_ms_day, m_time_scale, MinYear, PosixYear, and ns3::DateTime::UTC.
JulianDate() [2/4]
ns3::JulianDate::JulianDate (double jd)
JulianDate constructor receiving the Julian days as parameter.
This constructor has lower precision as there may be some inaccuracy at the millisecond level due to double type limited precision.
Parameters
jd The Julian days.
Definition at line 93 of file julian-date.cc.
References SetDate().
JulianDate() [3/4]
ns3::JulianDate::JulianDate (uint32_t days, uint32_t ms_day)
JulianDate constructor receiving time since Unix/POSIX epoch.
Parameters
days Full days since Unix/POSIX epoch (1 January 1970, 0h).
ms_day Milliseconds of the day (since midnight).
Definition at line 98 of file julian-date.cc.
References SetDate().
JulianDate() [4/4]
ns3::JulianDate::JulianDate (const std::string & date, TimeSystem ts = DateTime::UTC)
JulianDate constructor receiving time as a Gregorian date.
Parameters
date Gregorian calendar date.
ts Time system of the date (UTC, UT1, TAI, TT or GPST).
Definition at line 103 of file julian-date.cc.
References SetDate().
Member Function Documentation
Dut1()
Time ns3::JulianDate::Dut1 (uint32_t daysInPosix) static private
Retrieve the DUT1 (UT1 - UTC) value for a given day.
Parameters
daysInPosix number of full days since Unix/POSIX epoch.
Returns
the DUT1 measured/predicted as of IERS Bulletin A.
Definition at line 420 of file julian-date.cc.
References ns3::IersData::EopValues, and Posix1992.
Referenced by GetGmst(), OffsetFromUtc(), and OffsetToUtc().
GetDateTime() [1/2]
DateTime ns3::JulianDate::GetDateTime (TimeSystem ts) const
Get the Gregorian calendar date in the specified time system.
Returns
a DateTime struct with the Gregorian calendar date.
Definition at line 127 of file julian-date.cc.
References m_days, and OffsetFromUtc().
GetDateTime() [2/2]
DateTime ns3::JulianDate::GetDateTime (void) const
Get the Gregorian calendar date in current time system.
Returns
a DateTime struct with the Gregorian calendar date and time.
Definition at line 121 of file julian-date.cc.
References GregorianDate().
GetDouble()
double ns3::JulianDate::GetDouble (TimeSystem ts = DateTime::UTC) const
GetDouble Get the Julian days.
Parameters
ts Time system to consider for conversion (UTC by default).
Returns
the Julian days in time system ts.
Definition at line 109 of file julian-date.cc.
References DayToMs, m_days, m_ms_day, OffsetFromUtc(), ns3::DateTime::POSIX, and PosixEpoch.
Referenced by GetGmst().
GetGmst()
double ns3::JulianDate::GetGmst (void) const
Retrieve the Greenwich Mean Sidereal Time.
Returns
the GMST using DUT1 values measured/predicted as IERS' Bulletin A.
@TODO interpolate DUT1 between daily values
@TODO evaluate which formula is more accurate
Definition at line 183 of file julian-date.cc.
References Dut1(), GetDouble(), gstime(), and m_days.
Referenced by ns3::SatSGP4MobilityModel::TemeToPef().
GetOmegaEarth()
double ns3::JulianDate::GetOmegaEarth (void) const
Retrieve Earth's angular velocity.
Returns
the Earth's angular velocity.
Definition at line 170 of file julian-date.cc.
References DayToMs, ns3::IersData::EopValues, m_days, and Posix1992.
Referenced by ns3::SatSGP4MobilityModel::rvTemeTovItrf().
GetPolarMotion()
std::pair< double, double > ns3::JulianDate::GetPolarMotion (void) const
Retrieve the polar motion cofficients measured/predicted.
Returns
the polar motion values measured/predicted as IERS' Bulletin A.
Definition at line 157 of file julian-date.cc.
References ns3::IersData::EopValues, m_days, and Posix1992.
Referenced by ns3::SatSGP4MobilityModel::PefToItrf().
GregorianDate() [1/2]
DateTime ns3::JulianDate::GregorianDate (uint32_t days, uint32_t ms_day) static private
Convert Julian days into Gregorian calendar.
Parameters
days Full Julian days.
ms_day Milliseconds of the day (since midnight).
Returns
a DateTime struct with the date.
Definition at line 435 of file julian-date.cc.
References ns3::DateTime::day, ns3::DateTime::hours, IsLeapYear(), ns3::DateTime::millisecs, ns3::DateTime::minutes, MinYear, ns3::DateTime::month, Posix1992, ns3::DateTime::seconds, and ns3::DateTime::year.
GregorianDate() [2/2]
DateTime ns3::JulianDate::GregorianDate (void) const private
Convert into Gregorian calendar.
Returns
a DateTime struct with the date.
Definition at line 429 of file julian-date.cc.
References m_days, and m_ms_day.
Referenced by GetDateTime(), and ToString().
IsLeapYear()
bool ns3::JulianDate::IsLeapYear (uint32_t year) static private
Check if it is a leap year.
This function assumes that the year is in the [1992, 2099] range.
Parameters
year the year to check.
Returns
a boolean indicating whether it is a leap year.
Definition at line 401 of file julian-date.cc.
Referenced by GregorianDate().
OffsetFromUtc() [1/2]
Time ns3::JulianDate::OffsetFromUtc (uint32_t daysInPosix, TimeSystem ts) static private
Returns the offset from UTC for a given time.
Parameters
daysInPosix Full days since Unix/POSIX epoch.
ts Time system from.
Returns
the offset from UTC.
Definition at line 487 of file julian-date.cc.
References Dut1(), ns3::DateTime::GPST, ns3::DateTime::TAI, TaiMinusUtc(), TaiToGps, ns3::DateTime::TT, TtToTai, and ns3::DateTime::UT1.
OffsetFromUtc() [2/2]
Time ns3::JulianDate::OffsetFromUtc (void) const private
Returns the offset from UTC.
Returns the offset from UTC to its internal time system as of its internal time.
Returns
the offset from UTC.
Definition at line 481 of file julian-date.cc.
References m_days, and m_time_scale.
Referenced by GetDateTime(), GetDouble(), and ToString().
OffsetToUtc() [1/2]
Time ns3::JulianDate::OffsetToUtc (uint32_t daysInPosix, uint32_t ms_day, TimeSystem ts) static private
Returns the offset to UTC for a given time.
Parameters
daysInPosix Full days since Unix/POSIX epoch.
ms_day Milliseconds of the day (since midnight).
ts Time system to.
Returns
the offset to UTC.
Definition at line 520 of file julian-date.cc.
References Dut1(), ns3::DateTime::GPST, ns3::DateTime::POSIX, ns3::DateTime::TAI, TaiMinusUtc(), TaiToGps, ns3::DateTime::TT, TtToTai, ns3::DateTime::UT1, and ns3::DateTime::UTC.
OffsetToUtc() [2/2]
Time ns3::JulianDate::OffsetToUtc (void) const private
Returns the offset to UTC.
Returns the offset to UTC from its internal time system as of its internal time.
Returns
the offset to UTC.
Definition at line 514 of file julian-date.cc.
References m_days, m_ms_day, and m_time_scale.
Referenced by SetDate().
operator!=()
bool ns3::JulianDate::operator!= (const JulianDate & jd) const
operator != (compare Julian dates).
Parameters
jd Julian days.
Returns
a boolean to indicate if the Julian date is different.
Definition at line 380 of file julian-date.cc.
References m_days, and m_ms_day.
operator+()
JulianDate ns3::JulianDate::operator+ (const Time & t) const
operator + (positive time adjustment).
Parameters
t time adjustment.
Returns
a JulianDate object with the adjustment incorporated.
Definition at line 268 of file julian-date.cc.
References DayToMs, m_days, m_ms_day, and m_time_scale.
operator+=()
void ns3::JulianDate::operator+= (const Time & t)
operator += (positive time adjustment).
Parameters
t time adjustment.
Definition at line 288 of file julian-date.cc.
operator-() [1/2]
Time ns3::JulianDate::operator- (const JulianDate & jd) const
operator - (time between Julian dates).
Parameters
jd Julian days.
Returns
the time between both Julian dates.
Definition at line 326 of file julian-date.cc.
References m_days, and m_ms_day.
operator-() [2/2]
JulianDate ns3::JulianDate::operator- (const Time & t) const
operator - (negative time adjustment).
Parameters
t time adjustment.
Returns
a JulianDate object with the adjustment incorporated.
Definition at line 294 of file julian-date.cc.
References DayToMs, m_days, m_ms_day, and m_time_scale.
operator-=()
void ns3::JulianDate::operator-= (const Time & t)
operator -= (negative time adjustment).
Parameters
t time adjustment.
Definition at line 320 of file julian-date.cc.
operator<()
bool ns3::JulianDate::operator< (const JulianDate & jd) const
operator < (compare Julian dates).
Parameters
jd Julian days.
Returns
a boolean to indicate if the Julian date is prior.
Definition at line 334 of file julian-date.cc.
References m_days, and m_ms_day.
operator<=()
bool ns3::JulianDate::operator<= (const JulianDate & jd) const
operator <= (compare Julian dates).
Parameters
jd Julian days.
Returns
a boolean to indicate if the Julian date is prior or equal.
Definition at line 343 of file julian-date.cc.
References m_days, and m_ms_day.
operator==()
bool ns3::JulianDate::operator== (const JulianDate & jd) const
operator == (compare Julian dates).
Parameters
jd Julian days.
Returns
a boolean to indicate if the Julian date is equal.
Definition at line 371 of file julian-date.cc.
References m_days, and m_ms_day.
operator>()
bool ns3::JulianDate::operator> (const JulianDate & jd) const
operator > (compare Julian dates).
Parameters
jd Julian days.
Returns
a boolean to indicate if the Julian date is later.
Definition at line 353 of file julian-date.cc.
References m_days, and m_ms_day.
operator>=()
bool ns3::JulianDate::operator>= (const JulianDate & jd) const
operator >= (compare Julian dates).
Parameters
jd Julian days.
Returns
a boolean to indicate if the Julian date is equal or later.
Definition at line 362 of file julian-date.cc.
References m_days, and m_ms_day.
SetDate() [1/3]
void ns3::JulianDate::SetDate (const std::string & date, TimeSystem ts = DateTime::UTC)
Set Julian days using time in Gregorian calendar date.
Parameters
date Gregorian calendar date.
ts Time system of the date (UTC, UT1, TAI, TT or GPST).
Definition at line 234 of file julian-date.cc.
References ns3::DateTime::day, ns3::DateTime::hours, m_days, m_ms_day, m_time_scale, MaxYear, ns3::DateTime::millisecs, ns3::DateTime::minutes, MinYear, ns3::DateTime::month, OffsetToUtc(), ns3::DateTime::POSIX, PosixEpoch, ns3::DateTime::seconds, and ns3::DateTime::year.
SetDate() [2/3]
void ns3::JulianDate::SetDate (double jd)
Set the Julian days.
This function has lower precision as there may be some inaccuracy at the millisecond level due to double type limited precision.
Parameters
jd The Julian days.
Definition at line 214 of file julian-date.cc.
References DayToMs, m_days, m_ms_day, m_time_scale, PosixEpoch, and ns3::DateTime::UTC.
Referenced by JulianDate().
SetDate() [3/3]
void ns3::JulianDate::SetDate (uint32_t days, uint32_t ms_day)
Set Julian days using the time since Unix/POSIX epoch.
Parameters
days Full days since Unix/POSIX epoch (1 January 1970, 0h).
ms_day Milliseconds of the day (since midnight).
Definition at line 225 of file julian-date.cc.
References m_days, m_ms_day, m_time_scale, and ns3::DateTime::POSIX.
TaiMinusUtc()
Time ns3::JulianDate::TaiMinusUtc (uint32_t daysInPosix) static private
The difference between TAI and UTC time systems.
Parameters
daysInPosix Full days since Unix/POSIX epoch.
Returns
the difference between TAI and UTC (number of leap seconds).
Definition at line 409 of file julian-date.cc.
References ns3::IersData::BaseLeapSeconds, and ns3::IersData::LeapSeconds.
Referenced by OffsetFromUtc(), and OffsetToUtc().
ToString() [1/2]
std::string ns3::JulianDate::ToString (TimeSystem ts) const
Get the string representation of the Gregorian calendar date in time system ts.
The string is formatted as "YYYY-MM-DD hh:mm:ss.ms TTT", where YYYY is the year, MM the month, DD the day of the month, hh the hour of the day, mm the minutes of the day, ss the seconds of the day, and ms the milliseconds.
Returns
a string representing the Gregorian calendar date in time system ts.
Definition at line 147 of file julian-date.cc.
References m_time_scale, and ToString().
ToString() [2/2]
std::string ns3::JulianDate::ToString (void) const
Get the string representation of the Gregorian calendar date.
The string is formatted as "YYYY-MM-DD hh:mm:ss.ms TTT", where YYYY is the year, MM the month, DD the day of the month, hh the hour of the day, mm the minutes of the day, ss the seconds of the day, and ms the milliseconds.
Returns
a string representing the date in the Gregorian calendar.
Definition at line 133 of file julian-date.cc.
References ns3::DateTime::day, GregorianDate(), ns3::DateTime::hours, m_time_scale, ns3::DateTime::millisecs, ns3::DateTime::minutes, ns3::DateTime::month, OffsetFromUtc(), ns3::DateTime::seconds, and ns3::DateTime::year.
Referenced by ToString().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const JulianDate & jd) friend
operator << (print as GregorianDate).
Print the textual representation (Gregorian calendar date) using the time system specified upon creation or setting.
Parameters
os Output stream object.
jd Julian date object.
Returns
the output stream.
Definition at line 388 of file julian-date.cc.
Member Data Documentation
DayToMs
const uint32_t ns3::JulianDate::DayToMs = HourToMs * 24 static
milliseconds in a day
millisecs in a day
Definition at line 90 of file julian-date.h.
Referenced by GetDouble(), GetOmegaEarth(), operator+(), operator-(), and SetDate().
HourToMs
const uint32_t ns3::JulianDate::HourToMs = 3600000 static
milliseconds in an hour
millisecs in an hour
Definition at line 89 of file julian-date.h.
J2000Epoch
const uint32_t ns3::JulianDate::J2000Epoch = 2451545 static
1 Jan 2000, 12h
Definition at line 87 of file julian-date.h.
m_days
uint32_t ns3::JulianDate::m_days private
full days since epoch.
Definition at line 370 of file julian-date.h.
Referenced by JulianDate(), GetDateTime(), GetDouble(), GetGmst(), GetOmegaEarth(), GetPolarMotion(), GregorianDate(), OffsetFromUtc(), OffsetToUtc(), operator!=(), operator+(), operator-(), operator<(), operator<=(), operator==(), operator>(), operator>=(), and SetDate().
m_ms_day
uint32_t ns3::JulianDate::m_ms_day private
milliseconds of the day.
Definition at line 371 of file julian-date.h.
Referenced by JulianDate(), GetDouble(), GregorianDate(), OffsetToUtc(), operator!=(), operator+(), operator-(), operator<(), operator<=(), operator==(), operator>(), operator>=(), and SetDate().
m_time_scale
TimeSystem ns3::JulianDate::m_time_scale private
external time system.
Definition at line 372 of file julian-date.h.
Referenced by JulianDate(), OffsetFromUtc(), OffsetToUtc(), operator+(), operator-(), SetDate(), and ToString().
MaxYear
const uint32_t ns3::JulianDate::MaxYear = 2099 static
Maximum year supported.
maximum year
Definition at line 85 of file julian-date.h.
Referenced by SetDate().
MinYear
const uint32_t ns3::JulianDate::MinYear = 1992 static
Minimum year supported.
IERS data since.
Definition at line 84 of file julian-date.h.
Referenced by JulianDate(), GregorianDate(), and SetDate().
Posix1992
const uint32_t ns3::JulianDate::Posix1992 = 8035 static
1 Jan 1992 (POSIX days)
1 Jan 1992 (Unix days)
Definition at line 88 of file julian-date.h.
Referenced by Dut1(), GetOmegaEarth(), GetPolarMotion(), and GregorianDate().
PosixEpoch
const double ns3::JulianDate::PosixEpoch = 2440587.5 static
1 Jan 1970, 0h
Definition at line 86 of file julian-date.h.
Referenced by GetDouble(), and SetDate().
PosixYear
const uint32_t ns3::JulianDate::PosixYear = 1970 static
POSIX/Unix epoch year.
POSIX epoch year.
Definition at line 83 of file julian-date.h.
Referenced by JulianDate().
TaiToGps
const Time ns3::JulianDate::TaiToGps = MilliSeconds(19000) static
offset from TAI to GPST
TAI - GPST (in ms)
Definition at line 92 of file julian-date.h.
Referenced by OffsetFromUtc(), and OffsetToUtc().
TtToTai
const Time ns3::JulianDate::TtToTai = MilliSeconds(32184) static
offset from TT to TAI
TT - TAI (in ms)
Definition at line 91 of file julian-date.h.
Referenced by OffsetFromUtc(), and OffsetToUtc().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/julian-date.h
/builds/sns3/satellite/satellite/model/julian-date.cc