SNS3
ns3::LoraNetworkScheduler Class Reference
#include "lora-network-scheduler.h"
Public Member Functions
LoraNetworkScheduler ()
LoraNetworkScheduler (Ptr< LoraNetworkStatus > status, Ptr< LoraNetworkController > controller)
virtual ~LoraNetworkScheduler ()
TypeId GetInstanceTypeId (void) const
void OnReceivedPacket (Ptr< const Packet > packet)
Method called by NetworkServer to inform the Scheduler of a newly arrived uplink packet.
void OnReceiveWindowOpportunity (LoraDeviceAddress deviceAddress, int window)
Method that is scheduled after packet arrivals in order to act on receive windows 1 and 2 seconds later receptions.
Static Public Member Functions
static TypeId GetTypeId (void)
Private Attributes
Ptr< LoraNetworkController > m_controller
Time m_firstWindowAnswerDelay
Delay to wait between end of reception of paquet and sending of anwser, to be in first window opportunity.
TracedCallback< Ptr< const Packet > > m_receiveWindowOpened
Time m_secondWindowAnswerDelay
Delay to wait between end of reception of paquet and sending of anwser, to be in second window opportunity.
Ptr< LoraNetworkStatus > m_status
Detailed Description
Definition at line 42 of file lora-network-scheduler.h.
Constructor & Destructor Documentation
LoraNetworkScheduler() [1/2]
ns3::LoraNetworkScheduler::LoraNetworkScheduler ()
Definition at line 64 of file lora-network-scheduler.cc.
LoraNetworkScheduler() [2/2]
ns3::LoraNetworkScheduler::LoraNetworkScheduler (Ptr< LoraNetworkStatus > status, Ptr< LoraNetworkController > controller)
Definition at line 68 of file lora-network-scheduler.cc.
~LoraNetworkScheduler()
ns3::LoraNetworkScheduler::~LoraNetworkScheduler () virtual
Definition at line 78 of file lora-network-scheduler.cc.
Member Function Documentation
GetInstanceTypeId()
TypeId ns3::LoraNetworkScheduler::GetInstanceTypeId (void) const
Definition at line 59 of file lora-network-scheduler.cc.
References GetTypeId().
GetTypeId()
TypeId ns3::LoraNetworkScheduler::GetTypeId (void) static
Definition at line 33 of file lora-network-scheduler.cc.
References m_firstWindowAnswerDelay, m_receiveWindowOpened, and m_secondWindowAnswerDelay.
Referenced by GetInstanceTypeId().
OnReceivedPacket()
void ns3::LoraNetworkScheduler::OnReceivedPacket (Ptr< const Packet > packet)
Method called by NetworkServer to inform the Scheduler of a newly arrived uplink packet.
This function schedules the OnReceiveWindowOpportunity events 1 and 2 seconds later.
Definition at line 83 of file lora-network-scheduler.cc.
References ns3::LoraFrameHeader::GetAddress(), m_firstWindowAnswerDelay, m_status, OnReceiveWindowOpportunity(), and ns3::LoraFrameHeader::SetAsUplink().
OnReceiveWindowOpportunity()
void ns3::LoraNetworkScheduler::OnReceiveWindowOpportunity (LoraDeviceAddress deviceAddress, int window)
Method that is scheduled after packet arrivals in order to act on receive windows 1 and 2 seconds later receptions.
Definition at line 112 of file lora-network-scheduler.cc.
References m_controller, m_secondWindowAnswerDelay, and m_status.
Referenced by OnReceivedPacket().
Member Data Documentation
m_controller
Ptr<LoraNetworkController> ns3::LoraNetworkScheduler::m_controller private
Definition at line 69 of file lora-network-scheduler.h.
Referenced by OnReceiveWindowOpportunity().
m_firstWindowAnswerDelay
Time ns3::LoraNetworkScheduler::m_firstWindowAnswerDelay private
Delay to wait between end of reception of paquet and sending of anwser, to be in first window opportunity.
Definition at line 75 of file lora-network-scheduler.h.
Referenced by GetTypeId(), and OnReceivedPacket().
m_receiveWindowOpened
TracedCallback<Ptr<const Packet> > ns3::LoraNetworkScheduler::m_receiveWindowOpened private
Definition at line 67 of file lora-network-scheduler.h.
Referenced by GetTypeId().
m_secondWindowAnswerDelay
Time ns3::LoraNetworkScheduler::m_secondWindowAnswerDelay private
Delay to wait between end of reception of paquet and sending of anwser, to be in second window opportunity.
Definition at line 81 of file lora-network-scheduler.h.
Referenced by GetTypeId(), and OnReceiveWindowOpportunity().
m_status
Ptr<LoraNetworkStatus> ns3::LoraNetworkScheduler::m_status private
Definition at line 68 of file lora-network-scheduler.h.
Referenced by OnReceivedPacket(), and OnReceiveWindowOpportunity().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/lora-network-scheduler.h
/builds/sns3/satellite/satellite/model/lora-network-scheduler.cc