SNS3
ns3::SatUtils Class Reference abstract
SatUtils class is for general conversions used in satellite module.
#include "satellite-utils.h"
Static Public Member Functions
template<typename T >
static T DbmToW (T dbm)
Converts Decibel milli Watts to Watts.
template<typename T >
static T DbToLinear (T db)
Converts decibels to linear.
template<typename T >
static T DbWToW (T dbw)
Converts Decibel Watts to Watts.
template<typename T >
static T DegreesToRadians (T degree)
Converts degrees to radians.
static double GetCodingRate (SatEnums::SatModcod_t modcod)
Gets the coding rate of a certain MODCOD.
static SatEnums::SatBbFrameType_t GetFrameTypeS2X (SatEnums::SatModcod_t modcod)
static uint32_t GetModulatedBits (SatEnums::SatModcod_t modcod)
Get the modulated bits of a certain MODCOD.
static std::string GetPacketInfo (const Ptr< const Packet > p)
Get packet information in std::string for printing purposes.
static std::string GetPacketInfo (const std::vector< Ptr< Packet >> packets)
Gets packet information in std::string for printing purposes.
static double Interpolate (double x, double x0, double x1, double y0, double y1)
Simple linear interpolation.
template<typename T >
static T LinearToDb (T linear)
Converts linear to decibels.
template<typename T >
static T MaxDb ()
Get maximum value for Decibel.
template<typename T >
static T MaxLin ()
Get maximum value for linear.
template<typename T >
static T MinDb ()
Get minimum value for Decibel.
template<typename T >
static T MinLin ()
Get minimum value for linear.
template<typename T >
static T RadiansToDegrees (T radian)
Converts radians to degrees.
static double ScalarProduct (const std::vector< std::pair< double, double >> &vector)
Scalar product.
template<typename T >
static T WToDbm (T w)
Converts Watts to Decibel milli Watts.
template<typename T >
static T WToDbW (T w)
Converts Watts to Decibel Watts.
Private Member Functions
virtual ~SatUtils ()=0
Destructor.
Detailed Description
SatUtils class is for general conversions used in satellite module.
This class is not planned to be instantiated or inherited.
Definition at line 42 of file satellite-utils.h.
Constructor & Destructor Documentation
~SatUtils()
virtual ns3::SatUtils::~SatUtils () private pure virtual
Destructor.
Made Pure Virtual because the class is not planned be instantiated or inherited
Member Function Documentation
DbmToW()
template<typename T > static T ns3::SatUtils::DbmToW (T dbm) inline static
Converts Decibel milli Watts to Watts.
Parameters
dbm value in Decibel milli Watts to convert
Returns
Watts converted from Decibel milli Watts
Definition at line 183 of file satellite-utils.h.
DbToLinear()
template<typename T > static T ns3::SatUtils::DbToLinear (T db) inline static
Converts decibels to linear.
Accepted values for conversion are between minimum decibel value and maximum decibel value. Negative infinity is also an accepted value and it is converted to zero.
Parameters
db value in Decibels to convert
Returns
linear converted from Decibels
Definition at line 147 of file satellite-utils.h.
Referenced by ns3::SatGeoFeederPhy::SatGeoFeederPhy(), ns3::SatGeoUserPhy::SatGeoUserPhy(), ns3::SatGwPhy::SatGwPhy(), ns3::SatUtPhy::SatUtPhy(), ns3::SatAntennaGainPattern::GetAntennaGain_lin(), ns3::SatPhyRxCarrierPerWindow::GetEffectiveSnir(), ns3::SatFadingExternalInputTrace::GetFading(), ns3::SatBbFrameConf::InitializeCNoRequirements(), ns3::SatWaveformConf::InitializeEbNoRequirements(), ns3::SatPhyRxCarrierPerSlot::ReceiveSlot(), ns3::SatGeoFeederPhy::SendPduWithParams(), ns3::SatPhyRx::SetAntennaLoss_Db(), and ns3::SatPhyTx::SetMaxAntennaGain_Db().
DbWToW()
template<typename T > static T ns3::SatUtils::DbWToW (T dbw) inline static
Converts Decibel Watts to Watts.
Parameters
dbw value in Decibel Watts to convert
Returns
Watts converted from Decibel Watts
Definition at line 120 of file satellite-utils.h.
Referenced by ns3::SatPhy::Initialize(), and ns3::SatPhyRx::SetMaxAntennaGain_Db().
DegreesToRadians()
template<typename T > static T ns3::SatUtils::DegreesToRadians (T degree) inline static
Converts degrees to radians.
Parameters
degree value to convert as degrees
Returns
radians converted from degrees
Definition at line 64 of file satellite-utils.h.
Referenced by ns3::GeoCoordinate::ToVector(), and ns3::SatMobilityObserver::UpdateElevationAngle().
GetCodingRate()
static double ns3::SatUtils::GetCodingRate (SatEnums::SatModcod_t modcod) inline static
Gets the coding rate of a certain MODCOD.
Parameters
modcod Modulation and coding scheme
Returns
double coding rate
Definition at line 540 of file satellite-utils.h.
References ns3::SatEnums::SAT_MODCOD_16APSK_2_TO_3, ns3::SatEnums::SAT_MODCOD_16APSK_3_TO_4, ns3::SatEnums::SAT_MODCOD_16APSK_4_TO_5, ns3::SatEnums::SAT_MODCOD_16APSK_5_TO_6, ns3::SatEnums::SAT_MODCOD_16APSK_8_TO_9, ns3::SatEnums::SAT_MODCOD_16APSK_9_TO_10, ns3::SatEnums::SAT_MODCOD_16QAM_3_TO_4, ns3::SatEnums::SAT_MODCOD_16QAM_5_TO_6, ns3::SatEnums::SAT_MODCOD_32APSK_3_TO_4, ns3::SatEnums::SAT_MODCOD_32APSK_4_TO_5, ns3::SatEnums::SAT_MODCOD_32APSK_5_TO_6, ns3::SatEnums::SAT_MODCOD_32APSK_8_TO_9, ns3::SatEnums::SAT_MODCOD_8PSK_2_TO_3, ns3::SatEnums::SAT_MODCOD_8PSK_3_TO_4, ns3::SatEnums::SAT_MODCOD_8PSK_3_TO_5, ns3::SatEnums::SAT_MODCOD_8PSK_5_TO_6, ns3::SatEnums::SAT_MODCOD_8PSK_8_TO_9, ns3::SatEnums::SAT_MODCOD_8PSK_9_TO_10, ns3::SatEnums::SAT_MODCOD_BPSK_1_TO_3, ns3::SatEnums::SAT_MODCOD_QPSK_1_TO_2, ns3::SatEnums::SAT_MODCOD_QPSK_1_TO_3, ns3::SatEnums::SAT_MODCOD_QPSK_2_TO_3, ns3::SatEnums::SAT_MODCOD_QPSK_3_TO_4, ns3::SatEnums::SAT_MODCOD_QPSK_3_TO_5, ns3::SatEnums::SAT_MODCOD_QPSK_4_TO_5, ns3::SatEnums::SAT_MODCOD_QPSK_5_TO_6, ns3::SatEnums::SAT_MODCOD_QPSK_8_TO_9, ns3::SatEnums::SAT_MODCOD_QPSK_9_TO_10, ns3::SatEnums::SAT_MODCOD_S2X_128APSK_3_TO_4_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_128APSK_3_TO_4_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_128APSK_7_TO_9_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_128APSK_7_TO_9_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_13_TO_18_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_13_TO_18_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_1_TO_2_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_1_TO_2_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_23_TO_36_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_23_TO_36_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_25_TO_36_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_25_TO_36_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_26_TO_45_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_26_TO_45_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_26_TO_45_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_26_TO_45_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_28_TO_45_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_28_TO_45_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_2_TO_3_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_2_TO_3_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_2_TO_3_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_2_TO_3_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_2_TO_3_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_2_TO_3_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_32_TO_45_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_32_TO_45_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_4_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_4_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_4_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_4_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_5_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_5_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_5_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_5_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_5_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_5_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_4_TO_5_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_4_TO_5_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_4_TO_5_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_4_TO_5_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_5_TO_6_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_5_TO_6_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_5_TO_6_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_5_TO_6_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_5_TO_9_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_5_TO_9_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_77_TO_90_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_77_TO_90_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_7_TO_15_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_7_TO_15_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_7_TO_9_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_7_TO_9_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_8_TO_15_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_8_TO_15_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_8_TO_15_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_8_TO_15_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_8_TO_9_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_8_TO_9_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_8_TO_9_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_8_TO_9_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_9_TO_10_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_9_TO_10_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_11_TO_15_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_11_TO_15_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_29_TO_45_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_29_TO_45_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_2_TO_3_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_2_TO_3_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_31_TO_45_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_31_TO_45_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_32_TO_45_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_32_TO_45_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_3_TO_4_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_3_TO_4_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_11_TO_15_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_11_TO_15_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_2_TO_3_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_2_TO_3_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_2_TO_3_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_2_TO_3_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_32_TO_45_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_32_TO_45_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_32_TO_45_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_32_TO_45_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_3_TO_4_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_3_TO_4_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_3_TO_4_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_3_TO_4_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_4_TO_5_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_4_TO_5_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_4_TO_5_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_4_TO_5_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_5_TO_6_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_5_TO_6_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_5_TO_6_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_5_TO_6_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_7_TO_9_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_7_TO_9_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_8_TO_9_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_8_TO_9_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_8_TO_9_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_8_TO_9_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_9_TO_10_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_9_TO_10_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_11_TO_15_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_11_TO_15_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_32_TO_45_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_32_TO_45_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_4_TO_5_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_4_TO_5_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_5_TO_6_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_5_TO_6_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_7_TO_9_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_7_TO_9_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8APSK_26_TO_45_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8APSK_26_TO_45_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8APSK_5_TO_9_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8APSK_5_TO_9_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_13_TO_18_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_13_TO_18_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_23_TO_36_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_23_TO_36_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_25_TO_36_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_25_TO_36_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_26_TO_45_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_26_TO_45_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_2_TO_3_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_2_TO_3_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_2_TO_3_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_2_TO_3_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_32_TO_45_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_32_TO_45_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_3_TO_4_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_3_TO_4_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_3_TO_4_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_3_TO_4_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_3_TO_5_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_3_TO_5_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_3_TO_5_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_3_TO_5_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_5_TO_6_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_5_TO_6_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_5_TO_6_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_5_TO_6_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_7_TO_15_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_7_TO_15_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_8_TO_15_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_8_TO_15_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_8_TO_9_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_8_TO_9_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_8_TO_9_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_8_TO_9_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_9_TO_10_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_9_TO_10_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_11_TO_20_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_11_TO_20_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_11_TO_45_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_11_TO_45_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_13_TO_45_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_13_TO_45_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_14_TO_45_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_14_TO_45_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_2_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_2_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_2_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_2_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_3_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_3_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_3_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_3_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_4_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_4_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_4_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_4_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_2_TO_3_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_2_TO_3_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_2_TO_3_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_2_TO_3_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_2_TO_5_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_2_TO_5_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_2_TO_5_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_2_TO_5_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_32_TO_45_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_32_TO_45_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_3_TO_4_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_3_TO_4_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_3_TO_4_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_3_TO_4_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_3_TO_5_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_3_TO_5_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_3_TO_5_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_3_TO_5_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_4_TO_15_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_4_TO_15_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_4_TO_5_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_4_TO_5_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_4_TO_5_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_4_TO_5_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_5_TO_6_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_5_TO_6_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_5_TO_6_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_5_TO_6_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_7_TO_15_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_7_TO_15_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_8_TO_15_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_8_TO_15_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_8_TO_9_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_8_TO_9_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_8_TO_9_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_8_TO_9_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_9_TO_10_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_9_TO_10_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_9_TO_20_NORMAL_NOPILOTS, and ns3::SatEnums::SAT_MODCOD_S2X_QPSK_9_TO_20_NORMAL_PILOTS.
Referenced by ns3::SatBbFrameConf::CalculateBbFramePayloadBits(), ns3::SatPhyRxCarrier::CheckAgainstLinkResultsErrorModelAvi(), ns3::LorawanMacGateway::Send(), and ns3::LorawanMacEndDeviceClassA::SendToPhy().
GetFrameTypeS2X()
static SatEnums::SatBbFrameType_t ns3::SatUtils::GetFrameTypeS2X (SatEnums::SatModcod_t modcod) inline static
Definition at line 916 of file satellite-utils.h.
References ns3::SatEnums::NORMAL_FRAME, ns3::SatEnums::SAT_MODCOD_S2X_128APSK_3_TO_4_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_128APSK_3_TO_4_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_128APSK_7_TO_9_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_128APSK_7_TO_9_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_13_TO_18_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_13_TO_18_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_1_TO_2_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_1_TO_2_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_23_TO_36_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_23_TO_36_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_25_TO_36_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_25_TO_36_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_26_TO_45_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_26_TO_45_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_26_TO_45_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_26_TO_45_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_28_TO_45_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_28_TO_45_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_2_TO_3_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_2_TO_3_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_2_TO_3_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_2_TO_3_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_2_TO_3_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_2_TO_3_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_32_TO_45_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_32_TO_45_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_4_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_4_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_4_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_4_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_5_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_5_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_5_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_5_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_5_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_5_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_4_TO_5_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_4_TO_5_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_4_TO_5_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_4_TO_5_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_5_TO_6_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_5_TO_6_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_5_TO_6_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_5_TO_6_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_5_TO_9_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_5_TO_9_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_77_TO_90_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_77_TO_90_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_7_TO_15_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_7_TO_15_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_7_TO_9_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_7_TO_9_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_8_TO_15_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_8_TO_15_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_8_TO_15_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_8_TO_15_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_8_TO_9_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_8_TO_9_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_8_TO_9_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_8_TO_9_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_9_TO_10_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_9_TO_10_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_11_TO_15_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_11_TO_15_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_29_TO_45_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_29_TO_45_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_2_TO_3_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_2_TO_3_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_31_TO_45_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_31_TO_45_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_32_TO_45_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_32_TO_45_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_3_TO_4_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_3_TO_4_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_11_TO_15_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_11_TO_15_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_2_TO_3_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_2_TO_3_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_2_TO_3_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_2_TO_3_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_32_TO_45_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_32_TO_45_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_32_TO_45_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_32_TO_45_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_3_TO_4_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_3_TO_4_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_3_TO_4_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_3_TO_4_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_4_TO_5_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_4_TO_5_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_4_TO_5_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_4_TO_5_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_5_TO_6_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_5_TO_6_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_5_TO_6_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_5_TO_6_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_7_TO_9_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_7_TO_9_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_8_TO_9_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_8_TO_9_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_8_TO_9_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_8_TO_9_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_9_TO_10_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_9_TO_10_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_11_TO_15_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_11_TO_15_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_32_TO_45_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_32_TO_45_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_4_TO_5_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_4_TO_5_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_5_TO_6_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_5_TO_6_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_7_TO_9_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_7_TO_9_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8APSK_26_TO_45_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8APSK_26_TO_45_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8APSK_5_TO_9_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8APSK_5_TO_9_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_13_TO_18_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_13_TO_18_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_23_TO_36_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_23_TO_36_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_25_TO_36_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_25_TO_36_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_26_TO_45_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_26_TO_45_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_2_TO_3_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_2_TO_3_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_2_TO_3_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_2_TO_3_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_32_TO_45_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_32_TO_45_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_3_TO_4_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_3_TO_4_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_3_TO_4_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_3_TO_4_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_3_TO_5_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_3_TO_5_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_3_TO_5_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_3_TO_5_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_5_TO_6_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_5_TO_6_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_5_TO_6_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_5_TO_6_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_7_TO_15_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_7_TO_15_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_8_TO_15_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_8_TO_15_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_8_TO_9_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_8_TO_9_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_8_TO_9_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_8_TO_9_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_9_TO_10_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_9_TO_10_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_11_TO_20_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_11_TO_20_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_11_TO_45_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_11_TO_45_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_13_TO_45_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_13_TO_45_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_14_TO_45_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_14_TO_45_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_2_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_2_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_2_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_2_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_3_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_3_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_3_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_3_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_4_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_4_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_4_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_4_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_2_TO_3_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_2_TO_3_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_2_TO_3_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_2_TO_3_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_2_TO_5_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_2_TO_5_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_2_TO_5_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_2_TO_5_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_32_TO_45_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_32_TO_45_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_3_TO_4_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_3_TO_4_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_3_TO_4_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_3_TO_4_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_3_TO_5_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_3_TO_5_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_3_TO_5_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_3_TO_5_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_4_TO_15_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_4_TO_15_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_4_TO_5_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_4_TO_5_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_4_TO_5_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_4_TO_5_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_5_TO_6_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_5_TO_6_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_5_TO_6_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_5_TO_6_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_7_TO_15_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_7_TO_15_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_8_TO_15_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_8_TO_15_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_8_TO_9_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_8_TO_9_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_8_TO_9_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_8_TO_9_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_9_TO_10_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_9_TO_10_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_9_TO_20_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_9_TO_20_NORMAL_PILOTS, and ns3::SatEnums::SHORT_FRAME.
Referenced by ns3::SatBbFrameConf::SatBbFrameConf().
GetModulatedBits()
static uint32_t ns3::SatUtils::GetModulatedBits (SatEnums::SatModcod_t modcod) inline static
Get the modulated bits of a certain MODCOD.
Parameters
modcod Modulation and coding scheme
Returns
Modulated bits
Definition at line 242 of file satellite-utils.h.
References ns3::SatEnums::SAT_MODCOD_16APSK_2_TO_3, ns3::SatEnums::SAT_MODCOD_16APSK_3_TO_4, ns3::SatEnums::SAT_MODCOD_16APSK_4_TO_5, ns3::SatEnums::SAT_MODCOD_16APSK_5_TO_6, ns3::SatEnums::SAT_MODCOD_16APSK_8_TO_9, ns3::SatEnums::SAT_MODCOD_16APSK_9_TO_10, ns3::SatEnums::SAT_MODCOD_16QAM_3_TO_4, ns3::SatEnums::SAT_MODCOD_16QAM_5_TO_6, ns3::SatEnums::SAT_MODCOD_32APSK_3_TO_4, ns3::SatEnums::SAT_MODCOD_32APSK_4_TO_5, ns3::SatEnums::SAT_MODCOD_32APSK_5_TO_6, ns3::SatEnums::SAT_MODCOD_32APSK_8_TO_9, ns3::SatEnums::SAT_MODCOD_8PSK_2_TO_3, ns3::SatEnums::SAT_MODCOD_8PSK_3_TO_4, ns3::SatEnums::SAT_MODCOD_8PSK_3_TO_5, ns3::SatEnums::SAT_MODCOD_8PSK_5_TO_6, ns3::SatEnums::SAT_MODCOD_8PSK_8_TO_9, ns3::SatEnums::SAT_MODCOD_8PSK_9_TO_10, ns3::SatEnums::SAT_MODCOD_BPSK_1_TO_3, ns3::SatEnums::SAT_MODCOD_QPSK_1_TO_2, ns3::SatEnums::SAT_MODCOD_QPSK_1_TO_3, ns3::SatEnums::SAT_MODCOD_QPSK_2_TO_3, ns3::SatEnums::SAT_MODCOD_QPSK_3_TO_4, ns3::SatEnums::SAT_MODCOD_QPSK_3_TO_5, ns3::SatEnums::SAT_MODCOD_QPSK_4_TO_5, ns3::SatEnums::SAT_MODCOD_QPSK_5_TO_6, ns3::SatEnums::SAT_MODCOD_QPSK_8_TO_9, ns3::SatEnums::SAT_MODCOD_QPSK_9_TO_10, ns3::SatEnums::SAT_MODCOD_S2X_128APSK_3_TO_4_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_128APSK_3_TO_4_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_128APSK_7_TO_9_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_128APSK_7_TO_9_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_13_TO_18_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_13_TO_18_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_1_TO_2_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_1_TO_2_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_23_TO_36_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_23_TO_36_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_25_TO_36_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_25_TO_36_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_26_TO_45_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_26_TO_45_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_26_TO_45_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_26_TO_45_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_28_TO_45_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_28_TO_45_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_2_TO_3_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_2_TO_3_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_2_TO_3_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_2_TO_3_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_2_TO_3_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_2_TO_3_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_32_TO_45_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_32_TO_45_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_4_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_4_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_4_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_4_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_5_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_5_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_5_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_5_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_5_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_3_TO_5_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_4_TO_5_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_4_TO_5_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_4_TO_5_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_4_TO_5_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_5_TO_6_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_5_TO_6_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_5_TO_6_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_5_TO_6_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_5_TO_9_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_5_TO_9_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_77_TO_90_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_77_TO_90_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_7_TO_15_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_7_TO_15_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_7_TO_9_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_7_TO_9_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_8_TO_15_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_8_TO_15_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_8_TO_15_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_8_TO_15_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_8_TO_9_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_8_TO_9_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_8_TO_9_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_8_TO_9_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_9_TO_10_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_16APSK_9_TO_10_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_11_TO_15_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_11_TO_15_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_29_TO_45_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_29_TO_45_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_2_TO_3_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_2_TO_3_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_31_TO_45_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_31_TO_45_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_32_TO_45_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_32_TO_45_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_3_TO_4_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_256APSK_3_TO_4_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_11_TO_15_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_11_TO_15_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_2_TO_3_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_2_TO_3_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_2_TO_3_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_2_TO_3_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_32_TO_45_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_32_TO_45_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_32_TO_45_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_32_TO_45_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_3_TO_4_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_3_TO_4_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_3_TO_4_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_3_TO_4_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_4_TO_5_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_4_TO_5_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_4_TO_5_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_4_TO_5_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_5_TO_6_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_5_TO_6_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_5_TO_6_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_5_TO_6_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_7_TO_9_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_7_TO_9_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_8_TO_9_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_8_TO_9_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_8_TO_9_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_8_TO_9_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_9_TO_10_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_32APSK_9_TO_10_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_11_TO_15_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_11_TO_15_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_32_TO_45_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_32_TO_45_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_4_TO_5_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_4_TO_5_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_5_TO_6_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_5_TO_6_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_7_TO_9_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_64APSK_7_TO_9_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8APSK_26_TO_45_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8APSK_26_TO_45_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8APSK_5_TO_9_L_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8APSK_5_TO_9_L_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_13_TO_18_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_13_TO_18_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_23_TO_36_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_23_TO_36_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_25_TO_36_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_25_TO_36_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_26_TO_45_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_26_TO_45_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_2_TO_3_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_2_TO_3_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_2_TO_3_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_2_TO_3_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_32_TO_45_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_32_TO_45_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_3_TO_4_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_3_TO_4_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_3_TO_4_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_3_TO_4_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_3_TO_5_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_3_TO_5_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_3_TO_5_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_3_TO_5_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_5_TO_6_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_5_TO_6_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_5_TO_6_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_5_TO_6_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_7_TO_15_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_7_TO_15_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_8_TO_15_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_8_TO_15_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_8_TO_9_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_8_TO_9_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_8_TO_9_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_8_TO_9_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_9_TO_10_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_8PSK_9_TO_10_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_11_TO_20_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_11_TO_20_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_11_TO_45_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_11_TO_45_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_13_TO_45_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_13_TO_45_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_14_TO_45_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_14_TO_45_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_2_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_2_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_2_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_2_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_3_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_3_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_3_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_3_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_4_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_4_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_4_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_1_TO_4_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_2_TO_3_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_2_TO_3_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_2_TO_3_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_2_TO_3_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_2_TO_5_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_2_TO_5_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_2_TO_5_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_2_TO_5_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_32_TO_45_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_32_TO_45_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_3_TO_4_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_3_TO_4_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_3_TO_4_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_3_TO_4_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_3_TO_5_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_3_TO_5_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_3_TO_5_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_3_TO_5_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_4_TO_15_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_4_TO_15_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_4_TO_5_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_4_TO_5_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_4_TO_5_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_4_TO_5_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_5_TO_6_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_5_TO_6_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_5_TO_6_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_5_TO_6_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_7_TO_15_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_7_TO_15_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_8_TO_15_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_8_TO_15_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_8_TO_9_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_8_TO_9_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_8_TO_9_SHORT_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_8_TO_9_SHORT_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_9_TO_10_NORMAL_NOPILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_9_TO_10_NORMAL_PILOTS, ns3::SatEnums::SAT_MODCOD_S2X_QPSK_9_TO_20_NORMAL_NOPILOTS, and ns3::SatEnums::SAT_MODCOD_S2X_QPSK_9_TO_20_NORMAL_PILOTS.
Referenced by ns3::SatBbFrameConf::CalculateBbFrameDuration(), ns3::SatBbFrameConf::CalculateBbFramePayloadBits(), and ns3::SatPhyRxCarrier::CheckAgainstLinkResultsErrorModelAvi().
GetPacketInfo() [1/2]
static std::string ns3::SatUtils::GetPacketInfo (const Ptr< const Packet > p) inline static
Get packet information in std::string for printing purposes.
Parameters
p Packet
Returns
Packet information in std::string
Definition at line 206 of file satellite-utils.h.
References ns3::SatMacTag::GetDestAddress(), and ns3::SatMacTag::GetSourceAddress().
Referenced by ns3::SatUtMac::DoEssaTransmit(), ns3::SatUtMac::DoSlottedAlohaTransmit(), ns3::SatGeoLlc::Enque(), ns3::SatGwLlc::Enque(), ns3::SatLlc::Enque(), ns3::SatUtLlc::Enque(), ns3::SatUtMac::FetchPackets(), GetPacketInfo(), ns3::SatGeoLlc::NotifyTxOpportunity(), ns3::SatGwLlc::NotifyTxOpportunity(), ns3::SatUtLlc::NotifyTxOpportunity(), ns3::SatLorawanNetDevice::Receive(), ns3::SatNetDevice::Receive(), ns3::SatLlc::Receive(), ns3::SatGeoFeederPhy::Receive(), ns3::SatGeoUserPhy::Receive(), ns3::SatPhy::Receive(), ns3::SatGeoFeederMac::Receive(), ns3::SatGeoUserMac::Receive(), ns3::SatGwMac::Receive(), ns3::SatUtMac::Receive(), ns3::SatGeoNetDevice::ReceivePacketFeeder(), ns3::SatGeoNetDevice::ReceivePacketUser(), ns3::SatLorawanNetDevice::Send(), ns3::SatNetDevice::Send(), ns3::SatNetDevice::SendControlMsg(), ns3::SatNetDevice::SendFrom(), ns3::SatGeoFeederPhy::SendFromQueue(), ns3::SatGeoUserPhy::SendFromQueue(), ns3::SatGeoMac::SendPacket(), ns3::SatPhy::SendPdu(), ns3::SatGeoFeederPhy::SendPduWithParams(), ns3::SatGeoUserPhy::SendPduWithParams(), and ns3::SatGwMac::StartTransmission().
GetPacketInfo() [2/2]
static std::string ns3::SatUtils::GetPacketInfo (const std::vector< Ptr< Packet >> packets) inline static
Gets packet information in std::string for printing purposes.
Parameters
packets A vector of packets
Returns
Packet information in std::string
Definition at line 225 of file satellite-utils.h.
References GetPacketInfo().
Interpolate()
static double ns3::SatUtils::Interpolate (double x, double x0, double x1, double y0, double y1) inline static
Simple linear interpolation.
y = y0 + (y1-y0)*(x-x0)/(x1-x0) http://en.wikipedia.org/wiki/Linear_interpolation
Parameters
x Interpolated x
x0 Lower x value
x1 Higher x value
y0 Lower y value
y1 Higher y value
Returns
Interpolated value
Definition at line 1160 of file satellite-utils.h.
Referenced by ns3::SatChannelEstimationError::AddError(), ns3::SatLookUpTable::GetBler(), ns3::SatLookUpTable::GetEsNoDb(), ns3::SatMutualInformationTable::GetNormalizedSymbolInformation(), and ns3::SatMutualInformationTable::GetSnirDb().
LinearToDb()
template<typename T > static T ns3::SatUtils::LinearToDb (T linear) inline static
Converts linear to decibels.
Accepted values for conversion are between minimum linear value (greater than zero and maximum linear value. Zero is also accepted and it is converted to -INF.
Parameters
linear value to convert
Returns
Decibels converted from linear
Definition at line 166 of file satellite-utils.h.
Referenced by ns3::SatPhyRxCarrierPerWindow::CalculatePacketInterferenceVectors(), ns3::SatPhyRxCarrier::CheckAgainstLinkResultsErrorModelAvi(), ns3::SatPhyRxCarrierPerFrame::DoFrameEnd(), ns3::SatChannel::DoRxCnoInputTrace(), ns3::SatChannel::DoRxPowerInputTrace(), ns3::SatChannel::DoRxPowerOutputTrace(), ns3::SatWaveform::Dump(), ns3::SatPhyRxCarrierUplink::EndRxData(), ns3::SatWaveformConf::GetBestWaveformId(), ns3::SatPhyRxCarrierPerWindow::GetEffectiveSnir(), ns3::SatFreeSpaceLoss::GetFsldB(), ns3::SatAntennaGainPattern::IsValidPosition(), LinkBudgetTraceCb(), MaxDb(), MinDb(), ns3::SatPhyRxCarrierMarsala::PerformMarsala(), ns3::SatPhyRxCarrierPerFrame::ProcessReceivedCrdsaPacket(), ns3::SatPhyRxCarrierPerWindow::ProcessWindow(), ns3::SatPhyRxCarrierPerSlot::ReceiveSlot(), ns3::SatGeoFeederPhy::SendPduWithParams(), and ns3::SatPhyRxCarrier::StartRx().
MaxDb()
template<typename T > static T ns3::SatUtils::MaxDb () inline static
Get maximum value for Decibel.
Returns
maximum Decibel value
Definition at line 108 of file satellite-utils.h.
References LinearToDb().
MaxLin()
template<typename T > static T ns3::SatUtils::MaxLin () inline static
Get maximum value for linear.
Returns
maximum linear value
Definition at line 86 of file satellite-utils.h.
MinDb()
template<typename T > static T ns3::SatUtils::MinDb () inline static
Get minimum value for Decibel.
Returns
minimum Decibel value
Definition at line 97 of file satellite-utils.h.
References LinearToDb().
MinLin()
template<typename T > static T ns3::SatUtils::MinLin () inline static
Get minimum value for linear.
(The smallest value greater than zero)
Returns
minimum linear value
Definition at line 75 of file satellite-utils.h.
RadiansToDegrees()
template<typename T > static T ns3::SatUtils::RadiansToDegrees (T radian) inline static
Converts radians to degrees.
Parameters
radian value to convert as radians
Returns
degrees converted from radians
Definition at line 52 of file satellite-utils.h.
Referenced by ns3::GeoCoordinate::ConstructFromVector(), and ns3::SatMobilityObserver::UpdateElevationAngle().
ScalarProduct()
static double ns3::SatUtils::ScalarProduct (const std::vector< std::pair< double, double >> & vector) inline static
Scalar product.
Parameters
vector Array of pairs of doubles
Returns
Sum of the product of each pair elements
Definition at line 1174 of file satellite-utils.h.
Referenced by ns3::SatPhyRxCarrierPerWindow::CalculatePacketInterferenceVectors(), ns3::SatPerfectInterferenceElimination::EliminateInterferences(), ns3::SatResidualInterferenceElimination::EliminateInterferences(), ns3::SatSignalParameters::SetInterferencePower(), and ns3::SatSignalParameters::SetInterferencePowerInSatellite().
WToDbm()
template<typename T > static T ns3::SatUtils::WToDbm (T w) inline static
Converts Watts to Decibel milli Watts.
Parameters
w value in Watts to convert
Returns
Decibel milli Watts converted from Watts
Definition at line 195 of file satellite-utils.h.
WToDbW()
template<typename T > static T ns3::SatUtils::WToDbW (T w) inline static
Converts Watts to Decibel Watts.
Parameters
w value in Watts to convert
Returns
Decibel Watts converted from Watts
Definition at line 132 of file satellite-utils.h.
Referenced by LinkBudgetTraceCb().
The documentation for this class was generated from the following file:
/builds/sns3/satellite/satellite/model/satellite-utils.h