SNS3
ns3::SatInputFileStreamTimeLongDoubleContainer Class Reference
Class for input file stream container for storing long double values.
#include "satellite-input-fstream-time-long-double-container.h"
Public Member Functions
SatInputFileStreamTimeLongDoubleContainer ()
Constructor.
SatInputFileStreamTimeLongDoubleContainer (std::string filename, std::ios::openmode filemode, uint32_t valuesInRow)
Constructor.
~SatInputFileStreamTimeLongDoubleContainer ()
Destructor.
void DoDispose ()
Do needed dispose actions.
std::vector< long double > InterpolateBetweenClosestTimeSamples ()
Function for locating time samples enclosing the current time and a linear interpolation between these samples.
std::vector< long double > ProceedToNextClosestTimeSample ()
Function for locating the next closest time sample and returning the values related to it.
void UpdateContainer (std::string filename, std::ios::openmode filemode, uint32_t valuesInRow)
Function for updating the container.
Static Public Member Functions
static TypeId GetTypeId (void)
NS-3 function for type id.
Private Member Functions
void CheckContainerSanity ()
Check container time sample sanity.
void ClearContainer ()
Function for clearing the container.
bool FindNextClosest (uint32_t lastValidPosition, long double timeShiftValue, double long comparisonTimeValue)
Function for locating the next closest value index.
std::vector< long double > ReadRow ()
Function for reading a row from file.
void Reset ()
Function for resetting the variables.
void ResetStream ()
Function for resetting the stream.
Private Attributes
std::vector< std::vector< long double > > m_container
Container for value rows.
std::ios::openmode m_fileMode
File mode.
std::string m_fileName
File name.
std::ifstream * m_inputFileStream
Pointer to input file stream.
SatInputFileStreamWrapper * m_inputFileStreamWrapper
Pointer to input file stream wrapper.
uint32_t m_lastValidPosition
Last valid position.
uint32_t m_numOfPasses
Number for how many times the available samples have been looped over.
uint32_t m_timeColumn
Index for column which contains time information.
long double m_timeShiftValue
Shift value for sample time.
uint32_t m_valuesInRow
Number of values in a row.
Detailed Description
Class for input file stream container for storing long double values.
The class implements reading the values from a file, storing the values and iterating the stored values.
Row format is [time, value1, ..., value n].
Definition at line 42 of file satellite-input-fstream-time-long-double-container.h.
Constructor & Destructor Documentation
SatInputFileStreamTimeLongDoubleContainer() [1/2]
ns3::SatInputFileStreamTimeLongDoubleContainer::SatInputFileStreamTimeLongDoubleContainer (std::string filename, std::ios::openmode filemode, uint32_t valuesInRow)
Constructor.
Parameters
filename file name
filemode file mode
valuesInRow number of values in a row
Definition at line 41 of file satellite-input-fstream-time-long-double-container.cc.
References m_fileMode, m_fileName, m_valuesInRow, and UpdateContainer().
SatInputFileStreamTimeLongDoubleContainer() [2/2]
ns3::SatInputFileStreamTimeLongDoubleContainer::SatInputFileStreamTimeLongDoubleContainer ()
Constructor.
Definition at line 61 of file satellite-input-fstream-time-long-double-container.cc.
~SatInputFileStreamTimeLongDoubleContainer()
ns3::SatInputFileStreamTimeLongDoubleContainer::~SatInputFileStreamTimeLongDoubleContainer ()
Destructor.
Definition at line 78 of file satellite-input-fstream-time-long-double-container.cc.
References Reset().
Member Function Documentation
CheckContainerSanity()
void ns3::SatInputFileStreamTimeLongDoubleContainer::CheckContainerSanity () private
Check container time sample sanity.
check time sample sanity
Definition at line 148 of file satellite-input-fstream-time-long-double-container.cc.
References m_container, and m_timeColumn.
Referenced by UpdateContainer().
ClearContainer()
void ns3::SatInputFileStreamTimeLongDoubleContainer::ClearContainer () private
Function for clearing the container.
Definition at line 347 of file satellite-input-fstream-time-long-double-container.cc.
References m_container, m_lastValidPosition, m_numOfPasses, m_timeShiftValue, and m_valuesInRow.
Referenced by Reset(), and UpdateContainer().
DoDispose()
void ns3::SatInputFileStreamTimeLongDoubleContainer::DoDispose (void)
Do needed dispose actions.
Definition at line 86 of file satellite-input-fstream-time-long-double-container.cc.
References Reset().
FindNextClosest()
bool ns3::SatInputFileStreamTimeLongDoubleContainer::FindNextClosest (uint32_t lastValidPosition, long double timeShiftValue, double long comparisonTimeValue) private
Function for locating the next closest value index.
This locator loops the samples if the container does not have enough samples. Next closest index value is saved to a separate member variable.
Parameters
lastValidPosition position of last matching value
timeShiftValue value to shift the time if needed
comparisonValue value which next closest match to find
Returns
was next time sample found
Definition at line 260 of file satellite-input-fstream-time-long-double-container.cc.
References m_container, m_lastValidPosition, m_numOfPasses, m_timeColumn, m_timeShiftValue, and m_valuesInRow.
Referenced by InterpolateBetweenClosestTimeSamples(), and ProceedToNextClosestTimeSample().
GetTypeId()
TypeId ns3::SatInputFileStreamTimeLongDoubleContainer::GetTypeId (void) static
NS-3 function for type id.
Returns
type id
Definition at line 33 of file satellite-input-fstream-time-long-double-container.cc.
InterpolateBetweenClosestTimeSamples()
std::vector< long double > ns3::SatInputFileStreamTimeLongDoubleContainer::InterpolateBetweenClosestTimeSamples ()
Function for locating time samples enclosing the current time and a linear interpolation between these samples.
Returns
linear interpolation of the current time value between the two closest time samples
Definition at line 209 of file satellite-input-fstream-time-long-double-container.cc.
References FindNextClosest(), m_container, m_lastValidPosition, m_timeColumn, and m_timeShiftValue.
ProceedToNextClosestTimeSample()
std::vector< long double > ns3::SatInputFileStreamTimeLongDoubleContainer::ProceedToNextClosestTimeSample ()
Function for locating the next closest time sample and returning the values related to it.
Returns
matching values
Definition at line 182 of file satellite-input-fstream-time-long-double-container.cc.
References FindNextClosest(), m_container, m_fileName, m_lastValidPosition, m_numOfPasses, m_timeColumn, and m_timeShiftValue.
ReadRow()
std::vector< long double > ns3::SatInputFileStreamTimeLongDoubleContainer::ReadRow () private
Function for reading a row from file.
Returns
the row
Definition at line 132 of file satellite-input-fstream-time-long-double-container.cc.
References m_inputFileStream, and m_valuesInRow.
Referenced by UpdateContainer().
Reset()
void ns3::SatInputFileStreamTimeLongDoubleContainer::Reset (void) private
Function for resetting the variables.
Definition at line 325 of file satellite-input-fstream-time-long-double-container.cc.
References ClearContainer(), and ResetStream().
Referenced by ~SatInputFileStreamTimeLongDoubleContainer(), and DoDispose().
ResetStream()
void ns3::SatInputFileStreamTimeLongDoubleContainer::ResetStream () private
Function for resetting the stream.
Definition at line 334 of file satellite-input-fstream-time-long-double-container.cc.
References m_inputFileStream, and m_inputFileStreamWrapper.
Referenced by Reset(), and UpdateContainer().
UpdateContainer()
void ns3::SatInputFileStreamTimeLongDoubleContainer::UpdateContainer (std::string filename, std::ios::openmode filemode, uint32_t valuesInRow)
Function for updating the container.
Parameters
filename file name
filemode file mode
valuesInRow number of values in a row
Definition at line 95 of file satellite-input-fstream-time-long-double-container.cc.
References CheckContainerSanity(), ClearContainer(), ns3::SatInputFileStreamWrapper::GetStream(), m_container, m_fileMode, m_fileName, m_inputFileStream, m_inputFileStreamWrapper, m_valuesInRow, ReadRow(), and ResetStream().
Referenced by SatInputFileStreamTimeLongDoubleContainer().
Member Data Documentation
m_container
std::vector<std::vector<long double> > ns3::SatInputFileStreamTimeLongDoubleContainer::m_container private
Container for value rows.
Definition at line 148 of file satellite-input-fstream-time-long-double-container.h.
Referenced by CheckContainerSanity(), ClearContainer(), FindNextClosest(), InterpolateBetweenClosestTimeSamples(), ProceedToNextClosestTimeSample(), and UpdateContainer().
m_fileMode
std::ios::openmode ns3::SatInputFileStreamTimeLongDoubleContainer::m_fileMode private
File mode.
Definition at line 158 of file satellite-input-fstream-time-long-double-container.h.
Referenced by SatInputFileStreamTimeLongDoubleContainer(), and UpdateContainer().
m_fileName
std::string ns3::SatInputFileStreamTimeLongDoubleContainer::m_fileName private
File name.
Definition at line 153 of file satellite-input-fstream-time-long-double-container.h.
Referenced by SatInputFileStreamTimeLongDoubleContainer(), ProceedToNextClosestTimeSample(), and UpdateContainer().
m_inputFileStream
std::ifstream* ns3::SatInputFileStreamTimeLongDoubleContainer::m_inputFileStream private
Pointer to input file stream.
Definition at line 143 of file satellite-input-fstream-time-long-double-container.h.
Referenced by ReadRow(), ResetStream(), and UpdateContainer().
m_inputFileStreamWrapper
SatInputFileStreamWrapper* ns3::SatInputFileStreamTimeLongDoubleContainer::m_inputFileStreamWrapper private
Pointer to input file stream wrapper.
Definition at line 138 of file satellite-input-fstream-time-long-double-container.h.
Referenced by ResetStream(), and UpdateContainer().
m_lastValidPosition
uint32_t ns3::SatInputFileStreamTimeLongDoubleContainer::m_lastValidPosition private
Last valid position.
Definition at line 168 of file satellite-input-fstream-time-long-double-container.h.
Referenced by ClearContainer(), FindNextClosest(), InterpolateBetweenClosestTimeSamples(), and ProceedToNextClosestTimeSample().
m_numOfPasses
uint32_t ns3::SatInputFileStreamTimeLongDoubleContainer::m_numOfPasses private
Number for how many times the available samples have been looped over.
Definition at line 173 of file satellite-input-fstream-time-long-double-container.h.
Referenced by ClearContainer(), FindNextClosest(), and ProceedToNextClosestTimeSample().
m_timeColumn
uint32_t ns3::SatInputFileStreamTimeLongDoubleContainer::m_timeColumn private
Index for column which contains time information.
Definition at line 183 of file satellite-input-fstream-time-long-double-container.h.
Referenced by CheckContainerSanity(), FindNextClosest(), InterpolateBetweenClosestTimeSamples(), and ProceedToNextClosestTimeSample().
m_timeShiftValue
long double ns3::SatInputFileStreamTimeLongDoubleContainer::m_timeShiftValue private
Shift value for sample time.
Definition at line 178 of file satellite-input-fstream-time-long-double-container.h.
Referenced by ClearContainer(), FindNextClosest(), InterpolateBetweenClosestTimeSamples(), and ProceedToNextClosestTimeSample().
m_valuesInRow
uint32_t ns3::SatInputFileStreamTimeLongDoubleContainer::m_valuesInRow private
Number of values in a row.
Definition at line 163 of file satellite-input-fstream-time-long-double-container.h.
Referenced by SatInputFileStreamTimeLongDoubleContainer(), ClearContainer(), FindNextClosest(), ReadRow(), and UpdateContainer().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/utils/satellite-input-fstream-time-long-double-container.h
/builds/sns3/satellite/satellite/utils/satellite-input-fstream-time-long-double-container.cc