SNS3
ns3::SatLoraPhyTx Class Reference
Class adding methods linked to Lora, needed to be used in a satellite context.
#include "satellite-lora-phy-tx.h"
Public Types
typedef Callback< void > TxFinishedCallback
Type definition for a callback to call when a packet has finished sending.
Public Types inherited from ns3::SatPhyTx
enum SatPhyTxMode_t { NORMAL , TRANSPARENT }
enum State { IDLE , TX , RECONFIGURING }
PHY states.
Public Member Functions
SatLoraPhyTx ()
Constructor and destructor.
virtual ~SatLoraPhyTx ()
void EndTx ()
bool IsTransmitting ()
void SetTxFinishedCallback (TxFinishedCallback callback)
Set the callback to call after transmission of a packet.
void StartTx (Ptr< SatSignalParameters > txParams)
Start packet transmission to the channel.
Public Member Functions inherited from ns3::SatPhyTx
SatPhyTx ()
Default constructor.
virtual ~SatPhyTx ()
Destructor for SatPhyTx.
bool CanTransmit (void) const
Tell whether or not this channel can transmit data.
void ClearChannel ()
virtual void DoDispose ()
Dispose of this class instance.
double GetAntennaGain (Ptr< MobilityModel > mobility)
Get antenna gain based on position or in case that antenna pattern is not configured, maximum configured gain is return.
Ptr< SatChannel > GetChannel ()
double GetFadingValue (Address macAddress, SatEnums::ChannelType_t channelType)
Get fading value.
Ptr< MobilityModel > GetMobility ()
bool IsTransmitting (void) const
Tell whether or not this channel is transmitting data.
void SetAntennaGainPattern (Ptr< SatAntennaGainPattern > agp, Ptr< SatMobilityModel > mobility)
void SetBeamId (uint32_t beamId)
Set the beam id for all the transmissions from this SatPhyTx.
void SetChannel (Ptr< SatChannel > c)
void SetDefaultFadingValue (double fadingValue)
Function for setting the default fading value.
void SetFadingContainer (Ptr< SatBaseFading > fadingContainer)
Set fading container.
void SetMaxAntennaGain_Db (double gain_db)
Set the maximum Antenna gain in Db.
void SetMobility (Ptr< MobilityModel > m)
void SetSatId (uint32_t satId)
Set the satellite id for all the transmissions from this SatPhyTx.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::SatPhyTx
static TypeId GetTypeId (void)
inherited from Object
Private Attributes
bool m_isTransmitting
TxFinishedCallback m_txFinishedCallback
The callback to perform upon the end of a transmission.
Additional Inherited Members
Detailed Description
Class adding methods linked to Lora, needed to be used in a satellite context.
Definition at line 49 of file satellite-lora-phy-tx.h.
Member Typedef Documentation
TxFinishedCallback
typedef Callback<void> ns3::SatLoraPhyTx::TxFinishedCallback
Type definition for a callback to call when a packet has finished sending.
This callback is used by the MAC layer, to determine when to open a receive window.
Definition at line 67 of file satellite-lora-phy-tx.h.
Constructor & Destructor Documentation
SatLoraPhyTx()
ns3::SatLoraPhyTx::SatLoraPhyTx ()
Constructor and destructor.
Definition at line 37 of file satellite-lora-phy-tx.cc.
~SatLoraPhyTx()
ns3::SatLoraPhyTx::~SatLoraPhyTx () virtual
Definition at line 42 of file satellite-lora-phy-tx.cc.
Member Function Documentation
EndTx()
void ns3::SatLoraPhyTx::EndTx () virtual
Reimplemented from ns3::SatPhyTx.
Definition at line 63 of file satellite-lora-phy-tx.cc.
References ns3::SatPhyTx::EndTx(), m_isTransmitting, and m_txFinishedCallback.
GetTypeId()
TypeId ns3::SatLoraPhyTx::GetTypeId (void) static
Definition at line 31 of file satellite-lora-phy-tx.cc.
IsTransmitting()
bool ns3::SatLoraPhyTx::IsTransmitting (void)
Definition at line 75 of file satellite-lora-phy-tx.cc.
References ns3::SatPhyTx::IsTransmitting(), and m_isTransmitting.
SetTxFinishedCallback()
void ns3::SatLoraPhyTx::SetTxFinishedCallback (TxFinishedCallback callback)
Set the callback to call after transmission of a packet.
This method is typically called by an upper MAC layer that wants to be notified after the transmission of a packet.
Definition at line 47 of file satellite-lora-phy-tx.cc.
References m_txFinishedCallback.
StartTx()
void ns3::SatLoraPhyTx::StartTx (Ptr< SatSignalParameters > txParams) virtual
Start packet transmission to the channel.
Parameters
txParams Transmission parameters for a packet
Reimplemented from ns3::SatPhyTx.
Definition at line 53 of file satellite-lora-phy-tx.cc.
References m_isTransmitting, and ns3::SatPhyTx::StartTx().
Member Data Documentation
m_isTransmitting
bool ns3::SatLoraPhyTx::m_isTransmitting private
Definition at line 94 of file satellite-lora-phy-tx.h.
Referenced by EndTx(), IsTransmitting(), and StartTx().
m_txFinishedCallback
TxFinishedCallback ns3::SatLoraPhyTx::m_txFinishedCallback private
The callback to perform upon the end of a transmission.
Definition at line 92 of file satellite-lora-phy-tx.h.
Referenced by EndTx(), and SetTxFinishedCallback().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-lora-phy-tx.h
/builds/sns3/satellite/satellite/model/satellite-lora-phy-tx.cc