SNS3
ns3::SatFreeSpaceLoss Class Reference
This class is responsible of calculating the free space loss (FSL) based on two given node positions and used (center) frequency.
#include "satellite-free-space-loss.h"
Public Member Functions
SatFreeSpaceLoss ()
Default constructor.
~SatFreeSpaceLoss ()
virtual double GetFsl (Ptr< MobilityModel > a, Ptr< MobilityModel > b, double frequencyHz) const
Calculate the free-space loss in linear format.
virtual double GetFsldB (Ptr< MobilityModel > a, Ptr< MobilityModel > b, double frequencyHz) const
Calculate the free-space loss in dB.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Detailed Description
This class is responsible of calculating the free space loss (FSL) based on two given node positions and used (center) frequency.
Definition at line 35 of file satellite-free-space-loss.h.
Constructor & Destructor Documentation
SatFreeSpaceLoss()
ns3::SatFreeSpaceLoss::SatFreeSpaceLoss ()
Default constructor.
Definition at line 45 of file satellite-free-space-loss.cc.
~SatFreeSpaceLoss()
ns3::SatFreeSpaceLoss::~SatFreeSpaceLoss () inline
Definition at line 49 of file satellite-free-space-loss.h.
Member Function Documentation
GetFsl()
double ns3::SatFreeSpaceLoss::GetFsl (Ptr< MobilityModel > a, Ptr< MobilityModel > b, double frequencyHz) const virtual
Calculate the free-space loss in linear format.
Parameters
a Mobility model of node a
b Mobility model of node b
frequencyHz Frequency in Hertz
Returns
the free space loss as ratio.
Definition at line 62 of file satellite-free-space-loss.cc.
References ns3::SatConstVariables::SPEED_OF_LIGHT.
Referenced by GetFsldB().
GetFsldB()
double ns3::SatFreeSpaceLoss::GetFsldB (Ptr< MobilityModel > a, Ptr< MobilityModel > b, double frequencyHz) const virtual
Calculate the free-space loss in dB.
Parameters
a Mobility model of node a
b Mobility model of node b
frequencyHz Frequency in Hertz
Returns
the free space loss as dBs.
Definition at line 50 of file satellite-free-space-loss.cc.
References GetFsl(), and ns3::SatUtils::LinearToDb().
Referenced by SatFreeSpaceLossTestCase::DoRun().
GetTypeId()
TypeId ns3::SatFreeSpaceLoss::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 38 of file satellite-free-space-loss.cc.
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-free-space-loss.h
/builds/sns3/satellite/satellite/model/satellite-free-space-loss.cc