SNS3
ns3::SatRxCnoInputTraceContainer Class Reference
Class for Rx C/N0 input trace container.
#include "satellite-rx-cno-input-trace-container.h"
Public Types
typedef std::map< key_t, Ptr< SatInputFileStreamTimeDoubleContainer > > container_t
typedef for map of containers
typedef std::map< key_t, double > containerConstantCno_t
typedef for map of containers
typedef std::pair< Address, SatEnums::ChannelType_t > key_t
typedef for map key
Public Member Functions
SatRxCnoInputTraceContainer ()
Constructor.
~SatRxCnoInputTraceContainer ()
Destructor.
Ptr< SatInputFileStreamTimeDoubleContainer > AddNode (std::pair< Address, SatEnums::ChannelType_t > key)
Function for adding the node to the map.
void DoDispose ()
Do needed dispose actions.
TypeId GetInstanceTypeId (void) const
NS-3 instance type id function.
double GetRxCno (key_t key)
Function for getting the Rx C/N0.
void Reset ()
Function for resetting the variables.
void SetRxCno (key_t key, double cno)
Function for setting the Rx C/N0 with constant value.
void SetRxCnoFile (key_t key, std::string path)
Function for setting the Rx C/N0 with input file.
Public Member Functions inherited from ns3::SatBaseTraceContainer
SatBaseTraceContainer ()
Constructor.
virtual ~SatBaseTraceContainer ()
Destructor.
TypeId GetInstanceTypeId (void) const
NS-3 instance type id function.
Static Public Member Functions
static TypeId GetTypeId (void)
NS-3 type id function.
Static Public Member Functions inherited from ns3::SatBaseTraceContainer
static TypeId GetTypeId (void)
NS-3 type id function.
Private Member Functions
Ptr< SatInputFileStreamTimeDoubleContainer > FindNode (key_t key)
Function for finding the container matching the key.
Private Attributes
container_t m_container
Map for containers.
containerConstantCno_t m_containerConstantCno
Container to store the constant values of C/N0.
Additional Inherited Members
Static Public Attributes inherited from ns3::SatBaseTraceContainer
static const uint32_t CSINR_TRACE_DEFAULT_FADING_VALUE_INDEX = 1
Default sinr value index for composite sinr traces.
static const uint32_t CSINR_TRACE_DEFAULT_NUMBER_OF_COLUMNS = 2
Default number of columns for composite sinr traces.
static const uint32_t FADING_TRACE_DEFAULT_FADING_VALUE_INDEX = 1
Default fading value index for fading traces.
static const uint32_t FADING_TRACE_DEFAULT_NUMBER_OF_COLUMNS = 2
Default number of columns for fading traces.
static const uint32_t INTF_TRACE_DEFAULT_INTF_DENSITY_INDEX = 1
Default interference density index for interference traces.
static const uint32_t INTF_TRACE_DEFAULT_NUMBER_OF_COLUMNS = 2
Default number of columns for interference traces.
static const uint32_t POSITION_TRACE_DEFAULT_ALTITUDE_INDEX = 3
Default altitude value index for positions traces.
static const uint32_t POSITION_TRACE_DEFAULT_LATITUDE_INDEX = 1
Default latitude value index for positions traces.
static const uint32_t POSITION_TRACE_DEFAULT_LONGITUDE_INDEX = 2
Default longitude value index for positions traces.
static const uint32_t POSITION_TRACE_DEFAULT_NUMBER_OF_COLUMNS = 4
Default number of columns for position traces.
static const uint32_t RX_CNO_TRACE_DEFAULT_NUMBER_OF_COLUMNS = 2
Default Rx power density index for Rx power traces.
static const uint32_t RX_CNO_TRACE_DEFAULT_RX_POWER_DENSITY_INDEX = 1
Default Rx power density index for Rx power traces.
static const uint32_t RX_POWER_TRACE_DEFAULT_NUMBER_OF_COLUMNS = 2
Default Rx C/N0 index for C/N0 traces.
static const uint32_t RX_POWER_TRACE_DEFAULT_RX_POWER_DENSITY_INDEX = 1
Default Rx C/N0 index for C/N0 traces.
Detailed Description
Class for Rx C/N0 input trace container.
The class contains multiple Rx C/N0 input sample traces and provides an interface to them. It can also be set manually to a constant for chosen nodes.
Definition at line 41 of file satellite-rx-cno-input-trace-container.h.
Member Typedef Documentation
container_t
typedef std::map<key_t, Ptr<SatInputFileStreamTimeDoubleContainer> > ns3::SatRxCnoInputTraceContainer::container_t
typedef for map of containers
Definition at line 52 of file satellite-rx-cno-input-trace-container.h.
containerConstantCno_t
typedef std::map<key_t, double> ns3::SatRxCnoInputTraceContainer::containerConstantCno_t
typedef for map of containers
Definition at line 57 of file satellite-rx-cno-input-trace-container.h.
key_t
typedef std::pair<Address, SatEnums::ChannelType_t> ns3::SatRxCnoInputTraceContainer::key_t
typedef for map key
Definition at line 47 of file satellite-rx-cno-input-trace-container.h.
Constructor & Destructor Documentation
SatRxCnoInputTraceContainer()
ns3::SatRxCnoInputTraceContainer::SatRxCnoInputTraceContainer ()
Constructor.
Definition at line 53 of file satellite-rx-cno-input-trace-container.cc.
~SatRxCnoInputTraceContainer()
ns3::SatRxCnoInputTraceContainer::~SatRxCnoInputTraceContainer ()
Destructor.
Definition at line 58 of file satellite-rx-cno-input-trace-container.cc.
References Reset().
Member Function Documentation
AddNode()
Ptr< SatInputFileStreamTimeDoubleContainer > ns3::SatRxCnoInputTraceContainer::AddNode (std::pair< Address, SatEnums::ChannelType_t > key)
Function for adding the node to the map.
Parameters
key key
Returns
pointer to the added container
Definition at line 92 of file satellite-rx-cno-input-trace-container.cc.
References ns3::SatEnums::GetChannelTypeName(), m_container, and ns3::SatBaseTraceContainer::RX_CNO_TRACE_DEFAULT_NUMBER_OF_COLUMNS.
Referenced by FindNode().
DoDispose()
void ns3::SatRxCnoInputTraceContainer::DoDispose (void)
Do needed dispose actions.
Definition at line 66 of file satellite-rx-cno-input-trace-container.cc.
References Reset().
FindNode()
Ptr< SatInputFileStreamTimeDoubleContainer > ns3::SatRxCnoInputTraceContainer::FindNode (key_t key) private
Function for finding the container matching the key.
Parameters
key key
Returns
matching container
Definition at line 143 of file satellite-rx-cno-input-trace-container.cc.
References AddNode(), and m_container.
Referenced by GetRxCno().
GetInstanceTypeId()
TypeId ns3::SatRxCnoInputTraceContainer::GetInstanceTypeId (void) const
NS-3 instance type id function.
Returns
Instance type is
Definition at line 46 of file satellite-rx-cno-input-trace-container.cc.
References GetTypeId().
GetRxCno()
double ns3::SatRxCnoInputTraceContainer::GetRxCno (key_t key)
Function for getting the Rx C/N0.
Parameters
key key
Returns
Rx C/N0
Definition at line 158 of file satellite-rx-cno-input-trace-container.cc.
References FindNode(), m_containerConstantCno, and ns3::SatBaseTraceContainer::RX_CNO_TRACE_DEFAULT_RX_POWER_DENSITY_INDEX.
GetTypeId()
TypeId ns3::SatRxCnoInputTraceContainer::GetTypeId (void) static
NS-3 type id function.
Returns
type id
Definition at line 37 of file satellite-rx-cno-input-trace-container.cc.
Referenced by GetInstanceTypeId().
Reset()
void ns3::SatRxCnoInputTraceContainer::Reset (void) virtual
Function for resetting the variables.
Implements ns3::SatBaseTraceContainer.
Definition at line 76 of file satellite-rx-cno-input-trace-container.cc.
References m_container, and m_containerConstantCno.
Referenced by ~SatRxCnoInputTraceContainer(), and DoDispose().
SetRxCno()
void ns3::SatRxCnoInputTraceContainer::SetRxCno (key_t key, double cno)
Function for setting the Rx C/N0 with constant value.
Parameters
key key
cno C/N0
Definition at line 175 of file satellite-rx-cno-input-trace-container.cc.
References m_containerConstantCno.
SetRxCnoFile()
void ns3::SatRxCnoInputTraceContainer::SetRxCnoFile (key_t key, std::string path)
Function for setting the Rx C/N0 with input file.
Parameters
key key
path path to C/N0 file
Definition at line 198 of file satellite-rx-cno-input-trace-container.cc.
References m_container, m_containerConstantCno, and ns3::SatBaseTraceContainer::RX_CNO_TRACE_DEFAULT_NUMBER_OF_COLUMNS.
Member Data Documentation
m_container
container_t ns3::SatRxCnoInputTraceContainer::m_container private
Map for containers.
Definition at line 131 of file satellite-rx-cno-input-trace-container.h.
Referenced by AddNode(), FindNode(), Reset(), and SetRxCnoFile().
m_containerConstantCno
containerConstantCno_t ns3::SatRxCnoInputTraceContainer::m_containerConstantCno private
Container to store the constant values of C/N0.
Overrides the use of an input file for them.
Definition at line 137 of file satellite-rx-cno-input-trace-container.h.
Referenced by GetRxCno(), Reset(), SetRxCno(), and SetRxCnoFile().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-rx-cno-input-trace-container.h
/builds/sns3/satellite/satellite/model/satellite-rx-cno-input-trace-container.cc