SNS3
ns3::LoraConfirmedMessagesComponent Class Reference
#include "lora-network-controller-components.h"
Public Member Functions
LoraConfirmedMessagesComponent ()
virtual ~LoraConfirmedMessagesComponent ()
void BeforeSendingReply (Ptr< LoraEndDeviceStatus > status, Ptr< LoraNetworkStatus > networkStatus)
void OnFailedReply (Ptr< LoraEndDeviceStatus > status, Ptr< LoraNetworkStatus > networkStatus)
Method that is called when a packet cannot be sent in the downlink.
void OnReceivedPacket (Ptr< const Packet > packet, Ptr< LoraEndDeviceStatus > status, Ptr< LoraNetworkStatus > networkStatus)
This method checks whether the received packet requires an acknowledgment and sets up the appropriate reply in case it does.
Public Member Functions inherited from ns3::LoraNetworkControllerComponent
LoraNetworkControllerComponent ()
virtual ~LoraNetworkControllerComponent ()
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::LoraNetworkControllerComponent
static TypeId GetTypeId (void)
Detailed Description
Definition at line 86 of file lora-network-controller-components.h.
Constructor & Destructor Documentation
LoraConfirmedMessagesComponent()
ns3::LoraConfirmedMessagesComponent::LoraConfirmedMessagesComponent ()
Definition at line 60 of file lora-network-controller-components.cc.
~LoraConfirmedMessagesComponent()
ns3::LoraConfirmedMessagesComponent::~LoraConfirmedMessagesComponent () virtual
Definition at line 64 of file lora-network-controller-components.cc.
Member Function Documentation
BeforeSendingReply()
void ns3::LoraConfirmedMessagesComponent::BeforeSendingReply (Ptr< LoraEndDeviceStatus > status, Ptr< LoraNetworkStatus > networkStatus) virtual
Implements ns3::LoraNetworkControllerComponent.
Definition at line 108 of file lora-network-controller-components.cc.
GetTypeId()
TypeId ns3::LoraConfirmedMessagesComponent::GetTypeId (void) static
Definition at line 52 of file lora-network-controller-components.cc.
Referenced by OnReceivedPacket().
OnFailedReply()
void ns3::LoraConfirmedMessagesComponent::OnFailedReply (Ptr< LoraEndDeviceStatus > status, Ptr< LoraNetworkStatus > networkStatus) virtual
Method that is called when a packet cannot be sent in the downlink.
Parameters
status The EndDeviceStatus of the device to which it was impossible to send a reply.
networkStatus A pointer to the NetworkStatus object
Implements ns3::LoraNetworkControllerComponent.
Definition at line 116 of file lora-network-controller-components.cc.
OnReceivedPacket()
void ns3::LoraConfirmedMessagesComponent::OnReceivedPacket (Ptr< const Packet > packet, Ptr< LoraEndDeviceStatus > status, Ptr< LoraNetworkStatus > networkStatus) virtual
This method checks whether the received packet requires an acknowledgment and sets up the appropriate reply in case it does.
Parameters
packet The newly received packet
networkStatus A pointer to the NetworkStatus object
Implements ns3::LoraNetworkControllerComponent.
Definition at line 69 of file lora-network-controller-components.cc.
References ns3::LorawanMacHeader::CONFIRMED_DATA_UP, ns3::LoraFrameHeader::GetAddress(), ns3::LorawanMacHeader::GetMType(), GetTypeId(), ns3::LoraFrameHeader::SetAsUplink(), and ns3::LorawanMacHeader::UNCONFIRMED_DATA_DOWN.
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/lora-network-controller-components.h
/builds/sns3/satellite/satellite/model/lora-network-controller-components.cc