SNS3
SatFrameAllocatorTestCase Class Reference
Test case to unit test Satellite Frame Allocator.
Public Member Functions
SatFrameAllocatorTestCase ()
virtual ~SatFrameAllocatorTestCase ()
Private Types
typedef std::map< Address, std::pair< SatFrameAllocator::SatFrameAllocReq, uint32_t > > ReqInfo_t
Private Member Functions
void CheckMultiUtTestResults (SatFrameAllocator::UtAllocInfoContainer_t &utAllocContainer, ReqInfo_t &reqInfo)
void CheckSingleUtTestResults (uint32_t bytesReq, SatFrameAllocator::SatFrameAllocReq req, bool allocated, SatSuperframeConf::ConfigType_t configType, SatFrameAllocator::TbtpMsgContainer_t &tbtpContainer, SatFrameAllocator::UtAllocInfoContainer_t &utAllocContainer, bool rcBasedAllocation, bool fcaEnabled, bool acmEnabled)
SatFrameAllocator::SatFrameAllocReq ContructRequestForUt (uint32_t &totalBytes, uint32_t craBytes, uint32_t minRbdcBytes, uint32_t rbdcBytes, uint32_t vbdcBytes, uint32_t rcCount, bool controlSlot)
virtual void DoRun (void)
void InitFrame (SatSuperframeConf::ConfigType_t configType)
void RunMultiUtTest ()
void RunSingleUtTest (SatSuperframeConf::ConfigType_t configType, bool acmEnabled, bool fcaEnabled)
Private Attributes
SatFrameAllocator::CcLevel_t m_ccLevels [m_ccLevelCount]
uint32_t m_cnoIndex
double m_cnoValues [m_cnoValueCount]
Ptr< SatFrameAllocator > m_frameAllocator
Ptr< SatFrameConf > m_frameConf
Ptr< SatWaveformConf > m_waveFormConf
Static Private Attributes
static const uint32_t m_ccLevelCount = 4
static const uint32_t m_cnoValueCount = 10
Detailed Description
Test case to unit test Satellite Frame Allocator.
This case tests that SatFrameAllocator object allocates symbols (time slots) for UT/RCs correctly with different configurations.
Create frame configuration and frame allocator.
Reset allocator (method Reset)
Allocate UT(s) with RCs to Allocator (method Allocate)
When desired UTs allocated, pre-allocate symbols for the UT/RC(s). (method PreAllocateSymbols)
Finally generate time slots for UTs (method GenerateTimeSlots) by enabling/disabling RC based allocation.
Repeat steps 2 - 5 with different combination of UT/RCs.
Expected result: Time slots for UT/RC should be generated according to allocation requests and limits in frames.
NOTE: Control slot generation should be also enabled for some allocation requests. Test should executed with ACM enabled and disabled, FCA enabled and disabled.
Definition at line 70 of file satellite-frame-allocator-test.cc.
Member Typedef Documentation
ReqInfo_t
typedef std::map<Address, std::pair<SatFrameAllocator::SatFrameAllocReq, uint32_t> > SatFrameAllocatorTestCase::ReqInfo_t private
Definition at line 77 of file satellite-frame-allocator-test.cc.
Constructor & Destructor Documentation
SatFrameAllocatorTestCase()
SatFrameAllocatorTestCase::SatFrameAllocatorTestCase ()
Definition at line 119 of file satellite-frame-allocator-test.cc.
References m_ccLevels, m_cnoIndex, m_cnoValues, and m_waveFormConf.
~SatFrameAllocatorTestCase()
SatFrameAllocatorTestCase::~SatFrameAllocatorTestCase () virtual
Definition at line 145 of file satellite-frame-allocator-test.cc.
Member Function Documentation
CheckMultiUtTestResults()
void SatFrameAllocatorTestCase::CheckMultiUtTestResults (SatFrameAllocator::UtAllocInfoContainer_t & utAllocContainer, ReqInfo_t & reqInfo) private
Definition at line 633 of file satellite-frame-allocator-test.cc.
References m_frameConf.
Referenced by RunMultiUtTest().
CheckSingleUtTestResults()
void SatFrameAllocatorTestCase::CheckSingleUtTestResults (uint32_t bytesReq, SatFrameAllocator::SatFrameAllocReq req, bool allocated, SatSuperframeConf::ConfigType_t configType, SatFrameAllocator::TbtpMsgContainer_t & tbtpContainer, SatFrameAllocator::UtAllocInfoContainer_t & utAllocContainer, bool rcBasedAllocation, bool fcaEnabled, bool acmEnabled) private
Definition at line 366 of file satellite-frame-allocator-test.cc.
References ns3::SatFrameAllocator::SatFrameAllocReq::m_address, m_frameConf, ns3::SatFrameAllocator::SatFrameAllocReq::m_generateCtrlSlot, and ns3::SatFrameAllocator::SatFrameAllocReq::m_reqPerRc.
Referenced by RunSingleUtTest().
ContructRequestForUt()
SatFrameAllocator::SatFrameAllocReq SatFrameAllocatorTestCase::ContructRequestForUt (uint32_t & totalBytes, uint32_t craBytes, uint32_t minRbdcBytes, uint32_t rbdcBytes, uint32_t vbdcBytes, uint32_t rcCount, bool controlSlot) private
Definition at line 670 of file satellite-frame-allocator-test.cc.
References ns3::SatFrameAllocator::SatFrameAllocReq::m_address, ns3::SatFrameAllocator::SatFrameAllocReq::m_cno, m_cnoIndex, m_cnoValueCount, m_cnoValues, m_frameAllocator, m_frameConf, ns3::SatFrameAllocator::SatFrameAllocReq::m_generateCtrlSlot, and ns3::SatFrameAllocator::SatFrameAllocReq::m_reqPerRc.
Referenced by RunMultiUtTest(), and RunSingleUtTest().
DoRun()
void SatFrameAllocatorTestCase::DoRun (void) private virtual
Definition at line 768 of file satellite-frame-allocator-test.cc.
References RunMultiUtTest(), and RunSingleUtTest().
InitFrame()
void SatFrameAllocatorTestCase::InitFrame (SatSuperframeConf::ConfigType_t configType) private
Definition at line 150 of file satellite-frame-allocator-test.cc.
References ns3::SatFrameConf::SatFrameConfParams_t::m_allocationChannel, ns3::SatFrameConf::SatFrameConfParams_t::m_bandwidthHz, ns3::SatFrameConf::SatFrameConfParams_t::m_btuConf, ns3::SatFrameConf::SatFrameConfParams_t::m_checkSlotLimit, ns3::SatFrameConf::SatFrameConfParams_t::m_defaultWaveformInUse, m_frameAllocator, m_frameConf, ns3::SatFrameConf::SatFrameConfParams_t::m_guardTimeSymbols, ns3::SatFrameConf::SatFrameConfParams_t::m_isRandomAccess, ns3::SatFrameConf::SatFrameConfParams_t::m_targetDuration, ns3::SatFrameConf::SatFrameConfParams_t::m_waveformConf, and m_waveFormConf.
Referenced by RunMultiUtTest(), and RunSingleUtTest().
RunMultiUtTest()
void SatFrameAllocatorTestCase::RunMultiUtTest () private
Definition at line 507 of file satellite-frame-allocator-test.cc.
References CheckMultiUtTestResults(), ContructRequestForUt(), InitFrame(), m_ccLevelCount, m_ccLevels, m_frameAllocator, and m_waveFormConf.
Referenced by DoRun().
RunSingleUtTest()
void SatFrameAllocatorTestCase::RunSingleUtTest (SatSuperframeConf::ConfigType_t configType, bool acmEnabled, bool fcaEnabled) private
Definition at line 183 of file satellite-frame-allocator-test.cc.
References CheckSingleUtTestResults(), ContructRequestForUt(), InitFrame(), m_ccLevelCount, m_ccLevels, ns3::SatFrameAllocator::SatFrameAllocReq::m_cno, m_frameAllocator, m_frameConf, and m_waveFormConf.
Referenced by DoRun().
Member Data Documentation
m_ccLevelCount
const uint32_t SatFrameAllocatorTestCase::m_ccLevelCount = 4 static private
Definition at line 79 of file satellite-frame-allocator-test.cc.
Referenced by RunMultiUtTest(), and RunSingleUtTest().
m_ccLevels
SatFrameAllocator::CcLevel_t SatFrameAllocatorTestCase::m_ccLevels[m_ccLevelCount] private
Definition at line 82 of file satellite-frame-allocator-test.cc.
Referenced by SatFrameAllocatorTestCase(), RunMultiUtTest(), and RunSingleUtTest().
m_cnoIndex
uint32_t SatFrameAllocatorTestCase::m_cnoIndex private
Definition at line 84 of file satellite-frame-allocator-test.cc.
Referenced by SatFrameAllocatorTestCase(), and ContructRequestForUt().
m_cnoValueCount
const uint32_t SatFrameAllocatorTestCase::m_cnoValueCount = 10 static private
Definition at line 80 of file satellite-frame-allocator-test.cc.
Referenced by ContructRequestForUt().
m_cnoValues
double SatFrameAllocatorTestCase::m_cnoValues[m_cnoValueCount] private
Definition at line 83 of file satellite-frame-allocator-test.cc.
Referenced by SatFrameAllocatorTestCase(), and ContructRequestForUt().
m_frameAllocator
Ptr<SatFrameAllocator> SatFrameAllocatorTestCase::m_frameAllocator private
Definition at line 87 of file satellite-frame-allocator-test.cc.
Referenced by ContructRequestForUt(), InitFrame(), RunMultiUtTest(), and RunSingleUtTest().
m_frameConf
Ptr<SatFrameConf> SatFrameAllocatorTestCase::m_frameConf private
Definition at line 86 of file satellite-frame-allocator-test.cc.
Referenced by CheckMultiUtTestResults(), CheckSingleUtTestResults(), ContructRequestForUt(), InitFrame(), and RunSingleUtTest().
m_waveFormConf
Ptr<SatWaveformConf> SatFrameAllocatorTestCase::m_waveFormConf private
Definition at line 85 of file satellite-frame-allocator-test.cc.
Referenced by SatFrameAllocatorTestCase(), InitFrame(), RunMultiUtTest(), and RunSingleUtTest().
The documentation for this class was generated from the following file:
/builds/sns3/satellite/satellite/test/satellite-frame-allocator-test.cc