SNS3
ns3::SatMobilityObserver Class Reference
Observes given mobilities and keeps track of certain wanted properties.
#include "satellite-mobility-observer.h"
Public Types
typedef void(* PropertyChangedCallback) (Ptr< const SatMobilityObserver > mobilityObserver)
Callback signature for PropertyChanged trace source.
Public Member Functions
SatMobilityObserver ()
Default constructor of the mobility observer (should not be called)
SatMobilityObserver (Ptr< SatMobilityModel > ownMobility, Ptr< SatMobilityModel > geoSatMobility, bool isRegenerative=false)
Constructor for mobility observer.
virtual ~SatMobilityObserver ()
Destructor of the mobility observer.
virtual void DoDispose (void)
Dispose of this class instance.
double GetElevationAngle (void)
Get elevation angle.
TypeId GetInstanceTypeId (void) const
Time GetTimingAdvance (void)
Get timing advance.
double GetVelocity (void)
Get velocity of own movement (speed).
void ObserveTimingAdvance (Ptr< PropagationDelayModel > ownDelayModel, Ptr< PropagationDelayModel > anotherDelayModel, Ptr< SatMobilityModel > anotherMobility)
Enable observing of the timing advance.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void NotifyPropertyChange (void) const
Notify listeners about some property is changed.
void PositionChanged (std::string context, Ptr< const SatMobilityModel > position)
Listener (callback) for mobility position changes.
void SatelliteStatusChanged ()
Do actions needed when satellite position is changed.
void UpdateElevationAngle ()
Update elevation angle.
void UpdateTimingAdvance ()
Update timing advance.
Private Attributes
Ptr< SatMobilityModel > m_anotherMobility
Ptr< PropagationDelayModel > m_anotherProgDelayModel
double m_earthRadius
double m_elevationAngle
Ptr< SatMobilityModel > m_geoSatMobility
bool m_initialized
bool m_isRegenerative
double m_maxAltitude
double m_maxDistanceToSatellite
double m_minAltitude
Ptr< SatMobilityModel > m_ownMobility
Ptr< PropagationDelayModel > m_ownProgDelayModel
TracedCallback< Ptr< const SatMobilityObserver > > m_propertyChangeTrace
Used to alert subscribers that a change in some observed property has occurred.
double m_radiusRatio
Time m_timingAdvance_s
bool m_updateElevationAngle
bool m_updateTimingAdvance
double m_velocity
Detailed Description
Observes given mobilities and keeps track of certain wanted properties.
Properties can be observed currently are; the timing advance and elevation angle.
Observing of timing advance is set by method ObserveTimingAdvance If satellite regenerates packets on return link, delay corresponds to SAT<->UT link. Otherwise, delay corresponds to GW<->UT link.
Definition at line 43 of file satellite-mobility-observer.h.
Member Typedef Documentation
PropertyChangedCallback
typedef void(* ns3::SatMobilityObserver::PropertyChangedCallback) (Ptr< const SatMobilityObserver > mobilityObserver)
Callback signature for PropertyChanged trace source.
Parameters
mobilityObserver An instance of SatMobilityObserver which property has changed.
Definition at line 117 of file satellite-mobility-observer.h.
Constructor & Destructor Documentation
SatMobilityObserver() [1/2]
ns3::SatMobilityObserver::SatMobilityObserver ()
Default constructor of the mobility observer (should not be called)
Definition at line 94 of file satellite-mobility-observer.cc.
SatMobilityObserver() [2/2]
ns3::SatMobilityObserver::SatMobilityObserver (Ptr< SatMobilityModel > ownMobility, Ptr< SatMobilityModel > geoSatMobility, bool isRegenerative = false)
Constructor for mobility observer.
Parameters
ownMobility Own mobility to observe
geoSatMobility Satellite mobility to observe
isRegenerative Indicates if the satellite regenerates packets
Definition at line 102 of file satellite-mobility-observer.cc.
References ns3::GeoCoordinate::GetAltitude(), ns3::GeoCoordinate::GetRefEllipsoid(), m_earthRadius, m_geoSatMobility, m_initialized, m_ownMobility, m_timingAdvance_s, m_updateElevationAngle, m_updateTimingAdvance, m_velocity, PositionChanged(), SatelliteStatusChanged(), and ns3::GeoCoordinate::ToVector().
~SatMobilityObserver()
ns3::SatMobilityObserver::~SatMobilityObserver () virtual
Destructor of the mobility observer.
Definition at line 159 of file satellite-mobility-observer.cc.
Member Function Documentation
DoDispose()
void ns3::SatMobilityObserver::DoDispose (void) virtual
Dispose of this class instance.
Definition at line 148 of file satellite-mobility-observer.cc.
References m_anotherMobility, m_anotherProgDelayModel, m_geoSatMobility, m_ownMobility, and m_ownProgDelayModel.
GetElevationAngle()
double ns3::SatMobilityObserver::GetElevationAngle (void)
Get elevation angle.
Returns
the current elevation angle as degrees.
Definition at line 193 of file satellite-mobility-observer.cc.
References m_elevationAngle, m_geoSatMobility, m_ownMobility, m_updateElevationAngle, and UpdateElevationAngle().
Referenced by ns3::SatBeamHelper::InstallFadingContainer().
GetInstanceTypeId()
TypeId ns3::SatMobilityObserver::GetInstanceTypeId (void) const
Definition at line 87 of file satellite-mobility-observer.cc.
References GetTypeId().
GetTimingAdvance()
Time ns3::SatMobilityObserver::GetTimingAdvance (void)
Get timing advance.
Returns
the current timing advance.
Definition at line 223 of file satellite-mobility-observer.cc.
References m_anotherMobility, m_anotherProgDelayModel, m_geoSatMobility, m_ownMobility, m_timingAdvance_s, m_updateTimingAdvance, and UpdateTimingAdvance().
Referenced by ns3::SatUtHelper::InstallDvb().
GetTypeId()
TypeId ns3::SatMobilityObserver::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 39 of file satellite-mobility-observer.cc.
References m_anotherMobility, m_anotherProgDelayModel, m_geoSatMobility, m_maxAltitude, m_minAltitude, m_ownMobility, m_ownProgDelayModel, and m_propertyChangeTrace.
Referenced by GetInstanceTypeId().
GetVelocity()
double ns3::SatMobilityObserver::GetVelocity (void)
Get velocity of own movement (speed).
Returns
the current velocity.
Definition at line 211 of file satellite-mobility-observer.cc.
References m_ownMobility, and m_velocity.
Referenced by ns3::SatBeamHelper::InstallFadingContainer().
NotifyPropertyChange()
void ns3::SatMobilityObserver::NotifyPropertyChange (void) const private
Notify listeners about some property is changed.
Definition at line 249 of file satellite-mobility-observer.cc.
References m_initialized, and m_propertyChangeTrace.
Referenced by PositionChanged().
ObserveTimingAdvance()
void ns3::SatMobilityObserver::ObserveTimingAdvance (Ptr< PropagationDelayModel > ownDelayModel, Ptr< PropagationDelayModel > anotherDelayModel, Ptr< SatMobilityModel > anotherMobility)
Enable observing of the timing advance.
Parameters
ownDelayModel Own propagation delay model.
anotherDelayModel Propagation delay model of the another end.
anotherMobility Mobility of the another end.
Definition at line 165 of file satellite-mobility-observer.cc.
References m_anotherMobility, m_anotherProgDelayModel, m_ownMobility, m_ownProgDelayModel, and PositionChanged().
Referenced by ns3::SatUserHelper::UpdateUtRoutes().
PositionChanged()
void ns3::SatMobilityObserver::PositionChanged (std::string context, Ptr< const SatMobilityModel > position) private
Listener (callback) for mobility position changes.
Parameters
context Context of the mobility whose position is changed
position Mobility whose position is changed
Definition at line 260 of file satellite-mobility-observer.cc.
References m_updateElevationAngle, m_updateTimingAdvance, NotifyPropertyChange(), and SatelliteStatusChanged().
Referenced by SatMobilityObserver(), and ObserveTimingAdvance().
SatelliteStatusChanged()
void ns3::SatMobilityObserver::SatelliteStatusChanged () private
Do actions needed when satellite position is changed.
Definition at line 350 of file satellite-mobility-observer.cc.
References m_earthRadius, m_geoSatMobility, m_maxDistanceToSatellite, and m_radiusRatio.
Referenced by SatMobilityObserver(), and PositionChanged().
UpdateElevationAngle()
void ns3::SatMobilityObserver::UpdateElevationAngle () private
Update elevation angle.
Definition at line 282 of file satellite-mobility-observer.cc.
References ns3::SatUtils::DegreesToRadians(), ns3::GeoCoordinate::GetAltitude(), ns3::GeoCoordinate::GetLatitude(), ns3::GeoCoordinate::GetLongitude(), m_elevationAngle, m_geoSatMobility, m_maxAltitude, m_maxDistanceToSatellite, m_minAltitude, m_ownMobility, m_radiusRatio, ns3::SatUtils::RadiansToDegrees(), ns3::GeoCoordinate::SetAltitude(), and ns3::GeoCoordinate::ToVector().
Referenced by GetElevationAngle().
UpdateTimingAdvance()
void ns3::SatMobilityObserver::UpdateTimingAdvance () private
Update timing advance.
Definition at line 331 of file satellite-mobility-observer.cc.
References m_anotherMobility, m_anotherProgDelayModel, m_geoSatMobility, m_isRegenerative, m_ownMobility, m_ownProgDelayModel, and m_timingAdvance_s.
Referenced by GetTimingAdvance().
Member Data Documentation
m_anotherMobility
Ptr<SatMobilityModel> ns3::SatMobilityObserver::m_anotherMobility private
Definition at line 154 of file satellite-mobility-observer.h.
Referenced by DoDispose(), GetTimingAdvance(), GetTypeId(), ObserveTimingAdvance(), and UpdateTimingAdvance().
m_anotherProgDelayModel
Ptr<PropagationDelayModel> ns3::SatMobilityObserver::m_anotherProgDelayModel private
Definition at line 157 of file satellite-mobility-observer.h.
Referenced by DoDispose(), GetTimingAdvance(), GetTypeId(), ObserveTimingAdvance(), and UpdateTimingAdvance().
m_earthRadius
double ns3::SatMobilityObserver::m_earthRadius private
Definition at line 165 of file satellite-mobility-observer.h.
Referenced by SatMobilityObserver(), and SatelliteStatusChanged().
m_elevationAngle
double ns3::SatMobilityObserver::m_elevationAngle private
Definition at line 164 of file satellite-mobility-observer.h.
Referenced by GetElevationAngle(), and UpdateElevationAngle().
m_geoSatMobility
Ptr<SatMobilityModel> ns3::SatMobilityObserver::m_geoSatMobility private
Definition at line 155 of file satellite-mobility-observer.h.
Referenced by SatMobilityObserver(), DoDispose(), GetElevationAngle(), GetTimingAdvance(), GetTypeId(), SatelliteStatusChanged(), UpdateElevationAngle(), and UpdateTimingAdvance().
m_initialized
bool ns3::SatMobilityObserver::m_initialized private
Definition at line 159 of file satellite-mobility-observer.h.
Referenced by SatMobilityObserver(), and NotifyPropertyChange().
m_isRegenerative
bool ns3::SatMobilityObserver::m_isRegenerative private
Definition at line 170 of file satellite-mobility-observer.h.
Referenced by UpdateTimingAdvance().
m_maxAltitude
double ns3::SatMobilityObserver::m_maxAltitude private
Definition at line 163 of file satellite-mobility-observer.h.
Referenced by GetTypeId(), and UpdateElevationAngle().
m_maxDistanceToSatellite
double ns3::SatMobilityObserver::m_maxDistanceToSatellite private
Definition at line 167 of file satellite-mobility-observer.h.
Referenced by SatelliteStatusChanged(), and UpdateElevationAngle().
m_minAltitude
double ns3::SatMobilityObserver::m_minAltitude private
Definition at line 162 of file satellite-mobility-observer.h.
Referenced by GetTypeId(), and UpdateElevationAngle().
m_ownMobility
Ptr<SatMobilityModel> ns3::SatMobilityObserver::m_ownMobility private
Definition at line 153 of file satellite-mobility-observer.h.
Referenced by SatMobilityObserver(), DoDispose(), GetElevationAngle(), GetTimingAdvance(), GetTypeId(), GetVelocity(), ObserveTimingAdvance(), UpdateElevationAngle(), and UpdateTimingAdvance().
m_ownProgDelayModel
Ptr<PropagationDelayModel> ns3::SatMobilityObserver::m_ownProgDelayModel private
Definition at line 156 of file satellite-mobility-observer.h.
Referenced by DoDispose(), GetTypeId(), ObserveTimingAdvance(), and UpdateTimingAdvance().
m_propertyChangeTrace
TracedCallback<Ptr<const SatMobilityObserver> > ns3::SatMobilityObserver::m_propertyChangeTrace private
Used to alert subscribers that a change in some observed property has occurred.
Definition at line 151 of file satellite-mobility-observer.h.
Referenced by GetTypeId(), and NotifyPropertyChange().
m_radiusRatio
double ns3::SatMobilityObserver::m_radiusRatio private
Definition at line 166 of file satellite-mobility-observer.h.
Referenced by SatelliteStatusChanged(), and UpdateElevationAngle().
m_timingAdvance_s
Time ns3::SatMobilityObserver::m_timingAdvance_s private
Definition at line 168 of file satellite-mobility-observer.h.
Referenced by SatMobilityObserver(), GetTimingAdvance(), and UpdateTimingAdvance().
m_updateElevationAngle
bool ns3::SatMobilityObserver::m_updateElevationAngle private
Definition at line 160 of file satellite-mobility-observer.h.
Referenced by SatMobilityObserver(), GetElevationAngle(), and PositionChanged().
m_updateTimingAdvance
bool ns3::SatMobilityObserver::m_updateTimingAdvance private
Definition at line 161 of file satellite-mobility-observer.h.
Referenced by SatMobilityObserver(), GetTimingAdvance(), and PositionChanged().
m_velocity
double ns3::SatMobilityObserver::m_velocity private
Definition at line 169 of file satellite-mobility-observer.h.
Referenced by SatMobilityObserver(), and GetVelocity().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-mobility-observer.h
/builds/sns3/satellite/satellite/model/satellite-mobility-observer.cc