SNS3
ns3::SatStatsCapacityRequestHelper Class Reference
Satellite Statistics
Produce capacity request statistics of Random Access Slotted ALOHA from a satellite module simulation.
#include "satellite-stats-capacity-request-helper.h"
Public Member Functions
SatStatsCapacityRequestHelper (Ptr< const SatHelper > satHelper)
virtual ~SatStatsCapacityRequestHelper ()
/ Destructor.
Public Member Functions inherited from ns3::SatStatsHelper
SatStatsHelper (Ptr< const SatHelper > satHelper)
Creates a new helper instance.
virtual ~SatStatsHelper ()
/ Destructor.
IdentifierType_t GetIdentifierType () const
std::string GetName () const
OutputType_t GetOutputType () const
Ptr< const SatHelper > GetSatHelper () const
void Install ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
bool IsInstalled () const
void SetIdentifierType (IdentifierType_t identifierType)
void SetName (std::string name)
void SetOutputType (OutputType_t outputType)
Static Public Member Functions
static TypeId GetTypeId ()
inherited from ObjectBase base class
Static Public Member Functions inherited from ns3::SatStatsHelper
static std::string GetIdentifierTypeName (IdentifierType_t identifierType)
static std::string GetOutputTypeName (OutputType_t outputType)
static TypeId GetTypeId ()
inherited from ObjectBase base class
Protected Member Functions
void DoInstall ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
Protected Member Functions inherited from ns3::SatStatsHelper
Ptr< DataCollectionObject > CreateAggregator (std::string aggregatorTypeId, std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue())
Create the aggregator according to the output type.
uint32_t CreateCollectorPerIdentifier (CollectorMap &collectorMap) const
Create one collector instance for each identifier in the simulation.
virtual std::string GetDistributionHeading (std::string dataLabel) const
uint32_t GetGwId (Ptr< Node > gwNode) const
uint32_t GetIdentifierForBeam (uint32_t satId, uint32_t beamId) const
uint32_t GetIdentifierForGroup (uint32_t groupId) const
uint32_t GetIdentifierForGw (Ptr< Node > gwNode) const
uint32_t GetIdentifierForIsl (Ptr< Node > satNodeSrc, Ptr< Node > satNodeDst) const
uint32_t GetIdentifierForSat (Ptr< Node > satNode) const
uint32_t GetIdentifierForUt (Ptr< Node > utNode) const
uint32_t GetIdentifierForUtUser (Ptr< Node > utUserNode) const
virtual std::string GetIdentifierHeading (std::string dataLabel) const
virtual std::string GetOutputFileName () const
Compute the path and file name where statistics output should be written to.
virtual std::string GetOutputPath () const
uint32_t GetSatId (Ptr< Node > satNode) const
virtual std::string GetTimeHeading (std::string dataLabel) const
uint32_t GetUtId (Ptr< Node > utNode) const
uint32_t GetUtUserId (Ptr< Node > utUserNode) const
Private Attributes
Ptr< DataCollectionObject > m_aggregator
The aggregator created by this helper.
Additional Inherited Members
Public Types inherited from ns3::SatStatsHelper
enum IdentifierType_t {
IDENTIFIER_GLOBAL = 0 , IDENTIFIER_GW , IDENTIFIER_BEAM , IDENTIFIER_UT ,
IDENTIFIER_UT_USER , IDENTIFIER_SLICE , IDENTIFIER_GROUP , IDENTIFIER_SAT ,
IDENTIFIER_ISL
}
Possible categorization of statistics output.
enum OutputType_t {
OUTPUT_NONE = 0 , OUTPUT_SCALAR_FILE , OUTPUT_SCATTER_FILE , OUTPUT_HISTOGRAM_FILE ,
OUTPUT_PDF_FILE , OUTPUT_CDF_FILE , OUTPUT_SCALAR_PLOT , OUTPUT_SCATTER_PLOT ,
OUTPUT_HISTOGRAM_PLOT , OUTPUT_PDF_PLOT , OUTPUT_CDF_PLOT
}
Possible types and formats of statistics output.
Static Protected Member Functions inherited from ns3::SatStatsHelper
static NetDeviceContainer GetGwSatNetDevice (Ptr< Node > gwNode)
static Ptr< NetDevice > GetSatSatGeoNetDevice (Ptr< Node > satNode)
static Ptr< NetDevice > GetUtSatNetDevice (Ptr< Node > utNode)
Detailed Description
Produce capacity request statistics of Random Access Slotted ALOHA from a satellite module simulation.
Statistics logs every capacity request made in a simulation. Statistics consists of tuples: time, node id, rc id, type (RBDC/VBDC), kbps (RBDC) / bytes (VBDC), queued bytes.
Definition at line 43 of file satellite-stats-capacity-request-helper.h.
Constructor & Destructor Documentation
SatStatsCapacityRequestHelper()
ns3::SatStatsCapacityRequestHelper::SatStatsCapacityRequestHelper (Ptr< const SatHelper > satHelper)
Definition at line 42 of file satellite-stats-capacity-request-helper.cc.
~SatStatsCapacityRequestHelper()
ns3::SatStatsCapacityRequestHelper::~SatStatsCapacityRequestHelper () virtual
/ Destructor.
Definition at line 48 of file satellite-stats-capacity-request-helper.cc.
Member Function Documentation
DoInstall()
void ns3::SatStatsCapacityRequestHelper::DoInstall () protected virtual
Install the probes, collectors, and aggregators necessary to produce the statistics output.
An abstract method of SatStatsHelper which must be implemented by child classes. It will be invoked by Install().
Implements ns3::SatStatsHelper.
Definition at line 61 of file satellite-stats-capacity-request-helper.cc.
References ns3::SatStatsHelper::CreateAggregator(), ns3::SatStatsHelper::GetIdentifierForUt(), ns3::SatStatsHelper::GetIdentifierType(), ns3::SatStatsHelper::GetIdentifierTypeName(), ns3::SatStatsHelper::GetOutputFileName(), ns3::SatStatsHelper::GetOutputType(), ns3::SatStatsHelper::GetOutputTypeName(), ns3::SatStatsHelper::GetSatHelper(), ns3::SatStatsHelper::GetUtSatNetDevice(), ns3::SatStatsHelper::IDENTIFIER_BEAM, ns3::SatStatsHelper::IDENTIFIER_GLOBAL, ns3::SatStatsHelper::IDENTIFIER_GROUP, ns3::SatStatsHelper::IDENTIFIER_GW, ns3::SatStatsHelper::IDENTIFIER_UT, ns3::SatStatsHelper::IDENTIFIER_UT_USER, m_aggregator, and ns3::SatStatsHelper::OUTPUT_SCATTER_FILE.
GetTypeId()
TypeId ns3::SatStatsCapacityRequestHelper::GetTypeId (void) static
inherited from ObjectBase base class
Definition at line 54 of file satellite-stats-capacity-request-helper.cc.
Member Data Documentation
m_aggregator
Ptr<DataCollectionObject> ns3::SatStatsCapacityRequestHelper::m_aggregator private
The aggregator created by this helper.
Definition at line 65 of file satellite-stats-capacity-request-helper.h.
Referenced by DoInstall().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/stats/satellite-stats-capacity-request-helper.h
/builds/sns3/satellite/satellite/stats/satellite-stats-capacity-request-helper.cc