SNS3
ns3::SatTrafficHelper Class Reference
Creates pre-defined trafics.
#include "satellite-traffic-helper.h"
Classes
struct CustomTrafficInfo_s
Struct for info on last custom trafic created.
Public Types
enum TrafficDirection_t { RTN_LINK , FWD_LINK }
enum TrafficType_t {
CBR , HTTP , NRTV , CUSTOM ,
POISSON , VISIO , VOIP
}
List of available traffics.
enum VoipCodec_t {
G_711_1 , G_711_2 , G_723_1 , G_729_2 ,
G_729_3
}
Public Member Functions
SatTrafficHelper ()
Default constructor.
SatTrafficHelper (Ptr< SatHelper > satHelper, Ptr< SatStatsHelperContainer > satStatsHelperContainer)
Create a base SatTrafficHelper for creating customized traffics.
virtual ~SatTrafficHelper ()
Destructor for SatTrafficHelper.
void AddCbrTraffic (TrafficDirection_t direction, std::string interval, uint32_t packetSize, NodeContainer gws, NodeContainer uts, Time startTime, Time stopTime, Time startDelay)
Add a new UDP/CBR traffic between chosen GWs and UTs.
void AddCustomTraffic (TrafficDirection_t direction, std::string interval, uint32_t packetSize, NodeContainer gws, NodeContainer uts, Time startTime, Time stopTime, Time startDelay)
Add a new CBR traffic between chosen GWs and UTs that can be customized.
void AddHttpTraffic (TrafficDirection_t direction, NodeContainer gws, NodeContainer uts, Time startTime, Time stopTime, Time startDelay)
Add a new TCP/HTTP traffic between chosen GWs and UTs.
void AddNrtvTraffic (TrafficDirection_t direction, NodeContainer gws, NodeContainer uts, Time startTime, Time stopTime, Time startDelay)
Add a new TCP/NRTV traffic between chosen GWs and UTs.
void AddPoissonTraffic (TrafficDirection_t direction, Time onTime, Time offTimeExpMean, std::string rate, uint32_t packetSize, NodeContainer gws, NodeContainer uts, Time startTime, Time stopTime, Time startDelay)
Add a new Poisson traffic between chosen GWs and UTs.
void AddVoipTraffic (TrafficDirection_t direction, VoipCodec_t codec, NodeContainer gws, NodeContainer uts, Time startTime, Time stopTime, Time startDelay)
Add a new Poisson traffic between chosen GWs and UTs.
void ChangeCustomTraffic (Time delay, std::string interval, uint32_t packetSize)
Change the parameters of the last custom traffic created.
TypeId GetInstanceTypeId (void) const
Get the type ID of object instance.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
bool HasSinkInstalled (Ptr< Node > node, uint16_t port)
Check if node has a PacketSink installed at certain port.
void UpdateAttribute (Ptr< CbrApplication > application, std::string interval, uint32_t packetSize)
Update the chosen attribute of a custom traffic.
Private Attributes
CustomTrafficInfo_s m_last_custom_application
Ptr< SatHelper > m_satHelper
Ptr< SatStatsHelperContainer > m_satStatsHelperContainer
Detailed Description
Creates pre-defined trafics.
Use SatUserHelper and SatBeamHelper helper objects. TODO update
Definition at line 39 of file satellite-traffic-helper.h.
Member Enumeration Documentation
TrafficDirection_t
enum ns3::SatTrafficHelper::TrafficDirection_t
Enumerator
RTN_LINK
FWD_LINK
Definition at line 65 of file satellite-traffic-helper.h.
TrafficType_t
enum ns3::SatTrafficHelper::TrafficType_t
List of available traffics.
Enumerator
CBR
HTTP
NRTV
CUSTOM
POISSON
VISIO
VOIP
Definition at line 45 of file satellite-traffic-helper.h.
VoipCodec_t
enum ns3::SatTrafficHelper::VoipCodec_t
Enumerator
G_711_1
G_711_2
G_723_1
G_729_2
G_729_3
Definition at line 56 of file satellite-traffic-helper.h.
Constructor & Destructor Documentation
SatTrafficHelper() [1/2]
ns3::SatTrafficHelper::SatTrafficHelper ()
Default constructor.
Not used.
Definition at line 57 of file satellite-traffic-helper.cc.
SatTrafficHelper() [2/2]
ns3::SatTrafficHelper::SatTrafficHelper (Ptr< SatHelper > satHelper, Ptr< SatStatsHelperContainer > satStatsHelperContainer)
Create a base SatTrafficHelper for creating customized traffics.
Definition at line 64 of file satellite-traffic-helper.cc.
References ns3::SatTrafficHelper::CustomTrafficInfo_s::created, and m_last_custom_application.
~SatTrafficHelper()
virtual ns3::SatTrafficHelper::~SatTrafficHelper () inline virtual
Destructor for SatTrafficHelper.
Definition at line 97 of file satellite-traffic-helper.h.
Member Function Documentation
AddCbrTraffic()
void ns3::SatTrafficHelper::AddCbrTraffic (TrafficDirection_t direction, std::string interval, uint32_t packetSize, NodeContainer gws, NodeContainer uts, Time startTime, Time stopTime, Time startDelay)
Add a new UDP/CBR traffic between chosen GWs and UTs.
Parameters
direction Direction of traffic
interval Wait time between transmission of two packets
packetSize Packet size in bytes
gws The Gateways
uts The User Terminals
startTime Application Start time
stopTime Application stop time
startDelay application start delay between each user
Definition at line 73 of file satellite-traffic-helper.cc.
References FWD_LINK, HasSinkInstalled(), m_satHelper, m_satStatsHelperContainer, ns3::SatStatsHelper::OUTPUT_SCALAR_FILE, ns3::SatStatsHelper::OUTPUT_SCATTER_FILE, and RTN_LINK.
AddCustomTraffic()
void ns3::SatTrafficHelper::AddCustomTraffic (TrafficDirection_t direction, std::string interval, uint32_t packetSize, NodeContainer gws, NodeContainer uts, Time startTime, Time stopTime, Time startDelay)
Add a new CBR traffic between chosen GWs and UTs that can be customized.
Parameters
direction Direction of traffic
interval Initial wait time between transmission of two packets
packetSize Packet size in bytes
gws The Gateways
uts The User Terminals
startTime Application Start time
stopTime Application stop time
startDelay application start delay between each user
Definition at line 948 of file satellite-traffic-helper.cc.
References ns3::SatTrafficHelper::CustomTrafficInfo_s::application, ns3::SatTrafficHelper::CustomTrafficInfo_s::created, FWD_LINK, HasSinkInstalled(), m_last_custom_application, m_satHelper, m_satStatsHelperContainer, ns3::SatStatsHelper::OUTPUT_SCALAR_FILE, ns3::SatStatsHelper::OUTPUT_SCATTER_FILE, RTN_LINK, ns3::SatTrafficHelper::CustomTrafficInfo_s::start, and ns3::SatTrafficHelper::CustomTrafficInfo_s::stop.
AddHttpTraffic()
void ns3::SatTrafficHelper::AddHttpTraffic (TrafficDirection_t direction, NodeContainer gws, NodeContainer uts, Time startTime, Time stopTime, Time startDelay)
Add a new TCP/HTTP traffic between chosen GWs and UTs.
Parameters
direction Direction of traffic
gws The Gateways
uts The User Terminals
startTime Application Start time
stopTime Application stop time
startDelay application start delay between each user
Definition at line 234 of file satellite-traffic-helper.cc.
References FWD_LINK, m_satStatsHelperContainer, ns3::SatStatsHelper::OUTPUT_SCALAR_FILE, ns3::SatStatsHelper::OUTPUT_SCATTER_FILE, and RTN_LINK.
AddNrtvTraffic()
void ns3::SatTrafficHelper::AddNrtvTraffic (TrafficDirection_t direction, NodeContainer gws, NodeContainer uts, Time startTime, Time stopTime, Time startDelay)
Add a new TCP/NRTV traffic between chosen GWs and UTs.
Parameters
direction Direction of traffic
gws The Gateways
uts The User Terminals
startTime Application Start time
stopTime Application stop time
startDelay application start delay between each user
Definition at line 384 of file satellite-traffic-helper.cc.
References FWD_LINK, m_satStatsHelperContainer, ns3::SatStatsHelper::OUTPUT_SCALAR_FILE, ns3::SatStatsHelper::OUTPUT_SCATTER_FILE, and RTN_LINK.
AddPoissonTraffic()
void ns3::SatTrafficHelper::AddPoissonTraffic (TrafficDirection_t direction, Time onTime, Time offTimeExpMean, std::string rate, uint32_t packetSize, NodeContainer gws, NodeContainer uts, Time startTime, Time stopTime, Time startDelay)
Add a new Poisson traffic between chosen GWs and UTs.
Parameters
direction Direction of traffic
onTime On time duration in seconds
offTimeExpMean Off time mean in seconds. The off time follows an exponential law of mean offTimeExpMean
rate The rate with the unit
packetSize Packet size in bytes
gws The Gateways
uts The User Terminals
startTime Application Start time
stopTime Application stop time
startDelay application start delay between each user
Definition at line 516 of file satellite-traffic-helper.cc.
References FWD_LINK, HasSinkInstalled(), ns3::SatOnOffHelper::Install(), m_satHelper, m_satStatsHelperContainer, ns3::SatStatsHelper::OUTPUT_SCALAR_FILE, ns3::SatStatsHelper::OUTPUT_SCATTER_FILE, RTN_LINK, and ns3::SatOnOffHelper::SetAttribute().
AddVoipTraffic()
void ns3::SatTrafficHelper::AddVoipTraffic (TrafficDirection_t direction, VoipCodec_t codec, NodeContainer gws, NodeContainer uts, Time startTime, Time stopTime, Time startDelay)
Add a new Poisson traffic between chosen GWs and UTs.
Parameters
direction Direction of traffic
codec the Codec used
gws The Gateways
uts The User Terminals
startTime Application Start time
stopTime Application stop time
startDelay application start delay between each user
Definition at line 700 of file satellite-traffic-helper.cc.
References FWD_LINK, G_711_1, G_711_2, G_723_1, G_729_2, G_729_3, HasSinkInstalled(), ns3::SatOnOffHelper::Install(), m_satHelper, m_satStatsHelperContainer, ns3::SatStatsHelper::OUTPUT_SCALAR_FILE, ns3::SatStatsHelper::OUTPUT_SCATTER_FILE, RTN_LINK, and ns3::SatOnOffHelper::SetAttribute().
ChangeCustomTraffic()
void ns3::SatTrafficHelper::ChangeCustomTraffic (Time delay, std::string interval, uint32_t packetSize)
Change the parameters of the last custom traffic created.
Parameters
delay Delay after traffic launch to apply the changes
interval New wait time between transmission of two packets
packetSize New packet size in bytes
Definition at line 1124 of file satellite-traffic-helper.cc.
References ns3::SatTrafficHelper::CustomTrafficInfo_s::application, ns3::SatTrafficHelper::CustomTrafficInfo_s::created, m_last_custom_application, ns3::SatTrafficHelper::CustomTrafficInfo_s::start, ns3::SatTrafficHelper::CustomTrafficInfo_s::stop, and UpdateAttribute().
GetInstanceTypeId()
TypeId ns3::SatTrafficHelper::GetInstanceTypeId (void) const
Get the type ID of object instance.
Returns
the TypeId of object instance
Definition at line 50 of file satellite-traffic-helper.cc.
References GetTypeId().
GetTypeId()
TypeId ns3::SatTrafficHelper::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 42 of file satellite-traffic-helper.cc.
Referenced by GetInstanceTypeId().
HasSinkInstalled()
bool ns3::SatTrafficHelper::HasSinkInstalled (Ptr< Node > node, uint16_t port) private
Check if node has a PacketSink installed at certain port.
Definition at line 1163 of file satellite-traffic-helper.cc.
Referenced by AddCbrTraffic(), AddCustomTraffic(), AddPoissonTraffic(), and AddVoipTraffic().
UpdateAttribute()
void ns3::SatTrafficHelper::UpdateAttribute (Ptr< CbrApplication > application, std::string interval, uint32_t packetSize) private
Update the chosen attribute of a custom traffic.
Parameters
application The CBR application to update
interval The new interval
packetSize the new packet size
Definition at line 1152 of file satellite-traffic-helper.cc.
Referenced by ChangeCustomTraffic().
Member Data Documentation
m_last_custom_application
CustomTrafficInfo_s ns3::SatTrafficHelper::m_last_custom_application private
Definition at line 242 of file satellite-traffic-helper.h.
Referenced by SatTrafficHelper(), AddCustomTraffic(), and ChangeCustomTraffic().
m_satHelper
Ptr<SatHelper> ns3::SatTrafficHelper::m_satHelper private
Definition at line 238 of file satellite-traffic-helper.h.
Referenced by AddCbrTraffic(), AddCustomTraffic(), AddPoissonTraffic(), and AddVoipTraffic().
m_satStatsHelperContainer
Ptr<SatStatsHelperContainer> ns3::SatTrafficHelper::m_satStatsHelperContainer private
Definition at line 240 of file satellite-traffic-helper.h.
Referenced by AddCbrTraffic(), AddCustomTraffic(), AddHttpTraffic(), AddNrtvTraffic(), AddPoissonTraffic(), and AddVoipTraffic().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/helper/satellite-traffic-helper.h
/builds/sns3/satellite/satellite/helper/satellite-traffic-helper.cc