SNS3
SatRegenerationTest7 Class Reference
'Regeneration, test 7' test case implementation.
Public Member Functions
SatRegenerationTest7 ()
virtual ~SatRegenerationTest7 ()
Private Member Functions
virtual void DoRun (void)
void GeoPhyFeederModcodTraceCb (uint32_t modcod, const Address &address)
void GeoPhyGwModcodTraceCb (uint32_t modcod, const Address &address)
void GeoPhyUserModcodTraceCb (uint32_t modcod, const Address &address)
void GeoPhyUtModcodTraceCb (uint32_t modcod, const Address &address)
double GetAverage (std::vector< uint32_t > list, uint32_t beg, uint32_t end)
double GetMostFrequent (std::vector< uint32_t > list, uint32_t beg, uint32_t end)
Private Attributes
std::vector< uint32_t > m_feederModcods
std::vector< uint32_t > m_gwModcods
Ptr< SatHelper > m_helper
std::vector< uint32_t > m_userModcods
std::vector< uint32_t > m_utModcods
Detailed Description
'Regeneration, test 7' test case implementation.
This case tests ACM on all links. It is based on a SIMPLE scenario, with network regeneration on FWD and RTN.
Expected result: Most robust MODCOD used a start of simulation Efficient MODCOD used on all links after a few seconds Same MODCOD on FWD feeder and FWD user Not same MODCOD on RTN feeder and RTN user
Definition at line 1492 of file satellite-regeneration-test.cc.
Constructor & Destructor Documentation
SatRegenerationTest7()
SatRegenerationTest7::SatRegenerationTest7 ()
Definition at line 1575 of file satellite-regeneration-test.cc.
~SatRegenerationTest7()
SatRegenerationTest7::~SatRegenerationTest7 () virtual
Definition at line 1582 of file satellite-regeneration-test.cc.
Member Function Documentation
DoRun()
void SatRegenerationTest7::DoRun (void) private virtual
Set regeneration mode
Enable ACM
Set simulation output details
Definition at line 1590 of file satellite-regeneration-test.cc.
References GeoPhyFeederModcodTraceCb(), GeoPhyGwModcodTraceCb(), GeoPhyUserModcodTraceCb(), GeoPhyUtModcodTraceCb(), GetAverage(), GetMostFrequent(), m_feederModcods, m_gwModcods, m_helper, m_userModcods, and m_utModcods.
GeoPhyFeederModcodTraceCb()
void SatRegenerationTest7::GeoPhyFeederModcodTraceCb (uint32_t modcod, const Address & address) private
Definition at line 1529 of file satellite-regeneration-test.cc.
References m_feederModcods.
Referenced by DoRun().
GeoPhyGwModcodTraceCb()
void SatRegenerationTest7::GeoPhyGwModcodTraceCb (uint32_t modcod, const Address & address) private
Definition at line 1517 of file satellite-regeneration-test.cc.
References m_gwModcods.
Referenced by DoRun().
GeoPhyUserModcodTraceCb()
void SatRegenerationTest7::GeoPhyUserModcodTraceCb (uint32_t modcod, const Address & address) private
Definition at line 1535 of file satellite-regeneration-test.cc.
References m_userModcods.
Referenced by DoRun().
GeoPhyUtModcodTraceCb()
void SatRegenerationTest7::GeoPhyUtModcodTraceCb (uint32_t modcod, const Address & address) private
Definition at line 1523 of file satellite-regeneration-test.cc.
References m_utModcods.
Referenced by DoRun().
GetAverage()
double SatRegenerationTest7::GetAverage (std::vector< uint32_t > list, uint32_t beg, uint32_t end) private
Definition at line 1541 of file satellite-regeneration-test.cc.
Referenced by DoRun().
GetMostFrequent()
double SatRegenerationTest7::GetMostFrequent (std::vector< uint32_t > list, uint32_t beg, uint32_t end) private
Definition at line 1552 of file satellite-regeneration-test.cc.
Referenced by DoRun().
Member Data Documentation
m_feederModcods
std::vector<uint32_t> SatRegenerationTest7::m_feederModcods private
Definition at line 1512 of file satellite-regeneration-test.cc.
Referenced by DoRun(), and GeoPhyFeederModcodTraceCb().
m_gwModcods
std::vector<uint32_t> SatRegenerationTest7::m_gwModcods private
Definition at line 1510 of file satellite-regeneration-test.cc.
Referenced by DoRun(), and GeoPhyGwModcodTraceCb().
m_helper
Ptr<SatHelper> SatRegenerationTest7::m_helper private
Definition at line 1508 of file satellite-regeneration-test.cc.
Referenced by DoRun().
m_userModcods
std::vector<uint32_t> SatRegenerationTest7::m_userModcods private
Definition at line 1513 of file satellite-regeneration-test.cc.
Referenced by DoRun(), and GeoPhyUserModcodTraceCb().
m_utModcods
std::vector<uint32_t> SatRegenerationTest7::m_utModcods private
Definition at line 1511 of file satellite-regeneration-test.cc.
Referenced by DoRun(), and GeoPhyUtModcodTraceCb().
The documentation for this class was generated from the following file:
/builds/sns3/satellite/satellite/test/satellite-regeneration-test.cc