SNS3
ns3::SatRtnLinkTime Class Reference
SatRtnLinkTime is a singleton class initialized with superframe sequence.
#include "satellite-rtn-link-time.h"
Public Member Functions
SatRtnLinkTime ()
Default constructor.
virtual ~SatRtnLinkTime ()
Destructor for SatRtnLinkTime.
uint32_t GetCurrentSuperFrameCount (uint8_t superFrameSeqId) const
Get currently running superframe count.
uint32_t GetCurrentSuperFrameCount (uint8_t superFrameSeqId, Time timingAdvance) const
Get superframe count for current superframe with a certain timing advance.
Time GetCurrentSuperFrameStartTime (uint8_t superFrameSeqId) const
Get currently running superframe start time.
Time GetCurrentSuperFrameTxTime (uint8_t superFrameSeqId, Time timingAdvance) const
Get superframe transmission time for current superframe with a certain timing advance.
uint32_t GetNextSuperFrameCount (uint8_t superFrameSeqId) const
Get next superframe count.
uint32_t GetNextSuperFrameCount (uint8_t superFrameSeqId, Time timingAdvance) const
Get superframe count for next superframe with a certain timing advance.
Time GetNextSuperFrameStartTime (uint8_t superFrameSeqId) const
Get next superframe start time.
Time GetNextSuperFrameTxTime (uint8_t superFrameSeqId, Time timingAdvance) const
Get superframe transmission time for next superframe with a certain timing advance.
Time GetSuperFrameDuration (uint8_t superFrameSeqId) const
Get superframe duration of a superframe sequence.
Time GetSuperFrameTxTime (uint8_t superFrameSeqId, uint32_t superFrameCount, Time timingAdvance) const
Get superframe transmission time for a UT with a certain timing advance.
void Initialize (Ptr< SatSuperframeSeq > seq)
Initialize with the superframe sequence.
Private Attributes
Ptr< SatSuperframeSeq > m_superframeSeq
Detailed Description
SatRtnLinkTime is a singleton class initialized with superframe sequence.
The class holds information related to return link superframe timing related to both NCC and UT scheduling.
Definition at line 36 of file satellite-rtn-link-time.h.
Constructor & Destructor Documentation
SatRtnLinkTime()
ns3::SatRtnLinkTime::SatRtnLinkTime ()
Default constructor.
Definition at line 34 of file satellite-rtn-link-time.cc.
~SatRtnLinkTime()
ns3::SatRtnLinkTime::~SatRtnLinkTime () virtual
Destructor for SatRtnLinkTime.
Definition at line 40 of file satellite-rtn-link-time.cc.
Member Function Documentation
GetCurrentSuperFrameCount() [1/2]
uint32_t ns3::SatRtnLinkTime::GetCurrentSuperFrameCount (uint8_t superFrameSeqId) const
Get currently running superframe count.
Parameters
superFrameSeqId Superframe sequence id
Returns
Superframe count
Definition at line 60 of file satellite-rtn-link-time.cc.
References m_superframeSeq.
Referenced by GetCurrentSuperFrameStartTime(), GetCurrentSuperFrameTxTime(), and GetNextSuperFrameCount().
GetCurrentSuperFrameCount() [2/2]
uint32_t ns3::SatRtnLinkTime::GetCurrentSuperFrameCount (uint8_t superFrameSeqId, Time timingAdvance) const
Get superframe count for current superframe with a certain timing advance.
Parameters
superFrameSeqId Superframe sequence d
timingAdvance A propagation delay between sender and receiver
Returns
uint32_t Superframe count
Definition at line 107 of file satellite-rtn-link-time.cc.
References m_superframeSeq.
GetCurrentSuperFrameStartTime()
Time ns3::SatRtnLinkTime::GetCurrentSuperFrameStartTime (uint8_t superFrameSeqId) const
Get currently running superframe start time.
Parameters
superFrameSeqId Superframe sequence id
Returns
Superframe start time
Definition at line 77 of file satellite-rtn-link-time.cc.
References GetCurrentSuperFrameCount(), and m_superframeSeq.
GetCurrentSuperFrameTxTime()
Time ns3::SatRtnLinkTime::GetCurrentSuperFrameTxTime (uint8_t superFrameSeqId, Time timingAdvance) const
Get superframe transmission time for current superframe with a certain timing advance.
Parameters
superFrameSeqId Superframe sequence d
timingAdvance A propagation delay between sender and receiver
Returns
Superframe transmission time
Definition at line 129 of file satellite-rtn-link-time.cc.
References GetCurrentSuperFrameCount(), and m_superframeSeq.
GetNextSuperFrameCount() [1/2]
uint32_t ns3::SatRtnLinkTime::GetNextSuperFrameCount (uint8_t superFrameSeqId) const
Get next superframe count.
Parameters
superFrameSeqId Superframe sequence id
Returns
Superframe count
Definition at line 69 of file satellite-rtn-link-time.cc.
References GetCurrentSuperFrameCount().
Referenced by GetNextSuperFrameStartTime(), and GetNextSuperFrameTxTime().
GetNextSuperFrameCount() [2/2]
uint32_t ns3::SatRtnLinkTime::GetNextSuperFrameCount (uint8_t superFrameSeqId, Time timingAdvance) const
Get superframe count for next superframe with a certain timing advance.
Parameters
superFrameSeqId Superframe sequence d
timingAdvance A propagation delay between sender and receiver
Returns
Superframe count
Definition at line 119 of file satellite-rtn-link-time.cc.
References GetCurrentSuperFrameCount().
GetNextSuperFrameStartTime()
Time ns3::SatRtnLinkTime::GetNextSuperFrameStartTime (uint8_t superFrameSeqId) const
Get next superframe start time.
Parameters
superFrameSeqId Superframe sequence id
Returns
Superframe start time
Definition at line 86 of file satellite-rtn-link-time.cc.
References GetNextSuperFrameCount(), and m_superframeSeq.
GetNextSuperFrameTxTime()
Time ns3::SatRtnLinkTime::GetNextSuperFrameTxTime (uint8_t superFrameSeqId, Time timingAdvance) const
Get superframe transmission time for next superframe with a certain timing advance.
Parameters
superFrameSeqId Superframe sequence d
timingAdvance A propagation delay between sender and receiver
Returns
Superframe transmission time
Definition at line 142 of file satellite-rtn-link-time.cc.
References GetNextSuperFrameCount(), and m_superframeSeq.
GetSuperFrameDuration()
Time ns3::SatRtnLinkTime::GetSuperFrameDuration (uint8_t superFrameSeqId) const
Get superframe duration of a superframe sequence.
Parameters
superFrameSeqId Superframe sequence id
Returns
Superframe duration in Time
Definition at line 52 of file satellite-rtn-link-time.cc.
References m_superframeSeq.
GetSuperFrameTxTime()
Time ns3::SatRtnLinkTime::GetSuperFrameTxTime (uint8_t superFrameSeqId, uint32_t superFrameCount, Time timingAdvance) const
Get superframe transmission time for a UT with a certain timing advance.
Parameters
superFrameSeqId Superframe sequence d
superFrameCount Superframe count
timingAdvance A propagation delay between sender and receiver
Returns
Superframe transmission time
Definition at line 95 of file satellite-rtn-link-time.cc.
References m_superframeSeq.
Initialize()
void ns3::SatRtnLinkTime::Initialize (Ptr< SatSuperframeSeq > seq)
Initialize with the superframe sequence.
Parameters
seq Superframe sequence
Definition at line 45 of file satellite-rtn-link-time.cc.
References m_superframeSeq.
Member Data Documentation
m_superframeSeq
Ptr<SatSuperframeSeq> ns3::SatRtnLinkTime::m_superframeSeq private
Definition at line 134 of file satellite-rtn-link-time.h.
Referenced by GetCurrentSuperFrameCount(), GetCurrentSuperFrameStartTime(), GetCurrentSuperFrameTxTime(), GetNextSuperFrameStartTime(), GetNextSuperFrameTxTime(), GetSuperFrameDuration(), GetSuperFrameTxTime(), and Initialize().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-rtn-link-time.h
/builds/sns3/satellite/satellite/model/satellite-rtn-link-time.cc