SNS3
ns3::SatIslArbiterUnicastHelper Class Reference
#include "satellite-isl-arbiter-unicast-helper.h"
Public Member Functions
SatIslArbiterUnicastHelper ()
Default constructor.
SatIslArbiterUnicastHelper (NodeContainer geoNodes, std::vector< std::pair< uint32_t, uint32_t >> isls)
Constructor.
void InstallArbiters ()
Install arbiter on all satellite nodes.
void UpdateArbiters ()
Update arbiter on all satellite nodes.
Static Public Member Functions
static TypeId GetTypeId (void)
Private Member Functions
std::vector< std::map< uint32_t, uint32_t > > CalculateGlobalState ()
Compute routing tables for all satellite nodes.
Private Attributes
NodeContainer m_geoNodes
std::vector< std::pair< uint32_t, uint32_t > > m_isls
Detailed Description
Definition at line 33 of file satellite-isl-arbiter-unicast-helper.h.
Constructor & Destructor Documentation
SatIslArbiterUnicastHelper() [1/2]
ns3::SatIslArbiterUnicastHelper::SatIslArbiterUnicastHelper ()
Default constructor.
Must not be used
Definition at line 45 of file satellite-isl-arbiter-unicast-helper.cc.
SatIslArbiterUnicastHelper() [2/2]
ns3::SatIslArbiterUnicastHelper::SatIslArbiterUnicastHelper (NodeContainer geoNodes, std::vector< std::pair< uint32_t, uint32_t >> isls)
Constructor.
Parameters
geoNodes List of all satellite nodes
isls List of all ISLs
Definition at line 50 of file satellite-isl-arbiter-unicast-helper.cc.
Member Function Documentation
CalculateGlobalState()
std::vector< std::map< uint32_t, uint32_t > > ns3::SatIslArbiterUnicastHelper::CalculateGlobalState () private
Compute routing tables for all satellite nodes.
Definition at line 117 of file satellite-isl-arbiter-unicast-helper.cc.
References m_geoNodes, and m_isls.
Referenced by InstallArbiters().
GetTypeId()
TypeId ns3::SatIslArbiterUnicastHelper::GetTypeId (void) static
Definition at line 37 of file satellite-isl-arbiter-unicast-helper.cc.
InstallArbiters()
void ns3::SatIslArbiterUnicastHelper::InstallArbiters ()
Install arbiter on all satellite nodes.
Definition at line 60 of file satellite-isl-arbiter-unicast-helper.cc.
References CalculateGlobalState(), and m_geoNodes.
Referenced by UpdateArbiters().
UpdateArbiters()
void ns3::SatIslArbiterUnicastHelper::UpdateArbiters ()
Update arbiter on all satellite nodes.
Definition at line 109 of file satellite-isl-arbiter-unicast-helper.cc.
References InstallArbiters().
Member Data Documentation
m_geoNodes
NodeContainer ns3::SatIslArbiterUnicastHelper::m_geoNodes private
Definition at line 68 of file satellite-isl-arbiter-unicast-helper.h.
Referenced by CalculateGlobalState(), and InstallArbiters().
m_isls
std::vector<std::pair<uint32_t, uint32_t> > ns3::SatIslArbiterUnicastHelper::m_isls private
Definition at line 69 of file satellite-isl-arbiter-unicast-helper.h.
Referenced by CalculateGlobalState().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/helper/satellite-isl-arbiter-unicast-helper.h
/builds/sns3/satellite/satellite/helper/satellite-isl-arbiter-unicast-helper.cc