SNS3
ns3::SatAddressTag Class Reference
This class implements a tag that carries the MAC address of the sender of the packet.
#include "satellite-address-tag.h"
Public Member Functions
SatAddressTag ()
/ Creates a SatAddressTag instance with an invalid source address.
SatAddressTag (Address addr)
Creates a SatAddressTag instance with the given source address.
virtual void Deserialize (TagBuffer buf)
Deserializes information from buffer to this instance of Inherited.
virtual TypeId GetInstanceTypeId () const
Get the type ID of instance.
virtual uint32_t GetSerializedSize () const
Inherited from Tag base class.
Address GetSourceAddress () const
Get the source address.
virtual void Print (std::ostream &os) const
Print time stamp of this instance of Inherited.
virtual void Serialize (TagBuffer buf) const
Serializes information to buffer from this instance of Inherited.
void SetSourceAddress (Address addr)
Set the source address.
Static Public Member Functions
static TypeId GetTypeId ()
Inherited from ObjectBase base class.
Private Attributes
Address m_sourceAddress
The source address.
Detailed Description
This class implements a tag that carries the MAC address of the sender of the packet.
Address tag is used for statistics purposes.
Definition at line 35 of file satellite-address-tag.h.
Constructor & Destructor Documentation
SatAddressTag() [1/2]
ns3::SatAddressTag::SatAddressTag ()
/ Creates a SatAddressTag instance with an invalid source address.
Definition at line 32 of file satellite-address-tag.cc.
SatAddressTag() [2/2]
ns3::SatAddressTag::SatAddressTag (Address addr)
Creates a SatAddressTag instance with the given source address.
Parameters
addr the source address.
Definition at line 38 of file satellite-address-tag.cc.
Member Function Documentation
Deserialize()
void ns3::SatAddressTag::Deserialize (TagBuffer buf) virtual
Deserializes information from buffer to this instance of Inherited.
Parameters
buf Buffer from which the information is deserialized
Definition at line 74 of file satellite-address-tag.cc.
References m_sourceAddress.
GetInstanceTypeId()
TypeId ns3::SatAddressTag::GetInstanceTypeId (void) const virtual
Get the type ID of instance.
Returns
the object TypeId
Definition at line 54 of file satellite-address-tag.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::SatAddressTag::GetSerializedSize (void) const virtual
Inherited from Tag base class.
Definition at line 60 of file satellite-address-tag.cc.
References m_sourceAddress.
GetSourceAddress()
Address ns3::SatAddressTag::GetSourceAddress () const
Get the source address.
Returns
the source address.
Definition at line 96 of file satellite-address-tag.cc.
References m_sourceAddress.
Referenced by ns3::SatGeoFeederPhy::GetE2ESourceAddress(), ns3::SatLorawanNetDevice::Receive(), ns3::SatNetDevice::Receive(), ns3::SatGeoUserPhy::RxTraces(), ns3::SatMac::RxTraces(), ns3::SatPhy::RxTraces(), and ns3::SatLorawanNetDevice::Send().
GetTypeId()
TypeId ns3::SatAddressTag::GetTypeId (void) static
Inherited from ObjectBase base class.
Definition at line 46 of file satellite-address-tag.cc.
Referenced by ns3::SatGeoFeederPhy::GetE2ESourceAddress(), GetInstanceTypeId(), ns3::SatLorawanNetDevice::Receive(), ns3::SatNetDevice::Receive(), ns3::SatGeoUserPhy::RxTraces(), ns3::SatMac::RxTraces(), ns3::SatPhy::RxTraces(), and ns3::SatLorawanNetDevice::Send().
Print()
void ns3::SatAddressTag::Print (std::ostream & os) const virtual
Print time stamp of this instance of Inherited.
Parameters
&os Output stream to which tag timestamp is printed.
Definition at line 82 of file satellite-address-tag.cc.
References m_sourceAddress.
Serialize()
void ns3::SatAddressTag::Serialize (TagBuffer buf) const virtual
Serializes information to buffer from this instance of Inherited.
Parameters
buf Buffer in which the information is serialized
Definition at line 66 of file satellite-address-tag.cc.
References m_sourceAddress.
SetSourceAddress()
void ns3::SatAddressTag::SetSourceAddress (Address addr)
Set the source address.
Parameters
addr the source address.
Definition at line 89 of file satellite-address-tag.cc.
References m_sourceAddress.
Member Data Documentation
m_sourceAddress
Address ns3::SatAddressTag::m_sourceAddress private
The source address.
Definition at line 96 of file satellite-address-tag.h.
Referenced by Deserialize(), GetSerializedSize(), GetSourceAddress(), Print(), Serialize(), and SetSourceAddress().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-address-tag.h
/builds/sns3/satellite/satellite/model/satellite-address-tag.cc