SNS3
ns3::SatOnOffHelper Class Reference
A helper to make it easier to instantiate an ns3::SatOnOffApplication on a set of nodes.
#include "satellite-on-off-helper.h"
Public Member Functions
SatOnOffHelper (std::string protocol, Address address)
Create an SatOnOffHelper to make it easier to work with SatOnOffApplications.
ApplicationContainer Install (NodeContainer c) const
Install an ns3::SatOnOffApplication on each node of the input container configured with all the attributes set with SetAttribute.
ApplicationContainer Install (Ptr< Node > node) const
Install an ns3::SatOnOffApplication on the node configured with all the attributes set with SetAttribute.
void SetAttribute (std::string name, const AttributeValue &value)
Helper function used to set the underlying application attributes.
void SetConstantRate (DataRate dataRate, uint32_t packetSize=512)
Helper function to set a constant rate source.
Private Member Functions
Ptr< Application > InstallPriv (Ptr< Node > node) const
Install an ns3::SatOnOffApplication on the node configured with all the attributes set with SetAttribute.
Private Attributes
ObjectFactory m_factory
Object factory.
Detailed Description
A helper to make it easier to instantiate an ns3::SatOnOffApplication on a set of nodes.
Definition at line 43 of file satellite-on-off-helper.h.
Constructor & Destructor Documentation
SatOnOffHelper()
ns3::SatOnOffHelper::SatOnOffHelper (std::string protocol, Address address)
Create an SatOnOffHelper to make it easier to work with SatOnOffApplications.
Parameters
protocol the name of the protocol to use to send traffic by the applications. This string identifies the socket factory type used to create sockets for the applications. A typical value would be ns3::UdpSocketFactory.
address the address of the remote node to send traffic to.
Definition at line 29 of file satellite-on-off-helper.cc.
References m_factory.
Member Function Documentation
Install() [1/2]
ApplicationContainer ns3::SatOnOffHelper::Install (NodeContainer c) const
Install an ns3::SatOnOffApplication on each node of the input container configured with all the attributes set with SetAttribute.
Parameters
c NodeContainer of the set of nodes on which an SatOnOffApplication will be installed.
Returns
Container of Ptr to the applications installed.
Definition at line 49 of file satellite-on-off-helper.cc.
References InstallPriv().
Referenced by ns3::SatTrafficHelper::AddPoissonTraffic(), ns3::SatTrafficHelper::AddVoipTraffic(), and ns3::SimulationHelper::InstallTrafficModel().
Install() [2/2]
ApplicationContainer ns3::SatOnOffHelper::Install (Ptr< Node > node) const
Install an ns3::SatOnOffApplication on the node configured with all the attributes set with SetAttribute.
Parameters
node The node on which an SatOnOffApplication will be installed.
Returns
Container of Ptr to the applications installed.
Definition at line 43 of file satellite-on-off-helper.cc.
References InstallPriv().
InstallPriv()
Ptr< Application > ns3::SatOnOffHelper::InstallPriv (Ptr< Node > node) const private
Install an ns3::SatOnOffApplication on the node configured with all the attributes set with SetAttribute.
Parameters
node The node on which an SatOnOffApplication will be installed.
Returns
Ptr to the application installed.
Definition at line 61 of file satellite-on-off-helper.cc.
References m_factory.
Referenced by Install().
SetAttribute()
void ns3::SatOnOffHelper::SetAttribute (std::string name, const AttributeValue & value)
Helper function used to set the underlying application attributes.
Parameters
name the name of the application attribute to set
value the value of the application attribute to set
Definition at line 37 of file satellite-on-off-helper.cc.
References m_factory.
Referenced by ns3::SatTrafficHelper::AddPoissonTraffic(), ns3::SatTrafficHelper::AddVoipTraffic(), and ns3::SimulationHelper::InstallTrafficModel().
SetConstantRate()
void ns3::SatOnOffHelper::SetConstantRate (DataRate dataRate, uint32_t packetSize = 512)
Helper function to set a constant rate source.
Equivalent to setting the attributes OnTime to constant 1000 seconds, OffTime to constant 0 seconds, and the DataRate and PacketSize set accordingly
Parameters
dataRate DataRate object for the sending rate
packetSize size in bytes of the packet payloads generated
Definition at line 70 of file satellite-on-off-helper.cc.
References m_factory.
Member Data Documentation
m_factory
ObjectFactory ns3::SatOnOffHelper::m_factory private
Object factory.
Definition at line 104 of file satellite-on-off-helper.h.
Referenced by SatOnOffHelper(), InstallPriv(), SetAttribute(), and SetConstantRate().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/helper/satellite-on-off-helper.h
/builds/sns3/satellite/satellite/helper/satellite-on-off-helper.cc