SNS3
ns3::SatCompositeSinrOutputTraceContainer Class Reference
Class for composite SINR output trace container.
#include "satellite-composite-sinr-output-trace-container.h"
Public Types
typedef std::map< key_t, Ptr< SatOutputFileStreamDoubleContainer > > container_t
typedef for map of containers
typedef std::pair< Address, SatEnums::ChannelType_t > key_t
typedef for map key
Public Member Functions
SatCompositeSinrOutputTraceContainer ()
Constructor.
~SatCompositeSinrOutputTraceContainer ()
Destructor.
void AddToContainer (key_t key, std::vector< double > newItem)
Add the vector containing the values to container matching the key.
void DoDispose ()
Do needed dispose actions.
void EnableFigureOutput (bool enableFigureOutput)
Function for enabling / disabling figure output.
TypeId GetInstanceTypeId (void) const
NS-3 instance type id function.
void Reset ()
Function for resetting the variables.
Public Member Functions inherited from ns3::SatBaseTraceContainer
SatBaseTraceContainer ()
Constructor.
virtual ~SatBaseTraceContainer ()
Destructor.
TypeId GetInstanceTypeId (void) const
NS-3 instance type id function.
Static Public Member Functions
static TypeId GetTypeId (void)
NS-3 type id function.
Static Public Member Functions inherited from ns3::SatBaseTraceContainer
static TypeId GetTypeId (void)
NS-3 type id function.
Private Member Functions
Ptr< SatOutputFileStreamDoubleContainer > AddNode (std::pair< Address, SatEnums::ChannelType_t > key)
Function for adding the node to the map.
Ptr< SatOutputFileStreamDoubleContainer > FindNode (key_t key)
Function for finding the container matching the key.
void WriteToFile ()
Write the contents of a container matching to the key into a file.
Private Attributes
container_t m_container
Map for containers.
bool m_enableFigureOutput
Switch for figure output.
Additional Inherited Members
Static Public Attributes inherited from ns3::SatBaseTraceContainer
static const uint32_t CSINR_TRACE_DEFAULT_FADING_VALUE_INDEX = 1
Default sinr value index for composite sinr traces.
static const uint32_t CSINR_TRACE_DEFAULT_NUMBER_OF_COLUMNS = 2
Default number of columns for composite sinr traces.
static const uint32_t FADING_TRACE_DEFAULT_FADING_VALUE_INDEX = 1
Default fading value index for fading traces.
static const uint32_t FADING_TRACE_DEFAULT_NUMBER_OF_COLUMNS = 2
Default number of columns for fading traces.
static const uint32_t INTF_TRACE_DEFAULT_INTF_DENSITY_INDEX = 1
Default interference density index for interference traces.
static const uint32_t INTF_TRACE_DEFAULT_NUMBER_OF_COLUMNS = 2
Default number of columns for interference traces.
static const uint32_t POSITION_TRACE_DEFAULT_ALTITUDE_INDEX = 3
Default altitude value index for positions traces.
static const uint32_t POSITION_TRACE_DEFAULT_LATITUDE_INDEX = 1
Default latitude value index for positions traces.
static const uint32_t POSITION_TRACE_DEFAULT_LONGITUDE_INDEX = 2
Default longitude value index for positions traces.
static const uint32_t POSITION_TRACE_DEFAULT_NUMBER_OF_COLUMNS = 4
Default number of columns for position traces.
static const uint32_t RX_CNO_TRACE_DEFAULT_NUMBER_OF_COLUMNS = 2
Default Rx power density index for Rx power traces.
static const uint32_t RX_CNO_TRACE_DEFAULT_RX_POWER_DENSITY_INDEX = 1
Default Rx power density index for Rx power traces.
static const uint32_t RX_POWER_TRACE_DEFAULT_NUMBER_OF_COLUMNS = 2
Default Rx C/N0 index for C/N0 traces.
static const uint32_t RX_POWER_TRACE_DEFAULT_RX_POWER_DENSITY_INDEX = 1
Default Rx C/N0 index for C/N0 traces.
Detailed Description
Class for composite SINR output trace container.
The class contains multiple fading output sample traces and provides an interface to them.
Definition at line 38 of file satellite-composite-sinr-output-trace-container.h.
Member Typedef Documentation
container_t
typedef std::map<key_t, Ptr<SatOutputFileStreamDoubleContainer> > ns3::SatCompositeSinrOutputTraceContainer::container_t
typedef for map of containers
Definition at line 49 of file satellite-composite-sinr-output-trace-container.h.
key_t
typedef std::pair<Address, SatEnums::ChannelType_t> ns3::SatCompositeSinrOutputTraceContainer::key_t
typedef for map key
Definition at line 44 of file satellite-composite-sinr-output-trace-container.h.
Constructor & Destructor Documentation
SatCompositeSinrOutputTraceContainer()
ns3::SatCompositeSinrOutputTraceContainer::SatCompositeSinrOutputTraceContainer ()
Constructor.
Definition at line 55 of file satellite-composite-sinr-output-trace-container.cc.
~SatCompositeSinrOutputTraceContainer()
ns3::SatCompositeSinrOutputTraceContainer::~SatCompositeSinrOutputTraceContainer ()
Destructor.
Definition at line 61 of file satellite-composite-sinr-output-trace-container.cc.
References Reset().
Member Function Documentation
AddNode()
Ptr< SatOutputFileStreamDoubleContainer > ns3::SatCompositeSinrOutputTraceContainer::AddNode (std::pair< Address, SatEnums::ChannelType_t > key) private
Function for adding the node to the map.
Parameters
key key
Returns
pointer to the added container
Definition at line 93 of file satellite-composite-sinr-output-trace-container.cc.
References ns3::SatBaseTraceContainer::CSINR_TRACE_DEFAULT_NUMBER_OF_COLUMNS, ns3::SatEnums::GetChannelTypeName(), and m_container.
Referenced by FindNode().
AddToContainer()
void ns3::SatCompositeSinrOutputTraceContainer::AddToContainer (key_t key, std::vector< double > newItem)
Add the vector containing the values to container matching the key.
Parameters
key key
newItem vector of values
Definition at line 178 of file satellite-composite-sinr-output-trace-container.cc.
References ns3::SatBaseTraceContainer::CSINR_TRACE_DEFAULT_NUMBER_OF_COLUMNS, and FindNode().
DoDispose()
void ns3::SatCompositeSinrOutputTraceContainer::DoDispose (void)
Do needed dispose actions.
Definition at line 69 of file satellite-composite-sinr-output-trace-container.cc.
References Reset().
EnableFigureOutput()
void ns3::SatCompositeSinrOutputTraceContainer::EnableFigureOutput (bool enableFigureOutput) inline
Function for enabling / disabling figure output.
Parameters
enableFigureOutput
Definition at line 89 of file satellite-composite-sinr-output-trace-container.h.
References m_enableFigureOutput.
FindNode()
Ptr< SatOutputFileStreamDoubleContainer > ns3::SatCompositeSinrOutputTraceContainer::FindNode (key_t key) private
Function for finding the container matching the key.
Parameters
key key
Returns
matching container
Definition at line 141 of file satellite-composite-sinr-output-trace-container.cc.
References AddNode(), and m_container.
Referenced by AddToContainer().
GetInstanceTypeId()
TypeId ns3::SatCompositeSinrOutputTraceContainer::GetInstanceTypeId (void) const
NS-3 instance type id function.
Returns
Instance type is
Definition at line 48 of file satellite-composite-sinr-output-trace-container.cc.
References GetTypeId().
GetTypeId()
TypeId ns3::SatCompositeSinrOutputTraceContainer::GetTypeId (void) static
NS-3 type id function.
Returns
type id
Definition at line 39 of file satellite-composite-sinr-output-trace-container.cc.
Referenced by GetInstanceTypeId().
Reset()
void ns3::SatCompositeSinrOutputTraceContainer::Reset () virtual
Function for resetting the variables.
Implements ns3::SatBaseTraceContainer.
Definition at line 79 of file satellite-composite-sinr-output-trace-container.cc.
References m_container, m_enableFigureOutput, and WriteToFile().
Referenced by ~SatCompositeSinrOutputTraceContainer(), and DoDispose().
WriteToFile()
void ns3::SatCompositeSinrOutputTraceContainer::WriteToFile () private
Write the contents of a container matching to the key into a file.
Definition at line 156 of file satellite-composite-sinr-output-trace-container.cc.
References ns3::SatOutputFileStreamDoubleContainer::DECIBEL, m_container, and m_enableFigureOutput.
Referenced by Reset().
Member Data Documentation
m_container
container_t ns3::SatCompositeSinrOutputTraceContainer::m_container private
Map for containers.
Definition at line 123 of file satellite-composite-sinr-output-trace-container.h.
Referenced by AddNode(), FindNode(), Reset(), and WriteToFile().
m_enableFigureOutput
bool ns3::SatCompositeSinrOutputTraceContainer::m_enableFigureOutput private
Switch for figure output.
Definition at line 128 of file satellite-composite-sinr-output-trace-container.h.
Referenced by EnableFigureOutput(), Reset(), and WriteToFile().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-composite-sinr-output-trace-container.h
/builds/sns3/satellite/satellite/model/satellite-composite-sinr-output-trace-container.cc