SNS3
ns3::LoraLogicalChannelHelper Class Reference
This class supports LorawanMac instances by managing a list of the logical channels that the device is supposed to be using, and establishes their relationship with LoraSubBands.
#include "lora-logical-channel-helper.h"
Public Member Functions
LoraLogicalChannelHelper ()
virtual ~LoraLogicalChannelHelper ()
void AddChannel (double frequency)
Add a new channel to the list.
void AddChannel (Ptr< LoraLogicalChannel > logicalChannel)
Add a new channel to the list.
void AddEvent (Time duration, Ptr< LoraLogicalChannel > channel)
Register the transmission of a packet.
void AddLoraSubBand (double firstFrequency, double lastFrequency, double dutyCycle, double maxTxPowerDbm)
Add a new LoraSubBand to this helper.
void AddLoraSubBand (Ptr< LoraSubBand > subBand)
Add a new LoraSubBand.
void DisableChannel (int index)
Disable the channel at a specified index.
Time GetAggregatedWaitingTime (void)
Get the time it is necessary to wait before transmitting again, according to the aggregate duty cycle timer.
std::vector< Ptr< LoraLogicalChannel > > GetChannelList (void)
Get the list of LoraLogicalChannels currently registered on this helper.
std::vector< Ptr< LoraLogicalChannel > > GetEnabledChannelList (void)
Get the list of LoraLogicalChannels currently registered on this helper that have been enabled for Uplink transmission with the channel mask.
Ptr< LoraSubBand > GetLoraSubBandFromChannel (Ptr< LoraLogicalChannel > channel)
Get the LoraSubBand a channel belongs to.
Ptr< LoraSubBand > GetLoraSubBandFromFrequency (double frequency)
Get the LoraSubBand a frequency belongs to.
double GetTxPowerForChannel (Ptr< LoraLogicalChannel > logicalChannel)
Returns the maximum transmission power [dBm] that is allowed on a channel.
Time GetWaitingTime (Ptr< LoraLogicalChannel > channel)
Get the time it is necessary to wait for before transmitting on a given channel.
void RemoveChannel (Ptr< LoraLogicalChannel > channel)
Remove a channel.
void SetChannel (uint8_t chIndex, Ptr< LoraLogicalChannel > logicalChannel)
Set a new channel at a fixed index.
Static Public Member Functions
static TypeId GetTypeId (void)
Private Attributes
double m_aggregatedDutyCycle
transmission will be possible according to the aggregated transmission timer
std::vector< Ptr< LoraLogicalChannel > > m_channelList
A vector of the LoraLogicalChannels that are currently registered within this helper.
Time m_nextAggregatedTransmissionTime
The next time at which.
std::list< Ptr< LoraSubBand > > m_subBandList
A list of the LoraSubBands that are currently registered within this helper.
Detailed Description
This class supports LorawanMac instances by managing a list of the logical channels that the device is supposed to be using, and establishes their relationship with LoraSubBands.
This class also takes into account duty cycle limitations, by updating a list of LoraSubBand objects and providing methods to query whether transmission on a set channel is admissible or not.
Definition at line 49 of file lora-logical-channel-helper.h.
Constructor & Destructor Documentation
LoraLogicalChannelHelper()
ns3::LoraLogicalChannelHelper::LoraLogicalChannelHelper ()
Definition at line 42 of file lora-logical-channel-helper.cc.
~LoraLogicalChannelHelper()
ns3::LoraLogicalChannelHelper::~LoraLogicalChannelHelper () virtual
Definition at line 49 of file lora-logical-channel-helper.cc.
Member Function Documentation
AddChannel() [1/2]
void ns3::LoraLogicalChannelHelper::AddChannel (double frequency)
Add a new channel to the list.
Parameters
frequency The frequency of the channel to create.
Definition at line 119 of file lora-logical-channel-helper.cc.
References m_channelList.
Referenced by ns3::LorawanMacEndDevice::AddLogicalChannel(), ns3::SatLoraConf::SetEu863_870Conf(), and ns3::SatLoraConf::SetSatelliteConf().
AddChannel() [2/2]
void ns3::LoraLogicalChannelHelper::AddChannel (Ptr< LoraLogicalChannel > logicalChannel)
Add a new channel to the list.
Parameters
logicalChannel A pointer to the channel to add to the list.
Definition at line 133 of file lora-logical-channel-helper.cc.
References m_channelList.
AddEvent()
void ns3::LoraLogicalChannelHelper::AddEvent (Time duration, Ptr< LoraLogicalChannel > channel)
Register the transmission of a packet.
Parameters
duration The duration of the transmission event.
channel The channel the transmission was made on.
Definition at line 220 of file lora-logical-channel-helper.cc.
References GetLoraSubBandFromChannel(), m_aggregatedDutyCycle, and m_nextAggregatedTransmissionTime.
Referenced by ns3::LorawanMacGateway::Send(), and ns3::LorawanMacEndDeviceClassA::SendToPhy().
AddLoraSubBand() [1/2]
void ns3::LoraLogicalChannelHelper::AddLoraSubBand (double firstFrequency, double lastFrequency, double dutyCycle, double maxTxPowerDbm)
Add a new LoraSubBand to this helper.
Parameters
firstFrequency The first frequency of the subband, in MHz.
lastFrequency The last frequency of the subband, in MHz.
dutyCycle The duty cycle that needs to be enforced on this subband.
maxTxPowerDbm The maximum transmission power [dBm] that can be used on this LoraSubBand.
Definition at line 151 of file lora-logical-channel-helper.cc.
References m_subBandList.
Referenced by ns3::LorawanMacEndDevice::AddLoraSubBand(), ns3::SatLoraConf::SetEu863_870Conf(), and ns3::SatLoraConf::SetSatelliteConf().
AddLoraSubBand() [2/2]
void ns3::LoraLogicalChannelHelper::AddLoraSubBand (Ptr< LoraSubBand > subBand)
Add a new LoraSubBand.
Parameters
subBand A pointer to the LoraSubBand that needs to be added.
Definition at line 165 of file lora-logical-channel-helper.cc.
References m_subBandList.
DisableChannel()
void ns3::LoraLogicalChannelHelper::DisableChannel (int index)
Disable the channel at a specified index.
Parameters
index The index of the channel to disable.
Definition at line 266 of file lora-logical-channel-helper.cc.
References m_channelList.
GetAggregatedWaitingTime()
Time ns3::LoraLogicalChannelHelper::GetAggregatedWaitingTime (void)
Get the time it is necessary to wait before transmitting again, according to the aggregate duty cycle timer.
Returns
The aggregate waiting time.
Definition at line 189 of file lora-logical-channel-helper.cc.
References m_nextAggregatedTransmissionTime.
GetChannelList()
std::vector< Ptr< LoraLogicalChannel > > ns3::LoraLogicalChannelHelper::GetChannelList (void)
Get the list of LoraLogicalChannels currently registered on this helper.
Returns
A list of the managed channels.
Definition at line 55 of file lora-logical-channel-helper.cc.
References m_channelList.
Referenced by ns3::LorawanMacEndDevice::OnLinkAdrReq().
GetEnabledChannelList()
std::vector< Ptr< LoraLogicalChannel > > ns3::LoraLogicalChannelHelper::GetEnabledChannelList (void)
Get the list of LoraLogicalChannels currently registered on this helper that have been enabled for Uplink transmission with the channel mask.
Returns
A list of the managed channels enabled for Uplink transmission.
Definition at line 68 of file lora-logical-channel-helper.cc.
References m_channelList.
Referenced by ns3::LorawanMacEndDevice::GetChannelForTx(), and ns3::LorawanMacEndDevice::GetNextTransmissionDelay().
GetLoraSubBandFromChannel()
Ptr< LoraSubBand > ns3::LoraLogicalChannelHelper::GetLoraSubBandFromChannel (Ptr< LoraLogicalChannel > channel)
Get the LoraSubBand a channel belongs to.
Parameters
channel The channel whose LoraSubBand we want to get.
Returns
The LoraSubBand the channel belongs to.
Definition at line 93 of file lora-logical-channel-helper.cc.
References GetLoraSubBandFromFrequency().
Referenced by AddEvent(), and GetWaitingTime().
GetLoraSubBandFromFrequency()
Ptr< LoraSubBand > ns3::LoraLogicalChannelHelper::GetLoraSubBandFromFrequency (double frequency)
Get the LoraSubBand a frequency belongs to.
Parameters
frequency The frequency we want to check.
Returns
The LoraSubBand the frequency belongs to.
Definition at line 99 of file lora-logical-channel-helper.cc.
References m_subBandList.
Referenced by GetLoraSubBandFromChannel().
GetTxPowerForChannel()
double ns3::LoraLogicalChannelHelper::GetTxPowerForChannel (Ptr< LoraLogicalChannel > logicalChannel)
Returns the maximum transmission power [dBm] that is allowed on a channel.
Parameters
logicalChannel The power for which to check the maximum allowed transmission power.
Returns
The power in dBm.
Definition at line 246 of file lora-logical-channel-helper.cc.
References m_subBandList.
Referenced by ns3::LorawanMacEndDevice::Send().
GetTypeId()
TypeId ns3::LoraLogicalChannelHelper::GetTypeId (void) static
Definition at line 36 of file lora-logical-channel-helper.cc.
GetWaitingTime()
Time ns3::LoraLogicalChannelHelper::GetWaitingTime (Ptr< LoraLogicalChannel > channel)
Get the time it is necessary to wait for before transmitting on a given channel.
Remarks
This function does not take into account aggregate waiting time. Check on this should be performed before calling this function.
Parameters
channel A pointer to the channel we want to know the waiting time for.
Returns
A Time instance containing the waiting time before transmission is allowed on the channel.
Definition at line 203 of file lora-logical-channel-helper.cc.
References GetLoraSubBandFromChannel().
Referenced by ns3::LorawanMacEndDevice::GetChannelForTx(), ns3::LorawanMacEndDevice::GetNextTransmissionDelay(), ns3::LorawanMacGateway::GetWaitingTime(), and ns3::LorawanMacGateway::Send().
RemoveChannel()
void ns3::LoraLogicalChannelHelper::RemoveChannel (Ptr< LoraLogicalChannel > channel)
Remove a channel.
Parameters
channel A pointer to the channel we want to remove.
Definition at line 173 of file lora-logical-channel-helper.cc.
References m_channelList.
SetChannel()
void ns3::LoraLogicalChannelHelper::SetChannel (uint8_t chIndex, Ptr< LoraLogicalChannel > logicalChannel)
Set a new channel at a fixed index.
Parameters
chIndex The index of the channel to substitute.
logicalChannel A pointer to the channel to add to the list.
Definition at line 142 of file lora-logical-channel-helper.cc.
References m_channelList.
Referenced by ns3::LorawanMacEndDevice::SetLogicalChannel().
Member Data Documentation
m_aggregatedDutyCycle
double ns3::LoraLogicalChannelHelper::m_aggregatedDutyCycle private
transmission will be possible according to the aggregated transmission timer
The next time at which transmission will be possible
Definition at line 202 of file lora-logical-channel-helper.h.
Referenced by AddEvent().
m_channelList
std::vector<Ptr<LoraLogicalChannel> > ns3::LoraLogicalChannelHelper::m_channelList private
A vector of the LoraLogicalChannels that are currently registered within this helper.
This vector represents the node's channel mask. The first N channels are the default ones for a fixed region.
Definition at line 195 of file lora-logical-channel-helper.h.
Referenced by AddChannel(), DisableChannel(), GetChannelList(), GetEnabledChannelList(), RemoveChannel(), and SetChannel().
m_nextAggregatedTransmissionTime
Time ns3::LoraLogicalChannelHelper::m_nextAggregatedTransmissionTime private
The next time at which.
Definition at line 197 of file lora-logical-channel-helper.h.
Referenced by AddEvent(), and GetAggregatedWaitingTime().
m_subBandList
std::list<Ptr<LoraSubBand> > ns3::LoraLogicalChannelHelper::m_subBandList private
A list of the LoraSubBands that are currently registered within this helper.
Definition at line 188 of file lora-logical-channel-helper.h.
Referenced by AddLoraSubBand(), GetLoraSubBandFromFrequency(), and GetTxPowerForChannel().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/lora-logical-channel-helper.h
/builds/sns3/satellite/satellite/model/lora-logical-channel-helper.cc