SNS3
ns3::SatDevLinkTimeTag Class Reference
Time tag used to identify the time when packet is enqueued at device level.
#include "satellite-time-tag.h"
Public Member Functions
SatDevLinkTimeTag ()
Default constructor.
SatDevLinkTimeTag (Time senderTimestamp)
Constructor with initialization parameters.
virtual void Deserialize (TagBuffer i)
Deserializes information from buffer to this instance of SatDevLinkTimeTag.
virtual TypeId GetInstanceTypeId (void) const
Get the type ID of instance.
Time GetSenderTimestamp (void) const
Get sender time stamp of this tag.
virtual uint32_t GetSerializedSize () const
Get serialized size of SatDevLinkTimeTag.
virtual void Print (std::ostream &os) const
Print time stamp of this instance of SatDevLinkTimeTag.
virtual void Serialize (TagBuffer i) const
Serializes information to buffer from this instance of SatDevLinkTimeTag.
void SetSenderTimestamp (Time senderTimestamp)
Set sender time stamp of this tag.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Time m_senderTimestamp
Detailed Description
Time tag used to identify the time when packet is enqueued at device level.
Definition at line 467 of file satellite-time-tag.h.
Constructor & Destructor Documentation
SatDevLinkTimeTag() [1/2]
ns3::SatDevLinkTimeTag::SatDevLinkTimeTag ()
Default constructor.
Definition at line 449 of file satellite-time-tag.cc.
SatDevLinkTimeTag() [2/2]
ns3::SatDevLinkTimeTag::SatDevLinkTimeTag (Time senderTimestamp)
Constructor with initialization parameters.
Parameters
senderTimestamp
Definition at line 455 of file satellite-time-tag.cc.
Member Function Documentation
Deserialize()
void ns3::SatDevLinkTimeTag::Deserialize (TagBuffer i) virtual
Deserializes information from buffer to this instance of SatDevLinkTimeTag.
Parameters
i Buffer from which the information is deserialized
Definition at line 489 of file satellite-time-tag.cc.
References m_senderTimestamp.
GetInstanceTypeId()
TypeId ns3::SatDevLinkTimeTag::GetInstanceTypeId (void) const virtual
Get the type ID of instance.
Returns
the object TypeId
Definition at line 470 of file satellite-time-tag.cc.
References GetTypeId().
GetSenderTimestamp()
Time ns3::SatDevLinkTimeTag::GetSenderTimestamp (void) const
Get sender time stamp of this tag.
Returns
Sender timestamp
Definition at line 503 of file satellite-time-tag.cc.
References m_senderTimestamp.
Referenced by ns3::SatNetDevice::Receive(), ns3::SatGeoNetDevice::ReceivePacketFeeder(), and ns3::SatGeoNetDevice::ReceivePacketUser().
GetSerializedSize()
uint32_t ns3::SatDevLinkTimeTag::GetSerializedSize (void) const virtual
Get serialized size of SatDevLinkTimeTag.
Returns
Serialized size in bytes
Definition at line 476 of file satellite-time-tag.cc.
GetTypeId()
TypeId ns3::SatDevLinkTimeTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 462 of file satellite-time-tag.cc.
Referenced by GetInstanceTypeId().
Print()
void ns3::SatDevLinkTimeTag::Print (std::ostream & os) const virtual
Print time stamp of this instance of SatDevLinkTimeTag.
Parameters
&os Output stream to which tag timestamp is printed.
Definition at line 497 of file satellite-time-tag.cc.
References m_senderTimestamp.
Serialize()
void ns3::SatDevLinkTimeTag::Serialize (TagBuffer i) const virtual
Serializes information to buffer from this instance of SatDevLinkTimeTag.
Parameters
i Buffer in which the information is serialized
Definition at line 482 of file satellite-time-tag.cc.
References m_senderTimestamp.
SetSenderTimestamp()
void ns3::SatDevLinkTimeTag::SetSenderTimestamp (Time senderTimestamp)
Set sender time stamp of this tag.
Parameters
senderTimestamp Sender time stamp
Definition at line 509 of file satellite-time-tag.cc.
References m_senderTimestamp.
Member Data Documentation
m_senderTimestamp
Time ns3::SatDevLinkTimeTag::m_senderTimestamp private
Definition at line 530 of file satellite-time-tag.h.
Referenced by Deserialize(), GetSenderTimestamp(), Print(), Serialize(), and SetSenderTimestamp().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-time-tag.h
/builds/sns3/satellite/satellite/model/satellite-time-tag.cc