SNS3
ns3::SatReturnLinkEncapsulator Class Reference
SatReturnLinkEncapsulator class is used in the RTN link for RLE encapsulation and fragmentation of higher layer packets.
#include "satellite-return-link-encapsulator.h"
Public Member Functions
SatReturnLinkEncapsulator ()
Default constructor, not used.
SatReturnLinkEncapsulator (Mac48Address encapAddress, Mac48Address decapAddress, Mac48Address sourceE2EAddress, Mac48Address destE2EAddress, uint8_t rcIndex, uint32_t additionalHeaderSize=0)
Constructor.
virtual ~SatReturnLinkEncapsulator ()
Destructor for SatReturnLinkEncapsulator.
virtual void DoDispose ()
Dispose of this class instance.
virtual void EnquePdu (Ptr< Packet > p, Mac48Address dest)
Enqueue a Higher Layer packet to txBuffer.
virtual uint32_t GetMinTxOpportunityInBytes () const
Get minimum Tx opportunity in bytes, which takes the assumed header sizes into account.
virtual Ptr< Packet > NotifyTxOpportunity (uint32_t bytes, uint32_t &bytesLeft, uint32_t &nextMinTxO)
Notify a Tx opportunity to this encapsulator.
virtual void ReceiveAck (Ptr< SatArqAckMessage > ack)
Receive a control msg (ARQ ACK)
virtual void ReceivePdu (Ptr< Packet > p)
Receive a packet, thus decapsulate and defragment/deconcatenate if needed.
Public Member Functions inherited from ns3::SatBaseEncapsulator
SatBaseEncapsulator ()
Default constructor not used.
SatBaseEncapsulator (Mac48Address encapAddress, Mac48Address decapAddress, Mac48Address sourceE2EAddress, Mac48Address destE2EAddress, uint8_t flowId, uint32_t additionalHeaderSize=0)
Constructor.
virtual ~SatBaseEncapsulator ()
Destructor for SatBaseEncapsulator.
virtual Time GetHolDelay () const
Get Head-of-Line packet buffering delay.
Ptr< SatQueue > GetQueue ()
Get the queue instance.
virtual uint32_t GetTxBufferSizeInBytes () const
Get the buffered packets for this encapsulator.
void SetCtrlMsgCallback (SatBaseEncapsulator::SendCtrlCallback cb)
void SetQueue (Ptr< SatQueue > queue)
Set the used queue from outside.
void SetReceiveCallback (ReceiveCallback cb)
Method to set receive callback.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::SatBaseEncapsulator
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
Ptr< Packet > GetNewRlePdu (uint32_t txOpportunityBytes, uint32_t maxRlePduSize, uint32_t additionalHeaderSize=0)
Get new packet performs the RLE fragmentation and encapsulation for a one single packet.
void IncreaseFragmentId ()
Method increases the fragment id by one.
virtual void ProcessPdu (Ptr< Packet > p)
Process the reception of individual RLE PDUs.
void Reset ()
Reset defragmentation variables.
Protected Attributes
uint32_t m_currRxFragmentId
Current fragment id in the reassembly process.
Ptr< Packet > m_currRxPacketFragment
Current packet in the reassembly process.
uint32_t m_currRxPacketFragmentBytes
Currently received bytes of the fragmented packet.
uint32_t m_currRxPacketSize
The total size of the ALPDU size reassembly process.
uint32_t m_minTxOpportunity
Minimum Tx opportunity.
uint32_t m_txFragmentId
Fragment id used in the packet transmissions.
const uint32_t MAX_FRAGMENT_ID
The fragment is described with 3 bits, thus the maximum fragment id is 8.
const uint32_t MAX_HL_PDU_PACKET_SIZE
The maximum packet size is described with 12 bits, thus, the maximum HL packet size is 4096 bytes.
const uint32_t MAX_PPDU_PACKET_SIZE
The maximum PPDU fragment size is described with 11 bits, thus, the maximum fragment size is 2048 bytes.
Protected Attributes inherited from ns3::SatBaseEncapsulator
uint32_t m_additionalHeaderSize
Additional value in to take into account when pulling packets to represent E2E tags.
SendCtrlCallback m_ctrlCallback
Callback to send control messages.
Mac48Address m_decapAddress
Mac48Address m_destE2EAddress
Mac48Address m_encapAddress
Source and destination mac addresses.
uint8_t m_flowId
Flow identifier.
ReceiveCallback m_rxCallback
Receive callback.
Mac48Address m_sourceE2EAddress
Ptr< SatQueue > m_txQueue
Used queue in satellite encapsulator.
Additional Inherited Members
Public Types inherited from ns3::SatBaseEncapsulator
typedef Callback< void, Ptr< Packet >, Mac48Address, Mac48Address > ReceiveCallback
Callback to send packet to lower layer.
typedef Callback< bool, Ptr< SatControlMessage >, const Address & > SendCtrlCallback
Control msg sending callback.
Detailed Description
SatReturnLinkEncapsulator class is used in the RTN link for RLE encapsulation and fragmentation of higher layer packets.
SatReturnLinkEncapsulator object is flow (UT address - flow id) specific and its entities are located at both UT (encapsulation, fragmentation) and GW (decapsulation, defragmentation). Return link encapsulators/decapsulators are created dynamically when first needed (when a packet is received for this flow).
See also
ETSI TS 103 179 V1.1.1 Satellite Earth Stations and Systems (SES); Return Link Encapsulation (RLE) protocol
Definition at line 48 of file satellite-return-link-encapsulator.h.
Constructor & Destructor Documentation
SatReturnLinkEncapsulator() [1/2]
ns3::SatReturnLinkEncapsulator::SatReturnLinkEncapsulator ()
Default constructor, not used.
Default constuctor is not meant to be used!
Definition at line 41 of file satellite-return-link-encapsulator.cc.
SatReturnLinkEncapsulator() [2/2]
ns3::SatReturnLinkEncapsulator::SatReturnLinkEncapsulator (Mac48Address encapAddress, Mac48Address decapAddress, Mac48Address sourceE2EAddress, Mac48Address destE2EAddress, uint8_t rcIndex, uint32_t additionalHeaderSize = 0)
Constructor.
Parameters
encapAddress MAC addressd of encapsulator
decapAddress MAC addressd of decapsulator
sourceE2EAddress E2E source MAC addressd of packets (used to set SatAddressE2ETag)
destE2EAddress E2E destination MAC addressd of packets (used to set SatAddressE2ETag)
rcIndex RC index
additionalHeaderSize Additional value in to take into account when pulling packets to represent E2E tags
Definition at line 59 of file satellite-return-link-encapsulator.cc.
References ns3::SatPPduHeader::GetMaxHeaderSizeInBytes(), and m_minTxOpportunity.
~SatReturnLinkEncapsulator()
ns3::SatReturnLinkEncapsulator::~SatReturnLinkEncapsulator () virtual
Destructor for SatReturnLinkEncapsulator.
Definition at line 86 of file satellite-return-link-encapsulator.cc.
Member Function Documentation
DoDispose()
void ns3::SatReturnLinkEncapsulator::DoDispose (void) virtual
Dispose of this class instance.
Reimplemented from ns3::SatBaseEncapsulator.
Reimplemented in ns3::SatReturnLinkEncapsulatorArq.
Definition at line 101 of file satellite-return-link-encapsulator.cc.
References ns3::SatBaseEncapsulator::DoDispose().
Referenced by ns3::SatReturnLinkEncapsulatorArq::DoDispose().
EnquePdu()
void ns3::SatReturnLinkEncapsulator::EnquePdu (Ptr< Packet > p, Mac48Address dest) virtual
Enqueue a Higher Layer packet to txBuffer.
Parameters
p To be buffered packet
dest Target MAC address
TODO: This is the place to encapsulate the higher layer packet with Addressed Link (AL) header, if needed.
Reimplemented from ns3::SatBaseEncapsulator.
Definition at line 109 of file satellite-return-link-encapsulator.cc.
References ns3::SatEncapPduStatusTag::FULL_PDU, ns3::SatBaseEncapsulator::m_decapAddress, ns3::SatBaseEncapsulator::m_encapAddress, ns3::SatBaseEncapsulator::m_txQueue, MAX_HL_PDU_PACKET_SIZE, ns3::SatMacTag::SetDestAddress(), ns3::SatMacTag::SetSourceAddress(), and ns3::SatEncapPduStatusTag::SetStatus().
GetMinTxOpportunityInBytes()
uint32_t ns3::SatReturnLinkEncapsulator::GetMinTxOpportunityInBytes () const virtual
Get minimum Tx opportunity in bytes, which takes the assumed header sizes into account.
Returns
Minimum Tx opportunity
Reimplemented from ns3::SatBaseEncapsulator.
Definition at line 533 of file satellite-return-link-encapsulator.cc.
References m_minTxOpportunity.
Referenced by ns3::SatReturnLinkEncapsulatorArq::NotifyTxOpportunity(), and NotifyTxOpportunity().
GetNewRlePdu()
Ptr< Packet > ns3::SatReturnLinkEncapsulator::GetNewRlePdu (uint32_t txOpportunityBytes, uint32_t maxRlePduSize, uint32_t additionalHeaderSize = 0) protected
Get new packet performs the RLE fragmentation and encapsulation for a one single packet.
Returns NULL packet if a suitable packet is not created.
Returns
A RLE packet
Definition at line 214 of file satellite-return-link-encapsulator.cc.
References ns3::SatEncapPduStatusTag::CONTINUATION_PDU, ns3::SatEncapPduStatusTag::END_PDU, ns3::SatEncapPduStatusTag::FULL_PDU, ns3::SatPPduHeader::GetHeaderSizeInBytes(), ns3::SatEncapPduStatusTag::GetStatus(), IncreaseFragmentId(), m_txFragmentId, ns3::SatBaseEncapsulator::m_txQueue, ns3::SatPPduHeader::SetEndIndicator(), ns3::SatPPduHeader::SetFragmentId(), ns3::SatPPduHeader::SetPPduLength(), ns3::SatPPduHeader::SetStartIndicator(), ns3::SatEncapPduStatusTag::SetStatus(), ns3::SatPPduHeader::SetTotalLength(), and ns3::SatEncapPduStatusTag::START_PDU.
Referenced by ns3::SatReturnLinkEncapsulatorArq::NotifyTxOpportunity(), and NotifyTxOpportunity().
GetTypeId()
TypeId ns3::SatReturnLinkEncapsulator::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 92 of file satellite-return-link-encapsulator.cc.
IncreaseFragmentId()
void ns3::SatReturnLinkEncapsulator::IncreaseFragmentId () protected
Method increases the fragment id by one.
If the maximum fragment id is reached, it is reset to zero.
Definition at line 510 of file satellite-return-link-encapsulator.cc.
References m_txFragmentId, and MAX_FRAGMENT_ID.
Referenced by GetNewRlePdu().
NotifyTxOpportunity()
Ptr< Packet > ns3::SatReturnLinkEncapsulator::NotifyTxOpportunity (uint32_t bytes, uint32_t & bytesLeft, uint32_t & nextMinTxO) virtual
Notify a Tx opportunity to this encapsulator.
Parameters
bytes Notified tx opportunity bytes from lower layer
bytesLeft Bytes left after this TxOpportunity in txBuffer
&nextMinTxO Minimum TxO after this TxO
Returns
Ptr<Packet> a Frame PDU
Reimplemented from ns3::SatBaseEncapsulator.
Reimplemented in ns3::SatReturnLinkEncapsulatorArq.
Definition at line 147 of file satellite-return-link-encapsulator.cc.
References GetMinTxOpportunityInBytes(), GetNewRlePdu(), ns3::SatBaseEncapsulator::GetTxBufferSizeInBytes(), ns3::SatBaseEncapsulator::m_additionalHeaderSize, ns3::SatBaseEncapsulator::m_decapAddress, ns3::SatBaseEncapsulator::m_destE2EAddress, ns3::SatBaseEncapsulator::m_encapAddress, ns3::SatBaseEncapsulator::m_flowId, ns3::SatBaseEncapsulator::m_sourceE2EAddress, ns3::SatBaseEncapsulator::m_txQueue, MAX_PPDU_PACKET_SIZE, ns3::SatMacTag::SetDestAddress(), ns3::SatAddressE2ETag::SetE2EDestAddress(), ns3::SatAddressE2ETag::SetE2ESourceAddress(), ns3::SatFlowIdTag::SetFlowId(), and ns3::SatMacTag::SetSourceAddress().
ProcessPdu()
void ns3::SatReturnLinkEncapsulator::ProcessPdu (Ptr< Packet > p) protected virtual
Process the reception of individual RLE PDUs.
Parameters
p Packet to be received
Definition at line 414 of file satellite-return-link-encapsulator.cc.
References ns3::SatPPduHeader::GetEndIndicator(), ns3::SatPPduHeader::GetFragmentId(), ns3::SatPPduHeader::GetPPduLength(), ns3::SatPPduHeader::GetStartIndicator(), ns3::SatPPduHeader::GetTotalLength(), m_currRxFragmentId, m_currRxPacketFragment, m_currRxPacketFragmentBytes, m_currRxPacketSize, ns3::SatBaseEncapsulator::m_decapAddress, ns3::SatBaseEncapsulator::m_encapAddress, ns3::SatBaseEncapsulator::m_rxCallback, and Reset().
Referenced by ns3::SatReturnLinkEncapsulatorArq::ReassembleAndReceive(), and ReceivePdu().
ReceiveAck()
void ns3::SatReturnLinkEncapsulator::ReceiveAck (Ptr< SatArqAckMessage > ack) virtual
Receive a control msg (ARQ ACK)
Parameters
ack ACK control message pointer received from lower layer
The base encapsulator should not be used at receiving control packets at all! This functionality is implemented in the inherited classes.
Reimplemented from ns3::SatBaseEncapsulator.
Reimplemented in ns3::SatReturnLinkEncapsulatorArq.
Definition at line 498 of file satellite-return-link-encapsulator.cc.
ReceivePdu()
void ns3::SatReturnLinkEncapsulator::ReceivePdu (Ptr< Packet > p) virtual
Receive a packet, thus decapsulate and defragment/deconcatenate if needed.
The decapsulated/defragmented HL PDU is forwarded back to LLC and to upper layer.
Parameters
p packet pointer received from lower layer
Reimplemented from ns3::SatBaseEncapsulator.
Reimplemented in ns3::SatReturnLinkEncapsulatorArq.
Definition at line 385 of file satellite-return-link-encapsulator.cc.
References ns3::SatMacTag::GetDestAddress(), ns3::SatBaseEncapsulator::m_decapAddress, and ProcessPdu().
Reset()
void ns3::SatReturnLinkEncapsulator::Reset (void) protected
Reset defragmentation variables.
Definition at line 522 of file satellite-return-link-encapsulator.cc.
References m_currRxFragmentId, m_currRxPacketFragment, m_currRxPacketFragmentBytes, and m_currRxPacketSize.
Referenced by ProcessPdu().
Member Data Documentation
m_currRxFragmentId
uint32_t ns3::SatReturnLinkEncapsulator::m_currRxFragmentId protected
Current fragment id in the reassembly process.
Definition at line 163 of file satellite-return-link-encapsulator.h.
Referenced by ProcessPdu(), and Reset().
m_currRxPacketFragment
Ptr<Packet> ns3::SatReturnLinkEncapsulator::m_currRxPacketFragment protected
Current packet in the reassembly process.
Definition at line 168 of file satellite-return-link-encapsulator.h.
Referenced by ProcessPdu(), and Reset().
m_currRxPacketFragmentBytes
uint32_t ns3::SatReturnLinkEncapsulator::m_currRxPacketFragmentBytes protected
Currently received bytes of the fragmented packet.
Definition at line 178 of file satellite-return-link-encapsulator.h.
Referenced by ProcessPdu(), and Reset().
m_currRxPacketSize
uint32_t ns3::SatReturnLinkEncapsulator::m_currRxPacketSize protected
The total size of the ALPDU size reassembly process.
Definition at line 173 of file satellite-return-link-encapsulator.h.
Referenced by ProcessPdu(), and Reset().
m_minTxOpportunity
uint32_t ns3::SatReturnLinkEncapsulator::m_minTxOpportunity protected
Minimum Tx opportunity.
Definition at line 183 of file satellite-return-link-encapsulator.h.
Referenced by SatReturnLinkEncapsulator(), and GetMinTxOpportunityInBytes().
m_txFragmentId
uint32_t ns3::SatReturnLinkEncapsulator::m_txFragmentId protected
Fragment id used in the packet transmissions.
Definition at line 159 of file satellite-return-link-encapsulator.h.
Referenced by GetNewRlePdu(), and IncreaseFragmentId().
MAX_FRAGMENT_ID
const uint32_t ns3::SatReturnLinkEncapsulator::MAX_FRAGMENT_ID protected
The fragment is described with 3 bits, thus the maximum fragment id is 8.
Definition at line 189 of file satellite-return-link-encapsulator.h.
Referenced by IncreaseFragmentId().
MAX_HL_PDU_PACKET_SIZE
const uint32_t ns3::SatReturnLinkEncapsulator::MAX_HL_PDU_PACKET_SIZE protected
The maximum packet size is described with 12 bits, thus, the maximum HL packet size is 4096 bytes.
Definition at line 201 of file satellite-return-link-encapsulator.h.
Referenced by EnquePdu().
MAX_PPDU_PACKET_SIZE
const uint32_t ns3::SatReturnLinkEncapsulator::MAX_PPDU_PACKET_SIZE protected
The maximum PPDU fragment size is described with 11 bits, thus, the maximum fragment size is 2048 bytes.
Definition at line 195 of file satellite-return-link-encapsulator.h.
Referenced by NotifyTxOpportunity().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-return-link-encapsulator.h
/builds/sns3/satellite/satellite/model/satellite-return-link-encapsulator.cc