SNS3
ns3::SatStatsRbdcRequestHelper Class Reference
Satellite Statistics
Base class for RBDC requests statistics helpers.
#include "satellite-stats-rbdc-request-helper.h"
Public Member Functions
SatStatsRbdcRequestHelper (Ptr< const SatHelper > satHelper)
virtual ~SatStatsRbdcRequestHelper ()
/ Destructor.
bool GetAveragingMode () const
void InstallProbes ()
Set up several probes or other means of listeners and connect them to the collectors.
void RbdcRateCallback (std::string identifier, uint32_t rbdcTraceKbps)
Receive inputs from trace sources.
void SetAveragingMode (bool averagingMode)
Public Member Functions inherited from ns3::SatStatsHelper
SatStatsHelper (Ptr< const SatHelper > satHelper)
Creates a new helper instance.
virtual ~SatStatsHelper ()
/ Destructor.
IdentifierType_t GetIdentifierType () const
std::string GetName () const
OutputType_t GetOutputType () const
Ptr< const SatHelper > GetSatHelper () const
void Install ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
bool IsInstalled () const
void SetIdentifierType (IdentifierType_t identifierType)
void SetName (std::string name)
void SetOutputType (OutputType_t outputType)
Static Public Member Functions
static TypeId GetTypeId ()
inherited from ObjectBase base class
Static Public Member Functions inherited from ns3::SatStatsHelper
static std::string GetIdentifierTypeName (IdentifierType_t identifierType)
static std::string GetOutputTypeName (OutputType_t outputType)
static TypeId GetTypeId ()
inherited from ObjectBase base class
Protected Member Functions
void DoInstall ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
Protected Member Functions inherited from ns3::SatStatsHelper
Ptr< DataCollectionObject > CreateAggregator (std::string aggregatorTypeId, std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue())
Create the aggregator according to the output type.
uint32_t CreateCollectorPerIdentifier (CollectorMap &collectorMap) const
Create one collector instance for each identifier in the simulation.
virtual std::string GetDistributionHeading (std::string dataLabel) const
uint32_t GetGwId (Ptr< Node > gwNode) const
uint32_t GetIdentifierForBeam (uint32_t satId, uint32_t beamId) const
uint32_t GetIdentifierForGroup (uint32_t groupId) const
uint32_t GetIdentifierForGw (Ptr< Node > gwNode) const
uint32_t GetIdentifierForIsl (Ptr< Node > satNodeSrc, Ptr< Node > satNodeDst) const
uint32_t GetIdentifierForSat (Ptr< Node > satNode) const
uint32_t GetIdentifierForUt (Ptr< Node > utNode) const
uint32_t GetIdentifierForUtUser (Ptr< Node > utUserNode) const
virtual std::string GetIdentifierHeading (std::string dataLabel) const
virtual std::string GetOutputFileName () const
Compute the path and file name where statistics output should be written to.
virtual std::string GetOutputPath () const
uint32_t GetSatId (Ptr< Node > satNode) const
virtual std::string GetTimeHeading (std::string dataLabel) const
uint32_t GetUtId (Ptr< Node > utNode) const
uint32_t GetUtUserId (Ptr< Node > utUserNode) const
Protected Attributes
Ptr< DataCollectionObject > m_aggregator
The aggregator created by this helper.
Ptr< DistributionCollector > m_averagingCollector
The final collector utilized in averaged output (histogram, PDF, and CDF).
CollectorMap m_terminalCollectors
Maintains a list of collectors created by this helper.
Private Attributes
bool m_averagingMode
AveragingMode attribute.
Additional Inherited Members
Public Types inherited from ns3::SatStatsHelper
enum IdentifierType_t {
IDENTIFIER_GLOBAL = 0 , IDENTIFIER_GW , IDENTIFIER_BEAM , IDENTIFIER_UT ,
IDENTIFIER_UT_USER , IDENTIFIER_SLICE , IDENTIFIER_GROUP , IDENTIFIER_SAT ,
IDENTIFIER_ISL
}
Possible categorization of statistics output.
enum OutputType_t {
OUTPUT_NONE = 0 , OUTPUT_SCALAR_FILE , OUTPUT_SCATTER_FILE , OUTPUT_HISTOGRAM_FILE ,
OUTPUT_PDF_FILE , OUTPUT_CDF_FILE , OUTPUT_SCALAR_PLOT , OUTPUT_SCATTER_PLOT ,
OUTPUT_HISTOGRAM_PLOT , OUTPUT_PDF_PLOT , OUTPUT_CDF_PLOT
}
Possible types and formats of statistics output.
Static Protected Member Functions inherited from ns3::SatStatsHelper
static NetDeviceContainer GetGwSatNetDevice (Ptr< Node > gwNode)
static Ptr< NetDevice > GetSatSatGeoNetDevice (Ptr< Node > satNode)
static Ptr< NetDevice > GetUtSatNetDevice (Ptr< Node > utNode)
Detailed Description
Base class for RBDC requests statistics helpers.
Definition at line 45 of file satellite-stats-rbdc-request-helper.h.
Constructor & Destructor Documentation
SatStatsRbdcRequestHelper()
ns3::SatStatsRbdcRequestHelper::SatStatsRbdcRequestHelper (Ptr< const SatHelper > satHelper)
Definition at line 51 of file satellite-stats-rbdc-request-helper.cc.
~SatStatsRbdcRequestHelper()
ns3::SatStatsRbdcRequestHelper::~SatStatsRbdcRequestHelper () virtual
/ Destructor.
Definition at line 58 of file satellite-stats-rbdc-request-helper.cc.
Member Function Documentation
DoInstall()
void ns3::SatStatsRbdcRequestHelper::DoInstall () protected virtual
Install the probes, collectors, and aggregators necessary to produce the statistics output.
An abstract method of SatStatsHelper which must be implemented by child classes. It will be invoked by Install().
Todo:
Add support for boxes in Gnuplot.
Todo:
Find a better dataset name.
Todo:
Find a better dataset name.
Implements ns3::SatStatsHelper.
Definition at line 152 of file satellite-stats-rbdc-request-helper.cc.
References ns3::SatStatsHelper::CreateAggregator(), ns3::SatStatsHelper::CreateCollectorPerIdentifier(), ns3::SatStatsHelper::GetDistributionHeading(), ns3::SatStatsHelper::GetIdentifierHeading(), ns3::SatStatsHelper::GetName(), ns3::SatStatsHelper::GetOutputFileName(), ns3::SatStatsHelper::GetOutputPath(), ns3::SatStatsHelper::GetOutputType(), ns3::SatStatsHelper::GetOutputTypeName(), ns3::SatStatsHelper::GetTimeHeading(), InstallProbes(), m_aggregator, m_averagingCollector, m_averagingMode, m_terminalCollectors, ns3::SatStatsHelper::OUTPUT_CDF_FILE, ns3::SatStatsHelper::OUTPUT_CDF_PLOT, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_FILE, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_PLOT, ns3::SatStatsHelper::OUTPUT_NONE, ns3::SatStatsHelper::OUTPUT_PDF_FILE, ns3::SatStatsHelper::OUTPUT_PDF_PLOT, ns3::SatStatsHelper::OUTPUT_SCALAR_FILE, ns3::SatStatsHelper::OUTPUT_SCALAR_PLOT, ns3::SatStatsHelper::OUTPUT_SCATTER_FILE, and ns3::SatStatsHelper::OUTPUT_SCATTER_PLOT.
GetAveragingMode()
bool ns3::SatStatsRbdcRequestHelper::GetAveragingMode () const
Returns
the currently active averaging mode.
Definition at line 87 of file satellite-stats-rbdc-request-helper.cc.
References m_averagingMode.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::SatStatsRbdcRequestHelper::GetTypeId (void) static
inherited from ObjectBase base class
Definition at line 64 of file satellite-stats-rbdc-request-helper.cc.
References GetAveragingMode(), and SetAveragingMode().
InstallProbes()
void ns3::SatStatsRbdcRequestHelper::InstallProbes ()
Set up several probes or other means of listeners and connect them to the collectors.
Definition at line 457 of file satellite-stats-rbdc-request-helper.cc.
References ns3::SatStatsHelper::GetIdentifierForUt(), ns3::SatStatsHelper::GetIdentifierType(), ns3::SatStatsHelper::GetSatHelper(), ns3::SatStatsHelper::GetUtSatNetDevice(), ns3::SatStatsHelper::IDENTIFIER_BEAM, ns3::SatStatsHelper::IDENTIFIER_GLOBAL, ns3::SatStatsHelper::IDENTIFIER_GW, ns3::SatStatsHelper::IDENTIFIER_UT, and RbdcRateCallback().
Referenced by DoInstall().
RbdcRateCallback()
void ns3::SatStatsRbdcRequestHelper::RbdcRateCallback (std::string identifier, uint32_t rbdcTraceKbps)
Receive inputs from trace sources.
Parameters
identifier the source ID as a context string.
rbdcTraceKbps the requested RBDC capacity collected.
Definition at line 94 of file satellite-stats-rbdc-request-helper.cc.
References ns3::SatStatsHelper::GetOutputType(), ns3::SatStatsHelper::GetOutputTypeName(), m_averagingMode, m_terminalCollectors, ns3::SatStatsHelper::OUTPUT_CDF_FILE, ns3::SatStatsHelper::OUTPUT_CDF_PLOT, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_FILE, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_PLOT, ns3::SatStatsHelper::OUTPUT_PDF_FILE, ns3::SatStatsHelper::OUTPUT_PDF_PLOT, ns3::SatStatsHelper::OUTPUT_SCALAR_FILE, ns3::SatStatsHelper::OUTPUT_SCALAR_PLOT, ns3::SatStatsHelper::OUTPUT_SCATTER_FILE, and ns3::SatStatsHelper::OUTPUT_SCATTER_PLOT.
Referenced by InstallProbes().
SetAveragingMode()
void ns3::SatStatsRbdcRequestHelper::SetAveragingMode (bool averagingMode)
Parameters
averagingMode average all samples before passing them to aggregator.
Definition at line 80 of file satellite-stats-rbdc-request-helper.cc.
References m_averagingMode.
Referenced by GetTypeId().
Member Data Documentation
m_aggregator
Ptr<DataCollectionObject> ns3::SatStatsRbdcRequestHelper::m_aggregator protected
The aggregator created by this helper.
Definition at line 95 of file satellite-stats-rbdc-request-helper.h.
Referenced by DoInstall().
m_averagingCollector
Ptr<DistributionCollector> ns3::SatStatsRbdcRequestHelper::m_averagingCollector protected
The final collector utilized in averaged output (histogram, PDF, and CDF).
Definition at line 92 of file satellite-stats-rbdc-request-helper.h.
Referenced by DoInstall().
m_averagingMode
bool ns3::SatStatsRbdcRequestHelper::m_averagingMode private
AveragingMode attribute.
Definition at line 98 of file satellite-stats-rbdc-request-helper.h.
Referenced by DoInstall(), GetAveragingMode(), RbdcRateCallback(), and SetAveragingMode().
m_terminalCollectors
CollectorMap ns3::SatStatsRbdcRequestHelper::m_terminalCollectors protected
Maintains a list of collectors created by this helper.
Definition at line 89 of file satellite-stats-rbdc-request-helper.h.
Referenced by DoInstall(), and RbdcRateCallback().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/stats/satellite-stats-rbdc-request-helper.h
/builds/sns3/satellite/satellite/stats/satellite-stats-rbdc-request-helper.cc