SNS3
ns3::SatOnOffApplication Class Reference
This class implements Satellite specific OnOff application.
#include "satellite-on-off-application.h"
Public Member Functions
SatOnOffApplication ()
Constructor for Satellite specific on-off application.
virtual ~SatOnOffApplication ()
Destructor Satellite specific on-off application.
void EnableStatisticTags (bool enableStatus)
Enable or disable statistic tags.
bool IsStatisticTagsEnabled () const
Get enable status of statistic tags.
void SendPacketTrace (Ptr< const Packet > packet)
Trace callback for on-off application Tx.
Static Public Member Functions
static TypeId GetTypeId (void)
Private Attributes
bool m_isConnectedWithTraceSource
bool m_isStatisticsTagsEnabled
EnableStatisticsTags attribute.
Detailed Description
This class implements Satellite specific OnOff application.
It subclasses ns-3 'native' OnOffApplication to provide needed support for statics. Otherwise functionality of original OnOffApplication is not changed.
Definition at line 38 of file satellite-on-off-application.h.
Constructor & Destructor Documentation
SatOnOffApplication()
ns3::SatOnOffApplication::SatOnOffApplication ()
Constructor for Satellite specific on-off application.
Definition at line 54 of file satellite-on-off-application.cc.
~SatOnOffApplication()
ns3::SatOnOffApplication::~SatOnOffApplication () virtual
Destructor Satellite specific on-off application.
Definition at line 61 of file satellite-on-off-application.cc.
Member Function Documentation
EnableStatisticTags()
void ns3::SatOnOffApplication::EnableStatisticTags (bool enableStatus)
Enable or disable statistic tags.
Parameters
enableStatus Enable status for statistics
Definition at line 67 of file satellite-on-off-application.cc.
References m_isConnectedWithTraceSource, m_isStatisticsTagsEnabled, and SendPacketTrace().
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::SatOnOffApplication::GetTypeId (void) static
Definition at line 38 of file satellite-on-off-application.cc.
References EnableStatisticTags(), and IsStatisticTagsEnabled().
IsStatisticTagsEnabled()
bool ns3::SatOnOffApplication::IsStatisticTagsEnabled () const
Get enable status of statistic tags.
Returns
true if statistics are enabled, false if statistics are disabled
Definition at line 95 of file satellite-on-off-application.cc.
References m_isStatisticsTagsEnabled.
Referenced by GetTypeId().
SendPacketTrace()
void ns3::SatOnOffApplication::SendPacketTrace (Ptr< const Packet > packet)
Trace callback for on-off application Tx.
Parameters
packet Packet send by on-off application.
Definition at line 101 of file satellite-on-off-application.cc.
Referenced by EnableStatisticTags().
Member Data Documentation
m_isConnectedWithTraceSource
bool ns3::SatOnOffApplication::m_isConnectedWithTraceSource private
Definition at line 78 of file satellite-on-off-application.h.
Referenced by EnableStatisticTags().
m_isStatisticsTagsEnabled
bool ns3::SatOnOffApplication::m_isStatisticsTagsEnabled private
EnableStatisticsTags attribute.
Definition at line 77 of file satellite-on-off-application.h.
Referenced by EnableStatisticTags(), and IsStatisticTagsEnabled().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-on-off-application.h
/builds/sns3/satellite/satellite/model/satellite-on-off-application.cc