SNS3
ns3::SatPerfectInterferenceElimination Class Reference
Satellite perfect interference elimination.
#include "satellite-perfect-interference-elimination.h"
Public Member Functions
SatPerfectInterferenceElimination ()
Default constructor.
~SatPerfectInterferenceElimination ()
Destructor.
void EliminateInterferences (Ptr< SatSignalParameters > packetInterferedWith, Ptr< SatSignalParameters > processedPacket, double EsNo, bool isRegenerative)
Calculate residual power of interference for the given packets.
void EliminateInterferences (Ptr< SatSignalParameters > packetInterferedWith, Ptr< SatSignalParameters > processedPacket, double EsNo, bool isRegenerative, double startTime, double endTime)
Calculate residual power of interference for the given packets.
TypeId GetInstanceTypeId (void) const
Derived from Object.
double GetResidualPower (Ptr< SatSignalParameters > processedPacket, double EsNo)
Calculate the residual power of interference for a given packet.
Public Member Functions inherited from ns3::SatInterferenceElimination
SatInterferenceElimination ()
Constructor for Satellite interference elimination base class.
virtual ~SatInterferenceElimination ()
Destructor for Satellite interference elimination base class.
TypeId GetInstanceTypeId (void) const
Derived from Object.
Static Public Member Functions
static TypeId GetTypeId (void)
Derived from Object.
Static Public Member Functions inherited from ns3::SatInterferenceElimination
static TypeId GetTypeId (void)
Derived from Object.
Detailed Description
Satellite perfect interference elimination.
Interference values are removed without residual power.
Definition at line 35 of file satellite-perfect-interference-elimination.h.
Constructor & Destructor Documentation
SatPerfectInterferenceElimination()
ns3::SatPerfectInterferenceElimination::SatPerfectInterferenceElimination ()
Default constructor.
Definition at line 51 of file satellite-perfect-interference-elimination.cc.
~SatPerfectInterferenceElimination()
ns3::SatPerfectInterferenceElimination::~SatPerfectInterferenceElimination ()
Destructor.
Definition at line 56 of file satellite-perfect-interference-elimination.cc.
Member Function Documentation
EliminateInterferences() [1/2]
void ns3::SatPerfectInterferenceElimination::EliminateInterferences (Ptr< SatSignalParameters > packetInterferedWith, Ptr< SatSignalParameters > processedPacket, double EsNo, bool isRegenerative) virtual
Calculate residual power of interference for the given packets.
Parameters
packetInterferedWith Parameters of the packet whose interference level should be lowered
processedPacket Parameters of the packet we want to remove interference from
isRegenerative Tell if we are in regenerative configuration. Depending on this value, the computations are made on the GW or on the satellite
Implements ns3::SatInterferenceElimination.
Definition at line 62 of file satellite-perfect-interference-elimination.cc.
EliminateInterferences() [2/2]
void ns3::SatPerfectInterferenceElimination::EliminateInterferences (Ptr< SatSignalParameters > packetInterferedWith, Ptr< SatSignalParameters > processedPacket, double EsNo, bool isRegenerative, double startTime, double endTime) virtual
Calculate residual power of interference for the given packets.
Parameters
packetInterferedWith Parameters of the packet whose interference level should be lowered
processedPacket Parameters of the packet we want to remove interference from
isRegenerative Tell if we are in regenerative configuration. Depending on this value, the computations are made on the GW or on the satellite
startTime Normalized start time of the interference, with respect to packetInterferedWith
endTime Normalized end time of the interference, with respect to packetInterferedWith
Implements ns3::SatInterferenceElimination.
Definition at line 79 of file satellite-perfect-interference-elimination.cc.
References ns3::SatUtils::ScalarProduct().
GetInstanceTypeId()
TypeId ns3::SatPerfectInterferenceElimination::GetInstanceTypeId (void) const
Derived from Object.
Definition at line 46 of file satellite-perfect-interference-elimination.cc.
References GetTypeId().
GetResidualPower()
double ns3::SatPerfectInterferenceElimination::GetResidualPower (Ptr< SatSignalParameters > processedPacket, double EsNo) virtual
Calculate the residual power of interference for a given packet.
Implements ns3::SatInterferenceElimination.
Definition at line 146 of file satellite-perfect-interference-elimination.cc.
GetTypeId()
TypeId ns3::SatPerfectInterferenceElimination::GetTypeId (void) static
Derived from Object.
Definition at line 36 of file satellite-perfect-interference-elimination.cc.
Referenced by GetInstanceTypeId().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-perfect-interference-elimination.h
/builds/sns3/satellite/satellite/model/satellite-perfect-interference-elimination.cc