SNS3
ns3::SatLinkResultsPlot Class Reference
Example for plotting satellite link results data.
Public Member Functions
SatLinkResultsPlot ()
Creates an empty instance.
void Run ()
Load link results data files and generate plots from them.
Private Member Functions
Gnuplot GetGnuplot (std::string outputName, std::string title)
Gnuplot2dDataset GetGnuplotDataset (Ptr< SatLookUpTable > table, std::string title)
void RunDvbRcs2Psk8 ()
void RunDvbRcs2Qam16 ()
void RunDvbRcs2Qpsk ()
void RunDvbS2Apsk16 ()
void RunDvbS2Apsk32 ()
void RunDvbS2Psk8 ()
void RunDvbS2Qpsk ()
Private Attributes
std::string m_inputPath
double m_maxSinrDb
double m_minSinrDb
double m_resolutionDb
Detailed Description
Example for plotting satellite link results data.
This example can be run as it is, without any argument, i.e.:
$ ./waf --run="link-results-plot"
Several Gnuplot files (.plt) will be generated as output. Each of these files can be converted to a PNG file, for example by this command:
$ gnuplot s2-32apsk.plt
which will produce s2-32apsk.png file in the same directory. To convert all the Gnuplot files in the directory, the command below can be used:
$ gnuplot *.plt
Definition at line 61 of file sat-link-results-plot.cc.
Constructor & Destructor Documentation
SatLinkResultsPlot()
ns3::SatLinkResultsPlot::SatLinkResultsPlot ()
Creates an empty instance.
Definition at line 88 of file sat-link-results-plot.cc.
References m_inputPath, m_maxSinrDb, m_minSinrDb, and m_resolutionDb.
Member Function Documentation
GetGnuplot()
Gnuplot ns3::SatLinkResultsPlot::GetGnuplot (std::string outputName, std::string title) private
Definition at line 414 of file sat-link-results-plot.cc.
Referenced by RunDvbRcs2Psk8(), RunDvbRcs2Qam16(), RunDvbRcs2Qpsk(), RunDvbS2Apsk16(), RunDvbS2Apsk32(), RunDvbS2Psk8(), and RunDvbS2Qpsk().
GetGnuplotDataset()
Gnuplot2dDataset ns3::SatLinkResultsPlot::GetGnuplotDataset (Ptr< SatLookUpTable > table, std::string title) private
Definition at line 370 of file sat-link-results-plot.cc.
References m_maxSinrDb, m_minSinrDb, and m_resolutionDb.
Referenced by RunDvbRcs2Psk8(), RunDvbRcs2Qam16(), RunDvbRcs2Qpsk(), RunDvbS2Apsk16(), RunDvbS2Apsk32(), RunDvbS2Psk8(), and RunDvbS2Qpsk().
Run()
void ns3::SatLinkResultsPlot::Run ()
Load link results data files and generate plots from them.
Definition at line 97 of file sat-link-results-plot.cc.
References RunDvbRcs2Psk8(), RunDvbRcs2Qam16(), RunDvbRcs2Qpsk(), RunDvbS2Apsk16(), RunDvbS2Apsk32(), RunDvbS2Psk8(), and RunDvbS2Qpsk().
RunDvbRcs2Psk8()
void ns3::SatLinkResultsPlot::RunDvbRcs2Psk8 () private
Definition at line 163 of file sat-link-results-plot.cc.
References GetGnuplot(), GetGnuplotDataset(), and m_inputPath.
Referenced by Run().
RunDvbRcs2Qam16()
void ns3::SatLinkResultsPlot::RunDvbRcs2Qam16 () private
Definition at line 201 of file sat-link-results-plot.cc.
References GetGnuplot(), GetGnuplotDataset(), and m_inputPath.
Referenced by Run().
RunDvbRcs2Qpsk()
void ns3::SatLinkResultsPlot::RunDvbRcs2Qpsk () private
Definition at line 109 of file sat-link-results-plot.cc.
References GetGnuplot(), GetGnuplotDataset(), and m_inputPath.
Referenced by Run().
RunDvbS2Apsk16()
void ns3::SatLinkResultsPlot::RunDvbS2Apsk16 () private
Definition at line 307 of file sat-link-results-plot.cc.
References GetGnuplot(), GetGnuplotDataset(), and m_inputPath.
Referenced by Run().
RunDvbS2Apsk32()
void ns3::SatLinkResultsPlot::RunDvbS2Apsk32 () private
Definition at line 342 of file sat-link-results-plot.cc.
References GetGnuplot(), GetGnuplotDataset(), and m_inputPath.
Referenced by Run().
RunDvbS2Psk8()
void ns3::SatLinkResultsPlot::RunDvbS2Psk8 () private
Definition at line 273 of file sat-link-results-plot.cc.
References GetGnuplot(), GetGnuplotDataset(), and m_inputPath.
Referenced by Run().
RunDvbS2Qpsk()
void ns3::SatLinkResultsPlot::RunDvbS2Qpsk () private
Definition at line 233 of file sat-link-results-plot.cc.
References GetGnuplot(), GetGnuplotDataset(), and m_inputPath.
Referenced by Run().
Member Data Documentation
m_inputPath
std::string ns3::SatLinkResultsPlot::m_inputPath private
Definition at line 84 of file sat-link-results-plot.cc.
Referenced by SatLinkResultsPlot(), RunDvbRcs2Psk8(), RunDvbRcs2Qam16(), RunDvbRcs2Qpsk(), RunDvbS2Apsk16(), RunDvbS2Apsk32(), RunDvbS2Psk8(), and RunDvbS2Qpsk().
m_maxSinrDb
double ns3::SatLinkResultsPlot::m_maxSinrDb private
Definition at line 83 of file sat-link-results-plot.cc.
Referenced by SatLinkResultsPlot(), and GetGnuplotDataset().
m_minSinrDb
double ns3::SatLinkResultsPlot::m_minSinrDb private
Definition at line 82 of file sat-link-results-plot.cc.
Referenced by SatLinkResultsPlot(), and GetGnuplotDataset().
m_resolutionDb
double ns3::SatLinkResultsPlot::m_resolutionDb private
Definition at line 81 of file sat-link-results-plot.cc.
Referenced by SatLinkResultsPlot(), and GetGnuplotDataset().
The documentation for this class was generated from the following file:
/builds/sns3/satellite/satellite/examples/sat-link-results-plot.cc