SNS3
ns3::SatHelper Class Reference
Build a satellite network set with needed objects and configuration.
#include "satellite-helper.h"
Public Types
typedef std::map< std::pair< uint32_t, uint32_t >, SatBeamUserInfo > BeamUserInfoMap_t
definition for beam map key is pair sat ID / beam ID and value is UT/user info.
typedef Callback< uint32_t > GetNextUtUserCountCallback
Get number of Users for a UT.
enum PreDefinedScenario_t { NONE , SIMPLE , LARGER , FULL }
Values for pre-defined scenarios to be used by helper when building satellite network topology base.
Public Member Functions
SatHelper ()
Create a base SatHelper for creating customized Satellite topologies.
SatHelper (std::string scenarioName)
Create a base SatHelper for creating customized Satellite topologies.
virtual ~SatHelper ()
Destructor for SatHelper.
void CreateConstellationScenario (BeamUserInfoMap_t &info, GetNextUtUserCountCallback getNextUtUserCountCallback)
Creates satellite objects according to constellation parameters.
void CreatePredefinedScenario (PreDefinedScenario_t scenario)
Create a pre-defined SatHelper to make life easier when creating Satellite topologies.
void CreateUserDefinedScenario (BeamUserInfoMap_t &info)
Creates satellite objects according to user defined scenario.
void CreateUserDefinedScenarioFromListPositions (uint32_t satId, BeamUserInfoMap_t &info, bool checkBeam)
Creates satellite objects according to user defined scenario.
void DoDispose ()
Dispose of this class instance.
NodeContainer GeoSatNodes ()
Ptr< SatAntennaGainPatternContainer > GetAntennaGainPatterns ()
Ptr< SatSpotBeamPositionAllocator > GetBeamAllocator (uint32_t beamId)
Create a SatSpotBeamPositionAllocator able to generate random position within the given beam.
uint32_t GetBeamCount () const
Get count of the beams (configurations).
Ptr< SatBeamHelper > GetBeamHelper () const
uint32_t GetClosestSat (GeoCoordinate position)
Get closest satellite to a ground station.
Ptr< SatGroupHelper > GetGroupHelper () const
NodeContainer GetGwUsers () const
TypeId GetInstanceTypeId (void) const
Get the type ID of object instance.
Ipv4Address GetUserAddress (Ptr< Node > node)
Ptr< SatUserHelper > GetUserHelper () const
NodeContainer GetUtUsers () const
NodeContainer GetUtUsers (NodeContainer utNodes) const
NodeContainer GetUtUsers (Ptr< Node > utNode) const
NodeContainer GwNodes ()
bool IsSatConstellationEnabled ()
Ptr< Node > LoadMobileUtFromFile (uint32_t satId, const std::string &filename)
Load an UT with a SatTracedMobilityModel associated to them from the given file.
void LoadMobileUTsFromFolder (uint32_t satId, const std::string &folderName, Ptr< RandomVariableStream > utUsers)
Load UTs with a SatTracedMobilityModel associated to them from the files found in the given folder.
void PrintTopology (std::ostream &os) const
Print all the satellite topology.
void SetAntennaGainPatterns (Ptr< SatAntennaGainPatternContainer > antennaGainPattern)
Set the antenna gain patterns.
void SetBeamRoutingConstellations ()
Populate the routes, when using constellations.
void SetCustomUtPositionAllocator (Ptr< SatListPositionAllocator > posAllocator)
Set custom position allocator.
void SetGroupHelper (Ptr< SatGroupHelper > groupHelper)
set the group helper.
void SetGwAddressInUt ()
Set the value of GW address for each UT.
void SetMulticastGroupRoutes (Ptr< Node > source, NodeContainer receivers, Ipv4Address sourceAddress, Ipv4Address groupAddress)
Set multicast group to satellite network and IP router.
void SetUtPositionAllocatorForBeam (uint32_t beamId, Ptr< SatListPositionAllocator > posAllocator)
Set custom position allocator for specific beam.
NodeContainer UtNodes ()
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Private Types
typedef SatBeamHelper::MulticastBeamInfo_t MulticastBeamInfo_t
typedef SatBeamHelper::MulticastBeamInfoItem_t MulticastBeamInfoItem_t
Private Member Functions
void CheckNetwork (std::string networkName, const Ipv4Address &firstNetwork, const Ipv4Mask &mask, const std::set< uint32_t > &networkAddresses, uint32_t networkCount, uint32_t hostCount) const
Check validity of the configured network space.
bool ConstructMulticastInfo (Ptr< Node > sourceUtNode, NodeContainer receivers, MulticastBeamInfo_t &beamInfo, Ptr< NetDevice > &routerUserOutputDev)
Construct multicast information from source UT node and group receivers.
std::string CreateCreationSummary (std::string title)
Creates trace summary starting with give title.
void CreateFullScenario ()
Creates satellite objects according to full scenario.
void CreateLargerScenario ()
Creates satellite objects according to larger scenario.
void CreateSimpleScenario ()
Creates satellite objects according to simple scenario.
void CreationSummarySink (std::string title)
Sink for creation summary traces.
void DoCreateScenario (BeamUserInfoMap_t &info, uint32_t gwUsers)
Creates satellite objects according to given beam info.
void EnableCreationTraces ()
Enables creation traces to be written in given file.
void EnableDetailedCreationTraces ()
Enables creation traces in sub-helpers.
void EnablePacketTrace ()
Enable packet traces.
Ptr< NetDevice > FindMatchingDevice (Ptr< NetDevice > devA, Ptr< Node > nodeB)
Find given device's counterpart (device belonging to same network) device from given node.
bool FindMatchingDevices (Ptr< Node > nodeA, Ptr< Node > nodeB, std::pair< Ptr< NetDevice >, Ptr< NetDevice >> &matchingDevices)
Find counterpart (device belonging to same network) devices from given nodes.
void InstallMobilityObserver (uint32_t satId, NodeContainer nodes) const
Install Satellite Mobility Observer to nodes, if observer doesn't exist already in a node.
void LoadConstellationTopology (std::string path, std::vector< std::string > &tles, std::vector< std::pair< uint32_t, uint32_t >> &isls)
Load a constellation topology.
void SetGeoSatMobility (Ptr< Node > node)
Sets mobility to created Sat Geo node.
void SetGwMobility (uint32_t satId, Ptr< Node > gw, uint32_t gwIndex)
Sets mobilities to created GW nodes.
void SetMulticastRouteToSourceNetwork (Ptr< Node > source, Ptr< Node > destination)
Set multicast traffic to source's nwtwork by finding source network utilizing given destination node.
void SetNetworkAddresses (BeamUserInfoMap_t &info, uint32_t gwUsers) const
Set configured network addresses to user and beam helpers.
void SetSatMobility (Ptr< Node > node, std::string tle="")
Sets SGP4 mobility to created Sat node.
void SetUtMobility (NodeContainer uts, uint32_t satId, uint32_t beamId)
Sets mobility to created UT nodes.
void SetUtMobilityFromPosition (NodeContainer uts, uint32_t satId, uint32_t beamId, std::vector< std::pair< GeoCoordinate, uint32_t >> positionsAndGroupId)
Sets mobility to created UT nodes when position is known.
Static Private Member Functions
static void CreationDetailsSink (Ptr< OutputStreamWrapper > stream, std::string context, std::string info)
Sink for creation details traces.
Private Attributes
Ptr< SatAntennaGainPatternContainer > m_antennaGainPatterns
Antenna gain patterns for all spot-beams.
Ptr< SatBeamHelper > m_beamHelper
Beam helper.
Ipv4Address m_beamNetworkAddress
Initial network number of satellite devices, e.g., 10.1.1.0.
Ipv4Mask m_beamNetworkMask
Network mask number of satellite devices.
BeamUserInfoMap_t m_beamUserInfos
Info for beam creation in user defined scenario.
TracedCallback< std::string > m_creationDetailsTrace
Trace callback for creation traces (details)
TracedCallback< std::string > m_creationSummaryTrace
Trace callback for creation traces (summary)
bool m_creationTraces
flag to indicate if creation trace should be enabled for scenario creation.
Ptr< OutputStreamWrapper > m_creationTraceStream
Stream wrapper used for creation traces.
bool m_detailedCreationTraces
flag to indicate if detailed creation trace should be enabled for scenario creation.
std::string m_fwdConfFileName
std::string m_geoPosFileName
Ptr< SatGroupHelper > m_groupHelper
Group helper.
std::map< Ptr< Node >, Ptr< Node > > m_gwDistribution
Map indicating the GW node associated to each UT node.
Ipv4Address m_gwNetworkAddress
Initial network number of GW, router, and GW users, e.g., 10.2.1.0.
Ipv4Mask m_gwNetworkMask
Network mask number of GW, router, and GW users.
std::string m_gwPosFileName
std::map< uint32_t, uint32_t > m_gwSats
Map of closest satellite for each GW.
NodeContainer m_gwUser
Gateway container.
uint32_t m_gwUsers
Number of users created in public network (behind GWs) in full or user-defined scenario.
std::map< uint32_t, NodeContainer > m_mobileUtsByBeam
List of mobile UTs by beam ID.
std::multimap< uint32_t, uint32_t > m_mobileUtsUsersByBeam
List of users by mobile UT by beam ID.
bool m_packetTraces
flag to indicate if packet trace should be enabled after scenario creation.
std::string m_rtnConfFileName
Configuration file names as attributes of this class.
Ptr< SatConf > m_satConf
Configuration for satellite network.
bool m_satConstellationEnabled
Use a constellation of satellites.
std::string m_satConstellationFolder
Folder where are stored satellite constellation data.
bool m_satMobilitySGP4Enabled
The satellite moves following a SGP4 model.
std::string m_satMobilitySGP4TleFileName
TLE input filename used for SGP4 mobility.
bool m_scenarioCreated
flag to check if scenario is already created.
std::string m_scenarioCreationFileName
File name for scenario creation trace output.
SatEnums::Standard_t m_standard
Ptr< SatUserHelper > m_userHelper
User helper.
std::string m_utCreationFileName
File name for UT creation trace output.
Ipv4Address m_utNetworkAddress
Initial network number of UT and UT users, e.g., 10.3.1.0.
Ipv4Mask m_utNetworkMask
Network mask number of UT and UT users.
Ptr< SatListPositionAllocator > m_utPositions
User defined UT positions from SatConf (or manually set)
std::map< uint32_t, Ptr< SatListPositionAllocator > > m_utPositionsByBeam
User defined UT positions by beam ID.
std::map< Ptr< NetDevice >, NetDeviceContainer > m_utsDistribution
Map indicating all UT NetDevices associated to each GW NetDevice.
uint32_t m_utsInBeam
Number of UTs created per Beam in full or user-defined scenario.
Ptr< OutputStreamWrapper > m_utTraceStream
Stream wrapper used for UT position traces.
uint32_t m_utUsers
Number of users created in end user network (behind every UT) in full or user-defined scenario.
std::string m_waveformConfFileName
std::string m_wfConfigFileName
File name for Waveform configurations file.
Static Private Attributes
static const uint16_t MAX_ADDRESS_PREFIX_LENGTH = 31
static const uint16_t MIN_ADDRESS_PREFIX_LENGTH = 1
Detailed Description
Build a satellite network set with needed objects and configuration.
Utilizes SatUserHelper and SatBeamHelper helper objects.
Definition at line 55 of file satellite-helper.h.
Member Typedef Documentation
BeamUserInfoMap_t
typedef std::map<std::pair<uint32_t, uint32_t>, SatBeamUserInfo> ns3::SatHelper::BeamUserInfoMap_t
definition for beam map key is pair sat ID / beam ID and value is UT/user info.
Definition at line 61 of file satellite-helper.h.
GetNextUtUserCountCallback
typedef Callback<uint32_t> ns3::SatHelper::GetNextUtUserCountCallback
Get number of Users for a UT.
Returns
The number of UT users
Definition at line 108 of file satellite-helper.h.
MulticastBeamInfo_t
typedef SatBeamHelper::MulticastBeamInfo_t ns3::SatHelper::MulticastBeamInfo_t private
Definition at line 321 of file satellite-helper.h.
MulticastBeamInfoItem_t
typedef SatBeamHelper::MulticastBeamInfoItem_t ns3::SatHelper::MulticastBeamInfoItem_t private
Definition at line 320 of file satellite-helper.h.
Member Enumeration Documentation
PreDefinedScenario_t
enum ns3::SatHelper::PreDefinedScenario_t
Values for pre-defined scenarios to be used by helper when building satellite network topology base.
Enumerator
NONE
NONE Not used.
SIMPLE
SIMPLE Simple scenario used as base.
LARGER
LARGER Larger scenario used as base.
FULL
FULL Full scenario used as base.
Definition at line 67 of file satellite-helper.h.
Constructor & Destructor Documentation
SatHelper() [1/2]
ns3::SatHelper::SatHelper ()
Create a base SatHelper for creating customized Satellite topologies.
Definition at line 219 of file satellite-helper.cc.
References ns3::SatConf::GetCarrierBandwidthHz(), ns3::SatConf::GetCarrierFrequencyHz(), ns3::SatBeamHelper::GetPropagationDelayModel(), LoadConstellationTopology(), ns3::SatEnums::LORA, m_antennaGainPatterns, m_beamHelper, m_fwdConfFileName, m_geoPosFileName, m_gwPosFileName, m_rtnConfFileName, m_satConf, m_satConstellationEnabled, m_satConstellationFolder, m_satMobilitySGP4Enabled, m_satMobilitySGP4TleFileName, m_standard, m_userHelper, m_waveformConfFileName, ns3::SatEnums::PD_CONSTANT_SPEED, ns3::SatEnums::REGENERATION_NETWORK, SetGeoSatMobility(), ns3::SatLoraConf::setSatConfAttributes(), and SetSatMobility().
SatHelper() [2/2]
ns3::SatHelper::SatHelper (std::string scenarioName)
Create a base SatHelper for creating customized Satellite topologies.
~SatHelper()
virtual ns3::SatHelper::~SatHelper () inline virtual
Destructor for SatHelper.
Definition at line 100 of file satellite-helper.h.
Member Function Documentation
CheckNetwork()
void ns3::SatHelper::CheckNetwork (std::string networkName, const Ipv4Address & firstNetwork, const Ipv4Mask & mask, const std::set< uint32_t > & networkAddresses, uint32_t networkCount, uint32_t hostCount) const private
Check validity of the configured network space.
Parameters
networkName Name string of the network to check. To be used when printing out possible errors.
firstNetwork Address of the first network.
mask The mask of the networks.
networkAddresses The container of first address values of the networks used all together.
networkCount The number of the networks created in network.
hostCount The maximum number of the hosts created in a network.
Definition at line 1827 of file satellite-helper.cc.
References MAX_ADDRESS_PREFIX_LENGTH, and MIN_ADDRESS_PREFIX_LENGTH.
Referenced by SetNetworkAddresses().
ConstructMulticastInfo()
bool ns3::SatHelper::ConstructMulticastInfo (Ptr< Node > sourceUtNode, NodeContainer receivers, MulticastBeamInfo_t & beamInfo, Ptr< NetDevice > & routerUserOutputDev) private
Construct multicast information from source UT node and group receivers.
Parameters
sourceUtNode Pointer to UT source node. When NULL source node is not UT.
receivers Container of the multicast group receivers.
beamInfo Beam information to be filled in for multicast group.
routerUserOutputDev Pointer to router output device for backbone network (GW users). Set to NULL when traffic is not needed to route backbone network.
Returns
true when multicast traffic shall be routed to source's network.
Definition at line 1651 of file satellite-helper.cc.
References FindMatchingDevices(), m_beamHelper, and m_userHelper.
Referenced by SetMulticastGroupRoutes().
CreateConstellationScenario()
void ns3::SatHelper::CreateConstellationScenario (BeamUserInfoMap_t & info, GetNextUtUserCountCallback getNextUtUserCountCallback)
Creates satellite objects according to constellation parameters.
Parameters
infoList information of the enabled beams. UT information is given in parameters files.
getNextUtUserCountCallback Callback to get number of users per UT.
Definition at line 692 of file satellite-helper.cc.
References DoCreateScenario(), m_antennaGainPatterns, m_beamHelper, m_groupHelper, m_gwSats, m_gwUsers, and m_satConf.
CreateCreationSummary()
std::string ns3::SatHelper::CreateCreationSummary (std::string title) private
Creates trace summary starting with give title.
Parameters
title title for summary
Returns
std::string as summary
Definition at line 1410 of file satellite-helper.cc.
References m_beamHelper, and m_userHelper.
Referenced by CreationSummarySink().
CreateFullScenario()
void ns3::SatHelper::CreateFullScenario () private
Creates satellite objects according to full scenario.
Definition at line 588 of file satellite-helper.cc.
References DoCreateScenario(), m_beamUserInfos, m_creationSummaryTrace, m_gwUsers, m_satConf, m_utsInBeam, and m_utUsers.
Referenced by CreatePredefinedScenario().
CreateLargerScenario()
void ns3::SatHelper::CreateLargerScenario () private
Creates satellite objects according to larger scenario.
Definition at line 565 of file satellite-helper.cc.
References ns3::SatBeamUserInfo::AppendUt(), DoCreateScenario(), m_creationSummaryTrace, and ns3::SatBeamUserInfo::SetUtUserCount().
Referenced by CreatePredefinedScenario().
CreatePredefinedScenario()
void ns3::SatHelper::CreatePredefinedScenario (PreDefinedScenario_t scenario)
Create a pre-defined SatHelper to make life easier when creating Satellite topologies.
Definition at line 351 of file satellite-helper.cc.
References CreateFullScenario(), CreateLargerScenario(), CreateSimpleScenario(), FULL, LARGER, and SIMPLE.
CreateSimpleScenario()
void ns3::SatHelper::CreateSimpleScenario () private
Creates satellite objects according to simple scenario.
Definition at line 551 of file satellite-helper.cc.
References DoCreateScenario(), and m_creationSummaryTrace.
Referenced by CreatePredefinedScenario().
CreateUserDefinedScenario()
void ns3::SatHelper::CreateUserDefinedScenario (BeamUserInfoMap_t & info)
Creates satellite objects according to user defined scenario.
Parameters
info information of the beams, and beam UTs and users in beams
Definition at line 618 of file satellite-helper.cc.
References DoCreateScenario(), m_creationSummaryTrace, and m_gwUsers.
CreateUserDefinedScenarioFromListPositions()
void ns3::SatHelper::CreateUserDefinedScenarioFromListPositions (uint32_t satId, BeamUserInfoMap_t & info, bool checkBeam)
Creates satellite objects according to user defined scenario.
Positions are read from different input files from file set by attribute ns3::SatConf::UtPositionInputFileName.
Parameters
satId The ID of the satellite
info information of the beams, and beam UTs and users in beams
checkBeam Check that positions (set through SatConf) match with given beam (the beam is the best according to configured antenna patterns).
Definition at line 644 of file satellite-helper.cc.
References DoCreateScenario(), m_antennaGainPatterns, m_creationSummaryTrace, m_gwUsers, m_satConf, and m_utPositions.
CreationDetailsSink()
void ns3::SatHelper::CreationDetailsSink (Ptr< OutputStreamWrapper > stream, std::string context, std::string info) static private
Sink for creation details traces.
Parameters
stream stream for traces
context context for traces
info creation info
Definition at line 1393 of file satellite-helper.cc.
Referenced by EnableDetailedCreationTraces().
CreationSummarySink()
void ns3::SatHelper::CreationSummarySink (std::string title) private
Sink for creation summary traces.
Parameters
title creation summary title
Definition at line 1401 of file satellite-helper.cc.
References CreateCreationSummary(), m_beamHelper, m_creationTraceStream, and m_utTraceStream.
Referenced by EnableCreationTraces().
DoCreateScenario()
void ns3::SatHelper::DoCreateScenario (BeamUserInfoMap_t & info, uint32_t gwUsers) private
Creates satellite objects according to given beam info.
Parameters
infoList information of the sats and beam to create (and beams which are given in map)
gwUsers number of the users in GW(s) side
GW and beam ids are assumed to be the same for both directions currently!
Definition at line 731 of file satellite-helper.cc.
References ns3::SatConf::BEAM_ID_INDEX, EnableCreationTraces(), EnablePacketTrace(), ns3::SatConf::F_FREQ_ID_INDEX, ns3::SatNetDevice::GetMac(), ns3::SatConf::GW_ID_INDEX, GwNodes(), ns3::SatEnums::LD_FORWARD, ns3::SatEnums::LD_RETURN, ns3::SatLog::LOG_WARNING, ns3::SatEnums::LORA, m_beamHelper, m_creationTraces, m_gwDistribution, m_gwSats, m_mobileUtsByBeam, m_mobileUtsUsersByBeam, m_packetTraces, m_satConf, m_satConstellationEnabled, m_scenarioCreated, m_standard, m_userHelper, m_utsDistribution, SetBeamRoutingConstellations(), SetGwAddressInUt(), SetGwMobility(), SetNetworkAddresses(), SetUtMobility(), SetUtMobilityFromPosition(), ns3::SatConf::U_FREQ_ID_INDEX, ns3::SatUserHelper::UpdateGwRoutes(), ns3::SatUserHelper::UpdateUtRoutes(), and UtNodes().
Referenced by CreateConstellationScenario(), CreateFullScenario(), CreateLargerScenario(), CreateSimpleScenario(), CreateUserDefinedScenario(), and CreateUserDefinedScenarioFromListPositions().
DoDispose()
void ns3::SatHelper::DoDispose ()
Dispose of this class instance.
Definition at line 1427 of file satellite-helper.cc.
References m_antennaGainPatterns, m_beamHelper, m_mobileUtsByBeam, m_mobileUtsUsersByBeam, m_userHelper, and m_utPositionsByBeam.
EnableCreationTraces()
void ns3::SatHelper::EnableCreationTraces () private
Enables creation traces to be written in given file.
Definition at line 376 of file satellite-helper.cc.
References CreationSummarySink(), EnableDetailedCreationTraces(), m_creationTraceStream, m_detailedCreationTraces, m_scenarioCreationFileName, m_utCreationFileName, and m_utTraceStream.
Referenced by DoCreateScenario().
EnableDetailedCreationTraces()
void ns3::SatHelper::EnableDetailedCreationTraces () private
Enables creation traces in sub-helpers.
Definition at line 438 of file satellite-helper.cc.
References CreationDetailsSink(), m_beamHelper, m_creationTraceStream, and m_userHelper.
Referenced by EnableCreationTraces().
EnablePacketTrace()
void ns3::SatHelper::EnablePacketTrace () private
Enable packet traces.
Definition at line 402 of file satellite-helper.cc.
References m_beamHelper.
Referenced by DoCreateScenario().
FindMatchingDevice()
Ptr< NetDevice > ns3::SatHelper::FindMatchingDevice (Ptr< NetDevice > devA, Ptr< Node > nodeB) private
Find given device's counterpart (device belonging to same network) device from given node.
Parameters
devA Pointer to the device whose counterpart device is found from given node.
nodeB Pointer to node where given device's counterpart device is searched.
Returns
Pointer to device belonging to same network with given device in given node. NULL in cast that counterpart device is not found.
Definition at line 1588 of file satellite-helper.cc.
Referenced by FindMatchingDevices(), and SetMulticastGroupRoutes().
FindMatchingDevices()
bool ns3::SatHelper::FindMatchingDevices (Ptr< Node > nodeA, Ptr< Node > nodeB, std::pair< Ptr< NetDevice >, Ptr< NetDevice >> & matchingDevices) private
Find counterpart (device belonging to same network) devices from given nodes.
Returns
The device belonging to same network with given device on given node.
Parameters
nodeA Pointer to node A where given device's counterpart device is searched.
nodeB Pointer to node A where given device's counterpart device is searched.
matchingDevices Pair consisting pointers to found devices. first belongs to nodeA and second to nodeB.
Returns
true when counterpart devices are found from given nodes, false in other cases.
Definition at line 1566 of file satellite-helper.cc.
References FindMatchingDevice().
Referenced by ConstructMulticastInfo(), SetMulticastGroupRoutes(), and SetMulticastRouteToSourceNetwork().
GeoSatNodes()
NodeContainer ns3::SatHelper::GeoSatNodes () inline
Definition at line 287 of file satellite-helper.h.
References m_beamHelper.
GetAntennaGainPatterns()
Ptr< SatAntennaGainPatternContainer > ns3::SatHelper::GetAntennaGainPatterns ()
Returns
Get the antenna gain patterns
Definition at line 530 of file satellite-helper.cc.
References m_antennaGainPatterns.
GetBeamAllocator()
Ptr< SatSpotBeamPositionAllocator > ns3::SatHelper::GetBeamAllocator (uint32_t beamId)
Create a SatSpotBeamPositionAllocator able to generate random position within the given beam.
Parameters
beamId the beam for which the position allocator should be configured
Definition at line 1198 of file satellite-helper.cc.
References m_antennaGainPatterns, m_beamHelper, m_satConf, and m_satMobilitySGP4Enabled.
Referenced by SetUtMobility().
GetBeamCount()
uint32_t ns3::SatHelper::GetBeamCount () const
Get count of the beams (configurations).
Returns
beam count
Definition at line 543 of file satellite-helper.cc.
References m_satConf.
GetBeamHelper()
Ptr< SatBeamHelper > ns3::SatHelper::GetBeamHelper () const
Returns
pointer to beam helper.
Definition at line 502 of file satellite-helper.cc.
References m_beamHelper.
GetClosestSat()
uint32_t ns3::SatHelper::GetClosestSat (GeoCoordinate position)
Get closest satellite to a ground station.
Parameters
position The position of the ground station
Returns
The ID of the closest satellite
Definition at line 451 of file satellite-helper.cc.
References m_beamHelper.
Referenced by SetGwAddressInUt().
GetGroupHelper()
Ptr< SatGroupHelper > ns3::SatHelper::GetGroupHelper () const
Returns
pointer to group helper.
Definition at line 509 of file satellite-helper.cc.
References m_groupHelper.
GetGwUsers()
NodeContainer ns3::SatHelper::GetGwUsers () const
Returns
container having GW users.
Definition at line 494 of file satellite-helper.cc.
References m_userHelper.
GetInstanceTypeId()
TypeId ns3::SatHelper::GetInstanceTypeId (void) const
Get the type ID of object instance.
Returns
the TypeId of object instance
Definition at line 212 of file satellite-helper.cc.
References GetTypeId().
GetTypeId()
TypeId ns3::SatHelper::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 63 of file satellite-helper.cc.
References ns3::SatEnums::DVB, ns3::SatEnums::LORA, m_beamNetworkAddress, m_beamNetworkMask, m_creationDetailsTrace, m_creationSummaryTrace, m_creationTraces, m_detailedCreationTraces, m_fwdConfFileName, m_geoPosFileName, m_gwNetworkAddress, m_gwNetworkMask, m_gwPosFileName, m_gwUsers, m_packetTraces, m_rtnConfFileName, m_satConstellationEnabled, m_satConstellationFolder, m_satMobilitySGP4Enabled, m_satMobilitySGP4TleFileName, m_scenarioCreationFileName, m_standard, m_utCreationFileName, m_utNetworkAddress, m_utNetworkMask, m_utsInBeam, m_utUsers, and m_waveformConfFileName.
Referenced by GetInstanceTypeId().
GetUserAddress()
Ipv4Address ns3::SatHelper::GetUserAddress (Ptr< Node > node)
Parameters
node pointer to user node.
Returns
address of the user.
Definition at line 459 of file satellite-helper.cc.
GetUserHelper()
Ptr< SatUserHelper > ns3::SatHelper::GetUserHelper () const
Returns
pointer to user helper.
Definition at line 536 of file satellite-helper.cc.
References m_userHelper.
GetUtUsers() [1/3]
NodeContainer ns3::SatHelper::GetUtUsers () const
Returns
container having UT users
Definition at line 469 of file satellite-helper.cc.
References m_userHelper.
Referenced by GetUtUsers().
GetUtUsers() [2/3]
NodeContainer ns3::SatHelper::GetUtUsers (NodeContainer utNodes) const
Parameters
utNodes Container to UT nodes, which user nodes are requested.
Returns
A container having UT specific user nodes in satellite network.
Definition at line 483 of file satellite-helper.cc.
References GetUtUsers().
GetUtUsers() [3/3]
NodeContainer ns3::SatHelper::GetUtUsers (Ptr< Node > utNode) const
Parameters
utNode Pointer to UT node, which user nodes are requested.
Returns
A container having UT specific user nodes in satellite network.
Definition at line 477 of file satellite-helper.cc.
References m_userHelper.
GwNodes()
NodeContainer ns3::SatHelper::GwNodes () inline
Definition at line 277 of file satellite-helper.h.
References m_beamHelper.
Referenced by DoCreateScenario(), and SetBeamRoutingConstellations().
InstallMobilityObserver()
void ns3::SatHelper::InstallMobilityObserver (uint32_t satId, NodeContainer nodes) const private
Install Satellite Mobility Observer to nodes, if observer doesn't exist already in a node.
Parameters
satId ID of the satellite.
nodes Nodecontainer of nodes to install mobility observer.
Definition at line 1262 of file satellite-helper.cc.
References m_beamHelper, satMobility, and ns3::SatEnums::TRANSPARENT.
Referenced by LoadMobileUTsFromFolder(), SetGwMobility(), SetUtMobility(), and SetUtMobilityFromPosition().
IsSatConstellationEnabled()
bool ns3::SatHelper::IsSatConstellationEnabled () inline
Definition at line 305 of file satellite-helper.h.
References m_satConstellationEnabled.
LoadConstellationTopology()
void ns3::SatHelper::LoadConstellationTopology (std::string path, std::vector< std::string > & tles, std::vector< std::pair< uint32_t, uint32_t >> & isls) private
Load a constellation topology.
Parameters
path Folder where configuration files are located
tles vector to store read TLEs
isls vector to store read ISLs
Definition at line 408 of file satellite-helper.cc.
References m_fwdConfFileName, m_geoPosFileName, m_rtnConfFileName, m_satConf, m_satMobilitySGP4TleFileName, and m_waveformConfFileName.
Referenced by SatHelper().
LoadMobileUtFromFile()
Ptr< Node > ns3::SatHelper::LoadMobileUtFromFile (uint32_t satId, const std::string & filename)
Load an UT with a SatTracedMobilityModel associated to them from the given file.
Parameters
satId ID of satellite
filename Name of the trace file containing UT positions
Definition at line 1084 of file satellite-helper.cc.
References m_antennaGainPatterns.
Referenced by LoadMobileUTsFromFolder().
LoadMobileUTsFromFolder()
void ns3::SatHelper::LoadMobileUTsFromFolder (uint32_t satId, const std::string & folderName, Ptr< RandomVariableStream > utUsers)
Load UTs with a SatTracedMobilityModel associated to them from the files found in the given folder.
Each UT will be associated to the beam it is at it's starting position.
Parameters
satId ID of satellite
folderName Name of the folder to search for mobility trace files
utUsers Stream to generate the number of users associated to each loaded UT
Definition at line 1034 of file satellite-helper.cc.
References InstallMobilityObserver(), LoadMobileUtFromFile(), m_mobileUtsByBeam, and m_mobileUtsUsersByBeam.
PrintTopology()
void ns3::SatHelper::PrintTopology (std::ostream & os) const
Print all the satellite topology.
Parameters
os output stream in which the data should be printed
Definition at line 1441 of file satellite-helper.cc.
References m_beamHelper, and m_userHelper.
SetAntennaGainPatterns()
void ns3::SatHelper::SetAntennaGainPatterns (Ptr< SatAntennaGainPatternContainer > antennaGainPattern)
Set the antenna gain patterns.
Parameters
antennaGainPattern The pattern to set
Definition at line 523 of file satellite-helper.cc.
References m_antennaGainPatterns.
SetBeamRoutingConstellations()
void ns3::SatHelper::SetBeamRoutingConstellations ()
Populate the routes, when using constellations.
Definition at line 1008 of file satellite-helper.cc.
References GwNodes(), m_userHelper, and m_utsDistribution.
Referenced by DoCreateScenario().
SetCustomUtPositionAllocator()
void ns3::SatHelper::SetCustomUtPositionAllocator (Ptr< SatListPositionAllocator > posAllocator)
Set custom position allocator.
Parameters
posAllocator
Definition at line 629 of file satellite-helper.cc.
References m_utPositions.
SetGeoSatMobility()
void ns3::SatHelper::SetGeoSatMobility (Ptr< Node > node) private
Sets mobility to created Sat Geo node.
Parameters
node node pointer of Geo Satellite to set mobility
Definition at line 1217 of file satellite-helper.cc.
References m_satConf.
Referenced by SatHelper().
SetGroupHelper()
void ns3::SatHelper::SetGroupHelper (Ptr< SatGroupHelper > groupHelper)
set the group helper.
Definition at line 516 of file satellite-helper.cc.
References m_groupHelper.
SetGwAddressInUt()
void ns3::SatHelper::SetGwAddressInUt ()
Set the value of GW address for each UT.
This method is called when using constellations.
Definition at line 938 of file satellite-helper.cc.
References GetClosestSat(), m_beamHelper, and m_gwDistribution.
Referenced by DoCreateScenario().
SetGwMobility()
void ns3::SatHelper::SetGwMobility (uint32_t satId, Ptr< Node > gw, uint32_t gwIndex) private
Sets mobilities to created GW nodes.
Parameters
satId ID of the satellite link to this GW
gw GW to set mobility
gwIndex Index of GW in SatConf
Definition at line 1096 of file satellite-helper.cc.
References InstallMobilityObserver(), and m_satConf.
Referenced by DoCreateScenario().
SetMulticastGroupRoutes()
void ns3::SatHelper::SetMulticastGroupRoutes (Ptr< Node > source, NodeContainer receivers, Ipv4Address sourceAddress, Ipv4Address groupAddress)
Set multicast group to satellite network and IP router.
Add needed routes to net devices.
Parameters
source Source node of the multicast group (GW or UT connected user node)
receivers Receiver nodes of the multicast group. (GW or UT connected user nodes)
sourceAddress Source address of the multicast group.
groupAddress Address of the multicast group.
Definition at line 1290 of file satellite-helper.cc.
References ConstructMulticastInfo(), FindMatchingDevice(), FindMatchingDevices(), m_beamHelper, m_userHelper, and SetMulticastRouteToSourceNetwork().
SetMulticastRouteToSourceNetwork()
void ns3::SatHelper::SetMulticastRouteToSourceNetwork (Ptr< Node > source, Ptr< Node > destination) private
Set multicast traffic to source's nwtwork by finding source network utilizing given destination node.
Note that all multicast traffic is routed by source through selected device in source node to found network.
Parameters
source Pointer to source node of the multicast traffic.
destination Pointer to destination node where to find matching source network
Definition at line 1616 of file satellite-helper.cc.
References FindMatchingDevices().
Referenced by SetMulticastGroupRoutes().
SetNetworkAddresses()
void ns3::SatHelper::SetNetworkAddresses (BeamUserInfoMap_t & info, uint32_t gwUsers) const private
Set configured network addresses to user and beam helpers.
Definition at line 1742 of file satellite-helper.cc.
References CheckNetwork(), m_beamHelper, m_beamNetworkAddress, m_beamNetworkMask, m_gwNetworkAddress, m_gwNetworkMask, m_userHelper, m_utNetworkAddress, and m_utNetworkMask.
Referenced by DoCreateScenario().
SetSatMobility()
void ns3::SatHelper::SetSatMobility (Ptr< Node > node, std::string tle = "") private
Sets SGP4 mobility to created Sat node.
Parameters
node node pointer of Satellite to set mobility
Definition at line 1232 of file satellite-helper.cc.
References m_satConf.
Referenced by SatHelper().
SetUtMobility()
void ns3::SatHelper::SetUtMobility (NodeContainer uts, uint32_t satId, uint32_t beamId) private
Sets mobility to created UT nodes.
Parameters
uts node container of UTs to set mobility
satId the satellite id, where the UTs should be placed
beamId the spot-beam id, where the UTs should be placed
Definition at line 1114 of file satellite-helper.cc.
References GetBeamAllocator(), InstallMobilityObserver(), m_antennaGainPatterns, m_beamHelper, m_utPositions, and m_utPositionsByBeam.
Referenced by DoCreateScenario().
SetUtMobilityFromPosition()
void ns3::SatHelper::SetUtMobilityFromPosition (NodeContainer uts, uint32_t satId, uint32_t beamId, std::vector< std::pair< GeoCoordinate, uint32_t >> positionsAndGroupId) private
Sets mobility to created UT nodes when position is known.
Parameters
uts node container of UTs to set mobility
satId the satellite id, where the UTs should be placed
beamId the spot-beam id, where the UTs should be placed
positionsAndGroupId the list of known positions, associated to a group ID
Definition at line 1157 of file satellite-helper.cc.
References InstallMobilityObserver(), m_antennaGainPatterns, m_beamHelper, and m_groupHelper.
Referenced by DoCreateScenario().
SetUtPositionAllocatorForBeam()
void ns3::SatHelper::SetUtPositionAllocatorForBeam (uint32_t beamId, Ptr< SatListPositionAllocator > posAllocator)
Set custom position allocator for specific beam.
This overrides the custom position allocator for this beam.
Parameters
beamId
posAllocator
Definition at line 636 of file satellite-helper.cc.
References m_utPositionsByBeam.
UtNodes()
NodeContainer ns3::SatHelper::UtNodes () inline
Definition at line 282 of file satellite-helper.h.
References m_beamHelper.
Referenced by DoCreateScenario().
Member Data Documentation
m_antennaGainPatterns
Ptr<SatAntennaGainPatternContainer> ns3::SatHelper::m_antennaGainPatterns private
Antenna gain patterns for all spot-beams.
Used for beam selection.
Definition at line 476 of file satellite-helper.h.
Referenced by SatHelper(), CreateConstellationScenario(), CreateUserDefinedScenarioFromListPositions(), DoDispose(), GetAntennaGainPatterns(), GetBeamAllocator(), LoadMobileUtFromFile(), SetAntennaGainPatterns(), SetUtMobility(), and SetUtMobilityFromPosition().
m_beamHelper
Ptr<SatBeamHelper> ns3::SatHelper::m_beamHelper private
Beam helper.
Definition at line 365 of file satellite-helper.h.
Referenced by SatHelper(), ConstructMulticastInfo(), CreateConstellationScenario(), CreateCreationSummary(), CreationSummarySink(), DoCreateScenario(), DoDispose(), EnableDetailedCreationTraces(), EnablePacketTrace(), GeoSatNodes(), GetBeamAllocator(), GetBeamHelper(), GetClosestSat(), GwNodes(), InstallMobilityObserver(), PrintTopology(), SetGwAddressInUt(), SetMulticastGroupRoutes(), SetNetworkAddresses(), SetUtMobility(), SetUtMobilityFromPosition(), and UtNodes().
m_beamNetworkAddress
Ipv4Address ns3::SatHelper::m_beamNetworkAddress private
Initial network number of satellite devices, e.g., 10.1.1.0.
Definition at line 404 of file satellite-helper.h.
Referenced by GetTypeId(), and SetNetworkAddresses().
m_beamNetworkMask
Ipv4Mask ns3::SatHelper::m_beamNetworkMask private
Network mask number of satellite devices.
Definition at line 409 of file satellite-helper.h.
Referenced by GetTypeId(), and SetNetworkAddresses().
m_beamUserInfos
BeamUserInfoMap_t ns3::SatHelper::m_beamUserInfos private
Info for beam creation in user defined scenario.
first is ID of the beam and second is number of beam created in beam. If second is zero then default number of UTs is created (number set by attribute UtCount)
Info is set by attribute BeamInfo
Definition at line 456 of file satellite-helper.h.
Referenced by CreateFullScenario().
m_creationDetailsTrace
TracedCallback<std::string> ns3::SatHelper::m_creationDetailsTrace private
Trace callback for creation traces (details)
Definition at line 385 of file satellite-helper.h.
Referenced by GetTypeId().
m_creationSummaryTrace
TracedCallback<std::string> ns3::SatHelper::m_creationSummaryTrace private
Trace callback for creation traces (summary)
Definition at line 391 of file satellite-helper.h.
Referenced by CreateFullScenario(), CreateLargerScenario(), CreateSimpleScenario(), CreateUserDefinedScenario(), CreateUserDefinedScenarioFromListPositions(), and GetTypeId().
m_creationTraces
bool ns3::SatHelper::m_creationTraces private
flag to indicate if creation trace should be enabled for scenario creation.
Definition at line 421 of file satellite-helper.h.
Referenced by DoCreateScenario(), and GetTypeId().
m_creationTraceStream
Ptr<OutputStreamWrapper> ns3::SatHelper::m_creationTraceStream private
Stream wrapper used for creation traces.
Definition at line 396 of file satellite-helper.h.
Referenced by CreationSummarySink(), EnableCreationTraces(), and EnableDetailedCreationTraces().
m_detailedCreationTraces
bool ns3::SatHelper::m_detailedCreationTraces private
flag to indicate if detailed creation trace should be enabled for scenario creation.
Definition at line 426 of file satellite-helper.h.
Referenced by EnableCreationTraces(), and GetTypeId().
m_fwdConfFileName
std::string ns3::SatHelper::m_fwdConfFileName private
Definition at line 327 of file satellite-helper.h.
Referenced by SatHelper(), GetTypeId(), and LoadConstellationTopology().
m_geoPosFileName
std::string ns3::SatHelper::m_geoPosFileName private
Definition at line 329 of file satellite-helper.h.
Referenced by SatHelper(), GetTypeId(), and LoadConstellationTopology().
m_groupHelper
Ptr<SatGroupHelper> ns3::SatHelper::m_groupHelper private
Group helper.
Definition at line 370 of file satellite-helper.h.
Referenced by CreateConstellationScenario(), GetGroupHelper(), SetGroupHelper(), and SetUtMobilityFromPosition().
m_gwDistribution
std::map<Ptr<Node>, Ptr<Node> > ns3::SatHelper::m_gwDistribution private
Map indicating the GW node associated to each UT node.
Definition at line 507 of file satellite-helper.h.
Referenced by DoCreateScenario(), and SetGwAddressInUt().
m_gwNetworkAddress
Ipv4Address ns3::SatHelper::m_gwNetworkAddress private
Initial network number of GW, router, and GW users, e.g., 10.2.1.0.
Definition at line 406 of file satellite-helper.h.
Referenced by GetTypeId(), and SetNetworkAddresses().
m_gwNetworkMask
Ipv4Mask ns3::SatHelper::m_gwNetworkMask private
Network mask number of GW, router, and GW users.
Definition at line 410 of file satellite-helper.h.
Referenced by GetTypeId(), and SetNetworkAddresses().
m_gwPosFileName
std::string ns3::SatHelper::m_gwPosFileName private
Definition at line 328 of file satellite-helper.h.
Referenced by SatHelper(), and GetTypeId().
m_gwSats
std::map<uint32_t, uint32_t> ns3::SatHelper::m_gwSats private
Map of closest satellite for each GW.
Definition at line 502 of file satellite-helper.h.
Referenced by CreateConstellationScenario(), and DoCreateScenario().
m_gwUser
NodeContainer ns3::SatHelper::m_gwUser private
Gateway container.
Definition at line 375 of file satellite-helper.h.
m_gwUsers
uint32_t ns3::SatHelper::m_gwUsers private
Number of users created in public network (behind GWs) in full or user-defined scenario.
Definition at line 441 of file satellite-helper.h.
Referenced by CreateConstellationScenario(), CreateFullScenario(), CreateUserDefinedScenario(), CreateUserDefinedScenarioFromListPositions(), and GetTypeId().
m_mobileUtsByBeam
std::map<uint32_t, NodeContainer> ns3::SatHelper::m_mobileUtsByBeam private
List of mobile UTs by beam ID.
Definition at line 492 of file satellite-helper.h.
Referenced by DoCreateScenario(), DoDispose(), and LoadMobileUTsFromFolder().
m_mobileUtsUsersByBeam
std::multimap<uint32_t, uint32_t> ns3::SatHelper::m_mobileUtsUsersByBeam private
List of users by mobile UT by beam ID.
Definition at line 497 of file satellite-helper.h.
Referenced by DoCreateScenario(), DoDispose(), and LoadMobileUTsFromFolder().
m_packetTraces
bool ns3::SatHelper::m_packetTraces private
flag to indicate if packet trace should be enabled after scenario creation.
Definition at line 431 of file satellite-helper.h.
Referenced by DoCreateScenario(), and GetTypeId().
m_rtnConfFileName
std::string ns3::SatHelper::m_rtnConfFileName private
Configuration file names as attributes of this class.
Definition at line 326 of file satellite-helper.h.
Referenced by SatHelper(), GetTypeId(), and LoadConstellationTopology().
m_satConf
Ptr<SatConf> ns3::SatHelper::m_satConf private
Configuration for satellite network.
Definition at line 380 of file satellite-helper.h.
Referenced by SatHelper(), CreateConstellationScenario(), CreateFullScenario(), CreateUserDefinedScenarioFromListPositions(), DoCreateScenario(), GetBeamAllocator(), GetBeamCount(), LoadConstellationTopology(), SetGeoSatMobility(), SetGwMobility(), and SetSatMobility().
m_satConstellationEnabled
bool ns3::SatHelper::m_satConstellationEnabled private
Use a constellation of satellites.
Definition at line 345 of file satellite-helper.h.
Referenced by SatHelper(), DoCreateScenario(), GetTypeId(), and IsSatConstellationEnabled().
m_satConstellationFolder
std::string ns3::SatHelper::m_satConstellationFolder private
Folder where are stored satellite constellation data.
Definition at line 350 of file satellite-helper.h.
Referenced by SatHelper(), and GetTypeId().
m_satMobilitySGP4Enabled
bool ns3::SatHelper::m_satMobilitySGP4Enabled private
The satellite moves following a SGP4 model.
Definition at line 335 of file satellite-helper.h.
Referenced by SatHelper(), GetBeamAllocator(), and GetTypeId().
m_satMobilitySGP4TleFileName
std::string ns3::SatHelper::m_satMobilitySGP4TleFileName private
TLE input filename used for SGP4 mobility.
Definition at line 340 of file satellite-helper.h.
Referenced by SatHelper(), GetTypeId(), and LoadConstellationTopology().
m_scenarioCreated
bool ns3::SatHelper::m_scenarioCreated private
flag to check if scenario is already created.
Definition at line 416 of file satellite-helper.h.
Referenced by DoCreateScenario().
m_scenarioCreationFileName
std::string ns3::SatHelper::m_scenarioCreationFileName private
File name for scenario creation trace output.
Definition at line 461 of file satellite-helper.h.
Referenced by EnableCreationTraces(), and GetTypeId().
m_standard
SatEnums::Standard_t ns3::SatHelper::m_standard private
Definition at line 355 of file satellite-helper.h.
Referenced by SatHelper(), DoCreateScenario(), and GetTypeId().
m_userHelper
Ptr<SatUserHelper> ns3::SatHelper::m_userHelper private
User helper.
Definition at line 360 of file satellite-helper.h.
Referenced by SatHelper(), ConstructMulticastInfo(), CreateCreationSummary(), DoCreateScenario(), DoDispose(), EnableDetailedCreationTraces(), GetGwUsers(), GetUserHelper(), GetUtUsers(), PrintTopology(), SetBeamRoutingConstellations(), SetMulticastGroupRoutes(), and SetNetworkAddresses().
m_utCreationFileName
std::string ns3::SatHelper::m_utCreationFileName private
File name for UT creation trace output.
Definition at line 466 of file satellite-helper.h.
Referenced by EnableCreationTraces(), and GetTypeId().
m_utNetworkAddress
Ipv4Address ns3::SatHelper::m_utNetworkAddress private
Initial network number of UT and UT users, e.g., 10.3.1.0.
Definition at line 407 of file satellite-helper.h.
Referenced by GetTypeId(), and SetNetworkAddresses().
m_utNetworkMask
Ipv4Mask ns3::SatHelper::m_utNetworkMask private
Network mask number of UT and UT users.
Definition at line 411 of file satellite-helper.h.
Referenced by GetTypeId(), and SetNetworkAddresses().
m_utPositions
Ptr<SatListPositionAllocator> ns3::SatHelper::m_utPositions private
User defined UT positions from SatConf (or manually set)
Definition at line 487 of file satellite-helper.h.
Referenced by CreateUserDefinedScenarioFromListPositions(), SetCustomUtPositionAllocator(), and SetUtMobility().
m_utPositionsByBeam
std::map<uint32_t, Ptr<SatListPositionAllocator> > ns3::SatHelper::m_utPositionsByBeam private
User defined UT positions by beam ID.
This is preferred to m_utPositions, which is a common list for all UTs.
Definition at line 482 of file satellite-helper.h.
Referenced by DoDispose(), SetUtMobility(), and SetUtPositionAllocatorForBeam().
m_utsDistribution
std::map<Ptr<NetDevice>, NetDeviceContainer> ns3::SatHelper::m_utsDistribution private
Map indicating all UT NetDevices associated to each GW NetDevice.
Definition at line 512 of file satellite-helper.h.
Referenced by DoCreateScenario(), and SetBeamRoutingConstellations().
m_utsInBeam
uint32_t ns3::SatHelper::m_utsInBeam private
Number of UTs created per Beam in full or user-defined scenario.
Definition at line 436 of file satellite-helper.h.
Referenced by CreateFullScenario(), and GetTypeId().
m_utTraceStream
Ptr<OutputStreamWrapper> ns3::SatHelper::m_utTraceStream private
Stream wrapper used for UT position traces.
Definition at line 401 of file satellite-helper.h.
Referenced by CreationSummarySink(), and EnableCreationTraces().
m_utUsers
uint32_t ns3::SatHelper::m_utUsers private
Number of users created in end user network (behind every UT) in full or user-defined scenario.
Definition at line 447 of file satellite-helper.h.
Referenced by CreateFullScenario(), and GetTypeId().
m_waveformConfFileName
std::string ns3::SatHelper::m_waveformConfFileName private
Definition at line 330 of file satellite-helper.h.
Referenced by SatHelper(), GetTypeId(), and LoadConstellationTopology().
m_wfConfigFileName
std::string ns3::SatHelper::m_wfConfigFileName private
File name for Waveform configurations file.
Definition at line 471 of file satellite-helper.h.
MAX_ADDRESS_PREFIX_LENGTH
const uint16_t ns3::SatHelper::MAX_ADDRESS_PREFIX_LENGTH = 31 static private
Definition at line 318 of file satellite-helper.h.
Referenced by CheckNetwork().
MIN_ADDRESS_PREFIX_LENGTH
const uint16_t ns3::SatHelper::MIN_ADDRESS_PREFIX_LENGTH = 1 static private
Definition at line 317 of file satellite-helper.h.
Referenced by CheckNetwork().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/helper/satellite-helper.h
/builds/sns3/satellite/satellite/helper/satellite-helper.cc