SNS3
ns3::SatFrameUserLoadProbe Class Reference
Probe to translate from a FrameUtLoadTrace trace source.
#include "satellite-frame-user-load-probe.h"
Public Types
typedef void(* FrameUserLoadCallback) (uint32_t frameId, uint32_t utCount)
Callback signature for frame load in unit of users.
Public Member Functions
SatFrameUserLoadProbe ()
Default constructor.
virtual ~SatFrameUserLoadProbe ()
Destructor for SatFrameUserLoadProbe.
virtual bool ConnectByObject (std::string traceSource, Ptr< Object > obj)
connect to a trace source attribute provided by a given object
virtual void ConnectByPath (std::string path)
connect to a trace source provided by a config path
void SetValue (uint32_t frameId, uint32_t utCount)
Set a probe value.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
static void SetValueByPath (std::string path, uint32_t frameId, uint32_t utCount)
Set a probe value by its name in the Config system.
Private Member Functions
void TraceSink (uint32_t frameId, uint32_t utCount)
Method to connect to an underlying ns3::TraceSource with arguments of type uint32_t and uint32_t.
Private Attributes
TracedCallback< uint32_t, uint32_t > m_output
Output trace, the frame ID and number of scheduled users.
Detailed Description
Probe to translate from a FrameUtLoadTrace trace source.
This class is designed to probe an underlying ns3 TraceSource exporting a frame load information. This probe exports a trace source "Output" with two arguments of type uint32_t: frame ID and number of scheduled users. The trace sources emit values when either the probed trace source emits a new value, or when SetValue () is called.
Definition at line 48 of file satellite-frame-user-load-probe.h.
Member Typedef Documentation
FrameUserLoadCallback
typedef void(* ns3::SatFrameUserLoadProbe::FrameUserLoadCallback) (uint32_t frameId, uint32_t utCount)
Callback signature for frame load in unit of users.
Parameters
frameId The current frame number.
utCount The number of scheduled users.
Definition at line 109 of file satellite-frame-user-load-probe.h.
Constructor & Destructor Documentation
SatFrameUserLoadProbe()
ns3::SatFrameUserLoadProbe::SatFrameUserLoadProbe ()
Default constructor.
Definition at line 59 of file satellite-frame-user-load-probe.cc.
~SatFrameUserLoadProbe()
ns3::SatFrameUserLoadProbe::~SatFrameUserLoadProbe () virtual
Destructor for SatFrameUserLoadProbe.
Definition at line 64 of file satellite-frame-user-load-probe.cc.
Member Function Documentation
ConnectByObject()
bool ns3::SatFrameUserLoadProbe::ConnectByObject (std::string traceSource, Ptr< Object > obj) virtual
connect to a trace source attribute provided by a given object
Parameters
traceSource the name of the attribute TraceSource to connect to
obj ns3::Object to connect to
Returns
true if the trace source was successfully connected
Definition at line 86 of file satellite-frame-user-load-probe.cc.
References TraceSink().
ConnectByPath()
void ns3::SatFrameUserLoadProbe::ConnectByPath (std::string path) virtual
connect to a trace source provided by a config path
Parameters
path Config path to bind to
Note, if an invalid path is provided, the probe will not be connected to anything.
Definition at line 97 of file satellite-frame-user-load-probe.cc.
References TraceSink().
GetTypeId()
TypeId ns3::SatFrameUserLoadProbe::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 45 of file satellite-frame-user-load-probe.cc.
References m_output.
SetValue()
void ns3::SatFrameUserLoadProbe::SetValue (uint32_t frameId, uint32_t utCount)
Set a probe value.
Parameters
frameId set the frame number equal to this
utCount set the traced number of scheduled users equal to this
Definition at line 70 of file satellite-frame-user-load-probe.cc.
References m_output.
SetValueByPath()
void ns3::SatFrameUserLoadProbe::SetValueByPath (std::string path, uint32_t frameId, uint32_t utCount) static
Set a probe value by its name in the Config system.
Parameters
path config path to access the probe
frameId set the frame number equal to this
utCount set the traced number of scheduled users equal to this
Definition at line 77 of file satellite-frame-user-load-probe.cc.
TraceSink()
void ns3::SatFrameUserLoadProbe::TraceSink (uint32_t frameId, uint32_t utCount) private
Method to connect to an underlying ns3::TraceSource with arguments of type uint32_t and uint32_t.
Parameters
frameId frame number
utCount the traced number of scheduled users
Definition at line 105 of file satellite-frame-user-load-probe.cc.
References m_output.
Referenced by ConnectByObject(), and ConnectByPath().
Member Data Documentation
m_output
TracedCallback<uint32_t, uint32_t> ns3::SatFrameUserLoadProbe::m_output private
Output trace, the frame ID and number of scheduled users.
Definition at line 122 of file satellite-frame-user-load-probe.h.
Referenced by GetTypeId(), SetValue(), and TraceSink().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/stats/satellite-frame-user-load-probe.h
/builds/sns3/satellite/satellite/stats/satellite-frame-user-load-probe.cc