SNS3
ns3::SatStatsPacketCollisionHelper Class Reference
Satellite Statistics
#include "satellite-stats-packet-collision-helper.h"
Public Member Functions
SatStatsPacketCollisionHelper (Ptr< const SatHelper > satHelper)
virtual ~SatStatsPacketCollisionHelper ()
/ Destructor.
void CollisionRxCallback (uint32_t nPackets, const Address &from, bool isCollided)
Receive inputs from trace sources and determine the right collector to forward the inputs to.
std::string GetTraceSourceName () const
SatPhyRxCarrier::CarrierType GetValidCarrierType () const
Get the valid carrier type.
Public Member Functions inherited from ns3::SatStatsHelper
SatStatsHelper (Ptr< const SatHelper > satHelper)
Creates a new helper instance.
virtual ~SatStatsHelper ()
/ Destructor.
IdentifierType_t GetIdentifierType () const
std::string GetName () const
OutputType_t GetOutputType () const
Ptr< const SatHelper > GetSatHelper () const
void Install ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
bool IsInstalled () const
void SetIdentifierType (IdentifierType_t identifierType)
void SetName (std::string name)
void SetOutputType (OutputType_t outputType)
Static Public Member Functions
static TypeId GetTypeId ()
inherited from ObjectBase base class
Static Public Member Functions inherited from ns3::SatStatsHelper
static std::string GetIdentifierTypeName (IdentifierType_t identifierType)
static std::string GetOutputTypeName (OutputType_t outputType)
static TypeId GetTypeId ()
inherited from ObjectBase base class
Protected Member Functions
void SaveAddressAndIdentifier (Ptr< Node > utNode)
Save the address and the proper identifier from the given UT node.
void SetTraceSourceName (std::string traceSourceName)
void SetValidCarrierType (SatPhyRxCarrier::CarrierType carrierType)
Set valid carrier type for this statistics helper type.
Protected Member Functions inherited from ns3::SatStatsHelper
Ptr< DataCollectionObject > CreateAggregator (std::string aggregatorTypeId, std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue())
Create the aggregator according to the output type.
uint32_t CreateCollectorPerIdentifier (CollectorMap &collectorMap) const
Create one collector instance for each identifier in the simulation.
virtual void DoInstall ()=0
Install the probes, collectors, and aggregators necessary to produce the statistics output.
virtual std::string GetDistributionHeading (std::string dataLabel) const
uint32_t GetGwId (Ptr< Node > gwNode) const
uint32_t GetIdentifierForBeam (uint32_t satId, uint32_t beamId) const
uint32_t GetIdentifierForGroup (uint32_t groupId) const
uint32_t GetIdentifierForGw (Ptr< Node > gwNode) const
uint32_t GetIdentifierForIsl (Ptr< Node > satNodeSrc, Ptr< Node > satNodeDst) const
uint32_t GetIdentifierForSat (Ptr< Node > satNode) const
uint32_t GetIdentifierForUt (Ptr< Node > utNode) const
uint32_t GetIdentifierForUtUser (Ptr< Node > utUserNode) const
virtual std::string GetIdentifierHeading (std::string dataLabel) const
virtual std::string GetOutputFileName () const
Compute the path and file name where statistics output should be written to.
virtual std::string GetOutputPath () const
uint32_t GetSatId (Ptr< Node > satNode) const
virtual std::string GetTimeHeading (std::string dataLabel) const
uint32_t GetUtId (Ptr< Node > utNode) const
uint32_t GetUtUserId (Ptr< Node > utUserNode) const
Protected Attributes
std::map< const Address, uint32_t > m_identifierMap
Map of address and the identifier associated with it (for forward link).
CollectorMap m_terminalCollectors
Maintains a list of collectors created by this helper.
Private Attributes
SatPhyRxCarrier::CarrierType m_carrierType
std::string m_traceSourceName
Additional Inherited Members
Public Types inherited from ns3::SatStatsHelper
enum IdentifierType_t {
IDENTIFIER_GLOBAL = 0 , IDENTIFIER_GW , IDENTIFIER_BEAM , IDENTIFIER_UT ,
IDENTIFIER_UT_USER , IDENTIFIER_SLICE , IDENTIFIER_GROUP , IDENTIFIER_SAT ,
IDENTIFIER_ISL
}
Possible categorization of statistics output.
enum OutputType_t {
OUTPUT_NONE = 0 , OUTPUT_SCALAR_FILE , OUTPUT_SCATTER_FILE , OUTPUT_HISTOGRAM_FILE ,
OUTPUT_PDF_FILE , OUTPUT_CDF_FILE , OUTPUT_SCALAR_PLOT , OUTPUT_SCATTER_PLOT ,
OUTPUT_HISTOGRAM_PLOT , OUTPUT_PDF_PLOT , OUTPUT_CDF_PLOT
}
Possible types and formats of statistics output.
Static Protected Member Functions inherited from ns3::SatStatsHelper
static NetDeviceContainer GetGwSatNetDevice (Ptr< Node > gwNode)
static Ptr< NetDevice > GetSatSatGeoNetDevice (Ptr< Node > satNode)
static Ptr< NetDevice > GetUtSatNetDevice (Ptr< Node > utNode)
Detailed Description
Definition at line 46 of file satellite-stats-packet-collision-helper.h.
Constructor & Destructor Documentation
SatStatsPacketCollisionHelper()
ns3::SatStatsPacketCollisionHelper::SatStatsPacketCollisionHelper (Ptr< const SatHelper > satHelper)
Definition at line 57 of file satellite-stats-packet-collision-helper.cc.
~SatStatsPacketCollisionHelper()
ns3::SatStatsPacketCollisionHelper::~SatStatsPacketCollisionHelper () virtual
/ Destructor.
Definition at line 63 of file satellite-stats-packet-collision-helper.cc.
Member Function Documentation
CollisionRxCallback()
void ns3::SatStatsPacketCollisionHelper::CollisionRxCallback (uint32_t nPackets, const Address & from, bool isCollided)
Receive inputs from trace sources and determine the right collector to forward the inputs to.
Parameters
nPackets number of packets in the received packet burst.
from the source address of the packet.
isCollided whether a collision has occurred.
Definition at line 89 of file satellite-stats-packet-collision-helper.cc.
References ns3::SatStatsHelper::GetOutputType(), ns3::SatStatsHelper::GetOutputTypeName(), m_identifierMap, m_terminalCollectors, ns3::SatStatsHelper::OUTPUT_SCALAR_FILE, ns3::SatStatsHelper::OUTPUT_SCALAR_PLOT, ns3::SatStatsHelper::OUTPUT_SCATTER_FILE, and ns3::SatStatsHelper::OUTPUT_SCATTER_PLOT.
Referenced by ns3::SatStatsFeederPacketCollisionHelper::DoInstall(), and ns3::SatStatsUserPacketCollisionHelper::DoInstall().
GetTraceSourceName()
std::string ns3::SatStatsPacketCollisionHelper::GetTraceSourceName () const
Returns
Definition at line 83 of file satellite-stats-packet-collision-helper.cc.
References m_traceSourceName.
Referenced by ns3::SatStatsFeederPacketCollisionHelper::DoInstall(), and ns3::SatStatsUserPacketCollisionHelper::DoInstall().
GetTypeId()
TypeId ns3::SatStatsPacketCollisionHelper::GetTypeId (void) static
inherited from ObjectBase base class
Definition at line 69 of file satellite-stats-packet-collision-helper.cc.
GetValidCarrierType()
SatPhyRxCarrier::CarrierType ns3::SatStatsPacketCollisionHelper::GetValidCarrierType () const inline
Get the valid carrier type.
Returns
the valid carrier type
Definition at line 80 of file satellite-stats-packet-collision-helper.h.
References m_carrierType.
Referenced by ns3::SatStatsFeederPacketCollisionHelper::DoInstall(), and ns3::SatStatsUserPacketCollisionHelper::DoInstall().
SaveAddressAndIdentifier()
void ns3::SatStatsPacketCollisionHelper::SaveAddressAndIdentifier (Ptr< Node > utNode) protected
Save the address and the proper identifier from the given UT node.
Parameters
utNode a UT node.
The address of the given node will be saved in the m_identifierMap member variable.
Definition at line 151 of file satellite-stats-packet-collision-helper.cc.
References ns3::SatStatsHelper::GetIdentifierForUt(), ns3::SatIdMapper::GetUtMacWithNode(), and m_identifierMap.
Referenced by ns3::SatStatsFeederPacketCollisionHelper::DoInstall(), and ns3::SatStatsUserPacketCollisionHelper::DoInstall().
SetTraceSourceName()
void ns3::SatStatsPacketCollisionHelper::SetTraceSourceName (std::string traceSourceName) protected
Parameters
traceSourceName
Definition at line 76 of file satellite-stats-packet-collision-helper.cc.
References m_traceSourceName.
Referenced by ns3::SatStatsFeederCrdsaPacketCollisionHelper::SatStatsFeederCrdsaPacketCollisionHelper(), ns3::SatStatsFeederEssaPacketCollisionHelper::SatStatsFeederEssaPacketCollisionHelper(), ns3::SatStatsFeederSlottedAlohaPacketCollisionHelper::SatStatsFeederSlottedAlohaPacketCollisionHelper(), ns3::SatStatsUserCrdsaPacketCollisionHelper::SatStatsUserCrdsaPacketCollisionHelper(), ns3::SatStatsUserEssaPacketCollisionHelper::SatStatsUserEssaPacketCollisionHelper(), and ns3::SatStatsUserSlottedAlohaPacketCollisionHelper::SatStatsUserSlottedAlohaPacketCollisionHelper().
SetValidCarrierType()
void ns3::SatStatsPacketCollisionHelper::SetValidCarrierType (SatPhyRxCarrier::CarrierType carrierType) inline protected
Set valid carrier type for this statistics helper type.
Parameters
carrierType
Definition at line 104 of file satellite-stats-packet-collision-helper.h.
References m_carrierType.
Referenced by ns3::SatStatsFeederCrdsaPacketCollisionHelper::SatStatsFeederCrdsaPacketCollisionHelper(), ns3::SatStatsFeederEssaPacketCollisionHelper::SatStatsFeederEssaPacketCollisionHelper(), ns3::SatStatsFeederSlottedAlohaPacketCollisionHelper::SatStatsFeederSlottedAlohaPacketCollisionHelper(), ns3::SatStatsUserCrdsaPacketCollisionHelper::SatStatsUserCrdsaPacketCollisionHelper(), ns3::SatStatsUserEssaPacketCollisionHelper::SatStatsUserEssaPacketCollisionHelper(), and ns3::SatStatsUserSlottedAlohaPacketCollisionHelper::SatStatsUserSlottedAlohaPacketCollisionHelper().
Member Data Documentation
m_carrierType
SatPhyRxCarrier::CarrierType ns3::SatStatsPacketCollisionHelper::m_carrierType private
Definition at line 116 of file satellite-stats-packet-collision-helper.h.
Referenced by GetValidCarrierType(), and SetValidCarrierType().
m_identifierMap
std::map<const Address, uint32_t> ns3::SatStatsPacketCollisionHelper::m_identifierMap protected
Map of address and the identifier associated with it (for forward link).
Definition at line 113 of file satellite-stats-packet-collision-helper.h.
Referenced by CollisionRxCallback(), and SaveAddressAndIdentifier().
m_terminalCollectors
CollectorMap ns3::SatStatsPacketCollisionHelper::m_terminalCollectors protected
Maintains a list of collectors created by this helper.
Definition at line 110 of file satellite-stats-packet-collision-helper.h.
Referenced by CollisionRxCallback(), ns3::SatStatsFeederPacketCollisionHelper::DoInstall(), and ns3::SatStatsUserPacketCollisionHelper::DoInstall().
m_traceSourceName
std::string ns3::SatStatsPacketCollisionHelper::m_traceSourceName private
Definition at line 118 of file satellite-stats-packet-collision-helper.h.
Referenced by GetTraceSourceName(), and SetTraceSourceName().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/stats/satellite-stats-packet-collision-helper.h
/builds/sns3/satellite/satellite/stats/satellite-stats-packet-collision-helper.cc