SNS3
ns3::SatLowerLayerServiceRaEntry Class Reference
The SatLowerLayerService class holds information of a satellite lower layer service RA entry.
#include "satellite-lower-layer-service.h"
Public Member Functions
SatLowerLayerServiceRaEntry ()
~SatLowerLayerServiceRaEntry ()
Destructor for SatLowerLayerServiceRaEntry.
Private Member Functions
double GetAverageNormalizedOfferedLoadThreshold () const
Get average normalized offered load threshold.
uint16_t GetBackOffProbability () const
Get back off probability.
uint16_t GetBackOffTimeInMilliSeconds () const
Get back off time in milliseconds.
uint16_t GetHighLoadBackOffProbability () const
Get high load back off probability.
uint16_t GetHighLoadBackOffTimeInMilliSeconds () const
Get high load back off time in milliseconds.
bool GetIsCrdsaAllowed () const
Get CRDSA allowance.
bool GetIsEssaAllowed () const
Get ESSA allowance.
bool GetIsSlottedAlohaAllowed () const
Get Slotted Aloha allowance.
uint8_t GetMaximumConsecutiveBlockAccessed () const
Get maximum consecutive block accessed.
uint8_t GetMaximumUniquePayloadPerBlock () const
Get maximum unique payload per block.
uint8_t GetMinimumIdleBlock () const
Get minimum idle block.
uint8_t GetNumberOfInstances () const
Get number of instances.
void SetAverageNormalizedOfferedLoadThreshold (double averageNormalizedOfferedLoadThreshold)
Set average normalized offered load threshold.
void SetBackOffProbability (uint16_t backOffProbability)
Set back off probability.
void SetBackOffTimeInMilliSeconds (uint16_t backOffTimeInMilliSeconds)
Set back off time in milliseconds.
void SetHighLoadBackOffProbability (uint16_t highLoadBackOffProbability)
Set high load back off probability.
void SetHighLoadBackOffTimeInMilliSeconds (uint16_t backOffTimeInMilliSeconds)
Set high load back off time in milliseconds.
void SetIsCrdsaAllowed (bool isCrdsaAllowed)
Set CRDSA allowance.
void SetIsEssaAllowed (bool isEssaAllowed)
Set ESSA allowance.
void SetIsSlottedAlohaAllowed (bool isSlottedAlohaAllowed)
Set Slotted Aloha allowance.
void SetMaximumConsecutiveBlockAccessed (uint8_t maxConsecutiveBlockAccessed)
Set maximum consecutive block accessed.
void SetMaximumUniquePayloadPerBlock (uint8_t maxUniquePayloadPerBlock)
Set maximum unique payload per block.
void SetMinimumIdleBlock (uint8_t minimumIdleBlock)
Set minimum idle block.
void SetNumberOfInstances (uint8_t numberOfInstances)
Set number of instances.
Private Attributes
double m_averageNormalizedOfferedLoadThreshold
uint16_t m_backOffProbability
uint16_t m_backOffTimeInMilliSeconds
uint16_t m_highLoadBackOffProbability
uint16_t m_highLoadBackOffTimeInMilliSeconds
bool m_isCrdsaAllowed
bool m_isEssaAllowed
bool m_isSlottedAlohaAllowed
uint8_t m_maxConsecutiveBlockAccessed
uint8_t m_maxUniquePayloadPerBlock
uint8_t m_minimumIdleBlock
uint8_t m_numberOfInstances
Friends
class SatLowerLayerServiceConf
Detailed Description
The SatLowerLayerService class holds information of a satellite lower layer service RA entry.
Definition at line 221 of file satellite-lower-layer-service.h.
Constructor & Destructor Documentation
SatLowerLayerServiceRaEntry()
ns3::SatLowerLayerServiceRaEntry::SatLowerLayerServiceRaEntry ()
Definition at line 58 of file satellite-lower-layer-service.cc.
~SatLowerLayerServiceRaEntry()
ns3::SatLowerLayerServiceRaEntry::~SatLowerLayerServiceRaEntry ()
Destructor for SatLowerLayerServiceRaEntry.
Definition at line 75 of file satellite-lower-layer-service.cc.
Member Function Documentation
GetAverageNormalizedOfferedLoadThreshold()
double ns3::SatLowerLayerServiceRaEntry::GetAverageNormalizedOfferedLoadThreshold () const inline private
Get average normalized offered load threshold.
Returns
Average normalized offered load threshold
Definition at line 413 of file satellite-lower-layer-service.h.
References m_averageNormalizedOfferedLoadThreshold.
Referenced by ns3::SatLowerLayerServiceConf::GetRaAverageNormalizedOfferedLoadThreshold().
GetBackOffProbability()
uint16_t ns3::SatLowerLayerServiceRaEntry::GetBackOffProbability () const inline private
Get back off probability.
Returns
Back off probability
Definition at line 353 of file satellite-lower-layer-service.h.
References m_backOffProbability.
Referenced by ns3::SatLowerLayerServiceConf::GetRaBackOffProbability().
GetBackOffTimeInMilliSeconds()
uint16_t ns3::SatLowerLayerServiceRaEntry::GetBackOffTimeInMilliSeconds () const inline private
Get back off time in milliseconds.
Returns
Back off time
Definition at line 313 of file satellite-lower-layer-service.h.
References m_backOffTimeInMilliSeconds.
Referenced by ns3::SatLowerLayerServiceConf::GetRaBackOffTimeInMilliSeconds().
GetHighLoadBackOffProbability()
uint16_t ns3::SatLowerLayerServiceRaEntry::GetHighLoadBackOffProbability () const inline private
Get high load back off probability.
Returns
High load back off probability
Definition at line 373 of file satellite-lower-layer-service.h.
References m_highLoadBackOffProbability.
Referenced by ns3::SatLowerLayerServiceConf::GetRaHighLoadBackOffProbability().
GetHighLoadBackOffTimeInMilliSeconds()
uint16_t ns3::SatLowerLayerServiceRaEntry::GetHighLoadBackOffTimeInMilliSeconds () const inline private
Get high load back off time in milliseconds.
Returns
Back off time
Definition at line 333 of file satellite-lower-layer-service.h.
References m_highLoadBackOffTimeInMilliSeconds.
Referenced by ns3::SatLowerLayerServiceConf::GetRaHighLoadBackOffTimeInMilliSeconds().
GetIsCrdsaAllowed()
bool ns3::SatLowerLayerServiceRaEntry::GetIsCrdsaAllowed () const inline private
Get CRDSA allowance.
Returns
Is CRDSA allowed
Definition at line 454 of file satellite-lower-layer-service.h.
References m_isCrdsaAllowed.
Referenced by ns3::SatLowerLayerServiceConf::GetRaIsCrdsaAllowed().
GetIsEssaAllowed()
bool ns3::SatLowerLayerServiceRaEntry::GetIsEssaAllowed () const inline private
Get ESSA allowance.
Returns
Is ESSA allowed
Definition at line 474 of file satellite-lower-layer-service.h.
References m_isEssaAllowed.
Referenced by ns3::SatLowerLayerServiceConf::GetRaIsEssaAllowed().
GetIsSlottedAlohaAllowed()
bool ns3::SatLowerLayerServiceRaEntry::GetIsSlottedAlohaAllowed () const inline private
Get Slotted Aloha allowance.
Returns
Is Slotted Aloha allowed
Definition at line 434 of file satellite-lower-layer-service.h.
References m_isSlottedAlohaAllowed.
Referenced by ns3::SatLowerLayerServiceConf::GetRaIsSlottedAlohaAllowed().
GetMaximumConsecutiveBlockAccessed()
uint8_t ns3::SatLowerLayerServiceRaEntry::GetMaximumConsecutiveBlockAccessed () const inline private
Get maximum consecutive block accessed.
Returns
Maximum consecutive block accessed
Definition at line 273 of file satellite-lower-layer-service.h.
References m_maxConsecutiveBlockAccessed.
Referenced by ns3::SatLowerLayerServiceConf::GetRaMaximumConsecutiveBlockAccessed().
GetMaximumUniquePayloadPerBlock()
uint8_t ns3::SatLowerLayerServiceRaEntry::GetMaximumUniquePayloadPerBlock () const inline private
Get maximum unique payload per block.
Returns
Maximum unique payload per block
Definition at line 253 of file satellite-lower-layer-service.h.
References m_maxUniquePayloadPerBlock.
Referenced by ns3::SatLowerLayerServiceConf::GetRaMaximumUniquePayloadPerBlock().
GetMinimumIdleBlock()
uint8_t ns3::SatLowerLayerServiceRaEntry::GetMinimumIdleBlock () const inline private
Get minimum idle block.
Returns
Minimum idle block
Definition at line 293 of file satellite-lower-layer-service.h.
References m_minimumIdleBlock.
Referenced by ns3::SatLowerLayerServiceConf::GetRaMinimumIdleBlock().
GetNumberOfInstances()
uint8_t ns3::SatLowerLayerServiceRaEntry::GetNumberOfInstances () const inline private
Get number of instances.
Returns
Number of instances
Definition at line 393 of file satellite-lower-layer-service.h.
References m_numberOfInstances.
Referenced by ns3::SatLowerLayerServiceConf::GetRaNumberOfInstances().
SetAverageNormalizedOfferedLoadThreshold()
void ns3::SatLowerLayerServiceRaEntry::SetAverageNormalizedOfferedLoadThreshold (double averageNormalizedOfferedLoadThreshold) inline private
Set average normalized offered load threshold.
Parameters
averageNormalizedOfferedLoadThreshold Average normalized offered load threshold
Definition at line 423 of file satellite-lower-layer-service.h.
References m_averageNormalizedOfferedLoadThreshold.
Referenced by ns3::SatLowerLayerServiceConf::SetRaAverageNormalizedOfferedLoadThreshold().
SetBackOffProbability()
void ns3::SatLowerLayerServiceRaEntry::SetBackOffProbability (uint16_t backOffProbability) inline private
Set back off probability.
Parameters
backOffProbability Back off probability
Definition at line 363 of file satellite-lower-layer-service.h.
References m_backOffProbability.
Referenced by ns3::SatLowerLayerServiceConf::SetRaBackOffProbability().
SetBackOffTimeInMilliSeconds()
void ns3::SatLowerLayerServiceRaEntry::SetBackOffTimeInMilliSeconds (uint16_t backOffTimeInMilliSeconds) inline private
Set back off time in milliseconds.
Parameters
backOffTimeInMilliSeconds Back off time
Definition at line 323 of file satellite-lower-layer-service.h.
References m_backOffTimeInMilliSeconds.
Referenced by ns3::SatLowerLayerServiceConf::SetRaBackOffTimeInMilliSeconds().
SetHighLoadBackOffProbability()
void ns3::SatLowerLayerServiceRaEntry::SetHighLoadBackOffProbability (uint16_t highLoadBackOffProbability) inline private
Set high load back off probability.
Parameters
highLoadBackOffProbability High load back off probability
Definition at line 383 of file satellite-lower-layer-service.h.
References m_highLoadBackOffProbability.
Referenced by ns3::SatLowerLayerServiceConf::SetRaHighLoadBackOffProbability().
SetHighLoadBackOffTimeInMilliSeconds()
void ns3::SatLowerLayerServiceRaEntry::SetHighLoadBackOffTimeInMilliSeconds (uint16_t backOffTimeInMilliSeconds) inline private
Set high load back off time in milliseconds.
Parameters
backOffTimeInMilliSeconds Back off time
Definition at line 343 of file satellite-lower-layer-service.h.
References m_highLoadBackOffTimeInMilliSeconds.
Referenced by ns3::SatLowerLayerServiceConf::SetRaHighLoadBackOffTimeInMilliSeconds().
SetIsCrdsaAllowed()
void ns3::SatLowerLayerServiceRaEntry::SetIsCrdsaAllowed (bool isCrdsaAllowed) inline private
Set CRDSA allowance.
Parameters
isCrdsaAllowed Is CRDSA allowed
Definition at line 464 of file satellite-lower-layer-service.h.
References m_isCrdsaAllowed.
Referenced by ns3::SatLowerLayerServiceConf::SetRaIsCrdsaAllowed().
SetIsEssaAllowed()
void ns3::SatLowerLayerServiceRaEntry::SetIsEssaAllowed (bool isEssaAllowed) inline private
Set ESSA allowance.
Parameters
isEssaAllowed Is ESSA allowed
Definition at line 484 of file satellite-lower-layer-service.h.
References m_isEssaAllowed.
Referenced by ns3::SatLowerLayerServiceConf::SetRaIsEssaAllowed().
SetIsSlottedAlohaAllowed()
void ns3::SatLowerLayerServiceRaEntry::SetIsSlottedAlohaAllowed (bool isSlottedAlohaAllowed) inline private
Set Slotted Aloha allowance.
Parameters
isSlottedAlohaAllowed Is Slotted Aloha allowed
Definition at line 444 of file satellite-lower-layer-service.h.
References m_isSlottedAlohaAllowed.
Referenced by ns3::SatLowerLayerServiceConf::SetRaIsSlottedAlohaAllowed().
SetMaximumConsecutiveBlockAccessed()
void ns3::SatLowerLayerServiceRaEntry::SetMaximumConsecutiveBlockAccessed (uint8_t maxConsecutiveBlockAccessed) inline private
Set maximum consecutive block accessed.
Parameters
maxConsecutiveBlockAccessed Maximum consecutive block accessed
Definition at line 283 of file satellite-lower-layer-service.h.
References m_maxConsecutiveBlockAccessed.
Referenced by ns3::SatLowerLayerServiceConf::SetRaMaximumConsecutiveBlockAccessed().
SetMaximumUniquePayloadPerBlock()
void ns3::SatLowerLayerServiceRaEntry::SetMaximumUniquePayloadPerBlock (uint8_t maxUniquePayloadPerBlock) inline private
Set maximum unique payload per block.
Parameters
maxUniquePayloadPerBlock Maximum unique payload per block
Definition at line 263 of file satellite-lower-layer-service.h.
References m_maxUniquePayloadPerBlock.
Referenced by ns3::SatLowerLayerServiceConf::SetRaMaximumUniquePayloadPerBlock().
SetMinimumIdleBlock()
void ns3::SatLowerLayerServiceRaEntry::SetMinimumIdleBlock (uint8_t minimumIdleBlock) inline private
Set minimum idle block.
Parameters
minimumIdleBlock Minimum idle block
Definition at line 303 of file satellite-lower-layer-service.h.
References m_minimumIdleBlock.
Referenced by ns3::SatLowerLayerServiceConf::SetRaMinimumIdleBlock().
SetNumberOfInstances()
void ns3::SatLowerLayerServiceRaEntry::SetNumberOfInstances (uint8_t numberOfInstances) inline private
Set number of instances.
Parameters
numberOfInstances Number of instances
Definition at line 403 of file satellite-lower-layer-service.h.
References m_numberOfInstances.
Referenced by ns3::SatLowerLayerServiceConf::SetRaNumberOfInstances().
Friends And Related Function Documentation
SatLowerLayerServiceConf
friend class SatLowerLayerServiceConf friend
Definition at line 224 of file satellite-lower-layer-service.h.
Member Data Documentation
m_averageNormalizedOfferedLoadThreshold
double ns3::SatLowerLayerServiceRaEntry::m_averageNormalizedOfferedLoadThreshold private
Definition at line 243 of file satellite-lower-layer-service.h.
Referenced by GetAverageNormalizedOfferedLoadThreshold(), and SetAverageNormalizedOfferedLoadThreshold().
m_backOffProbability
uint16_t ns3::SatLowerLayerServiceRaEntry::m_backOffProbability private
Definition at line 240 of file satellite-lower-layer-service.h.
Referenced by GetBackOffProbability(), and SetBackOffProbability().
m_backOffTimeInMilliSeconds
uint16_t ns3::SatLowerLayerServiceRaEntry::m_backOffTimeInMilliSeconds private
Definition at line 238 of file satellite-lower-layer-service.h.
Referenced by GetBackOffTimeInMilliSeconds(), and SetBackOffTimeInMilliSeconds().
m_highLoadBackOffProbability
uint16_t ns3::SatLowerLayerServiceRaEntry::m_highLoadBackOffProbability private
Definition at line 241 of file satellite-lower-layer-service.h.
Referenced by GetHighLoadBackOffProbability(), and SetHighLoadBackOffProbability().
m_highLoadBackOffTimeInMilliSeconds
uint16_t ns3::SatLowerLayerServiceRaEntry::m_highLoadBackOffTimeInMilliSeconds private
Definition at line 239 of file satellite-lower-layer-service.h.
Referenced by GetHighLoadBackOffTimeInMilliSeconds(), and SetHighLoadBackOffTimeInMilliSeconds().
m_isCrdsaAllowed
bool ns3::SatLowerLayerServiceRaEntry::m_isCrdsaAllowed private
Definition at line 244 of file satellite-lower-layer-service.h.
Referenced by GetIsCrdsaAllowed(), and SetIsCrdsaAllowed().
m_isEssaAllowed
bool ns3::SatLowerLayerServiceRaEntry::m_isEssaAllowed private
Definition at line 246 of file satellite-lower-layer-service.h.
Referenced by GetIsEssaAllowed(), and SetIsEssaAllowed().
m_isSlottedAlohaAllowed
bool ns3::SatLowerLayerServiceRaEntry::m_isSlottedAlohaAllowed private
Definition at line 245 of file satellite-lower-layer-service.h.
Referenced by GetIsSlottedAlohaAllowed(), and SetIsSlottedAlohaAllowed().
m_maxConsecutiveBlockAccessed
uint8_t ns3::SatLowerLayerServiceRaEntry::m_maxConsecutiveBlockAccessed private
Definition at line 236 of file satellite-lower-layer-service.h.
Referenced by GetMaximumConsecutiveBlockAccessed(), and SetMaximumConsecutiveBlockAccessed().
m_maxUniquePayloadPerBlock
uint8_t ns3::SatLowerLayerServiceRaEntry::m_maxUniquePayloadPerBlock private
Definition at line 235 of file satellite-lower-layer-service.h.
Referenced by GetMaximumUniquePayloadPerBlock(), and SetMaximumUniquePayloadPerBlock().
m_minimumIdleBlock
uint8_t ns3::SatLowerLayerServiceRaEntry::m_minimumIdleBlock private
Definition at line 237 of file satellite-lower-layer-service.h.
Referenced by GetMinimumIdleBlock(), and SetMinimumIdleBlock().
m_numberOfInstances
uint8_t ns3::SatLowerLayerServiceRaEntry::m_numberOfInstances private
Definition at line 242 of file satellite-lower-layer-service.h.
Referenced by GetNumberOfInstances(), and SetNumberOfInstances().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-lower-layer-service.h
/builds/sns3/satellite/satellite/model/satellite-lower-layer-service.cc