SNS3
ns3::SatStatsWindowLoadHelper Class Reference abstract
Satellite Statistics
Abstract class inherited by SatStatsRtnFeederWindowLoadHelper.
#include "satellite-stats-window-load-helper.h"
Public Member Functions
SatStatsWindowLoadHelper (Ptr< const SatHelper > satHelper)
virtual ~SatStatsWindowLoadHelper ()
/ Destructor.
Callback< void, double > GetTraceSinkCallback () const
void InstallProbes ()
Set up several probes or other means of listeners and connect them to the collectors.
void WindowLoadCallback (double windowLoad)
Receive inputs from trace sources and forward them to the collector.
Public Member Functions inherited from ns3::SatStatsHelper
SatStatsHelper (Ptr< const SatHelper > satHelper)
Creates a new helper instance.
virtual ~SatStatsHelper ()
/ Destructor.
IdentifierType_t GetIdentifierType () const
std::string GetName () const
OutputType_t GetOutputType () const
Ptr< const SatHelper > GetSatHelper () const
void Install ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
bool IsInstalled () const
void SetIdentifierType (IdentifierType_t identifierType)
void SetName (std::string name)
void SetOutputType (OutputType_t outputType)
Static Public Member Functions
static TypeId GetTypeId ()
inherited from ObjectBase base class
Static Public Member Functions inherited from ns3::SatStatsHelper
static std::string GetIdentifierTypeName (IdentifierType_t identifierType)
static std::string GetOutputTypeName (OutputType_t outputType)
static TypeId GetTypeId ()
inherited from ObjectBase base class
Protected Member Functions
void DoInstall ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
virtual void DoInstallProbes ()=0
Protected Member Functions inherited from ns3::SatStatsHelper
Ptr< DataCollectionObject > CreateAggregator (std::string aggregatorTypeId, std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue())
Create the aggregator according to the output type.
uint32_t CreateCollectorPerIdentifier (CollectorMap &collectorMap) const
Create one collector instance for each identifier in the simulation.
virtual std::string GetDistributionHeading (std::string dataLabel) const
uint32_t GetGwId (Ptr< Node > gwNode) const
uint32_t GetIdentifierForBeam (uint32_t satId, uint32_t beamId) const
uint32_t GetIdentifierForGroup (uint32_t groupId) const
uint32_t GetIdentifierForGw (Ptr< Node > gwNode) const
uint32_t GetIdentifierForIsl (Ptr< Node > satNodeSrc, Ptr< Node > satNodeDst) const
uint32_t GetIdentifierForSat (Ptr< Node > satNode) const
uint32_t GetIdentifierForUt (Ptr< Node > utNode) const
uint32_t GetIdentifierForUtUser (Ptr< Node > utUserNode) const
virtual std::string GetIdentifierHeading (std::string dataLabel) const
virtual std::string GetOutputFileName () const
Compute the path and file name where statistics output should be written to.
virtual std::string GetOutputPath () const
uint32_t GetSatId (Ptr< Node > satNode) const
virtual std::string GetTimeHeading (std::string dataLabel) const
uint32_t GetUtId (Ptr< Node > utNode) const
uint32_t GetUtUserId (Ptr< Node > utUserNode) const
Protected Attributes
Ptr< DataCollectionObject > m_aggregator
The aggregator created by this helper.
Ptr< DataCollectionObject > m_collector
The collector created by this helper.
Private Attributes
Callback< void, double > m_traceSinkCallback
Additional Inherited Members
Public Types inherited from ns3::SatStatsHelper
enum IdentifierType_t {
IDENTIFIER_GLOBAL = 0 , IDENTIFIER_GW , IDENTIFIER_BEAM , IDENTIFIER_UT ,
IDENTIFIER_UT_USER , IDENTIFIER_SLICE , IDENTIFIER_GROUP , IDENTIFIER_SAT ,
IDENTIFIER_ISL
}
Possible categorization of statistics output.
enum OutputType_t {
OUTPUT_NONE = 0 , OUTPUT_SCALAR_FILE , OUTPUT_SCATTER_FILE , OUTPUT_HISTOGRAM_FILE ,
OUTPUT_PDF_FILE , OUTPUT_CDF_FILE , OUTPUT_SCALAR_PLOT , OUTPUT_SCATTER_PLOT ,
OUTPUT_HISTOGRAM_PLOT , OUTPUT_PDF_PLOT , OUTPUT_CDF_PLOT
}
Possible types and formats of statistics output.
Static Protected Member Functions inherited from ns3::SatStatsHelper
static NetDeviceContainer GetGwSatNetDevice (Ptr< Node > gwNode)
static Ptr< NetDevice > GetSatSatGeoNetDevice (Ptr< Node > satNode)
static Ptr< NetDevice > GetUtSatNetDevice (Ptr< Node > utNode)
Detailed Description
Abstract class inherited by SatStatsRtnFeederWindowLoadHelper.
Definition at line 42 of file satellite-stats-window-load-helper.h.
Constructor & Destructor Documentation
SatStatsWindowLoadHelper()
ns3::SatStatsWindowLoadHelper::SatStatsWindowLoadHelper (Ptr< const SatHelper > satHelper)
Definition at line 52 of file satellite-stats-window-load-helper.cc.
~SatStatsWindowLoadHelper()
ns3::SatStatsWindowLoadHelper::~SatStatsWindowLoadHelper () virtual
/ Destructor.
Definition at line 59 of file satellite-stats-window-load-helper.cc.
Member Function Documentation
DoInstall()
void ns3::SatStatsWindowLoadHelper::DoInstall () protected virtual
Install the probes, collectors, and aggregators necessary to produce the statistics output.
An abstract method of SatStatsHelper which must be implemented by child classes. It will be invoked by Install().
Todo:
Add support for boxes in Gnuplot.
Implements ns3::SatStatsHelper.
Definition at line 122 of file satellite-stats-window-load-helper.cc.
References ns3::SatStatsHelper::CreateAggregator(), ns3::SatStatsHelper::GetDistributionHeading(), ns3::SatStatsHelper::GetIdentifierHeading(), ns3::SatStatsHelper::GetName(), ns3::SatStatsHelper::GetOutputFileName(), ns3::SatStatsHelper::GetOutputPath(), ns3::SatStatsHelper::GetOutputType(), ns3::SatStatsHelper::GetOutputTypeName(), ns3::SatStatsHelper::GetTimeHeading(), InstallProbes(), m_aggregator, m_collector, ns3::SatStatsHelper::OUTPUT_CDF_FILE, ns3::SatStatsHelper::OUTPUT_CDF_PLOT, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_FILE, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_PLOT, ns3::SatStatsHelper::OUTPUT_NONE, ns3::SatStatsHelper::OUTPUT_PDF_FILE, ns3::SatStatsHelper::OUTPUT_PDF_PLOT, ns3::SatStatsHelper::OUTPUT_SCALAR_FILE, ns3::SatStatsHelper::OUTPUT_SCALAR_PLOT, ns3::SatStatsHelper::OUTPUT_SCATTER_FILE, and ns3::SatStatsHelper::OUTPUT_SCATTER_PLOT.
DoInstallProbes()
virtual void ns3::SatStatsWindowLoadHelper::DoInstallProbes () protected pure virtual
Implemented in ns3::SatStatsRtnFeederWindowLoadHelper.
Referenced by InstallProbes().
GetTraceSinkCallback()
Callback< void, double > ns3::SatStatsWindowLoadHelper::GetTraceSinkCallback () const
Returns
Definition at line 116 of file satellite-stats-window-load-helper.cc.
References m_traceSinkCallback.
Referenced by ns3::SatStatsRtnFeederWindowLoadHelper::DoInstallProbes().
GetTypeId()
TypeId ns3::SatStatsWindowLoadHelper::GetTypeId (void) static
inherited from ObjectBase base class
Definition at line 65 of file satellite-stats-window-load-helper.cc.
InstallProbes()
void ns3::SatStatsWindowLoadHelper::InstallProbes ()
Set up several probes or other means of listeners and connect them to the collectors.
Definition at line 305 of file satellite-stats-window-load-helper.cc.
References DoInstallProbes().
Referenced by DoInstall().
WindowLoadCallback()
void ns3::SatStatsWindowLoadHelper::WindowLoadCallback (double windowLoad)
Receive inputs from trace sources and forward them to the collector.
Parameters
windowLoad the normalized window load in bps/Hz.
Definition at line 72 of file satellite-stats-window-load-helper.cc.
References ns3::SatStatsHelper::GetOutputType(), ns3::SatStatsHelper::GetOutputTypeName(), m_collector, ns3::SatStatsHelper::OUTPUT_CDF_FILE, ns3::SatStatsHelper::OUTPUT_CDF_PLOT, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_FILE, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_PLOT, ns3::SatStatsHelper::OUTPUT_PDF_FILE, ns3::SatStatsHelper::OUTPUT_PDF_PLOT, ns3::SatStatsHelper::OUTPUT_SCALAR_FILE, ns3::SatStatsHelper::OUTPUT_SCALAR_PLOT, ns3::SatStatsHelper::OUTPUT_SCATTER_FILE, and ns3::SatStatsHelper::OUTPUT_SCATTER_PLOT.
Member Data Documentation
m_aggregator
Ptr<DataCollectionObject> ns3::SatStatsWindowLoadHelper::m_aggregator protected
The aggregator created by this helper.
Definition at line 88 of file satellite-stats-window-load-helper.h.
Referenced by DoInstall().
m_collector
Ptr<DataCollectionObject> ns3::SatStatsWindowLoadHelper::m_collector protected
The collector created by this helper.
Definition at line 85 of file satellite-stats-window-load-helper.h.
Referenced by DoInstall(), and WindowLoadCallback().
m_traceSinkCallback
Callback<void, double> ns3::SatStatsWindowLoadHelper::m_traceSinkCallback private
Definition at line 92 of file satellite-stats-window-load-helper.h.
Referenced by GetTraceSinkCallback().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/stats/satellite-stats-window-load-helper.h
/builds/sns3/satellite/satellite/stats/satellite-stats-window-load-helper.cc