SNS3
ns3::SatBeamUserInfo Class Reference
Class that holds information for each beam regarding UTs and their users camped in each beam.
#include "satellite-beam-user-info.h"
Public Member Functions
SatBeamUserInfo ()
Default constructor for SatBeamUserInfo enables creating an empty information structure.
SatBeamUserInfo (uint32_t utCount, uint32_t userCountPerUt)
Constructor for SatBeamUserInfo which allows creating a group of UT information structures with each UT having the same number of users.
virtual ~SatBeamUserInfo ()
Destructor for SatBeamUserInfo.
void AppendUt (uint32_t userCount)
Appends new UT to end of the list with given user count for the appended UT.
std::vector< std::pair< GeoCoordinate, uint32_t > > GetPositions ()
uint32_t GetUtCount () const
uint32_t GetUtUserCount (uint32_t utIndex) const
void SetPositions (std::vector< std::pair< GeoCoordinate, uint32_t >> positions)
Set the list of custom positions to create, and associated group.
void SetUtUserCount (uint32_t utIndex, uint32_t userCount)
Sets user count for the UT with given uIndex.
Private Attributes
std::vector< std::pair< GeoCoordinate, uint32_t > > m_positions
std::vector< uint32_t > m_userCount
Detailed Description
Class that holds information for each beam regarding UTs and their users camped in each beam.
Default constructor enables creating an empty information structure. The developer needs to Append individual UTs with individual number of users in each UT by calling the method AppendUt().
The second constructor allows creating a group of UT information structures with each UT having the same number of users.
Definition at line 43 of file satellite-beam-user-info.h.
Constructor & Destructor Documentation
SatBeamUserInfo() [1/2]
ns3::SatBeamUserInfo::SatBeamUserInfo ()
Default constructor for SatBeamUserInfo enables creating an empty information structure.
Definition at line 31 of file satellite-beam-user-info.cc.
SatBeamUserInfo() [2/2]
ns3::SatBeamUserInfo::SatBeamUserInfo (uint32_t utCount, uint32_t userCountPerUt)
Constructor for SatBeamUserInfo which allows creating a group of UT information structures with each UT having the same number of users.
Parameters
utCount UT count of the beam (can be added later by method AddUt)
userCountPerUt User count of the UTs (can be changed for the specific UT by method SetUtUserCount)
Definition at line 36 of file satellite-beam-user-info.cc.
References m_userCount.
~SatBeamUserInfo()
virtual ns3::SatBeamUserInfo::~SatBeamUserInfo () inline virtual
Destructor for SatBeamUserInfo.
Definition at line 64 of file satellite-beam-user-info.h.
Member Function Documentation
AppendUt()
void ns3::SatBeamUserInfo::AppendUt (uint32_t userCount)
Appends new UT to end of the list with given user count for the appended UT.
Parameters
userCount Number of users under the appended UT. Minimum value is 1.
Definition at line 78 of file satellite-beam-user-info.cc.
References m_userCount.
Referenced by ns3::SatHelper::CreateLargerScenario(), ns3::SimulationHelper::CreateSatScenario(), and ScenarioCreationUser::DoRun().
GetPositions()
std::vector< std::pair< GeoCoordinate, uint32_t > > ns3::SatBeamUserInfo::GetPositions ()
Returns
Get the list of custom positions to create, and associated group
Definition at line 94 of file satellite-beam-user-info.cc.
References m_positions.
GetUtCount()
uint32_t ns3::SatBeamUserInfo::GetUtCount () const
Returns
number of UTs in beam.
Definition at line 50 of file satellite-beam-user-info.cc.
References m_userCount.
GetUtUserCount()
uint32_t ns3::SatBeamUserInfo::GetUtUserCount (uint32_t utIndex) const
Parameters
utIndex index of the UT. Possible indexes are 0 to value -1 returned by GetUtCount
Returns
number of users in a UT.
Definition at line 58 of file satellite-beam-user-info.cc.
References m_userCount.
SetPositions()
void ns3::SatBeamUserInfo::SetPositions (std::vector< std::pair< GeoCoordinate, uint32_t >> positions)
Set the list of custom positions to create, and associated group.
Definition at line 88 of file satellite-beam-user-info.cc.
References m_positions.
SetUtUserCount()
void ns3::SatBeamUserInfo::SetUtUserCount (uint32_t utIndex, uint32_t userCount)
Sets user count for the UT with given uIndex.
Parameters
utIndex index of the UT. Possible indexes are 0 to value -1 returned by GetUtCount.
userCount Number of users under the UT of with given utIndex. Minimum value is 1. If this is not called for the UT then default value (1) is used for the UT.
Definition at line 68 of file satellite-beam-user-info.cc.
References m_userCount.
Referenced by ns3::SatHelper::CreateLargerScenario().
Member Data Documentation
m_positions
std::vector<std::pair<GeoCoordinate, uint32_t> > ns3::SatBeamUserInfo::m_positions private
Definition at line 112 of file satellite-beam-user-info.h.
Referenced by GetPositions(), and SetPositions().
m_userCount
std::vector<uint32_t> ns3::SatBeamUserInfo::m_userCount private
Definition at line 109 of file satellite-beam-user-info.h.
Referenced by SatBeamUserInfo(), AppendUt(), GetUtCount(), GetUtUserCount(), and SetUtUserCount().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/helper/satellite-beam-user-info.h
/builds/sns3/satellite/satellite/helper/satellite-beam-user-info.cc