SNS3
ns3::SatEnums Class Reference abstract
SatEnums class is for simplifying the use of enumerators in the satellite module.
#include "satellite-enums.h"
Public Types
enum BbFrameUsageMode_t { SHORT_FRAMES , NORMAL_FRAMES , SHORT_AND_NORMAL_FRAMES }
BBFrame usage modes.
enum CarrierBandwidthType_t { ALLOCATED_BANDWIDTH , OCCUPIED_BANDWIDTH , EFFECTIVE_BANDWIDTH }
Types of bandwidth.
enum ChannelType_t {
UNKNOWN_CH = 0 , FORWARD_FEEDER_CH = 1 , FORWARD_USER_CH = 2 , RETURN_USER_CH = 3 ,
RETURN_FEEDER_CH = 4
}
Types of channel.
enum DvbVersion_t { DVB_S2 , DVB_S2X }
The scheduling algorithm used to fill the BBFrames.
enum FadingModel_t { FADING_OFF , FADING_TRACE , FADING_MARKOV }
Fading models.
enum FwdSchedulingAlgorithm_t { NO_TIME_SLICING , TIME_SLICING }
The scheduling algorithm used to fill the BBFrames.
enum IslArbiterType_t { UNICAST , ECMP }
Choose the arbiter to use to route packets on ISLs.
enum LinkResults_t { LR_RCS2 = 0 , LR_FSIM = 1 , LR_LORA = 2 }
Return link Link result types.
enum PacketType_t {
PACKET_TYPE_DEDICATED_ACCESS = 0 , PACKET_TYPE_SLOTTED_ALOHA = 1 , PACKET_TYPE_CRDSA = 2 , PACKET_TYPE_ESSA = 3 ,
PACKET_TYPE_LOGON = 4
}
Packet types.
enum PropagationDelayModel_t { PD_CONSTANT = 0 , PD_CONSTANT_SPEED }
Propagation delay model.
enum RandomAccessModel_t {
RA_MODEL_OFF = 0 , RA_MODEL_SLOTTED_ALOHA = 1 , RA_MODEL_CRDSA = 2 , RA_MODEL_RCS2_SPECIFICATION = 3 ,
RA_MODEL_MARSALA = 4 , RA_MODEL_ESSA = 5
}
The defined random access models.
enum RandomAccessTriggerType_t { RA_TRIGGER_TYPE_SLOTTED_ALOHA = 0 , RA_TRIGGER_TYPE_CRDSA = 1 , RA_TRIGGER_TYPE_ESSA = 2 }
The defined random access trigger types.
enum RandomAccessTxOpportunityType_t { RA_TX_OPPORTUNITY_DO_NOTHING = 0 , RA_TX_OPPORTUNITY_SLOTTED_ALOHA = 1 , RA_TX_OPPORTUNITY_CRDSA = 2 , RA_TX_OPPORTUNITY_ESSA = 3 }
Random access Tx opportunity types.
enum RbdcCapacityRequestAlgorithm_t { CR_RBDC_LEGACY = 0 }
enum RegenerationMode_t { TRANSPARENT , REGENERATION_PHY , REGENERATION_LINK , REGENERATION_NETWORK }
The regeneration mode used in satellites.
enum RxPowerCalculationMode_t { RX_PWR_CALCULATION = 0 , RX_PWR_INPUT_TRACE = 1 , RX_CNO_INPUT_TRACE = 2 }
Modes of Rx power calculation.
enum SatBbFrameType_t { UNDEFINED_FRAME = 0 , SHORT_FRAME = 1 , NORMAL_FRAME = 2 , DUMMY_FRAME = 3 }
BB frame type used in DVB-S2 FWD link.
enum SatCapacityAllocationCategory_t { DA_UNKNOWN = 0 , DA_RBDC = 1 , DA_VBDC = 2 , DA_AVBDC = 3 }
Definition for different types of Capacity Request (CR) messages.
enum SatFlowId_t {
CONTROL_FID = 0 , EF_FID = 1 , AF_FID = 2 , BE_FID = 3 ,
NUM_FIDS = 4
}
Lower layer flow identifiers.
enum SatLinkDir_t { LD_FORWARD = 0 , LD_RETURN = 1 , LD_UNDEFINED = 2 }
Link direction used for packet tracing.
enum SatLogLevel_t {
LL_ND = 0 , LL_LLC = 1 , LL_MAC = 2 , LL_PHY = 3 ,
LL_CH = 4
}
Log level used for packet tracing.
enum SatLoraNodeType_t {
DVB_GW , DVB_UT , LORA_GW , LORA_UT ,
GEO
}
Specifies standard used and the king of node.
enum SatModcod_t {
SAT_NONVALID_MODCOD = 0 , SAT_MODCOD_QPSK_1_TO_3 , SAT_MODCOD_QPSK_1_TO_2 , SAT_MODCOD_QPSK_3_TO_5 ,
SAT_MODCOD_QPSK_2_TO_3 , SAT_MODCOD_QPSK_3_TO_4 , SAT_MODCOD_QPSK_4_TO_5 , SAT_MODCOD_QPSK_5_TO_6 ,
SAT_MODCOD_QPSK_8_TO_9 , SAT_MODCOD_QPSK_9_TO_10 , SAT_MODCOD_8PSK_3_TO_5 , SAT_MODCOD_8PSK_2_TO_3 ,
SAT_MODCOD_8PSK_3_TO_4 , SAT_MODCOD_8PSK_5_TO_6 , SAT_MODCOD_8PSK_8_TO_9 , SAT_MODCOD_8PSK_9_TO_10 ,
SAT_MODCOD_16APSK_2_TO_3 , SAT_MODCOD_16APSK_3_TO_4 , SAT_MODCOD_16APSK_4_TO_5 , SAT_MODCOD_16APSK_5_TO_6 ,
SAT_MODCOD_16APSK_8_TO_9 , SAT_MODCOD_16APSK_9_TO_10 , SAT_MODCOD_16QAM_3_TO_4 , SAT_MODCOD_16QAM_5_TO_6 ,
SAT_MODCOD_32APSK_3_TO_4 , SAT_MODCOD_32APSK_4_TO_5 , SAT_MODCOD_32APSK_5_TO_6 , SAT_MODCOD_32APSK_8_TO_9 ,
SAT_MODCOD_BPSK_1_TO_3 , SAT_MODCOD_S2X_QPSK_11_TO_45_SHORT_NOPILOTS , SAT_MODCOD_S2X_QPSK_11_TO_45_SHORT_PILOTS , SAT_MODCOD_S2X_QPSK_1_TO_4_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_QPSK_1_TO_4_NORMAL_PILOTS , SAT_MODCOD_S2X_QPSK_1_TO_4_SHORT_NOPILOTS , SAT_MODCOD_S2X_QPSK_1_TO_4_SHORT_PILOTS , SAT_MODCOD_S2X_QPSK_4_TO_15_SHORT_NOPILOTS ,
SAT_MODCOD_S2X_QPSK_4_TO_15_SHORT_PILOTS , SAT_MODCOD_S2X_QPSK_13_TO_45_NORMAL_NOPILOTS , SAT_MODCOD_S2X_QPSK_13_TO_45_NORMAL_PILOTS , SAT_MODCOD_S2X_QPSK_14_TO_45_SHORT_NOPILOTS ,
SAT_MODCOD_S2X_QPSK_14_TO_45_SHORT_PILOTS , SAT_MODCOD_S2X_QPSK_1_TO_3_NORMAL_NOPILOTS , SAT_MODCOD_S2X_QPSK_1_TO_3_NORMAL_PILOTS , SAT_MODCOD_S2X_QPSK_1_TO_3_SHORT_NOPILOTS ,
SAT_MODCOD_S2X_QPSK_1_TO_3_SHORT_PILOTS , SAT_MODCOD_S2X_QPSK_2_TO_5_NORMAL_NOPILOTS , SAT_MODCOD_S2X_QPSK_2_TO_5_NORMAL_PILOTS , SAT_MODCOD_S2X_QPSK_2_TO_5_SHORT_NOPILOTS ,
SAT_MODCOD_S2X_QPSK_2_TO_5_SHORT_PILOTS , SAT_MODCOD_S2X_QPSK_9_TO_20_NORMAL_NOPILOTS , SAT_MODCOD_S2X_QPSK_9_TO_20_NORMAL_PILOTS , SAT_MODCOD_S2X_QPSK_7_TO_15_SHORT_NOPILOTS ,
SAT_MODCOD_S2X_QPSK_7_TO_15_SHORT_PILOTS , SAT_MODCOD_S2X_QPSK_1_TO_2_NORMAL_NOPILOTS , SAT_MODCOD_S2X_QPSK_1_TO_2_NORMAL_PILOTS , SAT_MODCOD_S2X_QPSK_1_TO_2_SHORT_NOPILOTS ,
SAT_MODCOD_S2X_QPSK_1_TO_2_SHORT_PILOTS , SAT_MODCOD_S2X_QPSK_8_TO_15_SHORT_NOPILOTS , SAT_MODCOD_S2X_QPSK_8_TO_15_SHORT_PILOTS , SAT_MODCOD_S2X_QPSK_11_TO_20_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_QPSK_11_TO_20_NORMAL_PILOTS , SAT_MODCOD_S2X_QPSK_3_TO_5_NORMAL_NOPILOTS , SAT_MODCOD_S2X_QPSK_3_TO_5_NORMAL_PILOTS , SAT_MODCOD_S2X_QPSK_3_TO_5_SHORT_NOPILOTS ,
SAT_MODCOD_S2X_QPSK_3_TO_5_SHORT_PILOTS , SAT_MODCOD_S2X_QPSK_2_TO_3_NORMAL_NOPILOTS , SAT_MODCOD_S2X_QPSK_2_TO_3_NORMAL_PILOTS , SAT_MODCOD_S2X_QPSK_2_TO_3_SHORT_NOPILOTS ,
SAT_MODCOD_S2X_QPSK_2_TO_3_SHORT_PILOTS , SAT_MODCOD_S2X_QPSK_32_TO_45_SHORT_NOPILOTS , SAT_MODCOD_S2X_QPSK_32_TO_45_SHORT_PILOTS , SAT_MODCOD_S2X_QPSK_3_TO_4_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_QPSK_3_TO_4_NORMAL_PILOTS , SAT_MODCOD_S2X_QPSK_3_TO_4_SHORT_NOPILOTS , SAT_MODCOD_S2X_QPSK_3_TO_4_SHORT_PILOTS , SAT_MODCOD_S2X_QPSK_4_TO_5_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_QPSK_4_TO_5_NORMAL_PILOTS , SAT_MODCOD_S2X_QPSK_4_TO_5_SHORT_NOPILOTS , SAT_MODCOD_S2X_QPSK_4_TO_5_SHORT_PILOTS , SAT_MODCOD_S2X_QPSK_5_TO_6_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_QPSK_5_TO_6_NORMAL_PILOTS , SAT_MODCOD_S2X_QPSK_5_TO_6_SHORT_NOPILOTS , SAT_MODCOD_S2X_QPSK_5_TO_6_SHORT_PILOTS , SAT_MODCOD_S2X_QPSK_8_TO_9_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_QPSK_8_TO_9_NORMAL_PILOTS , SAT_MODCOD_S2X_QPSK_8_TO_9_SHORT_NOPILOTS , SAT_MODCOD_S2X_QPSK_8_TO_9_SHORT_PILOTS , SAT_MODCOD_S2X_QPSK_9_TO_10_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_QPSK_9_TO_10_NORMAL_PILOTS , SAT_MODCOD_S2X_8PSK_7_TO_15_SHORT_NOPILOTS , SAT_MODCOD_S2X_8PSK_7_TO_15_SHORT_PILOTS , SAT_MODCOD_S2X_8PSK_8_TO_15_SHORT_NOPILOTS ,
SAT_MODCOD_S2X_8PSK_8_TO_15_SHORT_PILOTS , SAT_MODCOD_S2X_8PSK_26_TO_45_SHORT_NOPILOTS , SAT_MODCOD_S2X_8PSK_26_TO_45_SHORT_PILOTS , SAT_MODCOD_S2X_8PSK_3_TO_5_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_8PSK_3_TO_5_NORMAL_PILOTS , SAT_MODCOD_S2X_8PSK_3_TO_5_SHORT_NOPILOTS , SAT_MODCOD_S2X_8PSK_3_TO_5_SHORT_PILOTS , SAT_MODCOD_S2X_8PSK_23_TO_36_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_8PSK_23_TO_36_NORMAL_PILOTS , SAT_MODCOD_S2X_8PSK_2_TO_3_NORMAL_NOPILOTS , SAT_MODCOD_S2X_8PSK_2_TO_3_NORMAL_PILOTS , SAT_MODCOD_S2X_8PSK_2_TO_3_SHORT_NOPILOTS ,
SAT_MODCOD_S2X_8PSK_2_TO_3_SHORT_PILOTS , SAT_MODCOD_S2X_8PSK_25_TO_36_NORMAL_NOPILOTS , SAT_MODCOD_S2X_8PSK_25_TO_36_NORMAL_PILOTS , SAT_MODCOD_S2X_8PSK_32_TO_45_SHORT_NOPILOTS ,
SAT_MODCOD_S2X_8PSK_32_TO_45_SHORT_PILOTS , SAT_MODCOD_S2X_8PSK_13_TO_18_NORMAL_NOPILOTS , SAT_MODCOD_S2X_8PSK_13_TO_18_NORMAL_PILOTS , SAT_MODCOD_S2X_8PSK_3_TO_4_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_8PSK_3_TO_4_NORMAL_PILOTS , SAT_MODCOD_S2X_8PSK_3_TO_4_SHORT_NOPILOTS , SAT_MODCOD_S2X_8PSK_3_TO_4_SHORT_PILOTS , SAT_MODCOD_S2X_8PSK_5_TO_6_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_8PSK_5_TO_6_NORMAL_PILOTS , SAT_MODCOD_S2X_8PSK_5_TO_6_SHORT_NOPILOTS , SAT_MODCOD_S2X_8PSK_5_TO_6_SHORT_PILOTS , SAT_MODCOD_S2X_8PSK_8_TO_9_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_8PSK_8_TO_9_NORMAL_PILOTS , SAT_MODCOD_S2X_8PSK_8_TO_9_SHORT_NOPILOTS , SAT_MODCOD_S2X_8PSK_8_TO_9_SHORT_PILOTS , SAT_MODCOD_S2X_8PSK_9_TO_10_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_8PSK_9_TO_10_NORMAL_PILOTS , SAT_MODCOD_S2X_8APSK_5_TO_9_L_NORMAL_NOPILOTS , SAT_MODCOD_S2X_8APSK_5_TO_9_L_NORMAL_PILOTS , SAT_MODCOD_S2X_8APSK_26_TO_45_L_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_8APSK_26_TO_45_L_NORMAL_PILOTS , SAT_MODCOD_S2X_16APSK_7_TO_15_SHORT_NOPILOTS , SAT_MODCOD_S2X_16APSK_7_TO_15_SHORT_PILOTS , SAT_MODCOD_S2X_16APSK_1_TO_2_L_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_16APSK_1_TO_2_L_NORMAL_PILOTS , SAT_MODCOD_S2X_16APSK_8_TO_15_L_NORMAL_NOPILOTS , SAT_MODCOD_S2X_16APSK_8_TO_15_L_NORMAL_PILOTS , SAT_MODCOD_S2X_16APSK_8_TO_15_SHORT_NOPILOTS ,
SAT_MODCOD_S2X_16APSK_8_TO_15_SHORT_PILOTS , SAT_MODCOD_S2X_16APSK_5_TO_9_L_NORMAL_NOPILOTS , SAT_MODCOD_S2X_16APSK_5_TO_9_L_NORMAL_PILOTS , SAT_MODCOD_S2X_16APSK_26_TO_45_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_16APSK_26_TO_45_NORMAL_PILOTS , SAT_MODCOD_S2X_16APSK_26_TO_45_SHORT_NOPILOTS , SAT_MODCOD_S2X_16APSK_26_TO_45_SHORT_PILOTS , SAT_MODCOD_S2X_16APSK_3_TO_5_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_16APSK_3_TO_5_NORMAL_PILOTS , SAT_MODCOD_S2X_16APSK_3_TO_5_L_NORMAL_NOPILOTS , SAT_MODCOD_S2X_16APSK_3_TO_5_L_NORMAL_PILOTS , SAT_MODCOD_S2X_16APSK_3_TO_5_SHORT_NOPILOTS ,
SAT_MODCOD_S2X_16APSK_3_TO_5_SHORT_PILOTS , SAT_MODCOD_S2X_16APSK_28_TO_45_NORMAL_NOPILOTS , SAT_MODCOD_S2X_16APSK_28_TO_45_NORMAL_PILOTS , SAT_MODCOD_S2X_16APSK_23_TO_36_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_16APSK_23_TO_36_NORMAL_PILOTS , SAT_MODCOD_S2X_16APSK_2_TO_3_L_NORMAL_NOPILOTS , SAT_MODCOD_S2X_16APSK_2_TO_3_L_NORMAL_PILOTS , SAT_MODCOD_S2X_16APSK_2_TO_3_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_16APSK_2_TO_3_NORMAL_PILOTS , SAT_MODCOD_S2X_16APSK_2_TO_3_SHORT_NOPILOTS , SAT_MODCOD_S2X_16APSK_2_TO_3_SHORT_PILOTS , SAT_MODCOD_S2X_16APSK_25_TO_36_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_16APSK_25_TO_36_NORMAL_PILOTS , SAT_MODCOD_S2X_16APSK_32_TO_45_SHORT_NOPILOTS , SAT_MODCOD_S2X_16APSK_32_TO_45_SHORT_PILOTS , SAT_MODCOD_S2X_16APSK_13_TO_18_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_16APSK_13_TO_18_NORMAL_PILOTS , SAT_MODCOD_S2X_16APSK_3_TO_4_NORMAL_NOPILOTS , SAT_MODCOD_S2X_16APSK_3_TO_4_NORMAL_PILOTS , SAT_MODCOD_S2X_16APSK_3_TO_4_SHORT_NOPILOTS ,
SAT_MODCOD_S2X_16APSK_3_TO_4_SHORT_PILOTS , SAT_MODCOD_S2X_16APSK_7_TO_9_NORMAL_NOPILOTS , SAT_MODCOD_S2X_16APSK_7_TO_9_NORMAL_PILOTS , SAT_MODCOD_S2X_16APSK_4_TO_5_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_16APSK_4_TO_5_NORMAL_PILOTS , SAT_MODCOD_S2X_16APSK_4_TO_5_SHORT_NOPILOTS , SAT_MODCOD_S2X_16APSK_4_TO_5_SHORT_PILOTS , SAT_MODCOD_S2X_16APSK_5_TO_6_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_16APSK_5_TO_6_NORMAL_PILOTS , SAT_MODCOD_S2X_16APSK_5_TO_6_SHORT_NOPILOTS , SAT_MODCOD_S2X_16APSK_5_TO_6_SHORT_PILOTS , SAT_MODCOD_S2X_16APSK_77_TO_90_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_16APSK_77_TO_90_NORMAL_PILOTS , SAT_MODCOD_S2X_16APSK_8_TO_9_NORMAL_NOPILOTS , SAT_MODCOD_S2X_16APSK_8_TO_9_NORMAL_PILOTS , SAT_MODCOD_S2X_16APSK_8_TO_9_SHORT_NOPILOTS ,
SAT_MODCOD_S2X_16APSK_8_TO_9_SHORT_PILOTS , SAT_MODCOD_S2X_16APSK_9_TO_10_NORMAL_NOPILOTS , SAT_MODCOD_S2X_16APSK_9_TO_10_NORMAL_PILOTS , SAT_MODCOD_S2X_32APSK_2_TO_3_L_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_32APSK_2_TO_3_L_NORMAL_PILOTS , SAT_MODCOD_S2X_32APSK_2_TO_3_SHORT_NOPILOTS , SAT_MODCOD_S2X_32APSK_2_TO_3_SHORT_PILOTS , SAT_MODCOD_S2X_32APSK_32_TO_45_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_32APSK_32_TO_45_NORMAL_PILOTS , SAT_MODCOD_S2X_32APSK_32_TO_45_SHORT_NOPILOTS , SAT_MODCOD_S2X_32APSK_32_TO_45_SHORT_PILOTS , SAT_MODCOD_S2X_32APSK_11_TO_15_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_32APSK_11_TO_15_NORMAL_PILOTS , SAT_MODCOD_S2X_32APSK_3_TO_4_NORMAL_NOPILOTS , SAT_MODCOD_S2X_32APSK_3_TO_4_NORMAL_PILOTS , SAT_MODCOD_S2X_32APSK_3_TO_4_SHORT_NOPILOTS ,
SAT_MODCOD_S2X_32APSK_3_TO_4_SHORT_PILOTS , SAT_MODCOD_S2X_32APSK_7_TO_9_NORMAL_NOPILOTS , SAT_MODCOD_S2X_32APSK_7_TO_9_NORMAL_PILOTS , SAT_MODCOD_S2X_32APSK_4_TO_5_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_32APSK_4_TO_5_NORMAL_PILOTS , SAT_MODCOD_S2X_32APSK_4_TO_5_SHORT_NOPILOTS , SAT_MODCOD_S2X_32APSK_4_TO_5_SHORT_PILOTS , SAT_MODCOD_S2X_32APSK_5_TO_6_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_32APSK_5_TO_6_NORMAL_PILOTS , SAT_MODCOD_S2X_32APSK_5_TO_6_SHORT_NOPILOTS , SAT_MODCOD_S2X_32APSK_5_TO_6_SHORT_PILOTS , SAT_MODCOD_S2X_32APSK_8_TO_9_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_32APSK_8_TO_9_NORMAL_PILOTS , SAT_MODCOD_S2X_32APSK_8_TO_9_SHORT_NOPILOTS , SAT_MODCOD_S2X_32APSK_8_TO_9_SHORT_PILOTS , SAT_MODCOD_S2X_32APSK_9_TO_10_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_32APSK_9_TO_10_NORMAL_PILOTS , SAT_MODCOD_S2X_64APSK_32_TO_45_L_NORMAL_NOPILOTS , SAT_MODCOD_S2X_64APSK_32_TO_45_L_NORMAL_PILOTS , SAT_MODCOD_S2X_64APSK_11_TO_15_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_64APSK_11_TO_15_NORMAL_PILOTS , SAT_MODCOD_S2X_64APSK_7_TO_9_NORMAL_NOPILOTS , SAT_MODCOD_S2X_64APSK_7_TO_9_NORMAL_PILOTS , SAT_MODCOD_S2X_64APSK_4_TO_5_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_64APSK_4_TO_5_NORMAL_PILOTS , SAT_MODCOD_S2X_64APSK_5_TO_6_NORMAL_NOPILOTS , SAT_MODCOD_S2X_64APSK_5_TO_6_NORMAL_PILOTS , SAT_MODCOD_S2X_128APSK_3_TO_4_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_128APSK_3_TO_4_NORMAL_PILOTS , SAT_MODCOD_S2X_128APSK_7_TO_9_NORMAL_NOPILOTS , SAT_MODCOD_S2X_128APSK_7_TO_9_NORMAL_PILOTS , SAT_MODCOD_S2X_256APSK_29_TO_45_L_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_256APSK_29_TO_45_L_NORMAL_PILOTS , SAT_MODCOD_S2X_256APSK_2_TO_3_L_NORMAL_NOPILOTS , SAT_MODCOD_S2X_256APSK_2_TO_3_L_NORMAL_PILOTS , SAT_MODCOD_S2X_256APSK_31_TO_45_L_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_256APSK_31_TO_45_L_NORMAL_PILOTS , SAT_MODCOD_S2X_256APSK_32_TO_45_NORMAL_NOPILOTS , SAT_MODCOD_S2X_256APSK_32_TO_45_NORMAL_PILOTS , SAT_MODCOD_S2X_256APSK_11_TO_15_L_NORMAL_NOPILOTS ,
SAT_MODCOD_S2X_256APSK_11_TO_15_L_NORMAL_PILOTS , SAT_MODCOD_S2X_256APSK_3_TO_4_NORMAL_NOPILOTS , SAT_MODCOD_S2X_256APSK_3_TO_4_NORMAL_PILOTS
}
Modulation scheme and coding rate for DVB-S2.
enum SatNodeType_t {
NT_UT = 0 , NT_SAT = 1 , NT_GW = 2 , NT_NCC = 3 ,
NT_TER = 4 , NT_UNDEFINED = 5
}
Node type used for packet tracing.
enum SatPacketEvent_t { PACKET_SENT = 0 , PACKET_RECV = 1 , PACKET_ENQUE = 2 , PACKET_DROP = 3 }
Packet event used for packet tracing.
enum SatWaveFormBurstLength_t { UNKNOWN_BURST = 0 , SHORT_BURST = 1 , LONG_BURST = 2 , SHORT_AND_LONG_BURST = 3 }
Definition for different types of Capacity Request (CR) messages.
enum Standard_t { DVB , LORA }
The global standard used.
enum SuperframeAllocatorType_t { DEFAULT_SUPERFRAME_ALLOCATOR = 0 }
enum VbdcCapacityRequestAlgorithm_t { CR_VBDC_LEGACY = 0 }
Static Public Member Functions
static void GetAvailableBbFrameTypes (std::vector< SatBbFrameType_t > &frameTypes)
static void GetAvailableModcodsFwdLink (std::vector< SatModcod_t > &modcods)
static void GetAvailableModcodsFwdLinkS2X (std::vector< SatModcod_t > &modcods, SatEnums::BbFrameUsageMode_t type, bool pilots)
static void GetAvailableModcodsFwdLinkS2XNormalFrames (std::vector< SatModcod_t > &modcods, bool pilots)
static void GetAvailableModcodsFwdLinkS2XShortFrames (std::vector< SatModcod_t > &modcods, bool pilots)
static void GetAvailableModcodsRtnLink (std::vector< SatModcod_t > &modcods)
static std::string GetCapacityAllocationCategory (SatCapacityAllocationCategory_t cac)
static std::string GetChannelTypeName (ChannelType_t channelType)
static std::string GetFrameTypeName (SatBbFrameType_t frameType)
static std::string GetLinkDirName (SatLinkDir_t linkDir)
static std::string GetLogLevelName (SatLogLevel_t logLevel)
static SatModcod_t GetModcodFromName (const std::string name)
static std::string GetModcodTypeName (SatModcod_t modcod)
static std::string GetNodeTypeName (SatNodeType_t nodeType)
static std::string GetPacketEventName (SatPacketEvent_t packetEvent)
static std::string GetPacketTypeName (PacketType_t packetType)
static std::string GetRandomAccessModelName (RandomAccessModel_t model)
static std::string GetRandomAccessOpportunityTypeName (RandomAccessTxOpportunityType_t opportunityType)
static std::string GetRandomAccessTriggerTypeName (RandomAccessTriggerType_t triggerType)
static std::string GetRbdcCapacityRequestAlgorithmName (RbdcCapacityRequestAlgorithm_t rbdcAlgorithm)
static std::string GetVbdcCapacityRequestAlgorithmName (VbdcCapacityRequestAlgorithm_t vbdcAlgorithm)
Private Member Functions
virtual ~SatEnums ()=0
Destructor.
Detailed Description
SatEnums class is for simplifying the use of enumerators in the satellite module.
The enums specified in this class mainly consist of enums used in multiple classes.
Definition at line 41 of file satellite-enums.h.
Member Enumeration Documentation
BbFrameUsageMode_t
enum ns3::SatEnums::BbFrameUsageMode_t
BBFrame usage modes.
Enumerator
SHORT_FRAMES
SHORT_FRAMES.
NORMAL_FRAMES
NORMAL_FRAMES.
SHORT_AND_NORMAL_FRAMES
SHORT_AND_NORMAL_FRAMES.
Definition at line 163 of file satellite-enums.h.
CarrierBandwidthType_t
enum ns3::SatEnums::CarrierBandwidthType_t
Types of bandwidth.
Enumerator
ALLOCATED_BANDWIDTH
OCCUPIED_BANDWIDTH
EFFECTIVE_BANDWIDTH
Definition at line 71 of file satellite-enums.h.
ChannelType_t
enum ns3::SatEnums::ChannelType_t
Types of channel.
Enumerator
UNKNOWN_CH
FORWARD_FEEDER_CH
FORWARD_USER_CH
RETURN_USER_CH
RETURN_FEEDER_CH
Definition at line 48 of file satellite-enums.h.
DvbVersion_t
enum ns3::SatEnums::DvbVersion_t
The scheduling algorithm used to fill the BBFrames.
Enumerator
DVB_S2
DVB_S2X
Definition at line 144 of file satellite-enums.h.
FadingModel_t
enum ns3::SatEnums::FadingModel_t
Fading models.
Enumerator
FADING_OFF
FADING_TRACE
FADING_MARKOV
Definition at line 82 of file satellite-enums.h.
FwdSchedulingAlgorithm_t
enum ns3::SatEnums::FwdSchedulingAlgorithm_t
The scheduling algorithm used to fill the BBFrames.
Enumerator
NO_TIME_SLICING
TIME_SLICING
Definition at line 154 of file satellite-enums.h.
IslArbiterType_t
enum ns3::SatEnums::IslArbiterType_t
Choose the arbiter to use to route packets on ISLs.
Enumerator
UNICAST
ECMP
Definition at line 109 of file satellite-enums.h.
LinkResults_t
enum ns3::SatEnums::LinkResults_t
Return link Link result types.
These are used to define which type of waveforms are used to check link results on the return link.
Enumerator
LR_RCS2
LR_FSIM
LR_LORA
Definition at line 2268 of file satellite-enums.h.
PacketType_t
enum ns3::SatEnums::PacketType_t
Packet types.
These are used determine Rx side actions
Enumerator
PACKET_TYPE_DEDICATED_ACCESS
PACKET_TYPE_SLOTTED_ALOHA
PACKET_TYPE_CRDSA
PACKET_TYPE_ESSA
PACKET_TYPE_LOGON
Definition at line 2164 of file satellite-enums.h.
PropagationDelayModel_t
enum ns3::SatEnums::PropagationDelayModel_t
Propagation delay model.
Enumerator
PD_CONSTANT
PD_CONSTANT_SPEED
Definition at line 61 of file satellite-enums.h.
RandomAccessModel_t
enum ns3::SatEnums::RandomAccessModel_t
The defined random access models.
These define the implemented algorithms
Enumerator
RA_MODEL_OFF
RA_MODEL_SLOTTED_ALOHA
RA_MODEL_CRDSA
RA_MODEL_RCS2_SPECIFICATION
RA_MODEL_MARSALA
RA_MODEL_ESSA
Definition at line 2082 of file satellite-enums.h.
RandomAccessTriggerType_t
enum ns3::SatEnums::RandomAccessTriggerType_t
The defined random access trigger types.
These help determine which algorithm to use if multiple algorithms are enabled
Enumerator
RA_TRIGGER_TYPE_SLOTTED_ALOHA
RA_TRIGGER_TYPE_CRDSA
RA_TRIGGER_TYPE_ESSA
Definition at line 2049 of file satellite-enums.h.
RandomAccessTxOpportunityType_t
enum ns3::SatEnums::RandomAccessTxOpportunityType_t
Random access Tx opportunity types.
These are used to define to which algorithm the results provided by this module applies to
Enumerator
RA_TX_OPPORTUNITY_DO_NOTHING
RA_TX_OPPORTUNITY_SLOTTED_ALOHA
RA_TX_OPPORTUNITY_CRDSA
RA_TX_OPPORTUNITY_ESSA
Definition at line 2125 of file satellite-enums.h.
RbdcCapacityRequestAlgorithm_t
enum ns3::SatEnums::RbdcCapacityRequestAlgorithm_t
Enumerator
CR_RBDC_LEGACY
Definition at line 2203 of file satellite-enums.h.
RegenerationMode_t
enum ns3::SatEnums::RegenerationMode_t
The regeneration mode used in satellites.
It can be set for each link with different values.
Enumerator
TRANSPARENT
REGENERATION_PHY
REGENERATION_LINK
REGENERATION_NETWORK
Definition at line 94 of file satellite-enums.h.
RxPowerCalculationMode_t
enum ns3::SatEnums::RxPowerCalculationMode_t
Modes of Rx power calculation.
Enumerator
RX_PWR_CALCULATION
RX_PWR_INPUT_TRACE
RX_CNO_INPUT_TRACE
Definition at line 1849 of file satellite-enums.h.
SatBbFrameType_t
enum ns3::SatEnums::SatBbFrameType_t
BB frame type used in DVB-S2 FWD link.
Enumerator
UNDEFINED_FRAME
SHORT_FRAME
NORMAL_FRAME
DUMMY_FRAME
Definition at line 1744 of file satellite-enums.h.
SatCapacityAllocationCategory_t
enum ns3::SatEnums::SatCapacityAllocationCategory_t
Definition for different types of Capacity Request (CR) messages.
Enumerator
DA_UNKNOWN
DA_RBDC
DA_VBDC
DA_AVBDC
Definition at line 1806 of file satellite-enums.h.
SatFlowId_t
enum ns3::SatEnums::SatFlowId_t
Lower layer flow identifiers.
Enumerator
CONTROL_FID
EF_FID
AF_FID
BE_FID
NUM_FIDS
Definition at line 1783 of file satellite-enums.h.
SatLinkDir_t
enum ns3::SatEnums::SatLinkDir_t
Link direction used for packet tracing.
Enumerator
LD_FORWARD
LD_RETURN
LD_UNDEFINED
Definition at line 1973 of file satellite-enums.h.
SatLogLevel_t
enum ns3::SatEnums::SatLogLevel_t
Log level used for packet tracing.
Enumerator
LL_ND
LL_LLC
LL_MAC
LL_PHY
LL_CH
Definition at line 2007 of file satellite-enums.h.
SatLoraNodeType_t
enum ns3::SatEnums::SatLoraNodeType_t
Specifies standard used and the king of node.
Enumerator
DVB_GW
DVB_UT
LORA_GW
LORA_UT
GEO
Definition at line 131 of file satellite-enums.h.
SatModcod_t
enum ns3::SatEnums::SatModcod_t
Modulation scheme and coding rate for DVB-S2.
Enumerator
SAT_NONVALID_MODCOD
SAT_MODCOD_QPSK_1_TO_3
SAT_MODCOD_QPSK_1_TO_2
SAT_MODCOD_QPSK_3_TO_5
SAT_MODCOD_QPSK_2_TO_3
SAT_MODCOD_QPSK_3_TO_4
SAT_MODCOD_QPSK_4_TO_5
SAT_MODCOD_QPSK_5_TO_6
SAT_MODCOD_QPSK_8_TO_9
SAT_MODCOD_QPSK_9_TO_10
SAT_MODCOD_8PSK_3_TO_5
SAT_MODCOD_8PSK_2_TO_3
SAT_MODCOD_8PSK_3_TO_4
SAT_MODCOD_8PSK_5_TO_6
SAT_MODCOD_8PSK_8_TO_9
SAT_MODCOD_8PSK_9_TO_10
SAT_MODCOD_16APSK_2_TO_3
SAT_MODCOD_16APSK_3_TO_4
SAT_MODCOD_16APSK_4_TO_5
SAT_MODCOD_16APSK_5_TO_6
SAT_MODCOD_16APSK_8_TO_9
SAT_MODCOD_16APSK_9_TO_10
SAT_MODCOD_16QAM_3_TO_4
SAT_MODCOD_16QAM_5_TO_6
SAT_MODCOD_32APSK_3_TO_4
SAT_MODCOD_32APSK_4_TO_5
SAT_MODCOD_32APSK_5_TO_6
SAT_MODCOD_32APSK_8_TO_9
SAT_MODCOD_BPSK_1_TO_3
SAT_MODCOD_S2X_QPSK_11_TO_45_SHORT_NOPILOTS
SAT_MODCOD_S2X_QPSK_11_TO_45_SHORT_PILOTS
SAT_MODCOD_S2X_QPSK_1_TO_4_NORMAL_NOPILOTS
SAT_MODCOD_S2X_QPSK_1_TO_4_NORMAL_PILOTS
SAT_MODCOD_S2X_QPSK_1_TO_4_SHORT_NOPILOTS
SAT_MODCOD_S2X_QPSK_1_TO_4_SHORT_PILOTS
SAT_MODCOD_S2X_QPSK_4_TO_15_SHORT_NOPILOTS
SAT_MODCOD_S2X_QPSK_4_TO_15_SHORT_PILOTS
SAT_MODCOD_S2X_QPSK_13_TO_45_NORMAL_NOPILOTS
SAT_MODCOD_S2X_QPSK_13_TO_45_NORMAL_PILOTS
SAT_MODCOD_S2X_QPSK_14_TO_45_SHORT_NOPILOTS
SAT_MODCOD_S2X_QPSK_14_TO_45_SHORT_PILOTS
SAT_MODCOD_S2X_QPSK_1_TO_3_NORMAL_NOPILOTS
SAT_MODCOD_S2X_QPSK_1_TO_3_NORMAL_PILOTS
SAT_MODCOD_S2X_QPSK_1_TO_3_SHORT_NOPILOTS
SAT_MODCOD_S2X_QPSK_1_TO_3_SHORT_PILOTS
SAT_MODCOD_S2X_QPSK_2_TO_5_NORMAL_NOPILOTS
SAT_MODCOD_S2X_QPSK_2_TO_5_NORMAL_PILOTS
SAT_MODCOD_S2X_QPSK_2_TO_5_SHORT_NOPILOTS
SAT_MODCOD_S2X_QPSK_2_TO_5_SHORT_PILOTS
SAT_MODCOD_S2X_QPSK_9_TO_20_NORMAL_NOPILOTS
SAT_MODCOD_S2X_QPSK_9_TO_20_NORMAL_PILOTS
SAT_MODCOD_S2X_QPSK_7_TO_15_SHORT_NOPILOTS
SAT_MODCOD_S2X_QPSK_7_TO_15_SHORT_PILOTS
SAT_MODCOD_S2X_QPSK_1_TO_2_NORMAL_NOPILOTS
SAT_MODCOD_S2X_QPSK_1_TO_2_NORMAL_PILOTS
SAT_MODCOD_S2X_QPSK_1_TO_2_SHORT_NOPILOTS
SAT_MODCOD_S2X_QPSK_1_TO_2_SHORT_PILOTS
SAT_MODCOD_S2X_QPSK_8_TO_15_SHORT_NOPILOTS
SAT_MODCOD_S2X_QPSK_8_TO_15_SHORT_PILOTS
SAT_MODCOD_S2X_QPSK_11_TO_20_NORMAL_NOPILOTS
SAT_MODCOD_S2X_QPSK_11_TO_20_NORMAL_PILOTS
SAT_MODCOD_S2X_QPSK_3_TO_5_NORMAL_NOPILOTS
SAT_MODCOD_S2X_QPSK_3_TO_5_NORMAL_PILOTS
SAT_MODCOD_S2X_QPSK_3_TO_5_SHORT_NOPILOTS
SAT_MODCOD_S2X_QPSK_3_TO_5_SHORT_PILOTS
SAT_MODCOD_S2X_QPSK_2_TO_3_NORMAL_NOPILOTS
SAT_MODCOD_S2X_QPSK_2_TO_3_NORMAL_PILOTS
SAT_MODCOD_S2X_QPSK_2_TO_3_SHORT_NOPILOTS
SAT_MODCOD_S2X_QPSK_2_TO_3_SHORT_PILOTS
SAT_MODCOD_S2X_QPSK_32_TO_45_SHORT_NOPILOTS
SAT_MODCOD_S2X_QPSK_32_TO_45_SHORT_PILOTS
SAT_MODCOD_S2X_QPSK_3_TO_4_NORMAL_NOPILOTS
SAT_MODCOD_S2X_QPSK_3_TO_4_NORMAL_PILOTS
SAT_MODCOD_S2X_QPSK_3_TO_4_SHORT_NOPILOTS
SAT_MODCOD_S2X_QPSK_3_TO_4_SHORT_PILOTS
SAT_MODCOD_S2X_QPSK_4_TO_5_NORMAL_NOPILOTS
SAT_MODCOD_S2X_QPSK_4_TO_5_NORMAL_PILOTS
SAT_MODCOD_S2X_QPSK_4_TO_5_SHORT_NOPILOTS
SAT_MODCOD_S2X_QPSK_4_TO_5_SHORT_PILOTS
SAT_MODCOD_S2X_QPSK_5_TO_6_NORMAL_NOPILOTS
SAT_MODCOD_S2X_QPSK_5_TO_6_NORMAL_PILOTS
SAT_MODCOD_S2X_QPSK_5_TO_6_SHORT_NOPILOTS
SAT_MODCOD_S2X_QPSK_5_TO_6_SHORT_PILOTS
SAT_MODCOD_S2X_QPSK_8_TO_9_NORMAL_NOPILOTS
SAT_MODCOD_S2X_QPSK_8_TO_9_NORMAL_PILOTS
SAT_MODCOD_S2X_QPSK_8_TO_9_SHORT_NOPILOTS
SAT_MODCOD_S2X_QPSK_8_TO_9_SHORT_PILOTS
SAT_MODCOD_S2X_QPSK_9_TO_10_NORMAL_NOPILOTS
SAT_MODCOD_S2X_QPSK_9_TO_10_NORMAL_PILOTS
SAT_MODCOD_S2X_8PSK_7_TO_15_SHORT_NOPILOTS
SAT_MODCOD_S2X_8PSK_7_TO_15_SHORT_PILOTS
SAT_MODCOD_S2X_8PSK_8_TO_15_SHORT_NOPILOTS
SAT_MODCOD_S2X_8PSK_8_TO_15_SHORT_PILOTS
SAT_MODCOD_S2X_8PSK_26_TO_45_SHORT_NOPILOTS
SAT_MODCOD_S2X_8PSK_26_TO_45_SHORT_PILOTS
SAT_MODCOD_S2X_8PSK_3_TO_5_NORMAL_NOPILOTS
SAT_MODCOD_S2X_8PSK_3_TO_5_NORMAL_PILOTS
SAT_MODCOD_S2X_8PSK_3_TO_5_SHORT_NOPILOTS
SAT_MODCOD_S2X_8PSK_3_TO_5_SHORT_PILOTS
SAT_MODCOD_S2X_8PSK_23_TO_36_NORMAL_NOPILOTS
SAT_MODCOD_S2X_8PSK_23_TO_36_NORMAL_PILOTS
SAT_MODCOD_S2X_8PSK_2_TO_3_NORMAL_NOPILOTS
SAT_MODCOD_S2X_8PSK_2_TO_3_NORMAL_PILOTS
SAT_MODCOD_S2X_8PSK_2_TO_3_SHORT_NOPILOTS
SAT_MODCOD_S2X_8PSK_2_TO_3_SHORT_PILOTS
SAT_MODCOD_S2X_8PSK_25_TO_36_NORMAL_NOPILOTS
SAT_MODCOD_S2X_8PSK_25_TO_36_NORMAL_PILOTS
SAT_MODCOD_S2X_8PSK_32_TO_45_SHORT_NOPILOTS
SAT_MODCOD_S2X_8PSK_32_TO_45_SHORT_PILOTS
SAT_MODCOD_S2X_8PSK_13_TO_18_NORMAL_NOPILOTS
SAT_MODCOD_S2X_8PSK_13_TO_18_NORMAL_PILOTS
SAT_MODCOD_S2X_8PSK_3_TO_4_NORMAL_NOPILOTS
SAT_MODCOD_S2X_8PSK_3_TO_4_NORMAL_PILOTS
SAT_MODCOD_S2X_8PSK_3_TO_4_SHORT_NOPILOTS
SAT_MODCOD_S2X_8PSK_3_TO_4_SHORT_PILOTS
SAT_MODCOD_S2X_8PSK_5_TO_6_NORMAL_NOPILOTS
SAT_MODCOD_S2X_8PSK_5_TO_6_NORMAL_PILOTS
SAT_MODCOD_S2X_8PSK_5_TO_6_SHORT_NOPILOTS
SAT_MODCOD_S2X_8PSK_5_TO_6_SHORT_PILOTS
SAT_MODCOD_S2X_8PSK_8_TO_9_NORMAL_NOPILOTS
SAT_MODCOD_S2X_8PSK_8_TO_9_NORMAL_PILOTS
SAT_MODCOD_S2X_8PSK_8_TO_9_SHORT_NOPILOTS
SAT_MODCOD_S2X_8PSK_8_TO_9_SHORT_PILOTS
SAT_MODCOD_S2X_8PSK_9_TO_10_NORMAL_NOPILOTS
SAT_MODCOD_S2X_8PSK_9_TO_10_NORMAL_PILOTS
SAT_MODCOD_S2X_8APSK_5_TO_9_L_NORMAL_NOPILOTS
SAT_MODCOD_S2X_8APSK_5_TO_9_L_NORMAL_PILOTS
SAT_MODCOD_S2X_8APSK_26_TO_45_L_NORMAL_NOPILOTS
SAT_MODCOD_S2X_8APSK_26_TO_45_L_NORMAL_PILOTS
SAT_MODCOD_S2X_16APSK_7_TO_15_SHORT_NOPILOTS
SAT_MODCOD_S2X_16APSK_7_TO_15_SHORT_PILOTS
SAT_MODCOD_S2X_16APSK_1_TO_2_L_NORMAL_NOPILOTS
SAT_MODCOD_S2X_16APSK_1_TO_2_L_NORMAL_PILOTS
SAT_MODCOD_S2X_16APSK_8_TO_15_L_NORMAL_NOPILOTS
SAT_MODCOD_S2X_16APSK_8_TO_15_L_NORMAL_PILOTS
SAT_MODCOD_S2X_16APSK_8_TO_15_SHORT_NOPILOTS
SAT_MODCOD_S2X_16APSK_8_TO_15_SHORT_PILOTS
SAT_MODCOD_S2X_16APSK_5_TO_9_L_NORMAL_NOPILOTS
SAT_MODCOD_S2X_16APSK_5_TO_9_L_NORMAL_PILOTS
SAT_MODCOD_S2X_16APSK_26_TO_45_NORMAL_NOPILOTS
SAT_MODCOD_S2X_16APSK_26_TO_45_NORMAL_PILOTS
SAT_MODCOD_S2X_16APSK_26_TO_45_SHORT_NOPILOTS
SAT_MODCOD_S2X_16APSK_26_TO_45_SHORT_PILOTS
SAT_MODCOD_S2X_16APSK_3_TO_5_NORMAL_NOPILOTS
SAT_MODCOD_S2X_16APSK_3_TO_5_NORMAL_PILOTS
SAT_MODCOD_S2X_16APSK_3_TO_5_L_NORMAL_NOPILOTS
SAT_MODCOD_S2X_16APSK_3_TO_5_L_NORMAL_PILOTS
SAT_MODCOD_S2X_16APSK_3_TO_5_SHORT_NOPILOTS
SAT_MODCOD_S2X_16APSK_3_TO_5_SHORT_PILOTS
SAT_MODCOD_S2X_16APSK_28_TO_45_NORMAL_NOPILOTS
SAT_MODCOD_S2X_16APSK_28_TO_45_NORMAL_PILOTS
SAT_MODCOD_S2X_16APSK_23_TO_36_NORMAL_NOPILOTS
SAT_MODCOD_S2X_16APSK_23_TO_36_NORMAL_PILOTS
SAT_MODCOD_S2X_16APSK_2_TO_3_L_NORMAL_NOPILOTS
SAT_MODCOD_S2X_16APSK_2_TO_3_L_NORMAL_PILOTS
SAT_MODCOD_S2X_16APSK_2_TO_3_NORMAL_NOPILOTS
SAT_MODCOD_S2X_16APSK_2_TO_3_NORMAL_PILOTS
SAT_MODCOD_S2X_16APSK_2_TO_3_SHORT_NOPILOTS
SAT_MODCOD_S2X_16APSK_2_TO_3_SHORT_PILOTS
SAT_MODCOD_S2X_16APSK_25_TO_36_NORMAL_NOPILOTS
SAT_MODCOD_S2X_16APSK_25_TO_36_NORMAL_PILOTS
SAT_MODCOD_S2X_16APSK_32_TO_45_SHORT_NOPILOTS
SAT_MODCOD_S2X_16APSK_32_TO_45_SHORT_PILOTS
SAT_MODCOD_S2X_16APSK_13_TO_18_NORMAL_NOPILOTS
SAT_MODCOD_S2X_16APSK_13_TO_18_NORMAL_PILOTS
SAT_MODCOD_S2X_16APSK_3_TO_4_NORMAL_NOPILOTS
SAT_MODCOD_S2X_16APSK_3_TO_4_NORMAL_PILOTS
SAT_MODCOD_S2X_16APSK_3_TO_4_SHORT_NOPILOTS
SAT_MODCOD_S2X_16APSK_3_TO_4_SHORT_PILOTS
SAT_MODCOD_S2X_16APSK_7_TO_9_NORMAL_NOPILOTS
SAT_MODCOD_S2X_16APSK_7_TO_9_NORMAL_PILOTS
SAT_MODCOD_S2X_16APSK_4_TO_5_NORMAL_NOPILOTS
SAT_MODCOD_S2X_16APSK_4_TO_5_NORMAL_PILOTS
SAT_MODCOD_S2X_16APSK_4_TO_5_SHORT_NOPILOTS
SAT_MODCOD_S2X_16APSK_4_TO_5_SHORT_PILOTS
SAT_MODCOD_S2X_16APSK_5_TO_6_NORMAL_NOPILOTS
SAT_MODCOD_S2X_16APSK_5_TO_6_NORMAL_PILOTS
SAT_MODCOD_S2X_16APSK_5_TO_6_SHORT_NOPILOTS
SAT_MODCOD_S2X_16APSK_5_TO_6_SHORT_PILOTS
SAT_MODCOD_S2X_16APSK_77_TO_90_NORMAL_NOPILOTS
SAT_MODCOD_S2X_16APSK_77_TO_90_NORMAL_PILOTS
SAT_MODCOD_S2X_16APSK_8_TO_9_NORMAL_NOPILOTS
SAT_MODCOD_S2X_16APSK_8_TO_9_NORMAL_PILOTS
SAT_MODCOD_S2X_16APSK_8_TO_9_SHORT_NOPILOTS
SAT_MODCOD_S2X_16APSK_8_TO_9_SHORT_PILOTS
SAT_MODCOD_S2X_16APSK_9_TO_10_NORMAL_NOPILOTS
SAT_MODCOD_S2X_16APSK_9_TO_10_NORMAL_PILOTS
SAT_MODCOD_S2X_32APSK_2_TO_3_L_NORMAL_NOPILOTS
SAT_MODCOD_S2X_32APSK_2_TO_3_L_NORMAL_PILOTS
SAT_MODCOD_S2X_32APSK_2_TO_3_SHORT_NOPILOTS
SAT_MODCOD_S2X_32APSK_2_TO_3_SHORT_PILOTS
SAT_MODCOD_S2X_32APSK_32_TO_45_NORMAL_NOPILOTS
SAT_MODCOD_S2X_32APSK_32_TO_45_NORMAL_PILOTS
SAT_MODCOD_S2X_32APSK_32_TO_45_SHORT_NOPILOTS
SAT_MODCOD_S2X_32APSK_32_TO_45_SHORT_PILOTS
SAT_MODCOD_S2X_32APSK_11_TO_15_NORMAL_NOPILOTS
SAT_MODCOD_S2X_32APSK_11_TO_15_NORMAL_PILOTS
SAT_MODCOD_S2X_32APSK_3_TO_4_NORMAL_NOPILOTS
SAT_MODCOD_S2X_32APSK_3_TO_4_NORMAL_PILOTS
SAT_MODCOD_S2X_32APSK_3_TO_4_SHORT_NOPILOTS
SAT_MODCOD_S2X_32APSK_3_TO_4_SHORT_PILOTS
SAT_MODCOD_S2X_32APSK_7_TO_9_NORMAL_NOPILOTS
SAT_MODCOD_S2X_32APSK_7_TO_9_NORMAL_PILOTS
SAT_MODCOD_S2X_32APSK_4_TO_5_NORMAL_NOPILOTS
SAT_MODCOD_S2X_32APSK_4_TO_5_NORMAL_PILOTS
SAT_MODCOD_S2X_32APSK_4_TO_5_SHORT_NOPILOTS
SAT_MODCOD_S2X_32APSK_4_TO_5_SHORT_PILOTS
SAT_MODCOD_S2X_32APSK_5_TO_6_NORMAL_NOPILOTS
SAT_MODCOD_S2X_32APSK_5_TO_6_NORMAL_PILOTS
SAT_MODCOD_S2X_32APSK_5_TO_6_SHORT_NOPILOTS
SAT_MODCOD_S2X_32APSK_5_TO_6_SHORT_PILOTS
SAT_MODCOD_S2X_32APSK_8_TO_9_NORMAL_NOPILOTS
SAT_MODCOD_S2X_32APSK_8_TO_9_NORMAL_PILOTS
SAT_MODCOD_S2X_32APSK_8_TO_9_SHORT_NOPILOTS
SAT_MODCOD_S2X_32APSK_8_TO_9_SHORT_PILOTS
SAT_MODCOD_S2X_32APSK_9_TO_10_NORMAL_NOPILOTS
SAT_MODCOD_S2X_32APSK_9_TO_10_NORMAL_PILOTS
SAT_MODCOD_S2X_64APSK_32_TO_45_L_NORMAL_NOPILOTS
SAT_MODCOD_S2X_64APSK_32_TO_45_L_NORMAL_PILOTS
SAT_MODCOD_S2X_64APSK_11_TO_15_NORMAL_NOPILOTS
SAT_MODCOD_S2X_64APSK_11_TO_15_NORMAL_PILOTS
SAT_MODCOD_S2X_64APSK_7_TO_9_NORMAL_NOPILOTS
SAT_MODCOD_S2X_64APSK_7_TO_9_NORMAL_PILOTS
SAT_MODCOD_S2X_64APSK_4_TO_5_NORMAL_NOPILOTS
SAT_MODCOD_S2X_64APSK_4_TO_5_NORMAL_PILOTS
SAT_MODCOD_S2X_64APSK_5_TO_6_NORMAL_NOPILOTS
SAT_MODCOD_S2X_64APSK_5_TO_6_NORMAL_PILOTS
SAT_MODCOD_S2X_128APSK_3_TO_4_NORMAL_NOPILOTS
SAT_MODCOD_S2X_128APSK_3_TO_4_NORMAL_PILOTS
SAT_MODCOD_S2X_128APSK_7_TO_9_NORMAL_NOPILOTS
SAT_MODCOD_S2X_128APSK_7_TO_9_NORMAL_PILOTS
SAT_MODCOD_S2X_256APSK_29_TO_45_L_NORMAL_NOPILOTS
SAT_MODCOD_S2X_256APSK_29_TO_45_L_NORMAL_PILOTS
SAT_MODCOD_S2X_256APSK_2_TO_3_L_NORMAL_NOPILOTS
SAT_MODCOD_S2X_256APSK_2_TO_3_L_NORMAL_PILOTS
SAT_MODCOD_S2X_256APSK_31_TO_45_L_NORMAL_NOPILOTS
SAT_MODCOD_S2X_256APSK_31_TO_45_L_NORMAL_PILOTS
SAT_MODCOD_S2X_256APSK_32_TO_45_NORMAL_NOPILOTS
SAT_MODCOD_S2X_256APSK_32_TO_45_NORMAL_PILOTS
SAT_MODCOD_S2X_256APSK_11_TO_15_L_NORMAL_NOPILOTS
SAT_MODCOD_S2X_256APSK_11_TO_15_L_NORMAL_PILOTS
SAT_MODCOD_S2X_256APSK_3_TO_4_NORMAL_NOPILOTS
SAT_MODCOD_S2X_256APSK_3_TO_4_NORMAL_PILOTS
Definition at line 174 of file satellite-enums.h.
SatNodeType_t
enum ns3::SatEnums::SatNodeType_t
Node type used for packet tracing.
Enumerator
NT_UT
NT_SAT
NT_GW
NT_NCC
NT_TER
NT_UNDEFINED
Definition at line 1927 of file satellite-enums.h.
SatPacketEvent_t
enum ns3::SatEnums::SatPacketEvent_t
Packet event used for packet tracing.
Enumerator
PACKET_SENT
PACKET_RECV
PACKET_ENQUE
PACKET_DROP
Definition at line 1889 of file satellite-enums.h.
SatWaveFormBurstLength_t
enum ns3::SatEnums::SatWaveFormBurstLength_t
Definition for different types of Capacity Request (CR) messages.
Enumerator
UNKNOWN_BURST
SHORT_BURST
LONG_BURST
SHORT_AND_LONG_BURST
Definition at line 1795 of file satellite-enums.h.
Standard_t
enum ns3::SatEnums::Standard_t
The global standard used.
Can be either DVB or Lora
Enumerator
DVB
LORA
Definition at line 121 of file satellite-enums.h.
SuperframeAllocatorType_t
enum ns3::SatEnums::SuperframeAllocatorType_t
Enumerator
DEFAULT_SUPERFRAME_ALLOCATOR
Definition at line 2258 of file satellite-enums.h.
VbdcCapacityRequestAlgorithm_t
enum ns3::SatEnums::VbdcCapacityRequestAlgorithm_t
Enumerator
CR_VBDC_LEGACY
Definition at line 2231 of file satellite-enums.h.
Constructor & Destructor Documentation
~SatEnums()
virtual ns3::SatEnums::~SatEnums () private pure virtual
Destructor.
Made Pure Virtual because the class is not planned be instantiated or inherited
Member Function Documentation
GetAvailableBbFrameTypes()
static void ns3::SatEnums::GetAvailableBbFrameTypes (std::vector< SatBbFrameType_t > & frameTypes) inline static
Definition at line 1839 of file satellite-enums.h.
References NORMAL_FRAME, and SHORT_FRAME.
Referenced by ns3::SatBbFrameConf::SatBbFrameConf().
GetAvailableModcodsFwdLink()
static void ns3::SatEnums::GetAvailableModcodsFwdLink (std::vector< SatModcod_t > & modcods) inline static
Note that the order of MODCODs have a meaning in ACM. The MODCODs should be in decreasing order based on coding rate.
Also note that three MODCODs (QPSK 1/3, 16QAM 3/4, and 16QAM 5/6) are not included because we currently don't have the link results for them.
Definition at line 422 of file satellite-enums.h.
References SAT_MODCOD_16APSK_2_TO_3, SAT_MODCOD_16APSK_3_TO_4, SAT_MODCOD_16APSK_4_TO_5, SAT_MODCOD_16APSK_5_TO_6, SAT_MODCOD_16APSK_8_TO_9, SAT_MODCOD_16APSK_9_TO_10, SAT_MODCOD_32APSK_3_TO_4, SAT_MODCOD_32APSK_4_TO_5, SAT_MODCOD_32APSK_5_TO_6, SAT_MODCOD_32APSK_8_TO_9, SAT_MODCOD_8PSK_2_TO_3, SAT_MODCOD_8PSK_3_TO_4, SAT_MODCOD_8PSK_3_TO_5, SAT_MODCOD_8PSK_5_TO_6, SAT_MODCOD_8PSK_8_TO_9, SAT_MODCOD_8PSK_9_TO_10, SAT_MODCOD_QPSK_1_TO_2, SAT_MODCOD_QPSK_2_TO_3, SAT_MODCOD_QPSK_3_TO_4, SAT_MODCOD_QPSK_3_TO_5, SAT_MODCOD_QPSK_4_TO_5, SAT_MODCOD_QPSK_5_TO_6, SAT_MODCOD_QPSK_8_TO_9, and SAT_MODCOD_QPSK_9_TO_10.
Referenced by ns3::SatBbFrameConf::GetModCodsList().
GetAvailableModcodsFwdLinkS2X()
static void ns3::SatEnums::GetAvailableModcodsFwdLinkS2X (std::vector< SatModcod_t > & modcods, SatEnums::BbFrameUsageMode_t type, bool pilots) inline static
Definition at line 461 of file satellite-enums.h.
References GetAvailableModcodsFwdLinkS2XNormalFrames(), GetAvailableModcodsFwdLinkS2XShortFrames(), NORMAL_FRAMES, SHORT_AND_NORMAL_FRAMES, and SHORT_FRAMES.
Referenced by ns3::SatBbFrameConf::GetModCodsList().
GetAvailableModcodsFwdLinkS2XNormalFrames()
static void ns3::SatEnums::GetAvailableModcodsFwdLinkS2XNormalFrames (std::vector< SatModcod_t > & modcods, bool pilots) inline static
Note that the order of MODCODs have a meaning in ACM. The MODCODs should be in decreasing order based on coding rate.
Definition at line 480 of file satellite-enums.h.
References SAT_MODCOD_S2X_128APSK_3_TO_4_NORMAL_NOPILOTS, SAT_MODCOD_S2X_128APSK_3_TO_4_NORMAL_PILOTS, SAT_MODCOD_S2X_128APSK_7_TO_9_NORMAL_NOPILOTS, SAT_MODCOD_S2X_128APSK_7_TO_9_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_13_TO_18_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_13_TO_18_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_1_TO_2_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_1_TO_2_L_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_23_TO_36_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_23_TO_36_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_25_TO_36_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_25_TO_36_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_26_TO_45_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_26_TO_45_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_28_TO_45_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_28_TO_45_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_2_TO_3_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_2_TO_3_L_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_2_TO_3_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_2_TO_3_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_3_TO_4_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_3_TO_4_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_3_TO_5_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_3_TO_5_L_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_3_TO_5_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_3_TO_5_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_4_TO_5_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_4_TO_5_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_5_TO_6_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_5_TO_6_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_5_TO_9_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_5_TO_9_L_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_77_TO_90_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_77_TO_90_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_7_TO_9_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_7_TO_9_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_8_TO_15_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_8_TO_15_L_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_8_TO_9_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_8_TO_9_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_9_TO_10_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_9_TO_10_NORMAL_PILOTS, SAT_MODCOD_S2X_256APSK_11_TO_15_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_256APSK_11_TO_15_L_NORMAL_PILOTS, SAT_MODCOD_S2X_256APSK_29_TO_45_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_256APSK_29_TO_45_L_NORMAL_PILOTS, SAT_MODCOD_S2X_256APSK_2_TO_3_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_256APSK_2_TO_3_L_NORMAL_PILOTS, SAT_MODCOD_S2X_256APSK_31_TO_45_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_256APSK_31_TO_45_L_NORMAL_PILOTS, SAT_MODCOD_S2X_256APSK_32_TO_45_NORMAL_NOPILOTS, SAT_MODCOD_S2X_256APSK_32_TO_45_NORMAL_PILOTS, SAT_MODCOD_S2X_256APSK_3_TO_4_NORMAL_NOPILOTS, SAT_MODCOD_S2X_256APSK_3_TO_4_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_11_TO_15_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_11_TO_15_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_2_TO_3_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_2_TO_3_L_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_32_TO_45_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_32_TO_45_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_3_TO_4_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_3_TO_4_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_4_TO_5_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_4_TO_5_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_5_TO_6_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_5_TO_6_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_7_TO_9_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_7_TO_9_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_8_TO_9_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_8_TO_9_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_9_TO_10_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_9_TO_10_NORMAL_PILOTS, SAT_MODCOD_S2X_64APSK_11_TO_15_NORMAL_NOPILOTS, SAT_MODCOD_S2X_64APSK_11_TO_15_NORMAL_PILOTS, SAT_MODCOD_S2X_64APSK_32_TO_45_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_64APSK_32_TO_45_L_NORMAL_PILOTS, SAT_MODCOD_S2X_64APSK_4_TO_5_NORMAL_NOPILOTS, SAT_MODCOD_S2X_64APSK_4_TO_5_NORMAL_PILOTS, SAT_MODCOD_S2X_64APSK_5_TO_6_NORMAL_NOPILOTS, SAT_MODCOD_S2X_64APSK_5_TO_6_NORMAL_PILOTS, SAT_MODCOD_S2X_64APSK_7_TO_9_NORMAL_NOPILOTS, SAT_MODCOD_S2X_64APSK_7_TO_9_NORMAL_PILOTS, SAT_MODCOD_S2X_8APSK_26_TO_45_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8APSK_26_TO_45_L_NORMAL_PILOTS, SAT_MODCOD_S2X_8APSK_5_TO_9_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8APSK_5_TO_9_L_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_13_TO_18_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_13_TO_18_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_23_TO_36_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_23_TO_36_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_25_TO_36_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_25_TO_36_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_2_TO_3_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_2_TO_3_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_3_TO_4_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_3_TO_4_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_3_TO_5_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_3_TO_5_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_5_TO_6_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_5_TO_6_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_8_TO_9_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_8_TO_9_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_9_TO_10_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_9_TO_10_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_11_TO_20_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_11_TO_20_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_13_TO_45_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_13_TO_45_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_1_TO_2_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_1_TO_2_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_1_TO_3_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_1_TO_3_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_1_TO_4_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_1_TO_4_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_2_TO_3_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_2_TO_3_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_2_TO_5_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_2_TO_5_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_3_TO_4_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_3_TO_4_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_3_TO_5_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_3_TO_5_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_4_TO_5_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_4_TO_5_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_5_TO_6_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_5_TO_6_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_8_TO_9_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_8_TO_9_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_9_TO_10_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_9_TO_10_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_9_TO_20_NORMAL_NOPILOTS, and SAT_MODCOD_S2X_QPSK_9_TO_20_NORMAL_PILOTS.
Referenced by GetAvailableModcodsFwdLinkS2X().
GetAvailableModcodsFwdLinkS2XShortFrames()
static void ns3::SatEnums::GetAvailableModcodsFwdLinkS2XShortFrames (std::vector< SatModcod_t > & modcods, bool pilots) inline static
Note that the order of MODCODs have a meaning in ACM. The MODCODs should be in decreasing order based on coding rate.
Definition at line 629 of file satellite-enums.h.
References SAT_MODCOD_S2X_16APSK_26_TO_45_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_26_TO_45_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_2_TO_3_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_2_TO_3_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_32_TO_45_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_32_TO_45_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_3_TO_4_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_3_TO_4_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_3_TO_5_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_3_TO_5_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_4_TO_5_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_4_TO_5_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_5_TO_6_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_5_TO_6_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_7_TO_15_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_7_TO_15_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_8_TO_15_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_8_TO_15_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_8_TO_9_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_8_TO_9_SHORT_PILOTS, SAT_MODCOD_S2X_32APSK_2_TO_3_SHORT_NOPILOTS, SAT_MODCOD_S2X_32APSK_2_TO_3_SHORT_PILOTS, SAT_MODCOD_S2X_32APSK_32_TO_45_SHORT_NOPILOTS, SAT_MODCOD_S2X_32APSK_32_TO_45_SHORT_PILOTS, SAT_MODCOD_S2X_32APSK_3_TO_4_SHORT_NOPILOTS, SAT_MODCOD_S2X_32APSK_3_TO_4_SHORT_PILOTS, SAT_MODCOD_S2X_32APSK_4_TO_5_SHORT_NOPILOTS, SAT_MODCOD_S2X_32APSK_4_TO_5_SHORT_PILOTS, SAT_MODCOD_S2X_32APSK_5_TO_6_SHORT_NOPILOTS, SAT_MODCOD_S2X_32APSK_5_TO_6_SHORT_PILOTS, SAT_MODCOD_S2X_32APSK_8_TO_9_SHORT_NOPILOTS, SAT_MODCOD_S2X_32APSK_8_TO_9_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_26_TO_45_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_26_TO_45_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_2_TO_3_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_2_TO_3_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_32_TO_45_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_32_TO_45_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_3_TO_4_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_3_TO_4_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_3_TO_5_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_3_TO_5_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_5_TO_6_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_5_TO_6_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_7_TO_15_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_7_TO_15_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_8_TO_15_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_8_TO_15_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_8_TO_9_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_8_TO_9_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_11_TO_45_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_11_TO_45_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_14_TO_45_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_14_TO_45_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_1_TO_2_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_1_TO_2_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_1_TO_3_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_1_TO_3_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_1_TO_4_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_1_TO_4_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_2_TO_3_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_2_TO_3_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_2_TO_5_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_2_TO_5_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_32_TO_45_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_32_TO_45_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_3_TO_4_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_3_TO_4_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_3_TO_5_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_3_TO_5_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_4_TO_15_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_4_TO_15_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_4_TO_5_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_4_TO_5_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_5_TO_6_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_5_TO_6_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_7_TO_15_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_7_TO_15_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_8_TO_15_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_8_TO_15_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_8_TO_9_SHORT_NOPILOTS, and SAT_MODCOD_S2X_QPSK_8_TO_9_SHORT_PILOTS.
Referenced by GetAvailableModcodsFwdLinkS2X().
GetAvailableModcodsRtnLink()
static void ns3::SatEnums::GetAvailableModcodsRtnLink (std::vector< SatModcod_t > & modcods) inline static
Note that the order of MODCODs have a meaning in ACM. The MODCODs should be in decreasing order based on coding rate.
Definition at line 728 of file satellite-enums.h.
References SAT_MODCOD_16QAM_3_TO_4, SAT_MODCOD_16QAM_5_TO_6, SAT_MODCOD_8PSK_2_TO_3, SAT_MODCOD_8PSK_3_TO_4, SAT_MODCOD_8PSK_5_TO_6, SAT_MODCOD_QPSK_1_TO_2, SAT_MODCOD_QPSK_1_TO_3, SAT_MODCOD_QPSK_2_TO_3, SAT_MODCOD_QPSK_3_TO_4, SAT_MODCOD_QPSK_4_TO_5, and SAT_MODCOD_QPSK_5_TO_6.
GetCapacityAllocationCategory()
static std::string ns3::SatEnums::GetCapacityAllocationCategory (SatCapacityAllocationCategory_t cac) inline static
Definition at line 1814 of file satellite-enums.h.
References DA_AVBDC, DA_RBDC, DA_UNKNOWN, and DA_VBDC.
Referenced by ns3::SatRequestManager::DoEvaluation().
GetChannelTypeName()
static std::string ns3::SatEnums::GetChannelTypeName (ChannelType_t channelType) inline static
Definition at line 1856 of file satellite-enums.h.
References FORWARD_FEEDER_CH, FORWARD_USER_CH, RETURN_FEEDER_CH, RETURN_USER_CH, and UNKNOWN_CH.
Referenced by ns3::SatPhyRxCarrier::SatPhyRxCarrier(), ns3::SatCompositeSinrOutputTraceContainer::AddNode(), ns3::SatFadingInputTraceContainer::AddNode(), ns3::SatFadingOutputTraceContainer::AddNode(), ns3::SatInterferenceInputTraceContainer::AddNode(), ns3::SatInterferenceOutputTraceContainer::AddNode(), ns3::SatRxCnoInputTraceContainer::AddNode(), ns3::SatRxPowerInputTraceContainer::AddNode(), ns3::SatRxPowerOutputTraceContainer::AddNode(), ns3::SatChannel::DoRxCnoInputTrace(), ns3::SatChannel::DoRxPowerInputTrace(), ns3::SatChannel::DoRxPowerOutputTrace(), ns3::SatPhyRxCarrierUplink::EndRxData(), LinkBudgetTraceCb(), ns3::SatPhyRxCarrierPerSlot::ReceiveSlot(), ns3::SatStatsPacketErrorHelper::SetChannelType(), and ns3::SatPhyRxCarrier::StartRx().
GetFrameTypeName()
static std::string ns3::SatEnums::GetFrameTypeName (SatBbFrameType_t frameType) inline static
Definition at line 1752 of file satellite-enums.h.
References DUMMY_FRAME, NORMAL_FRAME, and SHORT_FRAME.
Referenced by ns3::SatStatsFrameTypeUsageHelper::FrameTypeUsageCallback(), and PrintBbFrameInfo().
GetLinkDirName()
static std::string ns3::SatEnums::GetLinkDirName (SatLinkDir_t linkDir) inline static
Definition at line 1980 of file satellite-enums.h.
References LD_FORWARD, LD_RETURN, and LD_UNDEFINED.
Referenced by ns3::SatPacketTrace::AddTraceEntry().
GetLogLevelName()
static std::string ns3::SatEnums::GetLogLevelName (SatLogLevel_t logLevel) inline static
Definition at line 2016 of file satellite-enums.h.
References LL_CH, LL_LLC, LL_MAC, LL_ND, and LL_PHY.
Referenced by ns3::SatPacketTrace::AddTraceEntry().
GetModcodFromName()
static SatModcod_t ns3::SatEnums::GetModcodFromName (const std::string name) inline static
Definition at line 1247 of file satellite-enums.h.
References SAT_MODCOD_16APSK_2_TO_3, SAT_MODCOD_16APSK_3_TO_4, SAT_MODCOD_16APSK_4_TO_5, SAT_MODCOD_16APSK_5_TO_6, SAT_MODCOD_16APSK_8_TO_9, SAT_MODCOD_16APSK_9_TO_10, SAT_MODCOD_16QAM_3_TO_4, SAT_MODCOD_16QAM_5_TO_6, SAT_MODCOD_32APSK_3_TO_4, SAT_MODCOD_32APSK_4_TO_5, SAT_MODCOD_32APSK_5_TO_6, SAT_MODCOD_32APSK_8_TO_9, SAT_MODCOD_8PSK_2_TO_3, SAT_MODCOD_8PSK_3_TO_4, SAT_MODCOD_8PSK_3_TO_5, SAT_MODCOD_8PSK_5_TO_6, SAT_MODCOD_8PSK_8_TO_9, SAT_MODCOD_8PSK_9_TO_10, SAT_MODCOD_QPSK_1_TO_2, SAT_MODCOD_QPSK_1_TO_3, SAT_MODCOD_QPSK_2_TO_3, SAT_MODCOD_QPSK_3_TO_4, SAT_MODCOD_QPSK_3_TO_5, SAT_MODCOD_QPSK_4_TO_5, SAT_MODCOD_QPSK_5_TO_6, SAT_MODCOD_QPSK_8_TO_9, SAT_MODCOD_QPSK_9_TO_10, SAT_MODCOD_S2X_128APSK_3_TO_4_NORMAL_NOPILOTS, SAT_MODCOD_S2X_128APSK_3_TO_4_NORMAL_PILOTS, SAT_MODCOD_S2X_128APSK_7_TO_9_NORMAL_NOPILOTS, SAT_MODCOD_S2X_128APSK_7_TO_9_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_13_TO_18_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_13_TO_18_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_1_TO_2_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_1_TO_2_L_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_23_TO_36_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_23_TO_36_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_25_TO_36_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_25_TO_36_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_26_TO_45_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_26_TO_45_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_26_TO_45_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_26_TO_45_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_28_TO_45_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_28_TO_45_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_2_TO_3_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_2_TO_3_L_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_2_TO_3_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_2_TO_3_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_2_TO_3_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_2_TO_3_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_32_TO_45_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_32_TO_45_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_3_TO_4_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_3_TO_4_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_3_TO_4_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_3_TO_4_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_3_TO_5_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_3_TO_5_L_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_3_TO_5_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_3_TO_5_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_3_TO_5_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_3_TO_5_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_4_TO_5_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_4_TO_5_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_4_TO_5_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_4_TO_5_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_5_TO_6_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_5_TO_6_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_5_TO_6_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_5_TO_6_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_5_TO_9_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_5_TO_9_L_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_77_TO_90_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_77_TO_90_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_7_TO_15_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_7_TO_15_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_7_TO_9_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_7_TO_9_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_8_TO_15_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_8_TO_15_L_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_8_TO_15_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_8_TO_15_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_8_TO_9_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_8_TO_9_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_8_TO_9_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_8_TO_9_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_9_TO_10_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_9_TO_10_NORMAL_PILOTS, SAT_MODCOD_S2X_256APSK_11_TO_15_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_256APSK_11_TO_15_L_NORMAL_PILOTS, SAT_MODCOD_S2X_256APSK_29_TO_45_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_256APSK_29_TO_45_L_NORMAL_PILOTS, SAT_MODCOD_S2X_256APSK_2_TO_3_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_256APSK_2_TO_3_L_NORMAL_PILOTS, SAT_MODCOD_S2X_256APSK_31_TO_45_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_256APSK_31_TO_45_L_NORMAL_PILOTS, SAT_MODCOD_S2X_256APSK_32_TO_45_NORMAL_NOPILOTS, SAT_MODCOD_S2X_256APSK_32_TO_45_NORMAL_PILOTS, SAT_MODCOD_S2X_256APSK_3_TO_4_NORMAL_NOPILOTS, SAT_MODCOD_S2X_256APSK_3_TO_4_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_11_TO_15_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_11_TO_15_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_2_TO_3_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_2_TO_3_L_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_2_TO_3_SHORT_NOPILOTS, SAT_MODCOD_S2X_32APSK_2_TO_3_SHORT_PILOTS, SAT_MODCOD_S2X_32APSK_32_TO_45_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_32_TO_45_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_32_TO_45_SHORT_NOPILOTS, SAT_MODCOD_S2X_32APSK_32_TO_45_SHORT_PILOTS, SAT_MODCOD_S2X_32APSK_3_TO_4_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_3_TO_4_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_3_TO_4_SHORT_NOPILOTS, SAT_MODCOD_S2X_32APSK_3_TO_4_SHORT_PILOTS, SAT_MODCOD_S2X_32APSK_4_TO_5_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_4_TO_5_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_4_TO_5_SHORT_NOPILOTS, SAT_MODCOD_S2X_32APSK_4_TO_5_SHORT_PILOTS, SAT_MODCOD_S2X_32APSK_5_TO_6_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_5_TO_6_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_5_TO_6_SHORT_NOPILOTS, SAT_MODCOD_S2X_32APSK_5_TO_6_SHORT_PILOTS, SAT_MODCOD_S2X_32APSK_7_TO_9_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_7_TO_9_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_8_TO_9_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_8_TO_9_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_8_TO_9_SHORT_NOPILOTS, SAT_MODCOD_S2X_32APSK_8_TO_9_SHORT_PILOTS, SAT_MODCOD_S2X_32APSK_9_TO_10_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_9_TO_10_NORMAL_PILOTS, SAT_MODCOD_S2X_64APSK_11_TO_15_NORMAL_NOPILOTS, SAT_MODCOD_S2X_64APSK_11_TO_15_NORMAL_PILOTS, SAT_MODCOD_S2X_64APSK_32_TO_45_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_64APSK_32_TO_45_L_NORMAL_PILOTS, SAT_MODCOD_S2X_64APSK_4_TO_5_NORMAL_NOPILOTS, SAT_MODCOD_S2X_64APSK_4_TO_5_NORMAL_PILOTS, SAT_MODCOD_S2X_64APSK_5_TO_6_NORMAL_NOPILOTS, SAT_MODCOD_S2X_64APSK_5_TO_6_NORMAL_PILOTS, SAT_MODCOD_S2X_64APSK_7_TO_9_NORMAL_NOPILOTS, SAT_MODCOD_S2X_64APSK_7_TO_9_NORMAL_PILOTS, SAT_MODCOD_S2X_8APSK_26_TO_45_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8APSK_26_TO_45_L_NORMAL_PILOTS, SAT_MODCOD_S2X_8APSK_5_TO_9_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8APSK_5_TO_9_L_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_13_TO_18_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_13_TO_18_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_23_TO_36_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_23_TO_36_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_25_TO_36_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_25_TO_36_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_26_TO_45_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_26_TO_45_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_2_TO_3_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_2_TO_3_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_2_TO_3_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_2_TO_3_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_32_TO_45_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_32_TO_45_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_3_TO_4_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_3_TO_4_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_3_TO_4_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_3_TO_4_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_3_TO_5_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_3_TO_5_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_3_TO_5_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_3_TO_5_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_5_TO_6_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_5_TO_6_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_5_TO_6_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_5_TO_6_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_7_TO_15_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_7_TO_15_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_8_TO_15_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_8_TO_15_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_8_TO_9_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_8_TO_9_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_8_TO_9_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_8_TO_9_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_9_TO_10_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_9_TO_10_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_11_TO_20_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_11_TO_20_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_11_TO_45_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_11_TO_45_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_13_TO_45_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_13_TO_45_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_14_TO_45_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_14_TO_45_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_1_TO_2_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_1_TO_2_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_1_TO_2_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_1_TO_2_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_1_TO_3_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_1_TO_3_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_1_TO_3_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_1_TO_3_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_1_TO_4_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_1_TO_4_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_1_TO_4_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_1_TO_4_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_2_TO_3_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_2_TO_3_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_2_TO_3_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_2_TO_3_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_2_TO_5_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_2_TO_5_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_2_TO_5_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_2_TO_5_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_32_TO_45_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_32_TO_45_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_3_TO_4_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_3_TO_4_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_3_TO_4_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_3_TO_4_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_3_TO_5_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_3_TO_5_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_3_TO_5_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_3_TO_5_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_4_TO_15_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_4_TO_15_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_4_TO_5_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_4_TO_5_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_4_TO_5_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_4_TO_5_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_5_TO_6_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_5_TO_6_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_5_TO_6_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_5_TO_6_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_7_TO_15_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_7_TO_15_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_8_TO_15_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_8_TO_15_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_8_TO_9_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_8_TO_9_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_8_TO_9_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_8_TO_9_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_9_TO_10_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_9_TO_10_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_9_TO_20_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_9_TO_20_NORMAL_PILOTS, and SAT_NONVALID_MODCOD.
Referenced by ns3::SatBbFrameConf::SatBbFrameConf(), and ns3::SatBbFrameConf::GetModCodsList().
GetModcodTypeName()
static std::string ns3::SatEnums::GetModcodTypeName (SatModcod_t modcod) inline static
Definition at line 748 of file satellite-enums.h.
References SAT_MODCOD_16APSK_2_TO_3, SAT_MODCOD_16APSK_3_TO_4, SAT_MODCOD_16APSK_4_TO_5, SAT_MODCOD_16APSK_5_TO_6, SAT_MODCOD_16APSK_8_TO_9, SAT_MODCOD_16APSK_9_TO_10, SAT_MODCOD_16QAM_3_TO_4, SAT_MODCOD_16QAM_5_TO_6, SAT_MODCOD_32APSK_3_TO_4, SAT_MODCOD_32APSK_4_TO_5, SAT_MODCOD_32APSK_5_TO_6, SAT_MODCOD_32APSK_8_TO_9, SAT_MODCOD_8PSK_2_TO_3, SAT_MODCOD_8PSK_3_TO_4, SAT_MODCOD_8PSK_3_TO_5, SAT_MODCOD_8PSK_5_TO_6, SAT_MODCOD_8PSK_8_TO_9, SAT_MODCOD_8PSK_9_TO_10, SAT_MODCOD_BPSK_1_TO_3, SAT_MODCOD_QPSK_1_TO_2, SAT_MODCOD_QPSK_1_TO_3, SAT_MODCOD_QPSK_2_TO_3, SAT_MODCOD_QPSK_3_TO_4, SAT_MODCOD_QPSK_3_TO_5, SAT_MODCOD_QPSK_4_TO_5, SAT_MODCOD_QPSK_5_TO_6, SAT_MODCOD_QPSK_8_TO_9, SAT_MODCOD_QPSK_9_TO_10, SAT_MODCOD_S2X_128APSK_3_TO_4_NORMAL_NOPILOTS, SAT_MODCOD_S2X_128APSK_3_TO_4_NORMAL_PILOTS, SAT_MODCOD_S2X_128APSK_7_TO_9_NORMAL_NOPILOTS, SAT_MODCOD_S2X_128APSK_7_TO_9_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_13_TO_18_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_13_TO_18_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_1_TO_2_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_1_TO_2_L_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_23_TO_36_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_23_TO_36_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_25_TO_36_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_25_TO_36_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_26_TO_45_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_26_TO_45_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_26_TO_45_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_26_TO_45_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_28_TO_45_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_28_TO_45_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_2_TO_3_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_2_TO_3_L_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_2_TO_3_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_2_TO_3_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_2_TO_3_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_2_TO_3_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_32_TO_45_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_32_TO_45_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_3_TO_4_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_3_TO_4_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_3_TO_4_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_3_TO_4_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_3_TO_5_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_3_TO_5_L_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_3_TO_5_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_3_TO_5_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_3_TO_5_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_3_TO_5_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_4_TO_5_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_4_TO_5_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_4_TO_5_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_4_TO_5_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_5_TO_6_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_5_TO_6_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_5_TO_6_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_5_TO_6_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_5_TO_9_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_5_TO_9_L_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_77_TO_90_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_77_TO_90_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_7_TO_15_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_7_TO_15_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_7_TO_9_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_7_TO_9_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_8_TO_15_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_8_TO_15_L_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_8_TO_15_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_8_TO_15_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_8_TO_9_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_8_TO_9_NORMAL_PILOTS, SAT_MODCOD_S2X_16APSK_8_TO_9_SHORT_NOPILOTS, SAT_MODCOD_S2X_16APSK_8_TO_9_SHORT_PILOTS, SAT_MODCOD_S2X_16APSK_9_TO_10_NORMAL_NOPILOTS, SAT_MODCOD_S2X_16APSK_9_TO_10_NORMAL_PILOTS, SAT_MODCOD_S2X_256APSK_11_TO_15_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_256APSK_11_TO_15_L_NORMAL_PILOTS, SAT_MODCOD_S2X_256APSK_29_TO_45_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_256APSK_29_TO_45_L_NORMAL_PILOTS, SAT_MODCOD_S2X_256APSK_2_TO_3_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_256APSK_2_TO_3_L_NORMAL_PILOTS, SAT_MODCOD_S2X_256APSK_31_TO_45_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_256APSK_31_TO_45_L_NORMAL_PILOTS, SAT_MODCOD_S2X_256APSK_32_TO_45_NORMAL_NOPILOTS, SAT_MODCOD_S2X_256APSK_32_TO_45_NORMAL_PILOTS, SAT_MODCOD_S2X_256APSK_3_TO_4_NORMAL_NOPILOTS, SAT_MODCOD_S2X_256APSK_3_TO_4_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_11_TO_15_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_11_TO_15_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_2_TO_3_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_2_TO_3_L_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_2_TO_3_SHORT_NOPILOTS, SAT_MODCOD_S2X_32APSK_2_TO_3_SHORT_PILOTS, SAT_MODCOD_S2X_32APSK_32_TO_45_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_32_TO_45_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_32_TO_45_SHORT_NOPILOTS, SAT_MODCOD_S2X_32APSK_32_TO_45_SHORT_PILOTS, SAT_MODCOD_S2X_32APSK_3_TO_4_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_3_TO_4_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_3_TO_4_SHORT_NOPILOTS, SAT_MODCOD_S2X_32APSK_3_TO_4_SHORT_PILOTS, SAT_MODCOD_S2X_32APSK_4_TO_5_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_4_TO_5_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_4_TO_5_SHORT_NOPILOTS, SAT_MODCOD_S2X_32APSK_4_TO_5_SHORT_PILOTS, SAT_MODCOD_S2X_32APSK_5_TO_6_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_5_TO_6_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_5_TO_6_SHORT_NOPILOTS, SAT_MODCOD_S2X_32APSK_5_TO_6_SHORT_PILOTS, SAT_MODCOD_S2X_32APSK_7_TO_9_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_7_TO_9_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_8_TO_9_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_8_TO_9_NORMAL_PILOTS, SAT_MODCOD_S2X_32APSK_8_TO_9_SHORT_NOPILOTS, SAT_MODCOD_S2X_32APSK_8_TO_9_SHORT_PILOTS, SAT_MODCOD_S2X_32APSK_9_TO_10_NORMAL_NOPILOTS, SAT_MODCOD_S2X_32APSK_9_TO_10_NORMAL_PILOTS, SAT_MODCOD_S2X_64APSK_11_TO_15_NORMAL_NOPILOTS, SAT_MODCOD_S2X_64APSK_11_TO_15_NORMAL_PILOTS, SAT_MODCOD_S2X_64APSK_32_TO_45_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_64APSK_32_TO_45_L_NORMAL_PILOTS, SAT_MODCOD_S2X_64APSK_4_TO_5_NORMAL_NOPILOTS, SAT_MODCOD_S2X_64APSK_4_TO_5_NORMAL_PILOTS, SAT_MODCOD_S2X_64APSK_5_TO_6_NORMAL_NOPILOTS, SAT_MODCOD_S2X_64APSK_5_TO_6_NORMAL_PILOTS, SAT_MODCOD_S2X_64APSK_7_TO_9_NORMAL_NOPILOTS, SAT_MODCOD_S2X_64APSK_7_TO_9_NORMAL_PILOTS, SAT_MODCOD_S2X_8APSK_26_TO_45_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8APSK_26_TO_45_L_NORMAL_PILOTS, SAT_MODCOD_S2X_8APSK_5_TO_9_L_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8APSK_5_TO_9_L_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_13_TO_18_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_13_TO_18_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_23_TO_36_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_23_TO_36_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_25_TO_36_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_25_TO_36_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_26_TO_45_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_26_TO_45_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_2_TO_3_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_2_TO_3_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_2_TO_3_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_2_TO_3_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_32_TO_45_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_32_TO_45_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_3_TO_4_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_3_TO_4_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_3_TO_4_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_3_TO_4_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_3_TO_5_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_3_TO_5_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_3_TO_5_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_3_TO_5_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_5_TO_6_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_5_TO_6_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_5_TO_6_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_5_TO_6_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_7_TO_15_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_7_TO_15_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_8_TO_15_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_8_TO_15_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_8_TO_9_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_8_TO_9_NORMAL_PILOTS, SAT_MODCOD_S2X_8PSK_8_TO_9_SHORT_NOPILOTS, SAT_MODCOD_S2X_8PSK_8_TO_9_SHORT_PILOTS, SAT_MODCOD_S2X_8PSK_9_TO_10_NORMAL_NOPILOTS, SAT_MODCOD_S2X_8PSK_9_TO_10_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_11_TO_20_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_11_TO_20_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_11_TO_45_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_11_TO_45_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_13_TO_45_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_13_TO_45_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_14_TO_45_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_14_TO_45_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_1_TO_2_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_1_TO_2_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_1_TO_2_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_1_TO_2_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_1_TO_3_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_1_TO_3_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_1_TO_3_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_1_TO_3_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_1_TO_4_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_1_TO_4_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_1_TO_4_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_1_TO_4_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_2_TO_3_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_2_TO_3_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_2_TO_3_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_2_TO_3_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_2_TO_5_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_2_TO_5_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_2_TO_5_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_2_TO_5_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_32_TO_45_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_32_TO_45_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_3_TO_4_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_3_TO_4_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_3_TO_4_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_3_TO_4_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_3_TO_5_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_3_TO_5_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_3_TO_5_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_3_TO_5_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_4_TO_15_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_4_TO_15_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_4_TO_5_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_4_TO_5_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_4_TO_5_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_4_TO_5_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_5_TO_6_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_5_TO_6_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_5_TO_6_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_5_TO_6_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_7_TO_15_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_7_TO_15_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_8_TO_15_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_8_TO_15_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_8_TO_9_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_8_TO_9_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_8_TO_9_SHORT_NOPILOTS, SAT_MODCOD_S2X_QPSK_8_TO_9_SHORT_PILOTS, SAT_MODCOD_S2X_QPSK_9_TO_10_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_9_TO_10_NORMAL_PILOTS, SAT_MODCOD_S2X_QPSK_9_TO_20_NORMAL_NOPILOTS, SAT_MODCOD_S2X_QPSK_9_TO_20_NORMAL_PILOTS, and SAT_NONVALID_MODCOD.
Referenced by ns3::SatBbFrameConf::SatBbFrameConf(), ns3::SatDvbS2Waveform::Dump(), and PrintBbFrameInfo().
GetNodeTypeName()
static std::string ns3::SatEnums::GetNodeTypeName (SatNodeType_t nodeType) inline static
Definition at line 1937 of file satellite-enums.h.
References NT_GW, NT_NCC, NT_SAT, NT_TER, NT_UNDEFINED, and NT_UT.
Referenced by ns3::SatPacketTrace::AddTraceEntry().
GetPacketEventName()
static std::string ns3::SatEnums::GetPacketEventName (SatPacketEvent_t packetEvent) inline static
Definition at line 1897 of file satellite-enums.h.
References PACKET_DROP, PACKET_ENQUE, PACKET_RECV, and PACKET_SENT.
Referenced by ns3::SatPacketTrace::AddTraceEntry().
GetPacketTypeName()
static std::string ns3::SatEnums::GetPacketTypeName (PacketType_t packetType) inline static
Definition at line 2173 of file satellite-enums.h.
References PACKET_TYPE_CRDSA, PACKET_TYPE_DEDICATED_ACCESS, PACKET_TYPE_ESSA, and PACKET_TYPE_SLOTTED_ALOHA.
GetRandomAccessModelName()
static std::string ns3::SatEnums::GetRandomAccessModelName (RandomAccessModel_t model) inline static
Definition at line 2092 of file satellite-enums.h.
References RA_MODEL_CRDSA, RA_MODEL_ESSA, RA_MODEL_OFF, RA_MODEL_RCS2_SPECIFICATION, and RA_MODEL_SLOTTED_ALOHA.
Referenced by ns3::SatRandomAccess::SetRandomAccessModel().
GetRandomAccessOpportunityTypeName()
static std::string ns3::SatEnums::GetRandomAccessOpportunityTypeName (RandomAccessTxOpportunityType_t opportunityType) inline static
Definition at line 2133 of file satellite-enums.h.
References RA_TX_OPPORTUNITY_CRDSA, RA_TX_OPPORTUNITY_DO_NOTHING, RA_TX_OPPORTUNITY_ESSA, and RA_TX_OPPORTUNITY_SLOTTED_ALOHA.
Referenced by ns3::SatRandomAccess::DoCrdsa().
GetRandomAccessTriggerTypeName()
static std::string ns3::SatEnums::GetRandomAccessTriggerTypeName (RandomAccessTriggerType_t triggerType) inline static
Definition at line 2056 of file satellite-enums.h.
References RA_TRIGGER_TYPE_CRDSA, RA_TRIGGER_TYPE_ESSA, and RA_TRIGGER_TYPE_SLOTTED_ALOHA.
Referenced by ns3::SatRandomAccess::DoRandomAccess().
GetRbdcCapacityRequestAlgorithmName()
static std::string ns3::SatEnums::GetRbdcCapacityRequestAlgorithmName (RbdcCapacityRequestAlgorithm_t rbdcAlgorithm) inline static
Definition at line 2208 of file satellite-enums.h.
References CR_RBDC_LEGACY.
GetVbdcCapacityRequestAlgorithmName()
static std::string ns3::SatEnums::GetVbdcCapacityRequestAlgorithmName (VbdcCapacityRequestAlgorithm_t vbdcAlgorithm) inline static
Definition at line 2236 of file satellite-enums.h.
References CR_VBDC_LEGACY.
The documentation for this class was generated from the following file:
/builds/sns3/satellite/satellite/model/satellite-enums.h