SNS3
ns3::LorawanMacEndDeviceClassA Class Reference
Class representing the MAC layer of a Class A LoRaWAN device.
#include "lorawan-mac-end-device-class-a.h"
Public Member Functions
LorawanMacEndDeviceClassA ()
LorawanMacEndDeviceClassA (uint32_t satId, uint32_t beamId, Ptr< SatSuperframeSeq > seq)
virtual ~LorawanMacEndDeviceClassA ()
void CloseFirstReceiveWindow (void)
Perform operations needed to close the first receive window.
void CloseSecondReceiveWindow (void)
Perform operations needed to close the second receive window.
virtual void FailedReception (Ptr< const Packet > packet)
Function called by lower layers to inform this layer that reception of a packet we were locked on failed.
uint8_t GetFirstReceiveWindowDataRate (void)
Get the Data Rate that will be used in the first receive window.
virtual Time GetNextClassTransmissionDelay (Time waitingTime)
Find the minimum waiting time before the next possible transmission based on End Device's Class Type.
uint8_t GetSecondReceiveWindowDataRate (void)
Get the Data Rate that will be used in the second receive window.
double GetSecondReceiveWindowFrequency (void)
Get the frequency that is used for the second receive window.
virtual void OnRxClassParamSetupReq (Ptr< RxParamSetupReq > rxParamSetupReq)
Perform the actions that need to be taken when receiving a RxParamSetupReq command based on the Device's Class Type.
void OpenFirstReceiveWindow (void)
Perform operations needed to open the first receive window.
void OpenSecondReceiveWindow (void)
Perform operations needed to open the second receive window.
virtual void Receive (Ptr< Packet > packet)
Receive a packet.
virtual void SendToPhy (Ptr< Packet > packet)
Add headers and send a packet with the sending function of the physical layer.
void SetRaModel (SatEnums::RandomAccessModel_t randomAccessModel)
Set the random access model.
void SetSecondReceiveWindowDataRate (uint8_t dataRate)
Set the Data Rate to be used in the second receive window.
void SetSecondReceiveWindowFrequency (double frequencyMHz)
Set the frequency that will be used for the second receive window.
virtual void TxFinished ()
Perform the actions that are required after a packet send.
Public Member Functions inherited from ns3::LorawanMacEndDevice
LorawanMacEndDevice ()
LorawanMacEndDevice (uint32_t satId, uint32_t beamId)
virtual ~LorawanMacEndDevice ()
void AddLogicalChannel (double frequency)
Add a logical channel to the helper.
void AddLogicalChannel (Ptr< LoraLogicalChannel > logicalChannel)
Add a logical channel to the helper.
void AddLoraSubBand (double startFrequency, double endFrequency, double dutyCycle, double maxTxPowerDbm)
Add a subband to the logical channel helper.
void AddLorawanMacCommand (Ptr< LorawanMacCommand > macCommand)
Add a MAC command to the list of those that will be sent out in the next packet.
void ApplyNecessaryOptions (LoraFrameHeader &frameHeader)
Add the necessary options and MAC commands to the LoraFrameHeader.
void ApplyNecessaryOptions (LorawanMacHeader &macHeader)
Add the necessary options and MAC commands to the LorawanMacHeader.
virtual void DoSend (Ptr< Packet > packet)
Checking if we are performing the transmission of a new packet or a retransmission, and call SendToPhy function.
double GetAggregatedDutyCycle (void)
Set a value for the RX1DROffset parameter.
uint8_t GetDataRate (void)
Get the data rate this end device is set to use.
bool GetDataRateAdaptation (void)
Get if data rate adaptation is enabled or not.
LoraDeviceAddress GetDeviceAddress (void)
Get the network address of this device.
uint8_t GetMaxNumberOfTransmissions (void)
Set the maximum number of transmissions allowed.
LorawanMacHeader::MType GetMType (void)
Get the message type to send when the Send method is called.
Ptr< SatLoraPhyRx > GetPhyRx ()
virtual uint8_t GetTransmissionPower (void)
Get the transmission power this end device is set to use.
void OnDevStatusReq (void)
Perform the actions that need to be taken when receiving a DevStatusReq command.
void OnDutyCycleReq (double dutyCycle)
Perform the actions that need to be taken when receiving a DutyCycleReq command.
void OnLinkAdrReq (uint8_t dataRate, uint8_t txPower, std::list< int > enabledChannels, int repetitions)
Perform the actions that need to be taken when receiving a LinkAdrReq command.
void OnLinkCheckAns (uint8_t margin, uint8_t gwCnt)
Perform the actions that need to be taken when receiving a LinkCheckAns command.
void OnNewChannelReq (uint8_t chIndex, double frequency, uint8_t minDataRate, uint8_t maxDataRate)
Perform the actions that need to be taken when receiving a NewChannelReq command.
void OnRxParamSetupReq (Ptr< RxParamSetupReq > rxParamSetupReq)
Perform the actions that need to be taken when receiving a RxParamSetupReq command.
void ParseCommands (LoraFrameHeader frameHeader)
Parse and take action on the commands contained on this FrameHeader.
virtual void postponeTransmission (Time nextTxDelay, Ptr< Packet >)
Postpone transmission to the specified time and delete previously scheduled transmissions if present.
virtual void Receive (SatPhy::PacketContainer_t packets, Ptr< SatSignalParameters >)
Receive a packet from the lower layer.
virtual void resetRetransmissionParameters ()
Reset retransmission parameters contained in the structure LoraRetxParams.
virtual void Send (Ptr< Packet > packet)
Send a packet.
void SetDataRate (uint8_t dataRate)
Set the data rate this end device will use when transmitting.
void SetDataRateAdaptation (bool adapt)
Enable data rate adaptation in the retransmitting procedure.
void SetDeviceAddress (LoraDeviceAddress address)
Set the network address of this device.
void SetGatewayUpdateCallback (LorawanMacEndDevice::GatewayUpdateCallback cb)
Method to set the gateway address update callback.
void SetGwAddress (Mac48Address gwAddress)
Set address of the GW (or its MAC) serving this UT.
void SetLogicalChannel (uint8_t chIndex, double frequency, uint8_t minDataRate, uint8_t maxDataRate)
Set a new logical channel in the helper.
void SetMaxNumberOfTransmissions (uint8_t maxNumbTx)
Set the maximum number of transmissions allowed.
void SetMType (LorawanMacHeader::MType mType)
Set the message type to send when the Send method is called.
void SetPhyRx (Ptr< SatLoraPhyRx > phyRx)
void SetRaChannel (uint32_t raChannel)
Set RA channel assigned for this UT.
Public Member Functions inherited from ns3::LorawanMac
LorawanMac ()
LorawanMac (uint32_t satId, uint32_t beamId)
virtual ~LorawanMac ()
double GetBandwidthFromDataRate (uint8_t dataRate)
Get the BW corresponding to a data rate, based on this MAC's region.
double GetDbmForTxPower (uint8_t txPower)
Get the transmission power in dBm that corresponds, in this region, to the encoded 8-bit txPower.
Ptr< NetDevice > GetDevice (void)
Get the device this MAC layer is installed on.
LoraLogicalChannelHelper GetLoraLogicalChannelHelper (void)
Get the logical lora channel helper associated with this MAC.
int GetNPreambleSymbols (void)
Get the number of PHY preamble symbols this MAC is set to use.
Time GetOnAirTime (Ptr< Packet > packet, LoraTxParameters txParams)
Compute the time that a packet with certain characteristics will take to be transmitted.
Ptr< SatPhy > GetPhy (void)
Get the underlying PHY layer.
Ptr< SatLoraPhyTx > GetPhyTx (void)
Get the underlying PHY TX layer.
uint8_t GetSfFromDataRate (uint8_t dataRate)
Get the SF corresponding to a data rate, based on this MAC's region.
virtual void Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber)
Send a packet.
void SetBandwidthForDataRate (std::vector< double > bandwidthForDataRate)
Set the vector to use to check up correspondence between bandwidth and DataRate.
void SetDevice (Ptr< NetDevice > device)
Set the device this MAC layer is installed on.
void SetLoraLogicalChannelHelper (LoraLogicalChannelHelper helper)
Set the LoraLogicalChannelHelper this MAC instance will use.
void SetMaxAppPayloadForDataRate (std::vector< uint32_t > maxAppPayloadForDataRate)
Set the maximum App layer payload for a set DataRate.
void SetNPreambleSymbols (int nPreambleSymbols)
Set the number of PHY preamble symbols this MAC is set to use.
void SetPhy (Ptr< SatPhy > phy)
Set the underlying PHY layer.
void SetPhyTx (Ptr< SatLoraPhyTx > phyTx)
Set the underlying PHY TX layer.
void setRegenerative (bool isRegenerative)
Indicates if the satellite is regenerative on the link this layer is sending packets.
void SetReplyDataRateMatrix (ReplyDataRateMatrix replyDataRateMatrix)
Set the matrix to use when deciding with which DataRate to respond.
void SetSfForDataRate (std::vector< uint8_t > sfForDataRate)
Set the vector to use to check up correspondence between SF and DataRate.
void SetTxDbmForTxPower (std::vector< double > txDbmForTxPower)
Set the vector to use to check up which transmission power in Dbm corresponds to a certain TxPower value in this MAC's region.
Public Member Functions inherited from ns3::SatMac
SatMac ()
Construct a SatMac.
SatMac (uint32_t satId, uint32_t beamId, SatEnums::RegenerationMode_t forwardLinkRegenerationMode, SatEnums::RegenerationMode_t returnLinkRegenerationMode)
Construct a SatMac.
~SatMac ()
Destroy a SatMac.
virtual void Disable ()
Disable the MAC layer, i.e.
virtual void Enable ()
Enable the MAC layer, i.e.
Address GetAddress () const
Get MAC address.
uint32_t GetBeamId () const
Get beam ID of the object.
uint32_t GetSatId () const
Get sat ID of the object.
virtual void ReceiveQueueEvent (SatQueue::QueueEvent_t event, uint8_t flowIndex)
Receive a queue event:
uint32_t ReserveIdAndStoreCtrlMsgToContainer (Ptr< SatControlMessage > msg)
Reserve id and store the control message.
uint32_t SendCtrlMsgFromContainer (uint32_t sendId)
Send the control message from the container.
void SetLoraReceiveCallback (SatMac::LoraReceiveCallback cb)
Method to set receive callback.
virtual void SetNodeInfo (Ptr< SatNodeInfo > nodeInfo)
Set the node info.
void SetReadCtrlCallback (SatMac::ReadCtrlMsgCallback cb)
Method to set read control message callback.
void SetReceiveCallback (SatMac::ReceiveCallback cb)
Method to set receive callback.
void SetReserveCtrlCallback (SatMac::ReserveCtrlMsgCallback cb)
Method to set reserve control message id callback.
void SetRoutingUpdateCallback (SatMac::RoutingUpdateCallback cb)
Method to set the routing update callback.
virtual void SetSatelliteAddress (Address satelliteAddress)
Set the satellite MAC address on the other side of this link (if regenerative satellite).
void SetSendCtrlCallback (SatMac::SendCtrlMsgCallback cb)
Method to set send control message callback.
void SetTransmitCallback (SatMac::TransmitCallback cb)
Method to set transmit callback.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::LorawanMacEndDevice
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::LorawanMac
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::SatMac
static TypeId GetTypeId (void)
Derived from Object.
Private Attributes
EventId m_closeFirstWindow
The event of the closing the first receive window.
EventId m_closeSecondWindow
The event of the closing the second receive window.
Time m_firstWindowDelay
Time to wait between end of message transmission and opening of first reception window.
Time m_firstWindowDuration
Duration of first reception window.
SatEnums::PacketType_t m_packetType
Packet type used on RTN channel.
uint8_t m_rx1DrOffset
The RX1DROffset parameter value.
EventId m_secondReceiveWindow
The event of the second receive window opening.
uint8_t m_secondReceiveWindowDataRate
The Data Rate to listen for during the second downlink transmission.
double m_secondReceiveWindowFrequency
The frequency to listen on for the second receive window.
Time m_secondWindowDelay
Time to wait between end of message transmission and opening of second reception window.
Time m_secondWindowDuration
Duration of second reception window.
Ptr< SatSuperframeSeq > m_superframeSeq
Used superframe sequence for the return link.
Additional Inherited Members
Public Types inherited from ns3::LorawanMacEndDevice
typedef Callback< void, Mac48Address > GatewayUpdateCallback
Callback to update gateway address after handover.
Public Types inherited from ns3::LorawanMac
typedef std::array< std::array< uint8_t, 6 >, 8 > ReplyDataRateMatrix
Public Types inherited from ns3::SatMac
typedef Callback< void, Ptr< const Packet > > LoraReceiveCallback
Callback to receive packet by upper layer.
typedef Callback< Ptr< SatControlMessage >, uint32_t > ReadCtrlMsgCallback
Callback to read control messages from container storing control messages.
typedef Callback< void, Ptr< Packet >, Mac48Address, Mac48Address > ReceiveCallback
Callback to receive packet by upper layer.
typedef Callback< uint32_t, Ptr< SatControlMessage > > ReserveCtrlMsgCallback
Callback to reserve an id and initially store the control message.
typedef Callback< void, Address, Address > RoutingUpdateCallback
Callback to update routing and ARP tables after handover.
typedef Callback< uint32_t, uint32_t > SendCtrlMsgCallback
Callback to send a control message and allocate a recv ID for it.
typedef Callback< void, SatPhy::PacketContainer_t, uint32_t, Time, SatSignalParameters::txInfo_s > TransmitCallback
Callback to send packet to lower layer.
Protected Member Functions inherited from ns3::LorawanMacEndDevice
Ptr< LoraLogicalChannel > GetChannelForTx (void)
Find a suitable channel for transmission.
Protected Member Functions inherited from ns3::SatMac
void DoDispose (void)
Dispose of SatMac.
void RxTraces (SatPhy::PacketContainer_t packets)
Invoke the Rx trace source for each received packet.
virtual void SendPacket (SatPhy::PacketContainer_t packets, uint32_t carrierId, Time duration, SatSignalParameters::txInfo_s txInfo)
Send packets to lower layer by using a callback.
void SetTimeTag (SatPhy::PacketContainer_t packets)
Set SatMacTimeTag of packets.
Protected Attributes inherited from ns3::LorawanMacEndDevice
LoraDeviceAddress m_address
The address of this device.
uint8_t m_codingRate
The coding rate used by this device.
TracedValue< uint8_t > m_dataRate
The DataRate this device is using to transmit.
bool m_enableDRAdapt
Enable Data Rate adaptation during the retransmission procedure.
LorawanMacEndDevice::GatewayUpdateCallback m_gatewayUpdateCallback
Gateway address update callback.
Mac48Address m_gwAddress
bool m_headerDisabled
Whether or not the header is disabled for communications by this device.
std::list< Ptr< LorawanMacCommand > > m_macCommandList
List of the MAC commands that need to be applied to the next UL packet.
uint8_t m_maxNumbTx
Maximum number of transmission allowed.
Ptr< SatLoraPhyRx > m_phyRx
Reception phy layer for Lora operations.
uint32_t m_raChannel
RA channel assigned to the UT.
uint8_t m_receiveWindowDurationInSymbols
The duration of a receive window in number of symbols.
TracedCallback< uint8_t, bool, Time, Ptr< Packet > > m_requiredTxCallback
The trace source fired when the transmission procedure is finished.
struct LoraRetxParameters m_retxParams
TracedValue< double > m_txPower
The transmission power this device is using to transmit.
Ptr< UniformRandomVariable > m_uniformRV
An uniform random variable, used by the Shuffle method to randomly reorder the channel list.
Protected Attributes inherited from ns3::LorawanMac
std::vector< double > m_bandwidthForDataRate
A vector holding the bandwidth each Data Rate corresponds to.
uint32_t m_beamId
ID of beam for UT.
TracedCallback< Ptr< const Packet > > m_cannotSendBecauseDutyCycle
The trace source that is fired when a packet cannot be sent because of duty cycle limitations.
LoraLogicalChannelHelper m_channelHelper
The LoraLogicalChannelHelper instance that is assigned to this MAC.
Ptr< NetDevice > m_device
The device this MAC layer is installed on.
bool m_isRegenerative
Indicates if satellite is regenerative on the link where this layer is sending packets.
std::vector< uint32_t > m_maxAppPayloadForDataRate
A vector holding the maximum app payload size that corresponds to a certain DataRate.
int m_nPreambleSymbols
The number of symbols to use in the PHY preamble.
Ptr< SatPhy > m_phy
The PHY instance that sits under this MAC layer.
TracedCallback< Ptr< const Packet > > m_receivedPacket
Trace source that is fired when a packet reaches the MAC layer.
ReplyDataRateMatrix m_replyDataRateMatrix
The matrix that decides the DR the GW will use in a reply based on the ED's sending DR and on the value of the RX1DROffset parameter.
TracedCallback< Ptr< const Packet > > m_sentNewPacket
Trace source that is fired when a new APP layer packet arrives at the MAC layer.
std::vector< uint8_t > m_sfForDataRate
A vector holding the SF each Data Rate corresponds to.
std::vector< double > m_txDbmForTxPower
A vector holding the power that corresponds to a certain TxPower value.
Protected Attributes inherited from ns3::SatMac
Time m_beamEnabledTime
Time of the last beam enable event.
uint32_t m_beamId
The ID of the beam where mac belongs.
TracedCallback< Time > m_beamServiceTrace
Traced callback for beam being disabled and including service time.
SatEnums::RegenerationMode_t m_forwardLinkRegenerationMode
Regeneration mode on forward link.
bool m_isRegenerative
Indicate if satellite is regeneration (at least LINK level) for TX.
bool m_isStatisticsTagsEnabled
EnableStatisticsTags attribute.
Time m_lastDelay
Last delay measurement.
Time m_lastLinkDelay
Last delay measurement for link.
std::queue< Time > m_lastSOF
Store last 3 SOF date for Forward messages, to insert in NCR packets.
std::queue< Ptr< SatNcrMessage > > m_ncrMessagesToSend
List of NCR control messages created but not sent yet.
bool m_ncrV2
Use of version 2 of NCR dates.
Ptr< SatNodeInfo > m_nodeInfo
Node info containing node related information, such as node type, node id and MAC address (of the SatNetDevice)
TracedCallback< Time, SatEnums::SatPacketEvent_t, SatEnums::SatNodeType_t, uint32_t, Mac48Address, SatEnums::SatLogLevel_t, SatEnums::SatLinkDir_t, std::string > m_packetTrace
Trace callback used for packet tracing.
SatMac::ReadCtrlMsgCallback m_readCtrlCallback
The read control message callback.
SatMac::ReserveCtrlMsgCallback m_reserveCtrlCallback
The reserve control message id callback.
SatEnums::RegenerationMode_t m_returnLinkRegenerationMode
Regeneration mode on return link.
SatMac::RoutingUpdateCallback m_routingUpdateCallback
Callback to update routing and ARP tables after a beam handover.
SatMac::ReceiveCallback m_rxCallback
The upper layer package receive callback.
TracedCallback< const Time &, const Address & > m_rxDelayTrace
Traced callback for all received packets, including delay information and the address of the senders.
TracedCallback< const Time &, const Address & > m_rxJitterTrace
Traced callback for all received packets, including jitter information and the address of the senders.
TracedCallback< const Time &, const Address & > m_rxLinkDelayTrace
Traced callback for all received packets, including link delay information and the address of the senders.
TracedCallback< const Time &, const Address & > m_rxLinkJitterTrace
Traced callback for all received packets, including link jitter information and the address of the senders.
SatMac::LoraReceiveCallback m_rxLoraCallback
The upper layer package receive callback.
TracedCallback< Ptr< const Packet >, const Address & > m_rxTrace
Traced callback for all received packets, including the address of the senders.
Address m_satelliteAddress
MAC address of satellite on other side of the link.
uint32_t m_satId
The ID of the sat where mac belongs.
SatMac::SendCtrlMsgCallback m_sendCtrlCallback
The send control message callback.
SatMac::TransmitCallback m_txCallback
The lower layer packet transmit callback.
bool m_txEnabled
Flag indicating whether the MAC is enabled, i.e.
Detailed Description
Class representing the MAC layer of a Class A LoRaWAN device.
Definition at line 39 of file lorawan-mac-end-device-class-a.h.
Constructor & Destructor Documentation
LorawanMacEndDeviceClassA() [1/2]
ns3::LorawanMacEndDeviceClassA::LorawanMacEndDeviceClassA ()
Definition at line 77 of file lorawan-mac-end-device-class-a.cc.
LorawanMacEndDeviceClassA() [2/2]
ns3::LorawanMacEndDeviceClassA::LorawanMacEndDeviceClassA (uint32_t satId, uint32_t beamId, Ptr< SatSuperframeSeq > seq)
Definition at line 82 of file lorawan-mac-end-device-class-a.cc.
References m_closeFirstWindow, m_closeSecondWindow, and m_secondReceiveWindow.
~LorawanMacEndDeviceClassA()
ns3::LorawanMacEndDeviceClassA::~LorawanMacEndDeviceClassA () virtual
Definition at line 104 of file lorawan-mac-end-device-class-a.cc.
Member Function Documentation
CloseFirstReceiveWindow()
void ns3::LorawanMacEndDeviceClassA::CloseFirstReceiveWindow (void)
Perform operations needed to close the first receive window.
Definition at line 460 of file lorawan-mac-end-device-class-a.cc.
References ns3::LorawanMacEndDevice::m_phyRx, ns3::SatLoraPhyRx::RX, ns3::SatLoraPhyRx::SLEEP, ns3::SatLoraPhyRx::STANDBY, and ns3::SatLoraPhyRx::TX.
Referenced by OpenFirstReceiveWindow().
CloseSecondReceiveWindow()
void ns3::LorawanMacEndDeviceClassA::CloseSecondReceiveWindow (void)
Perform operations needed to close the second receive window.
Definition at line 520 of file lorawan-mac-end-device-class-a.cc.
References ns3::LorawanMacEndDevice::LoraRetxParameters::firstAttempt, ns3::LorawanMacEndDevice::m_maxNumbTx, ns3::LorawanMacEndDevice::m_phyRx, ns3::LorawanMacEndDevice::m_requiredTxCallback, ns3::LorawanMacEndDevice::m_retxParams, ns3::LorawanMacEndDevice::LoraRetxParameters::packet, ns3::LorawanMacEndDevice::resetRetransmissionParameters(), ns3::LorawanMacEndDevice::LoraRetxParameters::retxLeft, ns3::SatLoraPhyRx::RX, ns3::LorawanMacEndDevice::Send(), ns3::SatLoraPhyRx::SLEEP, ns3::SatLoraPhyRx::STANDBY, ns3::SatLoraPhyRx::TX, and ns3::LorawanMacEndDevice::LoraRetxParameters::waitingAck.
Referenced by OpenSecondReceiveWindow().
FailedReception()
void ns3::LorawanMacEndDeviceClassA::FailedReception (Ptr< const Packet > packet) virtual
Function called by lower layers to inform this layer that reception of a packet we were locked on failed.
Parameters
packet the packet we failed to receive
Reimplemented from ns3::LorawanMacEndDevice.
Definition at line 368 of file lorawan-mac-end-device-class-a.cc.
References ns3::LorawanMacEndDevice::LoraRetxParameters::firstAttempt, ns3::LorawanMacEndDevice::m_maxNumbTx, ns3::LorawanMacEndDevice::m_phyRx, ns3::LorawanMacEndDevice::m_requiredTxCallback, ns3::LorawanMacEndDevice::m_retxParams, m_secondReceiveWindow, ns3::LorawanMacEndDevice::LoraRetxParameters::packet, ns3::LorawanMacEndDevice::resetRetransmissionParameters(), ns3::LorawanMacEndDevice::LoraRetxParameters::retxLeft, ns3::LorawanMacEndDevice::Send(), and ns3::LorawanMacEndDevice::LoraRetxParameters::waitingAck.
GetFirstReceiveWindowDataRate()
uint8_t ns3::LorawanMacEndDeviceClassA::GetFirstReceiveWindowDataRate (void)
Get the Data Rate that will be used in the first receive window.
Returns
The Data Rate
Definition at line 634 of file lorawan-mac-end-device-class-a.cc.
References ns3::LorawanMacEndDevice::m_dataRate, ns3::LorawanMac::m_replyDataRateMatrix, and m_rx1DrOffset.
Referenced by SendToPhy().
GetNextClassTransmissionDelay()
Time ns3::LorawanMacEndDeviceClassA::GetNextClassTransmissionDelay (Time waitingTime) virtual
Find the minimum waiting time before the next possible transmission based on End Device's Class Type.
Parameters
waitingTime The minimum waiting time that has to be respected, irrespective of the class (e.g., because of duty cycle limitations).
Reimplemented from ns3::LorawanMacEndDevice.
Definition at line 590 of file lorawan-mac-end-device-class-a.cc.
References ns3::LorawanMac::GetBandwidthFromDataRate(), GetSecondReceiveWindowDataRate(), ns3::LorawanMac::GetSfFromDataRate(), m_closeFirstWindow, m_closeSecondWindow, ns3::LorawanMacEndDevice::m_receiveWindowDurationInSymbols, ns3::LorawanMacEndDevice::m_retxParams, m_secondReceiveWindow, ns3::LorawanMacEndDevice::m_uniformRV, and ns3::LorawanMacEndDevice::LoraRetxParameters::waitingAck.
GetSecondReceiveWindowDataRate()
uint8_t ns3::LorawanMacEndDeviceClassA::GetSecondReceiveWindowDataRate (void)
Get the Data Rate that will be used in the second receive window.
Returns
The Data Rate
Definition at line 646 of file lorawan-mac-end-device-class-a.cc.
References m_secondReceiveWindowDataRate.
Referenced by GetNextClassTransmissionDelay().
GetSecondReceiveWindowFrequency()
double ns3::LorawanMacEndDeviceClassA::GetSecondReceiveWindowFrequency (void)
Get the frequency that is used for the second receive window.
Returns
The frequency, in MHz
Definition at line 658 of file lorawan-mac-end-device-class-a.cc.
References m_secondReceiveWindowFrequency.
GetTypeId()
TypeId ns3::LorawanMacEndDeviceClassA::GetTypeId (void) static
Definition at line 46 of file lorawan-mac-end-device-class-a.cc.
References m_firstWindowDelay, m_firstWindowDuration, m_secondWindowDelay, and m_secondWindowDuration.
OnRxClassParamSetupReq()
void ns3::LorawanMacEndDeviceClassA::OnRxClassParamSetupReq (Ptr< RxParamSetupReq > rxParamSetupReq) virtual
Perform the actions that need to be taken when receiving a RxParamSetupReq command based on the Device's Class Type.
Parameters
rxParamSetupReq The Parameter Setup Request, which contains:
The offset to set.
The data rate to use for the second receive window.
The frequency to use for the second receive window.
Reimplemented from ns3::LorawanMacEndDevice.
Definition at line 668 of file lorawan-mac-end-device-class-a.cc.
References ns3::LorawanMac::GetBandwidthFromDataRate(), ns3::LorawanMac::GetSfFromDataRate(), ns3::LorawanMacEndDevice::m_macCommandList, m_rx1DrOffset, m_secondReceiveWindowDataRate, and m_secondReceiveWindowFrequency.
OpenFirstReceiveWindow()
void ns3::LorawanMacEndDeviceClassA::OpenFirstReceiveWindow (void)
Perform operations needed to open the first receive window.
Definition at line 444 of file lorawan-mac-end-device-class-a.cc.
References CloseFirstReceiveWindow(), m_closeFirstWindow, m_firstWindowDuration, and ns3::LorawanMacEndDevice::m_phyRx.
Referenced by TxFinished().
OpenSecondReceiveWindow()
void ns3::LorawanMacEndDeviceClassA::OpenSecondReceiveWindow (void)
Perform operations needed to open the second receive window.
Definition at line 489 of file lorawan-mac-end-device-class-a.cc.
References CloseSecondReceiveWindow(), ns3::LorawanMac::GetSfFromDataRate(), m_closeSecondWindow, ns3::LorawanMacEndDevice::m_phyRx, m_secondReceiveWindowDataRate, m_secondReceiveWindowFrequency, m_secondWindowDuration, and ns3::SatLoraPhyRx::RX.
Referenced by TxFinished().
Receive()
void ns3::LorawanMacEndDeviceClassA::Receive (Ptr< Packet > packet) virtual
Receive a packet.
This method is typically registered as a callback in the underlying PHY layer so that it's called when a packet is going up the stack.
Parameters
packet the received packet.
Implements ns3::LorawanMacEndDevice.
Definition at line 246 of file lorawan-mac-end-device-class-a.cc.
References ns3::LorawanMacEndDevice::LoraRetxParameters::firstAttempt, ns3::LoraFrameHeader::GetAddress(), ns3::LorawanMacHeader::IsUplink(), ns3::LorawanMacEndDevice::m_address, ns3::LorawanMacEndDevice::m_maxNumbTx, ns3::SatMac::m_nodeInfo, ns3::LorawanMacEndDevice::m_phyRx, ns3::LorawanMac::m_receivedPacket, ns3::LorawanMacEndDevice::m_requiredTxCallback, ns3::LorawanMacEndDevice::m_retxParams, m_secondReceiveWindow, ns3::LorawanMacEndDevice::LoraRetxParameters::packet, ns3::LorawanMacEndDevice::ParseCommands(), ns3::LorawanMacEndDevice::resetRetransmissionParameters(), ns3::LorawanMacEndDevice::LoraRetxParameters::retxLeft, ns3::SatMac::RxTraces(), ns3::LorawanMacEndDevice::Send(), ns3::LoraFrameHeader::SetAsDownlink(), ns3::SatMacTag::SetDestAddress(), ns3::SatAddressE2ETag::SetE2EDestAddress(), and ns3::LorawanMacEndDevice::LoraRetxParameters::waitingAck.
SendToPhy()
void ns3::LorawanMacEndDeviceClassA::SendToPhy (Ptr< Packet > packet) virtual
Add headers and send a packet with the sending function of the physical layer.
Parameters
packet the packet to send
Reimplemented from ns3::LorawanMacEndDevice.
Definition at line 114 of file lorawan-mac-end-device-class-a.cc.
References ns3::LoraLogicalChannelHelper::AddEvent(), ns3::LoraTxParameters::bandwidthHz, ns3::LoraTxParameters::codingRate, ns3::LoraTxParameters::crcEnabled, ns3::SatSignalParameters::txInfo_s::fecBlockSizeInBytes, ns3::SatSignalParameters::txInfo_s::frameType, ns3::LorawanMac::GetBandwidthFromDataRate(), ns3::LorawanMacEndDevice::GetChannelForTx(), ns3::SatUtils::GetCodingRate(), GetFirstReceiveWindowDataRate(), ns3::LorawanMac::GetOnAirTime(), ns3::LorawanMac::GetSfFromDataRate(), ns3::LoraTxParameters::headerDisabled, ns3::LoraTxParameters::lowDataRateOptimizationEnabled, ns3::LorawanMac::m_channelHelper, ns3::LorawanMacEndDevice::m_dataRate, ns3::LorawanMac::m_device, ns3::LorawanMacEndDevice::m_enableDRAdapt, ns3::LorawanMacEndDevice::m_gwAddress, ns3::LorawanMacEndDevice::m_headerDisabled, ns3::SatMac::m_isStatisticsTagsEnabled, ns3::LorawanMacEndDevice::m_maxNumbTx, ns3::SatMac::m_nodeInfo, ns3::LorawanMac::m_nPreambleSymbols, m_packetType, ns3::LorawanMac::m_phy, ns3::LorawanMacEndDevice::m_phyRx, ns3::LorawanMacEndDevice::m_retxParams, m_rx1DrOffset, m_superframeSeq, ns3::LorawanMacEndDevice::m_txPower, ns3::SatSignalParameters::txInfo_s::modCod, ns3::LoraTxParameters::nPreamble, ns3::SatSignalParameters::txInfo_s::packetType, ns3::LorawanMacEndDevice::LoraRetxParameters::retxLeft, ns3::LoraTag::SetDataRate(), ns3::SatMacTag::SetDestAddress(), ns3::SatAddressE2ETag::SetE2EDestAddress(), ns3::SatAddressE2ETag::SetE2ESourceAddress(), ns3::LoraTag::SetFrequency(), ns3::LoraTag::SetModcod(), ns3::SatMacTag::SetSourceAddress(), ns3::LoraTxParameters::sf, ns3::SatConstVariables::SUPERFRAME_SEQUENCE, ns3::SatEnums::UNDEFINED_FRAME, and ns3::SatSignalParameters::txInfo_s::waveformId.
SetRaModel()
void ns3::LorawanMacEndDeviceClassA::SetRaModel (SatEnums::RandomAccessModel_t randomAccessModel)
Set the random access model.
Parameters
randomAccessModel The model to use.
Definition at line 418 of file lorawan-mac-end-device-class-a.cc.
References m_packetType, ns3::SatEnums::PACKET_TYPE_CRDSA, ns3::SatEnums::PACKET_TYPE_DEDICATED_ACCESS, ns3::SatEnums::PACKET_TYPE_ESSA, ns3::SatEnums::PACKET_TYPE_SLOTTED_ALOHA, ns3::SatEnums::RA_MODEL_CRDSA, ns3::SatEnums::RA_MODEL_ESSA, ns3::SatEnums::RA_MODEL_MARSALA, ns3::SatEnums::RA_MODEL_OFF, ns3::SatEnums::RA_MODEL_RCS2_SPECIFICATION, and ns3::SatEnums::RA_MODEL_SLOTTED_ALOHA.
SetSecondReceiveWindowDataRate()
void ns3::LorawanMacEndDeviceClassA::SetSecondReceiveWindowDataRate (uint8_t dataRate)
Set the Data Rate to be used in the second receive window.
Parameters
dataRate The Data Rate.
Definition at line 640 of file lorawan-mac-end-device-class-a.cc.
References m_secondReceiveWindowDataRate.
SetSecondReceiveWindowFrequency()
void ns3::LorawanMacEndDeviceClassA::SetSecondReceiveWindowFrequency (double frequencyMHz)
Set the frequency that will be used for the second receive window.
Parameters
frequencyMHz the Frequency.
Definition at line 652 of file lorawan-mac-end-device-class-a.cc.
References m_secondReceiveWindowFrequency.
TxFinished()
void ns3::LorawanMacEndDeviceClassA::TxFinished () virtual
Perform the actions that are required after a packet send.
This function handles opening of the first receive window.
Reimplemented from ns3::LorawanMacEndDevice.
Definition at line 397 of file lorawan-mac-end-device-class-a.cc.
References m_firstWindowDelay, ns3::LorawanMacEndDevice::m_phyRx, m_secondReceiveWindow, m_secondWindowDelay, OpenFirstReceiveWindow(), and OpenSecondReceiveWindow().
Member Data Documentation
m_closeFirstWindow
EventId ns3::LorawanMacEndDeviceClassA::m_closeFirstWindow private
The event of the closing the first receive window.
This Event will be canceled if there's a successful reception of a packet.
Definition at line 208 of file lorawan-mac-end-device-class-a.h.
Referenced by LorawanMacEndDeviceClassA(), GetNextClassTransmissionDelay(), and OpenFirstReceiveWindow().
m_closeSecondWindow
EventId ns3::LorawanMacEndDeviceClassA::m_closeSecondWindow private
The event of the closing the second receive window.
This Event will be canceled if there's a successful reception of a packet.
Definition at line 215 of file lorawan-mac-end-device-class-a.h.
Referenced by LorawanMacEndDeviceClassA(), GetNextClassTransmissionDelay(), and OpenSecondReceiveWindow().
m_firstWindowDelay
Time ns3::LorawanMacEndDeviceClassA::m_firstWindowDelay private
Time to wait between end of message transmission and opening of first reception window.
Definition at line 186 of file lorawan-mac-end-device-class-a.h.
Referenced by GetTypeId(), and TxFinished().
m_firstWindowDuration
Time ns3::LorawanMacEndDeviceClassA::m_firstWindowDuration private
Duration of first reception window.
Definition at line 196 of file lorawan-mac-end-device-class-a.h.
Referenced by GetTypeId(), and OpenFirstReceiveWindow().
m_packetType
SatEnums::PacketType_t ns3::LorawanMacEndDeviceClassA::m_packetType private
Packet type used on RTN channel.
Definition at line 181 of file lorawan-mac-end-device-class-a.h.
Referenced by SendToPhy(), and SetRaModel().
m_rx1DrOffset
uint8_t ns3::LorawanMacEndDeviceClassA::m_rx1DrOffset private
The RX1DROffset parameter value.
Definition at line 238 of file lorawan-mac-end-device-class-a.h.
Referenced by GetFirstReceiveWindowDataRate(), OnRxClassParamSetupReq(), and SendToPhy().
m_secondReceiveWindow
EventId ns3::LorawanMacEndDeviceClassA::m_secondReceiveWindow private
The event of the second receive window opening.
This Event is used to cancel the second window in case the first one is successful.
Definition at line 223 of file lorawan-mac-end-device-class-a.h.
Referenced by LorawanMacEndDeviceClassA(), FailedReception(), GetNextClassTransmissionDelay(), Receive(), and TxFinished().
m_secondReceiveWindowDataRate
uint8_t ns3::LorawanMacEndDeviceClassA::m_secondReceiveWindowDataRate private
The Data Rate to listen for during the second downlink transmission.
Definition at line 233 of file lorawan-mac-end-device-class-a.h.
Referenced by GetSecondReceiveWindowDataRate(), OnRxClassParamSetupReq(), OpenSecondReceiveWindow(), and SetSecondReceiveWindowDataRate().
m_secondReceiveWindowFrequency
double ns3::LorawanMacEndDeviceClassA::m_secondReceiveWindowFrequency private
The frequency to listen on for the second receive window.
Definition at line 228 of file lorawan-mac-end-device-class-a.h.
Referenced by GetSecondReceiveWindowFrequency(), OnRxClassParamSetupReq(), OpenSecondReceiveWindow(), and SetSecondReceiveWindowFrequency().
m_secondWindowDelay
Time ns3::LorawanMacEndDeviceClassA::m_secondWindowDelay private
Time to wait between end of message transmission and opening of second reception window.
Definition at line 191 of file lorawan-mac-end-device-class-a.h.
Referenced by GetTypeId(), and TxFinished().
m_secondWindowDuration
Time ns3::LorawanMacEndDeviceClassA::m_secondWindowDuration private
Duration of second reception window.
Definition at line 201 of file lorawan-mac-end-device-class-a.h.
Referenced by GetTypeId(), and OpenSecondReceiveWindow().
m_superframeSeq
Ptr<SatSuperframeSeq> ns3::LorawanMacEndDeviceClassA::m_superframeSeq private
Used superframe sequence for the return link.
Definition at line 176 of file lorawan-mac-end-device-class-a.h.
Referenced by SendToPhy().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/lorawan-mac-end-device-class-a.h
/builds/sns3/satellite/satellite/model/lorawan-mac-end-device-class-a.cc