SNS3
ns3::SatOutputFileStreamStringContainer Class Reference
Class for output file stream container for strings.
#include "satellite-output-fstream-string-container.h"
Public Member Functions
SatOutputFileStreamStringContainer ()
Constructor.
SatOutputFileStreamStringContainer (std::string filename, std::ios::openmode filemode)
Constructor.
~SatOutputFileStreamStringContainer ()
Destructor.
void AddToContainer (std::string newLine)
Function for adding the line to container.
void DoDispose ()
Do needed dispose actions.
void WriteContainerToFile ()
Function for writing the container contents to file.
Static Public Member Functions
static TypeId GetTypeId (void)
NS-3 function for type id.
Private Member Functions
void ClearContainer ()
Function for clearing the container.
void OpenStream ()
Function for opening the output file stream.
void Reset ()
Function for resetting the variables.
void ResetStream ()
Function for resetting the stream.
Private Attributes
std::vector< std::string > m_container
Container for lines.
std::ios::openmode m_fileMode
File mode.
std::string m_fileName
File name.
std::ofstream * m_outputFileStream
Pointer to output file stream.
SatOutputFileStreamWrapper * m_outputFileStreamWrapper
Pointer to output file stream wrapper.
Detailed Description
Class for output file stream container for strings.
The class implements storing the values and writing the stored values into a file.
Definition at line 41 of file satellite-output-fstream-string-container.h.
Constructor & Destructor Documentation
SatOutputFileStreamStringContainer() [1/2]
ns3::SatOutputFileStreamStringContainer::SatOutputFileStreamStringContainer (std::string filename, std::ios::openmode filemode)
Constructor.
Parameters
filename file name
filemode file mode
Definition at line 41 of file satellite-output-fstream-string-container.cc.
References m_fileMode, and m_fileName.
SatOutputFileStreamStringContainer() [2/2]
ns3::SatOutputFileStreamStringContainer::SatOutputFileStreamStringContainer ()
Constructor.
Definition at line 52 of file satellite-output-fstream-string-container.cc.
~SatOutputFileStreamStringContainer()
ns3::SatOutputFileStreamStringContainer::~SatOutputFileStreamStringContainer ()
Destructor.
Definition at line 64 of file satellite-output-fstream-string-container.cc.
References Reset().
Member Function Documentation
AddToContainer()
void ns3::SatOutputFileStreamStringContainer::AddToContainer (std::string newLine)
Function for adding the line to container.
Definition at line 104 of file satellite-output-fstream-string-container.cc.
References m_container.
ClearContainer()
void ns3::SatOutputFileStreamStringContainer::ClearContainer () private
Function for clearing the container.
Definition at line 146 of file satellite-output-fstream-string-container.cc.
References m_container.
Referenced by Reset().
DoDispose()
void ns3::SatOutputFileStreamStringContainer::DoDispose (void)
Do needed dispose actions.
Definition at line 72 of file satellite-output-fstream-string-container.cc.
References Reset().
GetTypeId()
TypeId ns3::SatOutputFileStreamStringContainer::GetTypeId (void) static
NS-3 function for type id.
Returns
type id
Definition at line 33 of file satellite-output-fstream-string-container.cc.
OpenStream()
void ns3::SatOutputFileStreamStringContainer::OpenStream () private
Function for opening the output file stream.
Definition at line 112 of file satellite-output-fstream-string-container.cc.
References ns3::SatOutputFileStreamWrapper::GetStream(), m_fileMode, m_fileName, m_outputFileStream, and m_outputFileStreamWrapper.
Referenced by WriteContainerToFile().
Reset()
void ns3::SatOutputFileStreamStringContainer::Reset (void) private
Function for resetting the variables.
Definition at line 121 of file satellite-output-fstream-string-container.cc.
References ClearContainer(), and ResetStream().
Referenced by ~SatOutputFileStreamStringContainer(), DoDispose(), and WriteContainerToFile().
ResetStream()
void ns3::SatOutputFileStreamStringContainer::ResetStream () private
Function for resetting the stream.
Definition at line 130 of file satellite-output-fstream-string-container.cc.
References m_fileMode, m_fileName, m_outputFileStream, and m_outputFileStreamWrapper.
Referenced by Reset().
WriteContainerToFile()
void ns3::SatOutputFileStreamStringContainer::WriteContainerToFile ()
Function for writing the container contents to file.
Definition at line 81 of file satellite-output-fstream-string-container.cc.
References m_container, m_outputFileStream, OpenStream(), and Reset().
Member Data Documentation
m_container
std::vector<std::string> ns3::SatOutputFileStreamStringContainer::m_container private
Container for lines.
Definition at line 116 of file satellite-output-fstream-string-container.h.
Referenced by AddToContainer(), ClearContainer(), and WriteContainerToFile().
m_fileMode
std::ios::openmode ns3::SatOutputFileStreamStringContainer::m_fileMode private
File mode.
Definition at line 126 of file satellite-output-fstream-string-container.h.
Referenced by SatOutputFileStreamStringContainer(), OpenStream(), and ResetStream().
m_fileName
std::string ns3::SatOutputFileStreamStringContainer::m_fileName private
File name.
Definition at line 121 of file satellite-output-fstream-string-container.h.
Referenced by SatOutputFileStreamStringContainer(), OpenStream(), and ResetStream().
m_outputFileStream
std::ofstream* ns3::SatOutputFileStreamStringContainer::m_outputFileStream private
Pointer to output file stream.
Definition at line 111 of file satellite-output-fstream-string-container.h.
Referenced by OpenStream(), ResetStream(), and WriteContainerToFile().
m_outputFileStreamWrapper
SatOutputFileStreamWrapper* ns3::SatOutputFileStreamStringContainer::m_outputFileStreamWrapper private
Pointer to output file stream wrapper.
Definition at line 106 of file satellite-output-fstream-string-container.h.
Referenced by OpenStream(), and ResetStream().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/utils/satellite-output-fstream-string-container.h
/builds/sns3/satellite/satellite/utils/satellite-output-fstream-string-container.cc