SNS3
ns3::SatStatsUserSlottedAlohaPacketErrorHelper Class Reference
Satellite Statistics
Produce packet error statistics of Random Access Slotted ALOHA on user link from a satellite module simulation.
#include "satellite-stats-packet-error-helper.h"
Public Member Functions
SatStatsUserSlottedAlohaPacketErrorHelper (Ptr< const SatHelper > satHelper)
virtual ~SatStatsUserSlottedAlohaPacketErrorHelper ()
/ Destructor.
Public Member Functions inherited from ns3::SatStatsPacketErrorHelper
SatStatsPacketErrorHelper (Ptr< const SatHelper > satHelper)
virtual ~SatStatsPacketErrorHelper ()
/ Destructor.
void ErrorRxCallback (uint32_t nPackets, const Address &fromOrTo, bool isError)
Receive inputs from trace sources and determine the right collector to forward the inputs to.
SatEnums::ChannelType_t GetChannelType () const
std::string GetTraceSourceName () const
SatPhyRxCarrier::CarrierType GetValidCarrierType () const
Get the valid carrier type.
void SetChannelType (SatEnums::ChannelType_t channelType)
void SetTraceSourceName (std::string traceSourceName)
Public Member Functions inherited from ns3::SatStatsHelper
SatStatsHelper (Ptr< const SatHelper > satHelper)
Creates a new helper instance.
virtual ~SatStatsHelper ()
/ Destructor.
IdentifierType_t GetIdentifierType () const
std::string GetName () const
OutputType_t GetOutputType () const
Ptr< const SatHelper > GetSatHelper () const
void Install ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
bool IsInstalled () const
void SetIdentifierType (IdentifierType_t identifierType)
void SetName (std::string name)
void SetOutputType (OutputType_t outputType)
Static Public Member Functions
static TypeId GetTypeId ()
inherited from ObjectBase base class
Static Public Member Functions inherited from ns3::SatStatsPacketErrorHelper
static TypeId GetTypeId ()
inherited from ObjectBase base class
Static Public Member Functions inherited from ns3::SatStatsHelper
static std::string GetIdentifierTypeName (IdentifierType_t identifierType)
static std::string GetOutputTypeName (OutputType_t outputType)
static TypeId GetTypeId ()
inherited from ObjectBase base class
Additional Inherited Members
Public Types inherited from ns3::SatStatsHelper
enum IdentifierType_t {
IDENTIFIER_GLOBAL = 0 , IDENTIFIER_GW , IDENTIFIER_BEAM , IDENTIFIER_UT ,
IDENTIFIER_UT_USER , IDENTIFIER_SLICE , IDENTIFIER_GROUP , IDENTIFIER_SAT ,
IDENTIFIER_ISL
}
Possible categorization of statistics output.
enum OutputType_t {
OUTPUT_NONE = 0 , OUTPUT_SCALAR_FILE , OUTPUT_SCATTER_FILE , OUTPUT_HISTOGRAM_FILE ,
OUTPUT_PDF_FILE , OUTPUT_CDF_FILE , OUTPUT_SCALAR_PLOT , OUTPUT_SCATTER_PLOT ,
OUTPUT_HISTOGRAM_PLOT , OUTPUT_PDF_PLOT , OUTPUT_CDF_PLOT
}
Possible types and formats of statistics output.
Protected Member Functions inherited from ns3::SatStatsPacketErrorHelper
void DoInstall ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
void SetValidCarrierType (SatPhyRxCarrier::CarrierType carrierType)
Set valid carrier type for this statistics helper type.
Protected Member Functions inherited from ns3::SatStatsHelper
Ptr< DataCollectionObject > CreateAggregator (std::string aggregatorTypeId, std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue())
Create the aggregator according to the output type.
uint32_t CreateCollectorPerIdentifier (CollectorMap &collectorMap) const
Create one collector instance for each identifier in the simulation.
virtual std::string GetDistributionHeading (std::string dataLabel) const
uint32_t GetGwId (Ptr< Node > gwNode) const
uint32_t GetIdentifierForBeam (uint32_t satId, uint32_t beamId) const
uint32_t GetIdentifierForGroup (uint32_t groupId) const
uint32_t GetIdentifierForGw (Ptr< Node > gwNode) const
uint32_t GetIdentifierForIsl (Ptr< Node > satNodeSrc, Ptr< Node > satNodeDst) const
uint32_t GetIdentifierForSat (Ptr< Node > satNode) const
uint32_t GetIdentifierForUt (Ptr< Node > utNode) const
uint32_t GetIdentifierForUtUser (Ptr< Node > utUserNode) const
virtual std::string GetIdentifierHeading (std::string dataLabel) const
virtual std::string GetOutputFileName () const
Compute the path and file name where statistics output should be written to.
virtual std::string GetOutputPath () const
uint32_t GetSatId (Ptr< Node > satNode) const
virtual std::string GetTimeHeading (std::string dataLabel) const
uint32_t GetUtId (Ptr< Node > utNode) const
uint32_t GetUtUserId (Ptr< Node > utUserNode) const
Static Protected Member Functions inherited from ns3::SatStatsHelper
static NetDeviceContainer GetGwSatNetDevice (Ptr< Node > gwNode)
static Ptr< NetDevice > GetSatSatGeoNetDevice (Ptr< Node > satNode)
static Ptr< NetDevice > GetUtSatNetDevice (Ptr< Node > utNode)
Detailed Description
Produce packet error statistics of Random Access Slotted ALOHA on user link from a satellite module simulation.
For a more convenient usage in simulation script, it is recommended to use the corresponding methods in SatStatsHelperContainer class.
Otherwise, the following example can be used:
Ptr<SatStatsUserSlottedAlohaPacketErrorHelper> s =
Create<SatStatsUserSlottedAlohaPacketErrorHelper> (satHelper); s->SetName ("name");
s->SetIdentifierType (SatStatsHelper::IDENTIFIER_GLOBAL);
s->SetOutputType (SatStatsHelper::OUTPUT_SCATTER_FILE);
s->Install ();
Definition at line 373 of file satellite-stats-packet-error-helper.h.
Constructor & Destructor Documentation
SatStatsUserSlottedAlohaPacketErrorHelper()
ns3::SatStatsUserSlottedAlohaPacketErrorHelper::SatStatsUserSlottedAlohaPacketErrorHelper (Ptr< const SatHelper > satHelper)
Definition at line 818 of file satellite-stats-packet-error-helper.cc.
References ns3::SatPhyRxCarrier::RA_SLOTTED_ALOHA, ns3::SatEnums::RETURN_USER_CH, ns3::SatStatsPacketErrorHelper::SetChannelType(), ns3::SatStatsPacketErrorHelper::SetTraceSourceName(), and ns3::SatStatsPacketErrorHelper::SetValidCarrierType().
~SatStatsUserSlottedAlohaPacketErrorHelper()
ns3::SatStatsUserSlottedAlohaPacketErrorHelper::~SatStatsUserSlottedAlohaPacketErrorHelper () virtual
/ Destructor.
Definition at line 828 of file satellite-stats-packet-error-helper.cc.
Member Function Documentation
GetTypeId()
TypeId ns3::SatStatsUserSlottedAlohaPacketErrorHelper::GetTypeId (void) static
inherited from ObjectBase base class
Definition at line 834 of file satellite-stats-packet-error-helper.cc.
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/stats/satellite-stats-packet-error-helper.h
/builds/sns3/satellite/satellite/stats/satellite-stats-packet-error-helper.cc