SNS3
ns3::LoraBeamTag Class Reference
Tag used to save various data about a packet, like its Spreading Factor and data about interference.
#include "lora-beam-tag.h"
Public Member Functions
LoraBeamTag (uint8_t beamId=0)
Create a LoraBeamTag with a given beam ID.
virtual ~LoraBeamTag ()
virtual void Deserialize (TagBuffer i)
uint8_t GetBeamId () const
Read which beam ID this packet was transmitted with.
virtual TypeId GetInstanceTypeId (void) const
virtual uint32_t GetSerializedSize () const
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer i) const
void SetBeamId (uint8_t beamId)
Set which beamId this packet was transmitted with.
Static Public Member Functions
static TypeId GetTypeId (void)
Private Attributes
uint8_t m_beamId
The beam ID used by the packet.
Detailed Description
Tag used to save various data about a packet, like its Spreading Factor and data about interference.
Definition at line 33 of file lora-beam-tag.h.
Constructor & Destructor Documentation
LoraBeamTag()
ns3::LoraBeamTag::LoraBeamTag (uint8_t beamId = 0)
Create a LoraBeamTag with a given beam ID.
Parameters
beamId The beam ID associated to this packet
Definition at line 45 of file lora-beam-tag.cc.
~LoraBeamTag()
ns3::LoraBeamTag::~LoraBeamTag () virtual
Definition at line 50 of file lora-beam-tag.cc.
Member Function Documentation
Deserialize()
void ns3::LoraBeamTag::Deserialize (TagBuffer i) virtual
Definition at line 67 of file lora-beam-tag.cc.
References m_beamId.
GetBeamId()
uint8_t ns3::LoraBeamTag::GetBeamId () const
Read which beam ID this packet was transmitted with.
Returns
This tag's packet's beam ID.
Definition at line 79 of file lora-beam-tag.cc.
References m_beamId.
Referenced by ns3::LoraEndDeviceStatus::InsertReceivedPacket(), and ns3::LoraForwarder::ReceiveFromPointToPoint().
GetInstanceTypeId()
TypeId ns3::LoraBeamTag::GetInstanceTypeId (void) const virtual
Definition at line 40 of file lora-beam-tag.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::LoraBeamTag::GetSerializedSize (void) const virtual
Definition at line 55 of file lora-beam-tag.cc.
GetTypeId()
TypeId ns3::LoraBeamTag::GetTypeId (void) static
Definition at line 33 of file lora-beam-tag.cc.
Referenced by GetInstanceTypeId().
Print()
void ns3::LoraBeamTag::Print (std::ostream & os) const virtual
Definition at line 73 of file lora-beam-tag.cc.
References m_beamId.
Serialize()
void ns3::LoraBeamTag::Serialize (TagBuffer i) const virtual
Definition at line 61 of file lora-beam-tag.cc.
References m_beamId.
SetBeamId()
void ns3::LoraBeamTag::SetBeamId (uint8_t beamId)
Set which beamId this packet was transmitted with.
Parameters
beamId The beam ID.
Definition at line 85 of file lora-beam-tag.cc.
References m_beamId.
Referenced by ns3::LoraNetworkStatus::GetReplyForDevice().
Member Data Documentation
m_beamId
uint8_t ns3::LoraBeamTag::m_beamId private
The beam ID used by the packet.
Definition at line 68 of file lora-beam-tag.h.
Referenced by Deserialize(), GetBeamId(), Print(), Serialize(), and SetBeamId().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/lora-beam-tag.h
/builds/sns3/satellite/satellite/model/lora-beam-tag.cc