SNS3
ns3::SatMacLinkTimeTag Class Reference
Time tag used to identify the time when packet is enqueued at MAC on current link level.
#include "satellite-time-tag.h"
Public Member Functions
SatMacLinkTimeTag ()
Default constructor.
SatMacLinkTimeTag (Time senderTimestamp)
Constructor with initialization parameters.
virtual void Deserialize (TagBuffer i)
Deserializes information from buffer to this instance of SatMacLinkTimeTag.
virtual TypeId GetInstanceTypeId (void) const
Get the type ID of instance.
Time GetSenderLinkTimestamp (void) const
Get sender time stamp of this tag.
virtual uint32_t GetSerializedSize () const
Get serialized size of SatMacLinkTimeTag.
virtual void Print (std::ostream &os) const
Print time stamp of this instance of SatMacLinkTimeTag.
virtual void Serialize (TagBuffer i) const
Serializes information to buffer from this instance of SatMacLinkTimeTag.
void SetSenderLinkTimestamp (Time senderLinkTimestamp)
Set sender time stamp of this tag.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Time m_senderLinkTimestamp
Detailed Description
Time tag used to identify the time when packet is enqueued at MAC on current link level.
Definition at line 325 of file satellite-time-tag.h.
Constructor & Destructor Documentation
SatMacLinkTimeTag() [1/2]
ns3::SatMacLinkTimeTag::SatMacLinkTimeTag ()
Default constructor.
Definition at line 311 of file satellite-time-tag.cc.
SatMacLinkTimeTag() [2/2]
ns3::SatMacLinkTimeTag::SatMacLinkTimeTag (Time senderTimestamp)
Constructor with initialization parameters.
Parameters
senderTimestamp
Definition at line 317 of file satellite-time-tag.cc.
Member Function Documentation
Deserialize()
void ns3::SatMacLinkTimeTag::Deserialize (TagBuffer i) virtual
Deserializes information from buffer to this instance of SatMacLinkTimeTag.
Parameters
i Buffer from which the information is deserialized
Definition at line 351 of file satellite-time-tag.cc.
References m_senderLinkTimestamp.
GetInstanceTypeId()
TypeId ns3::SatMacLinkTimeTag::GetInstanceTypeId (void) const virtual
Get the type ID of instance.
Returns
the object TypeId
Definition at line 332 of file satellite-time-tag.cc.
References GetTypeId().
GetSenderLinkTimestamp()
Time ns3::SatMacLinkTimeTag::GetSenderLinkTimestamp (void) const
Get sender time stamp of this tag.
Returns
Sender timestamp
Definition at line 365 of file satellite-time-tag.cc.
References m_senderLinkTimestamp.
Referenced by ns3::SatGeoMac::RxTraces(), and ns3::SatMac::RxTraces().
GetSerializedSize()
uint32_t ns3::SatMacLinkTimeTag::GetSerializedSize (void) const virtual
Get serialized size of SatMacLinkTimeTag.
Returns
Serialized size in bytes
Definition at line 338 of file satellite-time-tag.cc.
GetTypeId()
TypeId ns3::SatMacLinkTimeTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 324 of file satellite-time-tag.cc.
Referenced by GetInstanceTypeId().
Print()
void ns3::SatMacLinkTimeTag::Print (std::ostream & os) const virtual
Print time stamp of this instance of SatMacLinkTimeTag.
Parameters
&os Output stream to which tag timestamp is printed.
Definition at line 359 of file satellite-time-tag.cc.
References m_senderLinkTimestamp.
Serialize()
void ns3::SatMacLinkTimeTag::Serialize (TagBuffer i) const virtual
Serializes information to buffer from this instance of SatMacLinkTimeTag.
Parameters
i Buffer in which the information is serialized
Definition at line 344 of file satellite-time-tag.cc.
References m_senderLinkTimestamp.
SetSenderLinkTimestamp()
void ns3::SatMacLinkTimeTag::SetSenderLinkTimestamp (Time senderLinkTimestamp)
Set sender time stamp of this tag.
Parameters
senderTimestamp Sender time stamp
Definition at line 371 of file satellite-time-tag.cc.
References m_senderLinkTimestamp.
Member Data Documentation
m_senderLinkTimestamp
Time ns3::SatMacLinkTimeTag::m_senderLinkTimestamp private
Definition at line 388 of file satellite-time-tag.h.
Referenced by Deserialize(), GetSenderLinkTimestamp(), Print(), Serialize(), and SetSenderLinkTimestamp().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-time-tag.h
/builds/sns3/satellite/satellite/model/satellite-time-tag.cc