SNS3
ns3::SatGroundStationAddressTag Class Reference
Tag to store ground station destination address.
#include "satellite-ground-station-address-tag.h"
Public Member Functions
SatGroundStationAddressTag ()
Default constructor.
SatGroundStationAddressTag (Mac48Address groundStationAddress)
Constructor with initialization parameters.
virtual void Deserialize (TagBuffer i)
Deserializes information from buffer to this instance of SatGroundStationAddressTag.
Mac48Address GetGroundStationAddress (void) const
Get the ground station MAC address.
virtual TypeId GetInstanceTypeId (void) const
Get the type ID of instance.
virtual uint32_t GetSerializedSize () const
Get serialized size of SatGroundStationAddressTag.
virtual void Print (std::ostream &os) const
Print time stamp of this instance of SatGroundStationAddressTag.
virtual void Serialize (TagBuffer i) const
Serializes information to buffer from this instance of SatGroundStationAddressTag.
void SetGroundStationAddress (Mac48Address groundStationAddress)
Set the ground station MAC address.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Mac48Address m_groundStationAddress
Static Private Attributes
static const uint32_t ADDRESS_LENGHT = 6
Detailed Description
Tag to store ground station destination address.
Use for routing in constellations
Definition at line 34 of file satellite-ground-station-address-tag.h.
Constructor & Destructor Documentation
SatGroundStationAddressTag() [1/2]
ns3::SatGroundStationAddressTag::SatGroundStationAddressTag ()
Default constructor.
Definition at line 32 of file satellite-ground-station-address-tag.cc.
SatGroundStationAddressTag() [2/2]
ns3::SatGroundStationAddressTag::SatGroundStationAddressTag (Mac48Address groundStationAddress)
Constructor with initialization parameters.
Parameters
groundStationAddress
Definition at line 37 of file satellite-ground-station-address-tag.cc.
Member Function Documentation
Deserialize()
void ns3::SatGroundStationAddressTag::Deserialize (TagBuffer i) virtual
Deserializes information from buffer to this instance of SatGroundStationAddressTag.
Parameters
i Buffer from which the information is deserialized
Definition at line 76 of file satellite-ground-station-address-tag.cc.
References ADDRESS_LENGHT, and m_groundStationAddress.
GetGroundStationAddress()
Mac48Address ns3::SatGroundStationAddressTag::GetGroundStationAddress (void) const
Get the ground station MAC address.
Returns
ground station MAC address
Definition at line 93 of file satellite-ground-station-address-tag.cc.
References m_groundStationAddress.
Referenced by ns3::PointToPointIslNetDevice::Receive(), ns3::SatGeoNetDevice::ReceivePacketFeeder(), and ns3::SatGeoNetDevice::ReceivePacketUser().
GetInstanceTypeId()
TypeId ns3::SatGroundStationAddressTag::GetInstanceTypeId (void) const virtual
Get the type ID of instance.
Returns
the object TypeId
Definition at line 53 of file satellite-ground-station-address-tag.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::SatGroundStationAddressTag::GetSerializedSize (void) const virtual
Get serialized size of SatGroundStationAddressTag.
Returns
Serialized size in bytes
Definition at line 59 of file satellite-ground-station-address-tag.cc.
References ADDRESS_LENGHT.
GetTypeId()
TypeId ns3::SatGroundStationAddressTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 44 of file satellite-ground-station-address-tag.cc.
Referenced by GetInstanceTypeId().
Print()
void ns3::SatGroundStationAddressTag::Print (std::ostream & os) const virtual
Print time stamp of this instance of SatGroundStationAddressTag.
Parameters
&os Output stream to which tag timestamp is printed.
Definition at line 87 of file satellite-ground-station-address-tag.cc.
References m_groundStationAddress.
Serialize()
void ns3::SatGroundStationAddressTag::Serialize (TagBuffer i) const virtual
Serializes information to buffer from this instance of SatGroundStationAddressTag.
Parameters
i Buffer in which the information is serialized
Definition at line 65 of file satellite-ground-station-address-tag.cc.
References ADDRESS_LENGHT, and m_groundStationAddress.
SetGroundStationAddress()
void ns3::SatGroundStationAddressTag::SetGroundStationAddress (Mac48Address groundStationAddress)
Set the ground station MAC address.
Parameters
groundStationAddress ground station MAC address
Definition at line 99 of file satellite-ground-station-address-tag.cc.
References m_groundStationAddress.
Member Data Documentation
ADDRESS_LENGHT
const uint32_t ns3::SatGroundStationAddressTag::ADDRESS_LENGHT = 6 static private
Definition at line 97 of file satellite-ground-station-address-tag.h.
Referenced by Deserialize(), GetSerializedSize(), and Serialize().
m_groundStationAddress
Mac48Address ns3::SatGroundStationAddressTag::m_groundStationAddress private
Definition at line 99 of file satellite-ground-station-address-tag.h.
Referenced by Deserialize(), GetGroundStationAddress(), Print(), Serialize(), and SetGroundStationAddress().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-ground-station-address-tag.h
/builds/sns3/satellite/satellite/model/satellite-ground-station-address-tag.cc