SNS3
ns3::SatDevTimeTag Class Reference
Time tag used to identify the time when packet is enqueued at device level.
#include "satellite-time-tag.h"
Public Member Functions
SatDevTimeTag ()
Default constructor.
SatDevTimeTag (Time senderTimestamp)
Constructor with initialization parameters.
virtual void Deserialize (TagBuffer i)
Deserializes information from buffer to this instance of SatDevTimeTag.
virtual TypeId GetInstanceTypeId (void) const
Get the type ID of instance.
Time GetSenderTimestamp (void) const
Get sender time stamp of this tag.
virtual uint32_t GetSerializedSize () const
Get serialized size of SatDevTimeTag.
virtual void Print (std::ostream &os) const
Print time stamp of this instance of SatDevTimeTag.
virtual void Serialize (TagBuffer i) const
Serializes information to buffer from this instance of SatDevTimeTag.
void SetSenderTimestamp (Time senderTimestamp)
Set sender time stamp of this tag.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Time m_senderTimestamp
Detailed Description
Time tag used to identify the time when packet is enqueued at device level.
Definition at line 396 of file satellite-time-tag.h.
Constructor & Destructor Documentation
SatDevTimeTag() [1/2]
ns3::SatDevTimeTag::SatDevTimeTag ()
Default constructor.
Definition at line 380 of file satellite-time-tag.cc.
SatDevTimeTag() [2/2]
ns3::SatDevTimeTag::SatDevTimeTag (Time senderTimestamp)
Constructor with initialization parameters.
Parameters
senderTimestamp
Definition at line 386 of file satellite-time-tag.cc.
Member Function Documentation
Deserialize()
void ns3::SatDevTimeTag::Deserialize (TagBuffer i) virtual
Deserializes information from buffer to this instance of SatDevTimeTag.
Parameters
i Buffer from which the information is deserialized
Definition at line 420 of file satellite-time-tag.cc.
References m_senderTimestamp.
GetInstanceTypeId()
TypeId ns3::SatDevTimeTag::GetInstanceTypeId (void) const virtual
Get the type ID of instance.
Returns
the object TypeId
Definition at line 401 of file satellite-time-tag.cc.
References GetTypeId().
GetSenderTimestamp()
Time ns3::SatDevTimeTag::GetSenderTimestamp (void) const
Get sender time stamp of this tag.
Returns
Sender timestamp
Definition at line 434 of file satellite-time-tag.cc.
References m_senderTimestamp.
Referenced by ns3::SatLorawanNetDevice::Receive(), and ns3::SatNetDevice::Receive().
GetSerializedSize()
uint32_t ns3::SatDevTimeTag::GetSerializedSize (void) const virtual
Get serialized size of SatDevTimeTag.
Returns
Serialized size in bytes
Definition at line 407 of file satellite-time-tag.cc.
GetTypeId()
TypeId ns3::SatDevTimeTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 393 of file satellite-time-tag.cc.
Referenced by GetInstanceTypeId().
Print()
void ns3::SatDevTimeTag::Print (std::ostream & os) const virtual
Print time stamp of this instance of SatDevTimeTag.
Parameters
&os Output stream to which tag timestamp is printed.
Definition at line 428 of file satellite-time-tag.cc.
References m_senderTimestamp.
Serialize()
void ns3::SatDevTimeTag::Serialize (TagBuffer i) const virtual
Serializes information to buffer from this instance of SatDevTimeTag.
Parameters
i Buffer in which the information is serialized
Definition at line 413 of file satellite-time-tag.cc.
References m_senderTimestamp.
SetSenderTimestamp()
void ns3::SatDevTimeTag::SetSenderTimestamp (Time senderTimestamp)
Set sender time stamp of this tag.
Parameters
senderTimestamp Sender time stamp
Definition at line 440 of file satellite-time-tag.cc.
References m_senderTimestamp.
Member Data Documentation
m_senderTimestamp
Time ns3::SatDevTimeTag::m_senderTimestamp private
Definition at line 459 of file satellite-time-tag.h.
Referenced by Deserialize(), GetSenderTimestamp(), Print(), Serialize(), and SetSenderTimestamp().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-time-tag.h
/builds/sns3/satellite/satellite/model/satellite-time-tag.cc