SNS3
ns3::SatLoraConf Class Reference
A configuration class for the GEO satellite reference system.
#include "satellite-lora-conf.h"
Public Types
enum PhyLayerStandard_t { SATELLITE , EU863_870 }
Public Member Functions
SatLoraConf ()
Default constructor.
virtual ~SatLoraConf ()
TypeId GetInstanceTypeId (void) const
void SetConf (Ptr< LorawanMacEndDeviceClassA > endDeviceMac)
void SetConf (Ptr< LorawanMacGateway > gatewayMac)
void setSatConfAttributes (Ptr< SatConf > satConf)
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void SetEu863_870Conf (Ptr< LorawanMacEndDeviceClassA > endDeviceMac)
void SetEu863_870Conf (Ptr< LorawanMacGateway > gatewayMac)
void SetSatelliteConf (Ptr< LorawanMacEndDeviceClassA > endDeviceMac)
void SetSatelliteConf (Ptr< LorawanMacGateway > gatewayMac)
Private Attributes
PhyLayerStandard_t m_phyLayerStandard
Detailed Description
A configuration class for the GEO satellite reference system.
Definition at line 35 of file satellite-lora-conf.h.
Member Enumeration Documentation
PhyLayerStandard_t
enum ns3::SatLoraConf::PhyLayerStandard_t
Enumerator
SATELLITE
For Satellite.
EU863_870
EU863-870.
Definition at line 38 of file satellite-lora-conf.h.
Constructor & Destructor Documentation
SatLoraConf()
ns3::SatLoraConf::SatLoraConf ()
Default constructor.
Definition at line 64 of file satellite-lora-conf.cc.
~SatLoraConf()
virtual ns3::SatLoraConf::~SatLoraConf () inline virtual
Definition at line 49 of file satellite-lora-conf.h.
Member Function Documentation
GetInstanceTypeId()
TypeId ns3::SatLoraConf::GetInstanceTypeId (void) const
Definition at line 57 of file satellite-lora-conf.cc.
References GetTypeId().
GetTypeId()
TypeId ns3::SatLoraConf::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 40 of file satellite-lora-conf.cc.
References EU863_870, m_phyLayerStandard, and SATELLITE.
Referenced by GetInstanceTypeId().
SetConf() [1/2]
void ns3::SatLoraConf::SetConf (Ptr< LorawanMacEndDeviceClassA > endDeviceMac)
Definition at line 90 of file satellite-lora-conf.cc.
References EU863_870, m_phyLayerStandard, SATELLITE, SetEu863_870Conf(), and SetSatelliteConf().
SetConf() [2/2]
void ns3::SatLoraConf::SetConf (Ptr< LorawanMacGateway > gatewayMac)
Definition at line 72 of file satellite-lora-conf.cc.
References EU863_870, m_phyLayerStandard, SATELLITE, SetEu863_870Conf(), and SetSatelliteConf().
Referenced by ns3::SatGwHelper::InstallLora(), and ns3::SatUtHelper::InstallLora().
SetEu863_870Conf() [1/2]
void ns3::SatLoraConf::SetEu863_870Conf (Ptr< LorawanMacEndDeviceClassA > endDeviceMac) private
Definition at line 181 of file satellite-lora-conf.cc.
References ns3::LoraLogicalChannelHelper::AddChannel(), and ns3::LoraLogicalChannelHelper::AddLoraSubBand().
SetEu863_870Conf() [2/2]
void ns3::SatLoraConf::SetEu863_870Conf (Ptr< LorawanMacGateway > gatewayMac) private
Definition at line 154 of file satellite-lora-conf.cc.
References ns3::LoraLogicalChannelHelper::AddChannel(), and ns3::LoraLogicalChannelHelper::AddLoraSubBand().
Referenced by SetConf().
setSatConfAttributes()
void ns3::SatLoraConf::setSatConfAttributes (Ptr< SatConf > satConf)
Definition at line 108 of file satellite-lora-conf.cc.
References EU863_870, m_phyLayerStandard, and SATELLITE.
Referenced by ns3::SatHelper::SatHelper().
SetSatelliteConf() [1/2]
void ns3::SatLoraConf::SetSatelliteConf (Ptr< LorawanMacEndDeviceClassA > endDeviceMac) private
Definition at line 255 of file satellite-lora-conf.cc.
References ns3::LoraLogicalChannelHelper::AddChannel(), and ns3::LoraLogicalChannelHelper::AddLoraSubBand().
SetSatelliteConf() [2/2]
void ns3::SatLoraConf::SetSatelliteConf (Ptr< LorawanMacGateway > gatewayMac) private
Definition at line 225 of file satellite-lora-conf.cc.
References ns3::LoraLogicalChannelHelper::AddChannel(), and ns3::LoraLogicalChannelHelper::AddLoraSubBand().
Referenced by SetConf().
Member Data Documentation
m_phyLayerStandard
PhyLayerStandard_t ns3::SatLoraConf::m_phyLayerStandard private
Definition at line 72 of file satellite-lora-conf.h.
Referenced by GetTypeId(), SetConf(), and setSatConfAttributes().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/helper/satellite-lora-conf.h
/builds/sns3/satellite/satellite/helper/satellite-lora-conf.cc