SNS3
ns3::SatMacTimeTag Class Reference
Time tag used to identify the time when packet is enqueued at MAC level.
#include "satellite-time-tag.h"
Public Member Functions
SatMacTimeTag ()
Default constructor.
SatMacTimeTag (Time senderTimestamp)
Constructor with initialization parameters.
virtual void Deserialize (TagBuffer i)
Deserializes information from buffer to this instance of SatMacTimeTag.
virtual TypeId GetInstanceTypeId (void) const
Get the type ID of instance.
Time GetSenderTimestamp (void) const
Get sender time stamp of this tag.
virtual uint32_t GetSerializedSize () const
Get serialized size of SatMacTimeTag.
virtual void Print (std::ostream &os) const
Print time stamp of this instance of SatMacTimeTag.
virtual void Serialize (TagBuffer i) const
Serializes information to buffer from this instance of SatMacTimeTag.
void SetSenderTimestamp (Time senderTimestamp)
Set sender time stamp of this tag.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Time m_senderTimestamp
Detailed Description
Time tag used to identify the time when packet is enqueued at MAC level.
Definition at line 254 of file satellite-time-tag.h.
Constructor & Destructor Documentation
SatMacTimeTag() [1/2]
ns3::SatMacTimeTag::SatMacTimeTag ()
Default constructor.
Definition at line 242 of file satellite-time-tag.cc.
SatMacTimeTag() [2/2]
ns3::SatMacTimeTag::SatMacTimeTag (Time senderTimestamp)
Constructor with initialization parameters.
Parameters
senderTimestamp
Definition at line 248 of file satellite-time-tag.cc.
Member Function Documentation
Deserialize()
void ns3::SatMacTimeTag::Deserialize (TagBuffer i) virtual
Deserializes information from buffer to this instance of SatMacTimeTag.
Parameters
i Buffer from which the information is deserialized
Definition at line 282 of file satellite-time-tag.cc.
References m_senderTimestamp.
GetInstanceTypeId()
TypeId ns3::SatMacTimeTag::GetInstanceTypeId (void) const virtual
Get the type ID of instance.
Returns
the object TypeId
Definition at line 263 of file satellite-time-tag.cc.
References GetTypeId().
GetSenderTimestamp()
Time ns3::SatMacTimeTag::GetSenderTimestamp (void) const
Get sender time stamp of this tag.
Returns
Sender timestamp
Definition at line 296 of file satellite-time-tag.cc.
References m_senderTimestamp.
Referenced by ns3::SatMac::RxTraces().
GetSerializedSize()
uint32_t ns3::SatMacTimeTag::GetSerializedSize (void) const virtual
Get serialized size of SatMacTimeTag.
Returns
Serialized size in bytes
Definition at line 269 of file satellite-time-tag.cc.
GetTypeId()
TypeId ns3::SatMacTimeTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 255 of file satellite-time-tag.cc.
Referenced by GetInstanceTypeId().
Print()
void ns3::SatMacTimeTag::Print (std::ostream & os) const virtual
Print time stamp of this instance of SatMacTimeTag.
Parameters
&os Output stream to which tag timestamp is printed.
Definition at line 290 of file satellite-time-tag.cc.
References m_senderTimestamp.
Serialize()
void ns3::SatMacTimeTag::Serialize (TagBuffer i) const virtual
Serializes information to buffer from this instance of SatMacTimeTag.
Parameters
i Buffer in which the information is serialized
Definition at line 275 of file satellite-time-tag.cc.
References m_senderTimestamp.
SetSenderTimestamp()
void ns3::SatMacTimeTag::SetSenderTimestamp (Time senderTimestamp)
Set sender time stamp of this tag.
Parameters
senderTimestamp Sender time stamp
Definition at line 302 of file satellite-time-tag.cc.
References m_senderTimestamp.
Member Data Documentation
m_senderTimestamp
Time ns3::SatMacTimeTag::m_senderTimestamp private
Definition at line 317 of file satellite-time-tag.h.
Referenced by Deserialize(), GetSenderTimestamp(), Print(), Serialize(), and SetSenderTimestamp().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-time-tag.h
/builds/sns3/satellite/satellite/model/satellite-time-tag.cc