SNS3
ns3::SatStatsPltHelper Class Reference abstract
Satellite Statistics
Base class for PLT statistics helpers.
#include "satellite-stats-plt-helper.h"
Public Member Functions
SatStatsPltHelper (Ptr< const SatHelper > satHelper)
virtual ~SatStatsPltHelper ()
/ Destructor.
bool GetAveragingMode () const
void InstallProbes ()
Set up several probes or other means of listeners and connect them to the collectors.
void RxPltCallback (const Time &plt, const Address &from)
Receive inputs from trace sources and determine the right collector to forward the inputs to.
void SetAveragingMode (bool averagingMode)
Public Member Functions inherited from ns3::SatStatsHelper
SatStatsHelper (Ptr< const SatHelper > satHelper)
Creates a new helper instance.
virtual ~SatStatsHelper ()
/ Destructor.
IdentifierType_t GetIdentifierType () const
std::string GetName () const
OutputType_t GetOutputType () const
Ptr< const SatHelper > GetSatHelper () const
void Install ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
bool IsInstalled () const
void SetIdentifierType (IdentifierType_t identifierType)
void SetName (std::string name)
void SetOutputType (OutputType_t outputType)
Static Public Member Functions
static TypeId GetTypeId ()
inherited from ObjectBase base class
Static Public Member Functions inherited from ns3::SatStatsHelper
static std::string GetIdentifierTypeName (IdentifierType_t identifierType)
static std::string GetOutputTypeName (OutputType_t outputType)
static TypeId GetTypeId ()
inherited from ObjectBase base class
Protected Member Functions
bool ConnectProbeToCollector (Ptr< Probe > probe, uint32_t identifier)
Connect the probe to the right collector.
void DoInstall ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
virtual void DoInstallProbes ()=0
void PassSampleToCollector (const Time &plt, uint32_t identifier)
Find a collector with the right identifier and pass a sample data to it.
void SaveAddressAndIdentifier (Ptr< Node > utNode)
Save the address and the proper identifier from the given UT node.
Protected Member Functions inherited from ns3::SatStatsHelper
Ptr< DataCollectionObject > CreateAggregator (std::string aggregatorTypeId, std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue())
Create the aggregator according to the output type.
uint32_t CreateCollectorPerIdentifier (CollectorMap &collectorMap) const
Create one collector instance for each identifier in the simulation.
virtual std::string GetDistributionHeading (std::string dataLabel) const
uint32_t GetGwId (Ptr< Node > gwNode) const
uint32_t GetIdentifierForBeam (uint32_t satId, uint32_t beamId) const
uint32_t GetIdentifierForGroup (uint32_t groupId) const
uint32_t GetIdentifierForGw (Ptr< Node > gwNode) const
uint32_t GetIdentifierForIsl (Ptr< Node > satNodeSrc, Ptr< Node > satNodeDst) const
uint32_t GetIdentifierForSat (Ptr< Node > satNode) const
uint32_t GetIdentifierForUt (Ptr< Node > utNode) const
uint32_t GetIdentifierForUtUser (Ptr< Node > utUserNode) const
virtual std::string GetIdentifierHeading (std::string dataLabel) const
virtual std::string GetOutputFileName () const
Compute the path and file name where statistics output should be written to.
virtual std::string GetOutputPath () const
uint32_t GetSatId (Ptr< Node > satNode) const
virtual std::string GetTimeHeading (std::string dataLabel) const
uint32_t GetUtId (Ptr< Node > utNode) const
uint32_t GetUtUserId (Ptr< Node > utUserNode) const
Protected Attributes
Ptr< DataCollectionObject > m_aggregator
The aggregator created by this helper.
Ptr< DistributionCollector > m_averagingCollector
The final collector utilized in averaged output (histogram, PDF, and CDF).
std::map< const Address, uint32_t > m_identifierMap
Map of address and the identifier associated with it (for return link).
CollectorMap m_terminalCollectors
Maintains a list of collectors created by this helper.
Private Attributes
bool m_averagingMode
AveragingMode attribute.
Additional Inherited Members
Public Types inherited from ns3::SatStatsHelper
enum IdentifierType_t {
IDENTIFIER_GLOBAL = 0 , IDENTIFIER_GW , IDENTIFIER_BEAM , IDENTIFIER_UT ,
IDENTIFIER_UT_USER , IDENTIFIER_SLICE , IDENTIFIER_GROUP , IDENTIFIER_SAT ,
IDENTIFIER_ISL
}
Possible categorization of statistics output.
enum OutputType_t {
OUTPUT_NONE = 0 , OUTPUT_SCALAR_FILE , OUTPUT_SCATTER_FILE , OUTPUT_HISTOGRAM_FILE ,
OUTPUT_PDF_FILE , OUTPUT_CDF_FILE , OUTPUT_SCALAR_PLOT , OUTPUT_SCATTER_PLOT ,
OUTPUT_HISTOGRAM_PLOT , OUTPUT_PDF_PLOT , OUTPUT_CDF_PLOT
}
Possible types and formats of statistics output.
Static Protected Member Functions inherited from ns3::SatStatsHelper
static NetDeviceContainer GetGwSatNetDevice (Ptr< Node > gwNode)
static Ptr< NetDevice > GetSatSatGeoNetDevice (Ptr< Node > satNode)
static Ptr< NetDevice > GetUtSatNetDevice (Ptr< Node > utNode)
Detailed Description
Base class for PLT statistics helpers.
Definition at line 48 of file satellite-stats-plt-helper.h.
Constructor & Destructor Documentation
SatStatsPltHelper()
ns3::SatStatsPltHelper::SatStatsPltHelper (Ptr< const SatHelper > satHelper)
Definition at line 62 of file satellite-stats-plt-helper.cc.
~SatStatsPltHelper()
ns3::SatStatsPltHelper::~SatStatsPltHelper () virtual
/ Destructor.
Definition at line 69 of file satellite-stats-plt-helper.cc.
Member Function Documentation
ConnectProbeToCollector()
bool ns3::SatStatsPltHelper::ConnectProbeToCollector (Ptr< Probe > probe, uint32_t identifier) protected
Connect the probe to the right collector.
Parameters
probe
identifier
Definition at line 466 of file satellite-stats-plt-helper.cc.
References ns3::SatStatsHelper::GetOutputType(), ns3::SatStatsHelper::GetOutputTypeName(), m_averagingMode, m_terminalCollectors, ns3::SatStatsHelper::OUTPUT_CDF_FILE, ns3::SatStatsHelper::OUTPUT_CDF_PLOT, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_FILE, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_PLOT, ns3::SatStatsHelper::OUTPUT_PDF_FILE, ns3::SatStatsHelper::OUTPUT_PDF_PLOT, ns3::SatStatsHelper::OUTPUT_SCALAR_FILE, ns3::SatStatsHelper::OUTPUT_SCALAR_PLOT, ns3::SatStatsHelper::OUTPUT_SCATTER_FILE, and ns3::SatStatsHelper::OUTPUT_SCATTER_PLOT.
Referenced by ns3::SatStatsFwdAppPltHelper::DoInstallProbes().
DoInstall()
void ns3::SatStatsPltHelper::DoInstall () protected virtual
Install the probes, collectors, and aggregators necessary to produce the statistics output.
An abstract method of SatStatsHelper which must be implemented by child classes. It will be invoked by Install().
Todo:
Add support for boxes in Gnuplot.
Todo:
Find a better dataset name.
Todo:
Find a better dataset name.
Implements ns3::SatStatsHelper.
Definition at line 104 of file satellite-stats-plt-helper.cc.
References ns3::SatStatsHelper::CreateAggregator(), ns3::SatStatsHelper::CreateCollectorPerIdentifier(), ns3::SatStatsHelper::GetDistributionHeading(), ns3::SatStatsHelper::GetIdentifierHeading(), ns3::SatStatsHelper::GetName(), ns3::SatStatsHelper::GetOutputFileName(), ns3::SatStatsHelper::GetOutputPath(), ns3::SatStatsHelper::GetOutputType(), ns3::SatStatsHelper::GetOutputTypeName(), ns3::SatStatsHelper::GetTimeHeading(), InstallProbes(), m_aggregator, m_averagingCollector, m_averagingMode, m_terminalCollectors, ns3::SatStatsHelper::OUTPUT_CDF_FILE, ns3::SatStatsHelper::OUTPUT_CDF_PLOT, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_FILE, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_PLOT, ns3::SatStatsHelper::OUTPUT_NONE, ns3::SatStatsHelper::OUTPUT_PDF_FILE, ns3::SatStatsHelper::OUTPUT_PDF_PLOT, ns3::SatStatsHelper::OUTPUT_SCALAR_FILE, ns3::SatStatsHelper::OUTPUT_SCALAR_PLOT, ns3::SatStatsHelper::OUTPUT_SCATTER_FILE, and ns3::SatStatsHelper::OUTPUT_SCATTER_PLOT.
DoInstallProbes()
virtual void ns3::SatStatsPltHelper::DoInstallProbes () protected pure virtual
Implemented in ns3::SatStatsRtnAppPltHelper, and ns3::SatStatsFwdAppPltHelper.
Referenced by InstallProbes().
GetAveragingMode()
bool ns3::SatStatsPltHelper::GetAveragingMode () const
Returns
the currently active averaging mode.
Definition at line 98 of file satellite-stats-plt-helper.cc.
References m_averagingMode.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::SatStatsPltHelper::GetTypeId (void) static
inherited from ObjectBase base class
Definition at line 75 of file satellite-stats-plt-helper.cc.
References GetAveragingMode(), and SetAveragingMode().
InstallProbes()
void ns3::SatStatsPltHelper::InstallProbes ()
Set up several probes or other means of listeners and connect them to the collectors.
Definition at line 410 of file satellite-stats-plt-helper.cc.
References DoInstallProbes().
Referenced by DoInstall().
PassSampleToCollector()
void ns3::SatStatsPltHelper::PassSampleToCollector (const Time & plt, uint32_t identifier) protected
Find a collector with the right identifier and pass a sample data to it.
Parameters
plt
identifier
Definition at line 532 of file satellite-stats-plt-helper.cc.
References ns3::SatStatsHelper::GetOutputType(), ns3::SatStatsHelper::GetOutputTypeName(), m_averagingMode, m_terminalCollectors, ns3::SatStatsHelper::OUTPUT_CDF_FILE, ns3::SatStatsHelper::OUTPUT_CDF_PLOT, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_FILE, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_PLOT, ns3::SatStatsHelper::OUTPUT_PDF_FILE, ns3::SatStatsHelper::OUTPUT_PDF_PLOT, ns3::SatStatsHelper::OUTPUT_SCALAR_FILE, ns3::SatStatsHelper::OUTPUT_SCALAR_PLOT, ns3::SatStatsHelper::OUTPUT_SCATTER_FILE, and ns3::SatStatsHelper::OUTPUT_SCATTER_PLOT.
Referenced by ns3::SatStatsRtnAppPltHelper::Ipv4Callback(), and RxPltCallback().
RxPltCallback()
void ns3::SatStatsPltHelper::RxPltCallback (const Time & plt, const Address & from)
Receive inputs from trace sources and determine the right collector to forward the inputs to.
Parameters
plt object PLT.
from the address of the sender of the object.
Used in return link statistics. DoInstallProbes() is expected to connect the right trace sources to this method.
Definition at line 417 of file satellite-stats-plt-helper.cc.
References m_identifierMap, and PassSampleToCollector().
SaveAddressAndIdentifier()
void ns3::SatStatsPltHelper::SaveAddressAndIdentifier (Ptr< Node > utNode) protected
Save the address and the proper identifier from the given UT node.
Parameters
utNode a UT node.
The address of the given node will be saved in the m_identifierMap member variable.
Used in return link statistics. DoInstallProbes() is expected to pass the the UT node of interest into this method.
Definition at line 446 of file satellite-stats-plt-helper.cc.
References ns3::SatStatsHelper::GetIdentifierForUt(), ns3::SatIdMapper::GetUtMacWithNode(), and m_identifierMap.
SetAveragingMode()
void ns3::SatStatsPltHelper::SetAveragingMode (bool averagingMode)
Parameters
averagingMode average all samples before passing them to aggregator.
Definition at line 91 of file satellite-stats-plt-helper.cc.
References m_averagingMode.
Referenced by GetTypeId().
Member Data Documentation
m_aggregator
Ptr<DataCollectionObject> ns3::SatStatsPltHelper::m_aggregator protected
The aggregator created by this helper.
Definition at line 134 of file satellite-stats-plt-helper.h.
Referenced by DoInstall().
m_averagingCollector
Ptr<DistributionCollector> ns3::SatStatsPltHelper::m_averagingCollector protected
The final collector utilized in averaged output (histogram, PDF, and CDF).
Definition at line 131 of file satellite-stats-plt-helper.h.
Referenced by DoInstall().
m_averagingMode
bool ns3::SatStatsPltHelper::m_averagingMode private
AveragingMode attribute.
Definition at line 140 of file satellite-stats-plt-helper.h.
Referenced by ConnectProbeToCollector(), DoInstall(), GetAveragingMode(), PassSampleToCollector(), and SetAveragingMode().
m_identifierMap
std::map<const Address, uint32_t> ns3::SatStatsPltHelper::m_identifierMap protected
Map of address and the identifier associated with it (for return link).
Definition at line 137 of file satellite-stats-plt-helper.h.
Referenced by ns3::SatStatsRtnAppPltHelper::Ipv4Callback(), RxPltCallback(), SaveAddressAndIdentifier(), and ns3::SatStatsRtnAppPltHelper::SaveIpv4AddressAndIdentifier().
m_terminalCollectors
CollectorMap ns3::SatStatsPltHelper::m_terminalCollectors protected
Maintains a list of collectors created by this helper.
Definition at line 128 of file satellite-stats-plt-helper.h.
Referenced by ConnectProbeToCollector(), DoInstall(), and PassSampleToCollector().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/stats/satellite-stats-plt-helper.h
/builds/sns3/satellite/satellite/stats/satellite-stats-plt-helper.cc