SNS3
ns3::SatPhyRxCarrier Class Reference abstract
Base class for all SatPhyRxCarriers.
#include "satellite-phy-rx-carrier.h"
Classes
struct rxParams_s
Struct for storing the packet specific Rx parameters.
Public Types
enum CarrierType {
BASE , DEDICATED_ACCESS , RA_SLOTTED_ALOHA , RA_CRDSA ,
RA_ESSA
}
Possible carrier types.
typedef void(* LinkBudgetTraceCallback) (Ptr< SatSignalParameters > rxParams, Mac48Address receiverAddress, Mac48Address destinationAddress, double interference, double sinr)
Callback signature for LinkBudgetTrace trace source.
typedef void(* LinkSinrTraceCallback) (double sinr, const Address &utAddress)
Callback signature for LinkSinrTrace trace source.
typedef void(* PhyRxCollisionCallback) (uint32_t nPackets, const Address &utAddress, bool isCollided)
Common callback signature for trace sources related to packets reception by PHY and its collision.
typedef void(* PhyRxErrorCallback) (uint32_t nPackets, const Address &utAddress, bool isError)
Common callback signature for trace sources related to packets reception by PHY and its error.
typedef void(* RxPowerTraceCallback) (double rxPower, const Address &utAddress)
Callback signature for RxPowerTrace trace source.
enum State { IDLE , RX }
Enum for PHY states.
Public Member Functions
SatPhyRxCarrier (uint32_t carrierId, Ptr< SatPhyRxCarrierConf > carrierConf, Ptr< SatWaveformConf > waveformConf, bool isRandomAccessEnabled)
Constructor.
virtual ~SatPhyRxCarrier ()
Destructor.
virtual void BeginEndScheduling ()
Function for initializing the frame/window end scheduling.
uint32_t GetBeamId ()
Get ID the ID of the beam this carrier is attached to.
virtual CarrierType GetCarrierType ()
Method for querying the type of the carrier.
double GetRxTemperatureK ()
Method for querying the temperature of the carrier.
uint32_t GetSatId ()
Get ID the ID of the satellite this carrier is attached to.
void SetAverageNormalizedOfferedLoadCallback (SatPhyRx::AverageNormalizedOfferedLoadCallback callback)
Function for setting the AverageNormalizedOfferedLoadCallback callback.
void SetBeamId (uint32_t beamId)
Function for setting the beam id for all the transmissions from this SatPhyTx.
void SetCnoCb (SatPhyRx::CnoCallback cb)
Function for settign the C/NO callback.
void SetNodeInfo (const Ptr< SatNodeInfo > nodeInfo)
Function for setting the node info class.
void SetPhy (Ptr< SatPhy > phy)
Function for setting the SatPhy module.
void SetReceiveCb (SatPhyRx::ReceiveCallback cb)
Function for setting the receive callback.
void SetSatId (uint32_t satId)
Function for setting the satellite id for all the transmissions from this SatPhyTx.
virtual bool StartRx (Ptr< SatSignalParameters > rxParams)
Function for starting packet reception from the SatChannel.
Static Public Member Functions
static TypeId GetTypeId (void)
Function for gettign the NS-3 type ID.
Protected Member Functions
double CalculateCompositeSinr (double sinr1, double sinr2)
Function for calculating the composite SINR.
double CalculateSinr (double rxPowerW, double ifPowerW, double rxNoisePowerW, double rxAciIfPowerW, double rxExtNoisePowerW, double otherInterference)
Function for calculating the SINR.
double CalculateSinr (double sinr, double otherInterference)
Calculate final SINR with PHY specific parameters and given calculated SINR.
void ChangeState (State newState)
Function for changing the receiver state.
bool CheckAgainstLinkResults (double cSinr, Ptr< SatSignalParameters > rxParams)
Function for checking the SINR against the link results.
void CheckRxStateSanity ()
Function for checking the Rx state sanity.
virtual Ptr< SatInterference::InterferenceChangeEvent > CreateInterference (Ptr< SatSignalParameters > rxParams, Address rxAddress)=0
Create an interference event based on Rx parameters and address.
void DecreaseNumOfRxState (SatEnums::PacketType_t packetType)
Function for decreasing the number of ongoing transmissions.
void DoCompositeSinrOutputTrace (double cSinr)
Function for composite SINR output tracing.
virtual void DoCreateInterferenceEliminationModel (Ptr< SatPhyRxCarrierConf > carrierConf, uint32_t carrierId, Ptr< SatWaveformConf > waveformConf)
Create an interference cancelation model for this carrier.
virtual void DoCreateInterferenceModel (Ptr< SatPhyRxCarrierConf > carrierConf, uint32_t carrierId, double rxBandwidthHz)
Create an interference model for this carrier.
virtual void DoDispose ()
Dispose.
virtual void EndRxData (uint32_t key)=0
Function for ending the packet reception from the SatChannel.
uint32_t GetCarrierId () const
Get the ID of the carrier.
Ptr< SatChannelEstimationErrorContainer > GetChannelEstimationErrorContainer ()
Get a pointer to the channel estimation error container of the carrier.
virtual SatEnums::ChannelType_t GetChannelType ()
Get the channel type.
virtual const bool GetDefaultReceiveMode ()
Get the default receive mode for the carrier.
Ptr< SatInterferenceElimination > GetInterferenceEliminationModel ()
Get pointer to the current interference elimination model.
Ptr< SatInterference > GetInterferenceModel ()
Get pointer to the current interference model.
virtual SatEnums::RegenerationMode_t GetLinkRegenerationMode ()
Get the link regeneration mode.
Ptr< SatLinkResults > GetLinkResults ()
Get pointer to the link results given by the carrier creation configuration.
Ptr< SatNodeInfo > GetNodeInfo ()
Get the satellite node info.
Mac48Address GetOwnAddress ()
Get the MAC address of the carrier.
std::pair< bool, SatPhyRxCarrier::rxParams_s > GetReceiveParams (Ptr< SatSignalParameters > rxParams)
Rx parameter storage methods.
State GetState ()
Get the state of the carrier.
rxParams_s GetStoredRxParams (uint32_t key)
Get stored rxParams under a key.
double GetUniformRandomValue (double min, double max)
A helper method for getting values form a uniform random variable in child classes.
Ptr< SatWaveformConf > GetWaveformConf ()
Get pointer to the waveform configuration.
double GetWorstSinr (double sinr1, double sinr2)
Function for calculating the worst sinr between uplink and downlink.
void IncreaseNumOfRxState (SatEnums::PacketType_t packetType)
Function for increasing the number of ongoing transmissions.
bool IsCompositeSinrOutputTraceEnabled () const
Check if composite SINR output trace is enabled.
bool IsReceivingDedicatedAccess ()
Check if the carrier is receiving a dedicated access packet.
void RemoveStoredRxParams (uint32_t key)
Remove stored rxParams under a key.
void SetChannelType (SatEnums::ChannelType_t channelType)
Set the channel type for the carrier.
void SetLinkRegenerationMode (SatEnums::RegenerationMode_t linkRegenerationMode)
Set the link regeneration mode.
void StoreRxParams (uint32_t key, rxParams_s rxParams)
Store rxParams under a key.
Protected Attributes
SatPhyRxCarrierConf::AdditionalInterferenceCallback m_additionalInterferenceCallback
Callback to get additional interference.
SatPhy::AverageNormalizedOfferedLoadCallback m_avgNormalizedOfferedLoadCallback
Average normalized offered load callback.
SatPhy::CnoCallback m_cnoCallback
The upper layer C/N0 receive callback.
TracedCallback< uint32_t, const Address & > m_daRxCarrierIdTrace
TracedCallback< uint32_t, const Address &, bool > m_daRxTrace
DaRx trace source.
TracedCallback< Ptr< SatSignalParameters >, Mac48Address, Mac48Address, double, double > m_linkBudgetTrace
The trace source on packet receptiong.
SatEnums::RegenerationMode_t m_linkRegenerationMode
Link regeneration mode.
TracedCallback< double, const Address & > m_linkSinrTrace
A callback for link specific SINR in dB.
const bool m_randomAccessEnabled
Is random access enabled for this carrier.
double m_rxAciIfPowerW
RX Adjacent channel interference.
double m_rxBandwidthHz
RX Bandwidth in Hz.
SatPhyRx::ReceiveCallback m_rxCallback
The upper layer package receive callback.
double m_rxExtNoisePowerW
External noise power system RX noise.
double m_rxNoisePowerW
RX noise.
TracedCallback< double, const Address & > m_rxPowerTrace
A callback for received signal power in dBW.
double m_rxTemperatureK
RX noise temperature in K.
TracedCallback< double, const Address & > m_sinrTrace
A callback for transmission composite SINR at UT (BBFrame) or GW (time slot).
Private Member Functions
bool CheckAgainstLinkResultsErrorModelAvi (double cSinr, Ptr< SatSignalParameters > rxParams)
Function for checking the SINR against the link results.
Private Attributes
uint32_t m_beamId
uint32_t m_carrierId
Ptr< SatChannelEstimationErrorContainer > m_channelEstimationError
Channel estimation error container.
SatEnums::ChannelType_t m_channelType
double m_constantErrorRate
bool m_enableCompositeSinrOutputTrace
SatPhyRxCarrierConf::ErrorModel m_errorModel
Ptr< SatLinkResults > m_linkResults
Ptr< SatNodeInfo > m_nodeInfo
uint32_t m_numOfOngoingRx
Contains information about how many ongoing Rx events there are.
Mac48Address m_ownAddress
bool m_receivingDedicatedAccess
uint32_t m_rxPacketCounter
Running counter for received packets.
std::map< uint32_t, rxParams_s > m_rxParamsMap
uint32_t m_satId
Ptr< SatInterference > m_satInterference
Ptr< SatInterferenceElimination > m_satInterferenceElimination
State m_state
Ptr< UniformRandomVariable > m_uniformVariable
Ptr< SatWaveformConf > m_waveformConf
Detailed Description
Base class for all SatPhyRxCarriers.
Definition at line 60 of file satellite-phy-rx-carrier.h.
Member Typedef Documentation
LinkBudgetTraceCallback
typedef void(* ns3::SatPhyRxCarrier::LinkBudgetTraceCallback) (Ptr< SatSignalParameters > rxParams, Mac48Address receiverAddress, Mac48Address destinationAddress, double interference, double sinr)
Callback signature for LinkBudgetTrace trace source.
Parameters
rxParams RX signalling parameters
receiverAddress receiver address
destinationAddress packet destination address
interference interference power (in W)
sinr composite SINR (in linear unit)
Definition at line 84 of file satellite-phy-rx-carrier.h.
LinkSinrTraceCallback
typedef void(* ns3::SatPhyRxCarrier::LinkSinrTraceCallback) (double sinr, const Address &utAddress)
Callback signature for LinkSinrTrace trace source.
Parameters
sinr link-specific SINR (in dB)
utAddress the MAC48 address of the corresponding UT.
Definition at line 102 of file satellite-phy-rx-carrier.h.
PhyRxCollisionCallback
typedef void(* ns3::SatPhyRxCarrier::PhyRxCollisionCallback) (uint32_t nPackets, const Address &utAddress, bool isCollided)
Common callback signature for trace sources related to packets reception by PHY and its collision.
Parameters
nPackets number of packets in the received packet burst.
utAddress the MAC48 address of the corresponding UT.
isCollided whether a collision has occurred.
Definition at line 120 of file satellite-phy-rx-carrier.h.
PhyRxErrorCallback
typedef void(* ns3::SatPhyRxCarrier::PhyRxErrorCallback) (uint32_t nPackets, const Address &utAddress, bool isError)
Common callback signature for trace sources related to packets reception by PHY and its error.
Parameters
nPackets number of upper layer packets in the received packet burst.
utAddress the MAC48 address of the corresponding UT.
isError whether a PHY error has occurred.
Definition at line 111 of file satellite-phy-rx-carrier.h.
RxPowerTraceCallback
typedef void(* ns3::SatPhyRxCarrier::RxPowerTraceCallback) (double rxPower, const Address &utAddress)
Callback signature for RxPowerTrace trace source.
Parameters
rxPower received signal power (in dbW)
utAddress the MAC48 address of the corresponding UT.
Definition at line 95 of file satellite-phy-rx-carrier.h.
Member Enumeration Documentation
CarrierType
enum ns3::SatPhyRxCarrier::CarrierType
Possible carrier types.
Enumerator
BASE
DEDICATED_ACCESS
RA_SLOTTED_ALOHA
RA_CRDSA
RA_ESSA
Definition at line 153 of file satellite-phy-rx-carrier.h.
State
enum ns3::SatPhyRxCarrier::State
Enum for PHY states.
Enumerator
IDLE
RX
Definition at line 144 of file satellite-phy-rx-carrier.h.
Constructor & Destructor Documentation
SatPhyRxCarrier()
ns3::SatPhyRxCarrier::SatPhyRxCarrier (uint32_t carrierId, Ptr< SatPhyRxCarrierConf > carrierConf, Ptr< SatWaveformConf > waveformConf, bool isRandomAccessEnabled)
Constructor.
Parameters
carrierId
carrierConf
waveformConf
isRandomAccessEnabled
Uniform random variable used for checking whether a packet was received successfully or not
Definition at line 59 of file satellite-phy-rx-carrier.cc.
References ns3::SatConstVariables::BOLTZMANN_CONSTANT, DoCreateInterferenceEliminationModel(), DoCreateInterferenceModel(), ns3::SatEnums::EFFECTIVE_BANDWIDTH, ns3::SatPhyRxCarrierConf::EM_AVI, GetChannelType(), ns3::SatEnums::GetChannelTypeName(), m_additionalInterferenceCallback, m_carrierId, m_channelEstimationError, m_constantErrorRate, m_errorModel, m_linkResults, m_rxAciIfPowerW, m_rxBandwidthHz, m_rxExtNoisePowerW, m_rxNoisePowerW, m_rxTemperatureK, m_uniformVariable, SetChannelType(), and SetLinkRegenerationMode().
~SatPhyRxCarrier()
ns3::SatPhyRxCarrier::~SatPhyRxCarrier () virtual
Destructor.
Definition at line 203 of file satellite-phy-rx-carrier.cc.
Member Function Documentation
BeginEndScheduling()
void ns3::SatPhyRxCarrier::BeginEndScheduling (void) virtual
Function for initializing the frame/window end scheduling.
Reimplemented in ns3::SatPhyRxCarrierPerWindow, ns3::SatPhyRxCarrierPerSlot, and ns3::SatPhyRxCarrierPerFrame.
Definition at line 209 of file satellite-phy-rx-carrier.cc.
CalculateCompositeSinr()
double ns3::SatPhyRxCarrier::CalculateCompositeSinr (double sinr1, double sinr2) protected
Function for calculating the composite SINR.
Parameters
sinr1 SINR 1
sinr2 SINR 2
Returns
Composite SINR
Definition at line 676 of file satellite-phy-rx-carrier.cc.
Referenced by ns3::SatPhyRxCarrierPerFrame::CalculatePacketCompositeSinr(), ns3::SatPhyRxCarrierPerWindow::CalculatePacketInterferenceVectors(), ns3::SatPhyRxCarrierMarsala::PerformMarsala(), and ns3::SatPhyRxCarrierPerSlot::ReceiveSlot().
CalculateSinr() [1/2]
double ns3::SatPhyRxCarrier::CalculateSinr (double rxPowerW, double ifPowerW, double rxNoisePowerW, double rxAciIfPowerW, double rxExtNoisePowerW, double otherInterference) protected
Function for calculating the SINR.
Parameters
rxPowerW Rx power in Watts
ifPowerW Interference power in Watts
rxNoisePowerW Rx noise power in Watts
rxAciIfPowerW Rx ACI power in Watts
rxExtNoisePowerW Rx external noise power in Watts
otherInterference Additional interference to compute final SINR
Returns
Calculated SINR
Definition at line 629 of file satellite-phy-rx-carrier.cc.
Referenced by ns3::SatPhyRxCarrierPerFrame::CalculatePacketCompositeSinr(), ns3::SatPhyRxCarrierPerWindow::CalculatePacketInterferenceVectors(), ns3::SatPhyRxCarrierUplink::EndRxData(), ns3::SatPhyRxCarrierMarsala::PerformMarsala(), and ns3::SatPhyRxCarrierPerSlot::ReceiveSlot().
CalculateSinr() [2/2]
double ns3::SatPhyRxCarrier::CalculateSinr (double sinr, double otherInterference) protected
Calculate final SINR with PHY specific parameters and given calculated SINR.
Additional interference value is added.
Parameters
sinr Calculated SINR
otherInterference Interference to add to the sinr
Returns
Final SINR
Definition at line 656 of file satellite-phy-rx-carrier.cc.
ChangeState()
void ns3::SatPhyRxCarrier::ChangeState (State newState) protected
Function for changing the receiver state.
Parameters
newState New state
Definition at line 300 of file satellite-phy-rx-carrier.cc.
References m_state.
Referenced by DecreaseNumOfRxState(), and IncreaseNumOfRxState().
CheckAgainstLinkResults()
bool ns3::SatPhyRxCarrier::CheckAgainstLinkResults (double cSinr, Ptr< SatSignalParameters > rxParams) protected
Function for checking the SINR against the link results.
Parameters
cSinr composite SINR
rxParams Rx parameters
Returns
result of the check
Initialize with no errors
No errors i.e. error = false;
Definition at line 484 of file satellite-phy-rx-carrier.cc.
References CheckAgainstLinkResultsErrorModelAvi(), ns3::SatPhyRxCarrierConf::EM_AVI, ns3::SatPhyRxCarrierConf::EM_CONSTANT, ns3::SatPhyRxCarrierConf::EM_NONE, GetUniformRandomValue(), m_constantErrorRate, and m_errorModel.
Referenced by ns3::SatPhyRxCarrierMarsala::PerformMarsala(), ns3::SatPhyRxCarrierPerFrame::ProcessReceivedCrdsaPacket(), ns3::SatPhyRxCarrierPerSlot::ProcessSlottedAlohaCollisions(), ns3::SatPhyRxCarrierPerWindow::ProcessWindow(), and ns3::SatPhyRxCarrierPerSlot::ReceiveSlot().
CheckAgainstLinkResultsErrorModelAvi()
bool ns3::SatPhyRxCarrier::CheckAgainstLinkResultsErrorModelAvi (double cSinr, Ptr< SatSignalParameters > rxParams) private
Function for checking the SINR against the link results.
Parameters
cSinr composite SINR
rxParams Rx parameters
Returns
result of the check
In forward link the link results are in Es/No format, thus here we need to convert the SINR into Es/No:
C/No = C/N * fs Es/No = C/N * B/fs = (C/No / fs) * B/fs Es/No = (C*Ts)/No = C/No * (1/fs) = C/N
where C/No = carrier to noise density C/N = signal to noise ratio (= SINR in the simulator) Es/No = energy per symbol per noise density B = channel bandwidth in Hz fs = symbol rate in baud
In return link the link results are in Eb/No format, thus here we need to convert the SINR into Eb/No: Eb/No = C/N * B/fb = (C/No / fs) * B/fb Eb/No = (Es/log2M)/No = (Es/No)*(1/log2M) = C/N * (1/log2M) = C/No * (1/fs) * (1/log2M)
where C/No = carrier to noise density C/N = signal to noise ratio (= SINR in the simulator) Es/No = energy per symbol per noise density Eb/No = energy per bit per noise density B = channel bandwidth in Hz fs = symbol rate in baud fb = channel bitrate (after FEC) in bps (i.e. burst payloadInBits / burstDurationInSec)
Definition at line 518 of file satellite-phy-rx-carrier.cc.
References ns3::SatEnums::FORWARD_FEEDER_CH, ns3::SatEnums::FORWARD_USER_CH, GetChannelType(), ns3::SatUtils::GetCodingRate(), GetLinkResults(), ns3::SatUtils::GetModulatedBits(), GetUniformRandomValue(), ns3::SatUtils::LinearToDb(), m_linkRegenerationMode, ns3::SatEnums::REGENERATION_LINK, ns3::SatEnums::REGENERATION_NETWORK, ns3::SatEnums::RETURN_FEEDER_CH, ns3::SatEnums::RETURN_USER_CH, and ns3::SatEnums::UNKNOWN_CH.
Referenced by CheckAgainstLinkResults().
CheckRxStateSanity()
void ns3::SatPhyRxCarrier::CheckRxStateSanity () protected
Function for checking the Rx state sanity.
Definition at line 751 of file satellite-phy-rx-carrier.cc.
References IDLE, m_numOfOngoingRx, m_state, and RX.
Referenced by DecreaseNumOfRxState(), and IncreaseNumOfRxState().
CreateInterference()
virtual Ptr<SatInterference::InterferenceChangeEvent> ns3::SatPhyRxCarrier::CreateInterference (Ptr< SatSignalParameters > rxParams, Address rxAddress) protected pure virtual
Create an interference event based on Rx parameters and address.
Implemented by child classes.
Returns
Pointer to the interference event.
Implemented in ns3::SatPhyRxCarrierUplink, and ns3::SatPhyRxCarrierPerSlot.
Referenced by StartRx().
DecreaseNumOfRxState()
void ns3::SatPhyRxCarrier::DecreaseNumOfRxState (SatEnums::PacketType_t packetType) protected
Function for decreasing the number of ongoing transmissions.
Parameters
packetType Packet type of the ongoing transmission
Definition at line 728 of file satellite-phy-rx-carrier.cc.
References ChangeState(), CheckRxStateSanity(), IDLE, m_numOfOngoingRx, m_receivingDedicatedAccess, and ns3::SatEnums::PACKET_TYPE_DEDICATED_ACCESS.
Referenced by ns3::SatPhyRxCarrierPerSlot::EndRxData(), and ns3::SatPhyRxCarrierUplink::EndRxData().
DoCompositeSinrOutputTrace()
void ns3::SatPhyRxCarrier::DoCompositeSinrOutputTrace (double cSinr) protected
Function for composite SINR output tracing.
Parameters
cSinr composite SINR
Definition at line 470 of file satellite-phy-rx-carrier.cc.
References GetChannelType(), and GetOwnAddress().
Referenced by ns3::SatPhyRxCarrierPerWindow::CalculatePacketInterferenceVectors(), and ns3::SatPhyRxCarrierPerSlot::ReceiveSlot().
DoCreateInterferenceEliminationModel()
void ns3::SatPhyRxCarrier::DoCreateInterferenceEliminationModel (Ptr< SatPhyRxCarrierConf > carrierConf, uint32_t carrierId, Ptr< SatWaveformConf > waveformConf) protected virtual
Create an interference cancelation model for this carrier.
Parameters
carrierConf
carrierId
frameConf
Definition at line 177 of file satellite-phy-rx-carrier.cc.
References m_randomAccessEnabled, m_satInterferenceElimination, ns3::SatPhyRxCarrierConf::SIC_PERFECT, and ns3::SatPhyRxCarrierConf::SIC_RESIDUAL.
Referenced by SatPhyRxCarrier().
DoCreateInterferenceModel()
void ns3::SatPhyRxCarrier::DoCreateInterferenceModel (Ptr< SatPhyRxCarrierConf > carrierConf, uint32_t carrierId, double rxBandwidthHz) protected virtual
Create an interference model for this carrier.
Parameters
carrierConf
carrierId
rxBandwidthHz
randomAccessEnabled
Definition at line 127 of file satellite-phy-rx-carrier.cc.
References GetChannelType(), ns3::SatPhyRxCarrierConf::IF_CONSTANT, ns3::SatPhyRxCarrierConf::IF_PER_FRAGMENT, ns3::SatPhyRxCarrierConf::IF_PER_PACKET, ns3::SatPhyRxCarrierConf::IF_TRACE, m_randomAccessEnabled, and m_satInterference.
Referenced by SatPhyRxCarrier().
DoDispose()
void ns3::SatPhyRxCarrier::DoDispose (void) protected virtual
Dispose.
Reimplemented in ns3::SatPhyRxCarrierPerWindow, ns3::SatPhyRxCarrierPerSlot, and ns3::SatPhyRxCarrierPerFrame.
Definition at line 252 of file satellite-phy-rx-carrier.cc.
References m_additionalInterferenceCallback, m_avgNormalizedOfferedLoadCallback, m_cnoCallback, m_rxCallback, m_satInterference, m_satInterferenceElimination, and m_uniformVariable.
Referenced by ns3::SatPhyRxCarrierPerSlot::DoDispose().
EndRxData()
virtual void ns3::SatPhyRxCarrier::EndRxData (uint32_t key) protected pure virtual
Function for ending the packet reception from the SatChannel.
Parameters
key Key for Rx params map
Implemented in ns3::SatPhyRxCarrierUplink, and ns3::SatPhyRxCarrierPerSlot.
Referenced by StartRx().
GetBeamId()
uint32_t ns3::SatPhyRxCarrier::GetBeamId (void) inline
Get ID the ID of the beam this carrier is attached to.
Returns
Beam ID
Definition at line 205 of file satellite-phy-rx-carrier.h.
References m_beamId.
Referenced by ns3::SatPhyRxCarrierPerSlot::CreateInterference(), ns3::SatPhyRxCarrierPerFrame::MeasureRandomAccessLoad(), ns3::SatPhyRxCarrierPerWindow::MeasureRandomAccessLoad(), ns3::SatPhyRxCarrierPerSlot::ReceiveSlot(), and StartRx().
GetCarrierId()
uint32_t ns3::SatPhyRxCarrier::GetCarrierId () const inline protected
Get the ID of the carrier.
Returns
Carrier ID
Definition at line 529 of file satellite-phy-rx-carrier.h.
References m_carrierId.
Referenced by ns3::SatPhyRxCarrierPerFrame::MeasureRandomAccessLoad(), ns3::SatPhyRxCarrierPerWindow::MeasureRandomAccessLoad(), and ns3::SatPhyRxCarrierPerSlot::ReceiveSlot().
GetCarrierType()
virtual CarrierType ns3::SatPhyRxCarrier::GetCarrierType () inline virtual
Method for querying the type of the carrier.
Reimplemented in ns3::SatPhyRxCarrierUplink, ns3::SatPhyRxCarrierPerWindow, ns3::SatPhyRxCarrierPerSlot, and ns3::SatPhyRxCarrierPerFrame.
Definition at line 226 of file satellite-phy-rx-carrier.h.
References BASE.
GetChannelEstimationErrorContainer()
Ptr<SatChannelEstimationErrorContainer> ns3::SatPhyRxCarrier::GetChannelEstimationErrorContainer () inline protected
Get a pointer to the channel estimation error container of the carrier.
Returns
channel estimation error containe pointer
Definition at line 557 of file satellite-phy-rx-carrier.h.
References m_channelEstimationError.
Referenced by ns3::SatPhyRxCarrierPerSlot::ReceiveSlot().
GetChannelType()
virtual SatEnums::ChannelType_t ns3::SatPhyRxCarrier::GetChannelType () inline protected virtual
Get the channel type.
Base class has undefined channel type, while child classes have can have other channel types.
Returns
Channel type
Definition at line 394 of file satellite-phy-rx-carrier.h.
References m_channelType.
Referenced by SatPhyRxCarrier(), CheckAgainstLinkResultsErrorModelAvi(), ns3::SatPhyRxCarrierPerSlot::CreateInterference(), DoCompositeSinrOutputTrace(), DoCreateInterferenceModel(), ns3::SatPhyRxCarrierUplink::EndRxData(), ns3::SatPhyRxCarrierPerWindow::MeasureRandomAccessLoad(), ns3::SatPhyRxCarrierPerSlot::ReceiveSlot(), and StartRx().
GetDefaultReceiveMode()
virtual const bool ns3::SatPhyRxCarrier::GetDefaultReceiveMode () inline protected virtual
Get the default receive mode for the carrier.
In satellite nodes, this will be overrided to always receive packets.
Returns
True or false, false by default in base class
Reimplemented in ns3::SatPhyRxCarrierUplink.
Definition at line 271 of file satellite-phy-rx-carrier.h.
Referenced by GetReceiveParams().
GetInterferenceEliminationModel()
Ptr<SatInterferenceElimination> ns3::SatPhyRxCarrier::GetInterferenceEliminationModel () inline protected
Get pointer to the current interference elimination model.
Returns
interference elimination model
Definition at line 298 of file satellite-phy-rx-carrier.h.
References m_satInterferenceElimination.
Referenced by ns3::SatPhyRxCarrierPerWindow::DoSic(), ns3::SatPhyRxCarrierPerFrame::EliminateInterference(), and ns3::SatPhyRxCarrierPerWindow::EliminatePreviousInterferences().
GetInterferenceModel()
Ptr<SatInterference> ns3::SatPhyRxCarrier::GetInterferenceModel () inline protected
Get pointer to the current interference model.
Returns
interference model
Definition at line 289 of file satellite-phy-rx-carrier.h.
References m_satInterference.
Referenced by ns3::SatPhyRxCarrierPerSlot::CreateInterference(), ns3::SatPhyRxCarrierUplink::CreateInterference(), ns3::SatPhyRxCarrierPerSlot::EndRxData(), ns3::SatPhyRxCarrierUplink::EndRxData(), ns3::SatPhyRxCarrierPerSlot::ProcessSlottedAlohaCollisions(), ns3::SatPhyRxCarrierPerFrame::ReceiveSlot(), ns3::SatPhyRxCarrierPerSlot::ReceiveSlot(), and StartRx().
GetLinkRegenerationMode()
virtual SatEnums::RegenerationMode_t ns3::SatPhyRxCarrier::GetLinkRegenerationMode () inline protected virtual
Get the link regeneration mode.
Returns
Link regeneration mode
Definition at line 412 of file satellite-phy-rx-carrier.h.
References m_linkRegenerationMode.
Referenced by ns3::SatPhyRxCarrierPerFrame::CalculatePacketCompositeSinr(), ns3::SatPhyRxCarrierPerWindow::CalculatePacketInterferenceVectors(), ns3::SatPhyRxCarrierPerSlot::CreateInterference(), ns3::SatPhyRxCarrierPerSlot::EndRxData(), ns3::SatPhyRxCarrierMarsala::PerformMarsala(), and ns3::SatPhyRxCarrierPerSlot::ReceiveSlot().
GetLinkResults()
Ptr<SatLinkResults> ns3::SatPhyRxCarrier::GetLinkResults () inline protected
Get pointer to the link results given by the carrier creation configuration.
Returns
Link results
Definition at line 539 of file satellite-phy-rx-carrier.h.
References m_linkResults.
Referenced by CheckAgainstLinkResultsErrorModelAvi(), and ns3::SatPhyRxCarrierPerWindow::GetEffectiveSnir().
GetNodeInfo()
Ptr<SatNodeInfo> ns3::SatPhyRxCarrier::GetNodeInfo () inline protected
Get the satellite node info.
Returns
SatNodeInfo pointer
Definition at line 357 of file satellite-phy-rx-carrier.h.
References m_nodeInfo.
Referenced by ns3::SatPhyRxCarrierPerFrame::BeginEndScheduling(), ns3::SatPhyRxCarrierPerWindow::BeginEndScheduling(), and ns3::SatPhyRxCarrierPerSlot::ReceiveSlot().
GetOwnAddress()
Mac48Address ns3::SatPhyRxCarrier::GetOwnAddress () inline protected
Get the MAC address of the carrier.
Returns
MAC address
Definition at line 348 of file satellite-phy-rx-carrier.h.
References m_ownAddress.
Referenced by ns3::SatPhyRxCarrierPerWindow::CalculatePacketInterferenceVectors(), ns3::SatPhyRxCarrierPerSlot::CreateInterference(), DoCompositeSinrOutputTrace(), ns3::SatPhyRxCarrierPerFrame::DoFrameEnd(), ns3::SatPhyRxCarrierUplink::EndRxData(), GetReceiveParams(), and ns3::SatPhyRxCarrierPerSlot::ReceiveSlot().
GetReceiveParams()
std::pair< bool, SatPhyRxCarrier::rxParams_s > ns3::SatPhyRxCarrier::GetReceiveParams (Ptr< SatSignalParameters > rxParams) protected
Rx parameter storage methods.
Get receive parameters from signal parameters.
Parameters
rxParams SatSignalParameters
Returns
A pair of boolean and rxParams_s struct. Boolean tells if we are about to receive a packet and struct contains all receiveing info.
Definition at line 308 of file satellite-phy-rx-carrier.cc.
References ns3::SatPhyRxCarrier::rxParams_s::destAddress, ns3::SatPhyRxCarrier::rxParams_s::finalDestAddress, ns3::SatPhyRxCarrier::rxParams_s::finalSourceAddress, ns3::SatEnums::FORWARD_FEEDER_CH, GetDefaultReceiveMode(), ns3::SatMacTag::GetDestAddress(), ns3::SatAddressE2ETag::GetE2EDestAddress(), ns3::SatAddressE2ETag::GetE2ESourceAddress(), GetOwnAddress(), ns3::SatMacTag::GetSourceAddress(), m_linkRegenerationMode, ns3::SatEnums::REGENERATION_PHY, ns3::SatEnums::RETURN_USER_CH, ns3::SatPhyRxCarrier::rxParams_s::rxParams, and ns3::SatPhyRxCarrier::rxParams_s::sourceAddress.
Referenced by StartRx().
GetRxTemperatureK()
double ns3::SatPhyRxCarrier::GetRxTemperatureK () inline
Method for querying the temperature of the carrier.
Definition at line 260 of file satellite-phy-rx-carrier.h.
References m_rxTemperatureK.
GetSatId()
uint32_t ns3::SatPhyRxCarrier::GetSatId () inline
Get ID the ID of the satellite this carrier is attached to.
Returns
Satellite ID
Definition at line 187 of file satellite-phy-rx-carrier.h.
References m_satId.
Referenced by ns3::SatPhyRxCarrierPerFrame::MeasureRandomAccessLoad(), ns3::SatPhyRxCarrierPerWindow::MeasureRandomAccessLoad(), and ns3::SatPhyRxCarrierPerSlot::ReceiveSlot().
GetState()
State ns3::SatPhyRxCarrier::GetState () inline protected
Get the state of the carrier.
Returns
State of the carrier.
Definition at line 436 of file satellite-phy-rx-carrier.h.
References m_state.
Referenced by ns3::SatPhyRxCarrierPerSlot::EndRxData(), and ns3::SatPhyRxCarrierUplink::EndRxData().
GetStoredRxParams()
rxParams_s ns3::SatPhyRxCarrier::GetStoredRxParams (uint32_t key) inline protected
Get stored rxParams under a key.
Definition at line 327 of file satellite-phy-rx-carrier.h.
References m_rxParamsMap.
Referenced by ns3::SatPhyRxCarrierPerSlot::EndRxData(), and ns3::SatPhyRxCarrierUplink::EndRxData().
GetTypeId()
TypeId ns3::SatPhyRxCarrier::GetTypeId (void) static
Function for gettign the NS-3 type ID.
Returns
Definition at line 214 of file satellite-phy-rx-carrier.cc.
References m_daRxCarrierIdTrace, m_daRxTrace, m_enableCompositeSinrOutputTrace, m_linkBudgetTrace, m_linkSinrTrace, m_rxPowerTrace, and m_sinrTrace.
GetUniformRandomValue()
double ns3::SatPhyRxCarrier::GetUniformRandomValue (double min, double max) inline protected
A helper method for getting values form a uniform random variable in child classes.
Parameters
min Minimum value
max Maximum value
Returns
Double between min and max
Definition at line 576 of file satellite-phy-rx-carrier.h.
References m_uniformVariable.
Referenced by CheckAgainstLinkResults(), CheckAgainstLinkResultsErrorModelAvi(), and ns3::SatPhyRxCarrierPerSlot::ProcessSlottedAlohaCollisions().
GetWaveformConf()
Ptr<SatWaveformConf> ns3::SatPhyRxCarrier::GetWaveformConf () inline protected
Get pointer to the waveform configuration.
Returns
Waveform Configuration
Definition at line 548 of file satellite-phy-rx-carrier.h.
References m_waveformConf.
Referenced by ns3::SatPhyRxCarrierPerWindow::CalculatePacketInterferenceVectors(), and ns3::SatPhyRxCarrierPerWindow::GetWindowBounds().
GetWorstSinr()
double ns3::SatPhyRxCarrier::GetWorstSinr (double sinr1, double sinr2) protected
Function for calculating the worst sinr between uplink and downlink.
Parameters
sinr1 SINR 1
sinr2 SINR 2
Returns
Worst SINR
Definition at line 694 of file satellite-phy-rx-carrier.cc.
Referenced by ns3::SatPhyRxCarrierPerSlot::ReceiveSlot().
IncreaseNumOfRxState()
void ns3::SatPhyRxCarrier::IncreaseNumOfRxState (SatEnums::PacketType_t packetType) protected
Function for increasing the number of ongoing transmissions.
Parameters
packetType Packet type of the ongoing transmission
Definition at line 712 of file satellite-phy-rx-carrier.cc.
References ChangeState(), CheckRxStateSanity(), m_numOfOngoingRx, m_receivingDedicatedAccess, ns3::SatEnums::PACKET_TYPE_DEDICATED_ACCESS, and RX.
Referenced by StartRx().
IsCompositeSinrOutputTraceEnabled()
bool ns3::SatPhyRxCarrier::IsCompositeSinrOutputTraceEnabled () const inline protected
Check if composite SINR output trace is enabled.
Definition at line 565 of file satellite-phy-rx-carrier.h.
References m_enableCompositeSinrOutputTrace.
Referenced by ns3::SatPhyRxCarrierPerWindow::CalculatePacketInterferenceVectors(), and ns3::SatPhyRxCarrierPerSlot::ReceiveSlot().
IsReceivingDedicatedAccess()
bool ns3::SatPhyRxCarrier::IsReceivingDedicatedAccess () inline protected
Check if the carrier is receiving a dedicated access packet.
Returns
true or false
Definition at line 280 of file satellite-phy-rx-carrier.h.
References m_receivingDedicatedAccess.
Referenced by StartRx().
RemoveStoredRxParams()
void ns3::SatPhyRxCarrier::RemoveStoredRxParams (uint32_t key) inline protected
Remove stored rxParams under a key.
Definition at line 339 of file satellite-phy-rx-carrier.h.
References m_rxParamsMap.
Referenced by ns3::SatPhyRxCarrierPerSlot::EndRxData(), and ns3::SatPhyRxCarrierUplink::EndRxData().
SetAverageNormalizedOfferedLoadCallback()
void ns3::SatPhyRxCarrier::SetAverageNormalizedOfferedLoadCallback (SatPhyRx::AverageNormalizedOfferedLoadCallback callback)
Function for setting the AverageNormalizedOfferedLoadCallback callback.
Parameters
callback callback
Definition at line 767 of file satellite-phy-rx-carrier.cc.
References m_avgNormalizedOfferedLoadCallback.
SetBeamId()
void ns3::SatPhyRxCarrier::SetBeamId (uint32_t beamId) inline
Function for setting the beam id for all the transmissions from this SatPhyTx.
Parameters
beamId the Beam Identifier
Definition at line 196 of file satellite-phy-rx-carrier.h.
References m_beamId.
SetChannelType()
void ns3::SatPhyRxCarrier::SetChannelType (SatEnums::ChannelType_t channelType) inline protected
Set the channel type for the carrier.
Parameters
channelType Channel type.
Definition at line 403 of file satellite-phy-rx-carrier.h.
References m_channelType.
Referenced by SatPhyRxCarrier().
SetCnoCb()
void ns3::SatPhyRxCarrier::SetCnoCb (SatPhyRx::CnoCallback cb)
Function for settign the C/NO callback.
Parameters
cb callback
Definition at line 293 of file satellite-phy-rx-carrier.cc.
References m_cnoCallback.
SetLinkRegenerationMode()
void ns3::SatPhyRxCarrier::SetLinkRegenerationMode (SatEnums::RegenerationMode_t linkRegenerationMode) inline protected
Set the link regeneration mode.
Parameters
linkRegenerationMode Link regeneration mode
Definition at line 421 of file satellite-phy-rx-carrier.h.
References m_linkRegenerationMode.
Referenced by SatPhyRxCarrier().
SetNodeInfo()
void ns3::SatPhyRxCarrier::SetNodeInfo (const Ptr< SatNodeInfo > nodeInfo)
Function for setting the node info class.
Parameters
nodeInfo Node information related to this SatPhyRxCarrier
Definition at line 620 of file satellite-phy-rx-carrier.cc.
References m_nodeInfo, and m_ownAddress.
SetPhy()
void ns3::SatPhyRxCarrier::SetPhy (Ptr< SatPhy > phy)
Function for setting the SatPhy module.
Parameters
phy PHY module
SetReceiveCb()
void ns3::SatPhyRxCarrier::SetReceiveCb (SatPhyRx::ReceiveCallback cb)
Function for setting the receive callback.
Parameters
cb callback
Definition at line 286 of file satellite-phy-rx-carrier.cc.
References m_rxCallback.
SetSatId()
void ns3::SatPhyRxCarrier::SetSatId (uint32_t satId) inline
Function for setting the satellite id for all the transmissions from this SatPhyTx.
Parameters
beamId the satellite Identifier
Definition at line 178 of file satellite-phy-rx-carrier.h.
References m_satId.
StartRx()
bool ns3::SatPhyRxCarrier::StartRx (Ptr< SatSignalParameters > rxParams) virtual
Function for starting packet reception from the SatChannel.
Parameters
rxParams The needed parameters for the received signal
Returns
true if packet is destinated to this beam
Reimplemented in ns3::SatPhyRxCarrierUplink.
Definition at line 375 of file satellite-phy-rx-carrier.cc.
References CreateInterference(), EndRxData(), ns3::SatPhyRxCarrier::rxParams_s::finalDestAddress, ns3::SatPhyRxCarrier::rxParams_s::finalSourceAddress, ns3::SatEnums::FORWARD_FEEDER_CH, ns3::SatEnums::FORWARD_USER_CH, GetBeamId(), GetChannelType(), ns3::SatEnums::GetChannelTypeName(), GetInterferenceModel(), GetReceiveParams(), IDLE, IncreaseNumOfRxState(), ns3::SatPhyRxCarrier::rxParams_s::interferenceEvent, IsReceivingDedicatedAccess(), ns3::SatUtils::LinearToDb(), m_carrierId, m_linkRegenerationMode, m_nodeInfo, m_rxPacketCounter, m_rxPowerTrace, m_state, ns3::SatEnums::PACKET_TYPE_DEDICATED_ACCESS, ns3::SatEnums::REGENERATION_LINK, ns3::SatEnums::REGENERATION_NETWORK, ns3::SatEnums::RETURN_FEEDER_CH, ns3::SatEnums::RETURN_USER_CH, RX, ns3::SatPhyRxCarrier::rxParams_s::sourceAddress, and StoreRxParams().
Referenced by ns3::SatPhyRxCarrierUplink::StartRx().
StoreRxParams()
void ns3::SatPhyRxCarrier::StoreRxParams (uint32_t key, rxParams_s rxParams) inline protected
Store rxParams under a key.
Definition at line 333 of file satellite-phy-rx-carrier.h.
References m_rxParamsMap.
Referenced by StartRx().
Member Data Documentation
m_additionalInterferenceCallback
SatPhyRxCarrierConf::AdditionalInterferenceCallback ns3::SatPhyRxCarrier::m_additionalInterferenceCallback protected
Callback to get additional interference.
Definition at line 666 of file satellite-phy-rx-carrier.h.
Referenced by SatPhyRxCarrier(), ns3::SatPhyRxCarrierPerFrame::CalculatePacketCompositeSinr(), ns3::SatPhyRxCarrierPerWindow::CalculatePacketInterferenceVectors(), DoDispose(), ns3::SatPhyRxCarrierUplink::EndRxData(), ns3::SatPhyRxCarrierMarsala::PerformMarsala(), ns3::SatPhyRxCarrierPerFrame::ProcessReceivedCrdsaPacket(), and ns3::SatPhyRxCarrierPerSlot::ReceiveSlot().
m_avgNormalizedOfferedLoadCallback
SatPhy::AverageNormalizedOfferedLoadCallback ns3::SatPhyRxCarrier::m_avgNormalizedOfferedLoadCallback protected
Average normalized offered load callback.
Definition at line 681 of file satellite-phy-rx-carrier.h.
Referenced by DoDispose(), ns3::SatPhyRxCarrierPerFrame::MeasureRandomAccessLoad(), ns3::SatPhyRxCarrierPerWindow::MeasureRandomAccessLoad(), and SetAverageNormalizedOfferedLoadCallback().
m_beamId
uint32_t ns3::SatPhyRxCarrier::m_beamId private
Definition at line 694 of file satellite-phy-rx-carrier.h.
Referenced by GetBeamId(), and SetBeamId().
m_carrierId
uint32_t ns3::SatPhyRxCarrier::m_carrierId private
Definition at line 695 of file satellite-phy-rx-carrier.h.
Referenced by SatPhyRxCarrier(), GetCarrierId(), and StartRx().
m_channelEstimationError
Ptr<SatChannelEstimationErrorContainer> ns3::SatPhyRxCarrier::m_channelEstimationError private
Channel estimation error container.
Definition at line 724 of file satellite-phy-rx-carrier.h.
Referenced by SatPhyRxCarrier(), and GetChannelEstimationErrorContainer().
m_channelType
SatEnums::ChannelType_t ns3::SatPhyRxCarrier::m_channelType private
Definition at line 714 of file satellite-phy-rx-carrier.h.
Referenced by GetChannelType(), and SetChannelType().
m_cnoCallback
SatPhy::CnoCallback ns3::SatPhyRxCarrier::m_cnoCallback protected
The upper layer C/N0 receive callback.
Definition at line 676 of file satellite-phy-rx-carrier.h.
Referenced by DoDispose(), ns3::SatPhyRxCarrierPerSlot::ReceiveSlot(), and SetCnoCb().
m_constantErrorRate
double ns3::SatPhyRxCarrier::m_constantErrorRate private
Definition at line 719 of file satellite-phy-rx-carrier.h.
Referenced by SatPhyRxCarrier(), and CheckAgainstLinkResults().
m_daRxCarrierIdTrace
TracedCallback<uint32_t, const Address&> ns3::SatPhyRxCarrier::m_daRxCarrierIdTrace protected
Definition at line 661 of file satellite-phy-rx-carrier.h.
Referenced by GetTypeId(), and ns3::SatPhyRxCarrierPerSlot::ReceiveSlot().
m_daRxTrace
TracedCallback<uint32_t, const Address&, bool> ns3::SatPhyRxCarrier::m_daRxTrace protected
DaRx trace source.
Fired when a packet burst is received through Dedicated Channel.
Contains the following information:
number of upper layer packets in the received packet burst;
the MAC48 address of the sender; and
whether a PHY error has occurred.
Definition at line 659 of file satellite-phy-rx-carrier.h.
Referenced by ns3::SatPhyRxCarrierPerWindow::CleanOldPackets(), GetTypeId(), and ns3::SatPhyRxCarrierPerSlot::ReceiveSlot().
m_enableCompositeSinrOutputTrace
bool ns3::SatPhyRxCarrier::m_enableCompositeSinrOutputTrace private
Definition at line 699 of file satellite-phy-rx-carrier.h.
Referenced by GetTypeId(), and IsCompositeSinrOutputTraceEnabled().
m_errorModel
SatPhyRxCarrierConf::ErrorModel ns3::SatPhyRxCarrier::m_errorModel private
Definition at line 718 of file satellite-phy-rx-carrier.h.
Referenced by SatPhyRxCarrier(), and CheckAgainstLinkResults().
m_linkBudgetTrace
TracedCallback<Ptr<SatSignalParameters>, Mac48Address, Mac48Address, double, double > ns3::SatPhyRxCarrier::m_linkBudgetTrace protected
The trace source on packet receptiong.
See also
class CallBackTraceSource
Definition at line 624 of file satellite-phy-rx-carrier.h.
Referenced by ns3::SatPhyRxCarrierPerWindow::CalculatePacketInterferenceVectors(), ns3::SatPhyRxCarrierPerFrame::DoFrameEnd(), ns3::SatPhyRxCarrierUplink::EndRxData(), GetTypeId(), and ns3::SatPhyRxCarrierPerSlot::ReceiveSlot().
m_linkRegenerationMode
SatEnums::RegenerationMode_t ns3::SatPhyRxCarrier::m_linkRegenerationMode protected
Link regeneration mode.
Definition at line 610 of file satellite-phy-rx-carrier.h.
Referenced by CheckAgainstLinkResultsErrorModelAvi(), ns3::SatPhyRxCarrierPerWindow::DoSic(), ns3::SatPhyRxCarrierPerFrame::EliminateInterference(), ns3::SatPhyRxCarrierPerWindow::EliminatePreviousInterferences(), GetLinkRegenerationMode(), GetReceiveParams(), SetLinkRegenerationMode(), and StartRx().
m_linkResults
Ptr<SatLinkResults> ns3::SatPhyRxCarrier::m_linkResults private
Definition at line 715 of file satellite-phy-rx-carrier.h.
Referenced by SatPhyRxCarrier(), and GetLinkResults().
m_linkSinrTrace
TracedCallback<double, const Address&> ns3::SatPhyRxCarrier::m_linkSinrTrace protected
A callback for link specific SINR in dB.
Definition at line 645 of file satellite-phy-rx-carrier.h.
Referenced by ns3::SatPhyRxCarrierPerWindow::CalculatePacketInterferenceVectors(), ns3::SatPhyRxCarrierUplink::EndRxData(), GetTypeId(), ns3::SatPhyRxCarrierMarsala::PerformMarsala(), ns3::SatPhyRxCarrierPerFrame::ProcessReceivedCrdsaPacket(), and ns3::SatPhyRxCarrierPerSlot::ReceiveSlot().
m_nodeInfo
Ptr<SatNodeInfo> ns3::SatPhyRxCarrier::m_nodeInfo private
Definition at line 713 of file satellite-phy-rx-carrier.h.
Referenced by GetNodeInfo(), SetNodeInfo(), and StartRx().
m_numOfOngoingRx
uint32_t ns3::SatPhyRxCarrier::m_numOfOngoingRx private
Contains information about how many ongoing Rx events there are.
Definition at line 704 of file satellite-phy-rx-carrier.h.
Referenced by CheckRxStateSanity(), DecreaseNumOfRxState(), and IncreaseNumOfRxState().
m_ownAddress
Mac48Address ns3::SatPhyRxCarrier::m_ownAddress private
Definition at line 712 of file satellite-phy-rx-carrier.h.
Referenced by GetOwnAddress(), and SetNodeInfo().
m_randomAccessEnabled
const bool ns3::SatPhyRxCarrier::m_randomAccessEnabled protected
Is random access enabled for this carrier.
Definition at line 458 of file satellite-phy-rx-carrier.h.
Referenced by ns3::SatPhyRxCarrierPerFrame::SatPhyRxCarrierPerFrame(), ns3::SatPhyRxCarrierPerWindow::SatPhyRxCarrierPerWindow(), DoCreateInterferenceEliminationModel(), DoCreateInterferenceModel(), and ns3::SatPhyRxCarrierPerSlot::GetCarrierType().
m_receivingDedicatedAccess
bool ns3::SatPhyRxCarrier::m_receivingDedicatedAccess private
Definition at line 696 of file satellite-phy-rx-carrier.h.
Referenced by DecreaseNumOfRxState(), IncreaseNumOfRxState(), and IsReceivingDedicatedAccess().
m_rxAciIfPowerW
double ns3::SatPhyRxCarrier::m_rxAciIfPowerW protected
RX Adjacent channel interference.
Definition at line 605 of file satellite-phy-rx-carrier.h.
Referenced by SatPhyRxCarrier(), ns3::SatPhyRxCarrierPerFrame::CalculatePacketCompositeSinr(), ns3::SatPhyRxCarrierPerWindow::CalculatePacketInterferenceVectors(), ns3::SatPhyRxCarrierUplink::EndRxData(), ns3::SatPhyRxCarrierMarsala::PerformMarsala(), and ns3::SatPhyRxCarrierPerSlot::ReceiveSlot().
m_rxBandwidthHz
double ns3::SatPhyRxCarrier::m_rxBandwidthHz protected
RX Bandwidth in Hz.
Definition at line 590 of file satellite-phy-rx-carrier.h.
Referenced by SatPhyRxCarrier(), ns3::SatPhyRxCarrierPerFrame::CalculateNormalizedOfferedRandomAccessLoad(), ns3::SatPhyRxCarrierPerWindow::CalculateNormalizedOfferedRandomAccessLoad(), and ns3::SatPhyRxCarrierPerSlot::ReceiveSlot().
m_rxCallback
SatPhyRx::ReceiveCallback ns3::SatPhyRxCarrier::m_rxCallback protected
The upper layer package receive callback.
Definition at line 671 of file satellite-phy-rx-carrier.h.
Referenced by DoDispose(), ns3::SatPhyRxCarrierPerFrame::DoFrameEnd(), ns3::SatPhyRxCarrierPerWindow::ProcessWindow(), ns3::SatPhyRxCarrierPerSlot::ReceiveSlot(), SetReceiveCb(), and ns3::SatPhyRxCarrierUplink::StartRx().
m_rxExtNoisePowerW
double ns3::SatPhyRxCarrier::m_rxExtNoisePowerW protected
External noise power system RX noise.
Definition at line 595 of file satellite-phy-rx-carrier.h.
Referenced by SatPhyRxCarrier(), ns3::SatPhyRxCarrierPerFrame::CalculatePacketCompositeSinr(), ns3::SatPhyRxCarrierPerWindow::CalculatePacketInterferenceVectors(), ns3::SatPhyRxCarrierUplink::EndRxData(), ns3::SatPhyRxCarrierMarsala::PerformMarsala(), and ns3::SatPhyRxCarrierPerSlot::ReceiveSlot().
m_rxNoisePowerW
double ns3::SatPhyRxCarrier::m_rxNoisePowerW protected
RX noise.
Definition at line 600 of file satellite-phy-rx-carrier.h.
Referenced by SatPhyRxCarrier(), ns3::SatPhyRxCarrierPerFrame::CalculatePacketCompositeSinr(), ns3::SatPhyRxCarrierPerWindow::CalculatePacketInterferenceVectors(), ns3::SatPhyRxCarrierUplink::EndRxData(), ns3::SatPhyRxCarrierMarsala::PerformMarsala(), and ns3::SatPhyRxCarrierPerSlot::ReceiveSlot().
m_rxPacketCounter
uint32_t ns3::SatPhyRxCarrier::m_rxPacketCounter private
Running counter for received packets.
Definition at line 709 of file satellite-phy-rx-carrier.h.
Referenced by StartRx().
m_rxParamsMap
std::map<uint32_t, rxParams_s> ns3::SatPhyRxCarrier::m_rxParamsMap private
Definition at line 711 of file satellite-phy-rx-carrier.h.
Referenced by GetStoredRxParams(), RemoveStoredRxParams(), and StoreRxParams().
m_rxPowerTrace
TracedCallback<double, const Address&> ns3::SatPhyRxCarrier::m_rxPowerTrace protected
A callback for received signal power in dBW.
Definition at line 630 of file satellite-phy-rx-carrier.h.
Referenced by GetTypeId(), and StartRx().
m_rxTemperatureK
double ns3::SatPhyRxCarrier::m_rxTemperatureK protected
RX noise temperature in K.
Definition at line 585 of file satellite-phy-rx-carrier.h.
Referenced by SatPhyRxCarrier(), and GetRxTemperatureK().
m_satId
uint32_t ns3::SatPhyRxCarrier::m_satId private
Definition at line 693 of file satellite-phy-rx-carrier.h.
Referenced by GetSatId(), and SetSatId().
m_satInterference
Ptr<SatInterference> ns3::SatPhyRxCarrier::m_satInterference private
Definition at line 697 of file satellite-phy-rx-carrier.h.
Referenced by DoCreateInterferenceModel(), DoDispose(), and GetInterferenceModel().
m_satInterferenceElimination
Ptr<SatInterferenceElimination> ns3::SatPhyRxCarrier::m_satInterferenceElimination private
Definition at line 698 of file satellite-phy-rx-carrier.h.
Referenced by DoCreateInterferenceEliminationModel(), DoDispose(), and GetInterferenceEliminationModel().
m_sinrTrace
TracedCallback<double, const Address&> ns3::SatPhyRxCarrier::m_sinrTrace protected
A callback for transmission composite SINR at UT (BBFrame) or GW (time slot).
The first argument is the SINR in dB. The second argument is the address of the node where the signal originates from.
Definition at line 639 of file satellite-phy-rx-carrier.h.
Referenced by ns3::SatPhyRxCarrierPerFrame::DoFrameEnd(), GetTypeId(), ns3::SatPhyRxCarrierPerWindow::ProcessWindow(), and ns3::SatPhyRxCarrierPerSlot::ReceiveSlot().
m_state
State ns3::SatPhyRxCarrier::m_state private
Definition at line 692 of file satellite-phy-rx-carrier.h.
Referenced by ChangeState(), CheckRxStateSanity(), GetState(), and StartRx().
m_uniformVariable
Ptr<UniformRandomVariable> ns3::SatPhyRxCarrier::m_uniformVariable private
Definition at line 717 of file satellite-phy-rx-carrier.h.
Referenced by SatPhyRxCarrier(), DoDispose(), and GetUniformRandomValue().
m_waveformConf
Ptr<SatWaveformConf> ns3::SatPhyRxCarrier::m_waveformConf private
Definition at line 716 of file satellite-phy-rx-carrier.h.
Referenced by GetWaveformConf().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-phy-rx-carrier.h
/builds/sns3/satellite/satellite/model/satellite-phy-rx-carrier.cc