SNS3
ns3::SatPhyRxCarrierPerSlot Class Reference
Inherited the base functionality of SatPhyRxCarriers for ground station nodes.
#include "satellite-phy-rx-carrier-per-slot.h"
Public Member Functions
SatPhyRxCarrierPerSlot (uint32_t carrierId, Ptr< SatPhyRxCarrierConf > carrierConf, Ptr< SatWaveformConf > waveformConf, bool randomAccessEnabled)
Constructor.
virtual ~SatPhyRxCarrierPerSlot ()
Destructor.
virtual void BeginEndScheduling ()
Function for initializing the frame/window end scheduling.
virtual CarrierType GetCarrierType ()
Method for querying the type of the carrier.
uint8_t GetRandomAccessAllocationChannelId () const
Function for getting the random access allocation channel ID.
void SetRandomAccessAllocationChannelId (uint8_t randomAccessAllocationChannelId)
Function for setting the random access allocation channel ID.
Public Member Functions inherited from ns3::SatPhyRxCarrier
SatPhyRxCarrier (uint32_t carrierId, Ptr< SatPhyRxCarrierConf > carrierConf, Ptr< SatWaveformConf > waveformConf, bool isRandomAccessEnabled)
Constructor.
virtual ~SatPhyRxCarrier ()
Destructor.
uint32_t GetBeamId ()
Get ID the ID of the beam this carrier is attached to.
double GetRxTemperatureK ()
Method for querying the temperature of the carrier.
uint32_t GetSatId ()
Get ID the ID of the satellite this carrier is attached to.
void SetAverageNormalizedOfferedLoadCallback (SatPhyRx::AverageNormalizedOfferedLoadCallback callback)
Function for setting the AverageNormalizedOfferedLoadCallback callback.
void SetBeamId (uint32_t beamId)
Function for setting the beam id for all the transmissions from this SatPhyTx.
void SetCnoCb (SatPhyRx::CnoCallback cb)
Function for settign the C/NO callback.
void SetNodeInfo (const Ptr< SatNodeInfo > nodeInfo)
Function for setting the node info class.
void SetPhy (Ptr< SatPhy > phy)
Function for setting the SatPhy module.
void SetReceiveCb (SatPhyRx::ReceiveCallback cb)
Function for setting the receive callback.
void SetSatId (uint32_t satId)
Function for setting the satellite id for all the transmissions from this SatPhyTx.
virtual bool StartRx (Ptr< SatSignalParameters > rxParams)
Function for starting packet reception from the SatChannel.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the TypeId of the class.
Static Public Member Functions inherited from ns3::SatPhyRxCarrier
static TypeId GetTypeId (void)
Function for gettign the NS-3 type ID.
Protected Member Functions
double CalculateAverageNormalizedOfferedRandomAccessLoad ()
Function for calculating the average normalized offered random access load.
virtual Ptr< SatInterference::InterferenceChangeEvent > CreateInterference (Ptr< SatSignalParameters > rxParams, Address rxAddress)
Create an interference event based on Rx parameters and address.
virtual void DoDispose ()
Dispose implementation.
virtual void EndRxData (uint32_t key)
Function for ending the packet reception from the SatChannel.
SatPhyRxCarrierConf::RandomAccessCollisionModel GetRandomAccessCollisionModel () const
Get the random access collision model of the carrier.
bool IsRandomAccessDynamicLoadControlEnabled () const
Check if random access dynamic load control is enabled.
virtual void ReceiveSlot (SatPhyRxCarrier::rxParams_s packetRxParams, const uint32_t nPackets)
Receive a slot.
void SaveMeasuredRandomAccessLoad (double measuredRandomAccessLoad)
Function for saving the measured random access load.
Protected Member Functions inherited from ns3::SatPhyRxCarrier
double CalculateCompositeSinr (double sinr1, double sinr2)
Function for calculating the composite SINR.
double CalculateSinr (double rxPowerW, double ifPowerW, double rxNoisePowerW, double rxAciIfPowerW, double rxExtNoisePowerW, double otherInterference)
Function for calculating the SINR.
double CalculateSinr (double sinr, double otherInterference)
Calculate final SINR with PHY specific parameters and given calculated SINR.
void ChangeState (State newState)
Function for changing the receiver state.
bool CheckAgainstLinkResults (double cSinr, Ptr< SatSignalParameters > rxParams)
Function for checking the SINR against the link results.
void CheckRxStateSanity ()
Function for checking the Rx state sanity.
void DecreaseNumOfRxState (SatEnums::PacketType_t packetType)
Function for decreasing the number of ongoing transmissions.
void DoCompositeSinrOutputTrace (double cSinr)
Function for composite SINR output tracing.
virtual void DoCreateInterferenceEliminationModel (Ptr< SatPhyRxCarrierConf > carrierConf, uint32_t carrierId, Ptr< SatWaveformConf > waveformConf)
Create an interference cancelation model for this carrier.
virtual void DoCreateInterferenceModel (Ptr< SatPhyRxCarrierConf > carrierConf, uint32_t carrierId, double rxBandwidthHz)
Create an interference model for this carrier.
uint32_t GetCarrierId () const
Get the ID of the carrier.
Ptr< SatChannelEstimationErrorContainer > GetChannelEstimationErrorContainer ()
Get a pointer to the channel estimation error container of the carrier.
virtual SatEnums::ChannelType_t GetChannelType ()
Get the channel type.
virtual const bool GetDefaultReceiveMode ()
Get the default receive mode for the carrier.
Ptr< SatInterferenceElimination > GetInterferenceEliminationModel ()
Get pointer to the current interference elimination model.
Ptr< SatInterference > GetInterferenceModel ()
Get pointer to the current interference model.
virtual SatEnums::RegenerationMode_t GetLinkRegenerationMode ()
Get the link regeneration mode.
Ptr< SatLinkResults > GetLinkResults ()
Get pointer to the link results given by the carrier creation configuration.
Ptr< SatNodeInfo > GetNodeInfo ()
Get the satellite node info.
Mac48Address GetOwnAddress ()
Get the MAC address of the carrier.
std::pair< bool, SatPhyRxCarrier::rxParams_s > GetReceiveParams (Ptr< SatSignalParameters > rxParams)
Rx parameter storage methods.
State GetState ()
Get the state of the carrier.
rxParams_s GetStoredRxParams (uint32_t key)
Get stored rxParams under a key.
double GetUniformRandomValue (double min, double max)
A helper method for getting values form a uniform random variable in child classes.
Ptr< SatWaveformConf > GetWaveformConf ()
Get pointer to the waveform configuration.
double GetWorstSinr (double sinr1, double sinr2)
Function for calculating the worst sinr between uplink and downlink.
void IncreaseNumOfRxState (SatEnums::PacketType_t packetType)
Function for increasing the number of ongoing transmissions.
bool IsCompositeSinrOutputTraceEnabled () const
Check if composite SINR output trace is enabled.
bool IsReceivingDedicatedAccess ()
Check if the carrier is receiving a dedicated access packet.
void RemoveStoredRxParams (uint32_t key)
Remove stored rxParams under a key.
void SetChannelType (SatEnums::ChannelType_t channelType)
Set the channel type for the carrier.
void SetLinkRegenerationMode (SatEnums::RegenerationMode_t linkRegenerationMode)
Set the link regeneration mode.
void StoreRxParams (uint32_t key, rxParams_s rxParams)
Store rxParams under a key.
Protected Attributes
uint32_t m_randomAccessBitsInFrame
The number of random access bits in current frame.
TracedCallback< uint32_t, const Address &, bool > m_slottedAlohaRxCollisionTrace
SlottedAlohaRxCollision trace source.
TracedCallback< uint32_t, const Address &, bool > m_slottedAlohaRxErrorTrace
SlottedAlohaRxError trace source.
Protected Attributes inherited from ns3::SatPhyRxCarrier
SatPhyRxCarrierConf::AdditionalInterferenceCallback m_additionalInterferenceCallback
Callback to get additional interference.
SatPhy::AverageNormalizedOfferedLoadCallback m_avgNormalizedOfferedLoadCallback
Average normalized offered load callback.
SatPhy::CnoCallback m_cnoCallback
The upper layer C/N0 receive callback.
TracedCallback< uint32_t, const Address & > m_daRxCarrierIdTrace
TracedCallback< uint32_t, const Address &, bool > m_daRxTrace
DaRx trace source.
TracedCallback< Ptr< SatSignalParameters >, Mac48Address, Mac48Address, double, double > m_linkBudgetTrace
The trace source on packet receptiong.
SatEnums::RegenerationMode_t m_linkRegenerationMode
Link regeneration mode.
TracedCallback< double, const Address & > m_linkSinrTrace
A callback for link specific SINR in dB.
const bool m_randomAccessEnabled
Is random access enabled for this carrier.
double m_rxAciIfPowerW
RX Adjacent channel interference.
double m_rxBandwidthHz
RX Bandwidth in Hz.
SatPhyRx::ReceiveCallback m_rxCallback
The upper layer package receive callback.
double m_rxExtNoisePowerW
External noise power system RX noise.
double m_rxNoisePowerW
RX noise.
TracedCallback< double, const Address & > m_rxPowerTrace
A callback for received signal power in dBW.
double m_rxTemperatureK
RX noise temperature in K.
TracedCallback< double, const Address & > m_sinrTrace
A callback for transmission composite SINR at UT (BBFrame) or GW (time slot).
Private Member Functions
bool ProcessSlottedAlohaCollisions (double cSinr, Ptr< SatSignalParameters > rxParams, Ptr< SatInterference::InterferenceChangeEvent > interferenceEvent)
Function for processing the Slotted ALOHA collisions.
Private Attributes
bool m_disableErrorHighTransmissionTime
bool m_enableRandomAccessDynamicLoadControl
uint8_t m_randomAccessAllocationChannelId
PRIVATE MEMBER VARIABLES.
uint32_t m_randomAccessAverageNormalizedOfferedLoadMeasurementWindowSize
SatPhyRxCarrierConf::RandomAccessCollisionModel m_randomAccessCollisionModel
double m_randomAccessConstantErrorRate
std::deque< double > m_randomAccessDynamicLoadControlNormalizedOfferedLoad
Additional Inherited Members
Public Types inherited from ns3::SatPhyRxCarrier
enum CarrierType {
BASE , DEDICATED_ACCESS , RA_SLOTTED_ALOHA , RA_CRDSA ,
RA_ESSA
}
Possible carrier types.
typedef void(* LinkBudgetTraceCallback) (Ptr< SatSignalParameters > rxParams, Mac48Address receiverAddress, Mac48Address destinationAddress, double interference, double sinr)
Callback signature for LinkBudgetTrace trace source.
typedef void(* LinkSinrTraceCallback) (double sinr, const Address &utAddress)
Callback signature for LinkSinrTrace trace source.
typedef void(* PhyRxCollisionCallback) (uint32_t nPackets, const Address &utAddress, bool isCollided)
Common callback signature for trace sources related to packets reception by PHY and its collision.
typedef void(* PhyRxErrorCallback) (uint32_t nPackets, const Address &utAddress, bool isError)
Common callback signature for trace sources related to packets reception by PHY and its error.
typedef void(* RxPowerTraceCallback) (double rxPower, const Address &utAddress)
Callback signature for RxPowerTrace trace source.
enum State { IDLE , RX }
Enum for PHY states.
Detailed Description
Inherited the base functionality of SatPhyRxCarriers for ground station nodes.
Definition at line 48 of file satellite-phy-rx-carrier-per-slot.h.
Constructor & Destructor Documentation
SatPhyRxCarrierPerSlot()
ns3::SatPhyRxCarrierPerSlot::SatPhyRxCarrierPerSlot (uint32_t carrierId, Ptr< SatPhyRxCarrierConf > carrierConf, Ptr< SatWaveformConf > waveformConf, bool randomAccessEnabled)
Constructor.
Parameters
carrierId ID of the carrier
carrierConf Carrier configuration
waveformConf Waveform configuration
randomAccessEnabled Is this a RA carrier
Definition at line 44 of file satellite-phy-rx-carrier-per-slot.cc.
References m_enableRandomAccessDynamicLoadControl, m_randomAccessAverageNormalizedOfferedLoadMeasurementWindowSize, m_randomAccessCollisionModel, and m_randomAccessConstantErrorRate.
~SatPhyRxCarrierPerSlot()
ns3::SatPhyRxCarrierPerSlot::~SatPhyRxCarrierPerSlot () virtual
Destructor.
Definition at line 74 of file satellite-phy-rx-carrier-per-slot.cc.
Member Function Documentation
BeginEndScheduling()
void ns3::SatPhyRxCarrierPerSlot::BeginEndScheduling (void) virtual
Function for initializing the frame/window end scheduling.
Reimplemented from ns3::SatPhyRxCarrier.
Reimplemented in ns3::SatPhyRxCarrierPerWindow, and ns3::SatPhyRxCarrierPerFrame.
Definition at line 80 of file satellite-phy-rx-carrier-per-slot.cc.
CalculateAverageNormalizedOfferedRandomAccessLoad()
double ns3::SatPhyRxCarrierPerSlot::CalculateAverageNormalizedOfferedRandomAccessLoad () protected
Function for calculating the average normalized offered random access load.
Returns
Average normalized offered load
Definition at line 542 of file satellite-phy-rx-carrier-per-slot.cc.
References m_randomAccessDynamicLoadControlNormalizedOfferedLoad.
Referenced by ns3::SatPhyRxCarrierPerFrame::MeasureRandomAccessLoad(), and ns3::SatPhyRxCarrierPerWindow::MeasureRandomAccessLoad().
CreateInterference()
Ptr< SatInterference::InterferenceChangeEvent > ns3::SatPhyRxCarrierPerSlot::CreateInterference (Ptr< SatSignalParameters > rxParams, Address rxAddress) protected virtual
Create an interference event based on Rx parameters and address.
Returns
Pointer to the interference event.
Implements ns3::SatPhyRxCarrier.
Definition at line 120 of file satellite-phy-rx-carrier-per-slot.cc.
References ns3::SatEnums::FORWARD_USER_CH, ns3::SatPhyRxCarrier::GetBeamId(), ns3::SatPhyRxCarrier::GetChannelType(), ns3::SatPhyRxCarrier::GetInterferenceModel(), ns3::SatPhyRxCarrier::GetLinkRegenerationMode(), ns3::SatPhyRxCarrier::GetOwnAddress(), m_disableErrorHighTransmissionTime, ns3::SatEnums::RETURN_FEEDER_CH, and ns3::SatEnums::TRANSPARENT.
DoDispose()
void ns3::SatPhyRxCarrierPerSlot::DoDispose (void) protected virtual
Dispose implementation.
Reimplemented from ns3::SatPhyRxCarrier.
Reimplemented in ns3::SatPhyRxCarrierPerWindow, and ns3::SatPhyRxCarrierPerFrame.
Definition at line 111 of file satellite-phy-rx-carrier-per-slot.cc.
References ns3::SatPhyRxCarrier::DoDispose(), and m_randomAccessDynamicLoadControlNormalizedOfferedLoad.
Referenced by ns3::SatPhyRxCarrierPerFrame::DoDispose(), and ns3::SatPhyRxCarrierPerWindow::DoDispose().
EndRxData()
void ns3::SatPhyRxCarrierPerSlot::EndRxData (uint32_t key) protected virtual
Function for ending the packet reception from the SatChannel.
Parameters
key Key for Rx params map
erase the used Rx params
Implements ns3::SatPhyRxCarrier.
Definition at line 190 of file satellite-phy-rx-carrier-per-slot.cc.
References ns3::SatPhyRxCarrier::DecreaseNumOfRxState(), ns3::SatPhyRxCarrier::GetInterferenceModel(), ns3::SatPhyRxCarrier::GetLinkRegenerationMode(), ns3::SatPhyRxCarrier::GetState(), ns3::SatPhyRxCarrier::GetStoredRxParams(), ns3::SatPhyRxCarrier::rxParams_s::interferenceEvent, ReceiveSlot(), ns3::SatPhyRxCarrier::RemoveStoredRxParams(), ns3::SatPhyRxCarrier::RX, ns3::SatPhyRxCarrier::rxParams_s::rxParams, and ns3::SatEnums::TRANSPARENT.
GetCarrierType()
virtual CarrierType ns3::SatPhyRxCarrierPerSlot::GetCarrierType () inline virtual
Method for querying the type of the carrier.
Reimplemented from ns3::SatPhyRxCarrier.
Reimplemented in ns3::SatPhyRxCarrierPerWindow, and ns3::SatPhyRxCarrierPerFrame.
Definition at line 100 of file satellite-phy-rx-carrier-per-slot.h.
References ns3::SatPhyRxCarrier::m_randomAccessEnabled.
GetRandomAccessAllocationChannelId()
uint8_t ns3::SatPhyRxCarrierPerSlot::GetRandomAccessAllocationChannelId () const inline
Function for getting the random access allocation channel ID.
Returns
randomAccessAllocationChannelId
Definition at line 92 of file satellite-phy-rx-carrier-per-slot.h.
References m_randomAccessAllocationChannelId.
Referenced by ns3::SatPhyRxCarrierPerFrame::MeasureRandomAccessLoad(), and ns3::SatPhyRxCarrierPerWindow::MeasureRandomAccessLoad().
GetRandomAccessCollisionModel()
SatPhyRxCarrierConf::RandomAccessCollisionModel ns3::SatPhyRxCarrierPerSlot::GetRandomAccessCollisionModel () const inline protected
Get the random access collision model of the carrier.
Definition at line 126 of file satellite-phy-rx-carrier-per-slot.h.
References m_randomAccessCollisionModel.
Referenced by ns3::SatPhyRxCarrierPerFrame::ProcessReceivedCrdsaPacket().
GetTypeId()
TypeId ns3::SatPhyRxCarrierPerSlot::GetTypeId (void) static
Get the TypeId of the class.
Returns
TypeId
Definition at line 85 of file satellite-phy-rx-carrier-per-slot.cc.
References m_disableErrorHighTransmissionTime, m_slottedAlohaRxCollisionTrace, and m_slottedAlohaRxErrorTrace.
IsRandomAccessDynamicLoadControlEnabled()
bool ns3::SatPhyRxCarrierPerSlot::IsRandomAccessDynamicLoadControlEnabled () const inline protected
Check if random access dynamic load control is enabled.
Definition at line 134 of file satellite-phy-rx-carrier-per-slot.h.
References m_enableRandomAccessDynamicLoadControl.
Referenced by ns3::SatPhyRxCarrierPerFrame::DoFrameEnd(), and ns3::SatPhyRxCarrierPerWindow::ProcessWindow().
ProcessSlottedAlohaCollisions()
bool ns3::SatPhyRxCarrierPerSlot::ProcessSlottedAlohaCollisions (double cSinr, Ptr< SatSignalParameters > rxParams, Ptr< SatInterference::InterferenceChangeEvent > interferenceEvent) private
Function for processing the Slotted ALOHA collisions.
Parameters
cSinr Composite SINR
rxParams Rx parameters of the packet
interferenceEvent Interference event details
Returns
PHY error
check whether the packet has collided. This mode is intended to be used with constant interference and traced interference
check cSinr against link results
Definition at line 223 of file satellite-phy-rx-carrier-per-slot.cc.
References ns3::SatPhyRxCarrier::CheckAgainstLinkResults(), ns3::SatPhyRxCarrier::GetInterferenceModel(), ns3::SatPhyRxCarrier::GetUniformRandomValue(), m_randomAccessCollisionModel, m_randomAccessConstantErrorRate, ns3::SatPhyRxCarrierConf::RA_COLLISION_ALWAYS_DROP_ALL_COLLIDING_PACKETS, ns3::SatPhyRxCarrierConf::RA_COLLISION_CHECK_AGAINST_SINR, and ns3::SatPhyRxCarrierConf::RA_CONSTANT_COLLISION_PROBABILITY.
Referenced by ReceiveSlot().
ReceiveSlot()
void ns3::SatPhyRxCarrierPerSlot::ReceiveSlot (SatPhyRxCarrier::rxParams_s packetRxParams, const uint32_t nPackets) protected virtual
Receive a slot.
Overridable by child classes.
calculates sinr for 2nd link
PHY transmission decoded successfully. Note, that at transparent satellite, all the transmissions are not decoded.
calculate composite SINR if transparent. Otherwise take only current sinr.
Channel estimation error is added to the cno measurement, which is utilized e.g. for ACM.
Channel estimation error is added to the cno measurement, which is utilized e.g. for ACM.
composite sinr output trace
check for slotted aloha packet collisions
check against link results
uses composite sinr
send packet upwards
Reimplemented in ns3::SatPhyRxCarrierPerWindow, and ns3::SatPhyRxCarrierPerFrame.
Definition at line 265 of file satellite-phy-rx-carrier-per-slot.cc.
References ns3::SatConstVariables::BITS_PER_BYTE, ns3::SatPhyRxCarrier::CalculateCompositeSinr(), ns3::SatPhyRxCarrier::CalculateSinr(), ns3::SatPhyRxCarrier::CheckAgainstLinkResults(), ns3::SatUtils::DbToLinear(), ns3::SatPhyRxCarrier::rxParams_s::destAddress, ns3::SatPhyRxCarrier::DoCompositeSinrOutputTrace(), ns3::SatEnums::FORWARD_FEEDER_CH, ns3::SatEnums::FORWARD_USER_CH, ns3::SatPhyRxCarrier::GetBeamId(), ns3::SatUplinkInfoTag::GetBeamId(), ns3::SatPhyRxCarrier::GetCarrierId(), ns3::SatPhyRxCarrier::GetChannelEstimationErrorContainer(), ns3::SatPhyRxCarrier::GetChannelType(), ns3::SatEnums::GetChannelTypeName(), ns3::SatAddressE2ETag::GetE2EDestAddress(), ns3::SatAddressE2ETag::GetE2ESourceAddress(), ns3::SatPhyRxCarrier::GetInterferenceModel(), ns3::SatPhyRxCarrier::GetLinkRegenerationMode(), ns3::SatPhyRxCarrier::GetNodeInfo(), ns3::SatPhyRxCarrier::GetOwnAddress(), ns3::SatPhyRxCarrier::GetSatId(), ns3::SatUplinkInfoTag::GetSatId(), ns3::SatUplinkInfoTag::GetSinr(), ns3::SatMacTag::GetSourceAddress(), ns3::SatPhyRxCarrier::GetWorstSinr(), ns3::SatPhyRxCarrier::rxParams_s::interferenceEvent, ns3::SatPhyRxCarrier::IsCompositeSinrOutputTraceEnabled(), ns3::SatUtils::LinearToDb(), ns3::SatPhyRxCarrier::m_additionalInterferenceCallback, ns3::SatPhyRxCarrier::m_cnoCallback, ns3::SatPhyRxCarrier::m_daRxCarrierIdTrace, ns3::SatPhyRxCarrier::m_daRxTrace, ns3::SatPhyRxCarrier::m_linkBudgetTrace, ns3::SatPhyRxCarrier::m_linkSinrTrace, m_randomAccessBitsInFrame, ns3::SatPhyRxCarrier::m_rxAciIfPowerW, ns3::SatPhyRxCarrier::m_rxBandwidthHz, ns3::SatPhyRxCarrier::m_rxCallback, ns3::SatPhyRxCarrier::m_rxExtNoisePowerW, ns3::SatPhyRxCarrier::m_rxNoisePowerW, ns3::SatPhyRxCarrier::m_sinrTrace, m_slottedAlohaRxCollisionTrace, m_slottedAlohaRxErrorTrace, ns3::SatEnums::NT_GW, ns3::SatEnums::NT_UT, ns3::SatEnums::PACKET_TYPE_CRDSA, ns3::SatEnums::PACKET_TYPE_SLOTTED_ALOHA, ProcessSlottedAlohaCollisions(), ns3::SatEnums::REGENERATION_LINK, ns3::SatEnums::REGENERATION_NETWORK, ns3::SatEnums::REGENERATION_PHY, ns3::SatEnums::RETURN_FEEDER_CH, ns3::SatEnums::RETURN_USER_CH, ns3::SatPhyRxCarrier::rxParams_s::rxParams, ns3::SatUplinkInfoTag::SetSinr(), ns3::SatPhyRxCarrier::rxParams_s::sourceAddress, and ns3::SatEnums::TRANSPARENT.
Referenced by EndRxData(), and ns3::SatPhyRxCarrierPerFrame::ReceiveSlot().
SaveMeasuredRandomAccessLoad()
void ns3::SatPhyRxCarrierPerSlot::SaveMeasuredRandomAccessLoad (double measuredRandomAccessLoad) protected
Function for saving the measured random access load.
Parameters
measuredRandomAccessLoad Measured random access load
Definition at line 528 of file satellite-phy-rx-carrier-per-slot.cc.
References m_randomAccessAverageNormalizedOfferedLoadMeasurementWindowSize, and m_randomAccessDynamicLoadControlNormalizedOfferedLoad.
Referenced by ns3::SatPhyRxCarrierPerFrame::MeasureRandomAccessLoad(), and ns3::SatPhyRxCarrierPerWindow::MeasureRandomAccessLoad().
SetRandomAccessAllocationChannelId()
void ns3::SatPhyRxCarrierPerSlot::SetRandomAccessAllocationChannelId (uint8_t randomAccessAllocationChannelId) inline
Function for setting the random access allocation channel ID.
Parameters
randomAccessAllocationChannelId
Definition at line 83 of file satellite-phy-rx-carrier-per-slot.h.
References m_randomAccessAllocationChannelId.
Member Data Documentation
m_disableErrorHighTransmissionTime
bool ns3::SatPhyRxCarrierPerSlot::m_disableErrorHighTransmissionTime private
Definition at line 220 of file satellite-phy-rx-carrier-per-slot.h.
Referenced by CreateInterference(), and GetTypeId().
m_enableRandomAccessDynamicLoadControl
bool ns3::SatPhyRxCarrierPerSlot::m_enableRandomAccessDynamicLoadControl private
Definition at line 215 of file satellite-phy-rx-carrier-per-slot.h.
Referenced by SatPhyRxCarrierPerSlot(), and IsRandomAccessDynamicLoadControlEnabled().
m_randomAccessAllocationChannelId
uint8_t ns3::SatPhyRxCarrierPerSlot::m_randomAccessAllocationChannelId private
PRIVATE MEMBER VARIABLES.
Definition at line 206 of file satellite-phy-rx-carrier-per-slot.h.
Referenced by GetRandomAccessAllocationChannelId(), and SetRandomAccessAllocationChannelId().
m_randomAccessAverageNormalizedOfferedLoadMeasurementWindowSize
uint32_t ns3::SatPhyRxCarrierPerSlot::m_randomAccessAverageNormalizedOfferedLoadMeasurementWindowSize private
Definition at line 212 of file satellite-phy-rx-carrier-per-slot.h.
Referenced by SatPhyRxCarrierPerSlot(), and SaveMeasuredRandomAccessLoad().
m_randomAccessBitsInFrame
uint32_t ns3::SatPhyRxCarrierPerSlot::m_randomAccessBitsInFrame protected
The number of random access bits in current frame.
Protected so that child classes are able to alter this.
Definition at line 164 of file satellite-phy-rx-carrier-per-slot.h.
Referenced by ns3::SatPhyRxCarrierPerFrame::CalculateNormalizedOfferedRandomAccessLoad(), ReceiveSlot(), and ns3::SatPhyRxCarrierPerFrame::UpdateRandomAccessLoad().
m_randomAccessCollisionModel
SatPhyRxCarrierConf::RandomAccessCollisionModel ns3::SatPhyRxCarrierPerSlot::m_randomAccessCollisionModel private
Definition at line 208 of file satellite-phy-rx-carrier-per-slot.h.
Referenced by SatPhyRxCarrierPerSlot(), GetRandomAccessCollisionModel(), and ProcessSlottedAlohaCollisions().
m_randomAccessConstantErrorRate
double ns3::SatPhyRxCarrierPerSlot::m_randomAccessConstantErrorRate private
Definition at line 209 of file satellite-phy-rx-carrier-per-slot.h.
Referenced by SatPhyRxCarrierPerSlot(), and ProcessSlottedAlohaCollisions().
m_randomAccessDynamicLoadControlNormalizedOfferedLoad
std::deque<double> ns3::SatPhyRxCarrierPerSlot::m_randomAccessDynamicLoadControlNormalizedOfferedLoad private
Definition at line 217 of file satellite-phy-rx-carrier-per-slot.h.
Referenced by CalculateAverageNormalizedOfferedRandomAccessLoad(), DoDispose(), and SaveMeasuredRandomAccessLoad().
m_slottedAlohaRxCollisionTrace
TracedCallback<uint32_t, const Address&, bool> ns3::SatPhyRxCarrierPerSlot::m_slottedAlohaRxCollisionTrace protected
SlottedAlohaRxCollision trace source.
Fired when a packet burst is received through Random Access Slotted ALOHA.
Contains the following information:
number of upper layer packets in the received packet burst;
the MAC48 address of the sender; and
whether a collision has occurred.
Definition at line 177 of file satellite-phy-rx-carrier-per-slot.h.
Referenced by GetTypeId(), and ReceiveSlot().
m_slottedAlohaRxErrorTrace
TracedCallback<uint32_t, const Address&, bool> ns3::SatPhyRxCarrierPerSlot::m_slottedAlohaRxErrorTrace protected
SlottedAlohaRxError trace source.
Fired when a packet burst is received through Random Access Slotted ALOHA.
Contains the following information:
number of upper layer packets in the received packet burst;
the MAC48 address of the sender; and
whether a PHY error has occurred.
Definition at line 189 of file satellite-phy-rx-carrier-per-slot.h.
Referenced by GetTypeId(), and ReceiveSlot().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-phy-rx-carrier-per-slot.h
/builds/sns3/satellite/satellite/model/satellite-phy-rx-carrier-per-slot.cc