SNS3
ns3::SatLowerLayerServiceDaEntry Class Reference
The SatLowerLayerService class holds information of a satellite lower layer service DA entry.
#include "satellite-lower-layer-service.h"
Public Member Functions
SatLowerLayerServiceDaEntry ()
~SatLowerLayerServiceDaEntry ()
Destructor for SatLowerLayerServiceDaEntry.
Private Member Functions
bool GetConstantAssignmentProvided () const
Get state, if constant assignment is provided.
uint16_t GetConstantServiceRateInKbps () const
Get constant service rate.
Ptr< RandomVariableStream > GetConstantServiceRateStream () const
Get constant service rate stream.
uint16_t GetMaximumBacklogInKbytes () const
Get maximum backlog size.
uint16_t GetMaximumServiceRateInKbps () const
Get maximum service rate.
uint16_t GetMinimumServiceRateInKbps () const
Get minimum service rate.
bool GetRbdcAllowed () const
Get state, if RBDC is allowed.
bool GetVolumeAllowed () const
Get state, if volume is allowed.
void SetConstantAssignmentProvided (bool constAssignmentProvided)
Set state, if constant assignment is provided.
void SetConstantServiceRateStream (Ptr< RandomVariableStream > constantServiceRateStream)
Set constant service rate stream.
void SetMaximumBacklogInKbytes (uint16_t maximumBacklogInKbytes)
Set maximum backlog size.
void SetMaximumServiceRateInKbps (uint16_t maximumServiceRateKbps)
Set maximum service rate.
void SetMinimumServiceRateInKbps (uint16_t minimumServiceRateKbps)
Set minimum service rate.
void SetRbdcAllowed (bool bdcAllowed)
Set state, if RBDC is allowed.
void SetVolumeAllowed (bool volumeAllowed)
Set state, if volume is allowed.
Private Attributes
bool m_constantAssignmentProvided
Ptr< RandomVariableStream > m_constantServiceRateStream
uint16_t m_maximumBacklogInKbytes
uint16_t m_maximumServiceRateKbps
uint16_t m_minimumServiceRateKbps
bool m_rbdcAllowed
bool m_volumeAllowed
Friends
class SatLowerLayerServiceConf
Detailed Description
The SatLowerLayerService class holds information of a satellite lower layer service DA entry.
This class is only used by SatLowerLayerServiceConf class.
Definition at line 43 of file satellite-lower-layer-service.h.
Constructor & Destructor Documentation
SatLowerLayerServiceDaEntry()
ns3::SatLowerLayerServiceDaEntry::SatLowerLayerServiceDaEntry ()
Definition at line 41 of file satellite-lower-layer-service.cc.
~SatLowerLayerServiceDaEntry()
ns3::SatLowerLayerServiceDaEntry::~SatLowerLayerServiceDaEntry ()
Destructor for SatLowerLayerServiceDaEntry.
Definition at line 53 of file satellite-lower-layer-service.cc.
Member Function Documentation
GetConstantAssignmentProvided()
bool ns3::SatLowerLayerServiceDaEntry::GetConstantAssignmentProvided () const inline private
Get state, if constant assignment is provided.
Returns
Is constant assignment provided [true or false]
Definition at line 70 of file satellite-lower-layer-service.h.
References m_constantAssignmentProvided.
Referenced by ns3::SatLowerLayerServiceConf::GetDaConstantAssignmentProvided().
GetConstantServiceRateInKbps()
uint16_t ns3::SatLowerLayerServiceDaEntry::GetConstantServiceRateInKbps () const inline private
Get constant service rate.
Returns
Constant service rate [KBps]
Definition at line 130 of file satellite-lower-layer-service.h.
References m_constantServiceRateStream.
Referenced by ns3::SatLowerLayerServiceConf::GetDaConstantServiceRateInKbps().
GetConstantServiceRateStream()
Ptr<RandomVariableStream> ns3::SatLowerLayerServiceDaEntry::GetConstantServiceRateStream () const inline private
Get constant service rate stream.
Returns
Constant service rate stream.
Definition at line 140 of file satellite-lower-layer-service.h.
References m_constantServiceRateStream.
Referenced by ns3::SatLowerLayerServiceConf::GetDaConstantServiceRateStream().
GetMaximumBacklogInKbytes()
uint16_t ns3::SatLowerLayerServiceDaEntry::GetMaximumBacklogInKbytes () const inline private
Get maximum backlog size.
Returns
Maximum backlog size [KBytes]
Definition at line 200 of file satellite-lower-layer-service.h.
References m_maximumBacklogInKbytes.
Referenced by ns3::SatLowerLayerServiceConf::GetDaMaximumBacklogInKbytes().
GetMaximumServiceRateInKbps()
uint16_t ns3::SatLowerLayerServiceDaEntry::GetMaximumServiceRateInKbps () const inline private
Get maximum service rate.
Returns
Maximum service rate [KBps]
Definition at line 160 of file satellite-lower-layer-service.h.
References m_maximumServiceRateKbps.
Referenced by ns3::SatLowerLayerServiceConf::GetDaMaximumServiceRateInKbps().
GetMinimumServiceRateInKbps()
uint16_t ns3::SatLowerLayerServiceDaEntry::GetMinimumServiceRateInKbps () const inline private
Get minimum service rate.
Returns
Minimum service rate [KBps]
Definition at line 180 of file satellite-lower-layer-service.h.
References m_minimumServiceRateKbps.
Referenced by ns3::SatLowerLayerServiceConf::GetDaMinimumServiceRateInKbps().
GetRbdcAllowed()
bool ns3::SatLowerLayerServiceDaEntry::GetRbdcAllowed () const inline private
Get state, if RBDC is allowed.
Returns
Is RBDC allowed [true or false]
Definition at line 90 of file satellite-lower-layer-service.h.
References m_rbdcAllowed.
Referenced by ns3::SatLowerLayerServiceConf::GetDaRbdcAllowed().
GetVolumeAllowed()
bool ns3::SatLowerLayerServiceDaEntry::GetVolumeAllowed () const inline private
Get state, if volume is allowed.
Returns
Is volume allowed [true or false]
Definition at line 110 of file satellite-lower-layer-service.h.
References m_volumeAllowed.
Referenced by ns3::SatLowerLayerServiceConf::GetDaVolumeAllowed().
SetConstantAssignmentProvided()
void ns3::SatLowerLayerServiceDaEntry::SetConstantAssignmentProvided (bool constAssignmentProvided) inline private
Set state, if constant assignment is provided.
Parameters
constAssignmentProvided Constant assignment provided state [true or false]
Definition at line 80 of file satellite-lower-layer-service.h.
References m_constantAssignmentProvided.
Referenced by ns3::SatLowerLayerServiceConf::SetDaConstantAssignmentProvided().
SetConstantServiceRateStream()
void ns3::SatLowerLayerServiceDaEntry::SetConstantServiceRateStream (Ptr< RandomVariableStream > constantServiceRateStream) inline private
Set constant service rate stream.
Parameters
constantServiceRateKbps Constant service rate [KBps]
Definition at line 150 of file satellite-lower-layer-service.h.
References m_constantServiceRateStream.
Referenced by ns3::SatLowerLayerServiceConf::SetDaConstantServiceRateStream().
SetMaximumBacklogInKbytes()
void ns3::SatLowerLayerServiceDaEntry::SetMaximumBacklogInKbytes (uint16_t maximumBacklogInKbytes) inline private
Set maximum backlog size.
Parameters
maximumBacklogInBytes Maximum backlog size [KBytes]
Definition at line 210 of file satellite-lower-layer-service.h.
References m_maximumBacklogInKbytes.
Referenced by ns3::SatLowerLayerServiceConf::SetDaMaximumBacklogInKbytes().
SetMaximumServiceRateInKbps()
void ns3::SatLowerLayerServiceDaEntry::SetMaximumServiceRateInKbps (uint16_t maximumServiceRateKbps) inline private
Set maximum service rate.
Parameters
maximumServiceRateKbps Maximum service rate [KBps]
Definition at line 170 of file satellite-lower-layer-service.h.
References m_maximumServiceRateKbps.
Referenced by ns3::SatLowerLayerServiceConf::SetDaMaximumServiceRateInKbps().
SetMinimumServiceRateInKbps()
void ns3::SatLowerLayerServiceDaEntry::SetMinimumServiceRateInKbps (uint16_t minimumServiceRateKbps) inline private
Set minimum service rate.
Parameters
minimumServiceRateKbps Minimum service rate [KBps]
Definition at line 190 of file satellite-lower-layer-service.h.
References m_minimumServiceRateKbps.
Referenced by ns3::SatLowerLayerServiceConf::SetDaMinimumServiceRateInKbps().
SetRbdcAllowed()
void ns3::SatLowerLayerServiceDaEntry::SetRbdcAllowed (bool bdcAllowed) inline private
Set state, if RBDC is allowed.
Parameters
bdcAllowed RBDC allowed state [true or false]
Definition at line 100 of file satellite-lower-layer-service.h.
References m_rbdcAllowed.
Referenced by ns3::SatLowerLayerServiceConf::SetDaRbdcAllowed().
SetVolumeAllowed()
void ns3::SatLowerLayerServiceDaEntry::SetVolumeAllowed (bool volumeAllowed) inline private
Set state, if volume is allowed.
Parameters
volumeAllowed Volume allowed state [true or false]
Definition at line 120 of file satellite-lower-layer-service.h.
References m_volumeAllowed.
Referenced by ns3::SatLowerLayerServiceConf::SetDaVolumeAllowed().
Friends And Related Function Documentation
SatLowerLayerServiceConf
friend class SatLowerLayerServiceConf friend
Definition at line 46 of file satellite-lower-layer-service.h.
Member Data Documentation
m_constantAssignmentProvided
bool ns3::SatLowerLayerServiceDaEntry::m_constantAssignmentProvided private
Definition at line 57 of file satellite-lower-layer-service.h.
Referenced by GetConstantAssignmentProvided(), and SetConstantAssignmentProvided().
m_constantServiceRateStream
Ptr<RandomVariableStream> ns3::SatLowerLayerServiceDaEntry::m_constantServiceRateStream private
Definition at line 60 of file satellite-lower-layer-service.h.
Referenced by GetConstantServiceRateInKbps(), GetConstantServiceRateStream(), and SetConstantServiceRateStream().
m_maximumBacklogInKbytes
uint16_t ns3::SatLowerLayerServiceDaEntry::m_maximumBacklogInKbytes private
Definition at line 63 of file satellite-lower-layer-service.h.
Referenced by GetMaximumBacklogInKbytes(), and SetMaximumBacklogInKbytes().
m_maximumServiceRateKbps
uint16_t ns3::SatLowerLayerServiceDaEntry::m_maximumServiceRateKbps private
Definition at line 61 of file satellite-lower-layer-service.h.
Referenced by GetMaximumServiceRateInKbps(), and SetMaximumServiceRateInKbps().
m_minimumServiceRateKbps
uint16_t ns3::SatLowerLayerServiceDaEntry::m_minimumServiceRateKbps private
Definition at line 62 of file satellite-lower-layer-service.h.
Referenced by GetMinimumServiceRateInKbps(), and SetMinimumServiceRateInKbps().
m_rbdcAllowed
bool ns3::SatLowerLayerServiceDaEntry::m_rbdcAllowed private
Definition at line 58 of file satellite-lower-layer-service.h.
Referenced by GetRbdcAllowed(), and SetRbdcAllowed().
m_volumeAllowed
bool ns3::SatLowerLayerServiceDaEntry::m_volumeAllowed private
Definition at line 59 of file satellite-lower-layer-service.h.
Referenced by GetVolumeAllowed(), and SetVolumeAllowed().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-lower-layer-service.h
/builds/sns3/satellite/satellite/model/satellite-lower-layer-service.cc