SNS3
SatPerPacketInterferenceTestCase Class Reference
Test case to unit test satellite per packet interference model.
Public Member Functions
SatPerPacketInterferenceTestCase ()
virtual ~SatPerPacketInterferenceTestCase ()
void AddInterference (Time duration, double power, Address rxAddress)
void Receive (uint32_t rxIndex)
void StartReceiver (Time duration, double power, Address rxAddress)
Private Member Functions
virtual void DoRun (void)
Private Attributes
double finalPower [4]
Ptr< SatPerPacketInterference > m_interference
Ptr< SatInterference::InterferenceChangeEvent > m_rxEvent [4]
uint32_t m_rxIndex
Detailed Description
Test case to unit test satellite per packet interference model.
This case tests that SatPerPacketInterference object can be created successfully and interference value calculated correctly.
Create SatPerPacketInterference object.
Create events, add them to SatPerPacketInterference about them.
Notify SatPerPacketInterference about the event wanted to calculate.
Get interference with calculate method with the event to calculate.
Expected result: Value should be correctly calculated. According to interfering events added.
Definition at line 142 of file satellite-interference-test.cc.
Constructor & Destructor Documentation
SatPerPacketInterferenceTestCase()
SatPerPacketInterferenceTestCase::SatPerPacketInterferenceTestCase ()
Definition at line 165 of file satellite-interference-test.cc.
References finalPower, m_interference, m_rxEvent, and m_rxIndex.
~SatPerPacketInterferenceTestCase()
SatPerPacketInterferenceTestCase::~SatPerPacketInterferenceTestCase () virtual
Definition at line 178 of file satellite-interference-test.cc.
Member Function Documentation
AddInterference()
void SatPerPacketInterferenceTestCase::AddInterference (Time duration, double power, Address rxAddress)
Definition at line 183 of file satellite-interference-test.cc.
References m_interference.
Referenced by DoRun().
DoRun()
void SatPerPacketInterferenceTestCase::DoRun (void) private virtual
Definition at line 219 of file satellite-interference-test.cc.
References AddInterference(), finalPower, and StartReceiver().
Receive()
void SatPerPacketInterferenceTestCase::Receive (uint32_t rxIndex)
Definition at line 208 of file satellite-interference-test.cc.
References finalPower, m_interference, and m_rxEvent.
Referenced by StartReceiver().
StartReceiver()
void SatPerPacketInterferenceTestCase::StartReceiver (Time duration, double power, Address rxAddress)
Definition at line 190 of file satellite-interference-test.cc.
References m_interference, m_rxEvent, m_rxIndex, and Receive().
Referenced by DoRun().
Member Data Documentation
finalPower
double SatPerPacketInterferenceTestCase::finalPower[4] private
Definition at line 162 of file satellite-interference-test.cc.
Referenced by SatPerPacketInterferenceTestCase(), DoRun(), and Receive().
m_interference
Ptr<SatPerPacketInterference> SatPerPacketInterferenceTestCase::m_interference private
Definition at line 159 of file satellite-interference-test.cc.
Referenced by SatPerPacketInterferenceTestCase(), AddInterference(), Receive(), and StartReceiver().
m_rxEvent
Ptr<SatInterference::InterferenceChangeEvent> SatPerPacketInterferenceTestCase::m_rxEvent[4] private
Definition at line 160 of file satellite-interference-test.cc.
Referenced by SatPerPacketInterferenceTestCase(), Receive(), and StartReceiver().
m_rxIndex
uint32_t SatPerPacketInterferenceTestCase::m_rxIndex private
Definition at line 161 of file satellite-interference-test.cc.
Referenced by SatPerPacketInterferenceTestCase(), and StartReceiver().
The documentation for this class was generated from the following file:
/builds/sns3/satellite/satellite/test/satellite-interference-test.cc