SNS3
ns3::SatPhyLinkTimeTag Class Reference
Time tag used to identify the time when packet is enqueued at PHY on current link level.
#include "satellite-time-tag.h"
Public Member Functions
SatPhyLinkTimeTag ()
Default constructor.
SatPhyLinkTimeTag (Time senderTimestamp)
Constructor with initialization parameters.
virtual void Deserialize (TagBuffer i)
Deserializes information from buffer to this instance of SatPhyLinkTimeTag.
virtual TypeId GetInstanceTypeId (void) const
Get the type ID of instance.
Time GetSenderLinkTimestamp (void) const
Get sender time stamp of this tag.
virtual uint32_t GetSerializedSize () const
Get serialized size of SatPhyLinkTimeTag.
virtual void Print (std::ostream &os) const
Print time stamp of this instance of SatPhyLinkTimeTag.
virtual void Serialize (TagBuffer i) const
Serializes information to buffer from this instance of SatPhyLinkTimeTag.
void SetSenderLinkTimestamp (Time senderLinkTimestamp)
Set sender time stamp of this tag.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Time m_senderLinkTimestamp
Detailed Description
Time tag used to identify the time when packet is enqueued at PHY on current link level.
Definition at line 183 of file satellite-time-tag.h.
Constructor & Destructor Documentation
SatPhyLinkTimeTag() [1/2]
ns3::SatPhyLinkTimeTag::SatPhyLinkTimeTag ()
Default constructor.
Definition at line 173 of file satellite-time-tag.cc.
SatPhyLinkTimeTag() [2/2]
ns3::SatPhyLinkTimeTag::SatPhyLinkTimeTag (Time senderTimestamp)
Constructor with initialization parameters.
Parameters
senderTimestamp
Definition at line 179 of file satellite-time-tag.cc.
Member Function Documentation
Deserialize()
void ns3::SatPhyLinkTimeTag::Deserialize (TagBuffer i) virtual
Deserializes information from buffer to this instance of SatPhyLinkTimeTag.
Parameters
i Buffer from which the information is deserialized
Definition at line 213 of file satellite-time-tag.cc.
References m_senderLinkTimestamp.
GetInstanceTypeId()
TypeId ns3::SatPhyLinkTimeTag::GetInstanceTypeId (void) const virtual
Get the type ID of instance.
Returns
the object TypeId
Definition at line 194 of file satellite-time-tag.cc.
References GetTypeId().
GetSenderLinkTimestamp()
Time ns3::SatPhyLinkTimeTag::GetSenderLinkTimestamp (void) const
Get sender time stamp of this tag.
Returns
Sender timestamp
Definition at line 227 of file satellite-time-tag.cc.
References m_senderLinkTimestamp.
Referenced by ns3::SatGeoFeederPhy::RxTraces(), ns3::SatGeoUserPhy::RxTraces(), and ns3::SatPhy::RxTraces().
GetSerializedSize()
uint32_t ns3::SatPhyLinkTimeTag::GetSerializedSize (void) const virtual
Get serialized size of SatPhyLinkTimeTag.
Returns
Serialized size in bytes
Definition at line 200 of file satellite-time-tag.cc.
GetTypeId()
TypeId ns3::SatPhyLinkTimeTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 186 of file satellite-time-tag.cc.
Referenced by GetInstanceTypeId().
Print()
void ns3::SatPhyLinkTimeTag::Print (std::ostream & os) const virtual
Print time stamp of this instance of SatPhyLinkTimeTag.
Parameters
&os Output stream to which tag timestamp is printed.
Definition at line 221 of file satellite-time-tag.cc.
References m_senderLinkTimestamp.
Serialize()
void ns3::SatPhyLinkTimeTag::Serialize (TagBuffer i) const virtual
Serializes information to buffer from this instance of SatPhyLinkTimeTag.
Parameters
i Buffer in which the information is serialized
Definition at line 206 of file satellite-time-tag.cc.
References m_senderLinkTimestamp.
SetSenderLinkTimestamp()
void ns3::SatPhyLinkTimeTag::SetSenderLinkTimestamp (Time senderLinkTimestamp)
Set sender time stamp of this tag.
Parameters
senderTimestamp Sender time stamp
Definition at line 233 of file satellite-time-tag.cc.
References m_senderLinkTimestamp.
Member Data Documentation
m_senderLinkTimestamp
Time ns3::SatPhyLinkTimeTag::m_senderLinkTimestamp private
Definition at line 246 of file satellite-time-tag.h.
Referenced by Deserialize(), GetSenderLinkTimestamp(), Print(), Serialize(), and SetSenderLinkTimestamp().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-time-tag.h
/builds/sns3/satellite/satellite/model/satellite-time-tag.cc