SNS3
SatMobilityObserverTestCase Class Reference
Test case to unit test Satellite Mobility Observer.
Public Member Functions
SatMobilityObserverTestCase ()
virtual ~SatMobilityObserverTestCase ()
Private Member Functions
virtual void DoRun (void)
Detailed Description
Test case to unit test Satellite Mobility Observer.
This case tests that SatMobilityObserver object can be created successfully and it calculates correctly.
Create SatMobilityObserver object with geo mobility and own mobility.
Set position of Geo satellite mobility.
Set position of own mobility.
Set propagation delay and another mobility to observer.
Get timing advance from observer.
Set position of own mobility.
Get elevation angle from observer.
Repeat steps 6 and 7 several times.
Set Geo satellite using reference satellite and repeat steps 6 and 7 several times.
Expected result: Timing advance and elevation angle values got are correct.
Notes: At least corner points, valid values and out of range (NAN) elevation angle values is needed to test. When reference satellite is used for example MatLab is useful to get reference values for elevation angles.
Definition at line 295 of file satellite-mobility-observer-test.cc.
Constructor & Destructor Documentation
SatMobilityObserverTestCase()
SatMobilityObserverTestCase::SatMobilityObserverTestCase ()
Definition at line 305 of file satellite-mobility-observer-test.cc.
~SatMobilityObserverTestCase()
SatMobilityObserverTestCase::~SatMobilityObserverTestCase () virtual
Definition at line 310 of file satellite-mobility-observer-test.cc.
Member Function Documentation
DoRun()
void SatMobilityObserverTestCase::DoRun (void) private virtual
Definition at line 315 of file satellite-mobility-observer-test.cc.
References g_firstLatValue, g_firstLonValue, g_latitudeCount, g_latStep, g_longitudeCount, g_lonStep, g_refElAngles, ns3::GeoCoordinate::SetAltitude(), ns3::GeoCoordinate::SetLatitude(), and ns3::GeoCoordinate::SetLongitude().
The documentation for this class was generated from the following file:
/builds/sns3/satellite/satellite/test/satellite-mobility-observer-test.cc