SNS3
ns3::SatArqHeader Class Reference
ARQ header implementation contains the sequence number related to the packet in question.
#include "satellite-arq-header.h"
Public Member Functions
SatArqHeader ()
Constructor.
~SatArqHeader ()
Destructor for SatArqHeader.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserializes information from buffer to this instance of SatArqHeader.
virtual TypeId GetInstanceTypeId (void) const
Get the type ID of instance.
uint8_t GetSeqNo () const
Get sequence number.
virtual uint32_t GetSerializedSize (void) const
Get serialized size of SatArqHeader.
virtual void Print (std::ostream &os) const
Print time stamp of this instance of SatArqHeader.
virtual void Serialize (Buffer::Iterator start) const
Serializes information to buffer from this instance of SatArqHeader.
void SetSeqNo (uint8_t seqNo)
Set sequence number.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_seqNo
Sequence number represented by one Byte.
Detailed Description
ARQ header implementation contains the sequence number related to the packet in question.
Sequence number is identified with one byte, thus it may range between 0 - 255.
Definition at line 39 of file satellite-arq-header.h.
Constructor & Destructor Documentation
SatArqHeader()
ns3::SatArqHeader::SatArqHeader ()
Constructor.
Definition at line 32 of file satellite-arq-header.cc.
~SatArqHeader()
ns3::SatArqHeader::~SatArqHeader ()
Destructor for SatArqHeader.
Definition at line 37 of file satellite-arq-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::SatArqHeader::Deserialize (Buffer::Iterator start) virtual
Deserializes information from buffer to this instance of SatArqHeader.
Parameters
start Buffer from which the information is deserialized
Returns
Serialized size of the buffer
Definition at line 65 of file satellite-arq-header.cc.
References GetSerializedSize(), and m_seqNo.
GetInstanceTypeId()
TypeId ns3::SatArqHeader::GetInstanceTypeId (void) const virtual
Get the type ID of instance.
Returns
the object TypeId
Definition at line 81 of file satellite-arq-header.cc.
References GetTypeId().
GetSeqNo()
uint8_t ns3::SatArqHeader::GetSeqNo () const
Get sequence number.
Returns
Sequence number
Definition at line 87 of file satellite-arq-header.cc.
References m_seqNo.
Referenced by ns3::SatGenericStreamEncapsulatorArq::ReceivePdu(), and ns3::SatReturnLinkEncapsulatorArq::ReceivePdu().
GetSerializedSize()
uint32_t ns3::SatArqHeader::GetSerializedSize (void) const virtual
Get serialized size of SatArqHeader.
Returns
Serialized size in bytes
Definition at line 50 of file satellite-arq-header.cc.
Referenced by Deserialize().
GetTypeId()
TypeId ns3::SatArqHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 42 of file satellite-arq-header.cc.
Referenced by GetInstanceTypeId().
Print()
void ns3::SatArqHeader::Print (std::ostream & os) const virtual
Print time stamp of this instance of SatArqHeader.
Parameters
&os Output stream to which tag timestamp is printed.
Definition at line 75 of file satellite-arq-header.cc.
References m_seqNo.
Serialize()
void ns3::SatArqHeader::Serialize (Buffer::Iterator start) const virtual
Serializes information to buffer from this instance of SatArqHeader.
Parameters
start Buffer in which the information is serialized
Definition at line 57 of file satellite-arq-header.cc.
References m_seqNo.
SetSeqNo()
void ns3::SatArqHeader::SetSeqNo (uint8_t seqNo)
Set sequence number.
Parameters
seqNo Sequence number
Definition at line 94 of file satellite-arq-header.cc.
References m_seqNo.
Referenced by ns3::SatGenericStreamEncapsulatorArq::NotifyTxOpportunity(), and ns3::SatReturnLinkEncapsulatorArq::NotifyTxOpportunity().
Member Data Documentation
m_seqNo
uint8_t ns3::SatArqHeader::m_seqNo private
Sequence number represented by one Byte.
Definition at line 105 of file satellite-arq-header.h.
Referenced by Deserialize(), GetSeqNo(), Print(), Serialize(), and SetSeqNo().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-arq-header.h
/builds/sns3/satellite/satellite/model/satellite-arq-header.cc