SNS3
ns3::SatFlowIdTag Class Reference
SatFlowIdTag implements a tag which carries the flow identifier of a packet.
#include "satellite-mac-tag.h"
Public Member Functions
SatFlowIdTag ()
Default constructor.
~SatFlowIdTag ()
Destructor for SatFlowIdTag.
virtual void Deserialize (TagBuffer i)
Deserializes information from buffer to this instance of SatFlowIdTag.
uint8_t GetFlowId () const
Get flow identifier.
virtual TypeId GetInstanceTypeId (void) const
Get the type ID of instance.
virtual uint32_t GetSerializedSize (void) const
Get serialized size of SatFlowIdTag.
virtual void Print (std::ostream &os) const
Print time stamp of this instance of SatFlowIdTag.
virtual void Serialize (TagBuffer i) const
Serializes information to buffer from this instance of SatFlowIdTag.
void SetFlowId (uint8_t flowId)
Set flow id.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_flowId
Detailed Description
SatFlowIdTag implements a tag which carries the flow identifier of a packet.
Definition at line 209 of file satellite-mac-tag.h.
Constructor & Destructor Documentation
SatFlowIdTag()
ns3::SatFlowIdTag::SatFlowIdTag ()
Default constructor.
Definition at line 230 of file satellite-mac-tag.cc.
~SatFlowIdTag()
ns3::SatFlowIdTag::~SatFlowIdTag ()
Destructor for SatFlowIdTag.
Definition at line 236 of file satellite-mac-tag.cc.
Member Function Documentation
Deserialize()
void ns3::SatFlowIdTag::Deserialize (TagBuffer i) virtual
Deserializes information from buffer to this instance of SatFlowIdTag.
Parameters
i Buffer from which the information is deserialized
Definition at line 287 of file satellite-mac-tag.cc.
References m_flowId.
GetFlowId()
uint8_t ns3::SatFlowIdTag::GetFlowId () const
Get flow identifier.
Returns
Flow identifier
Definition at line 264 of file satellite-mac-tag.cc.
References m_flowId.
Referenced by ns3::SatLlc::Receive().
GetInstanceTypeId()
TypeId ns3::SatFlowIdTag::GetInstanceTypeId (void) const virtual
Get the type ID of instance.
Returns
the object TypeId
Definition at line 249 of file satellite-mac-tag.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::SatFlowIdTag::GetSerializedSize (void) const virtual
Get serialized size of SatFlowIdTag.
Returns
Serialized size in bytes
Definition at line 271 of file satellite-mac-tag.cc.
GetTypeId()
TypeId ns3::SatFlowIdTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 242 of file satellite-mac-tag.cc.
Referenced by GetInstanceTypeId().
Print()
void ns3::SatFlowIdTag::Print (std::ostream & os) const virtual
Print time stamp of this instance of SatFlowIdTag.
Parameters
&os Output stream to which tag timestamp is printed.
Definition at line 295 of file satellite-mac-tag.cc.
References m_flowId.
Serialize()
void ns3::SatFlowIdTag::Serialize (TagBuffer i) const virtual
Serializes information to buffer from this instance of SatFlowIdTag.
Parameters
i Buffer in which the information is serialized
Definition at line 279 of file satellite-mac-tag.cc.
References m_flowId.
SetFlowId()
void ns3::SatFlowIdTag::SetFlowId (uint8_t flowId)
Set flow id.
Parameters
flowId Flow identifier
Definition at line 257 of file satellite-mac-tag.cc.
References m_flowId.
Referenced by ns3::SatBaseEncapsulator::EnquePdu(), ns3::SatGenericStreamEncapsulatorArq::NotifyTxOpportunity(), ns3::SatGenericStreamEncapsulator::NotifyTxOpportunity(), ns3::SatReturnLinkEncapsulatorArq::NotifyTxOpportunity(), and ns3::SatReturnLinkEncapsulator::NotifyTxOpportunity().
Member Data Documentation
m_flowId
uint8_t ns3::SatFlowIdTag::m_flowId private
Definition at line 271 of file satellite-mac-tag.h.
Referenced by Deserialize(), GetFlowId(), Print(), Serialize(), and SetFlowId().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-mac-tag.h
/builds/sns3/satellite/satellite/model/satellite-mac-tag.cc