SNS3
ns3::SatTracedMobilityModel Class Reference
Satellite mobility model for which the current position change based on values read from a file.
#include "satellite-traced-mobility-model.h"
Public Member Functions
SatTracedMobilityModel ()
Default constructor.
SatTracedMobilityModel (uint32_t satId, const std::string &filename, Ptr< SatAntennaGainPatternContainer > agp)
Constructor.
virtual ~SatTracedMobilityModel ()
Destructor for SatMobilityModel.
virtual void DoDispose ()
Dispose of this class instance.
uint32_t GetBestBeamId (void) const
Return the best beam ID based on the current position.
TypeId GetInstanceTypeId (void) const
Public Member Functions inherited from ns3::SatMobilityModel
SatMobilityModel ()
Default constructor.
virtual ~SatMobilityModel ()=0
Destructor for SatMobilityModel.
GeoCoordinate GetGeoPosition (void) const
TypeId GetInstanceTypeId (void) const
void NotifyGeoCourseChange (void) const
void SetGeoPosition (const GeoCoordinate &position)
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::SatMobilityModel
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual GeoCoordinate DoGetGeoPosition (void) const
virtual Vector DoGetVelocity (void) const
virtual void DoSetGeoPosition (const GeoCoordinate &position)
void UpdateGeoPositionFromFile (void)
Private Attributes
Ptr< SatAntennaGainPatternContainer > m_antennaGainPatterns
GeoCoordinate m_geoPosition
GeoCoordinate::ReferenceEllipsoid_t m_refEllipsoid
uint32_t m_satId
std::string m_traceFilename
Time m_updateInterval
Vector m_velocity
Additional Inherited Members
Public Types inherited from ns3::SatMobilityModel
typedef void(* CourseChangeCallback) (const Ptr< const SatMobilityModel > model)
Callback signature for SatCourseChange trace source.
Detailed Description
Satellite mobility model for which the current position change based on values read from a file.
Definition at line 38 of file satellite-traced-mobility-model.h.
Constructor & Destructor Documentation
SatTracedMobilityModel() [1/2]
ns3::SatTracedMobilityModel::SatTracedMobilityModel ()
Default constructor.
Unused.
Definition at line 77 of file satellite-traced-mobility-model.cc.
SatTracedMobilityModel() [2/2]
ns3::SatTracedMobilityModel::SatTracedMobilityModel (uint32_t satId, const std::string & filename, Ptr< SatAntennaGainPatternContainer > agp)
Constructor.
Definition at line 82 of file satellite-traced-mobility-model.cc.
References UpdateGeoPositionFromFile().
~SatTracedMobilityModel()
ns3::SatTracedMobilityModel::~SatTracedMobilityModel () virtual
Destructor for SatMobilityModel.
Definition at line 98 of file satellite-traced-mobility-model.cc.
Member Function Documentation
DoDispose()
void ns3::SatTracedMobilityModel::DoDispose (void) virtual
Dispose of this class instance.
Definition at line 70 of file satellite-traced-mobility-model.cc.
References m_antennaGainPatterns.
DoGetGeoPosition()
GeoCoordinate ns3::SatTracedMobilityModel::DoGetGeoPosition (void) const private virtual
Returns
the current position.
Implements ns3::SatMobilityModel.
Definition at line 104 of file satellite-traced-mobility-model.cc.
References m_geoPosition.
DoGetVelocity()
Vector ns3::SatTracedMobilityModel::DoGetVelocity (void) const private virtual
Returns
the current velocity.
Definition at line 128 of file satellite-traced-mobility-model.cc.
References m_velocity.
DoSetGeoPosition()
void ns3::SatTracedMobilityModel::DoSetGeoPosition (const GeoCoordinate & position) private virtual
Parameters
position the position to set.
Implements ns3::SatMobilityModel.
Definition at line 112 of file satellite-traced-mobility-model.cc.
References m_geoPosition, m_updateInterval, m_velocity, ns3::SatMobilityModel::NotifyGeoCourseChange(), and ns3::GeoCoordinate::ToVector().
Referenced by UpdateGeoPositionFromFile().
GetBestBeamId()
uint32_t ns3::SatTracedMobilityModel::GetBestBeamId (void) const
Return the best beam ID based on the current position.
Definition at line 149 of file satellite-traced-mobility-model.cc.
References m_antennaGainPatterns, m_geoPosition, and m_satId.
GetInstanceTypeId()
TypeId ns3::SatTracedMobilityModel::GetInstanceTypeId (void) const
Definition at line 64 of file satellite-traced-mobility-model.cc.
References GetTypeId().
GetTypeId()
TypeId ns3::SatTracedMobilityModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 38 of file satellite-traced-mobility-model.cc.
References ns3::GeoCoordinate::GRS80, m_refEllipsoid, m_updateInterval, ns3::GeoCoordinate::SPHERE, and ns3::GeoCoordinate::WGS84.
Referenced by GetInstanceTypeId().
UpdateGeoPositionFromFile()
void ns3::SatTracedMobilityModel::UpdateGeoPositionFromFile (void) private
Definition at line 136 of file satellite-traced-mobility-model.cc.
References DoSetGeoPosition(), m_refEllipsoid, m_traceFilename, and m_updateInterval.
Referenced by SatTracedMobilityModel().
Member Data Documentation
m_antennaGainPatterns
Ptr<SatAntennaGainPatternContainer> ns3::SatTracedMobilityModel::m_antennaGainPatterns private
Definition at line 99 of file satellite-traced-mobility-model.h.
Referenced by DoDispose(), and GetBestBeamId().
m_geoPosition
GeoCoordinate ns3::SatTracedMobilityModel::m_geoPosition private
Definition at line 97 of file satellite-traced-mobility-model.h.
Referenced by DoGetGeoPosition(), DoSetGeoPosition(), and GetBestBeamId().
m_refEllipsoid
GeoCoordinate::ReferenceEllipsoid_t ns3::SatTracedMobilityModel::m_refEllipsoid private
Definition at line 96 of file satellite-traced-mobility-model.h.
Referenced by GetTypeId(), and UpdateGeoPositionFromFile().
m_satId
uint32_t ns3::SatTracedMobilityModel::m_satId private
Definition at line 93 of file satellite-traced-mobility-model.h.
Referenced by GetBestBeamId().
m_traceFilename
std::string ns3::SatTracedMobilityModel::m_traceFilename private
Definition at line 94 of file satellite-traced-mobility-model.h.
Referenced by UpdateGeoPositionFromFile().
m_updateInterval
Time ns3::SatTracedMobilityModel::m_updateInterval private
Definition at line 95 of file satellite-traced-mobility-model.h.
Referenced by DoSetGeoPosition(), GetTypeId(), and UpdateGeoPositionFromFile().
m_velocity
Vector ns3::SatTracedMobilityModel::m_velocity private
Definition at line 98 of file satellite-traced-mobility-model.h.
Referenced by DoGetVelocity(), and DoSetGeoPosition().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-traced-mobility-model.h
/builds/sns3/satellite/satellite/model/satellite-traced-mobility-model.cc