SNS3
GeoCoordinateTestCase Class Reference
Test case to unit test that GeoCoordinate can be created with valid values.
Public Member Functions
GeoCoordinateTestCase ()
virtual ~GeoCoordinateTestCase ()
Private Member Functions
virtual void DoRun (void)
void Validate (GeoCoordinate &coord1, GeoCoordinate &coord2)
Detailed Description
Test case to unit test that GeoCoordinate can be created with valid values.
Definition at line 60 of file satellite-geo-coordinate-test.cc.
Constructor & Destructor Documentation
GeoCoordinateTestCase()
GeoCoordinateTestCase::GeoCoordinateTestCase ()
Definition at line 71 of file satellite-geo-coordinate-test.cc.
~GeoCoordinateTestCase()
GeoCoordinateTestCase::~GeoCoordinateTestCase () virtual
Definition at line 76 of file satellite-geo-coordinate-test.cc.
Member Function Documentation
DoRun()
void GeoCoordinateTestCase::DoRun (void) private virtual
Definition at line 81 of file satellite-geo-coordinate-test.cc.
References ns3::GeoCoordinate::ToVector(), and Validate().
Validate()
void GeoCoordinateTestCase::Validate (GeoCoordinate & coord1, GeoCoordinate & coord2) private
Definition at line 117 of file satellite-geo-coordinate-test.cc.
References ns3::GeoCoordinate::GetAltitude(), ns3::GeoCoordinate::GetLatitude(), and ns3::GeoCoordinate::GetLongitude().
Referenced by DoRun().
The documentation for this class was generated from the following file:
/builds/sns3/satellite/satellite/test/satellite-geo-coordinate-test.cc