SNS3
ns3::SatStatsFwdLinkSchedulerSymbolRateHelper Class Reference
Satellite Statistics
Helper for forward link scheduler symbol rate statistic.
#include "satellite-stats-fwd-link-scheduler-symbol-rate-helper.h"
Public Member Functions
SatStatsFwdLinkSchedulerSymbolRateHelper (Ptr< const SatHelper > satHelper)
virtual ~SatStatsFwdLinkSchedulerSymbolRateHelper ()
/ Destructor.
Callback< void, uint8_t, double > GetTraceSinkCallback () const
void InstallProbes ()
Set up several probes or other means of listeners and connect them to the collectors.
void SymbolRateCallback (uint8_t sliceId, double symbolRate)
Receive inputs from trace sources and forward them to the collector.
Public Member Functions inherited from ns3::SatStatsHelper
SatStatsHelper (Ptr< const SatHelper > satHelper)
Creates a new helper instance.
virtual ~SatStatsHelper ()
/ Destructor.
IdentifierType_t GetIdentifierType () const
std::string GetName () const
OutputType_t GetOutputType () const
Ptr< const SatHelper > GetSatHelper () const
void Install ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
bool IsInstalled () const
void SetIdentifierType (IdentifierType_t identifierType)
void SetName (std::string name)
void SetOutputType (OutputType_t outputType)
Static Public Member Functions
static TypeId GetTypeId ()
inherited from ObjectBase base class
Static Public Member Functions inherited from ns3::SatStatsHelper
static std::string GetIdentifierTypeName (IdentifierType_t identifierType)
static std::string GetOutputTypeName (OutputType_t outputType)
static TypeId GetTypeId ()
inherited from ObjectBase base class
Protected Member Functions
void DoInstall ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
Protected Member Functions inherited from ns3::SatStatsHelper
Ptr< DataCollectionObject > CreateAggregator (std::string aggregatorTypeId, std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue())
Create the aggregator according to the output type.
uint32_t CreateCollectorPerIdentifier (CollectorMap &collectorMap) const
Create one collector instance for each identifier in the simulation.
virtual std::string GetDistributionHeading (std::string dataLabel) const
uint32_t GetGwId (Ptr< Node > gwNode) const
uint32_t GetIdentifierForBeam (uint32_t satId, uint32_t beamId) const
uint32_t GetIdentifierForGroup (uint32_t groupId) const
uint32_t GetIdentifierForGw (Ptr< Node > gwNode) const
uint32_t GetIdentifierForIsl (Ptr< Node > satNodeSrc, Ptr< Node > satNodeDst) const
uint32_t GetIdentifierForSat (Ptr< Node > satNode) const
uint32_t GetIdentifierForUt (Ptr< Node > utNode) const
uint32_t GetIdentifierForUtUser (Ptr< Node > utUserNode) const
virtual std::string GetIdentifierHeading (std::string dataLabel) const
virtual std::string GetOutputFileName () const
Compute the path and file name where statistics output should be written to.
virtual std::string GetOutputPath () const
uint32_t GetSatId (Ptr< Node > satNode) const
virtual std::string GetTimeHeading (std::string dataLabel) const
uint32_t GetUtId (Ptr< Node > utNode) const
uint32_t GetUtUserId (Ptr< Node > utUserNode) const
Protected Attributes
Ptr< DataCollectionObject > m_aggregator
The aggregator created by this helper.
CollectorMap m_collectors
Maintains a list of collectors created by this helper.
Private Attributes
Callback< void, uint8_t, double > m_traceSinkCallback
Additional Inherited Members
Public Types inherited from ns3::SatStatsHelper
enum IdentifierType_t {
IDENTIFIER_GLOBAL = 0 , IDENTIFIER_GW , IDENTIFIER_BEAM , IDENTIFIER_UT ,
IDENTIFIER_UT_USER , IDENTIFIER_SLICE , IDENTIFIER_GROUP , IDENTIFIER_SAT ,
IDENTIFIER_ISL
}
Possible categorization of statistics output.
enum OutputType_t {
OUTPUT_NONE = 0 , OUTPUT_SCALAR_FILE , OUTPUT_SCATTER_FILE , OUTPUT_HISTOGRAM_FILE ,
OUTPUT_PDF_FILE , OUTPUT_CDF_FILE , OUTPUT_SCALAR_PLOT , OUTPUT_SCATTER_PLOT ,
OUTPUT_HISTOGRAM_PLOT , OUTPUT_PDF_PLOT , OUTPUT_CDF_PLOT
}
Possible types and formats of statistics output.
Static Protected Member Functions inherited from ns3::SatStatsHelper
static NetDeviceContainer GetGwSatNetDevice (Ptr< Node > gwNode)
static Ptr< NetDevice > GetSatSatGeoNetDevice (Ptr< Node > satNode)
static Ptr< NetDevice > GetUtSatNetDevice (Ptr< Node > utNode)
Detailed Description
Helper for forward link scheduler symbol rate statistic.
Base class.
Definition at line 45 of file satellite-stats-fwd-link-scheduler-symbol-rate-helper.h.
Constructor & Destructor Documentation
SatStatsFwdLinkSchedulerSymbolRateHelper()
ns3::SatStatsFwdLinkSchedulerSymbolRateHelper::SatStatsFwdLinkSchedulerSymbolRateHelper (Ptr< const SatHelper > satHelper)
Definition at line 54 of file satellite-stats-fwd-link-scheduler-symbol-rate-helper.cc.
~SatStatsFwdLinkSchedulerSymbolRateHelper()
ns3::SatStatsFwdLinkSchedulerSymbolRateHelper::~SatStatsFwdLinkSchedulerSymbolRateHelper () virtual
/ Destructor.
Definition at line 63 of file satellite-stats-fwd-link-scheduler-symbol-rate-helper.cc.
Member Function Documentation
DoInstall()
void ns3::SatStatsFwdLinkSchedulerSymbolRateHelper::DoInstall () protected virtual
Install the probes, collectors, and aggregators necessary to produce the statistics output.
An abstract method of SatStatsHelper which must be implemented by child classes. It will be invoked by Install().
Todo:
Add support for boxes in Gnuplot.
Implements ns3::SatStatsHelper.
Definition at line 146 of file satellite-stats-fwd-link-scheduler-symbol-rate-helper.cc.
References ns3::SatStatsHelper::CreateAggregator(), ns3::SatStatsHelper::CreateCollectorPerIdentifier(), ns3::SatStatsHelper::GetDistributionHeading(), ns3::SatStatsHelper::GetIdentifierHeading(), ns3::SatStatsHelper::GetName(), ns3::SatStatsHelper::GetOutputFileName(), ns3::SatStatsHelper::GetOutputPath(), ns3::SatStatsHelper::GetOutputType(), ns3::SatStatsHelper::GetOutputTypeName(), ns3::SatStatsHelper::GetTimeHeading(), InstallProbes(), m_aggregator, m_collectors, ns3::SatStatsHelper::OUTPUT_CDF_FILE, ns3::SatStatsHelper::OUTPUT_CDF_PLOT, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_FILE, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_PLOT, ns3::SatStatsHelper::OUTPUT_NONE, ns3::SatStatsHelper::OUTPUT_PDF_FILE, ns3::SatStatsHelper::OUTPUT_PDF_PLOT, ns3::SatStatsHelper::OUTPUT_SCALAR_FILE, ns3::SatStatsHelper::OUTPUT_SCALAR_PLOT, ns3::SatStatsHelper::OUTPUT_SCATTER_FILE, and ns3::SatStatsHelper::OUTPUT_SCATTER_PLOT.
GetTraceSinkCallback()
Callback< void, uint8_t, double > ns3::SatStatsFwdLinkSchedulerSymbolRateHelper::GetTraceSinkCallback () const
Returns
Definition at line 140 of file satellite-stats-fwd-link-scheduler-symbol-rate-helper.cc.
References m_traceSinkCallback.
Referenced by InstallProbes().
GetTypeId()
TypeId ns3::SatStatsFwdLinkSchedulerSymbolRateHelper::GetTypeId (void) static
inherited from ObjectBase base class
Definition at line 69 of file satellite-stats-fwd-link-scheduler-symbol-rate-helper.cc.
InstallProbes()
void ns3::SatStatsFwdLinkSchedulerSymbolRateHelper::InstallProbes ()
Set up several probes or other means of listeners and connect them to the collectors.
Definition at line 332 of file satellite-stats-fwd-link-scheduler-symbol-rate-helper.cc.
References ns3::SatStatsHelper::GetGwSatNetDevice(), ns3::SatStatsHelper::GetSatHelper(), and GetTraceSinkCallback().
Referenced by DoInstall().
SymbolRateCallback()
void ns3::SatStatsFwdLinkSchedulerSymbolRateHelper::SymbolRateCallback (uint8_t sliceId, double symbolRate)
Receive inputs from trace sources and forward them to the collector.
Parameters
sliceId the sliceId ID of the BBFrame.
symbolRate the symbol rate during the allocation cycle.
Definition at line 77 of file satellite-stats-fwd-link-scheduler-symbol-rate-helper.cc.
References ns3::SatStatsHelper::GetIdentifierType(), ns3::SatStatsHelper::GetOutputType(), ns3::SatStatsHelper::GetOutputTypeName(), ns3::SatStatsHelper::IDENTIFIER_GLOBAL, ns3::SatStatsHelper::IDENTIFIER_SLICE, m_collectors, ns3::SatStatsHelper::OUTPUT_CDF_FILE, ns3::SatStatsHelper::OUTPUT_CDF_PLOT, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_FILE, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_PLOT, ns3::SatStatsHelper::OUTPUT_PDF_FILE, ns3::SatStatsHelper::OUTPUT_PDF_PLOT, ns3::SatStatsHelper::OUTPUT_SCALAR_FILE, ns3::SatStatsHelper::OUTPUT_SCALAR_PLOT, ns3::SatStatsHelper::OUTPUT_SCATTER_FILE, and ns3::SatStatsHelper::OUTPUT_SCATTER_PLOT.
Member Data Documentation
m_aggregator
Ptr<DataCollectionObject> ns3::SatStatsFwdLinkSchedulerSymbolRateHelper::m_aggregator protected
The aggregator created by this helper.
Definition at line 87 of file satellite-stats-fwd-link-scheduler-symbol-rate-helper.h.
Referenced by DoInstall().
m_collectors
CollectorMap ns3::SatStatsFwdLinkSchedulerSymbolRateHelper::m_collectors protected
Maintains a list of collectors created by this helper.
Definition at line 84 of file satellite-stats-fwd-link-scheduler-symbol-rate-helper.h.
Referenced by DoInstall(), and SymbolRateCallback().
m_traceSinkCallback
Callback<void, uint8_t, double> ns3::SatStatsFwdLinkSchedulerSymbolRateHelper::m_traceSinkCallback private
Definition at line 91 of file satellite-stats-fwd-link-scheduler-symbol-rate-helper.h.
Referenced by GetTraceSinkCallback().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/stats/satellite-stats-fwd-link-scheduler-symbol-rate-helper.h
/builds/sns3/satellite/satellite/stats/satellite-stats-fwd-link-scheduler-symbol-rate-helper.cc