SNS3
ns3::SatStatsThroughputHelper Class Reference abstract
Satellite Statistics
#include "satellite-stats-throughput-helper.h"
Public Member Functions
SatStatsThroughputHelper (Ptr< const SatHelper > satHelper)
virtual ~SatStatsThroughputHelper ()
/ Destructor.
bool GetAveragingMode () const
void InstallProbes ()
Set up several probes or other means of listeners and connect them to the first-level collectors.
void RxCallback (Ptr< const Packet > packet, const Address &from)
Receive inputs from trace sources and determine the right collector to forward the inputs to.
void SetAveragingMode (bool averagingMode)
Public Member Functions inherited from ns3::SatStatsHelper
SatStatsHelper (Ptr< const SatHelper > satHelper)
Creates a new helper instance.
virtual ~SatStatsHelper ()
/ Destructor.
IdentifierType_t GetIdentifierType () const
std::string GetName () const
OutputType_t GetOutputType () const
Ptr< const SatHelper > GetSatHelper () const
void Install ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
bool IsInstalled () const
void SetIdentifierType (IdentifierType_t identifierType)
void SetName (std::string name)
void SetOutputType (OutputType_t outputType)
Static Public Member Functions
static TypeId GetTypeId ()
inherited from ObjectBase base class
Static Public Member Functions inherited from ns3::SatStatsHelper
static std::string GetIdentifierTypeName (IdentifierType_t identifierType)
static std::string GetOutputTypeName (OutputType_t outputType)
static TypeId GetTypeId ()
inherited from ObjectBase base class
Protected Member Functions
void DoInstall ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
virtual void DoInstallProbes ()=0
void SaveAddressAndIdentifier (Ptr< Node > utNode)
Save the address and the proper identifier from the given UT node.
Protected Member Functions inherited from ns3::SatStatsHelper
Ptr< DataCollectionObject > CreateAggregator (std::string aggregatorTypeId, std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue())
Create the aggregator according to the output type.
uint32_t CreateCollectorPerIdentifier (CollectorMap &collectorMap) const
Create one collector instance for each identifier in the simulation.
virtual std::string GetDistributionHeading (std::string dataLabel) const
uint32_t GetGwId (Ptr< Node > gwNode) const
uint32_t GetIdentifierForBeam (uint32_t satId, uint32_t beamId) const
uint32_t GetIdentifierForGroup (uint32_t groupId) const
uint32_t GetIdentifierForGw (Ptr< Node > gwNode) const
uint32_t GetIdentifierForIsl (Ptr< Node > satNodeSrc, Ptr< Node > satNodeDst) const
uint32_t GetIdentifierForSat (Ptr< Node > satNode) const
uint32_t GetIdentifierForUt (Ptr< Node > utNode) const
uint32_t GetIdentifierForUtUser (Ptr< Node > utUserNode) const
virtual std::string GetIdentifierHeading (std::string dataLabel) const
virtual std::string GetOutputFileName () const
Compute the path and file name where statistics output should be written to.
virtual std::string GetOutputPath () const
uint32_t GetSatId (Ptr< Node > satNode) const
virtual std::string GetTimeHeading (std::string dataLabel) const
uint32_t GetUtId (Ptr< Node > utNode) const
uint32_t GetUtUserId (Ptr< Node > utUserNode) const
Protected Attributes
Ptr< DataCollectionObject > m_aggregator
The aggregator created by this helper.
Ptr< DistributionCollector > m_averagingCollector
The final collector utilized in averaged output (histogram, PDF, and CDF).
CollectorMap m_conversionCollectors
Maintains a list of first-level collectors created by this helper.
std::map< const Address, uint32_t > m_identifierMap
Map of address and the identifier associated with it (for return link).
CollectorMap m_terminalCollectors
Maintains a list of second-level collectors created by this helper.
Private Attributes
bool m_averagingMode
AveragingMode attribute.
Additional Inherited Members
Public Types inherited from ns3::SatStatsHelper
enum IdentifierType_t {
IDENTIFIER_GLOBAL = 0 , IDENTIFIER_GW , IDENTIFIER_BEAM , IDENTIFIER_UT ,
IDENTIFIER_UT_USER , IDENTIFIER_SLICE , IDENTIFIER_GROUP , IDENTIFIER_SAT ,
IDENTIFIER_ISL
}
Possible categorization of statistics output.
enum OutputType_t {
OUTPUT_NONE = 0 , OUTPUT_SCALAR_FILE , OUTPUT_SCATTER_FILE , OUTPUT_HISTOGRAM_FILE ,
OUTPUT_PDF_FILE , OUTPUT_CDF_FILE , OUTPUT_SCALAR_PLOT , OUTPUT_SCATTER_PLOT ,
OUTPUT_HISTOGRAM_PLOT , OUTPUT_PDF_PLOT , OUTPUT_CDF_PLOT
}
Possible types and formats of statistics output.
Static Protected Member Functions inherited from ns3::SatStatsHelper
static NetDeviceContainer GetGwSatNetDevice (Ptr< Node > gwNode)
static Ptr< NetDevice > GetSatSatGeoNetDevice (Ptr< Node > satNode)
static Ptr< NetDevice > GetUtSatNetDevice (Ptr< Node > utNode)
Detailed Description
Definition at line 48 of file satellite-stats-throughput-helper.h.
Constructor & Destructor Documentation
SatStatsThroughputHelper()
ns3::SatStatsThroughputHelper::SatStatsThroughputHelper (Ptr< const SatHelper > satHelper)
Definition at line 62 of file satellite-stats-throughput-helper.cc.
~SatStatsThroughputHelper()
ns3::SatStatsThroughputHelper::~SatStatsThroughputHelper () virtual
/ Destructor.
Definition at line 69 of file satellite-stats-throughput-helper.cc.
Member Function Documentation
DoInstall()
void ns3::SatStatsThroughputHelper::DoInstall () protected virtual
Install the probes, collectors, and aggregators necessary to produce the statistics output.
An abstract method of SatStatsHelper which must be implemented by child classes. It will be invoked by Install().
Todo:
Add support for boxes in Gnuplot.
Todo:
Find a better dataset name.
Todo:
Find a better dataset name.
Implements ns3::SatStatsHelper.
Definition at line 104 of file satellite-stats-throughput-helper.cc.
References ns3::SatStatsHelper::CreateAggregator(), ns3::SatStatsHelper::CreateCollectorPerIdentifier(), ns3::SatStatsHelper::GetDistributionHeading(), ns3::SatStatsHelper::GetIdentifierHeading(), ns3::SatStatsHelper::GetName(), ns3::SatStatsHelper::GetOutputFileName(), ns3::SatStatsHelper::GetOutputPath(), ns3::SatStatsHelper::GetOutputType(), ns3::SatStatsHelper::GetOutputTypeName(), ns3::SatStatsHelper::GetTimeHeading(), InstallProbes(), m_aggregator, m_averagingCollector, m_averagingMode, m_conversionCollectors, m_terminalCollectors, ns3::SatStatsHelper::OUTPUT_CDF_FILE, ns3::SatStatsHelper::OUTPUT_CDF_PLOT, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_FILE, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_PLOT, ns3::SatStatsHelper::OUTPUT_NONE, ns3::SatStatsHelper::OUTPUT_PDF_FILE, ns3::SatStatsHelper::OUTPUT_PDF_PLOT, ns3::SatStatsHelper::OUTPUT_SCALAR_FILE, ns3::SatStatsHelper::OUTPUT_SCALAR_PLOT, ns3::SatStatsHelper::OUTPUT_SCATTER_FILE, and ns3::SatStatsHelper::OUTPUT_SCATTER_PLOT.
DoInstallProbes()
virtual void ns3::SatStatsThroughputHelper::DoInstallProbes () protected pure virtual
Implemented in ns3::SatStatsRtnUserPhyThroughputHelper, ns3::SatStatsRtnFeederPhyThroughputHelper, ns3::SatStatsRtnUserMacThroughputHelper, ns3::SatStatsRtnFeederMacThroughputHelper, ns3::SatStatsRtnUserDevThroughputHelper, ns3::SatStatsRtnFeederDevThroughputHelper, ns3::SatStatsRtnAppThroughputHelper, ns3::SatStatsFwdUserPhyThroughputHelper, ns3::SatStatsFwdFeederPhyThroughputHelper, ns3::SatStatsFwdUserMacThroughputHelper, ns3::SatStatsFwdFeederMacThroughputHelper, ns3::SatStatsFwdUserDevThroughputHelper, ns3::SatStatsFwdFeederDevThroughputHelper, and ns3::SatStatsFwdAppThroughputHelper.
Referenced by InstallProbes().
GetAveragingMode()
bool ns3::SatStatsThroughputHelper::GetAveragingMode () const
Returns
the currently active averaging mode.
Definition at line 98 of file satellite-stats-throughput-helper.cc.
References m_averagingMode.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::SatStatsThroughputHelper::GetTypeId (void) static
inherited from ObjectBase base class
Definition at line 75 of file satellite-stats-throughput-helper.cc.
References GetAveragingMode(), and SetAveragingMode().
InstallProbes()
void ns3::SatStatsThroughputHelper::InstallProbes ()
Set up several probes or other means of listeners and connect them to the first-level collectors.
Definition at line 387 of file satellite-stats-throughput-helper.cc.
References DoInstallProbes().
Referenced by DoInstall().
RxCallback()
void ns3::SatStatsThroughputHelper::RxCallback (Ptr< const Packet > packet, const Address & from)
Receive inputs from trace sources and determine the right collector to forward the inputs to.
Parameters
packet received packet data.
from the address of the sender of the packet.
Used in return link statistics. DoInstallProbes() is expected to connect the right trace sources to this method.
Definition at line 396 of file satellite-stats-throughput-helper.cc.
References m_conversionCollectors, and m_identifierMap.
Referenced by ns3::SatStatsFwdFeederDevThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdFeederMacThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdFeederPhyThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnFeederDevThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnUserDevThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnFeederMacThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnUserMacThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnFeederPhyThroughputHelper::DoInstallProbes(), and ns3::SatStatsRtnUserPhyThroughputHelper::DoInstallProbes().
SaveAddressAndIdentifier()
void ns3::SatStatsThroughputHelper::SaveAddressAndIdentifier (Ptr< Node > utNode) protected
Save the address and the proper identifier from the given UT node.
Parameters
utNode a UT node.
The address of the given node will be saved in the m_identifierMap member variable.
Used in return link statistics. DoInstallProbes() is expected to pass the the UT node of interest into this method.
Definition at line 436 of file satellite-stats-throughput-helper.cc.
References ns3::SatStatsHelper::GetIdentifierForUt(), ns3::SatIdMapper::GetUtMacWithNode(), and m_identifierMap.
Referenced by ns3::SatStatsFwdFeederDevThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdFeederMacThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdFeederPhyThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnFeederDevThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnUserDevThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnFeederMacThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnUserMacThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnFeederPhyThroughputHelper::DoInstallProbes(), and ns3::SatStatsRtnUserPhyThroughputHelper::DoInstallProbes().
SetAveragingMode()
void ns3::SatStatsThroughputHelper::SetAveragingMode (bool averagingMode)
Parameters
averagingMode average all samples before passing them to aggregator.
Definition at line 91 of file satellite-stats-throughput-helper.cc.
References m_averagingMode.
Referenced by GetTypeId().
Member Data Documentation
m_aggregator
Ptr<DataCollectionObject> ns3::SatStatsThroughputHelper::m_aggregator protected
The aggregator created by this helper.
Definition at line 122 of file satellite-stats-throughput-helper.h.
Referenced by DoInstall().
m_averagingCollector
Ptr<DistributionCollector> ns3::SatStatsThroughputHelper::m_averagingCollector protected
The final collector utilized in averaged output (histogram, PDF, and CDF).
Definition at line 119 of file satellite-stats-throughput-helper.h.
Referenced by DoInstall().
m_averagingMode
bool ns3::SatStatsThroughputHelper::m_averagingMode private
AveragingMode attribute.
Definition at line 128 of file satellite-stats-throughput-helper.h.
Referenced by DoInstall(), GetAveragingMode(), and SetAveragingMode().
m_conversionCollectors
CollectorMap ns3::SatStatsThroughputHelper::m_conversionCollectors protected
Maintains a list of first-level collectors created by this helper.
Definition at line 113 of file satellite-stats-throughput-helper.h.
Referenced by DoInstall(), ns3::SatStatsFwdAppThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdUserDevThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdUserMacThroughputHelper::DoInstallProbes(), ns3::SatStatsFwdUserPhyThroughputHelper::DoInstallProbes(), ns3::SatStatsRtnAppThroughputHelper::Ipv4Callback(), and RxCallback().
m_identifierMap
std::map<const Address, uint32_t> ns3::SatStatsThroughputHelper::m_identifierMap protected
Map of address and the identifier associated with it (for return link).
Definition at line 125 of file satellite-stats-throughput-helper.h.
Referenced by ns3::SatStatsRtnAppThroughputHelper::Ipv4Callback(), RxCallback(), SaveAddressAndIdentifier(), and ns3::SatStatsRtnAppThroughputHelper::SaveIpv4AddressAndIdentifier().
m_terminalCollectors
CollectorMap ns3::SatStatsThroughputHelper::m_terminalCollectors protected
Maintains a list of second-level collectors created by this helper.
Definition at line 116 of file satellite-stats-throughput-helper.h.
Referenced by DoInstall().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/stats/satellite-stats-throughput-helper.h
/builds/sns3/satellite/satellite/stats/satellite-stats-throughput-helper.cc