SNS3
SatBasicEstimatorMinTestCase Class Reference
Test case to unit test satellite C/N0 estimator with mode MINIMUM.
Public Member Functions
SatBasicEstimatorMinTestCase ()
virtual ~SatBasicEstimatorMinTestCase ()
Public Member Functions inherited from SatEstimatorBaseTestCase
SatEstimatorBaseTestCase ()
SatEstimatorBaseTestCase (std::string info)
virtual ~SatEstimatorBaseTestCase ()
void AddSample (double cno)
void CreateEstimator (SatCnoEstimator::EstimationMode_t mode, Time window)
void GetCnoEstimation ()
Protected Member Functions
virtual void DoRun (void)
Additional Inherited Members
Protected Attributes inherited from SatEstimatorBaseTestCase
std::vector< double > m_cnoEstimations
Ptr< SatCnoEstimator > m_estimator
Detailed Description
Test case to unit test satellite C/N0 estimator with mode MINIMUM.
This case tests that SatBasicCnoEstimator can be created in mode MINIMUM and C/N0 is estimated correctly in set window.
Create SatBasicCnoEstimator object with MINIMUM mode using different window values.
Set samples to estimator at different points of time (method AddSample).
Get C/N0 estimation from estimator at some points of time (method GetCnoEstimation).
Expected result: Returned C/N0 estimation must be the minimum value of samples in window.
C/N0 estimation must be NAN, if no samples are got during time window.
Definition at line 237 of file satellite-cno-estimator-test.cc.
Constructor & Destructor Documentation
SatBasicEstimatorMinTestCase()
SatBasicEstimatorMinTestCase::SatBasicEstimatorMinTestCase () inline
Definition at line 240 of file satellite-cno-estimator-test.cc.
~SatBasicEstimatorMinTestCase()
virtual SatBasicEstimatorMinTestCase::~SatBasicEstimatorMinTestCase () inline virtual
Definition at line 245 of file satellite-cno-estimator-test.cc.
Member Function Documentation
DoRun()
void SatBasicEstimatorMinTestCase::DoRun (void) protected virtual
Implements SatEstimatorBaseTestCase.
Definition at line 254 of file satellite-cno-estimator-test.cc.
References SatEstimatorBaseTestCase::AddSample(), SatEstimatorBaseTestCase::CreateEstimator(), SatEstimatorBaseTestCase::GetCnoEstimation(), and ns3::SatCnoEstimator::MINIMUM.
The documentation for this class was generated from the following file:
/builds/sns3/satellite/satellite/test/satellite-cno-estimator-test.cc