SNS3
ns3::SatStatsQueueHelper Class Reference abstract
Satellite Statistics
Helper for queue statistics.
#include "satellite-stats-queue-helper.h"
Public Types
enum UnitType_t { UNIT_BYTES = 0 , UNIT_NUMBER_OF_PACKETS }
Public Types inherited from ns3::SatStatsHelper
enum IdentifierType_t {
IDENTIFIER_GLOBAL = 0 , IDENTIFIER_GW , IDENTIFIER_BEAM , IDENTIFIER_UT ,
IDENTIFIER_UT_USER , IDENTIFIER_SLICE , IDENTIFIER_GROUP , IDENTIFIER_SAT ,
IDENTIFIER_ISL
}
Possible categorization of statistics output.
enum OutputType_t {
OUTPUT_NONE = 0 , OUTPUT_SCALAR_FILE , OUTPUT_SCATTER_FILE , OUTPUT_HISTOGRAM_FILE ,
OUTPUT_PDF_FILE , OUTPUT_CDF_FILE , OUTPUT_SCALAR_PLOT , OUTPUT_SCATTER_PLOT ,
OUTPUT_HISTOGRAM_PLOT , OUTPUT_PDF_PLOT , OUTPUT_CDF_PLOT
}
Possible types and formats of statistics output.
Public Member Functions
SatStatsQueueHelper (Ptr< const SatHelper > satHelper)
virtual ~SatStatsQueueHelper ()
/ Destructor.
void EnlistSource ()
Identify the list of source of queue events.
Time GetPollInterval () const
UnitType_t GetUnitType () const
void Poll ()
Retrieve the queue size of every relevant encapsulator and push the values to the right collectors.
void SetPollInterval (Time pollInterval)
void SetUnitType (UnitType_t unitType)
Public Member Functions inherited from ns3::SatStatsHelper
SatStatsHelper (Ptr< const SatHelper > satHelper)
Creates a new helper instance.
virtual ~SatStatsHelper ()
/ Destructor.
IdentifierType_t GetIdentifierType () const
std::string GetName () const
OutputType_t GetOutputType () const
Ptr< const SatHelper > GetSatHelper () const
void Install ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
bool IsInstalled () const
void SetIdentifierType (IdentifierType_t identifierType)
void SetName (std::string name)
void SetOutputType (OutputType_t outputType)
Static Public Member Functions
static TypeId GetTypeId ()
inherited from ObjectBase base class
static std::string GetUnitTypeName (UnitType_t unitType)
Static Public Member Functions inherited from ns3::SatStatsHelper
static std::string GetIdentifierTypeName (IdentifierType_t identifierType)
static std::string GetOutputTypeName (OutputType_t outputType)
static TypeId GetTypeId ()
inherited from ObjectBase base class
Protected Member Functions
virtual void DoEnlistSource ()=0
void DoInstall ()
Install the probes, collectors, and aggregators necessary to produce the statistics output.
virtual void DoPoll ()=0
Retrieve the queue size of every relevant encapsulator and push the values to the right collectors.
void PushToCollector (uint32_t identifier, uint32_t value)
Protected Member Functions inherited from ns3::SatStatsHelper
Ptr< DataCollectionObject > CreateAggregator (std::string aggregatorTypeId, std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue())
Create the aggregator according to the output type.
uint32_t CreateCollectorPerIdentifier (CollectorMap &collectorMap) const
Create one collector instance for each identifier in the simulation.
virtual std::string GetDistributionHeading (std::string dataLabel) const
uint32_t GetGwId (Ptr< Node > gwNode) const
uint32_t GetIdentifierForBeam (uint32_t satId, uint32_t beamId) const
uint32_t GetIdentifierForGroup (uint32_t groupId) const
uint32_t GetIdentifierForGw (Ptr< Node > gwNode) const
uint32_t GetIdentifierForIsl (Ptr< Node > satNodeSrc, Ptr< Node > satNodeDst) const
uint32_t GetIdentifierForSat (Ptr< Node > satNode) const
uint32_t GetIdentifierForUt (Ptr< Node > utNode) const
uint32_t GetIdentifierForUtUser (Ptr< Node > utUserNode) const
virtual std::string GetIdentifierHeading (std::string dataLabel) const
virtual std::string GetOutputFileName () const
Compute the path and file name where statistics output should be written to.
virtual std::string GetOutputPath () const
uint32_t GetSatId (Ptr< Node > satNode) const
virtual std::string GetTimeHeading (std::string dataLabel) const
uint32_t GetUtId (Ptr< Node > utNode) const
uint32_t GetUtUserId (Ptr< Node > utUserNode) const
Protected Attributes
Ptr< DataCollectionObject > m_aggregator
The aggregator created by this helper.
CollectorMap m_terminalCollectors
Maintains a list of collectors created by this helper.
Private Attributes
std::string m_longLabel
Time m_pollInterval
PollInterval attribute.
std::string m_shortLabel
UnitType_t m_unitType
Additional Inherited Members
Static Protected Member Functions inherited from ns3::SatStatsHelper
static NetDeviceContainer GetGwSatNetDevice (Ptr< Node > gwNode)
static Ptr< NetDevice > GetSatSatGeoNetDevice (Ptr< Node > satNode)
static Ptr< NetDevice > GetUtSatNetDevice (Ptr< Node > utNode)
Detailed Description
Helper for queue statistics.
Base class.
Definition at line 46 of file satellite-stats-queue-helper.h.
Member Enumeration Documentation
UnitType_t
enum ns3::SatStatsQueueHelper::UnitType_t
Enumerator
UNIT_BYTES
UNIT_NUMBER_OF_PACKETS
Definition at line 53 of file satellite-stats-queue-helper.h.
Constructor & Destructor Documentation
SatStatsQueueHelper()
ns3::SatStatsQueueHelper::SatStatsQueueHelper (Ptr< const SatHelper > satHelper)
Definition at line 75 of file satellite-stats-queue-helper.cc.
~SatStatsQueueHelper()
ns3::SatStatsQueueHelper::~SatStatsQueueHelper () virtual
/ Destructor.
Definition at line 85 of file satellite-stats-queue-helper.cc.
Member Function Documentation
DoEnlistSource()
virtual void ns3::SatStatsQueueHelper::DoEnlistSource () protected pure virtual
Implemented in ns3::SatStatsRtnQueueHelper, and ns3::SatStatsFwdQueueHelper.
Referenced by EnlistSource().
DoInstall()
void ns3::SatStatsQueueHelper::DoInstall () protected virtual
Install the probes, collectors, and aggregators necessary to produce the statistics output.
An abstract method of SatStatsHelper which must be implemented by child classes. It will be invoked by Install().
Todo:
Add support for boxes in Gnuplot.
Implements ns3::SatStatsHelper.
Definition at line 147 of file satellite-stats-queue-helper.cc.
References ns3::SatStatsHelper::CreateAggregator(), ns3::SatStatsHelper::CreateCollectorPerIdentifier(), EnlistSource(), ns3::SatStatsHelper::GetDistributionHeading(), ns3::SatStatsHelper::GetIdentifierHeading(), ns3::SatStatsHelper::GetName(), ns3::SatStatsHelper::GetOutputFileName(), ns3::SatStatsHelper::GetOutputPath(), ns3::SatStatsHelper::GetOutputType(), ns3::SatStatsHelper::GetOutputTypeName(), ns3::SatStatsHelper::GetTimeHeading(), m_aggregator, m_longLabel, m_pollInterval, m_shortLabel, m_terminalCollectors, ns3::SatStatsHelper::OUTPUT_CDF_FILE, ns3::SatStatsHelper::OUTPUT_CDF_PLOT, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_FILE, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_PLOT, ns3::SatStatsHelper::OUTPUT_NONE, ns3::SatStatsHelper::OUTPUT_PDF_FILE, ns3::SatStatsHelper::OUTPUT_PDF_PLOT, ns3::SatStatsHelper::OUTPUT_SCALAR_FILE, ns3::SatStatsHelper::OUTPUT_SCALAR_PLOT, ns3::SatStatsHelper::OUTPUT_SCATTER_FILE, ns3::SatStatsHelper::OUTPUT_SCATTER_PLOT, and Poll().
DoPoll()
virtual void ns3::SatStatsQueueHelper::DoPoll () protected pure virtual
Retrieve the queue size of every relevant encapsulator and push the values to the right collectors.
Implemented in ns3::SatStatsRtnQueueHelper, and ns3::SatStatsFwdQueueHelper.
Referenced by Poll().
EnlistSource()
void ns3::SatStatsQueueHelper::EnlistSource ()
Identify the list of source of queue events.
Definition at line 341 of file satellite-stats-queue-helper.cc.
References DoEnlistSource().
Referenced by DoInstall().
GetPollInterval()
Time ns3::SatStatsQueueHelper::GetPollInterval () const
Returns
Definition at line 141 of file satellite-stats-queue-helper.cc.
References m_pollInterval.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::SatStatsQueueHelper::GetTypeId (void) static
inherited from ObjectBase base class
Definition at line 91 of file satellite-stats-queue-helper.cc.
References GetPollInterval(), and SetPollInterval().
GetUnitType()
SatStatsQueueHelper::UnitType_t ns3::SatStatsQueueHelper::GetUnitType () const
Returns
Definition at line 128 of file satellite-stats-queue-helper.cc.
References m_unitType.
Referenced by ns3::SatStatsFwdQueueHelper::DoPoll(), and ns3::SatStatsRtnQueueHelper::DoPoll().
GetUnitTypeName()
std::string ns3::SatStatsQueueHelper::GetUnitTypeName (SatStatsQueueHelper::UnitType_t unitType) static
Parameters
unitType
Returns
Definition at line 58 of file satellite-stats-queue-helper.cc.
References UNIT_BYTES, and UNIT_NUMBER_OF_PACKETS.
Referenced by SetUnitType().
Poll()
void ns3::SatStatsQueueHelper::Poll ()
Retrieve the queue size of every relevant encapsulator and push the values to the right collectors.
Definition at line 350 of file satellite-stats-queue-helper.cc.
References DoPoll(), and m_pollInterval.
Referenced by DoInstall().
PushToCollector()
void ns3::SatStatsQueueHelper::PushToCollector (uint32_t identifier, uint32_t value) protected
Parameters
identifier
value
Definition at line 362 of file satellite-stats-queue-helper.cc.
References ns3::SatStatsHelper::GetOutputType(), ns3::SatStatsHelper::GetOutputTypeName(), m_terminalCollectors, ns3::SatStatsHelper::OUTPUT_CDF_FILE, ns3::SatStatsHelper::OUTPUT_CDF_PLOT, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_FILE, ns3::SatStatsHelper::OUTPUT_HISTOGRAM_PLOT, ns3::SatStatsHelper::OUTPUT_PDF_FILE, ns3::SatStatsHelper::OUTPUT_PDF_PLOT, ns3::SatStatsHelper::OUTPUT_SCALAR_FILE, ns3::SatStatsHelper::OUTPUT_SCALAR_PLOT, ns3::SatStatsHelper::OUTPUT_SCATTER_FILE, and ns3::SatStatsHelper::OUTPUT_SCATTER_PLOT.
Referenced by ns3::SatStatsFwdQueueHelper::DoPoll(), and ns3::SatStatsRtnQueueHelper::DoPoll().
SetPollInterval()
void ns3::SatStatsQueueHelper::SetPollInterval (Time pollInterval)
Parameters
pollInterval
Definition at line 134 of file satellite-stats-queue-helper.cc.
References m_pollInterval.
Referenced by GetTypeId().
SetUnitType()
void ns3::SatStatsQueueHelper::SetUnitType (SatStatsQueueHelper::UnitType_t unitType)
Parameters
unitType
Definition at line 105 of file satellite-stats-queue-helper.cc.
References GetUnitTypeName(), m_longLabel, m_shortLabel, m_unitType, UNIT_BYTES, and UNIT_NUMBER_OF_PACKETS.
Referenced by ns3::SatStatsFwdQueueBytesHelper::SatStatsFwdQueueBytesHelper(), ns3::SatStatsFwdQueuePacketsHelper::SatStatsFwdQueuePacketsHelper(), ns3::SatStatsRtnQueueBytesHelper::SatStatsRtnQueueBytesHelper(), and ns3::SatStatsRtnQueuePacketsHelper::SatStatsRtnQueuePacketsHelper().
Member Data Documentation
m_aggregator
Ptr<DataCollectionObject> ns3::SatStatsQueueHelper::m_aggregator protected
The aggregator created by this helper.
Definition at line 134 of file satellite-stats-queue-helper.h.
Referenced by DoInstall().
m_longLabel
std::string ns3::SatStatsQueueHelper::m_longLabel private
Definition at line 140 of file satellite-stats-queue-helper.h.
Referenced by DoInstall(), and SetUnitType().
m_pollInterval
Time ns3::SatStatsQueueHelper::m_pollInterval private
PollInterval attribute.
Definition at line 137 of file satellite-stats-queue-helper.h.
Referenced by DoInstall(), GetPollInterval(), Poll(), and SetPollInterval().
m_shortLabel
std::string ns3::SatStatsQueueHelper::m_shortLabel private
Definition at line 139 of file satellite-stats-queue-helper.h.
Referenced by DoInstall(), and SetUnitType().
m_terminalCollectors
CollectorMap ns3::SatStatsQueueHelper::m_terminalCollectors protected
Maintains a list of collectors created by this helper.
Definition at line 131 of file satellite-stats-queue-helper.h.
Referenced by DoInstall(), and PushToCollector().
m_unitType
UnitType_t ns3::SatStatsQueueHelper::m_unitType private
Definition at line 138 of file satellite-stats-queue-helper.h.
Referenced by GetUnitType(), and SetUnitType().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/stats/satellite-stats-queue-helper.h
/builds/sns3/satellite/satellite/stats/satellite-stats-queue-helper.cc