SNS3
ns3::SatGeoFeederMac Class Reference
The SatGeoFeederMac models the user link MAC layer of the satellite node.
#include "satellite-geo-feeder-mac.h"
Public Member Functions
SatGeoFeederMac (uint32_t satId, uint32_t beamId, SatEnums::RegenerationMode_t forwardLinkRegenerationMode, SatEnums::RegenerationMode_t returnLinkRegenerationMode)
Construct a SatGeoFeederMac.
SatGeoFeederMac (void)
Default constructor.
virtual ~SatGeoFeederMac ()
Destructor for SatGeoFeederMac.
virtual void DoDispose (void)
Dispose of this class instance.
virtual void DoInitialize (void)
virtual void EnquePacket (Ptr< Packet > packet)
Add new packet to the LLC queue.
TypeId GetInstanceTypeId (void) const
void Receive (SatPhy::PacketContainer_t packets, Ptr< SatSignalParameters > rxParams)
Receive packet from lower layer.
void ReceiveSignalingPacket (Ptr< Packet > packet)
Public Member Functions inherited from ns3::SatGeoMac
SatGeoMac (uint32_t satId, uint32_t beamId, SatEnums::RegenerationMode_t forwardLinkRegenerationMode, SatEnums::RegenerationMode_t returnLinkRegenerationMode)
Construct a SatGeoMac.
SatGeoMac (void)
Default constructor.
virtual ~SatGeoMac ()
Destructor for SatGeoMac.
virtual Time GetGuardTime () const
TypeId GetInstanceTypeId (void) const
void SetFwdScheduler (Ptr< SatFwdLinkScheduler > fwdScheduler)
Method to set link scheduler (forward or SCPC)
virtual void SetGuardTime (Time guardTime)
void SetLlc (Ptr< SatGeoLlc > llc)
Set the Geo LLC associated to this Geo MAC layer.
void SetReceiveNetDeviceCallback (SatGeoMac::ReceiveNetDeviceCallback cb)
void SetTransmitCallback (SatGeoMac::TransmitCallback cb)
void StartPeriodicTransmissions ()
Starts periodical transmissions.
Public Member Functions inherited from ns3::SatMac
SatMac ()
Construct a SatMac.
SatMac (uint32_t satId, uint32_t beamId, SatEnums::RegenerationMode_t forwardLinkRegenerationMode, SatEnums::RegenerationMode_t returnLinkRegenerationMode)
Construct a SatMac.
~SatMac ()
Destroy a SatMac.
virtual void Disable ()
Disable the MAC layer, i.e.
virtual void Enable ()
Enable the MAC layer, i.e.
Address GetAddress () const
Get MAC address.
uint32_t GetBeamId () const
Get beam ID of the object.
uint32_t GetSatId () const
Get sat ID of the object.
virtual void ReceiveQueueEvent (SatQueue::QueueEvent_t event, uint8_t flowIndex)
Receive a queue event:
uint32_t ReserveIdAndStoreCtrlMsgToContainer (Ptr< SatControlMessage > msg)
Reserve id and store the control message.
uint32_t SendCtrlMsgFromContainer (uint32_t sendId)
Send the control message from the container.
void SetLoraReceiveCallback (SatMac::LoraReceiveCallback cb)
Method to set receive callback.
virtual void SetNodeInfo (Ptr< SatNodeInfo > nodeInfo)
Set the node info.
void SetReadCtrlCallback (SatMac::ReadCtrlMsgCallback cb)
Method to set read control message callback.
void SetReceiveCallback (SatMac::ReceiveCallback cb)
Method to set receive callback.
void SetReserveCtrlCallback (SatMac::ReserveCtrlMsgCallback cb)
Method to set reserve control message id callback.
void SetRoutingUpdateCallback (SatMac::RoutingUpdateCallback cb)
Method to set the routing update callback.
virtual void SetSatelliteAddress (Address satelliteAddress)
Set the satellite MAC address on the other side of this link (if regenerative satellite).
void SetSendCtrlCallback (SatMac::SendCtrlMsgCallback cb)
Method to set send control message callback.
void SetTransmitCallback (SatMac::TransmitCallback cb)
Method to set transmit callback.
Static Public Member Functions
static TypeId GetTypeId (void)
inherited from Object
Static Public Member Functions inherited from ns3::SatGeoMac
static TypeId GetTypeId (void)
inherited from Object
Static Public Member Functions inherited from ns3::SatMac
static TypeId GetTypeId (void)
Derived from Object.
Protected Member Functions
virtual Address GetRxUtAddress (Ptr< Packet > packet)
Get the UT address associated to this RX packet.
virtual SatEnums::SatLinkDir_t GetSatLinkRxDir ()
Get the link RX direction.
virtual SatEnums::SatLinkDir_t GetSatLinkTxDir ()
Get the link TX direction.
Protected Member Functions inherited from ns3::SatGeoMac
virtual void RxTraces (SatPhy::PacketContainer_t packets)
Invoke the Rx trace source for each received packet.
virtual void SendPacket (SatPhy::PacketContainer_t packets, uint32_t carrierId, Time duration, SatSignalParameters::txInfo_s txInfo)
Send packets to lower layer by using a callback.
void StartTransmission (uint32_t carrierId)
Start sending a Packet Down the Wire.
Protected Member Functions inherited from ns3::SatMac
void DoDispose (void)
Dispose of SatMac.
void RxTraces (SatPhy::PacketContainer_t packets)
Invoke the Rx trace source for each received packet.
void SetTimeTag (SatPhy::PacketContainer_t packets)
Set SatMacTimeTag of packets.
Additional Inherited Members
Public Types inherited from ns3::SatGeoMac
typedef Callback< void, SatPhy::PacketContainer_t, Ptr< SatSignalParameters > > ReceiveNetDeviceCallback
typedef Callback< void, Ptr< SatSignalParameters > > TransmitCallback
Public Types inherited from ns3::SatMac
typedef Callback< void, Ptr< const Packet > > LoraReceiveCallback
Callback to receive packet by upper layer.
typedef Callback< Ptr< SatControlMessage >, uint32_t > ReadCtrlMsgCallback
Callback to read control messages from container storing control messages.
typedef Callback< void, Ptr< Packet >, Mac48Address, Mac48Address > ReceiveCallback
Callback to receive packet by upper layer.
typedef Callback< uint32_t, Ptr< SatControlMessage > > ReserveCtrlMsgCallback
Callback to reserve an id and initially store the control message.
typedef Callback< void, Address, Address > RoutingUpdateCallback
Callback to update routing and ARP tables after handover.
typedef Callback< uint32_t, uint32_t > SendCtrlMsgCallback
Callback to send a control message and allocate a recv ID for it.
typedef Callback< void, SatPhy::PacketContainer_t, uint32_t, Time, SatSignalParameters::txInfo_s > TransmitCallback
Callback to send packet to lower layer.
Protected Attributes inherited from ns3::SatGeoMac
TracedCallback< Ptr< SatBbFrame > > m_bbFrameTxTrace
Trace for transmitted BB frames.
uint32_t m_beamId
ID of beam for UT.
Ptr< SatFwdLinkScheduler > m_fwdScheduler
Scheduler for the forward link.
Time m_guardTime
Guard time for BB frames.
Ptr< SatGeoLlc > m_llc
LLC layer linked to this MAC.
ReceiveNetDeviceCallback m_rxNetDeviceCallback
uint32_t m_satId
ID of sat for UT.
TransmitCallback m_txCallback
Protected Attributes inherited from ns3::SatMac
Time m_beamEnabledTime
Time of the last beam enable event.
uint32_t m_beamId
The ID of the beam where mac belongs.
TracedCallback< Time > m_beamServiceTrace
Traced callback for beam being disabled and including service time.
SatEnums::RegenerationMode_t m_forwardLinkRegenerationMode
Regeneration mode on forward link.
bool m_isRegenerative
Indicate if satellite is regeneration (at least LINK level) for TX.
bool m_isStatisticsTagsEnabled
EnableStatisticsTags attribute.
Time m_lastDelay
Last delay measurement.
Time m_lastLinkDelay
Last delay measurement for link.
std::queue< Time > m_lastSOF
Store last 3 SOF date for Forward messages, to insert in NCR packets.
std::queue< Ptr< SatNcrMessage > > m_ncrMessagesToSend
List of NCR control messages created but not sent yet.
bool m_ncrV2
Use of version 2 of NCR dates.
Ptr< SatNodeInfo > m_nodeInfo
Node info containing node related information, such as node type, node id and MAC address (of the SatNetDevice)
TracedCallback< Time, SatEnums::SatPacketEvent_t, SatEnums::SatNodeType_t, uint32_t, Mac48Address, SatEnums::SatLogLevel_t, SatEnums::SatLinkDir_t, std::string > m_packetTrace
Trace callback used for packet tracing.
SatMac::ReadCtrlMsgCallback m_readCtrlCallback
The read control message callback.
SatMac::ReserveCtrlMsgCallback m_reserveCtrlCallback
The reserve control message id callback.
SatEnums::RegenerationMode_t m_returnLinkRegenerationMode
Regeneration mode on return link.
SatMac::RoutingUpdateCallback m_routingUpdateCallback
Callback to update routing and ARP tables after a beam handover.
SatMac::ReceiveCallback m_rxCallback
The upper layer package receive callback.
TracedCallback< const Time &, const Address & > m_rxDelayTrace
Traced callback for all received packets, including delay information and the address of the senders.
TracedCallback< const Time &, const Address & > m_rxJitterTrace
Traced callback for all received packets, including jitter information and the address of the senders.
TracedCallback< const Time &, const Address & > m_rxLinkDelayTrace
Traced callback for all received packets, including link delay information and the address of the senders.
TracedCallback< const Time &, const Address & > m_rxLinkJitterTrace
Traced callback for all received packets, including link jitter information and the address of the senders.
SatMac::LoraReceiveCallback m_rxLoraCallback
The upper layer package receive callback.
TracedCallback< Ptr< const Packet >, const Address & > m_rxTrace
Traced callback for all received packets, including the address of the senders.
Address m_satelliteAddress
MAC address of satellite on other side of the link.
uint32_t m_satId
The ID of the sat where mac belongs.
SatMac::SendCtrlMsgCallback m_sendCtrlCallback
The send control message callback.
SatMac::TransmitCallback m_txCallback
The lower layer packet transmit callback.
bool m_txEnabled
Flag indicating whether the MAC is enabled, i.e.
Detailed Description
The SatGeoFeederMac models the user link MAC layer of the satellite node.
Definition at line 46 of file satellite-geo-feeder-mac.h.
Constructor & Destructor Documentation
SatGeoFeederMac() [1/2]
ns3::SatGeoFeederMac::SatGeoFeederMac (void)
Default constructor.
Definition at line 66 of file satellite-geo-feeder-mac.cc.
SatGeoFeederMac() [2/2]
ns3::SatGeoFeederMac::SatGeoFeederMac (uint32_t satId, uint32_t beamId, SatEnums::RegenerationMode_t forwardLinkRegenerationMode, SatEnums::RegenerationMode_t returnLinkRegenerationMode)
Construct a SatGeoFeederMac.
This is the constructor for the SatGeoFeederMac
Parameters
satId ID of sat for UT
beamid ID of beam for UT
forwardLinkRegenerationMode Forward link regeneration mode
returnLinkRegenerationMode Return link regeneration mode
Definition at line 72 of file satellite-geo-feeder-mac.cc.
~SatGeoFeederMac()
ns3::SatGeoFeederMac::~SatGeoFeederMac () virtual
Destructor for SatGeoFeederMac.
Definition at line 81 of file satellite-geo-feeder-mac.cc.
Member Function Documentation
DoDispose()
void ns3::SatGeoFeederMac::DoDispose (void) virtual
Dispose of this class instance.
Reimplemented from ns3::SatGeoMac.
Definition at line 87 of file satellite-geo-feeder-mac.cc.
DoInitialize()
void ns3::SatGeoFeederMac::DoInitialize (void) virtual
Reimplemented from ns3::SatGeoMac.
Definition at line 94 of file satellite-geo-feeder-mac.cc.
EnquePacket()
void ns3::SatGeoFeederMac::EnquePacket (Ptr< Packet > packet) virtual
Add new packet to the LLC queue.
Parameters
packet Packets to be sent.
Implements ns3::SatGeoMac.
Definition at line 101 of file satellite-geo-feeder-mac.cc.
References ns3::SatAddressE2ETag::GetE2EDestAddress(), ns3::SatGeoMac::m_llc, ns3::SatMac::m_nodeInfo, ns3::SatMac::m_returnLinkRegenerationMode, ns3::SatEnums::REGENERATION_NETWORK, ns3::SatMacTag::SetDestAddress(), and ns3::SatMacTag::SetSourceAddress().
GetInstanceTypeId()
TypeId ns3::SatGeoFeederMac::GetInstanceTypeId (void) const
Definition at line 59 of file satellite-geo-feeder-mac.cc.
References GetTypeId().
GetRxUtAddress()
Address ns3::SatGeoFeederMac::GetRxUtAddress (Ptr< Packet > packet) protected virtual
Get the UT address associated to this RX packet.
In this class, this is the destination address
Parameters
packet The packet to consider
Returns
The address of associated UT
Implements ns3::SatGeoMac.
Definition at line 294 of file satellite-geo-feeder-mac.cc.
References ns3::SatAddressE2ETag::GetE2EDestAddress().
GetSatLinkRxDir()
SatEnums::SatLinkDir_t ns3::SatGeoFeederMac::GetSatLinkRxDir () protected virtual
Get the link RX direction.
Must be implemented by child clases.
Returns
The link RX direction
Implements ns3::SatGeoMac.
Definition at line 288 of file satellite-geo-feeder-mac.cc.
References ns3::SatEnums::LD_FORWARD.
GetSatLinkTxDir()
SatEnums::SatLinkDir_t ns3::SatGeoFeederMac::GetSatLinkTxDir () protected virtual
Get the link TX direction.
Must be implemented by child clases.
Returns
The link TX direction
Implements ns3::SatGeoMac.
Definition at line 282 of file satellite-geo-feeder-mac.cc.
References ns3::SatEnums::LD_RETURN.
GetTypeId()
TypeId ns3::SatGeoFeederMac::GetTypeId (void) static
inherited from Object
Definition at line 44 of file satellite-geo-feeder-mac.cc.
References ns3::SatGeoMac::GetGuardTime(), and ns3::SatGeoMac::SetGuardTime().
Referenced by GetInstanceTypeId().
Receive()
void ns3::SatGeoFeederMac::Receive (SatPhy::PacketContainer_t packets, Ptr< SatSignalParameters > rxParams)
Receive packet from lower layer.
Parameters
packets Pointers to packets received.
Definition at line 133 of file satellite-geo-feeder-mac.cc.
References ns3::SatMacTag::GetDestAddress(), ns3::SatAddressE2ETag::GetE2EDestAddress(), ns3::SatControlMsgTag::GetMsgType(), ns3::SatUtils::GetPacketInfo(), ns3::SatMacTag::GetSourceAddress(), ns3::SatEnums::LD_FORWARD, ns3::SatEnums::LL_MAC, ns3::SatMac::m_forwardLinkRegenerationMode, ns3::SatMac::m_nodeInfo, ns3::SatMac::m_packetTrace, ns3::SatMac::m_rxCallback, ns3::SatGeoMac::m_rxNetDeviceCallback, ns3::SatEnums::PACKET_RECV, ReceiveSignalingPacket(), ns3::SatEnums::REGENERATION_LINK, ns3::SatEnums::REGENERATION_NETWORK, ns3::SatGeoMac::RxTraces(), and ns3::SatControlMsgTag::SAT_NON_CTRL_MSG.
Referenced by ns3::SatGeoHelper::AttachChannelsFeeder().
ReceiveSignalingPacket()
void ns3::SatGeoFeederMac::ReceiveSignalingPacket (Ptr< Packet > packet)
Definition at line 234 of file satellite-geo-feeder-mac.cc.
References ns3::SatControlMsgTag::GetMsgId(), ns3::SatControlMsgTag::GetMsgType(), ns3::SatMacTag::GetSourceAddress(), ns3::SatGeoMac::m_fwdScheduler, ns3::SatMac::m_readCtrlCallback, and ns3::SatControlMsgTag::SAT_CN0_REPORT.
Referenced by Receive().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-geo-feeder-mac.h
/builds/sns3/satellite/satellite/model/satellite-geo-feeder-mac.cc