SNS3
ns3::SatUtPhy Class Reference
The SatUtPhy models the physical layer of the User Terminal of the satellite system.
#include "satellite-ut-phy.h"
Public Member Functions
SatUtPhy (SatPhy::CreateParam_t &params, Ptr< SatLinkResults > linkResults, SatPhyRxCarrierConf::RxCarrierCreateParams_s parameters, Ptr< SatSuperframeConf > superFrameConf, SatEnums::RegenerationMode_t forwardLinkRegenerationMode)
Constructor.
SatUtPhy (void)
Default constructor, which is not used.
virtual ~SatUtPhy ()
Destructor.
virtual void DoDispose (void)
Dispose of SatUtPhy.
virtual void DoInitialize (void)
Initialization of SatUtPhy.
virtual double GetAdditionalInterference ()
Get additional interference, used to compute final SINR at RX.
TypeId GetInstanceTypeId (void) const
bool IsTxPossible (void) const
Inform whether or not the underlying Tx channel is properly configured for transmission.
void PerformHandover (uint32_t beamId)
Change underlying SatChannel to send and receive data from a new beam.
void Receive (Ptr< SatSignalParameters > rxParams, bool phyError)
Receives packets from lower layer.
void UpdateSliceSubscription (uint8_t slice)
Updates the slices subscription list.
Public Member Functions inherited from ns3::SatPhy
SatPhy (CreateParam_t &params)
Constructor to create PHY objects with parameters.
SatPhy (void)
Default constructor.
virtual ~SatPhy ()
Destructor.
void AverageNormalizedOfferedRandomAccessLoadInfo (uint32_t satId, uint32_t beamId, uint32_t carrierId, uint8_t allocationChannelId, double averageNormalizedOfferedLoad)
Function for getting the normalized offered load of the specific random access allocation channel.
void BeginEndScheduling ()
Begin frame/window end scheduling for processes utilizing frame length as interval.
double CalculateSinr (double sinr, double otherInterference)
Calculate final SINR with PHY specific parameters and given calculated SINR.
void CnoInfo (uint32_t satId, uint32_t beamId, Address source, Address destination, double cno, bool isSatelliteMac)
Function for getting the C/NO information.
void ConfigureRxCarriers (Ptr< SatPhyRxCarrierConf > carrierConf, Ptr< SatSuperframeConf > superFrameConf)
Configure Rx carriers.
double GetDefaultFading () const
Get the default fading of the PHY.
TypeId GetInstanceTypeId (void) const
Derived from Object.
virtual Ptr< SatPhyRx > GetPhyRx () const
Get the SatPhyRx pointer.
virtual Ptr< SatPhyTx > GetPhyTx () const
Get the SatPhyTx pointer.
double GetRxAntennaGainDb () const
Get the maximum antenna gain of the receiver in dB.
double GetRxAntennaLossDb () const
Get the antenna loss of the receiver in dB.
double GetRxNoiseTemperatureDbk () const
Get the noise temperature of the receiver in dbK.
double GetTxAntennaGainDb () const
Get the maximum antenna gain of the transmitter in dB.
double GetTxAntennaLossDb () const
Get the antenna loss of the transmitter in dB.
Ptr< SatChannel > GetTxChannel ()
Get the Tx satellite channel.
double GetTxMaxPowerDbw () const
Get the maximum transmit power of the transmitter in dB.
double GetTxOboLossDb () const
Get the OBO loss of the transmitter in dB.
double GetTxOutputLossDb () const
Get the output loss of the transmitter in dB.
double GetTxPointingLossDb () const
Get the pointing loss of the transmitter in dB.
void Initialize ()
Initialize phy.
virtual void SendPdu (PacketContainer_t, uint32_t carrierId, Time duration, SatSignalParameters::txInfo_s txInfo)
Send Pdu to the PHY tx module (for initial transmissions from either UT or GW)
virtual void SendPduWithParams (Ptr< SatSignalParameters > rxParams)
Send Pdu to the PHY tx module (for GEO satellite switch packet forwarding)
void SetBeamId (uint32_t beamId)
Set the beamId this PHY is connected with.
void SetChannelPairGetterCallback (SatPhy::ChannelPairGetterCallback cb)
Set the channel pair getter callback.
void SetDefaultFading (double fading)
Set the default fading of the PHY.
void SetNodeInfo (const Ptr< SatNodeInfo > nodeInfo)
Set the node info class.
virtual void SetPhyRx (Ptr< SatPhyRx > phyRx)
Set the SatPhyRx module.
virtual void SetPhyTx (Ptr< SatPhyTx > phyTx)
Set the SatPhyTx module.
void SetRxAntennaGainDb (double gainDb)
Set the maximum antenna gain of the receiver in dB.
virtual void SetRxAntennaGainPattern (Ptr< SatAntennaGainPattern > agp, Ptr< SatMobilityModel > satelliteMobility)
Set the receive antenna gain pattern.
void SetRxAntennaLossDb (double lossDb)
Set the antenna loss of the receiver in dB.
void SetRxFadingContainer (Ptr< SatBaseFading > fadingContainer)
Set fading container.
void SetRxNoiseTemperatureDbk (double temperatureDbk)
Set the noise temperature of the receiver in dbK.
void SetSatId (uint32_t satId)
Set the satId this PHY is connected with.
void SetTxAntennaGainDb (double gainDb)
Set the maximum antenna gain of the transmitter in dB.
virtual void SetTxAntennaGainPattern (Ptr< SatAntennaGainPattern > agp, Ptr< SatMobilityModel > satelliteMobility)
Set the transmit antenna gain pattern.
void SetTxAntennaLossDb (double lossDb)
Set the antenna loss of the transmitter in dB.
void SetTxFadingContainer (Ptr< SatBaseFading > fadingContainer)
Set fading container.
void SetTxMaxPowerDbw (double powerDb)
Set the maximum transmit power of the transmitter in dB.
void SetTxOboLossDb (double lossDb)
Set the OBO loss of the transmitter in dB.
void SetTxOutputLossDb (double lossDb)
Set the output loss of the transmitter in dB.
void SetTxPointingLossDb (double lossDb)
Set the pointing loss of the transmitter in dB.
Static Public Member Functions
static TypeId GetTypeId (void)
inherited from Object
Static Public Member Functions inherited from ns3::SatPhy
static TypeId GetTypeId (void)
Derived from Object.
Private Member Functions
void AssignNewSatChannels ()
Update the underlying SatChannel to send and receive data from the current beam (as described in the m_beamId attribute).
virtual SatEnums::SatLinkDir_t GetSatLinkRxDir ()
Get the link RX direction.
virtual SatEnums::SatLinkDir_t GetSatLinkTxDir ()
Get the link TX direction.
Private Attributes
Time m_antennaReconfigurationDelay
Delay of antenna reconfiguration when performing handover.
double m_otherSysInterferenceCOverI
Other system interference in linear.
double m_otherSysInterferenceCOverIDb
Configured other system interference in dB.
std::set< uint8_t > m_slicesSubscribed
The list of slices subscribed for this UT.
Additional Inherited Members
Public Types inherited from ns3::SatPhy
typedef Callback< void, uint32_t, uint32_t, uint32_t, uint8_t, double > AverageNormalizedOfferedLoadCallback
typedef Callback< SatChannelPair::ChannelPair_t, uint32_t, uint32_t > ChannelPairGetterCallback
Callback for retrieving a pair of SatChannel associated to a beam.
typedef Callback< void, uint32_t, uint32_t, Address, Address, double, bool > CnoCallback
typedef SatPhyRxCarrierConf::ErrorModel ErrorModel
Define ErrorModel in SatPhy.
typedef SatPhyRxCarrierConf::InterferenceEliminationModel InterferenceEliminationModel
Define InterferenceEliminationModel in SatPhy.
typedef SatPhyRxCarrierConf::InterferenceModel InterferenceModel
Define InterferenceModel in SatPhy.
typedef SatSignalParameters::PacketsInBurst_t PacketContainer_t
Define PacketContainer in SatPhy.
typedef Callback< void, PacketContainer_t, Ptr< SatSignalParameters > > ReceiveCallback
Protected Member Functions inherited from ns3::SatPhy
void ModcodTrace (Ptr< SatSignalParameters > rxParams)
Invoke the RxLinkModcod trace source for each received packet.
virtual void RxTraces (SatPhy::PacketContainer_t packets)
Invoke the Rx trace source for each received packet.
void SetTimeTag (SatPhy::PacketContainer_t packets)
Set SatPhyTimeTag of packets.
Protected Attributes inherited from ns3::SatPhy
uint32_t m_beamId
Beam ID.
double m_eirpWoGainW
Calculated EIRP without gain in W.
bool m_isStatisticsTagsEnabled
EnableStatisticsTags attribute.
Time m_lastDelay
Last delay measurement.
Time m_lastLinkDelay
Last delay measurement for link.
Ptr< SatNodeInfo > m_nodeInfo
Node info containing node related information, such as node type, node id and MAC address (of the SatNetDevice)
TracedCallback< Time, SatEnums::SatPacketEvent_t, SatEnums::SatNodeType_t, uint32_t, Mac48Address, SatEnums::SatLogLevel_t, SatEnums::SatLinkDir_t, std::string > m_packetTrace
Trace callback used for packet tracing:
Ptr< SatPhyRx > m_phyRx
Pointer to internal SatPhyRx instance.
Ptr< SatPhyTx > m_phyTx
Pointer to internal SatPhyTx instance.
SatPhy::ChannelPairGetterCallback m_retrieveChannelPair
Callback for retrieving SatChannel pairs by beam.
SatPhy::ReceiveCallback m_rxCallback
The upper layer package receive callback.
TracedCallback< const Time &, const Address & > m_rxDelayTrace
Traced callback for all received packets, including delay information and the address of the senders.
TracedCallback< const Time &, const Address & > m_rxJitterTrace
Traced callback for all received packets, including jitter information and the address of the senders.
TracedCallback< const Time &, const Address & > m_rxLinkDelayTrace
Traced callback for all received packets, including link delay information and the address of the senders.
TracedCallback< const Time &, const Address & > m_rxLinkJitterTrace
Traced callback for all received packets, including link jitter information and the address of the senders.
TracedCallback< uint32_t, const Address & > m_rxLinkModcodTrace
Traced callback for all received packets, including link MODCOD information and the address of the senders.
TracedCallback< Ptr< const Packet >, const Address & > m_rxTrace
Traced callback for all received packets, including the address of the senders.
uint32_t m_satId
Satellite ID.
Detailed Description
The SatUtPhy models the physical layer of the User Terminal of the satellite system.
Definition at line 51 of file satellite-ut-phy.h.
Constructor & Destructor Documentation
SatUtPhy() [1/2]
ns3::SatUtPhy::SatUtPhy (void)
Default constructor, which is not used.
Definition at line 140 of file satellite-ut-phy.cc.
SatUtPhy() [2/2]
ns3::SatUtPhy::SatUtPhy (SatPhy::CreateParam_t & params, Ptr< SatLinkResults > linkResults, SatPhyRxCarrierConf::RxCarrierCreateParams_s parameters, Ptr< SatSuperframeConf > superFrameConf, SatEnums::RegenerationMode_t forwardLinkRegenerationMode)
Constructor.
Parameters
params Creation parameters
linkResults Link results
parameters Rx carrier creation parameters
superFrameConf Superframe configuration
Definition at line 149 of file satellite-ut-phy.cc.
References ns3::SatPhy::ConfigureRxCarriers(), ns3::SatUtils::DbToLinear(), ns3::SatEnums::FORWARD_USER_CH, GetAdditionalInterference(), ns3::SatPhy::GetRxNoiseTemperatureDbk(), m_otherSysInterferenceCOverI, m_otherSysInterferenceCOverIDb, and ns3::SatPhyRxCarrierConf::NORMAL.
~SatUtPhy()
ns3::SatUtPhy::~SatUtPhy () virtual
Destructor.
Definition at line 183 of file satellite-ut-phy.cc.
Member Function Documentation
AssignNewSatChannels()
void ns3::SatUtPhy::AssignNewSatChannels () private
Update the underlying SatChannel to send and receive data from the current beam (as described in the m_beamId attribute).
Definition at line 226 of file satellite-ut-phy.cc.
References ns3::SatPhy::m_beamId, ns3::SatPhy::m_phyRx, ns3::SatPhy::m_phyTx, ns3::SatPhy::m_retrieveChannelPair, and ns3::SatPhy::m_satId.
Referenced by PerformHandover().
DoDispose()
void ns3::SatUtPhy::DoDispose (void) virtual
Dispose of SatUtPhy.
Reimplemented from ns3::SatPhy.
Definition at line 189 of file satellite-ut-phy.cc.
DoInitialize()
void ns3::SatUtPhy::DoInitialize (void) virtual
Initialization of SatUtPhy.
Reimplemented from ns3::SatPhy.
Definition at line 196 of file satellite-ut-phy.cc.
GetAdditionalInterference()
double ns3::SatUtPhy::GetAdditionalInterference (void) virtual
Get additional interference, used to compute final SINR at RX.
Returns
Additional interference
Implements ns3::SatPhy.
Definition at line 203 of file satellite-ut-phy.cc.
References m_otherSysInterferenceCOverI.
Referenced by SatUtPhy().
GetInstanceTypeId()
TypeId ns3::SatUtPhy::GetInstanceTypeId (void) const
Definition at line 134 of file satellite-ut-phy.cc.
References GetTypeId().
GetSatLinkRxDir()
SatEnums::SatLinkDir_t ns3::SatUtPhy::GetSatLinkRxDir () private virtual
Get the link RX direction.
Must be implemented by child clases.
Returns
The link RX direction
Reimplemented from ns3::SatPhy.
Definition at line 248 of file satellite-ut-phy.cc.
References ns3::SatEnums::LD_FORWARD.
GetSatLinkTxDir()
SatEnums::SatLinkDir_t ns3::SatUtPhy::GetSatLinkTxDir () private virtual
Get the link TX direction.
Must be implemented by child clases.
Returns
The link TX direction
Reimplemented from ns3::SatPhy.
Definition at line 242 of file satellite-ut-phy.cc.
References ns3::SatEnums::LD_RETURN.
GetTypeId()
TypeId ns3::SatUtPhy::GetTypeId (void) static
inherited from Object
Definition at line 47 of file satellite-ut-phy.cc.
References ns3::SatPhy::GetDefaultFading(), ns3::SatPhy::GetPhyRx(), ns3::SatPhy::GetPhyTx(), ns3::SatPhy::GetRxAntennaGainDb(), ns3::SatPhy::GetRxAntennaLossDb(), ns3::SatPhy::GetRxNoiseTemperatureDbk(), ns3::SatPhy::GetTxAntennaGainDb(), ns3::SatPhy::GetTxAntennaLossDb(), ns3::SatPhy::GetTxMaxPowerDbw(), ns3::SatPhy::GetTxOboLossDb(), ns3::SatPhy::GetTxOutputLossDb(), ns3::SatPhy::GetTxPointingLossDb(), m_antennaReconfigurationDelay, m_otherSysInterferenceCOverIDb, ns3::SatPhy::SetDefaultFading(), ns3::SatPhy::SetPhyRx(), ns3::SatPhy::SetPhyTx(), ns3::SatPhy::SetRxAntennaGainDb(), ns3::SatPhy::SetRxAntennaLossDb(), ns3::SatPhy::SetRxNoiseTemperatureDbk(), ns3::SatPhy::SetTxAntennaGainDb(), ns3::SatPhy::SetTxAntennaLossDb(), ns3::SatPhy::SetTxMaxPowerDbw(), ns3::SatPhy::SetTxOboLossDb(), ns3::SatPhy::SetTxOutputLossDb(), and ns3::SatPhy::SetTxPointingLossDb().
Referenced by GetInstanceTypeId().
IsTxPossible()
bool ns3::SatUtPhy::IsTxPossible (void) const
Inform whether or not the underlying Tx channel is properly configured for transmission.
Definition at line 254 of file satellite-ut-phy.cc.
References ns3::SatPhy::m_phyTx.
Referenced by ns3::SatUtHelper::InstallDvb().
PerformHandover()
void ns3::SatUtPhy::PerformHandover (uint32_t beamId)
Change underlying SatChannel to send and receive data from a new beam.
Parameters
beamId the new beam to listen/send to
Definition at line 211 of file satellite-ut-phy.cc.
References AssignNewSatChannels(), m_antennaReconfigurationDelay, ns3::SatPhy::m_beamId, ns3::SatPhy::m_phyRx, ns3::SatPhy::m_phyTx, ns3::SatPhy::m_retrieveChannelPair, ns3::SatPhy::m_satId, and ns3::SatPhy::SetBeamId().
Referenced by ns3::SatUtHelper::InstallDvb().
Receive()
void ns3::SatUtPhy::Receive (Ptr< SatSignalParameters > rxParams, bool phyError) virtual
Receives packets from lower layer.
Parameters
rxParams Packet reception parameters
phyError Boolean indicating whether the packet successfully received or not?
Reimplemented from ns3::SatPhy.
Definition at line 261 of file satellite-ut-phy.cc.
References ns3::SatEnums::DUMMY_FRAME, m_slicesSubscribed, and ns3::SatPhy::Receive().
UpdateSliceSubscription()
void ns3::SatUtPhy::UpdateSliceSubscription (uint8_t slice)
Updates the slices subscription list.
Parameters
slice The new slice to subscribe. If zero, reset the subscription list (except slice zero used for control messages).
Definition at line 285 of file satellite-ut-phy.cc.
References m_slicesSubscribed.
Referenced by ns3::SatUtHelper::InstallDvb().
Member Data Documentation
m_antennaReconfigurationDelay
Time ns3::SatUtPhy::m_antennaReconfigurationDelay private
Delay of antenna reconfiguration when performing handover.
Definition at line 158 of file satellite-ut-phy.h.
Referenced by GetTypeId(), and PerformHandover().
m_otherSysInterferenceCOverI
double ns3::SatUtPhy::m_otherSysInterferenceCOverI private
Other system interference in linear.
Definition at line 153 of file satellite-ut-phy.h.
Referenced by SatUtPhy(), and GetAdditionalInterference().
m_otherSysInterferenceCOverIDb
double ns3::SatUtPhy::m_otherSysInterferenceCOverIDb private
Configured other system interference in dB.
Definition at line 148 of file satellite-ut-phy.h.
Referenced by SatUtPhy(), and GetTypeId().
m_slicesSubscribed
std::set<uint8_t> ns3::SatUtPhy::m_slicesSubscribed private
The list of slices subscribed for this UT.
Definition at line 163 of file satellite-ut-phy.h.
Referenced by Receive(), and UpdateSliceSubscription().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-ut-phy.h
/builds/sns3/satellite/satellite/model/satellite-ut-phy.cc