SNS3
ns3::SatConstantInterference Class Reference
Satellite constant interference.
#include "satellite-constant-interference.h"
Public Member Functions
SatConstantInterference ()
Default constructor.
~SatConstantInterference ()
Destructor for SatConstantInterference.
TypeId GetInstanceTypeId (void) const
Public Member Functions inherited from ns3::SatInterference
SatInterference ()
Constructor for Satellite interference base class.
~SatInterference ()
Destructor for Satellite interference base class.
Ptr< SatInterference::InterferenceChangeEvent > Add (Time rxDuration, double rxPower, Address rxAddress)
Adds interference power to interference object.
std::vector< std::pair< double, double > > Calculate (Ptr< SatInterference::InterferenceChangeEvent > event)
Calculates interference power for the given reference.
TypeId GetInstanceTypeId (void) const
Derived from Object.
virtual bool HasCollision (Ptr< SatInterference::InterferenceChangeEvent > event)
Checks whether the packet has collided.
virtual void NotifyRxEnd (Ptr< SatInterference::InterferenceChangeEvent > event)
Notifies that RX is ended by a receiver.
virtual void NotifyRxStart (Ptr< SatInterference::InterferenceChangeEvent > event)
Notifies that RX is started by a receiver.
void Reset (void)
Resets current interference.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::SatInterference
static TypeId GetTypeId (void)
Derived from Object.
Private Member Functions
SatConstantInterference (const SatConstantInterference &o)
virtual Ptr< SatInterference::InterferenceChangeEvent > DoAdd (Time rxDuration, double rxPower, Address rxAddress)
Adds interference power to interference object.
virtual std::vector< std::pair< double, double > > DoCalculate (Ptr< SatInterference::InterferenceChangeEvent > event)
Calculates interference power for the given reference Sets final power at end time to finalPower.
virtual void DoNotifyRxEnd (Ptr< SatInterference::InterferenceChangeEvent > event)
Notifies that RX is ended by a receiver.
virtual void DoNotifyRxStart (Ptr< SatInterference::InterferenceChangeEvent > event)
Notifies that RX is started by a receiver.
virtual void DoReset (void)
Resets current interference.
SatConstantInterference & operator= (const SatConstantInterference &o)
Private Attributes
double m_power
bool m_rxing
Detailed Description
Satellite constant interference.
Interference is constant until set again by an attribute.
Definition at line 36 of file satellite-constant-interference.h.
Constructor & Destructor Documentation
SatConstantInterference() [1/2]
ns3::SatConstantInterference::SatConstantInterference ()
Default constructor.
Definition at line 56 of file satellite-constant-interference.cc.
~SatConstantInterference()
ns3::SatConstantInterference::~SatConstantInterference ()
Destructor for SatConstantInterference.
Definition at line 62 of file satellite-constant-interference.cc.
References ns3::SatInterference::Reset().
SatConstantInterference() [2/2]
ns3::SatConstantInterference::SatConstantInterference (const SatConstantInterference & o) private
Member Function Documentation
DoAdd()
Ptr< SatInterference::InterferenceChangeEvent > ns3::SatConstantInterference::DoAdd (Time rxDuration, double rxPower, Address rxAddress) private virtual
Adds interference power to interference object.
No effect in this implementation.
Parameters
rxDuration Duration of the receiving.
rxPower Receiving power.
rxAddress
Returns
the pointer to interference event as a reference of the addition
Implements ns3::SatInterference.
Definition at line 68 of file satellite-constant-interference.cc.
DoCalculate()
std::vector< std::pair< double, double > > ns3::SatConstantInterference::DoCalculate (Ptr< SatInterference::InterferenceChangeEvent > event) private virtual
Calculates interference power for the given reference Sets final power at end time to finalPower.
Just return constant value set by Set method in this implementation. finalPower is set to returned value.
Parameters
event Reference event which for interference is calculated.
Returns
Final power value at end of receiving
Implements ns3::SatInterference.
Definition at line 79 of file satellite-constant-interference.cc.
References m_power, and m_rxing.
DoNotifyRxEnd()
void ns3::SatConstantInterference::DoNotifyRxEnd (Ptr< SatInterference::InterferenceChangeEvent > event) private virtual
Notifies that RX is ended by a receiver.
Parameters
event Interference reference event of receiver (ignored in this implementation)
Implements ns3::SatInterference.
Definition at line 112 of file satellite-constant-interference.cc.
References m_rxing.
DoNotifyRxStart()
void ns3::SatConstantInterference::DoNotifyRxStart (Ptr< SatInterference::InterferenceChangeEvent > event) private virtual
Notifies that RX is started by a receiver.
Parameters
event Interference reference event of receiver (ignored in this implementation)
Implements ns3::SatInterference.
Definition at line 104 of file satellite-constant-interference.cc.
References m_rxing.
DoReset()
void ns3::SatConstantInterference::DoReset (void) private virtual
Resets current interference.
Implements ns3::SatInterference.
Definition at line 96 of file satellite-constant-interference.cc.
References m_rxing.
GetInstanceTypeId()
TypeId ns3::SatConstantInterference::GetInstanceTypeId (void) const
Definition at line 51 of file satellite-constant-interference.cc.
References GetTypeId().
GetTypeId()
TypeId ns3::SatConstantInterference::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 37 of file satellite-constant-interference.cc.
References m_power.
Referenced by GetInstanceTypeId().
operator=()
SatConstantInterference& ns3::SatConstantInterference::operator= (const SatConstantInterference & o) private
Member Data Documentation
m_power
double ns3::SatConstantInterference::m_power private
Definition at line 109 of file satellite-constant-interference.h.
Referenced by DoCalculate(), and GetTypeId().
m_rxing
bool ns3::SatConstantInterference::m_rxing private
Definition at line 114 of file satellite-constant-interference.h.
Referenced by DoCalculate(), DoNotifyRxEnd(), DoNotifyRxStart(), and DoReset().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-constant-interference.h
/builds/sns3/satellite/satellite/model/satellite-constant-interference.cc