SNS3
ns3::LoraNetworkServerHelper Class Reference
This class can install Network Server applications on multiple nodes at once.
#include "lora-network-server-helper.h"
Public Member Functions
LoraNetworkServerHelper ()
~LoraNetworkServerHelper ()
void EnableAdr (bool enableAdr)
Enable (true) or disable (false) the ADR component in the Network Server created by this helper.
ApplicationContainer Install (NodeContainer c)
ApplicationContainer Install (Ptr< Node > node)
void SetAdr (std::string type)
Set the ADR implementation to use in the Network Server created by this helper.
void SetAttribute (std::string name, const AttributeValue &value)
void SetEndDevices (NodeContainer endDevices)
Set which end devices will be managed by this NS.
void SetGateways (NodeContainer gateways)
Set which gateways will need to be connected to this NS.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void InstallComponents (Ptr< LoraNetworkServer > netServer)
Ptr< Application > InstallPriv (Ptr< Node > node)
Private Attributes
bool m_adrEnabled
ObjectFactory m_adrSupportFactory
NodeContainer m_endDevices
Set of endDevices to connect to this NS.
ObjectFactory m_factory
NodeContainer m_gateways
Set of gateways to connect to this NS.
PointToPointHelper p2pHelper
Helper to create PointToPoint links.
Detailed Description
This class can install Network Server applications on multiple nodes at once.
Definition at line 44 of file lora-network-server-helper.h.
Constructor & Destructor Documentation
LoraNetworkServerHelper()
ns3::LoraNetworkServerHelper::LoraNetworkServerHelper ()
Definition at line 50 of file lora-network-server-helper.cc.
References m_factory, p2pHelper, and SetAdr().
~LoraNetworkServerHelper()
ns3::LoraNetworkServerHelper::~LoraNetworkServerHelper ()
Definition at line 58 of file lora-network-server-helper.cc.
Member Function Documentation
EnableAdr()
void ns3::LoraNetworkServerHelper::EnableAdr (bool enableAdr)
Enable (true) or disable (false) the ADR component in the Network Server created by this helper.
Definition at line 136 of file lora-network-server-helper.cc.
References m_adrEnabled.
GetTypeId()
TypeId ns3::LoraNetworkServerHelper::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 42 of file lora-network-server-helper.cc.
Install() [1/2]
ApplicationContainer ns3::LoraNetworkServerHelper::Install (NodeContainer c)
Definition at line 87 of file lora-network-server-helper.cc.
References InstallPriv().
Install() [2/2]
ApplicationContainer ns3::LoraNetworkServerHelper::Install (Ptr< Node > node)
Definition at line 81 of file lora-network-server-helper.cc.
References InstallPriv().
InstallComponents()
void ns3::LoraNetworkServerHelper::InstallComponents (Ptr< LoraNetworkServer > netServer) private
Definition at line 153 of file lora-network-server-helper.cc.
References m_adrEnabled, and m_adrSupportFactory.
Referenced by InstallPriv().
InstallPriv()
Ptr< Application > ns3::LoraNetworkServerHelper::InstallPriv (Ptr< Node > node) private
Definition at line 99 of file lora-network-server-helper.cc.
References InstallComponents(), m_endDevices, m_factory, m_gateways, p2pHelper, and ns3::LoraNetworkServer::Receive().
Referenced by Install().
SetAdr()
void ns3::LoraNetworkServerHelper::SetAdr (std::string type)
Set the ADR implementation to use in the Network Server created by this helper.
Definition at line 144 of file lora-network-server-helper.cc.
References m_adrSupportFactory.
Referenced by LoraNetworkServerHelper().
SetAttribute()
void ns3::LoraNetworkServerHelper::SetAttribute (std::string name, const AttributeValue & value)
Definition at line 63 of file lora-network-server-helper.cc.
References m_factory.
SetEndDevices()
void ns3::LoraNetworkServerHelper::SetEndDevices (NodeContainer endDevices)
Set which end devices will be managed by this NS.
Definition at line 75 of file lora-network-server-helper.cc.
References m_endDevices.
SetGateways()
void ns3::LoraNetworkServerHelper::SetGateways (NodeContainer gateways)
Set which gateways will need to be connected to this NS.
Definition at line 69 of file lora-network-server-helper.cc.
References m_gateways.
Member Data Documentation
m_adrEnabled
bool ns3::LoraNetworkServerHelper::m_adrEnabled private
Definition at line 97 of file lora-network-server-helper.h.
Referenced by EnableAdr(), and InstallComponents().
m_adrSupportFactory
ObjectFactory ns3::LoraNetworkServerHelper::m_adrSupportFactory private
Definition at line 99 of file lora-network-server-helper.h.
Referenced by InstallComponents(), and SetAdr().
m_endDevices
NodeContainer ns3::LoraNetworkServerHelper::m_endDevices private
Set of endDevices to connect to this NS.
Definition at line 93 of file lora-network-server-helper.h.
Referenced by InstallPriv(), and SetEndDevices().
m_factory
ObjectFactory ns3::LoraNetworkServerHelper::m_factory private
Definition at line 89 of file lora-network-server-helper.h.
Referenced by LoraNetworkServerHelper(), InstallPriv(), and SetAttribute().
m_gateways
NodeContainer ns3::LoraNetworkServerHelper::m_gateways private
Set of gateways to connect to this NS.
Definition at line 91 of file lora-network-server-helper.h.
Referenced by InstallPriv(), and SetGateways().
p2pHelper
PointToPointHelper ns3::LoraNetworkServerHelper::p2pHelper private
Helper to create PointToPoint links.
Definition at line 95 of file lora-network-server-helper.h.
Referenced by LoraNetworkServerHelper(), and InstallPriv().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/helper/lora-network-server-helper.h
/builds/sns3/satellite/satellite/helper/lora-network-server-helper.cc