SNS3
ns3::PointToPointIslNetDevice Class Reference
#include "satellite-point-to-point-isl-net-device.h"
Public Member Functions
PointToPointIslNetDevice ()
Construct a PointToPointIslNetDevice.
virtual ~PointToPointIslNetDevice ()
Destroy a PointToPointIslNetDevice.
virtual void AddLinkChangeCallback (Callback< void > callback)
bool Attach (Ptr< PointToPointIslChannel > ch)
Attach the device to a channel.
virtual Address GetAddress (void) const
virtual Address GetBroadcast (void) const
virtual Ptr< Channel > GetChannel (void) const
virtual Ptr< Node > GetDestinationNode (void) const
virtual uint32_t GetIfIndex (void) const
virtual uint16_t GetMtu (void) const
virtual Address GetMulticast (Ipv4Address multicastGroup) const
virtual Address GetMulticast (Ipv6Address addr) const
virtual Ptr< Node > GetNode (void) const
Ptr< DropTailQueue< Packet > > GetQueue (void) const
Get a copy of the attached Queue.
virtual bool IsBridge (void) const
virtual bool IsBroadcast (void) const
virtual bool IsLinkUp (void) const
virtual bool IsMulticast (void) const
virtual bool IsPointToPoint (void) const
virtual bool NeedsArp (void) const
void Receive (Ptr< Packet > p)
Receive a packet from a connected PointToPointIslChannel.
virtual bool Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber)
virtual bool SendFrom (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)
virtual void SetAddress (Address address)
void SetDataRate (DataRate bps)
Set the Data Rate used for transmission of packets.
virtual void SetDestinationNode (Ptr< Node > node)
void SetGeoNetDevice (Ptr< SatGeoNetDevice > geoNetDevice)
Set the associated GeoNetDevice.
virtual void SetIfIndex (const uint32_t index)
void SetInterframeGap (Time t)
Set the interframe gap used to separate packets.
virtual bool SetMtu (const uint16_t mtu)
virtual void SetNode (Ptr< Node > node)
virtual void SetPromiscReceiveCallback (PromiscReceiveCallback cb)
void SetQueue (Ptr< DropTailQueue< Packet >> queue)
Attach a queue to the PointToPointIslNetDevice.
virtual void SetReceiveCallback (NetDevice::ReceiveCallback cb)
void SetReceiveErrorModel (Ptr< ErrorModel > em)
Attach a receive ErrorModel to the PointToPointIslNetDevice.
virtual bool SupportsSendFrom (void) const
Static Public Member Functions
static TypeId GetTypeId (void)
Get the TypeId.
Private Types
enum TxMachineState { READY , BUSY }
Enumeration of the states of the transmit machine of the net device.
Private Member Functions
PointToPointIslNetDevice (const PointToPointIslNetDevice &o)
Copy constructor.
void AddHeader (Ptr< Packet > p, uint16_t protocolNumber)
Adds the necessary headers and trailers to a packet of data in order to respect the protocol implemented by the agent.
virtual void DoDispose (void)
Dispose of the object.
Address GetRemote (void) const
void NotifyLinkUp (void)
Make the link up and running.
PointToPointIslNetDevice & operator= (const PointToPointIslNetDevice &o)
Assign operator.
bool ProcessHeader (Ptr< Packet > p, uint16_t &param)
Removes, from a packet of data, all headers and trailers that relate to the protocol implemented by the agent.
void TransmitComplete (void)
Stop Sending a Packet Down the Wire and Begin the Interframe Gap.
bool TransmitStart (Ptr< Packet > p)
Start Sending a Packet Down the Wire.
Static Private Member Functions
static uint16_t EtherToPpp (uint16_t protocol)
Ethernet to PPP protocol number mapping.
static uint16_t PppToEther (uint16_t protocol)
PPP to Ethernet protocol number mapping.
Private Attributes
Mac48Address m_address
Mac48Address of this NetDevice.
Ptr< PointToPointIslChannel > m_channel
The PointToPointIslChannel to which this PointToPointIslNetDevice has been attached.
Ptr< Packet > m_currentPkt
Current packet processed.
DataRate m_dataRate
The data rate that the Net Device uses to simulate packet transmission timing.
Ptr< Node > m_destinationNode
Node at the other end of the p2pIslLink.
Ptr< SatGeoNetDevice > m_geoNetDevice
Satellite GEO Net Device associated to this instance.
uint32_t m_ifIndex
Index of the interface.
bool m_linkUp
Identify if the link is up or not.
uint32_t m_mtu
The Maximum Transmission Unit.
Ptr< Node > m_node
Node owning this NetDevice.
TracedCallback< uint32_t, Ptr< Node >, Ptr< Node >, bool > m_packetDropRateTrace
Traced callback for drop rate in queue.
NetDevice::PromiscReceiveCallback m_promiscCallback
Receive callback.
Ptr< DropTailQueue< Packet > > m_queue
The Queue which this PointToPointIslNetDevice uses as a packet source.
Ptr< ErrorModel > m_receiveErrorModel
Error model for receive packet events.
NetDevice::ReceiveCallback m_rxCallback
Receive callback.
Time m_tInterframeGap
The interframe gap that the Net Device uses to throttle packet transmission.
TxMachineState m_txMachineState
The state of the Net Device transmit state machine.
Static Private Attributes
static const uint16_t DEFAULT_MTU = 1500
Default MTU.
Detailed Description
Definition at line 64 of file satellite-point-to-point-isl-net-device.h.
Member Enumeration Documentation
TxMachineState
enum ns3::PointToPointIslNetDevice::TxMachineState private
Enumeration of the states of the transmit machine of the net device.
Enumerator
READY
The transmitter is ready to begin transmission of a packet.
BUSY
The transmitter is busy transmitting a packet.
Definition at line 289 of file satellite-point-to-point-isl-net-device.h.
Constructor & Destructor Documentation
PointToPointIslNetDevice() [1/2]
ns3::PointToPointIslNetDevice::PointToPointIslNetDevice ()
Construct a PointToPointIslNetDevice.
This is the constructor for the PointToPointIslNetDevice
Definition at line 71 of file satellite-point-to-point-isl-net-device.cc.
~PointToPointIslNetDevice()
ns3::PointToPointIslNetDevice::~PointToPointIslNetDevice () virtual
Destroy a PointToPointIslNetDevice.
This is the destructor for the PointToPointIslNetDevice.
Definition at line 80 of file satellite-point-to-point-isl-net-device.cc.
PointToPointIslNetDevice() [2/2]
ns3::PointToPointIslNetDevice::PointToPointIslNetDevice (const PointToPointIslNetDevice & o) private
Copy constructor.
The method is private, so it is DISABLED.
Parameters
o Other NetDevice
Member Function Documentation
AddHeader()
void ns3::PointToPointIslNetDevice::AddHeader (Ptr< Packet > p, uint16_t protocolNumber) private
Adds the necessary headers and trailers to a packet of data in order to respect the protocol implemented by the agent.
Parameters
p packet
protocolNumber protocol number
Definition at line 86 of file satellite-point-to-point-isl-net-device.cc.
References EtherToPpp().
Referenced by Send().
AddLinkChangeCallback()
void ns3::PointToPointIslNetDevice::AddLinkChangeCallback (Callback< void > callback) virtual
Definition at line 334 of file satellite-point-to-point-isl-net-device.cc.
Attach()
bool ns3::PointToPointIslNetDevice::Attach (Ptr< PointToPointIslChannel > ch)
Attach the device to a channel.
Parameters
ch Ptr to the channel to which this object is being attached.
Returns
true if the operation was successful (always true actually)
Definition at line 185 of file satellite-point-to-point-isl-net-device.cc.
References m_channel, and NotifyLinkUp().
DoDispose()
void ns3::PointToPointIslNetDevice::DoDispose (void) private virtual
Dispose of the object.
Definition at line 105 of file satellite-point-to-point-isl-net-device.cc.
References m_channel, m_currentPkt, m_node, m_queue, and m_receiveErrorModel.
EtherToPpp()
uint16_t ns3::PointToPointIslNetDevice::EtherToPpp (uint16_t protocol) static private
Ethernet to PPP protocol number mapping.
Parameters
protocol An Ethernet protocol number
Returns
The corresponding PPP protocol number
Definition at line 535 of file satellite-point-to-point-isl-net-device.cc.
Referenced by AddHeader().
GetAddress()
Address ns3::PointToPointIslNetDevice::GetAddress (void) const virtual
Definition at line 308 of file satellite-point-to-point-isl-net-device.cc.
References m_address.
Referenced by Receive().
GetBroadcast()
Address ns3::PointToPointIslNetDevice::GetBroadcast (void) const virtual
Definition at line 356 of file satellite-point-to-point-isl-net-device.cc.
GetChannel()
Ptr< Channel > ns3::PointToPointIslNetDevice::GetChannel (void) const virtual
Definition at line 289 of file satellite-point-to-point-isl-net-device.cc.
References m_channel.
GetDestinationNode()
Ptr< Node > ns3::PointToPointIslNetDevice::GetDestinationNode (void) const virtual
Definition at line 321 of file satellite-point-to-point-isl-net-device.cc.
References m_destinationNode.
GetIfIndex()
uint32_t ns3::PointToPointIslNetDevice::GetIfIndex (void) const virtual
Definition at line 283 of file satellite-point-to-point-isl-net-device.cc.
References m_ifIndex.
GetMtu()
uint16_t ns3::PointToPointIslNetDevice::GetMtu (void) const virtual
Definition at line 512 of file satellite-point-to-point-isl-net-device.cc.
References m_mtu.
GetMulticast() [1/2]
Address ns3::PointToPointIslNetDevice::GetMulticast (Ipv4Address multicastGroup) const virtual
Definition at line 370 of file satellite-point-to-point-isl-net-device.cc.
GetMulticast() [2/2]
Address ns3::PointToPointIslNetDevice::GetMulticast (Ipv6Address addr) const virtual
Definition at line 377 of file satellite-point-to-point-isl-net-device.cc.
GetNode()
Ptr< Node > ns3::PointToPointIslNetDevice::GetNode (void) const virtual
Definition at line 447 of file satellite-point-to-point-isl-net-device.cc.
References m_node.
GetQueue()
Ptr< DropTailQueue< Packet > > ns3::PointToPointIslNetDevice::GetQueue (void) const
Get a copy of the attached Queue.
Returns
Ptr to the queue.
Definition at line 262 of file satellite-point-to-point-isl-net-device.cc.
References m_queue.
GetRemote()
Address ns3::PointToPointIslNetDevice::GetRemote (void) const private
Returns
the address of the remote device connected to this device through the point to point channel.
Definition at line 486 of file satellite-point-to-point-isl-net-device.cc.
References m_channel.
Referenced by Receive().
GetTypeId()
TypeId ns3::PointToPointIslNetDevice::GetTypeId (void) static
Get the TypeId.
Returns
The TypeId for this class
Definition at line 47 of file satellite-point-to-point-isl-net-device.cc.
References m_packetDropRateTrace, m_receiveErrorModel, and m_tInterframeGap.
IsBridge()
bool ns3::PointToPointIslNetDevice::IsBridge (void) const virtual
Definition at line 391 of file satellite-point-to-point-isl-net-device.cc.
IsBroadcast()
bool ns3::PointToPointIslNetDevice::IsBroadcast (void) const virtual
Definition at line 344 of file satellite-point-to-point-isl-net-device.cc.
IsLinkUp()
bool ns3::PointToPointIslNetDevice::IsLinkUp (void) const virtual
Definition at line 327 of file satellite-point-to-point-isl-net-device.cc.
References m_linkUp.
Referenced by Send().
IsMulticast()
bool ns3::PointToPointIslNetDevice::IsMulticast (void) const virtual
Definition at line 363 of file satellite-point-to-point-isl-net-device.cc.
IsPointToPoint()
bool ns3::PointToPointIslNetDevice::IsPointToPoint (void) const virtual
Definition at line 384 of file satellite-point-to-point-isl-net-device.cc.
NeedsArp()
bool ns3::PointToPointIslNetDevice::NeedsArp (void) const virtual
Definition at line 460 of file satellite-point-to-point-isl-net-device.cc.
NotifyLinkUp()
void ns3::PointToPointIslNetDevice::NotifyLinkUp (void) private
Make the link up and running.
It calls also the linkChange callback.
Definition at line 269 of file satellite-point-to-point-isl-net-device.cc.
References m_linkUp.
Referenced by Attach().
operator=()
PointToPointIslNetDevice& ns3::PointToPointIslNetDevice::operator= (const PointToPointIslNetDevice & o) private
Assign operator.
The method is private, so it is DISABLED.
Parameters
o Other NetDevice
Returns
New instance of the NetDevice
PppToEther()
uint16_t ns3::PointToPointIslNetDevice::PppToEther (uint16_t protocol) static private
PPP to Ethernet protocol number mapping.
Parameters
protocol A PPP protocol number
Returns
The corresponding Ethernet protocol number
Definition at line 519 of file satellite-point-to-point-isl-net-device.cc.
Referenced by ProcessHeader().
ProcessHeader()
bool ns3::PointToPointIslNetDevice::ProcessHeader (Ptr< Packet > p, uint16_t & param) private
Removes, from a packet of data, all headers and trailers that relate to the protocol implemented by the agent.
Parameters
p Packet whose headers need to be processed
param An integer parameter that can be set by the function
Returns
Returns true if the packet should be forwarded up the protocol stack.
Definition at line 95 of file satellite-point-to-point-isl-net-device.cc.
References PppToEther().
Referenced by Receive().
Receive()
void ns3::PointToPointIslNetDevice::Receive (Ptr< Packet > p)
Receive a packet from a connected PointToPointIslChannel.
The PointToPointIslNetDevice receives packets from its connected channel and forwards them up the protocol stack. This is the public method used by the channel to indicate that the last bit of a packet has arrived at the device.
Parameters
p Ptr to the received packet.
Definition at line 217 of file satellite-point-to-point-isl-net-device.cc.
References GetAddress(), ns3::SatGroundStationAddressTag::GetGroundStationAddress(), GetRemote(), m_geoNetDevice, m_promiscCallback, m_receiveErrorModel, and ProcessHeader().
Referenced by ns3::PointToPointIslChannel::TransmitStart().
Send()
bool ns3::PointToPointIslNetDevice::Send (Ptr< Packet > packet, const Address & dest, uint16_t protocolNumber) virtual
Definition at line 398 of file satellite-point-to-point-isl-net-device.cc.
References AddHeader(), IsLinkUp(), m_destinationNode, m_node, m_packetDropRateTrace, m_queue, m_txMachineState, READY, and TransmitStart().
SendFrom()
bool ns3::PointToPointIslNetDevice::SendFrom (Ptr< Packet > packet, const Address & source, const Address & dest, uint16_t protocolNumber) virtual
Definition at line 437 of file satellite-point-to-point-isl-net-device.cc.
SetAddress()
void ns3::PointToPointIslNetDevice::SetAddress (Address address) virtual
Definition at line 301 of file satellite-point-to-point-isl-net-device.cc.
References m_address.
Referenced by ns3::PointToPointIslHelper::Install().
SetDataRate()
void ns3::PointToPointIslNetDevice::SetDataRate (DataRate bps)
Set the Data Rate used for transmission of packets.
The data rate is set in the Attach () method from the corresponding field in the channel to which the device is attached. It can be overridden using this method.
Parameters
bps the data rate at which this object operates
Definition at line 117 of file satellite-point-to-point-isl-net-device.cc.
References m_dataRate.
SetDestinationNode()
void ns3::PointToPointIslNetDevice::SetDestinationNode (Ptr< Node > node) virtual
Definition at line 314 of file satellite-point-to-point-isl-net-device.cc.
References m_destinationNode.
SetGeoNetDevice()
void ns3::PointToPointIslNetDevice::SetGeoNetDevice (Ptr< SatGeoNetDevice > geoNetDevice)
Set the associated GeoNetDevice.
Parameters
geoNetDevice The device to attach to this instance
Definition at line 254 of file satellite-point-to-point-isl-net-device.cc.
References m_geoNetDevice.
SetIfIndex()
void ns3::PointToPointIslNetDevice::SetIfIndex (const uint32_t index) virtual
Definition at line 276 of file satellite-point-to-point-isl-net-device.cc.
References m_ifIndex.
SetInterframeGap()
void ns3::PointToPointIslNetDevice::SetInterframeGap (Time t)
Set the interframe gap used to separate packets.
The interframe gap defines the minimum space required between packets sent by this device.
Parameters
t the interframe gap time
Definition at line 124 of file satellite-point-to-point-isl-net-device.cc.
References m_tInterframeGap.
SetMtu()
bool ns3::PointToPointIslNetDevice::SetMtu (const uint16_t mtu) virtual
Definition at line 504 of file satellite-point-to-point-isl-net-device.cc.
References m_mtu.
SetNode()
void ns3::PointToPointIslNetDevice::SetNode (Ptr< Node > node) virtual
Definition at line 453 of file satellite-point-to-point-isl-net-device.cc.
References m_node.
SetPromiscReceiveCallback()
void ns3::PointToPointIslNetDevice::SetPromiscReceiveCallback (PromiscReceiveCallback cb) virtual
Definition at line 473 of file satellite-point-to-point-isl-net-device.cc.
References m_promiscCallback.
SetQueue()
void ns3::PointToPointIslNetDevice::SetQueue (Ptr< DropTailQueue< Packet >> queue)
Attach a queue to the PointToPointIslNetDevice.
The PointToPointIslNetDevice "owns" a queue that implements a queueing method such as DropTailQueue or RedQueue
Parameters
queue Ptr to the new queue.
Definition at line 203 of file satellite-point-to-point-isl-net-device.cc.
References m_queue.
SetReceiveCallback()
void ns3::PointToPointIslNetDevice::SetReceiveCallback (NetDevice::ReceiveCallback cb) virtual
Definition at line 467 of file satellite-point-to-point-isl-net-device.cc.
References m_rxCallback.
SetReceiveErrorModel()
void ns3::PointToPointIslNetDevice::SetReceiveErrorModel (Ptr< ErrorModel > em)
Attach a receive ErrorModel to the PointToPointIslNetDevice.
The PointToPointNetLaserDevice may optionally include an ErrorModel in the packet receive chain.
Parameters
em Ptr to the ErrorModel.
Definition at line 210 of file satellite-point-to-point-isl-net-device.cc.
References m_receiveErrorModel.
SupportsSendFrom()
bool ns3::PointToPointIslNetDevice::SupportsSendFrom (void) const virtual
Definition at line 479 of file satellite-point-to-point-isl-net-device.cc.
TransmitComplete()
void ns3::PointToPointIslNetDevice::TransmitComplete (void) private
Stop Sending a Packet Down the Wire and Begin the Interframe Gap.
The TransmitComplete method is used internally to finish the process of sending a packet out on the channel.
Definition at line 156 of file satellite-point-to-point-isl-net-device.cc.
References BUSY, m_currentPkt, m_queue, m_txMachineState, READY, and TransmitStart().
Referenced by TransmitStart().
TransmitStart()
bool ns3::PointToPointIslNetDevice::TransmitStart (Ptr< Packet > p) private
Start Sending a Packet Down the Wire.
The TransmitStart method is the method that is used internally in the PointToPointIslNetDevice to begin the process of sending a packet out on the channel. The corresponding method is called on the channel to let it know that the physical device this class represents has virtually started sending signals. An event is scheduled for the time at which the bits have been completely transmitted.
See also
PointToPointIslChannel::TransmitStart ()
TransmitComplete()
Parameters
p a reference to the packet to send
Returns
true if success, false on failure
Definition at line 131 of file satellite-point-to-point-isl-net-device.cc.
References BUSY, m_channel, m_currentPkt, m_dataRate, m_destinationNode, m_tInterframeGap, m_txMachineState, READY, and TransmitComplete().
Referenced by Send(), and TransmitComplete().
Member Data Documentation
DEFAULT_MTU
const uint16_t ns3::PointToPointIslNetDevice::DEFAULT_MTU = 1500 static private
Default MTU.
Definition at line 295 of file satellite-point-to-point-isl-net-device.h.
m_address
Mac48Address ns3::PointToPointIslNetDevice::m_address private
Mac48Address of this NetDevice.
Definition at line 311 of file satellite-point-to-point-isl-net-device.h.
Referenced by GetAddress(), and SetAddress().
m_channel
Ptr<PointToPointIslChannel> ns3::PointToPointIslNetDevice::m_channel private
The PointToPointIslChannel to which this PointToPointIslNetDevice has been attached.
Definition at line 302 of file satellite-point-to-point-isl-net-device.h.
Referenced by Attach(), DoDispose(), GetChannel(), GetRemote(), and TransmitStart().
m_currentPkt
Ptr<Packet> ns3::PointToPointIslNetDevice::m_currentPkt private
Current packet processed.
Definition at line 318 of file satellite-point-to-point-isl-net-device.h.
Referenced by DoDispose(), TransmitComplete(), and TransmitStart().
m_dataRate
DataRate ns3::PointToPointIslNetDevice::m_dataRate private
The data rate that the Net Device uses to simulate packet transmission timing.
Definition at line 298 of file satellite-point-to-point-isl-net-device.h.
Referenced by SetDataRate(), and TransmitStart().
m_destinationNode
Ptr<Node> ns3::PointToPointIslNetDevice::m_destinationNode private
Node at the other end of the p2pIslLink.
Definition at line 310 of file satellite-point-to-point-isl-net-device.h.
Referenced by GetDestinationNode(), Send(), SetDestinationNode(), and TransmitStart().
m_geoNetDevice
Ptr<SatGeoNetDevice> ns3::PointToPointIslNetDevice::m_geoNetDevice private
Satellite GEO Net Device associated to this instance.
Definition at line 320 of file satellite-point-to-point-isl-net-device.h.
Referenced by Receive(), and SetGeoNetDevice().
m_ifIndex
uint32_t ns3::PointToPointIslNetDevice::m_ifIndex private
Index of the interface.
Definition at line 315 of file satellite-point-to-point-isl-net-device.h.
Referenced by GetIfIndex(), and SetIfIndex().
m_linkUp
bool ns3::PointToPointIslNetDevice::m_linkUp private
Identify if the link is up or not.
Definition at line 316 of file satellite-point-to-point-isl-net-device.h.
Referenced by IsLinkUp(), and NotifyLinkUp().
m_mtu
uint32_t ns3::PointToPointIslNetDevice::m_mtu private
The Maximum Transmission Unit.
Definition at line 317 of file satellite-point-to-point-isl-net-device.h.
Referenced by GetMtu(), and SetMtu().
m_node
Ptr<Node> ns3::PointToPointIslNetDevice::m_node private
Node owning this NetDevice.
Definition at line 309 of file satellite-point-to-point-isl-net-device.h.
Referenced by DoDispose(), GetNode(), Send(), and SetNode().
m_packetDropRateTrace
TracedCallback<uint32_t, Ptr<Node>, Ptr<Node>, bool> ns3::PointToPointIslNetDevice::m_packetDropRateTrace private
Traced callback for drop rate in queue.
Definition at line 339 of file satellite-point-to-point-isl-net-device.h.
Referenced by GetTypeId(), and Send().
m_promiscCallback
NetDevice::PromiscReceiveCallback ns3::PointToPointIslNetDevice::m_promiscCallback private
Receive callback.
Definition at line 313 of file satellite-point-to-point-isl-net-device.h.
Referenced by Receive(), and SetPromiscReceiveCallback().
m_queue
Ptr<DropTailQueue<Packet> > ns3::PointToPointIslNetDevice::m_queue private
The Queue which this PointToPointIslNetDevice uses as a packet source.
Definition at line 305 of file satellite-point-to-point-isl-net-device.h.
Referenced by DoDispose(), GetQueue(), Send(), SetQueue(), and TransmitComplete().
m_receiveErrorModel
Ptr<ErrorModel> ns3::PointToPointIslNetDevice::m_receiveErrorModel private
Error model for receive packet events.
Definition at line 308 of file satellite-point-to-point-isl-net-device.h.
Referenced by DoDispose(), GetTypeId(), Receive(), and SetReceiveErrorModel().
m_rxCallback
NetDevice::ReceiveCallback ns3::PointToPointIslNetDevice::m_rxCallback private
Receive callback.
Definition at line 312 of file satellite-point-to-point-isl-net-device.h.
Referenced by SetReceiveCallback().
m_tInterframeGap
Time ns3::PointToPointIslNetDevice::m_tInterframeGap private
The interframe gap that the Net Device uses to throttle packet transmission.
Definition at line 300 of file satellite-point-to-point-isl-net-device.h.
Referenced by GetTypeId(), SetInterframeGap(), and TransmitStart().
m_txMachineState
TxMachineState ns3::PointToPointIslNetDevice::m_txMachineState private
The state of the Net Device transmit state machine.
Definition at line 297 of file satellite-point-to-point-isl-net-device.h.
Referenced by Send(), TransmitComplete(), and TransmitStart().
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/satellite-point-to-point-isl-net-device.h
/builds/sns3/satellite/satellite/model/satellite-point-to-point-isl-net-device.cc