SNS3
ns3::LoraLinkCheckComponent Class Reference
#include "lora-network-controller-components.h"
Public Member Functions
LoraLinkCheckComponent ()
virtual ~LoraLinkCheckComponent ()
void BeforeSendingReply (Ptr< LoraEndDeviceStatus > status, Ptr< LoraNetworkStatus > networkStatus)
void OnFailedReply (Ptr< LoraEndDeviceStatus > status, Ptr< LoraNetworkStatus > networkStatus)
Method that is called when a packet cannot be sent in the downlink.
void OnReceivedPacket (Ptr< const Packet > packet, Ptr< LoraEndDeviceStatus > status, Ptr< LoraNetworkStatus > networkStatus)
This method checks whether the received packet requires an acknowledgment and sets up the appropriate reply in case it does.
Public Member Functions inherited from ns3::LoraNetworkControllerComponent
LoraNetworkControllerComponent ()
virtual ~LoraNetworkControllerComponent ()
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::LoraNetworkControllerComponent
static TypeId GetTypeId (void)
Private Member Functions
void UpdateLinkCheckAns (Ptr< const Packet > packet, Ptr< LoraEndDeviceStatus > status)
Detailed Description
Definition at line 115 of file lora-network-controller-components.h.
Constructor & Destructor Documentation
LoraLinkCheckComponent()
ns3::LoraLinkCheckComponent::LoraLinkCheckComponent ()
Definition at line 137 of file lora-network-controller-components.cc.
~LoraLinkCheckComponent()
ns3::LoraLinkCheckComponent::~LoraLinkCheckComponent () virtual
Definition at line 141 of file lora-network-controller-components.cc.
Member Function Documentation
BeforeSendingReply()
void ns3::LoraLinkCheckComponent::BeforeSendingReply (Ptr< LoraEndDeviceStatus > status, Ptr< LoraNetworkStatus > networkStatus) virtual
Implements ns3::LoraNetworkControllerComponent.
Definition at line 157 of file lora-network-controller-components.cc.
References ns3::LoraFrameHeader::GetLorawanMacCommand(), ns3::LoraFrameHeader::SetAsUplink(), and ns3::LorawanMacHeader::UNCONFIRMED_DATA_DOWN.
GetTypeId()
TypeId ns3::LoraLinkCheckComponent::GetTypeId (void) static
Definition at line 129 of file lora-network-controller-components.cc.
Referenced by OnFailedReply(), and OnReceivedPacket().
OnFailedReply()
void ns3::LoraLinkCheckComponent::OnFailedReply (Ptr< LoraEndDeviceStatus > status, Ptr< LoraNetworkStatus > networkStatus) virtual
Method that is called when a packet cannot be sent in the downlink.
Parameters
status The EndDeviceStatus of the device to which it was impossible to send a reply.
networkStatus A pointer to the NetworkStatus object
Implements ns3::LoraNetworkControllerComponent.
Definition at line 193 of file lora-network-controller-components.cc.
References GetTypeId().
OnReceivedPacket()
void ns3::LoraLinkCheckComponent::OnReceivedPacket (Ptr< const Packet > packet, Ptr< LoraEndDeviceStatus > status, Ptr< LoraNetworkStatus > networkStatus) virtual
This method checks whether the received packet requires an acknowledgment and sets up the appropriate reply in case it does.
Parameters
packet The newly received packet
networkStatus A pointer to the NetworkStatus object
Implements ns3::LoraNetworkControllerComponent.
Definition at line 146 of file lora-network-controller-components.cc.
References GetTypeId().
UpdateLinkCheckAns()
void ns3::LoraLinkCheckComponent::UpdateLinkCheckAns (Ptr< const Packet > packet, Ptr< LoraEndDeviceStatus > status) private
The documentation for this class was generated from the following files:
/builds/sns3/satellite/satellite/model/lora-network-controller-components.h
/builds/sns3/satellite/satellite/model/lora-network-controller-components.cc