SNS3
SatRegenerationTest4 Class Reference
'Regeneration, test 4' test case implementation.
Public Member Functions
SatRegenerationTest4 ()
virtual ~SatRegenerationTest4 ()
Private Member Functions
virtual void DoRun (void)
void GeoDevGwRxTraceCb (Ptr< const Packet > packet, const Address &)
void GeoDevGwTxTraceCb (Ptr< const Packet > packet)
void GeoDevUtRxTraceCb (Ptr< const Packet > packet, const Address &)
void GeoDevUtTxTraceCb (Ptr< const Packet > packet)
bool HasSinkInstalled (Ptr< Node > node, uint16_t port)
Private Attributes
Ptr< SatHelper > m_helper
uint32_t m_totalReceivedGw
uint32_t m_totalReceivedUt
uint32_t m_totalSentGw
uint32_t m_totalSentUt
Detailed Description
'Regeneration, test 4' test case implementation.
This case tests link regeneration on satellite. It is based on a LARGER scenario.
Expected result: No bytes sent or received on FWD Same number of bytes sent and received on RTN
Definition at line 865 of file satellite-regeneration-test.cc.
Constructor & Destructor Documentation
SatRegenerationTest4()
SatRegenerationTest4::SatRegenerationTest4 ()
Definition at line 931 of file satellite-regeneration-test.cc.
References m_totalReceivedGw, m_totalReceivedUt, m_totalSentGw, and m_totalSentUt.
~SatRegenerationTest4()
SatRegenerationTest4::~SatRegenerationTest4 () virtual
Definition at line 942 of file satellite-regeneration-test.cc.
Member Function Documentation
DoRun()
void SatRegenerationTest4::DoRun (void) private virtual
Set regeneration mode
Set simulation output details
Definition at line 950 of file satellite-regeneration-test.cc.
References GeoDevGwRxTraceCb(), GeoDevGwTxTraceCb(), GeoDevUtRxTraceCb(), GeoDevUtTxTraceCb(), HasSinkInstalled(), m_helper, m_totalReceivedGw, m_totalReceivedUt, m_totalSentGw, and m_totalSentUt.
GeoDevGwRxTraceCb()
void SatRegenerationTest4::GeoDevGwRxTraceCb (Ptr< const Packet > packet, const Address &) private
Definition at line 900 of file satellite-regeneration-test.cc.
References m_totalReceivedGw.
Referenced by DoRun().
GeoDevGwTxTraceCb()
void SatRegenerationTest4::GeoDevGwTxTraceCb (Ptr< const Packet > packet) private
Definition at line 888 of file satellite-regeneration-test.cc.
References m_totalSentGw.
Referenced by DoRun().
GeoDevUtRxTraceCb()
void SatRegenerationTest4::GeoDevUtRxTraceCb (Ptr< const Packet > packet, const Address & address) private
Definition at line 906 of file satellite-regeneration-test.cc.
References m_totalReceivedUt.
Referenced by DoRun().
GeoDevUtTxTraceCb()
void SatRegenerationTest4::GeoDevUtTxTraceCb (Ptr< const Packet > packet) private
Definition at line 894 of file satellite-regeneration-test.cc.
References m_totalSentUt.
Referenced by DoRun().
HasSinkInstalled()
bool SatRegenerationTest4::HasSinkInstalled (Ptr< Node > node, uint16_t port) private
Definition at line 912 of file satellite-regeneration-test.cc.
Referenced by DoRun().
Member Data Documentation
m_helper
Ptr<SatHelper> SatRegenerationTest4::m_helper private
Definition at line 879 of file satellite-regeneration-test.cc.
Referenced by DoRun().
m_totalReceivedGw
uint32_t SatRegenerationTest4::m_totalReceivedGw private
Definition at line 883 of file satellite-regeneration-test.cc.
Referenced by SatRegenerationTest4(), DoRun(), and GeoDevGwRxTraceCb().
m_totalReceivedUt
uint32_t SatRegenerationTest4::m_totalReceivedUt private
Definition at line 884 of file satellite-regeneration-test.cc.
Referenced by SatRegenerationTest4(), DoRun(), and GeoDevUtRxTraceCb().
m_totalSentGw
uint32_t SatRegenerationTest4::m_totalSentGw private
Definition at line 881 of file satellite-regeneration-test.cc.
Referenced by SatRegenerationTest4(), DoRun(), and GeoDevGwTxTraceCb().
m_totalSentUt
uint32_t SatRegenerationTest4::m_totalSentUt private
Definition at line 882 of file satellite-regeneration-test.cc.
Referenced by SatRegenerationTest4(), DoRun(), and GeoDevUtTxTraceCb().
The documentation for this class was generated from the following file:
/builds/sns3/satellite/satellite/test/satellite-regeneration-test.cc