SNS3
ns3 Namespace Reference
SatArqSequenceNumber is handling the sequence numbers for the ARQ process.
Namespaces
SatConstVariables
SatConstVariables is used for const variable definitions in satellite module.
Classes
struct DateTime
The DateTime struct.
class DevStatusAns
Implementation of the DevStatusAns LoRaWAN MAC command.
class DevStatusReq
Implementation of the DevStatusReq LoRaWAN MAC command.
class DlChannelAns
Implementation of the DlChannelAns LoRaWAN MAC command.
class DropTailQueue
class DutyCycleAns
Implementation of the DutyCycleAns LoRaWAN MAC command.
class DutyCycleReq
Implementation of the DutyCycleReq LoRaWAN MAC command.
class EncapKey
EncapKey class is used as a key in the encapsulator/decapsulator container.
class EncapKeyCompare
EncapKeyCompare is used as a custom compare method within EncapContainer map.
class GeoCoordinate
GeoCoordinate class is used to store and operate with geodetic coordinates.
class IersData
class JulianDate
Class to handle Julian days and provide respective Earth Orientation Parameters (EOP).
class LinkAdrAns
Implementation of the LinkAdrAns LoRaWAN MAC command.
class LinkAdrReq
Implementation of the LinkAdrReq LoRaWAN MAC command.
class LinkCheckAns
Implementation of the LinkCheckAns LoRaWAN MAC command.
class LinkCheckReq
Implementation of the LinkCheckReq LoRaWAN MAC command.
class LinkResultTestSuite
Unit test suite for link results (sat-link-results-test).
class LoraAdrComponent
class LoraBeamTag
Tag used to save various data about a packet, like its Spreading Factor and data about interference.
class LoraConfirmedMessagesComponent
class LoraDeviceAddress
This class represents the device address of a LoraWAN End Device.
class LoraDeviceAddressGenerator
This class generates sequential LoraDeviceAddress instances.
class LoraEndDeviceStatus
This class represents the Network Server's knowledge about an End Device in the LoRaWAN network it is administering.
class LoraForwarder
This application forwards packets between NetDevices: SatLorawanNetDevice -> PointToPointNetDevice and vice versa.
class LoraForwarderHelper
This class can be used to install LoraForwarder applications on a set of gateways.
class LoraFrameHeader
This class represents the Frame header (FHDR) used in a LoraWAN network.
class LoraGatewayStatus
class LoraLinkCheckComponent
class LoraLogicalChannel
This class represents a logical LoRaWAN channel.
class LoraLogicalChannelHelper
This class supports LorawanMac instances by managing a list of the logical channels that the device is supposed to be using, and establishes their relationship with LoraSubBands.
class LoraNetworkController
This class collects a series of components that deal with various aspects of managing the network, and queries them for action when a new packet is received or other events occur in the network.
class LoraNetworkControllerComponent
Generic class describing a component of the NetworkController.
class LoraNetworkScheduler
class LoraNetworkServer
The LoraNetworkServer is an application standing on top of a node equipped with links that connect it with the gateways.
class LoraNetworkServerHelper
This class can install Network Server applications on multiple nodes at once.
class LoraNetworkStatus
This class represents the knowledge about the state of the network that is available at the Network Server.
class LoraPeriodicSender
class LoraSubBand
Class representing a LoraSubBand, i.e., a frequency band subject to some regulations on duty cycle and transmission power.
class LoraTag
Tag used to save various data about a packet, like its Spreading Factor and data about interference.
struct LoraTxParameters
Structure to collect all parameters that are used to compute the duration of a packet (excluding payload length).
class LorawanMac
Class representing the LoRaWAN MAC layer.
class LorawanMacCommand
This base class is used to represent a general MAC command.
class LorawanMacEndDevice
Class representing the MAC layer of a LoRaWAN device.
class LorawanMacEndDeviceClassA
Class representing the MAC layer of a Class A LoRaWAN device.
class LorawanMacGateway
class LorawanMacHeader
This class represents the Mac header of a LoRaWAN packet.
class NewChannelAns
Implementation of the NewChannelAns LoRaWAN MAC command.
class NewChannelReq
Implementation of the NewChannelReq LoRaWAN MAC command.
class NwkAddr
Class representing the Network Address component of a LoraDeviceAddress (25 bits)
class NwkID
Class representing the NetworkId component of a LoraDeviceAddress (7 bits).
class PointToPointIslChannel
Point to Point ISL Channel.
class PointToPointIslHelper
class PointToPointIslNetDevice
class RxParamSetupAns
Implementation of the RxParamSetupAns LoRaWAN MAC command.
class RxParamSetupReq
Implementation of the RxParamSetupReq LoRaWAN MAC command.
class RxTimingSetupAns
Implementation of the RxTimingSetupAns LoRaWAN MAC command.
class RxTimingSetupReq
Implementation of the RxTimingSetupReq LoRaWAN MAC command.
class SatAddressE2ETag
This class implements a tag that carries the satellite MAC of GW and UT.
class SatAddressTag
This class implements a tag that carries the MAC address of the sender of the packet.
class SatAntennaGainPattern
SatAntennaGainPattern class holds the antenna gain pattern data for a one single spot-beam.
class SatAntennaGainPatternContainer
Antenna gain pattern container holds all antenna patterns related to a satellite system.
class SatArpCache
An ARP cache interface for satellite module.
class SatArqAckMessage
The packet for the Automatic Repeat reQuest (ARQ) acknowledgment (ACK) messages.
class SatArqBufferContext
ARQ buffer context is holding information related to the ARQ transmission or reception depending on whether packet(s) are being transmitted or received.
class SatArqHeader
ARQ header implementation contains the sequence number related to the packet in question.
class SatArqSequenceNumber
class SatBaseEncapsulator
A base encapsulator implementation which does not support encapsulation, fragmentation or packing.
class SatBaseFader
Base class for faders such as the Rayleigh fader.
class SatBaseFaderConf
Base class for fader configuration classes.
class SatBaseFading
Base class for fading models such as Markov-based fading or fading trace.
class SatBaseTraceContainer
Base class for trace containers such as interference or fading traces.
class SatBasicCnoEstimator
class for module SatCnoEstimator.
class SatBbFrame
SatBbFrame class implements functionality for BB frames.
class SatBbFrameConf
This class implements the BB Frame configurations for DVB-S2.
class SatBbFrameContainer
BB Frame container class.
class SatBeamHelper
SatBeamHelper builds a set Satellite beams with needed objects and configuration.
class SatBeamScheduler
class for module Beam Scheduler.
class SatBeamUserInfo
Class that holds information for each beam regarding UTs and their users camped in each beam.
class SatBstpController
SatBstpController class is responsible of enabling and disabling configurable spot-beams defined by a Beam Switching Time Plan (BSTP).
class SatBtuConf
This class implements configuration for Bandwidth Time Unit (BTU).
class SatChannel
Satellite channel implementation.
class SatChannelEstimationError
SatChannelEstimatorError reads from file and stores the channel estimation error mean and standard deviation values for a set of SINR values.
class SatChannelEstimationErrorContainer
SatChannelEstimationErrorContainer is responsible of adding a channel estimation error on top of raw measured SINR.
class SatChannelPair
Container of Satellite channels pairs.
class SatCmtMessage
This control message is used to give time, power and frequency correction to UTs.
class SatCnoEstimator
SatCnoEstimator class defines interface for C/N0 estimators.
class SatCnoHelper
This helper allows to set customs C/N0 values for some GW or UT nodes.
class SatCnoReportMessage
C/N0 (CNI) estimation report message.
class SatCompositeSinrOutputTraceContainer
Class for composite SINR output trace container.
class SatConf
A configuration class for the GEO satellite reference system.
class SatConstantInterference
Satellite constant interference.
class SatConstantPositionMobilityModel
Satellite mobility model for which the current position does not change once it has been set and until it is set again explicitly to a new value.
class SatConstantPropagationDelayModel
The propagation delay is constant in time.
class SatControlMessage
Abstract satellite control message class.
class SatControlMsgContainer
The container to store control messages.
class SatControlMsgTag
This class implements a tag that is used to identify control messages (packages).
class SatCrdsaReplicaTag
This class implements a tag that carries information about the slot IDs of CRDSA packet replicas.
class SatCrMessage
The packet for the Capacity Request (CR) messages.
class SatDamaEntry
class for module SatDamaEntry.
class SatDefaultSuperframeAllocator
helper class for Satellite Beam Scheduler.
class SatDevLinkTimeTag
Time tag used to identify the time when packet is enqueued at device level.
class SatDevTimeTag
Time tag used to identify the time when packet is enqueued at device level.
class SatDvbS2Waveform
This class implements the content of one individual DVB-S2 waveform.
class SatEncapPduStatusTag
SatEncapPduStatusTag is used temporarily to tag packets with the fragmentation status in the encapsulation and fragmentation process.
class SatEnums
SatEnums class is for simplifying the use of enumerators in the satellite module.
class SatEnvVariables
Class for environmental variables.
class SatFadingExternalInputTrace
The class for satellite fading external input trace.
class SatFadingExternalInputTraceContainer
Container class for external input fading traces.
class SatFadingInputTrace
Class for fading input trace.
class SatFadingInputTraceContainer
Class for fading input trace container.
class SatFadingOscillator
Oscillator class for faders.
class SatFadingOutputTraceContainer
Class for fading output trace container.
class SatFlowIdTag
SatFlowIdTag implements a tag which carries the flow identifier of a packet.
class SatFrameAllocator
helper class for Satellite Superframe Allocator.
class SatFrameConf
This class implements configuration for frames (for super frames)
class SatFrameSymbolLoadProbe
Probe to translate from a FrameLoadTrace trace source.
class SatFrameUserLoadProbe
Probe to translate from a FrameUtLoadTrace trace source.
class SatFreeSpaceLoss
This class is responsible of calculating the free space loss (FSL) based on two given node positions and used (center) frequency.
class SatFwdCarrierConf
This class implements configuration for forward link carrier .
class SatFwdLinkChannelEstimationErrorContainer
class SatFwdLinkScheduler
SatFwdLinkScheduler schedules BB frames for forward link.
class SatFwdLinkSchedulerDefault
SatFwdLinkSchedulerDefault schedules BB frames for forward link.
class SatFwdLinkSchedulerTimeSlicing
SatFwdLinkSchedulerTimeSlicing schedules BB frames for forward link.
class SatGenericStreamEncapsulator
SatGenericStreamEncapsulator class is used in the FWD link for GSE encapsulation and fragmentation of higher layer packets.
class SatGenericStreamEncapsulatorArq
SatGenericStreamEncapsulatorArq class is inherited from the SatGenericStreamEncapsulator class, which is used in FWD link for encapsulation and fragmentation of higher layer packets.
class SatGeoFeederLlc
SatGeoFeederLlc holds the GEO feeder implementation of LLC layer.
class SatGeoFeederMac
The SatGeoFeederMac models the user link MAC layer of the satellite node.
class SatGeoFeederPhy
The SatGeoFeederPhy models the feeder link physical layer of the satellite node.
class SatGeoHelper
Creates needed objects for Geo Satellite node like SatGeoNetDevice objects.
class SatGeoLlc
SatGeoLlc holds the GEO implementation of LLC layer.
class SatGeoMac
The SatGeoMac models the global link MAC layer of the satellite node.
class SatGeoNetDevice
SatGeoNetDevice to be utilized in geostationary satellite.
class SatGeoUserLlc
SatGeoUserLlc holds the GEO user implementation of LLC layer.
class SatGeoUserMac
The SatGeoUserMac models the user link MAC layer of the satellite node.
class SatGeoUserPhy
The SatGeoUserPhy models the user link physical layer of the satellite node.
class SatGroundStationAddressTag
Tag to store ground station destination address.
class SatGroupHelper
This helper is used to create groups of UTs.
class SatGseHeader
SatGseHeader implementation.
class SatGwHelper
Creates needed objects for GW nodes like SatGeoNetDevice objects.
class SatGwLlc
SatGwLlc holds the GW implementation of LLC layer.
class SatGwMac
GW specific Mac class for Sat Net Devices.
class SatGwPhy
The SatGwPhy models the physical layer of the satellite system (UT, GW, satellite)
class SatHandoverRecommendationMessage
Handover recommendation control message (Tagged by SatControlMsgTag with type value SAT_HR_CTRL_MSG)
class SatHelper
Build a satellite network set with needed objects and configuration.
class SatIdMapper
Class for ID-mapper.
class SatInputFileStreamTimeDoubleContainer
Class for input file stream container for storing double values.
class SatInputFileStreamTimeLongDoubleContainer
Class for input file stream container for storing long double values.
class SatInputFileStreamWrapper
A class encapsulating an STL input stream.
class SatInterference
Abstract class defining interface for interference calculations objects.
class SatInterferenceElimination
Abstract class defining interface for interference elimination calculation objects.
class SatInterferenceInputTraceContainer
Class for interference input trace container.
class SatInterferenceOutputTraceContainer
Class for interference output trace container.
class SatInterferenceParameters
class SatIslArbiter
class SatIslArbiterUnicast
class SatIslArbiterUnicastHelper
class SatLinkResults
Abstract class for storing link results.
class SatLinkResultsDvbRcs2
Link results for DVB-RCS2.
class SatLinkResultsDvbRcs2TestCase
Test case for comparing a BLER value computed by DVB-RCS2 link results with a BLER value taken from a reference.
class SatLinkResultsDvbS2
Link results for DVB-S2.
class SatLinkResultsDvbS2TestCase
Test case for comparing a BLER value computed by DVB-S2 link results with a BLER value taken from a reference.
class SatLinkResultsDvbS2X
Link results for DVB-S2X.
class SatLinkResultsFSim
Link results for F-SIM.
class SatLinkResultsFwd
Link results for forward link.
class SatLinkResultsLora
Link results for F-SIM.
class SatLinkResultsPlot
Example for plotting satellite link results data.
class SatLinkResultsRtn
Link results for DVB-RCS2.
class SatListPositionAllocator
Allocate positions from a deterministic list specified by the user.
class SatLlc
SatLlc base class holds the UT specific SatBaseEncapsulator instances, which are responsible of fragmentation, defragmentation, encapsulation and decapsulation.
class SatLog
Class for simulator output logging such as warnings and error messages.
class SatLogoffMessage
This control message is used to inform the UT that it has been deconnected by GW (Tagged by SatControlMsgTag with type value SAT_LOGOFF_CTRL_MSG)
class SatLogonMessage
This control message is used to inform the GW that a UT wants to connect (Tagged by SatControlMsgTag with type value SAT_LOGON_CTRL_MSG)
class SatLogonResponseMessage
This control message is used to inform the UT of a connection success (Tagged by SatControlMsgTag with type value SAT_LOGON_RESPONSE_CTRL_MSG)
class SatLooConf
A configuration class for Loo's model fader.
class SatLookUpTable
Loads a link result file and provide query service for BLER.
class SatLooModel
Class for Loo's model fader.
class SatLoraConf
A configuration class for the GEO satellite reference system.
class SatLoraPhyRx
Class adding methods linked to Lora, needed to be used in a satellite context.
class SatLoraPhyTx
Class adding methods linked to Lora, needed to be used in a satellite context.
class SatLorawanNetDevice
SatLorawanNetDevice to be utilized in the UT and GW nodes for IoT configuration.
class SatLowerLayerServiceConf
The SatLowerLayerServiceConf class holds information of all configures lower layer service entries.
class SatLowerLayerServiceDaEntry
The SatLowerLayerService class holds information of a satellite lower layer service DA entry.
class SatLowerLayerServiceRaEntry
The SatLowerLayerService class holds information of a satellite lower layer service RA entry.
class SatMac
Base MAC class for SatNetDevices.
class SatMacLinkTimeTag
Time tag used to identify the time when packet is enqueued at MAC on current link level.
class SatMacTag
This class implements a tag that carries the satellite MAC specific information, such as source and destination MAC address.
class SatMacTimeTag
Time tag used to identify the time when packet is enqueued at MAC level.
class SatMarkovConf
A configuration class for three state Markov model.
class SatMarkovContainer
Container for Markov-model.
class SatMarkovFadingExamplePlot
class SatMarkovModel
Class for Markov state machine.
class SatMobilityModel
Keep track of the current position and velocity of an object in satellite network.
class SatMobilityObserver
Observes given mobilities and keeps track of certain wanted properties.
class SatMutualInformationTable
Loads a mutual information file and provide query service.
class SatNcc
class for module NCC used as shared module among Gateways (GWs).
class SatNcrMessage
This control message is used to broadcast NCR date to UTs.
class SatNetDevice
SatNetDevice to be utilized in the UT and GW nodes.
class SatNodeInfo
The SatNodeInfo implements a container for all needed node related information.
class SatOnOffApplication
This class implements Satellite specific OnOff application.
class SatOnOffHelper
A helper to make it easier to instantiate an ns3::SatOnOffApplication on a set of nodes.
class SatOutputFileStreamDoubleContainer
Class for output file stream container for double values.
class SatOutputFileStreamLongDoubleContainer
Class for output file stream container for long double values.
class SatOutputFileStreamStringContainer
Class for output file stream container for strings.
class SatOutputFileStreamWrapper
A class encapsulating an STL output stream.
class SatPacketClassifier
SatPacketClassifier is responsible of classifying packets into certain flow identifier.
class SatPacketTrace
The SatPacketTrace implements a packet trace functionality.
class SatPerfectInterferenceElimination
Satellite perfect interference elimination.
class SatPerFragmentInterference
Packet fragment by packet fragment interference.
class SatPerPacketInterference
Packet by packet interference.
class SatPhy
The SatPhy models the basic physical layer of the satellite system.
class SatPhyLinkTimeTag
Time tag used to identify the time when packet is enqueued at PHY on current link level.
class SatPhyRx
The SatPhyRx models the physical layer receiver of satellite system.
class SatPhyRxCarrier
Base class for all SatPhyRxCarriers.
class SatPhyRxCarrierConf
Information of beam users liken UTs and their users.
class SatPhyRxCarrierMarsala
Bite.
class SatPhyRxCarrierPacketProbe
Probe to translate from a TraceSource to two more easily parsed TraceSources.
class SatPhyRxCarrierPerFrame
Inherited the functionality of ground station SatPhyRxCarriers and extended it with CRDSA functionality.
class SatPhyRxCarrierPerSlot
Inherited the base functionality of SatPhyRxCarriers for ground station nodes.
class SatPhyRxCarrierPerWindow
Inherited the functionality of ground station SatPhyRxCarriers and extended it with CRDSA functionality.
class SatPhyRxCarrierUplink
Inherited functionality of the base SatPhyRxCarrier for satellite node.
class SatPhyTimeTag
Time tag used to identify the time when packet is enqueued at PHY on first link between GW and UT level.
class SatPhyTx
The SatellitePhyTx models the physical layer transmitter of satellite system.
class SatPositionAllocator
Allocate a set of satellite positions.
class SatPositionInputTraceContainer
Class for Rx power input trace container.
class SatPPduHeader
SatPPduHeader implementation.
class SatQueue
SatQueue implements a queue utilized in the satellite module.
class SatRaMessage
Random access load control message (Tagged by SatControlMsgTag with type value SAT_RA_CTRL_MSG)
class SatRandomAccess
Class for random access algorithms.
class SatRandomAccessAllocationChannel
Class for random access allocation channel configuration.
class SatRandomAccessConf
Class for random access configuration.
class SatRandomBoxPositionAllocator
Allocate random positions within a 3D box according to a set of three random variables (longitude, latitude, altitude).
class SatRandomCirclePositionAllocator
Allocate random positions within a circle (center and radius), uniformly distributed.
class SatRayleighConf
A configuration class for Rayleigh model fader.
class SatRayleighModel
Class for Rayleigh model fader.
class SatRequestManager
SatRequestManager analyzes periodically or on-a-need-basis UT's buffer status for different RC indices (= queues), and sends Capacity Requests to NCC according to need and lower layer service configuration.
class SatResidualInterferenceElimination
Satellite interference elimination with residual power.
class SatReturnLinkEncapsulator
SatReturnLinkEncapsulator class is used in the RTN link for RLE encapsulation and fragmentation of higher layer packets.
class SatReturnLinkEncapsulatorArq
SatReturnLinkEncapsulatorArq class is inherited from the SatReturnLinkEncapsulator class, which is used in RTN link for encapsulation and fragmentation of higher layer packets.
class SatRtnLinkChannelEstimationErrorContainer
class SatRtnLinkTime
SatRtnLinkTime is a singleton class initialized with superframe sequence.
class SatRxCnoInputTraceContainer
Class for Rx C/N0 input trace container.
class SatRxPowerInputTraceContainer
Class for Rx power input trace container.
class SatRxPowerOutputTraceContainer
Class for Rx power output trace container.
class SatSchedulingObject
SatSchedulingObject is on object which passes the LLC/encapsulator layer related information for MAC layer to be used by the scheduler (either at GW by the forward link scheduler or at the UT by the RTN link UT scheduler).
class SatScpcScheduler
SatFwdLinkSchedulerDefault schedules BB frames for forward link.
class SatSGP4MobilityModel
Keep track of the current position and velocity of satellite using SGP4 model.
class SatSignalParameters
Actual physical layer transmission container.
class SatSimpleChannel
The satellite simple channel, for satellite public and backbone networks.
class SatSimpleChannelEstimationErrorContainer
class SatSimpleNetDevice
Satellite simple net device for satellite public and backbone network use.
class SatSinrProbe
Probe to translate from a TraceSource to two more easily parsed TraceSources.
class SatSliceSubscriptionMessage
This control message is used to inform the UT it has to subscribe to a new slice.
class SatSpotBeamPositionAllocator
Allocate random positions within the area of a certain spot-beam.
class SatStaticBstp
SatStaticBstp class models the static beam switching time plan (BSTP) configuration, which is defined in an external file read by this class.
class SatStatsAntennaGainHelper
Base class for antenna gain statistics helpers.
class SatStatsBackloggedRequestHelper
class SatStatsBeamServiceTimeHelper
class SatStatsCapacityRequestHelper
Produce capacity request statistics of Random Access Slotted ALOHA from a satellite module simulation.
class SatStatsCarrierIdHelper
class SatStatsCompositeSinrHelper
Abstract class inherited by SatStatsFwdCompositeSinrHelper and SatStatsRtnCompositeSinrHelper.
class SatStatsDelayHelper
Base class for delay statistics helpers.
class SatStatsFeederCrdsaPacketCollisionHelper
Produce packet collision statistics of Random Access CRDSA from a satellite module simulation.
class SatStatsFeederCrdsaPacketErrorHelper
Produce packet error statistics of Random Access CRDSA on feeder link from a satellite module simulation.
class SatStatsFeederEssaPacketCollisionHelper
Produce packet collision statistics of Random Access E-SSA from a satellite module simulation.
class SatStatsFeederEssaPacketErrorHelper
Produce packet error statistics of Random Access E-SSA on feeder link from a satellite module simulation.
class SatStatsFeederPacketCollisionHelper
class SatStatsFeederSlottedAlohaPacketCollisionHelper
Produce packet collision statistics of Random Access Slotted ALOHA from a satellite module simulation.
class SatStatsFeederSlottedAlohaPacketErrorHelper
Produce packet error statistics of Random Access Slotted ALOHA on feeder link from a satellite module simulation.
class SatStatsFrameLoadHelper
Helper for frame load statistics.
class SatStatsFrameSymbolLoadHelper
Helper for frame symbol load statistics.
class SatStatsFrameTypeUsageHelper
class SatStatsFrameUserLoadHelper
Helper for frame user load statistics.
class SatStatsFwdAppDelayHelper
Produce forward link application-level delay statistics from a satellite module simulation.
class SatStatsFwdAppJitterHelper
class SatStatsFwdAppPltHelper
class SatStatsFwdAppThroughputHelper
Produce forward link application-level throughput statistics from a satellite module simulation.
class SatStatsFwdCompositeSinrHelper
Produce forward link composite SINR statistics from a satellite module simulation.
class SatStatsFwdDevDelayHelper
Produce forward link device-level delay statistics from a satellite module simulation.
class SatStatsFwdDevJitterHelper
class SatStatsFwdFeederDaPacketErrorHelper
Produce packet error statistics of Dedicated Access in forward feeder link from a satellite module simulation.
class SatStatsFwdFeederDevLinkDelayHelper
Produce forward feeder link DEV-level delay statistics from a satellite module simulation.
class SatStatsFwdFeederDevLinkJitterHelper
Produce forward feeder link DEV-level jitter statistics from a satellite module simulation.
class SatStatsFwdFeederDevThroughputHelper
Produce forward feeder link device-level throughput statistics from a satellite module simulation.
class SatStatsFwdFeederLinkModcodHelper
Produce forward feeder link modcod statistics from a satellite module simulation.
class SatStatsFwdFeederLinkRxPowerHelper
Produce forward feeder link RX power statistics from a satellite module simulation.
class SatStatsFwdFeederLinkSinrHelper
Produce forward feeder link SINR statistics from a satellite module simulation.
class SatStatsFwdFeederMacLinkDelayHelper
Produce forward feeder link MAC-level delay statistics from a satellite module simulation.
class SatStatsFwdFeederMacLinkJitterHelper
Produce forward feeder link MAC-level jitter statistics from a satellite module simulation.
class SatStatsFwdFeederMacThroughputHelper
Produce forward feeder link MAC-level throughput statistics from a satellite module simulation.
class SatStatsFwdFeederPhyLinkDelayHelper
Produce forward feeder link PHY-level delay statistics from a satellite module simulation.
class SatStatsFwdFeederPhyLinkJitterHelper
Produce forward feeder link PHY-level jitter statistics from a satellite module simulation.
class SatStatsFwdFeederPhyThroughputHelper
Produce forward feeder link PHY-level throughput statistics from a satellite module simulation.
class SatStatsFwdLinkSchedulerSymbolRateHelper
Helper for forward link scheduler symbol rate statistic.
class SatStatsFwdMacDelayHelper
Produce forward link MAC-level delay statistics from a satellite module simulation.
class SatStatsFwdMacJitterHelper
class SatStatsFwdPhyDelayHelper
Produce forward link PHY-level delay statistics from a satellite module simulation.
class SatStatsFwdPhyJitterHelper
class SatStatsFwdQueueBytesHelper
Helper for forward link queue statistics using byte as unit.
class SatStatsFwdQueueHelper
Helper for forward link queue statistics.
class SatStatsFwdQueuePacketsHelper
Helper for forward link queue statistics using packet as unit.
class SatStatsFwdSignallingLoadHelper
Produce forward link signalling load statistics from a satellite module simulation.
class SatStatsFwdUserDaPacketErrorHelper
Produce packet error statistics of Dedicated Access in forward user link from a satellite module simulation.
class SatStatsFwdUserDevLinkDelayHelper
Produce forward user link DEV-level delay statistics from a satellite module simulation.
class SatStatsFwdUserDevLinkJitterHelper
Produce forward user link DEV-level jitter statistics from a satellite module simulation.
class SatStatsFwdUserDevThroughputHelper
Produce forward user link device-level throughput statistics from a satellite module simulation.
class SatStatsFwdUserLinkModcodHelper
Produce forward user link modcod statistics from a satellite module simulation.
class SatStatsFwdUserLinkRxPowerHelper
Produce forward user link RX power statistics from a satellite module simulation.
class SatStatsFwdUserLinkSinrHelper
Produce forward user link SINR statistics from a satellite module simulation.
class SatStatsFwdUserMacLinkDelayHelper
Produce forward user link MAC-level delay statistics from a satellite module simulation.
class SatStatsFwdUserMacLinkJitterHelper
Produce forward user link MAC-level jitter statistics from a satellite module simulation.
class SatStatsFwdUserMacThroughputHelper
Produce forward user link MAC-level throughput statistics from a satellite module simulation.
class SatStatsFwdUserPhyLinkDelayHelper
Produce forward user link PHY-level delay statistics from a satellite module simulation.
class SatStatsFwdUserPhyLinkJitterHelper
Produce forward user link PHY-level jitter statistics from a satellite module simulation.
class SatStatsFwdUserPhyThroughputHelper
Produce forward user link PHY-level throughput statistics from a satellite module simulation.
class SatStatsFwdUserQueueBytesHelper
Produce queue size statistics in packets for return feeder link.
class SatStatsFwdUserQueuePacketsHelper
Produce queue size statistics in packets for return feeder link.
class SatStatsHelper
Parent abstract class of all satellite statistics helpers.
class SatStatsHelperContainer
Container of SatStatsHelper instances.
class SatStatsJitterHelper
Base class for jitter statistics helpers.
class SatStatsLinkDelayHelper
Base class for delay statistics helpers.
class SatStatsLinkJitterHelper
Base class for jitter statistics helpers.
class SatStatsLinkModcodHelper
Base class for MODCOD statistics helpers.
class SatStatsLinkRxPowerHelper
Base class for link RX power statistics helpers.
class SatStatsLinkSinrHelper
Base class for link SINR statistics helpers.
class SatStatsMarsalaCorrelationHelper
class SatStatsPacketCollisionHelper
class SatStatsPacketDropRateHelper
Base class for antenna gain statistics helpers.
class SatStatsPacketErrorHelper
Base class for packet error statistics helpers.
class SatStatsPltHelper
Base class for PLT statistics helpers.
class SatStatsQueueHelper
Helper for queue statistics.
class SatStatsRbdcRequestHelper
Base class for RBDC requests statistics helpers.
class SatStatsResourcesGrantedHelper
class SatStatsRtnAppDelayHelper
Produce return link application-level delay statistics from a satellite module simulation.
class SatStatsRtnAppJitterHelper
class SatStatsRtnAppPltHelper
class SatStatsRtnAppThroughputHelper
Produce return link application-level throughput statistics from a satellite module simulation.
class SatStatsRtnCompositeSinrHelper
Produce return link composite SINR statistics from a satellite module simulation.
class SatStatsRtnDevDelayHelper
Produce return link device-level delay statistics from a satellite module simulation.
class SatStatsRtnDevJitterHelper
class SatStatsRtnFeederDaPacketErrorHelper
Produce packet error statistics of Dedicated Access in return feeder link from a satellite module simulation.
class SatStatsRtnFeederDevLinkDelayHelper
Produce return feeder link DEV-level delay statistics from a satellite module simulation.
class SatStatsRtnFeederDevLinkJitterHelper
Produce return feeder link DEV-level jitter statistics from a satellite module simulation.
class SatStatsRtnFeederDevThroughputHelper
Produce return feeder link device-level throughput statistics from a satellite module simulation.
class SatStatsRtnFeederLinkModcodHelper
Produce return feeder link modcod statistics from a satellite module simulation.
class SatStatsRtnFeederLinkRxPowerHelper
Produce return feeder link RX power statistics from a satellite module simulation.
class SatStatsRtnFeederLinkSinrHelper
Produce return feeder link SINR statistics from a satellite module simulation.
class SatStatsRtnFeederMacLinkDelayHelper
Produce return feeder link MAC-level delay statistics from a satellite module simulation.
class SatStatsRtnFeederMacLinkJitterHelper
Produce return feeder link MAC-level jitter statistics from a satellite module simulation.
class SatStatsRtnFeederMacThroughputHelper
Produce return feeder link MAC-level throughput statistics from a satellite module simulation.
class SatStatsRtnFeederPhyLinkDelayHelper
Produce return feeder link PHY-level delay statistics from a satellite module simulation.
class SatStatsRtnFeederPhyLinkJitterHelper
Produce return feeder link PHY-level jitter statistics from a satellite module simulation.
class SatStatsRtnFeederPhyThroughputHelper
Produce return feeder link PHY-level throughput statistics from a satellite module simulation.
class SatStatsRtnFeederQueueBytesHelper
Produce queue size statistics in packets for return feeder link.
class SatStatsRtnFeederQueuePacketsHelper
Produce queue size statistics in packets for return feeder link.
class SatStatsRtnFeederWindowLoadHelper
Produce return feeder window load statistics from a satellite module simulation.
class SatStatsRtnMacDelayHelper
Produce return link MAC-level delay statistics from a satellite module simulation.
class SatStatsRtnMacJitterHelper
class SatStatsRtnPhyDelayHelper
Produce return link PHY-level delay statistics from a satellite module simulation.
class SatStatsRtnPhyJitterHelper
class SatStatsRtnQueueBytesHelper
Helper for return link queue statistics using byte as unit.
class SatStatsRtnQueueHelper
Helper for return link queue statistics.
class SatStatsRtnQueuePacketsHelper
Helper for return link queue statistics using packet as unit.
class SatStatsRtnSignallingLoadHelper
Produce return link signalling load statistics from a satellite module simulation.
class SatStatsRtnUserDaPacketErrorHelper
Produce packet error statistics of Dedicated Access in return user link from a satellite module simulation.
class SatStatsRtnUserDevLinkDelayHelper
Produce return user link DEV-level delay statistics from a satellite module simulation.
class SatStatsRtnUserDevLinkJitterHelper
Produce return user link DEV-level jitter statistics from a satellite module simulation.
class SatStatsRtnUserDevThroughputHelper
Produce return user link device-level throughput statistics from a satellite module simulation.
class SatStatsRtnUserLinkModcodHelper
Produce return user link modcod statistics from a satellite module simulation.
class SatStatsRtnUserLinkRxPowerHelper
Produce return user link RX power statistics from a satellite module simulation.
class SatStatsRtnUserLinkSinrHelper
Produce return user link SINR statistics from a satellite module simulation.
class SatStatsRtnUserMacLinkDelayHelper
Produce return user link MAC-level delay statistics from a satellite module simulation.
class SatStatsRtnUserMacLinkJitterHelper
Produce return user link MAC-level jitter statistics from a satellite module simulation.
class SatStatsRtnUserMacThroughputHelper
Produce return user link MAC-level throughput statistics from a satellite module simulation.
class SatStatsRtnUserPhyLinkDelayHelper
Produce return user link PHY-level delay statistics from a satellite module simulation.
class SatStatsRtnUserPhyLinkJitterHelper
Produce return user link PHY-level jitter statistics from a satellite module simulation.
class SatStatsRtnUserPhyThroughputHelper
Produce return user link PHY-level throughput statistics from a satellite module simulation.
class SatStatsSatelliteQueueHelper
Base class for sat queue statistics helpers.
class SatStatsSignallingLoadHelper
Abstract class inherited by SatStatsFwdSignallingLoadHelper and SatStatsRtnSignallingLoadHelper.
class SatStatsThroughputHelper
class SatStatsUserCrdsaPacketCollisionHelper
Produce packet collision statistics of Random Access CRDSA from a satellite module simulation.
class SatStatsUserCrdsaPacketErrorHelper
Produce packet error statistics of Random Access CRDSA on user link from a satellite module simulation.
class SatStatsUserEssaPacketCollisionHelper
Produce packet collision statistics of Random Access E-SSA from a satellite module simulation.
class SatStatsUserEssaPacketErrorHelper
Produce packet error statistics of Random Access E-SSA on user link from a satellite module simulation.
class SatStatsUserPacketCollisionHelper
class SatStatsUserSlottedAlohaPacketCollisionHelper
Produce packet collision statistics of Random Access Slotted ALOHA from a satellite module simulation.
class SatStatsUserSlottedAlohaPacketErrorHelper
Produce packet error statistics of Random Access Slotted ALOHA on user link from a satellite module simulation.
class SatStatsWaveformUsageHelper
class SatStatsWindowLoadHelper
Abstract class inherited by SatStatsRtnFeederWindowLoadHelper.
class SatSuperframeAllocator
helper class for Satellite Beam Scheduler.
class SatSuperframeConf
This abstract class defines and implements interface of configuration for super frames.
class SatSuperframeConf0
This class implements super frame configuration 0.
class SatSuperframeConf1
This class implements super frame configuration 1.
class SatSuperframeConf2
This class implements sup.
class SatSuperframeConf3
This class implements super frame configuration 3.
class SatSuperframeConf4
This class implements super frame configuration 4.
class SatSuperframeSeq
This class implements super frame sequence.
class SatTbtpContainer
A container of received TBTPs.
class SatTbtpMessage
The packet for the Terminal Burst Time Plan (TBTP) messages.
class SatTimeSlotConf
This class implements configuration for time slots (for super frames / frames)
class SatTimeTag
Time tag used to identify the time when packet is enqueued at LLC level.
class SatTimuMessage
TIM unicast control message (Tagged by SatControlMsgTag with type value SAT_TIMU_CTRL_MSG)
class SatTracedInterference
Satellite traced interference.
class SatTracedMobilityModel
Satellite mobility model for which the current position change based on values read from a file.
class SatTrafficHelper
Creates pre-defined trafics.
class SatTypedefs
SatTypedefs class is for general typedefs used in satellite module.
class SatUplinkInfoTag
Tag to store uplink phy info that need to be forwarded to the downlink.
class SatUserHelper
Build a set of user nodes and links channels between user nodes and satellite nodes.
class SatUtHandoverModule
UT handover module.
class SatUtHelper
Creates needed objects for UT nodes like SatGeoNetDevice objects.
class SatUtils
SatUtils class is for general conversions used in satellite module.
class SatUtLlc
SatUtLlc holds the UT implementation of LLC layer.
class SatUtMac
UT specific Mac class for Sat Net Devices.
class SatUtMacState
Class handling UT Mac states and transitions.
class SatUtPhy
The SatUtPhy models the physical layer of the User Terminal of the satellite system.
class SatUtScheduler
The SatUtScheduler is responsible of getting a packet of proper size from higher protocol layer.
class SatWaveform
This class implements the content of one individual DVB-RCS2 waveform.
class SatWaveformConf
This class implements the available waveform configurations of DVB-RCS2 return link.
class SimulationHelper
A helper to make it easier to create example simulation cases.
class SimulationHelperConf
class SortByMetric
Sort metric which sorts a vector available RC indices based on "unallocated load".
class SortTimeSlots
This class sorts time slots within TBTP into increasing order based on start time.
class TxParamSetupAns
Implementation of the TxParamSetupAns LoRaWAN MAC command.
class TxParamSetupReq
Implementation of the TxParamSetupReq LoRaWAN MAC command.
Enumerations
enum MacCommandType {
INVALID , LINK_CHECK_REQ , LINK_CHECK_ANS , LINK_ADR_REQ ,
LINK_ADR_ANS , DUTY_CYCLE_REQ , DUTY_CYCLE_ANS , RX_PARAM_SETUP_REQ ,
RX_PARAM_SETUP_ANS , DEV_STATUS_REQ , DEV_STATUS_ANS , NEW_CHANNEL_REQ ,
NEW_CHANNEL_ANS , RX_TIMING_SETUP_REQ , RX_TIMING_SETUP_ANS , TX_PARAM_SETUP_REQ ,
TX_PARAM_SETUP_ANS , DL_CHANNEL_REQ , DL_CHANNEL_ANS
}
Enum for every possible command type.
Functions
ATTRIBUTE_HELPER_CPP (GeoCoordinate)
ATTRIBUTE_HELPER_HEADER (GeoCoordinate)
Vector3D CrossProduct (const Vector3D &v1, const Vector3D &v2)
Cross product of two Vector3D objects.
double DotProduct (const Vector3D &v1, const Vector3D &v2)
Dot product of two Vector3D objects.
void logonCallbackHelper (Ptr< SatNcc > ncc, Ptr< SatLowerLayerServiceConf > llsConf, Address utId, uint32_t satId, uint32_t beamId, Callback< void, uint32_t > setRaChannelCallback)
double Magnitude (const Vector3D &vector)
Magnitude of a Vector3D object.
double MagnitudeSquared (const Vector3D &vector)
The square of the magnitude of a Vector3D object.
Ptr< const AttributeChecker > MakeGeoCoordinateChecker (void)
bool operator!= (const Ptr< LoraLogicalChannel > &first, const Ptr< LoraLogicalChannel > &second)
Overload the != operator to compare different instances of the same LoraLogicalChannel.
Vector3D operator* (const Vector3D &vector, double scalar)
Multiplication between a Vector3D object and a scalar.
Vector3D operator* (double scalar, const Vector3D &vector)
Multiplication between a scalar and a Vector3D object.
Vector3D operator+ (const Vector3D &v1, const Vector3D &v2)
extensions to ns3::Vector3D to support additional operations
Vector3D operator- (const Vector3D &v1, const Vector3D &v2)
Subtraction of Vector3D objects.
std::ostream & operator<< (std::ostream &os, const GeoCoordinate &coordinate)
std::ostream & operator<< (std::ostream &os, const JulianDate &jd)
std::ostream & operator<< (std::ostream &os, const LoraDeviceAddress &address)
Operator overload to correctly handle logging when an address is passed as an argument.
std::ostream & operator<< (std::ostream &os, const LoraEndDeviceStatus &status)
std::ostream & operator<< (std::ostream &os, DateTime::TimeSystem ts)
std::ostream & operator<< (std::ostream &os, SatPhyRxCarrier::State s)
std::ostream & operator<< (std::ostream &os, SatPhyTx::State s)
bool operator== (const Ptr< LoraLogicalChannel > &first, const Ptr< LoraLogicalChannel > &second)
Overload of the == operator to compare different instances of the same LoraLogicalChannel.
std::istream & operator>> (std::istream &is, GeoCoordinate &coordinate)
SAT_STATS_GLOBAL_METHOD_DEFINITION (FeederSlottedAlohaPacketCollision, "feeder-slotted-aloha-collision") SAT_STATS_PER_GW_METHOD_DEFINITION(FeederSlottedAlohaPacketCollision
feeder slotted aloha collision SAT_STATS_PER_BEAM_METHOD_DEFINITION (FeederSlottedAlohaPacketCollision, "feeder-slotted-aloha-collision") SAT_STATS_PER_GROUP_METHOD_DEFINITION(FeederSlottedAlohaPacketCollision
feeder slotted aloha collision feeder slotted aloha collision feeder slotted aloha collision SAT_STATS_PER_BEAM_METHOD_DEFINITION (UserSlottedAlohaPacketCollision, "user-slotted-aloha-collision") SAT_STATS_PER_GROUP_METHOD_DEFINITION(UserSlottedAlohaPacketCollision
feeder slotted aloha collision feeder slotted aloha collision SAT_STATS_PER_UT_METHOD_DEFINITION (FeederSlottedAlohaPacketCollision, "feeder-slotted-aloha-collision") SAT_STATS_PER_SAT_METHOD_DEFINITION(FeederSlottedAlohaPacketCollision
Variables
ns3::LinkResultTestSuite g_linkResultTestSuite
static const double g_LooParameters [SatMarkovConf::DEFAULT_ELEVATION_COUNT][SatMarkovConf::DEFAULT_STATE_COUNT][SatLooConf::DEFAULT_LOO_PARAMETER_COUNT]
static const double g_MarkovElevationStateChangeProbabilities [SatMarkovConf::DEFAULT_ELEVATION_COUNT][SatMarkovConf::DEFAULT_STATE_COUNT][SatMarkovConf::DEFAULT_STATE_COUNT]
static const double g_MarkovInitialStateProbabilities [SatMarkovConf::DEFAULT_STATE_COUNT]
static const double g_RayleighParameters [SatMarkovConf::DEFAULT_ELEVATION_COUNT][SatMarkovConf::DEFAULT_STATE_COUNT][SatRayleighConf::DEFAULT_RAYLEIGH_PARAMETER_COUNT]
const uint32_t payloadConf [7][3]
1st col = modulated bits 2nd col = payload slots per normal frame 3rnd col = payload slots per short frame
Detailed Description
SatArqSequenceNumber is handling the sequence numbers for the ARQ process.
There may be a total of windowSize sequential sequence numbers in use simultaneously. If all of them are booked, then no new sequence numbers are available for new transmissions until some sequence numbers are released. Releasing may happen due to maximum retransmissions reached or received ACK. Sequence number is identified with one byte, thus it may range between 0 - 255.
Enumeration Type Documentation
MacCommandType
enum ns3::MacCommandType
Enum for every possible command type.
Enumerator
INVALID
LINK_CHECK_REQ
LINK_CHECK_ANS
LINK_ADR_REQ
LINK_ADR_ANS
DUTY_CYCLE_REQ
DUTY_CYCLE_ANS
RX_PARAM_SETUP_REQ
RX_PARAM_SETUP_ANS
DEV_STATUS_REQ
DEV_STATUS_ANS
NEW_CHANNEL_REQ
NEW_CHANNEL_ANS
RX_TIMING_SETUP_REQ
RX_TIMING_SETUP_ANS
TX_PARAM_SETUP_REQ
TX_PARAM_SETUP_ANS
DL_CHANNEL_REQ
DL_CHANNEL_ANS
Definition at line 36 of file lorawan-mac-command.h.
Function Documentation
ATTRIBUTE_HELPER_CPP()
ns3::ATTRIBUTE_HELPER_CPP (GeoCoordinate)
ATTRIBUTE_HELPER_HEADER()
ns3::ATTRIBUTE_HELPER_HEADER (GeoCoordinate)
CrossProduct()
Vector3D ns3::CrossProduct (const Vector3D & v1, const Vector3D & v2)
Cross product of two Vector3D objects.
Parameters
v1 The first vector.
v2 The second vector.
Returns
a vector that is the cross product of the two vectors.
Definition at line 57 of file vector-extensions.cc.
Referenced by ns3::SatSGP4MobilityModel::rvTemeTovItrf().
DotProduct()
double ns3::DotProduct (const Vector3D & v1, const Vector3D & v2)
Dot product of two Vector3D objects.
Parameters
v1 The first vector.
v2 The second vector.
Returns
a scalar that is the dot product of the two vectors.
Definition at line 65 of file vector-extensions.cc.
Referenced by Magnitude(), and MagnitudeSquared().
logonCallbackHelper()
void ns3::logonCallbackHelper (Ptr< SatNcc > ncc, Ptr< SatLowerLayerServiceConf > llsConf, Address utId, uint32_t satId, uint32_t beamId, Callback< void, uint32_t > setRaChannelCallback)
Definition at line 66 of file satellite-gw-helper.cc.
Referenced by ns3::SatGwHelper::InstallDvb().
Magnitude()
double ns3::Magnitude (const Vector3D & vector)
Magnitude of a Vector3D object.
Parameters
vector The vector.
Returns
a scalar that is the magnitude of the vector.
Definition at line 71 of file vector-extensions.cc.
References DotProduct().
MagnitudeSquared()
double ns3::MagnitudeSquared (const Vector3D & vector)
The square of the magnitude of a Vector3D object.
Parameters
vector The vector.
Returns
a scalar that is the square of the magnitude of the vector.
Definition at line 77 of file vector-extensions.cc.
References DotProduct().
MakeGeoCoordinateChecker()
Ptr<const AttributeChecker> ns3::MakeGeoCoordinateChecker (void)
Referenced by ns3::SatMobilityModel::GetTypeId().
operator!=()
bool ns3::operator!= (const Ptr< LoraLogicalChannel > & first, const Ptr< LoraLogicalChannel > & second)
Overload the != operator to compare different instances of the same LoraLogicalChannel.
Definition at line 133 of file lora-logical-channel.cc.
operator*() [1/2]
Vector3D ns3::operator* (const Vector3D & vector, double scalar)
Multiplication between a Vector3D object and a scalar.
Parameters
vector The vector.
scalar The scalar.
Returns
a vector that is the product of the vector by the scalar.
Definition at line 45 of file vector-extensions.cc.
operator*() [2/2]
Vector3D ns3::operator* (double scalar, const Vector3D & vector)
Multiplication between a scalar and a Vector3D object.
Parameters
scalar The scalar.
vector The vector.
Returns
a vector that is the product of the vector by the scalar.
Definition at line 51 of file vector-extensions.cc.
operator+()
Vector3D ns3::operator+ (const Vector3D & v1, const Vector3D & v2)
extensions to ns3::Vector3D to support additional operations
This file defines vector addition, vector difference, the product between a vector and a scalar, the cross product, the inner product, the magnitude, and the square of the magnitude.
Addition of Vector3D objects.
Parameters
v1 The first vector.
v2 The second vector.
Returns
a vector that is the sum of v1 and v2.
Definition at line 33 of file vector-extensions.cc.
operator-()
Vector3D ns3::operator- (const Vector3D & v1, const Vector3D & v2)
Subtraction of Vector3D objects.
Parameters
v1 The first vector.
v2 The second vector.
Returns
a vector that is the difference between v1 and v2.
Definition at line 39 of file vector-extensions.cc.
operator<<() [1/7]
std::ostream & ns3::operator<< (std::ostream & os, const GeoCoordinate & coordinate)
Definition at line 344 of file geo-coordinate.cc.
References ns3::GeoCoordinate::GetAltitude(), ns3::GeoCoordinate::GetLatitude(), and ns3::GeoCoordinate::GetLongitude().
operator<<() [2/7]
std::ostream& ns3::operator<< (std::ostream & os, const JulianDate & jd)
Print the textual representation (Gregorian calendar date) using the time system specified upon creation or setting.
Parameters
os Output stream object.
jd Julian date object.
Returns
the output stream.
Definition at line 388 of file julian-date.cc.
operator<<() [3/7]
std::ostream & ns3::operator<< (std::ostream & os, const LoraDeviceAddress & address)
Operator overload to correctly handle logging when an address is passed as an argument.
Definition at line 272 of file lora-device-address.cc.
References ns3::LoraDeviceAddress::Print().
operator<<() [4/7]
std::ostream& ns3::operator<< (std::ostream & os, const LoraEndDeviceStatus & status)
Definition at line 446 of file lora-end-device-status.cc.
operator<<() [5/7]
std::ostream& ns3::operator<< (std::ostream & os, DateTime::TimeSystem ts)
Definition at line 55 of file julian-date.cc.
operator<<() [6/7]
std::ostream& ns3::operator<< (std::ostream & os, SatPhyRxCarrier::State s)
Definition at line 267 of file satellite-phy-rx-carrier.cc.
References ns3::SatPhyRxCarrier::IDLE, and ns3::SatPhyRxCarrier::RX.
operator<<() [7/7]
std::ostream& ns3::operator<< (std::ostream & os, SatPhyTx::State s)
Definition at line 72 of file satellite-phy-tx.cc.
References ns3::SatPhyTx::IDLE, ns3::SatPhyTx::RECONFIGURING, and ns3::SatPhyTx::TX.
operator==()
bool ns3::operator== (const Ptr< LoraLogicalChannel > & first, const Ptr< LoraLogicalChannel > & second)
Overload of the == operator to compare different instances of the same LoraLogicalChannel.
Definition at line 120 of file lora-logical-channel.cc.
operator>>()
std::istream & ns3::operator>> (std::istream & is, GeoCoordinate & coordinate)
Definition at line 357 of file geo-coordinate.cc.
References ns3::GeoCoordinate::SetAltitude(), ns3::GeoCoordinate::SetLatitude(), and ns3::GeoCoordinate::SetLongitude().
SAT_STATS_GLOBAL_METHOD_DEFINITION()
ns3::SAT_STATS_GLOBAL_METHOD_DEFINITION (FeederSlottedAlohaPacketCollision , "feeder-slotted-aloha-collision")
SAT_STATS_PER_BEAM_METHOD_DEFINITION() [1/2]
feeder slotted aloha collision ns3::SAT_STATS_PER_BEAM_METHOD_DEFINITION (FeederSlottedAlohaPacketCollision , "feeder-slotted-aloha-collision")
SAT_STATS_PER_BEAM_METHOD_DEFINITION() [2/2]
feeder slotted aloha collision feeder slotted aloha collision feeder slotted aloha collision ns3::SAT_STATS_PER_BEAM_METHOD_DEFINITION (UserSlottedAlohaPacketCollision , "user-slotted-aloha-collision")
SAT_STATS_PER_UT_METHOD_DEFINITION()
feeder slotted aloha collision feeder slotted aloha collision ns3::SAT_STATS_PER_UT_METHOD_DEFINITION (FeederSlottedAlohaPacketCollision , "feeder-slotted-aloha-collision")
Variable Documentation
g_linkResultTestSuite
ns3::LinkResultTestSuite ns3::g_linkResultTestSuite static
g_LooParameters
const double ns3::g_LooParameters[SatMarkovConf::DEFAULT_ELEVATION_COUNT][SatMarkovConf::DEFAULT_STATE_COUNT][SatLooConf::DEFAULT_LOO_PARAMETER_COUNT] static
Initial value:
= {
        {{0.0, 0.5, -25.0, 10, 10, 2, 30},
         {-10.0, 3.0, -25.0, 10, 10, 2, 30},
         {-21.0, 4.0, -25.0, 10, 10, 2, 30}}}
Definition at line 33 of file satellite-loo-conf.cc.
Referenced by ns3::SatLooConf::SatLooConf().
g_MarkovElevationStateChangeProbabilities
const double ns3::g_MarkovElevationStateChangeProbabilities[SatMarkovConf::DEFAULT_ELEVATION_COUNT][SatMarkovConf::DEFAULT_STATE_COUNT][SatMarkovConf::DEFAULT_STATE_COUNT] static
Initial value:
= {
        {{0.9684, 0.0316, 0.0000}, {0.4155, 0.5845, 0.0000}, {0.0000, 0.0000, 0.0000}}}
Definition at line 33 of file satellite-markov-conf.cc.
Referenced by ns3::SatMarkovConf::SatMarkovConf().
g_MarkovInitialStateProbabilities
const double ns3::g_MarkovInitialStateProbabilities[SatMarkovConf::DEFAULT_STATE_COUNT] static
Initial value:
= {
    0.9293,
    0.0707,
    0.0000}
Definition at line 48 of file satellite-markov-conf.cc.
Referenced by ns3::SatMarkovConf::SatMarkovConf().
g_RayleighParameters
const double ns3::g_RayleighParameters[SatMarkovConf::DEFAULT_ELEVATION_COUNT][SatMarkovConf::DEFAULT_STATE_COUNT][SatRayleighConf::DEFAULT_RAYLEIGH_PARAMETER_COUNT] static
Initial value:
= {
                                            {{10, 10}, {10, 10}, {10, 10}}}
Definition at line 33 of file satellite-rayleigh-conf.cc.
Referenced by ns3::SatRayleighConf::SatRayleighConf().
payloadConf
const uint32_t ns3::payloadConf[7][3]
Initial value:
= {
    {2, 360, 90},
    {3, 240, 60},
    {4, 180, 45},
    {5, 144, 36},
    {6, 120, 30},
    {7, 102, 25},
    {8, 90, 22},
}
1st col = modulated bits 2nd col = payload slots per normal frame 3rnd col = payload slots per short frame
Definition at line 48 of file satellite-bbframe-conf.cc.
Referenced by ns3::SatBbFrameConf::SatBbFrameConf().