SNS3
sat-fwd-system-test-example.cc File Reference
Simulation script to execute system tests for the forward link.
#include "ns3/applications-module.h"
#include "ns3/config-store-module.h"
#include "ns3/core-module.h"
#include "ns3/internet-module.h"
#include "ns3/network-module.h"
#include "ns3/satellite-module.h"
#include "ns3/traffic-module.h"
Functions
static void PrintBbFrameInfo (Ptr< SatBbFrame > bbFrame)
static void PrintBbFrameMergeInfo (Ptr< SatBbFrame > mergeTo, Ptr< SatBbFrame > mergeFrom)
Detailed Description
Simulation script to execute system tests for the forward link.
To get help of the command line arguments for the example, execute command -> ./waf –run "sat-fwd-sys-test --PrintHelp"
Definition in file sat-fwd-system-test-example.cc.
Function Documentation
PrintBbFrameInfo()
static void PrintBbFrameInfo (Ptr< SatBbFrame > bbFrame) static
Definition at line 45 of file sat-fwd-system-test-example.cc.
References ns3::SatMacTag::GetDestAddress(), ns3::SatEnums::GetFrameTypeName(), and ns3::SatEnums::GetModcodTypeName().
Referenced by PrintBbFrameMergeInfo().
PrintBbFrameMergeInfo()
static void PrintBbFrameMergeInfo (Ptr< SatBbFrame > mergeTo, Ptr< SatBbFrame > mergeFrom) static
Definition at line 90 of file sat-fwd-system-test-example.cc.
References PrintBbFrameInfo().