SNS3
satellite-sgp4unit.cc File Reference
#include "satellite-sgp4unit.h"
Functions
static void dpper (double e3, double ee2, double peo, double pgho, double pho, double pinco, double plo, double se2, double se3, double sgh2, double sgh3, double sgh4, double sh2, double sh3, double si2, double si3, double sl2, double sl3, double sl4, double t, double xgh2, double xgh3, double xgh4, double xh2, double xh3, double xi2, double xi3, double xl2, double xl3, double xl4, double zmol, double zmos, double inclo, char init, double &ep, double &inclp, double &nodep, double &argpp, double &mp, char opsmode)
static void dscom (double epoch, double ep, double argpp, double tc, double inclp, double nodep, double np, double &snodm, double &cnodm, double &sinim, double &cosim, double &sinomm, double &cosomm, double &day, double &e3, double &ee2, double &em, double &emsq, double &gam, double &peo, double &pgho, double &pho, double &pinco, double &plo, double &rtemsq, double &se2, double &se3, double &sgh2, double &sgh3, double &sgh4, double &sh2, double &sh3, double &si2, double &si3, double &sl2, double &sl3, double &sl4, double &s1, double &s2, double &s3, double &s4, double &s5, double &s6, double &s7, double &ss1, double &ss2, double &ss3, double &ss4, double &ss5, double &ss6, double &ss7, double &sz1, double &sz2, double &sz3, double &sz11, double &sz12, double &sz13, double &sz21, double &sz22, double &sz23, double &sz31, double &sz32, double &sz33, double &xgh2, double &xgh3, double &xgh4, double &xh2, double &xh3, double &xi2, double &xi3, double &xl2, double &xl3, double &xl4, double &nm, double &z1, double &z2, double &z3, double &z11, double &z12, double &z13, double &z21, double &z22, double &z23, double &z31, double &z32, double &z33, double &zmol, double &zmos)
static void dsinit (gravconsttype whichconst, double cosim, double emsq, double argpo, double s1, double s2, double s3, double s4, double s5, double sinim, double ss1, double ss2, double ss3, double ss4, double ss5, double sz1, double sz3, double sz11, double sz13, double sz21, double sz23, double sz31, double sz33, double t, double tc, double gsto, double mo, double mdot, double no, double nodeo, double nodedot, double xpidot, double z1, double z3, double z11, double z13, double z21, double z23, double z31, double z33, double ecco, double eccsq, double &em, double &argpm, double &inclm, double &mm, double &nm, double &nodem, int &irez, double &atime, double &d2201, double &d2211, double &d3210, double &d3222, double &d4410, double &d4422, double &d5220, double &d5232, double &d5421, double &d5433, double &dedt, double &didt, double &dmdt, double &dndt, double &dnodt, double &domdt, double &del1, double &del2, double &del3, double &xfact, double &xlamo, double &xli, double &xni)
static void dspace (int irez, double d2201, double d2211, double d3210, double d3222, double d4410, double d4422, double d5220, double d5232, double d5421, double d5433, double dedt, double del1, double del2, double del3, double didt, double dmdt, double dnodt, double domdt, double argpo, double argpdot, double t, double tc, double gsto, double xfact, double xlamo, double no, double &atime, double &em, double &argpm, double &inclm, double &xli, double &mm, double &xni, double &nodem, double &dndt, double &nm)
void getgravconst (gravconsttype whichconst, double &tumin, double &mu, double &radiusearthkm, double &xke, double &j2, double &j3, double &j4, double &j3oj2)
double gstime (double jdut1)
static void initl (long int satn, gravconsttype whichconst, double ecco, double epoch, double inclo, double &no, char &method, double &ainv, double &ao, double &con41, double &con42, double &cosio, double &cosio2, double &eccsq, double &omeosq, double &posq, double &rp, double &rteosq, double &sinio, double &gsto, char opsmode)
bool sgp4 (gravconsttype whichconst, elsetrec &satrec, double tsince, double r[3], double v[3])
bool sgp4init (gravconsttype whichconst, char opsmode, const long int satn, const double epoch, const double xbstar, const double xecco, const double xargpo, const double xinclo, const double xmo, const double xno, const double xnodeo, elsetrec &satrec)
Function Documentation
dpper()
static void dpper (double e3, double ee2, double peo, double pgho, double pho, double pinco, double plo, double se2, double se3, double sgh2, double sgh3, double sgh4, double sh2, double sh3, double si2, double si3, double sl2, double sl3, double sl4, double t, double xgh2, double xgh3, double xgh4, double xh2, double xh3, double xi2, double xi3, double xl2, double xl3, double xl4, double zmol, double zmos, double inclo, char init, double & ep, double & inclp, double & nodep, double & argpp, double & mp, char opsmode) static
Definition at line 387 of file satellite-sgp4unit.cc.
References pi.
Referenced by sgp4(), and sgp4init().
dscom()
static void dscom (double epoch, double ep, double argpp, double tc, double inclp, double nodep, double np, double & snodm, double & cnodm, double & sinim, double & cosim, double & sinomm, double & cosomm, double & day, double & e3, double & ee2, double & em, double & emsq, double & gam, double & peo, double & pgho, double & pho, double & pinco, double & plo, double & rtemsq, double & se2, double & se3, double & sgh2, double & sgh3, double & sgh4, double & sh2, double & sh3, double & si2, double & si3, double & sl2, double & sl3, double & sl4, double & s1, double & s2, double & s3, double & s4, double & s5, double & s6, double & s7, double & ss1, double & ss2, double & ss3, double & ss4, double & ss5, double & ss6, double & ss7, double & sz1, double & sz2, double & sz3, double & sz11, double & sz12, double & sz13, double & sz21, double & sz22, double & sz23, double & sz31, double & sz32, double & sz33, double & xgh2, double & xgh3, double & xgh4, double & xh2, double & xh3, double & xi2, double & xi3, double & xl2, double & xl3, double & xl4, double & nm, double & z1, double & z2, double & z3, double & z11, double & z12, double & z13, double & z21, double & z22, double & z23, double & z31, double & z32, double & z33, double & zmol, double & zmos) static
Definition at line 608 of file satellite-sgp4unit.cc.
References pi.
Referenced by sgp4init().
dsinit()
static void dsinit (gravconsttype whichconst, double cosim, double emsq, double argpo, double s1, double s2, double s3, double s4, double s5, double sinim, double ss1, double ss2, double ss3, double ss4, double ss5, double sz1, double sz3, double sz11, double sz13, double sz21, double sz23, double sz31, double sz33, double t, double tc, double gsto, double mo, double mdot, double no, double nodeo, double nodedot, double xpidot, double z1, double z3, double z11, double z13, double z21, double z23, double z31, double z33, double ecco, double eccsq, double & em, double & argpm, double & inclm, double & mm, double & nm, double & nodem, int & irez, double & atime, double & d2201, double & d2211, double & d3210, double & d3222, double & d4410, double & d4422, double & d5220, double & d5232, double & d5421, double & d5433, double & dedt, double & didt, double & dmdt, double & dndt, double & dnodt, double & domdt, double & del1, double & del2, double & del3, double & xfact, double & xlamo, double & xli, double & xni) static
Definition at line 950 of file satellite-sgp4unit.cc.
References getgravconst(), and pi.
Referenced by sgp4init().
dspace()
static void dspace (int irez, double d2201, double d2211, double d3210, double d3222, double d4410, double d4422, double d5220, double d5232, double d5421, double d5433, double dedt, double del1, double del2, double del3, double didt, double dmdt, double dnodt, double domdt, double argpo, double argpdot, double t, double tc, double gsto, double xfact, double xlamo, double no, double & atime, double & em, double & argpm, double & inclm, double & xli, double & mm, double & xni, double & nodem, double & dndt, double & nm) static
Definition at line 1304 of file satellite-sgp4unit.cc.
References pi.
Referenced by sgp4().
getgravconst()
void getgravconst (gravconsttype whichconst, double & tumin, double & mu, double & radiusearthkm, double & xke, double & j2, double & j3, double & j4, double & j3oj2)
Definition at line 2683 of file satellite-sgp4unit.cc.
References wgs72, wgs72old, and wgs84.
Referenced by dsinit(), initl(), sgp4(), sgp4init(), and twoline2rv().
gstime()
double gstime (double jdut1)
Definition at line 2634 of file satellite-sgp4unit.cc.
References pi.
Referenced by ns3::JulianDate::GetGmst(), and initl().
initl()
static void initl (long int satn, gravconsttype whichconst, double ecco, double epoch, double inclo, double & no, char & method, double & ainv, double & ao, double & con41, double & con42, double & cosio, double & cosio2, double & eccsq, double & omeosq, double & posq, double & rp, double & rteosq, double & sinio, double & gsto, char opsmode) static
Definition at line 1524 of file satellite-sgp4unit.cc.
References getgravconst(), gstime(), and pi.
Referenced by sgp4init().
sgp4()
bool sgp4 (gravconsttype whichconst, elsetrec & satrec, double tsince, double r[3], double v[3])
Definition at line 2286 of file satellite-sgp4unit.cc.
References elsetrec::argpdot, elsetrec::argpo, elsetrec::atime, elsetrec::aycof, elsetrec::bstar, elsetrec::cc1, elsetrec::cc4, elsetrec::cc5, elsetrec::con41, elsetrec::d2, elsetrec::d2201, elsetrec::d2211, elsetrec::d3, elsetrec::d3210, elsetrec::d3222, elsetrec::d4, elsetrec::d4410, elsetrec::d4422, elsetrec::d5220, elsetrec::d5232, elsetrec::d5421, elsetrec::d5433, elsetrec::dedt, elsetrec::del1, elsetrec::del2, elsetrec::del3, elsetrec::delmo, elsetrec::didt, elsetrec::dmdt, elsetrec::dnodt, elsetrec::domdt, dpper(), dspace(), elsetrec::e3, elsetrec::ecco, elsetrec::ee2, elsetrec::error, elsetrec::eta, getgravconst(), elsetrec::gsto, elsetrec::inclo, elsetrec::irez, elsetrec::isimp, elsetrec::mdot, elsetrec::method, elsetrec::mo, elsetrec::no, elsetrec::nodecf, elsetrec::nodedot, elsetrec::nodeo, elsetrec::omgcof, elsetrec::operationmode, elsetrec::peo, elsetrec::pgho, elsetrec::pho, pi, elsetrec::pinco, elsetrec::plo, elsetrec::se2, elsetrec::se3, elsetrec::sgh2, elsetrec::sgh3, elsetrec::sgh4, elsetrec::sh2, elsetrec::sh3, elsetrec::si2, elsetrec::si3, elsetrec::sinmao, elsetrec::sl2, elsetrec::sl3, elsetrec::sl4, elsetrec::t, elsetrec::t2cof, elsetrec::t3cof, elsetrec::t4cof, elsetrec::t5cof, elsetrec::x1mth2, elsetrec::x7thm1, elsetrec::xfact, elsetrec::xgh2, elsetrec::xgh3, elsetrec::xgh4, elsetrec::xh2, elsetrec::xh3, elsetrec::xi2, elsetrec::xi3, elsetrec::xl2, elsetrec::xl3, elsetrec::xl4, elsetrec::xlamo, elsetrec::xlcof, elsetrec::xli, elsetrec::xmcof, elsetrec::xni, elsetrec::zmol, and elsetrec::zmos.
Referenced by ns3::SatSGP4MobilityModel::DoGetGeoPosition(), ns3::SatSGP4MobilityModel::DoGetVelocity(), ns3::SatSGP4MobilityModel::SetTleInfo(), and sgp4init().
sgp4init()
bool sgp4init (gravconsttype whichconst, char opsmode, const long int satn, const double epoch, const double xbstar, const double xecco, const double xargpo, const double xinclo, const double xmo, const double xno, const double xnodeo, elsetrec & satrec)
Definition at line 1693 of file satellite-sgp4unit.cc.
References elsetrec::argpdot, elsetrec::argpo, elsetrec::atime, elsetrec::aycof, elsetrec::bstar, elsetrec::cc1, elsetrec::cc4, elsetrec::cc5, elsetrec::con41, elsetrec::d2, elsetrec::d2201, elsetrec::d2211, elsetrec::d3, elsetrec::d3210, elsetrec::d3222, elsetrec::d4, elsetrec::d4410, elsetrec::d4422, elsetrec::d5220, elsetrec::d5232, elsetrec::d5421, elsetrec::d5433, elsetrec::dedt, elsetrec::del1, elsetrec::del2, elsetrec::del3, elsetrec::delmo, elsetrec::didt, elsetrec::dmdt, elsetrec::dnodt, elsetrec::domdt, dpper(), dscom(), dsinit(), elsetrec::e3, elsetrec::ecco, elsetrec::ee2, elsetrec::error, elsetrec::eta, getgravconst(), elsetrec::gsto, elsetrec::inclo, elsetrec::init, initl(), elsetrec::irez, elsetrec::isimp, elsetrec::mdot, elsetrec::method, elsetrec::mo, elsetrec::no, elsetrec::nodecf, elsetrec::nodedot, elsetrec::nodeo, elsetrec::omgcof, elsetrec::operationmode, elsetrec::peo, elsetrec::pgho, elsetrec::pho, pi, elsetrec::pinco, elsetrec::plo, elsetrec::se2, elsetrec::se3, elsetrec::sgh2, elsetrec::sgh3, elsetrec::sgh4, sgp4(), elsetrec::sh2, elsetrec::sh3, elsetrec::si2, elsetrec::si3, elsetrec::sinmao, elsetrec::sl2, elsetrec::sl3, elsetrec::sl4, elsetrec::t, elsetrec::t2cof, elsetrec::t3cof, elsetrec::t4cof, elsetrec::t5cof, elsetrec::x1mth2, elsetrec::x7thm1, elsetrec::xfact, elsetrec::xgh2, elsetrec::xgh3, elsetrec::xgh4, elsetrec::xh2, elsetrec::xh3, elsetrec::xi2, elsetrec::xi3, elsetrec::xl2, elsetrec::xl3, elsetrec::xl4, elsetrec::xlamo, elsetrec::xlcof, elsetrec::xli, elsetrec::xmcof, elsetrec::xni, elsetrec::zmol, and elsetrec::zmos.
Referenced by twoline2rv().