SNS3
satellite-sgp4io.h File Reference
#include "satellite-sgp4ext.h"
#include "satellite-sgp4unit.h"
#include <math.h>
#include <stdio.h>
Functions
void twoline2rv (char longstr1[130], char longstr2[130], char typerun, char typeinput, char opsmode, gravconsttype whichconst, double &startmfe, double &stopmfe, double &deltamin, elsetrec &satrec)
Function Documentation
twoline2rv()
void twoline2rv (char longstr1[130], char longstr2[130], char typerun, char typeinput, char opsmode, gravconsttype whichconst, double & startmfe, double & stopmfe, double & deltamin, elsetrec & satrec)
Definition at line 71 of file satellite-sgp4io.cc.
References elsetrec::a, elsetrec::alta, elsetrec::altp, elsetrec::argpo, elsetrec::bstar, days2mdhms(), elsetrec::ecco, elsetrec::epochdays, elsetrec::epochyr, elsetrec::error, getgravconst(), elsetrec::inclo, jday(), elsetrec::jdsatepoch, elsetrec::mo, elsetrec::nddot, elsetrec::ndot, elsetrec::no, elsetrec::nodeo, pi, elsetrec::satnum, and sgp4init().
Referenced by ns3::SatSGP4MobilityModel::SetTleInfo().