SNS3
satellite-sgp4ext.cc File Reference
#include "satellite-sgp4ext.h"
Functions
double angle (double vec1[3], double vec2[3])
void cross (double vec1[3], double vec2[3], double outvec[3])
void days2mdhms (int year, double days, int &mon, int &day, int &hr, int &minute, double &sec)
double dot (double x[3], double y[3])
void invjday (double jd, int &year, int &mon, int &day, int &hr, int &minute, double &sec)
void jday (int year, int mon, int day, int hr, int minute, double sec, double &jd)
double mag (double x[3])
void newtonnu (double ecc, double nu, double &e0, double &m)
void rv2coe (double r[3], double v[3], double mu, double &p, double &a, double &ecc, double &incl, double &omega, double &argp, double &nu, double &m, double &arglat, double &truelon, double &lonper)
double sgn (double x)
Function Documentation
angle()
double angle (double vec1[3], double vec2[3])
Definition at line 152 of file satellite-sgp4ext.cc.
References dot(), mag(), and sgn().
Referenced by rv2coe().
cross()
void cross (double vec1[3], double vec2[3], double outvec[3])
Definition at line 91 of file satellite-sgp4ext.cc.
Referenced by rv2coe().
days2mdhms()
void days2mdhms (int year, double days, int & mon, int & day, int & hr, int & minute, double & sec)
Definition at line 596 of file satellite-sgp4ext.cc.
Referenced by invjday(), and twoline2rv().
dot()
double dot (double x[3], double y[3])
Definition at line 122 of file satellite-sgp4ext.cc.
Referenced by angle(), and rv2coe().
invjday()
void invjday (double jd, int & year, int & mon, int & day, int & hr, int & minute, double & sec)
Definition at line 666 of file satellite-sgp4ext.cc.
References days2mdhms().
jday()
void jday (int year, int mon, int day, int hr, int minute, double sec, double & jd)
Definition at line 551 of file satellite-sgp4ext.cc.
Referenced by twoline2rv().
mag()
double mag (double x[3])
Definition at line 63 of file satellite-sgp4ext.cc.
Referenced by angle(), and rv2coe().
newtonnu()
void newtonnu (double ecc, double nu, double & e0, double & m)
Definition at line 235 of file satellite-sgp4ext.cc.
References pi.
Referenced by rv2coe().
rv2coe()
void rv2coe (double r[3], double v[3], double mu, double & p, double & a, double & ecc, double & incl, double & omega, double & argp, double & nu, double & m, double & arglat, double & truelon, double & lonper)
Definition at line 345 of file satellite-sgp4ext.cc.
References angle(), cross(), dot(), mag(), newtonnu(), pi, and sgn().
sgn()
double sgn (double x)
Definition at line 28 of file satellite-sgp4ext.cc.
Referenced by angle(), and rv2coe().