SNS3
satellite-per-packet-if-test.cc File Reference
System test cases for Satellite Per-Packet Interference Model.
#include "ns3/applications-module.h"
#include "ns3/boolean.h"
#include "ns3/config.h"
#include "ns3/log.h"
#include "ns3/satellite-module.h"
#include "ns3/simulator.h"
#include "ns3/singleton.h"
#include "ns3/string.h"
#include "ns3/test.h"
#include "ns3/timer.h"
#include "ns3/traffic-module.h"
#include <iomanip>
Classes
class SatPerPacketBaseTestCase
class SatPerPacketFwdLinkFullTestCase
class SatPerPacketFwdLinkUserTestCase
class SatPerPacketIfTestSuite
Test suite for Satellite interference unit test cases.
class SatPerPacketRtnLinkFullTestCase
class SatPerPacketRtnLinkUserTestCase
Functions
static void LinkBudgetTraceCb (std::string context, Ptr< SatSignalParameters > params, Mac48Address ownAdd, Mac48Address destAdd, double ifPower, double cSinr)
Variables
static const char * defFwdFullName
Per-packet interference, Forward Link System test case.
static const char * defFwdUserName
Per-packet interference, Forward Link System test case.
static const char * defRtnFullName
static const char * defRtnUserName
Per-packet interference, Return Link System test case.
static SatPerPacketIfTestSuite satSatPerPacketIfTestSuite
Detailed Description
System test cases for Satellite Per-Packet Interference Model.
Definition in file satellite-per-packet-if-test.cc.
Function Documentation
LinkBudgetTraceCb()
static void LinkBudgetTraceCb (std::string context, Ptr< SatSignalParameters > params, Mac48Address ownAdd, Mac48Address destAdd, double ifPower, double cSinr) static
Definition at line 45 of file satellite-per-packet-if-test.cc.
References ns3::SatEnums::GetChannelTypeName().
Referenced by SatPerPacketFwdLinkUserTestCase::DoRun(), SatPerPacketFwdLinkFullTestCase::DoRun(), SatPerPacketRtnLinkUserTestCase::DoRun(), and SatPerPacketRtnLinkFullTestCase::DoRun().
Variable Documentation
defFwdFullName
const char* defFwdFullName static
Initial value:
=
    "Test satellite per packet interference in Forward Link with fullscenario. "
Per-packet interference, Forward Link System test case.
Full scenario created without fading and dummy frame sending.
Pre-conditions: Network is configured to use only one carrier in forward link. Per-packet interference is configured on for forward link.
This case tests per-packet interference in forward link with full or user defined scenario.
Full test scenario set with helper.
User Node-1 sends packets continuously, transmitting constant bitrate (CBR) to user Node-3.
User Node-2 sends short packets with e.g. 100ms delay between packets to user Node-4.
Expected result: UT serving Node-3 should see interference only in some of the received packet (when Node-2 is sending). UT serving Node-4 should see inference in every packet it receives.
Notes: Node-1 and Node-2 are attached to different IP router (different GW nodes) and Node-3 and Node-4 are attached to different UT nodes. Node-1 and Node-2 must be selected from different beams, so that packet sending happens in same channel at least in feeder or user link.
Definition at line 408 of file satellite-per-packet-if-test.cc.
defFwdUserName
const char* defFwdUserName static
Initial value:
=
    "Test satellite per packet interference in Forward Link with user defined scenario. "
Per-packet interference, Forward Link System test case.
User defined scenario created without fading and dummy frame sending.
Pre-conditions: Network is configured to use only one carrier in forward link. Per-packet interference is configured on for forward link.
This case tests per-packet interference in forward link with full or user defined scenario.
User-defined test scenario set with helper.
User Node-1 sends packets continuously, transmitting constant bitrate (CBR) to user Node-3.
User Node-2 sends short packets with e.g. 100ms delay between packets to user Node-4.
Expected result: UT serving Node-3 should see interference only in some of the received packet (when Node-2 is sending). UT serving Node-4 should see inference in every packet it receives.
Notes: Node-1 and Node-2 are attached to different IP router (different GW nodes) and Node-3 and Node-4 are attached to different UT nodes. Node-1 and Node-2 must be selected from different beams, so that packet sending happens in same channel at least in feeder or user link.
Definition at line 208 of file satellite-per-packet-if-test.cc.
defRtnFullName
const char* defRtnFullName static
Initial value:
=
    "Test satellite per packet interference in Return Link with full defined scenario. "
Definition at line 761 of file satellite-per-packet-if-test.cc.
defRtnUserName
const char* defRtnUserName static
Initial value:
=
    "Test satellite per packet interference in Return Link with user defined scenario. "
Per-packet interference, Return Link System test case.
Pre-conditions: Network is configured to use only one carrier in return link. Per-packet interference is configured on for return link.
This case tests per-packet interference in return link with full or user defined scenario.
Full or user-defined test scenario set with helper.
User Node-3 sends packets continuously, transmitting constant bitrate (CBR) to user Node-1.
User Node-4 sends short packets with e.g. 100ms delay between packets to user Node-2.
Expected result: GW serving Node-1 should see interference only in some of the received packet (when Node-4 is sending). GW serving Node-2 should see inference in every packet it receives.
Notes: Node-1 and Node-2 are attached to IP router (different GW nodes) and Node-3 and Node-4 are attached to different UT nodes. Node-1 and Node-2 must be selected from different beams, so that packet sending happens in same channel at least in user or feeder link.
Definition at line 596 of file satellite-per-packet-if-test.cc.
satSatPerPacketIfTestSuite
SatPerPacketIfTestSuite satSatPerPacketIfTestSuite static
Definition at line 955 of file satellite-per-packet-if-test.cc.