SNS3
satellite-sgp4unit.h File Reference
#include <math.h>
#include <stdio.h>
Classes
struct elsetrec
Macros
#define pi 3.14159265358979323846
#define SGP4Version "SGP4 Version 2011-12-30"
Enumerations
enum gravconsttype { wgs72old , wgs72 , wgs84 }
Functions
void getgravconst (gravconsttype whichconst, double &tumin, double &mu, double &radiusearthkm, double &xke, double &j2, double &j3, double &j4, double &j3oj2)
double gstime (double jdut1)
bool sgp4 (gravconsttype whichconst, elsetrec &satrec, double tsince, double r[3], double v[3])
bool sgp4init (gravconsttype whichconst, char opsmode, const long int satn, const double epoch, const double xbstar, const double xecco, const double xargpo, const double xinclo, const double xmo, const double xno, const double xnodeo, elsetrec &satrec)
Macro Definition Documentation
pi
#define pi 3.14159265358979323846
Definition at line 59 of file satellite-sgp4unit.h.
SGP4Version
#define SGP4Version "SGP4 Version 2011-12-30"
Definition at line 57 of file satellite-sgp4unit.h.
Enumeration Type Documentation
gravconsttype
enum gravconsttype
Enumerator
wgs72old
wgs72
wgs84
Definition at line 62 of file satellite-sgp4unit.h.
Function Documentation
getgravconst()
void getgravconst (gravconsttype whichconst, double & tumin, double & mu, double & radiusearthkm, double & xke, double & j2, double & j3, double & j4, double & j3oj2)
Definition at line 2683 of file satellite-sgp4unit.cc.
References wgs72, wgs72old, and wgs84.
Referenced by dsinit(), initl(), sgp4(), sgp4init(), and twoline2rv().
gstime()
double gstime (double jdut1)
Definition at line 2634 of file satellite-sgp4unit.cc.
References pi.
Referenced by ns3::JulianDate::GetGmst(), and initl().
sgp4()
bool sgp4 (gravconsttype whichconst, elsetrec & satrec, double tsince, double r[3], double v[3])
Definition at line 2286 of file satellite-sgp4unit.cc.
References elsetrec::argpdot, elsetrec::argpo, elsetrec::atime, elsetrec::aycof, elsetrec::bstar, elsetrec::cc1, elsetrec::cc4, elsetrec::cc5, elsetrec::con41, elsetrec::d2, elsetrec::d2201, elsetrec::d2211, elsetrec::d3, elsetrec::d3210, elsetrec::d3222, elsetrec::d4, elsetrec::d4410, elsetrec::d4422, elsetrec::d5220, elsetrec::d5232, elsetrec::d5421, elsetrec::d5433, elsetrec::dedt, elsetrec::del1, elsetrec::del2, elsetrec::del3, elsetrec::delmo, elsetrec::didt, elsetrec::dmdt, elsetrec::dnodt, elsetrec::domdt, dpper(), dspace(), elsetrec::e3, elsetrec::ecco, elsetrec::ee2, elsetrec::error, elsetrec::eta, getgravconst(), elsetrec::gsto, elsetrec::inclo, elsetrec::irez, elsetrec::isimp, elsetrec::mdot, elsetrec::method, elsetrec::mo, elsetrec::no, elsetrec::nodecf, elsetrec::nodedot, elsetrec::nodeo, elsetrec::omgcof, elsetrec::operationmode, elsetrec::peo, elsetrec::pgho, elsetrec::pho, pi, elsetrec::pinco, elsetrec::plo, elsetrec::se2, elsetrec::se3, elsetrec::sgh2, elsetrec::sgh3, elsetrec::sgh4, elsetrec::sh2, elsetrec::sh3, elsetrec::si2, elsetrec::si3, elsetrec::sinmao, elsetrec::sl2, elsetrec::sl3, elsetrec::sl4, elsetrec::t, elsetrec::t2cof, elsetrec::t3cof, elsetrec::t4cof, elsetrec::t5cof, elsetrec::x1mth2, elsetrec::x7thm1, elsetrec::xfact, elsetrec::xgh2, elsetrec::xgh3, elsetrec::xgh4, elsetrec::xh2, elsetrec::xh3, elsetrec::xi2, elsetrec::xi3, elsetrec::xl2, elsetrec::xl3, elsetrec::xl4, elsetrec::xlamo, elsetrec::xlcof, elsetrec::xli, elsetrec::xmcof, elsetrec::xni, elsetrec::zmol, and elsetrec::zmos.
Referenced by ns3::SatSGP4MobilityModel::DoGetGeoPosition(), ns3::SatSGP4MobilityModel::DoGetVelocity(), ns3::SatSGP4MobilityModel::SetTleInfo(), and sgp4init().
sgp4init()
bool sgp4init (gravconsttype whichconst, char opsmode, const long int satn, const double epoch, const double xbstar, const double xecco, const double xargpo, const double xinclo, const double xmo, const double xno, const double xnodeo, elsetrec & satrec)
Definition at line 1693 of file satellite-sgp4unit.cc.
References elsetrec::argpdot, elsetrec::argpo, elsetrec::atime, elsetrec::aycof, elsetrec::bstar, elsetrec::cc1, elsetrec::cc4, elsetrec::cc5, elsetrec::con41, elsetrec::d2, elsetrec::d2201, elsetrec::d2211, elsetrec::d3, elsetrec::d3210, elsetrec::d3222, elsetrec::d4, elsetrec::d4410, elsetrec::d4422, elsetrec::d5220, elsetrec::d5232, elsetrec::d5421, elsetrec::d5433, elsetrec::dedt, elsetrec::del1, elsetrec::del2, elsetrec::del3, elsetrec::delmo, elsetrec::didt, elsetrec::dmdt, elsetrec::dnodt, elsetrec::domdt, dpper(), dscom(), dsinit(), elsetrec::e3, elsetrec::ecco, elsetrec::ee2, elsetrec::error, elsetrec::eta, getgravconst(), elsetrec::gsto, elsetrec::inclo, elsetrec::init, initl(), elsetrec::irez, elsetrec::isimp, elsetrec::mdot, elsetrec::method, elsetrec::mo, elsetrec::no, elsetrec::nodecf, elsetrec::nodedot, elsetrec::nodeo, elsetrec::omgcof, elsetrec::operationmode, elsetrec::peo, elsetrec::pgho, elsetrec::pho, pi, elsetrec::pinco, elsetrec::plo, elsetrec::se2, elsetrec::se3, elsetrec::sgh2, elsetrec::sgh3, elsetrec::sgh4, sgp4(), elsetrec::sh2, elsetrec::sh3, elsetrec::si2, elsetrec::si3, elsetrec::sinmao, elsetrec::sl2, elsetrec::sl3, elsetrec::sl4, elsetrec::t, elsetrec::t2cof, elsetrec::t3cof, elsetrec::t4cof, elsetrec::t5cof, elsetrec::x1mth2, elsetrec::x7thm1, elsetrec::xfact, elsetrec::xgh2, elsetrec::xgh3, elsetrec::xgh4, elsetrec::xh2, elsetrec::xh3, elsetrec::xi2, elsetrec::xi3, elsetrec::xl2, elsetrec::xl3, elsetrec::xl4, elsetrec::xlamo, elsetrec::xlcof, elsetrec::xli, elsetrec::xmcof, elsetrec::xni, elsetrec::zmol, and elsetrec::zmos.
Referenced by twoline2rv().