SNS3
satellite-mobility-test.cc File Reference
Test cases to unit test Satellite Mobility.
#include "../model/satellite-mobility-model.h"
#include "../model/satellite-position-allocator.h"
#include "../utils/satellite-env-variables.h"
#include "ns3/boolean.h"
#include "ns3/config.h"
#include "ns3/log.h"
#include "ns3/mobility-helper.h"
#include "ns3/simulator.h"
#include "ns3/singleton.h"
#include "ns3/string.h"
#include "ns3/test.h"
#include <iostream>
Classes
class SatMobilityList1TestCase
Test case to unit test satellite mobility's position setting from list position allocator.
class SatMobilityList2TestCase
Test case to unit test satellite mobility's position setting from list position allocator.
class SatMobilityRandomTestCase
Test case to unit test satellite mobility's position setting from random box position allocator.
class SatMobilityTestSuite
Test suite for Satellite mobility unit test cases.
Functions
static void SatCourseChange (std::string context, Ptr< const SatMobilityModel > position)
Variables
static SatMobilityTestSuite satSatMobilityTestSuite
Detailed Description
Test cases to unit test Satellite Mobility.
Definition in file satellite-mobility-test.cc.
Function Documentation
SatCourseChange()
static void SatCourseChange (std::string context, Ptr< const SatMobilityModel > position) static
Definition at line 46 of file satellite-mobility-test.cc.
References ns3::GeoCoordinate::GetAltitude(), ns3::GeoCoordinate::GetLatitude(), ns3::GeoCoordinate::GetLongitude(), and ns3::GeoCoordinate::ToVector().
Referenced by SatMobilityRandomTestCase::DoRun().
Variable Documentation
satSatMobilityTestSuite
SatMobilityTestSuite satSatMobilityTestSuite static
Definition at line 348 of file satellite-mobility-test.cc.